### ISSUE TITLE
Disable logs printed by SLF4J (FileUtils)

### ISSUE THREAD

**Issue by iamporus** [oshi/oshi#1011]
Some of the functions inside FileUtils print logs while reading files from the system. I tried but couldn't figure out a way to disable those logs. 
I tried writing a configuration for SLF4J in my app but couldn't get it to work.

**Comment by dbwiddis** [comment]
You should just be able to set the log level for the `FileUtil` class to a level higher than the messages, and it will suppress them.  As far as configuration, slf4j is just a facade, you actually need to configure whatever logger you are using to implement slf4j.  Can you share more details about how you are configuring it?
