### ISSUE TITLE
WindowsUsbDevice#getControllerDeviceIdList is not thread safe

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1015]
I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to open source before. This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. :-) 

As noted in [this report](https://scrutinizer-ci.com/g/oshi/oshi/issues/master/files/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsUsbDevice.java?selectedLabels%5B0%5D=37&orderField=path&order=asc&honorSelectedPaths=0&issueId=40218079#inspectioncomment-136359521), the lazy initialization of a list in `WindowsUSBDevice` is not thread safe.  If two threads call `getUsbDevices()` simultaneously they could both pass the `null` check and then both attempt to modify the same variable.

Create a thread-safe lazy initialization using OSHI's `Memoizer` class.

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- In the [`WindowsUsbDevice`](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsUsbDevice.java) class:
  - Modify the [`getControllerDeviceIdList()`](https://github.com/oshi/oshi/blob/31858912752ada0e0ceb43b43196ed1409601b96/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsUsbDevice.java#L309) method to take no arguments.  Inside the method, get the `wmiQueryHandler` by [copying from line 136](https://github.com/oshi/oshi/blob/31858912752ada0e0ceb43b43196ed1409601b96/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsUsbDevice.java#L136).  
  - Also remove the `if (controllerDeviceIds == null)` conditional 
  - Redefine that `controllerDeviceIds` variable with a differently named local variable in the method. 
  - Replace the static class variable with a memoized supplier: `private static Supplier<List<String>> controllerDeviceIds = Memoizer
            .memoize(WindowsUsbDevice::getControllerDeviceIdList);`
  - In the [`getUsbDevices()` method](https://github.com/oshi/oshi/blob/31858912752ada0e0ceb43b43196ed1409601b96/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsUsbDevice.java#L137) instead of calling the old method, instead fetch from the memoizer: `List<String> controllerDeviceIdList = controllerDeviceIds.get();`
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

**Comment by DanielMK01** [comment]
Hi, I have never contributed to a project before. Can I try this out?

**Comment by dbwiddis** [comment]
You certainly may!

**Comment by DanielMK01** [comment]
I have a question about a compiling error. I just downloaded the repository onto my device, as well as the most recent versions of jGrasp and Java. When I tried to compile the code, I received many error messages along the lines of "ParseUtil.java:40: error: package org.slf4j does not exist" and other similar errors. Did I clone the project incorrectly? Sorry, I'm really a beginner to Git and open-source projects.

**Comment by dbwiddis** [comment]
The project has a few dependencies, particularly `slf4j` (and whatever logging framework you want to use) and `jna`/`jna-platform`.  These are described in the `pom.xml` file which is used by the [Maven dependency manager](https://maven.apache.org/).

I'm not familiar with jGrasp, as I use Eclipse, but see if the documentation mentions Maven integration.

**Comment by DanielMK01** [comment]
I see. Thank you for the clarification!

**Comment by dbwiddis** [comment]
If you can't use Maven you can also download the `jar` files for all the dependencies and put them in a library where you add them as dependencies on the classpath.  However, it's probably well worth your effort to try to set up an IDE that uses Maven.  (Or Gradle or other dependency managers.)

**Comment by DanielMK01** [comment]
Thanks! I decided to go download Eclipse just for the benefit of standardization.

**Comment by dbwiddis** [comment]
[This SO answer](https://stackoverflow.com/a/36242422/1161484) is helpful.

Also you'll want to set up your editing format to match OSHI's.  We use the "Sun Java Conventions" except with 4 space indent instead of tabs.  You can import the formatting conventions [from here](https://github.com/oshi/oshi/tree/master/oshi-dist/src/main/resources/eclipse).

**Comment by DanielMK01** [comment]
Hi, I have just committed the changes and pushed them to my fork. I am a little confused about how to create a pull request. Can you walk me through that process?

**Comment by dbwiddis** [comment]
Go to [your github site](https://github.com/DanielMK01/oshi).  Look for where it says "This branch is 1 commit ahead of oshi:master."  To the right of that is a button to create a pull request.

**Comment by DanielMK01** [comment]
I've submitted the pull request. Thank you for all the help!

**Comment by dbwiddis** [comment]
Great job!  Now for the code review!
