### ISSUE TITLE
Wrong PhysicalMemory on some OS

### ISSUE THREAD

**Issue by suchorski** [oshi/oshi#1021]
I noted some issue when tyring to get the Physical Ram

I got: [main] WARN oshi.util.platform.windows.WmiQueryHandler - COM exception: Invalid
Query: SELECT BANKLABEL,CAPACITY,CONFIGUREDCLOCKSPEED,MANUFACTURER,SMBIOSMEMORYT
YPE FROM Win32_PhysicalMemory

The code was:
```
long ram = 0;
PhysicalMemory[] pm = new SystemInfo().getHardware().getMemory().getPhysicalMemory();
for (int i = 0; i < pm.length; ++i) {
	ram += pm[i].getCapacity();
	System.out.println(pm[i].getCapacity());
}
System.out.println(FormatUtil.formatBytes(ram));
```

Error OSs: Windows 7 SP1 (32 and 64 bits), Windows 8.1 (64 bits) and Windows XP (all using Java 8.121 32 bits)
Working OSs: Windows 10 (64 bits) (using Java 8.121 32 bits and Java 8.221 64 bits)

**Comment by suchorski** [comment]
Does't have on OS before Windows 10 :)

SMBIOSMemoryType

    Data type: uint32

    Access type: Read-only

    Qualifiers: MappingStrings ("SMBIOS|Type 17|Memory_Type")

    The raw SMBIOS memory type. The value of the MemoryType property is a CIM value that is mapped to the SMBIOS value.

    Windows Server 2012 R2, Windows 8.1, Windows Server 2012, Windows 8, Windows Server 2008 R2, Windows 7, Windows Server 2008 and Windows Vista: This property is not supported before Windows Server 2016 and Windows 10.

**Comment by suchorski** [comment]
I'm sorry, but I'm new to git commiting. I'll try to make this and my other one change. Thanks

**Comment by suchorski** [comment]
Others that is minimum from windows 10: ConfiguredClockSpeed

**Comment by dbwiddis** [comment]
Oops.  Looks like we can fall back (on pre-Win10) to the MemoryType field for type and the Speed field for clock speed, although it appears it's in units of nanoseconds, so we'll need to confirm that and perform the conversion.

**Comment by dbwiddis** [comment]
@suchorski Did you want to submit a PR for this yourself? I'm happy to make the fix but you sounded like you wanted to do it. :)
