### ISSUE TITLE
Wrong temperature on Raspberry Pi

### ISSUE THREAD

**Issue by jtreml** [oshi/oshi#1023]
I'm using OSHI on a Raspberry Pi 4.
Reading CPU temperature worked correctly until I added a DS18B20 temperature sensor over the 1-wire interface.
Now OSHI picks up this sensor's value as the CPU temperature.

All other tools and `vcgencmd measure_temp` continue to work just fine and show the correct CPU temperature, but OSHI somehow picks the wrong sensor (under `/sys/bus/w1/devices/28-xxxxxxxx/w1_slave`)

Any ideas where the issue might be?

**Comment by jtreml** [comment]
Looking through the code and also #347 it seems the issue is that OSHI checks /sys/class/hwmon/hwmon0 first and takes that if it exists.

Unfortunately the DS18B20 external sensor is getting mapped to that.

**Comment by dbwiddis** [comment]
Updated the code to try vcgencmd once and prefer it if it got results.
