### ISSUE TITLE
Can OSHI show process threads similar to Windows Task Manager?

### ISSUE THREAD

**Issue by dawzhang** [oshi/oshi#1027]
such as use chrome,  windows task manager show 10 chrome process, but oshi getProcesses() only show 1 .

**Comment by dbwiddis** [comment]
There's actually only one Chrome process.  The rest of the Chrome "processes" you see on Task Manager are actually threads.

You may notice on Task manager that the statistics for the parent process CPU is the sum of the CPU of the subordinate threads.

OSHI doesn't (yet) expose all the thread details, but it may be a useful future addition.

**Comment by tausiflife** [comment]
Hi, Can i work on this?

**Comment by dbwiddis** [comment]
Absolutely! What plan do you have for implementing it?

**Comment by tausiflife** [comment]
Thanks. My plan is to implement this in a step by step manner for each OS starting with Linux. 
I think that i can get the thread details of a process for Linux systems from /proc/{processid}/task/ directory. I want to add a method in `OSProcess.java` named `getThreadDetails` to expose the details. I haven't thought much about displaying the results in OshiGUI yet. 

This is the first time i am trying to contribute a functionality to opensource. Please bear with me if i have not answered your question correctly. Also i would like to listen to your ideas about this.

**Comment by dbwiddis** [comment]
OK, great, that sounds like a good direction to start.  I like to start by defining the top level API which you have with `getThreadDetails` as the method.  Now to identify what details are available!

It would be good to look at WIndows, at least, to try to identify the direction you're going to go as you design the API.  It looks like the CreateToolhelp32Snapshot along with the Thread32First and Thread32Next functions can iterate that list similar to how we do processes, you would just have to filter for process ID.  Good to see what stats that API exposes that match the same in Linux.

**Comment by tausiflife** [comment]
sure. I will have a look at it as well.

**Comment by dbwiddis** [comment]
Great, looking forward to it!  

One other implementation detail: please try to put as much of the actual implementation code in the `oshi.driver` package structure.  The main implementation methods will be short, calling out to these other packages.

I haven't gone through all existing code to move things there yet (it's more of a move-while-fixing) I do want to try to put new code there to start.   This will enable more modularity in the future (e.g., JDK9+ has some methods such as iterating `ProcessHandles` that may be more efficient at some of the things OSHI does (directory list) and we could substitute one of those drivers in a multi-release JAR).

**Comment by tausiflife** [comment]
I have started adding implementation `oshi.driver` package. One of the thing that i wanted to discuss is about the threads details. As threads are light weight processes, the information that is present inside `/proc/{processID}/task/{threadID}/` is similar to what is present in the `/proc/{processID}/`. What all information do you think are necessary to retrieve for a thread? 
Also thanks for the suggestion regarding Windows. Helped me a lot to to move ahead.

**Comment by dbwiddis** [comment]
I’d say everything in OSProcess that’s not redundant.  You probably don’t have a process name, command line, and different user/group but the rest seems relevant.

**Comment by tausiflife** [comment]
I have completed a part of the code and want to review the design with you. Should i just create a PR for review? or Is there any other way i can show you the code?

**Comment by dbwiddis** [comment]
A PR is probably easiest to do in line review. I can also just look at a branch in your fork for general feedback.

**Comment by tausiflife** [comment]
Created a PR. Have a look :)

**Comment by dbwiddis** [comment]
OK I think somehow you interpreted my last comment the opposite of what I meant.  For threads, aren't the `exe` and `commandline` always the same as the parent process? From [`man proc`](https://man7.org/linux/man-pages/man5/proc.5.html),

>               For attributes that are shared by all threads,
>               the contents for each of the files under the task/[tid] subdi‐
>               rectories will be the same as in the corresponding file in the
>               parent /proc/[pid] directory (e.g., in a multithreaded
>               process, all of the task/[tid]/cwd files will have the same
>               value as the /proc/[pid]/cwd file in the parent directory,
>               since all of the threads in a process share a working direc‐
>               tory).  For attributes that are distinct for each thread, the
>               corresponding files under task/[tid] may have different values
>               (e.g., various fields in each of the task/[tid]/status files
>               may be different for each thread), or they might not exist in
>               /proc/[pid] at all.

So I know cwd is the same and I assume name/commandline is also.  But you are missing the key fields that we want like kernel/user time, rss/vsz memory stats, execution state, priority, etc. and you can probably use the same parsing procedure for `/proc/pid/stat`. 

It might not be a bad idea to simply have OSThread extend OSProcess (and just call `super.foo()` when needed) and then add the extra fields (owning process, start address, wait reason).

**Comment by tausiflife** [comment]
Sounds like a good idea for OSThread to extend the OSProcess. This will need some code refactoring to reuse the parsing logic, but i think it should be ok.

**Comment by tausiflife** [comment]
I did of lot of searching in the jna and i couldn't find anything for the Thread32First or Thread32Next functions. Do you think you can help me here?

**Comment by dbwiddis** [comment]
This is a case we have to map it ourselves in a Kernel32 function.  (And eventually submit to JNA for its next version)

**Comment by dbwiddis** [comment]
You may not need that function, though.  It has limited information.  I think most of the stuff we use for Processes (registry, etc.) will work for threads.

**Comment by dbwiddis** [comment]
Implemented in #1258
