### ISSUE TITLE
java.lang.NoClassDefFoundError: com/sun/jna/platform/mac/SystemB$VMMeter

### ISSUE THREAD

**Issue by Beautiful1205** [oshi/oshi#1046]
Does anyone met this problem? 
I tried run the following code on mac, 

`        CentralProcessor processor = systemInfo.getHardware().getProcessor();
`

It throws me this error:
`Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jna/platform/mac/SystemB$VMMeter
	at oshi.hardware.platform.mac.MacHardwareAbstractionLayer.getProcessor(MacHardwareAbstractionLayer.java:60)
	at com.example.demo8.jvmservice.OshiTest.printlnCpuInfo(OshiTest.java:36)
	at com.example.demo8.jvmservice.OshiTest.main(OshiTest.java:21)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.platform.mac.SystemB$VMMeter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more`

it told me "cannot find declaration to go to", as shown in the image:
![image](https://user-images.githubusercontent.com/39459724/69031578-5e3f0200-0a15-11ea-93c0-7bc060fcbd1c.png)

is it dependencies conflicts or  not supported for mac?

thank you for your replying!

**Comment by Beautiful1205** [comment]
that is the dependency in pom.xml：
`<dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>
            <version>4.0.0</version>
</dependency>`

**Comment by dbwiddis** [comment]
That class was added to JNA in version 5.0.0.  OSHI 4.0.0 depends on at least JNA 5.4.0.  It is likely you are getting a transitive dependency for JNA from another source.   As documented in the README, you can usually resolve this by either moving oshi higher in the list of dependencies, or explicitly specifying the required JNA version in your POM.

I'd also recommend you use the most recent version of OSHI, 4.2.1 (and JNA 5.5.0).

**Comment by Beautiful1205** [comment]
Thank you! I revised the pom.xml and it works.
The dependencies are as following:
`<dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>net.java.dev.jna</groupId>
                    <artifactId>jna</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>net.java.dev.jna</groupId>
                    <artifactId>jna-platform</artifactId>
                </exclusion>
            </exclusions>
            <version>4.2.0</version>
        </dependency>
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>5.0.0</version>
        </dependency>
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna-platform</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>net.java.dev.jna</groupId>
                    <artifactId>jna</artifactId>
                </exclusion>
            </exclusions>
            <version>5.4.0</version>
        </dependency>`

what's more, the 'oshi-core' with version 4.2.1 is not avaliable in my project, and I just find it in the github.
Has it been deployed in the remote maven repository? 
If yes, then that might be my problem and I will try to fix it.

**Comment by dbwiddis** [comment]
Yes, 4.2.1 is [available on Maven](https://search.maven.org/artifact/com.github.oshi/oshi-core/4.2.1/jar). 

But it depends on JNA 5.5.0 and it looks like you are specifying an earlier version (5.0.0) of JNA.  You'll likely get a similar error somewhere else....

**Comment by Beautiful1205** [comment]
thank you for your explanation. have a good day!
