### ISSUE TITLE
GetServices not working on Centos 7

### ISSUE THREAD

**Issue by devinrsmith** [oshi/oshi#1055]
The SystemInfoTest does not seem to work on my Centos 7 install (on latest master commit `d7d2e9f8dd46dd4ce6dd1e787a15f4ce29626d10`).

```
$ ./mvnw test-compile -pl oshi-core -q exec:java   -Dexec.mainClass="oshi.SystemInfoTest"   -Dexec.classpathScope="test"
2019-12-03 13:21:40.938 [ERROR] LinuxOperatingSystem - Directory: /etc/init does not exist
2019-12-03 13:21:41.067 [ERROR] LinuxOperatingSystem - Directory: /etc/init does not exist
```

```
$ uname -a
Linux my-host 3.10.0-1062.4.3.el7.x86_64 #1 SMP Wed Nov 13 23:58:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Version 3.13.4 seems to work though:
```
$ ./mvnw test-compile -pl oshi-core -q exec:java   -Dexec.mainClass="oshi.SystemInfoTest"   -Dexec.classpathScope="test"
2019-12-03 13:28:48.488 [INFO] SystemInfoTest - Initializing System...
GNU/Linux CentOS Linux 7.7.1908 (Core) build 3.10.0-1062.4.3.el7.x86_64
2019-12-03 13:28:48.526 [INFO] SystemInfoTest - Checking computer system...
...
```

**Comment by dbwiddis** [comment]
4.0 would probably work, too, as that code is in the `getServices()` method.  This should just be a log error, however, and the rest should work fine.

Looks like it should be searching for `/etc/init.d` rather than `/etc/init` on CentOS

**Comment by devinrsmith** [comment]
Looking at the code, it seems like it *should* continue on - but those `[ERROR]` log lines are the only output :/

**Comment by dbwiddis** [comment]
Hmm.... maybe the logging level suppresses everything below ERROR?  The entire output should be logged....

**Comment by dbwiddis** [comment]
OK, 2 things going on here.

First, I updated the code to use the `systemctl` command in preference to checking `/etc/init` which should avoid that log error on CentOS and RHEL and possibly other distros.

Second, there is output, it's just being sent to a log INFO level and for some reason on all platforms, logging is only showing at Debug level.  I think there's a duplicate logging config somewhere, still hunting that down, but will fix that separately.
