### ISSUE TITLE
Linux OperatingSystemVersion vs OSVersionInfo

### ISSUE THREAD

**Issue by devinrsmith** [oshi/oshi#1056]
I see that `OperatingSystem#getVersion` is deprecated in favor of `OperatingSystem#getVersionInfo`. It seems like the recommended version always has a null build number for Linux though (whereas the deprecated version is non-null). Is this intentional?

**Comment by dbwiddis** [comment]
When non-null was it still "unknown"?  If I recall correctly there was some post-processing of the individual fields to create a display string.   I did intentionally leave some `null` results in the new format, although my reasoning was more laziness than whether I wanted to have the null have meaning.

**Comment by devinrsmith** [comment]
It was not "unknown" - it was "3.10.0-1062.4.3.el7.x86_64". It looks to be getting parsed out of `/proc/version`:

```
$ cat /proc/version
Linux version 3.10.0-1062.4.3.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Wed Nov 13 23:58:53 UTC 2019
```

**Comment by dbwiddis** [comment]
Looks like I need to download a CentOS VM and do some testing. :)

**Comment by dbwiddis** [comment]
Hey @devinrsmith sorry it's taken so long to look at this.  My day job gets crazy this time of year.  I'll take a look at this over the coming week.  Can you be more clear on old vs. new what you expect vs. what is?

**Comment by devinrsmith** [comment]
I'm hoping to follow up in the new year w/ a bit more specifics. Thanks!

**Comment by dbwiddis** [comment]
OK, so I finally had time to look into this.  With the new version, the build number is always null.  The older version made an attempt to parse `/proc/version` to find the build number, returning an empty string if unsuccessful.  I'll try to copy over that parsing attempt.
