### ISSUE TITLE
RAM Page size incorrectly showing on Ubuntu.

### ISSUE THREAD

**Issue by surajs1n** [oshi/oshi#1059]
Currently, I have two PCs: one desktop running on Ubuntu and another Mac. I used oshi to determine the details of hardware and OS on my respective computers.

Everything was looking good till I saw page size on ubuntu was showing 1B (which is actually 4KB). It was the same on Mac but there it was showing correctly. 

Attaching sample shortened code sample I used to get the page size:

    public Map<String, String> fetchOSDetails() {
        // something above.

        final SystemInfo si = new SystemInfo();
        final HardwareAbstractionLayer hal = si.getHardware();
        getMemoryDetails(hal.getMemory());

        // something below.
    }

    private void getMemoryDetails(final GlobalMemory memory) {
        osDetails.put("RAM Total Space (MB)", String.valueOf(memory.getTotal()/MEGA));
        osDetails.put("RAM Available Space (MB)", String.valueOf(memory.getAvailable()/MEGA));
        osDetails.put("RAM Page Size (Byte)", String.valueOf(memory.getPageSize())); <== Page size
    }

 Link to entire file can be found here: https://github.com/surajs1n/JIO/blob/master/src/main/java/io/os/OperatingSystemDetails.java

My ubuntu version: GNU/Linux Ubuntu 18.04.3 LTS (Bionic Beaver) build 4.15.0-72-generic

**Comment by dbwiddis** [comment]
Interesting.  I test the Linux code on an Ubuntu VM and it works fine.  On Linux, the page size is determined from a call to [`sysinfo()`](http://man7.org/linux/man-pages/man2/sysinfo.2.html) returning the `mem_unit` value of the returned structure.

On closer inspection, however, nothing in the docs specifies that is page size.  Perhaps I should just use the `getconf PAGE_SIZE` output instead, as that's more standard.  Thoughts?

**Comment by surajs1n** [comment]
@dbwiddis I think you are right. I did check `sysinfo( )` documentation, it doesn't guarantee `mem_unit` can be interpreted as page size. 

Beside documentation says:

    In the above structure, sizes of the memory and swap fields are given 
    as multiples of mem_unit bytes.   

I also checked `LinuxGlobalMemory's readSysinfo()` code:

    private void readSysinfo() {
        try {
            Sysinfo info = new Sysinfo();
            if (0 == LibC.INSTANCE.sysinfo(info)) {
                this.memTotal = info.totalram.longValue();
                this.pageSize = info.mem_unit;
            } else {
                LOG.error("Failed to get sysinfo. Error code: {}", Native.getLastError());
            }
        } catch (UnsatisfiedLinkError | NoClassDefFoundError e) {
            LOG.error("Failed to get sysinfo. {}", e);
            this.pageSize = ParseUtil.parseLongOrDefault(ExecutingCommand.getFirstAnswer("getconf PAGE_SIZE"), 4096L);
            updateMemInfo();
        }
    }

I agree the better practice would be to keep the `memTotal` calculation as the way it is. But in case of pageSize, considering the code under catch block be better than any other assumption.
