### ISSUE TITLE
TransferTime is wrong again

### ISSUE THREAD

**Issue by Space2Man** [oshi/oshi#1061]
Hi,

on Windows the transfertime seems to be wrong again. We fixed this in #653 but somehow on an completely idle disk (like CDROM) I see that transfertime == timestamp.

This is with OSHI 3.13.4.

Best regards, Space

**Comment by Space2Man** [comment]
Issue seems to come from #763 ...

**Comment by Space2Man** [comment]
I opened pull request #1063

**Comment by Space2Man** [comment]
Ah, now I see why #763 broke it ... it applied the 1-x part, but it uses the diskTime, not the idleTime. I guess we should rename it for 3.13.x as well.

Although it might very well be that 4.2.x was working before that. I noticed that my test systems all are running against 3.13.4 at the moment. And there we have the 1-%diskTime which is of course wrong.

**Comment by dbwiddis** [comment]
or remove the 1-x part? Heh.

**Comment by Space2Man** [comment]
I think it's better to use 1-%idle, see http://support.demandtech.com/index.php?pg=kb.page&id=47
On laptops this probably does not matter (that much) but I think on pretty busy database servers the numbers get wrong otherwise. I don't expect a disk to be >100% busy ...

But 1-%disk is definetly wrong :)

**Comment by dbwiddis** [comment]
I concur 1-%idle is probably the best.   Is the PR good to go? I haven't had time to look at it yet.

**Comment by Space2Man** [comment]
Hi, I have not been able to test this as I switched my workstation to Linux and for the other systems there is currently a change freeze :-\

**Comment by dbwiddis** [comment]
Fixed in #1063 and #1065
