### ISSUE TITLE
Cannot get CPU temperature information

### ISSUE THREAD

**Issue by hxzcan** [oshi/oshi#1064]
I get the CPU information under windows system is:CPU Temperature=0.0°C, Fan Speeds=[], CPU Voltage=0.0

**Comment by dbwiddis** [comment]
This is addressed [in the FAQ](https://github.com/oshi/oshi/blob/master/FAQ.md#what-api-features-are-not-implemented-on-some-operating-systems) and also the [`Sensors` class javadoc](http://oshi.github.io/oshi/apidocs/oshi/hardware/Sensors.html):

> Windows information is retrieved via Windows Management Instrumentation (WMI). Unfortunately, most hardware providers do not publish values to WMI. If a value is not available through the Microsoft API, Oshi will attempt to retrieve values as published to WMI by [Open Hardware Monitor](https://openhardwaremonitor.org/) if it is running.

**Comment by hxzcan** [comment]
Is there an API to kill the process?

**Comment by dbwiddis** [comment]
Which process? OpenHardwareMonitor?  It's just an executable you can open, and just close it when you're done.  It's possible to configure it to run as a service, and shut it off with the services API.

**Comment by hxzcan** [comment]
I mean get the progress of the system, kill some progress of the system

**Comment by hxzcan** [comment]
I mean, get the process of the system, and kill a process of the system

**Comment by dbwiddis** [comment]
Which process?  

There's always the Task Manager...

**Comment by hxzcan** [comment]
For example, I want to close the Google Chrome process. Is there a function to call

**Comment by dbwiddis** [comment]
Ah, now I understand what you're asking.  No, OSHI does not have an API for terminating processes.

There is a `taskkill` command line command to kill a process that you could use, e.g., `ExecutingCommand.runNative("taskkill /F /PID "+pid);`

**Comment by hxzcan** [comment]
ok,thanks
