### ISSUE TITLE
Pdh call failed with error code 0x800007D0

### ISSUE THREAD

**Issue by XakepSDK** [oshi/oshi#1066]
I got this exception automatically collected by report service.
oshi 4.2.1, windows 7 64bit
```
com.sun.jna.platform.win32.PdhUtil$PdhException: Pdh call failed with error code 0x800007D0
	at com.sun.jna.platform.win32.PdhUtil.PdhLookupPerfNameByIndex(PdhUtil.java:71) ~[jna-platform-5.5.0.jar:5.5.0 (b0)]
	at oshi.util.platform.windows.PerfCounterWildcardQuery.localize(PerfCounterWildcardQuery.java:142) ~[oshi-core-4.2.1.jar:4.2.1]
	at oshi.util.platform.windows.PerfCounterWildcardQuery.<init>(PerfCounterWildcardQuery.java:123) ~[oshi-core-4.2.1.jar:4.2.1]
	at oshi.software.os.windows.WindowsOperatingSystem.<init>(WindowsOperatingSystem.java:126) ~[oshi-core-4.2.1.jar:4.2.1]
	at oshi.SystemInfo.createOperatingSystem(SystemInfo.java:102) ~[oshi-core-4.2.1.jar:4.2.1]
	at oshi.util.Memoizer$1.get(Memoizer.java:84) ~[oshi-core-4.2.1.jar:4.2.1]
	at oshi.SystemInfo.getOperatingSystem(SystemInfo.java:95) ~[oshi-core-4.2.1.jar:4.2.1]
```

**Comment by dbwiddis** [comment]
Interesting. This is failing the [PdhLookupPerfNameByIndex](https://docs.microsoft.com/en-us/windows/win32/api/pdh/nf-pdh-pdhlookupperfnamebyindexa) call while trying to localize the `Process` counter name, but the error `0x800007D0` is 
> Unable to connect to the specified computer, or the computer is offline.

That's odd since it's the local computer (null).  This looks similar to the error reported in #643, which seemed to have been permissions-based.

In any case, we are already trying to catch the `Win32Exception` in this same call, and I think we need to add the `PdhException` to that catch clause to fix it.

**Comment by dbwiddis** [comment]
I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to open source before. This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. :-) 

When localizing performance counter names, OSHI is not catching all the exception conditions.  Add the `PdhException` to the catch clause in the `PerfCounterWildcardQuery`'s `localize()` method.

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- In the [`PerfCounterWildcardQuery`](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/util/platform/windows/PerfCounterWildcardQuery.java#L143) class, modify the catch clause to include a [`PdhException`](https://java-native-access.github.io/jna/5.3.1/javadoc/com/sun/jna/platform/win32/PdhUtil.PdhException.html).
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:
