### ISSUE TITLE
LinuxOperatingSystem.getProcess fails on OpenVZ 7 kernels

### ISSUE THREAD

**Issue by TJSomething** [oshi/oshi#1071]
If you run `LinuxOperatingSystem.getProcess` on a VPS that is running an OpenVZ 7 (Linux 3.10) kernel, it will fail because `/proc/<pid>/stat` has 61 instead of the expected 52 fields. When this happens, ParseUtil throws the error. Unfortunately, I cannot find documentation on these extra fields, just the source code at [the OpenVZ project](https://src.openvz.org/projects/OVZ/repos/vzkernel/browse/fs/proc/array.c).

An example output is:

```
15609 (bash) S 15608 15609 15609 34816 9427 4202496 2925 680374 0 24 22 8 17352 664 20 0 1 0 1146373690 20877312 614 18446744073709551615 94099565166592 94099566228152 140723742166656 140723742165320 140488442316423 0 65536 3670020 1266777851 18446744072105880390 0 0 17 0 0 0 0 0 0 94099568328080 94099568375140 94099570638848 140723742170743 140723742170749 140723742170749 140723742171118 0  0 0 0 0 0 15609 709af748-5f8e-41b3-b73a-b440ef4406c8 709af748-5f8e-41b3-b73a-b440ef4406c8 709af748-5f8e-41b3-b73a-b440ef4406c8
```

**Comment by dbwiddis** [comment]
The philosophical side of me loves the freedom of Linux distributions to do whatever they want.  The coder in me hates lack of standards!  

Looks like the last 3 fields are in UUID format... would love documentation to that effect so I can rely on it.

**Comment by dbwiddis** [comment]
I believe #1073 should fix this.  Can you test the PR -- it's also been uploaded to SNAPSHOT

**Comment by TJSomething** [comment]
Now there's a new error. Before it was:

```
Not enough fields in string '20506 (java) S 20458 20458 27348 34816 20458 1077944320 143968 5114 0 0 2255 100 1 4 20 0 31 0 1154040180 5288026112 134325 18446744073709551615 94100196270080 94100196272576 140735487474384 140735487457008 140018962210093 0 0 0 16800975 18446744073709551615 0 0 17 2 0 0 0 0 0 94100198370648 94100198371344 94100214939648 140735487477306 140735487477451 140735487477451 140735487479786 0  0 0 0 0 0 20506 709af748-5f8e-41b3-b73a-b440ef4406c8 709af748-5f8e-41b3-b73a-b440ef4406c8 709af748-5f8e-41b3-b73a-b440ef4406c8' parsing to long array: 1
```

Now it is:

```
ERROR oshi.util.ParseUtil - Number is too big for a long parsing string '21083 (java) S 21035 21035 27348 34816 21035 1077944320 163342 5117 0 0 3357 124 1 4 20 0 30 0 1154050194 5229572096 146263 18446744073709551615 94235316494336 94235316496832 140723954847376 140723954830000 139776761543981 0 0 0 16800975 18446744073709551615 0 0 17 0 0 0 0 0 0 94235318594904 94235318595600 94235346337792 140723954849338 140723954849483 140723954849483 140723954851818 0  0 0 0 0 0 21083 709af748-5f8e-41b3-b73a-b440ef4406c8 709af748-5f8e-41b3-b73a-b440ef4406c8 709af748-5f8e-41b3-b73a-b440ef4406c8' to long array
```

**Comment by dbwiddis** [comment]
> Number is too big for a long

That would be 18446744073709551615 which looks like the max unsigned 64-bit value. 

The whole point of this particular parsing routine is to be fast and memory efficient since it's called for every process on the system, so I'd have to use a `BigInteger` to handle that value.  I could, possibly, ignore such large numbers if they aren't part of the returned output array, but this one is one of the values you requested.  What does it represent and how would you like those values handled?

**Comment by dbwiddis** [comment]
Looks like that's the value for RSS.  That's 1.8 million Terabytes.  Sine the [most memory a computer has had is 12 TB](https://www.quora.com/What-is-the-most-RAM-a-computer-has-ever-had), something tells me that's not a valid value ;)

**Comment by TJSomething** [comment]
I think that value means unlimited and it's always that for any kernel Linux 3 and up. I'm also seeing it in my regular Debian 5.3.0 kernel.

**Comment by dbwiddis** [comment]
Ah, yes, off by one.  It's the `(25) rsslim  %lu` value and given the `%lu` that seems valid.  Would it be reasonable to return `Long.MAX_VALUE` in these cases?  It's under by a factor of 2, but the other option is to return `-1`.

**Comment by TJSomething** [comment]
I think that `Long.MAX_VALUE` sounds reasonable. Current CPUs cannot handle addresses above 48-bits anyway.

**Comment by dbwiddis** [comment]
OK, instead of an error, values above the max long now just return the max long.  Try it out!

**Comment by TJSomething** [comment]
It looks like it works. Thank you very much!

**Comment by dbwiddis** [comment]
Cool!  Merging, will cut a new release within a week or so once I handle the CentOS tickets.
