### ISSUE TITLE
Spark metrics thread is stuck getSystemCpuLoadBetweenTicks in centos virtual machine

### ISSUE THREAD

**Issue by PengleiShi** [oshi/oshi#1072]
Hello everyone, i am using oshi to get system metric like cpu usage in Spark metric system with custom source, but when metric reporter starts, it can get os name, but when getSystemCpuLoadBetweenTicks is invoked in code, the thread begin to be stuck and with no exception throwed, like this:
![image](https://user-images.githubusercontent.com/23723660/71621448-3c3ac100-2c0a-11ea-9548-b4785689527b.png)

If i run a sample java jar which just gets cpu usage and then prints it, it worked,
![image](https://user-images.githubusercontent.com/23723660/71621456-49f04680-2c0a-11ea-9a1b-1c7998ecce8e.png)

Anyone could help me?

**Comment by PengleiShi** [comment]
I found getSystemCpuLoadTicks is worked, and i can use it to caculate cpu usage in my code.

**Comment by dbwiddis** [comment]
This may be a problem in the external (Spark metrics) app you were using.  Can you share the source code for that (or a link to it)?

**Comment by PengleiShi** [comment]
Thanks, i can't share  the source code, it contains multiple files. 
reference http://jhu-chang.github.io/bigdata/2016/03/24/custom-spark-metric-to-report-process-and-system-information/ ， this is demo which use Sigar, and i replace Sigar with oshi.

**Comment by dbwiddis** [comment]
I'll close this issue as you're using the "ticks" command as an incrementing counter, which is the API design.  The "between ticks" requires you to store the previous value and pass it, and is really only provided for convenience.
