### ISSUE TITLE
Test script on README doesn't output logs below DEBUG

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1075]
As reported in #1055 the command given on the `README` to display the `SystemInfoTest` output no longer seems to work:

```
git clone https://github.com/oshi/oshi.git && cd oshi

./mvnw test-compile -pl oshi-core -q exec:java \
  -Dexec.mainClass="oshi.SystemInfoTest" \
  -Dexec.classpathScope="test"
```
Produces no output.  

Instrumenting SystemInfoTest with some output:
```
        System.out.println("Logging test:");
        System.out.println("ERROR? " + logger.isErrorEnabled());
        logger.error("Error");
        System.out.println("WARN? " + logger.isWarnEnabled());
        logger.warn("Warn");
        System.out.println("INFO? " + logger.isInfoEnabled());
        logger.info("Info");
        System.out.println("DEBUG? " + logger.isDebugEnabled());
        logger.debug("Debug");
        System.out.println("TRACE? " + logger.isDebugEnabled());
        logger.trace("Trace");
```
Results in:
```
Logging test:
ERROR? true
2019-12-31 18:31:35.506 [ERROR] SystemInfoTest - Error
WARN? false
INFO? false
DEBUG? false
TRACE?false
```
Attempting to change logging on the command line by adding `-Dorg.slf4j.simpleLogger.defaultLogLevel=info` doesn't help.

I suspect there's some configuration change in the `pom.xml` that is suppressing the logs.

**Comment by hazendaz** [comment]
@dbwiddis Do the logs go to the test output files (junit)?  I do't recall if that was setup to push logs to files.  If so, it's likely in the physical log files rather than the command line.  I can take a deeper look in next few days.

**Comment by dbwiddis** [comment]
Nope, no trace of the log output -- which I think is going to console, as ERROR logging goes there.  It's more an issue of why the log level is set to error, that I can't figure out.  

It's possible it's been this way a long time, and the change to output the test case to the logger suppressed the output.

All copies of `simplelogger.properties` on my machine specify `info` level (which is supposed to be the default anyway) including the maven installation.  Same symptoms with the maven wrapper and maven commandline so I don't think that's the problem.  It works totally fine in my IDE (Eclipse).

Take your time looking at this, I know it's the holidays!  I just figured if anyone would know some maven subtlety causing this, you might.

**Comment by dbwiddis** [comment]
OK, the answer to the original question is simple.  

The previous script relied on `System.out` and so suppressed OSHI logs to only `ERROR` level using the `-q` (`--quiet`) switch.  Removing that switch restores the logging output at the `INFO` level, for both the maven setup (which logs all the building/compiling steps, and OSHI's output, which changes to a different log output format, as it's using a different logging properties file -- but it's wrapped inside the Maven `exec` command's `INFO` level output.

I believe this may be a limitation of `slf4j` where you can't change logging level on-the-fly.  I'll look into whether that's possible and/or if there's any configuration for the `exec` command regarding the logging.

**Comment by dbwiddis** [comment]
One possibility instead of `-q` to strip the maven headers (and make the log filtering clearer to the user) is to remove the Maven logs which are prepended with `[INFO]` but leave the OSHI logs which have the timestamp first before `[INFO]`, so we could pipe the existing command into ` | egrep -v "(^\[INFO\])"` on *nix, and `| findstr /V /R "^\[INFO\]"` on Windows.

**Comment by dbwiddis** [comment]
And although the above works, there's a few second delay during the maven build, and I think I'd just prefer to see those steps so I know stuff's happening.

**Comment by dbwiddis** [comment]
Removed the `-q` along with the [2020 licence header commit](https://github.com/oshi/oshi/commit/afb4c55a1d75571cb259391be8e38a476e5e3de7)

**Comment by hazendaz** [comment]
@dbwiddis See C:\Users\Jeremy\Documents\GitHub\oshi\oshi-core\target\surefire-reports\oshi.SystemInfoTest-output.txt.  That is the output of the run.  Nothing special other than mvn clean install.

**Comment by dbwiddis** [comment]
That's using the 'install' command vs. the `exec` which the test script did.  Anyway, traced the issue to the `-q` switch, so this is no longer an issue.  That switch was fine when suppressing the maven output but allowing the `System.out` code, but broke things when we switched to log output.

**Comment by hazendaz** [comment]
Cool!  One less thing to worry about :)  now time for me to resync up latest to psi probe:)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
