### ISSUE TITLE
unable to get cpu frequency on cloud server

### ISSUE THREAD

**Issue by tomcraft** [oshi/oshi#1078]
Hello, i use this library since few months and never had problem, but today i ordered a different kind of server (public cloud @ ovh), and my software is unable to get cpu frequency.

using `CentralProcessor#getMaxFreq` returns -1 with oshi v4.3.0

command `lscpu` 

> Architecture:        x86_64
> CPU op-mode(s):      32-bit, 64-bit
> Byte Order:          Little Endian
> Address sizes:       40 bits physical, 48 bits virtual
> CPU(s):              8
> On-line CPU(s) list: 0-7
> Thread(s) per core:  1
> Core(s) per socket:  1
> Socket(s):           8
> NUMA node(s):        1
> Vendor ID:           GenuineIntel
> CPU family:          6
> Model:               60
> Model name:          Intel Core Processor (Haswell, no TSX)
> Stepping:            1
> CPU MHz:             3092.824
> BogoMIPS:            6185.64
> Virtualization:      VT-x
> Hypervisor vendor:   KVM
> Virtualization type: full
> L1d cache:           32K
> L1i cache:           32K
> L2 cache:            4096K
> NUMA node0 CPU(s):   0-7
> Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear

command `uname -a`

> Linux <hostname> 4.19.0-6-cloud-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

command `cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq`

> cat: /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq: No such file or directory

i'm available to answer any question you would have to fix this.

Best regards

**Comment by dbwiddis** [comment]
The current and max frequency are unlikely to work on a cloud server, as the CPUs you see aren't really physical ones.   You should still be able to use "VendorFrequency" to find the rated CPU frequency of the processors, the theoretical maximum the cloud provider should be providing you when you need it.

See #1053 for .a similar question/answer.

**Comment by tomcraft** [comment]
thank you for the answer, i test this asap and I report the result here.
