### ISSUE TITLE
unable to get the cpu info by OSUtils.cpuUsage method

### ISSUE THREAD

**Issue by huangjiayegithub** [oshi/oshi#1080]
hello, i got this problem for a long time , Many methods have been used, like reinstall jdk ,upgrade mac os, but they can't be solved..

```java
Exception in thread "main" java.lang.NoSuchMethodError: com.sun.jna.platform.mac.SystemB$HostCpuLoadInfo.createFieldsOrder(Ljava/lang/String;)Ljava/util/List;
	at com.sun.jna.platform.mac.SystemB$HostCpuLoadInfo.<clinit>(SystemB.java:69)
	at oshi.hardware.platform.mac.MacCentralProcessor.getSystemCpuLoadTicks(MacCentralProcessor.java:114)
	at oshi.hardware.common.AbstractCentralProcessor.updateSystemTicks(AbstractCentralProcessor.java:409)
	at oshi.hardware.common.AbstractCentralProcessor.initTicks(AbstractCentralProcessor.java:148)
	at oshi.hardware.platform.mac.MacCentralProcessor.<init>(MacCentralProcessor.java:76)
	at oshi.hardware.platform.mac.MacHardwareAbstractionLayer.getProcessor(MacHardwareAbstractionLayer.java:53)
	at com.yibo.modules.controller.OSUtils.cpuUsage(OSUtils.java:78)
	at com.yibo.modules.controller.Test.main(Test.java:13)
Disconnected from the target VM, address: '127.0.0.1:54518', transport: 'socket'

Process finished with exit code 1
```

```java
import oshi.jna.platform.mac.SystemB;
import java.util.Collections;
import java.util.List;


public class Test {
    public static void main(String[] args) {

        double v = OSUtils.cpuUsage();
        System.out.println("v = " + v);


       /* List<String> cpu_ticks = SystemB.HostCpuLoadInfo.createFieldsOrder("cpu_ticks");
        System.out.println("cpu_ticks = " + cpu_ticks);*/


        /*List<String> nihao = Collections.unmodifiableList(Collections.singletonList("nihao"));
        System.out.println("nihao = " + nihao);*/

    }
}
`

**Comment by dbwiddis** [comment]
The current version of the `SystemB` class in the JNA project has the [`HostCpuLoadInfo` class initialization on line 91](https://github.com/java-native-access/jna/blob/master/contrib/platform/src/com/sun/jna/platform/mac/SystemB.java#L91).  Your stack trace indicates line 69, implying you have an older version of this class in your JNA dependency list.

Please ensure you are using the latest version (5.5.0) of JNA.  If you are using Maven, list the oshi dependency first in your dependency list to ensure that any other imports which include a JNA dependency do not process their transitive dependencies first; alternately, specify the most recent JNA versions at the top level in your POM.

**Comment by dbwiddis** [comment]
It looks like you have version 4.2.0 of `jna-platform.jar`.

**Comment by huangjiayegithub** [comment]
> It looks like you have version 4.2.0 of `jna-platform.jar`.

thanks for your reply ,  here is my dependency version:

**Comment by huangjiayegithub** [comment]
> It looks like you have version 4.2.0 of `jna-platform.jar`.

<dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>
            <version>3.5.0</version>
        </dependency>
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna-platform</artifactId>
            <version>4.5.2</version>
        </dependency>

**Comment by dbwiddis** [comment]
The latest version of `oshi-core` is 4.3.0.  Can you use that dependency?

**Comment by huangjiayegithub** [comment]
> The latest version of `oshi-core` is 4.3.0. Can you use that dependency?

OK，  I'll try 4.3.0 now

**Comment by dbwiddis** [comment]
If you do use the earlier 3.5.0 version, you need both the `jna` and `jna-platform` dependencies at the same corresponding version level (4.5.2 would be correct for both, for that older version).  It's possible you only included the `jna-platform` dependency, but you have an earlier `jna` dependency loaded transitively.

**Comment by huangjiayegithub** [comment]
> If you do use the earlier 3.5.0 version, you need both the `jna` and `jna-platform` dependencies at the same corresponding version level (4.5.2 would be correct for both, for that older version). It's possible you only included the `jna-platform` dependency, but you have an earlier `jna` dependency loaded transitively.

but i found the classloader info like this :

jar:file:/Users/huangjiaye/.m2/repository/net/java/dev/jna/jna-platform/4.5.2/jna-platform-4.5.2.jar!/com/sun/jna/platform/mac/SystemB.class

jar:file:/Users/huangjiaye/.m2/repository/com/github/oshi/oshi-core/3.5.0/oshi-core-3.5.0.jar!/oshi/hardware/common/AbstractCentralProcessor.class

**Comment by huangjiayegithub** [comment]
> > If you do use the earlier 3.5.0 version, you need both the `jna` and `jna-platform` dependencies at the same corresponding version level (4.5.2 would be correct for both, for that older version). It's possible you only included the `jna-platform` dependency, but you have an earlier `jna` dependency loaded transitively.
> 
> but i found the classloader info like this :
> 
> jar:file:/Users/huangjiaye/.m2/repository/net/java/dev/jna/jna-platform/4.5.2/jna-platform-4.5.2.jar!/com/sun/jna/platform/mac/SystemB.class
> 
> jar:file:/Users/huangjiaye/.m2/repository/com/github/oshi/oshi-core/3.5.0/oshi-core-3.5.0.jar!/oshi/hardware/common/AbstractCentralProcessor.class

Add a message：
jar:file:/Library/Java/Extensions/jna-4.1.0.jar!/com/sun/jna/Structure.class

maybe 4.1.0 Version not suitable？

**Comment by dbwiddis** [comment]
That's your problem, you need `jna-4.5.2.jar` to match up with the `jna-platform`.  But why do you have it loaded separately in your library instead of as part of the Maven dependencies?

**Comment by huangjiayegithub** [comment]
> That's your problem, you need `jna-4.5.2.jar` to match up with the `jna-platform`. But why do you have it loaded separately in your library instead of as part of the Maven dependencies?

i just run zookeeper and redis by docker,  but i don't know why jna  and jna-platform is loaded separately in my library.   now i try to stop zookeeper and redis, then restart my mac os , try test OSUtil. cpuUsage() method again

**Comment by dbwiddis** [comment]
Zookeeper probably adds JNA as a dependency. How are you including it?  Try explicitly specifying the latest JNA version for both files in your POM

**Comment by huangjiayegithub** [comment]
> Zookeeper probably adds JNA as a dependency. How are you including it? Try explicitly specifying the latest JNA version for both files in your POM

The problem has been solved, thank you for your help. This is my first time to ask questions at GitHub, Sincere thanks

**Comment by dbwiddis** [comment]
Glad you got the problem solved!
