### ISSUE TITLE
OSHI is getting popular

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1084]
OSHI downloads increased fivefold in 2018

![image](https://user-images.githubusercontent.com/9291703/50721158-98a6e700-106f-11e9-8910-d3ec01da9e0e.png)
![image](https://user-images.githubusercontent.com/9291703/50721166-ae1c1100-106f-11e9-915e-fc0d8ce221db.png)

We're a dependency in some [cool projects](https://mvnrepository.com/artifact/com.github.oshi/oshi-core/usages).

One fun fact to see on that list is JPPF, a project I was contributing to before OSHI.   I came to OSHI when trying to monitor memory usage in a distributed network of cloud servers. JPPF was using Java's OperatingSystemMXBean's [free physical memory](https://docs.oracle.com/javase/7/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html#getFreePhysicalMemorySize()) method which was useless on Linux, and I went hunting for better alternatives.  OSHI had the same issue but was more easily fixed -- which got me contributing here, and the rest is history.   Good to see that JPPF finally updated to use my improved code!

**Comment by dbwiddis** [comment]
The growth continues. Thanks to everyone who's contributing with PRs, bug reports, and suggestions.

![image](https://user-images.githubusercontent.com/9291703/72231714-d89d8580-3571-11ea-80b1-87ab54746308.png)
![image](https://user-images.githubusercontent.com/9291703/72231739-f10da000-3571-11ea-8dbf-63989c8583f1.png)

**Comment by hazendaz** [comment]
Nice year over year! Congrats!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dbwiddis** [comment]
![image](https://user-images.githubusercontent.com/9291703/104890295-3d798180-5924-11eb-8acb-b1dbaed23485.png)
![image](https://user-images.githubusercontent.com/9291703/104890430-669a1200-5924-11eb-8459-ba20c2cccf55.png)

**Comment by dbwiddis** [comment]
![image](https://user-images.githubusercontent.com/9291703/149057832-0592d132-cc3e-4420-947f-f0362481f31c.png)
![image](https://user-images.githubusercontent.com/9291703/149057891-dca0272a-2d98-4db7-ba27-e0c089f24497.png)

**Comment by dbwiddis** [comment]
Hit the million download mark in March 2022.  For comparison (see above) 6000 downloads in March 2018.

![image](https://user-images.githubusercontent.com/9291703/163516184-00533f8d-7885-445b-92e5-b6b9e36c0417.png)

**Comment by hazendaz** [comment]
Wow.  Great numbers

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dbwiddis** [comment]
Not sure why it peaked in March, but still on a slow upward trend finishing the year at 964K.

![Screen Shot 2023-01-23 at 8 47 32 AM](https://user-images.githubusercontent.com/9291703/214098910-8aeb6728-529a-4c80-bde6-010a40b0cc9f.png)

**Comment by dbwiddis** [comment]
Missed grabbing this last month...

![image](https://github.com/oshi/oshi/assets/9291703/73ae4134-b7d0-45db-8962-3e92e2c4246e)
![image](https://github.com/oshi/oshi/assets/9291703/fd308cf3-049e-405c-840b-69afac21b871)

**Comment by dbwiddis** [comment]
![Screenshot 2025-01-07 at 3 07 55 PM](https://github.com/user-attachments/assets/1b748a1c-4f64-48dc-9671-52fa3cb50c38)
![Screenshot 2025-01-07 at 3 08 27 PM](https://github.com/user-attachments/assets/874c3ed8-2407-4cdf-9aaf-439454f09fb8)
