### ISSUE TITLE
LinuxFileSystem: option to access only local filesystems?

### ISSUE THREAD

**Issue by Space2Man** [oshi/oshi#1097]
Hi dbwiddis,

right now there does not seem to be an option to query only local filesystems (so no network fs like nfs or cifs) in getFileStoreMatching/getFileStores. I would welcome such an option very much since with the current version it might happen that the call *hangs* in the statvfs call if e.g. an NFS server is not responding:

`LinuxFileSystem: Failed to get information to use statvfs. path: /some/nfs/path, Error code: 5`

So I would like to have an option where I can specify that the method does not query the utilisation if the FS is a network FS.

What's your opinion on that?

Thanks and best regards,

    Space

**Comment by Space2Man** [comment]
Two ideas:

- getLocalFileStores(): get OSFileStore[] for local fs only
- getFileStores([fsTypes]): get OSFileStore[] where the type matches one of the arguments

**Comment by dbwiddis** [comment]
How about `getFileStores(boolean localOnly)`?

It's the same general concept as the various boolean `slowFields` switches we have on some getters.  Could do something similar for the Network Interfaces to address #976.  

Can you submit a PR for that please?

**Comment by Space2Man** [comment]
Two questions:

- default should be false I guess so that getFileStores behaves the same way as right now
- is there an option -l for df on Solaris (to avoid checking possible hanging network mounts in case of unresponsive NFS server) ... I know that option from Linux but I am not sure if it's available on Solaris as well. And the man page does not even know the option -g (at least according to [docs.oracle.com](https://docs.oracle.com/cd/E36784_01/html/E36870/df-1b.html). But this other man page knows both -g and -l: [docs.oracle.com](https://docs.oracle.com/cd/E36784_01/html/E36871/df-1m.html#REFMAN1Mdf-1m) ... so I guess I can use -l to check for local fs only ...

**Comment by Space2Man** [comment]
And the Windows stuff ... I am not sure how to handle that ... to me it sounds like getLocalVolumes returns only local volumes and getWmiVolumes returns the network volumes as well ... but getWmiVolumes is called as well for the local volumes to update the name infos ... I could make the call to

`result.add(wmiVolume);`

depending on localOnly == false ... but it would query the network volumes anyway. But I am not sure if this could hang on Windows as well like it can on the Unix systems.

**Comment by dbwiddis** [comment]
> default should be false I guess 
Yep.  The no-arg `getFileStores()` should call `getFileStores(false)` (or maybe `true` with a variable name of "nonLocal").  [Naming variables is hard](https://martinfowler.com/bliki/TwoHardThings.html).  Your original suggestion of a fstype sounds good from an API standpoint but  then would we have to read all the info first (possibly slow)?  I guess on the *nix machines if we start with the `mounts` command we could figure out the types from that and pre-filter before any other command.  The bigger question is Windows. We currently call `getLocalVolumes()` and then back that up with a WMI query to get the rest; so the local/nonlocal binary choice seems the best from a performance standpoint.

> is there an option -l for df on Solaris

`df -l` works on my Solaris 11.3 VM.  `man df` says:
![image](https://user-images.githubusercontent.com/9291703/74093782-c557da00-4a8b-11ea-882b-d67722201530.png)

**Comment by Space2Man** [comment]
Check: Implement option to gather only local filestore stats. #1098

**Comment by dbwiddis** [comment]
> getWmiVolumes is called as well for the local volumes to update the name infos 

Good point.... I instrumented the code to see what happens to the name. Here's what it looks like:
```
Changing name 'PRL (A:\)' to '3 1/2 Inch Floppy Drive (A:)'.
Changing name ' (C:\)' to 'Local Fixed Disk (C:)'.
Changing name ' (D:\)' to 'CD-ROM Disc (D:)'.
```
I think that's valuable information.  I think we could filter the WMI query to only the mount points returned as local.  I'd have to do some experiments to see whether there's a performance difference if WMI doesn't need to return info on network drives... I'll try that next week.

**Comment by Space2Man** [comment]
And I need to get maven up and running again next week if the build on Travis still fails ...

**Comment by dbwiddis** [comment]
Heh, I saw at least one of those errors with my human compiler eyes. :)   Busy today but might look tomorrow afternoon at non-windows, and do some performance tests monday to see if WMI filtering matters.

**Comment by Space2Man** [comment]
Ok, I fixed those compiler errors ... too bad if you are still in Groovy mode :)
