### ISSUE TITLE
NullPointerException is given when getting disk info

### ISSUE THREAD

**Issue by lixiaochun** [oshi/oshi#1102]
Hi, I use the latest version to get disk info in SuSE 11.3,but the error as below occurs.
could you pls look into it, thank you so much.
 
```
Exception in thread "main" java.lang.NullPointerException
        at oshi.hardware.platform.linux.LinuxDisks.getDisks(LinuxDisks.java:123)
        at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.getDiskStores(LinuxHardwareAbstractionLayer.java:78)
        at com.td.isp.Main.main(Main.java:247)
ubp@mix-163:~>
ubp@mix-163:~>
ubp@mix-163:~> uname -a
Linux mix-163 3.0.76-0.11-default #1 SMP Fri Jun 14 08:21:43 UTC 2013 (ccab990) x86_64 x86_64 x86_64 GNU/Linux
ubp@mix-163:~> cat /etc/SuSE-release
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 3
```

**Comment by dbwiddis** [comment]
It appears `udev_device_get_devnode(device)` is returning `null`.  We do a null check on `device` but according to [the docs](https://manpages.debian.org/testing/libudev-dev/udev_device_get_devnode.3.en.html), null results when the function fails.

I can check for the null, but I'm not sure why the result would be null and what the appropriate action to take is here.  Does anything look unusual in the directory `/dev/block` ?

**Comment by dbwiddis** [comment]
Also the output of `lsblk` would be helpful.

**Comment by dbwiddis** [comment]
While researching, I found [this link](https://www.suse.com/support/kb/doc/?id=7022728) indicating that `lsblk` (and the udev equivalent we're using) may be broken on kernel `3.0.101-108.35` on VMWare. This is a later version than yours, but the poster didn't say what they upgraded from.

**Comment by lixiaochun** [comment]
output of lsblk and /dev/block is as below:
 
linux-x99z:~ # lsblk
NAME                  MAJ:MIN RM   SIZE RO MOUNTPOINT
sda                     8:0    0   100G  0
|-sda1                  8:1    0   101M  0 /boot
|-sda2                  8:2    0     4G  0 [SWAP]
`-sda3                  8:3    0  95.9G  0
  `-vg0-lvroot (dm-0) 253:0    0  95.9G  0 /
fd0                     2:0    1     4K  0
sr0                    11:0    1  1024M  0
loop0                   7:0    0   400M  0 /home/ftpuser
linux-x99z:~ # ll /dev/block
▒▒▒▒▒ 0
lrwxrwxrwx 1 root root 6 10▒▒  6 2018 11:0 -> ../sr0
lrwxrwxrwx 1 root root 6 10▒▒  6 2018 2:0 -> ../fd0
lrwxrwxrwx 1 root root 7 10▒▒  6 2018 253:0 -> ../dm-0
lrwxrwxrwx 1 root root 8  1▒▒  7 15:03 7:0 -> ../loop0
lrwxrwxrwx 1 root root 8 10▒▒  6 2018 7:1 -> ../loop1
lrwxrwxrwx 1 root root 8 10▒▒  6 2018 7:2 -> ../loop2
lrwxrwxrwx 1 root root 8 10▒▒  6 2018 7:3 -> ../loop3
lrwxrwxrwx 1 root root 8 10▒▒  6 2018 7:4 -> ../loop4
lrwxrwxrwx 1 root root 8 10▒▒  6 2018 7:5 -> ../loop5
lrwxrwxrwx 1 root root 8 10▒▒  6 2018 7:6 -> ../loop6
lrwxrwxrwx 1 root root 8 10▒▒  6 2018 7:7 -> ../loop7
lrwxrwxrwx 1 root root 6 10▒▒  6 2018 8:0 -> ../sda
lrwxrwxrwx 1 root root 7 10▒▒  6 2018 8:1 -> ../sda1
lrwxrwxrwx 1 root root 7 10▒▒  6 2018 8:2 -> ../sda2
lrwxrwxrwx 1 root root 7 10▒▒  6 2018 8:3 -> ../sda3

**Comment by dbwiddis** [comment]
Well, I don't see anything obvious. I'll just try to ignore the failed device and continue with the loop...

**Comment by lixiaochun** [comment]
greate idea， thank you for your update：）

**Comment by dbwiddis** [comment]
I've just pushed the fix to SNAPSHOT. Can you test it?

**Comment by lixiaochun** [comment]
sorry， I downloaded the SNAPSHOT and try to build  but it failed because some urls in pom,xml are not reachable due to private network and company firwall....,is there any way to get the SNAPSHOT jar directly?

**Comment by dbwiddis** [comment]
There should be [a link on the README](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=com.github.oshi&a=oshi-core&v=4.5.0-SNAPSHOT&e=jar) that redirects.

The snapshot repository should be reachable here, to grab the latest:
https://oss.sonatype.org/service/local/repositories/snapshots/content/com/github/oshi/oshi-core/4.5.0-SNAPSHOT/oshi-core-4.5.0-20200213.060129-1.jar

**Comment by lixiaochun** [comment]
I test with snapshot, and the same error occurs
Exception in thread "main" java.lang.NullPointerException
        at oshi.hardware.platform.linux.LinuxDisks.getDisks(LinuxDisks.java:129)
        at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.getDiskStores(LinuxHardwareAbstractionLayer.java:78)
        at com.td.isp.Main.main(Main.java:244)

I guess devnode should be null...
if (!devnode.startsWith("/dev/loop") && !devnode.startsWith("/dev/ram")) {

**Comment by dbwiddis** [comment]
I think you grabbed one snapshot too early (or I linked one). I forgot the `continue` so that line is now 130 and the current line 129 is a comment. Sorry about that.

**Comment by dbwiddis** [comment]
Latest is https://oss.sonatype.org/service/local/repositories/snapshots/content/com/github/oshi/oshi-core/4.5.0-SNAPSHOT/oshi-core-4.5.0-20200213.061617-2.jar

**Comment by lixiaochun** [comment]
yes, I tested using the latest vesion once again, no NullPointException errors.
in my enviroment the output of get disk is empty, maybe something is unusual or wrong for my OS,
i will check myself, thank you for your support:)
