### ISSUE TITLE
autofs filesystems not detected as pseudo or network FS

### ISSUE THREAD

**Issue by Space2Man** [oshi/oshi#1104]
Hi,

I just tested OSHI 4.4.0 and found out that NFS filesystems which are mounted from automounter via /etc/auto.direct are still detected as local filesystems. Also the info seems strange:

`13/Feb/2020 11:17:58,433- DEBUG FilesystemStats: Found FileStore: /ixos/devices/backup/ixos6_18, {"volume":"/etc/auto.direct","type":"autofs","mount":"/ixos/devices/backup/ixos6_18","freeSpace":62603329536,"usableSpace":62603329536,"freeInodes":31876197,"options":"rw,relatime,fd=12,pgrp=9690,timeout=600,minproto=5,maxproto=5,direct","UUID":"","totalSpace":1932735283200,"description":"Mount Point","logicalVolume":"","totalInodes":31876689,"name":"/etc/auto.direct"}
`

I just checked /proc mounts and there are two entries for that:

```
# cat /proc/mounts | grep /ixos/devices/backup/ixos6_18
/etc/auto.direct /ixos/devices/backup/ixos6_18 autofs rw,relatime,fd=12,pgrp=9690,timeout=600,minproto=5,maxproto=5,direct 0 0
xd00387a:/vol/ix20872_18/ixos6_18 /ixos/devices/backup/ixos6_18 nfs rw,sync,relatime,vers=3,rsize=32768,wsize=32768,namlen=255,acregmin=0,acregmax=0,acdirmin=0,acdirmax=0,hard,noac,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.253.19.169,mountvers=3,mountport=4046,mountproto=tcp,local_lock=none,addr=10.253.19.169 0 0

```
The nfs filesystem is filtered correctly but I guess autofs needs to be added to the pseudo filesystems. Otherwise the autofs mounts get triggered when getFileStores() is called.

**Comment by Space2Man** [comment]
What do you think? Is autofs a pseudo filesystem or a network filesystem? I think it's more a pseudo filesystem...

**Comment by Space2Man** [comment]
Wouldn't all the filesystems which are "nodev" filesystems be either pseudo or network?

```
# cat /proc/filesystems 
nodev	sysfs
nodev	rootfs
nodev	bdev
nodev	proc
nodev	cgroup
nodev	cpuset
nodev	tmpfs
nodev	devtmpfs
nodev	debugfs
nodev	securityfs
nodev	sockfs
nodev	pipefs
nodev	anon_inodefs
nodev	devpts
nodev	ramfs
nodev	hugetlbfs
	iso9660
nodev	pstore
nodev	mqueue
nodev	usbfs
	ext3
nodev	fuse
	fuseblk
nodev	fusectl
nodev	binfmt_misc
nodev	autofs
nodev	rpc_pipefs
nodev	nfsd
nodev	nfs
nodev	nfs4
	ext2
```

**Comment by Space2Man** [comment]
Just did a scan over multiple systems with RedHat 6, 7 and SLES 11, 12 and I see the following virtual filesystems:

```
nodev anon_inodefs
nodev autofs
nodev bdev
nodev binfmt_misc
nodev bpf
nodev cgroup
nodev cifs
nodev configfs
nodev cpuset
nodev dax
nodev debugfs
nodev devpts
nodev devtmpfs
nodev drm
nodev ecryptfs
nodev fuse
nodev fusectl
nodev hugetlbfs
nodev inotifyfs
nodev mqueue
nodev nfs
nodev nfs4
nodev nfsd
nodev pipefs
nodev proc
nodev pstore
nodev ramfs
nodev rootfs
nodev rpc_pipefs
nodev securityfs
nodev selinuxfs
nodev sockfs
nodev sysfs
nodev tmpfs
nodev tracefs
nodev usbfs
```

I will try to create a pull request.

**Comment by dbwiddis** [comment]
Sounds good, thanks!

Probably want to split that list out between network and pseudo, and create another constant in the `AbstractFileSystem` class.  I think each OS had a different list of pseudo-FS but they all probably should be the same.

**Comment by Space2Man** [comment]
I have created a pull request #1105 ... I have gathered data from >1k systems running various SuSE und RedHat releases. I also added the ones from current Arch and Gentoo. So I hope I have a complete list now and I tried to explain what they are used for.

**Comment by Space2Man** [comment]
Only regarding fuse I am not so sure if it's really a pseudo filesystem ...
