### ISSUE TITLE
Adding a dependency to Guava

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1112]
I've long tried to keep OSHI free of external dependencies, but I think it's time to add one to Guava.  After the third instance of "roll your own" code (some StringUtils, the Memoizer, and most recently the Pair object) I think it will make things easier all around to have to reinvent less.

**Comment by cilki** [comment]
Guava adds all of this other stuff too:
```
com.google.guava:guava:28.2-jre
|    +--- com.google.guava:failureaccess:1.0.1
|    +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
|    +--- com.google.code.findbugs:jsr305:3.0.2
|    +--- org.checkerframework:checker-qual:2.10.0
|    +--- com.google.errorprone:error_prone_annotations:2.3.4
|    \--- com.google.j2objc:j2objc-annotations:1.3
```
However, it's so convenient that I support inclusion (with the hope that one day it might become modular).

**Comment by dbwiddis** [comment]
It looks like we can probably [exclude all but one of those](https://github.com/google/guava/wiki/UseGuavaInYourBuild#what-about-guavas-own-dependencies) but won't know until we test.   

But it's still a rather large jar by itself, so perhaps this should be carefully considered.  I do see many references to [ProGuard](https://www.guardsquare.com/en/products/proguard) as an option for reducing the size to what's needed.

**Comment by hazendaz** [comment]
A large portion of guava is in jdk8.  You may want to exhaust jdk items before adding.  Most projects use guava anyways along with all their deps.  While some are likely not runtime deps, they should fix but its negotiable as they are small APIs.

FYI.  Waffle is using guava too.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by XakepSDK** [comment]
Please, no. If you wish to use guava, could you please minimize, relocate and shade it in oshi's jar?

**Comment by dbwiddis** [comment]
I think I’ll stick to using the source as inspiration but only including the minimal needs.   I keep thinking of doing more caching and then revert to thinking that should be the user’s responsibility.
