### ISSUE TITLE
OSHI: writing 100k lines like: LinuxDisks: Failed to retrieve devnode for device 139857818616464

### ISSUE THREAD

**Issue by Space2Man** [oshi/oshi#1113]
Hi,

we have rolled out a new version of OSHI and on some systems we see the following error being written >100k times (within a couple of seconds):

```
20/Feb/2020 12:02:20,186- WARN  LinuxDisks: Failed to retrieve devnode for device 139858081186928
20/Feb/2020 12:02:20,186- WARN  LinuxDisks: Failed to retrieve devnode for device 139858081188368
20/Feb/2020 12:02:20,186- WARN  LinuxDisks: Failed to retrieve devnode for device 139858081190624
```

And the number only increases by small amounts. Is this working correctly in an error case or is it looping constantly inside the while(true)?

**Comment by Space2Man** [comment]
Btw. the process consumed about 20G of memory and died with:

```
Exception in thread "main" java.lang.OutOfMemoryError: native memory exhausted
        at java.lang.ClassLoader.findLoadedClassImpl(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:536)

```

**Comment by dbwiddis** [comment]
Whatever changed probably happened in #1103.

**Comment by dbwiddis** [comment]
For clarity:  the #1103 PR missed adding a "continue" after the log statement, that was added in a separate commit.  But that's clearly the new log error.  What I don't get is why those many lines weren't previously failing with an NPE as reported in #1102.

**Comment by dbwiddis** [comment]
As for the incrementing number, it's just a pointer value as a "handle" to the device, so incrementing doesn't seem abnormal as it might just grab a new pointer on the next iteration.  But the OOM error implies a possible resource leak.  The `Udev.INSTANCE.udev_device_unref(device);` is probably being skipped.

**Comment by Space2Man** [comment]
The question is: where does it continue after line 127 ...

**Comment by Space2Man** [comment]
The system is SuSE as well btw ...

**Comment by Space2Man** [comment]
Before we were using OSHI 3.13.x ...

**Comment by Space2Man** [comment]
I think it will just run the loop again and skip:

            entry = Udev.INSTANCE.udev_list_entry_get_next(oldEntry);
            Udev.INSTANCE.udev_device_unref(device);

That sounds like an indefinite loop!

**Comment by dbwiddis** [comment]
> That sounds like an indefinite loop!

Oops. 😬

**Comment by dbwiddis** [comment]
So we have two issues here.   First, the infinite loop/resource leak that I'll get fixed pronto.

A different issue is why the udev calls are failing on SuSE.

**Comment by dbwiddis** [comment]
OK, #1114 fixes the endless loop/resource leak issue, and is in 4.5.0-SNAPSHOT right now.  Still not sure why the udev code is failing on SuSE in 4.x but didn't fail in 3.x.

**Comment by Space2Man** [comment]
Question is what triggers it failing ... it might not fail all the time ... but if it failed it was critical now.

**Comment by lixiaochun** [comment]
@dbwiddis  perfect， thank you for your support,  I did test once again using snapshort verion today in my env,it works properly ：）

**Comment by dbwiddis** [comment]
4.4.2 is released with this fix.

**Comment by Space2Man** [comment]
Hi, yes, I have seen that this morning already. But we will start with the rollout on Monday :)

**Comment by Space2Man** [comment]
FYI: I just did some investigation and found out that all systems that were affected are running SuSE release 11 patchlevel 3 or 4 ...

**Comment by dbwiddis** [comment]
Perhaps related to the issue I noted on #1102, or perhaps not!

**Comment by Space2Man** [comment]
They are all OS clusters ... Veritas cluster in this case ... maybe this is somehow related to the shared disks? What command fails? Can I run that on the command line?

**Comment by dbwiddis** [comment]
Looks like lsblk was problematic on VMware but not sure if you’d see the same results.  The link indicates versions that have the bug (CD-Rom emulation) fixed.
