### ISSUE TITLE
`com.github.oshi:oshi-parent:4.5.1` missing in Maven Central

### ISSUE THREAD

**Issue by mprins** [oshi/oshi#1146]
Something must have gone awry when publishing version 4.5.1 as the `oshi-parent` module is missing from Maven Central.

Check https://repo.maven.apache.org/maven2/com/github/oshi/oshi-parent/4.5.1/ which only has the `.asc` PGP signature but not the `oshi-parent-4.5.1.pom` file or the other checksum files.

Perhaps you can manually (re)publish the parent module? as it it now this wil cause any maven build to fail after upgrading eg. `oshi-core` to 4.5.1 because the dependencies cannot be resolved properly.

**Comment by dbwiddis** [comment]
Not sure if I can fix 4.5.1 but I will try a 4.5.2....

**Comment by dbwiddis** [comment]
Made it as far as staging this time...
![image](https://user-images.githubusercontent.com/9291703/77178574-7d61a500-6a84-11ea-9c98-3486e3da7037.png)

**Comment by dbwiddis** [comment]
OK, 4.5.2 is released.  May take a few hours to show up in the search.  I'll leave this issue open for about 24 hours for anyone else stumbling on the problem.

**Comment by mprins** [comment]
:tada:  just upgraded my project to 4.5.2 succesfully.

Thanks

**Comment by dbwiddis** [comment]
Woot!  And all the files are at https://repo.maven.apache.org/maven2/com/github/oshi/oshi-parent/4.5.2/

**Comment by dbwiddis** [comment]
As for what happened, I think I know.  I had had a few failed builds trying to debug a maven plugin, and prior to the release that "worked" had clicked on the OSS gui to "drop" the previous staging repository, a few seconds before kicking off the new build.   I suspect the actual drop was delayed a few more seconds and it deleted the first few files uploaded, namely the missing parent pom.    

I'll make a note to be a bit more patient the next time something like this happens.
