### ISSUE TITLE
Linux proc symlinks may show as (deleted)

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1153]
In the category of "things a newly spun up VM won't catch in CI"...

Per [`man proc`](http://man7.org/linux/man-pages/man5/proc.5.html):

> /proc/[pid]/exe
>               Under Linux 2.2 and later, this file is a symbolic link containing the actual pathname of the executed command.  This symbolic link can be dereferenced normally; attempting to open it will open the executable.  You can even type /proc/[pid]/exe to run another copy of the same executable that is being run by process [pid]. 

This is the behavior we've been relying on to read the 32-bit or 64-bit ELF header. But:
> If the pathname has been unlinked, the symbolic link will contain the string '(deleted)' appended to the original pathname.  In a multi‐threaded process, the contents of this symbolic link are not available if the main thread has already terminated (typically by calling pthread_exit(3)).

This is rarely the case for processes, but is often the case for services after the system has been up for a while.  The "path" is still correct, and for services almost always still present in the filesystem. Unsurprisingly, an attempt to read the symbolic link `/usr/bin/foo (deleted)` fails.

We need to check whether the resolved path ends in `(deleted)` and remove that string prior to further processing the path.

**Comment by dbwiddis** [comment]
I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to open source before. This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. :-) 

As noted in the comment above, the symbolic link for a `/proc/pid/exe` may include the string "(deleted)" after the filename if the originating process thread has terminated (common for services).  [This link explains more](https://unix.stackexchange.com/questions/197854/how-does-the-proc-pid-exe-symlink-differ-from-ordinary-symlinks).  Your mission, should you choose to accept it, is to remove that extra text from the string.

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  We'll follow those steps, and I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- In the [`LinuxOperatingSystem`](https://github.com/oshi/oshi/blob/f0e11a66ade552dff4a93b82d6de639a7c5f133f/oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java#L241) class, the `path` string at line 241 may contain " (deleted)" at the end of the string.  Insert new code immediately following this to remove the extra text if necessary.
   - I would suggest calculating `path.indexOf(" (deleted)")` and if the result is not `-1` then use `substring()` to trim `path`, unless you have a better idea.
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

**Comment by jlangst6** [comment]
Hello! I had my go at this, let me know if I did anything wrong or anything needs to be improved upon! This is my first open-source contribution, so I'm still getting used to things. I'd like to thank you @dbwiddisfor for putting the time and writing such a detailed issue. Let me know if there are any issues with my pull request at all, thanks!
