### ISSUE TITLE
Memory leak in HWDiskStore.updateAttributes() on Linux

### ISSUE THREAD

**Issue by Sebastian-0** [oshi/oshi#1162]
I recently updated my OSHI dependency from 3.12.2 to 4.6.0 and then I noticed that the memory usage starts to increase over time. Initially I thought the problem was in my code but the memory is not allocated on the heap but in native objects.

After some investigation I realized that there appears to be a memory leak in `HWDiskStore.updateAttributes()` on Linux (x64). Like I said, the java heap stays the same size but the memory usage of the process increases every time this method is invoked. I did a memory dump of the process and it was filled with disk/partition information further hinting of an issue.

You can easily reproduce the problem by running the following code with a fixed heap size (`-Xms100m -Xmx100m`):
```
public class MemTest {
	public static void main(String[] args) {
		SystemInfo info = new SystemInfo();
		HWDiskStore[] disks = info.getHardware().getDiskStores();
		while (true) {
			for (HWDiskStore disk : disks) {
				disk.updateAtrributes();
			}
		}
	}
}
```
After ~4 minutes this reaches 1.2GB of memory usage on my machine (2 disks):
![image](https://user-images.githubusercontent.com/6851439/78757553-f87bf400-797c-11ea-98c6-fe0058d17050.png)

Meanwhile this is what the heap looks like in JVisualVM:
![image](https://user-images.githubusercontent.com/6851439/78757659-25c8a200-797d-11ea-8c66-67ec0b2e493c.png)

I saw that there are other similar issues that were closed but I did not find any solution there. Unfortunately I don't have time right now to debug this any further myself. Please tell me if you need more information!

**Comment by dbwiddis** [comment]
Thanks for the report, but can you be a bit more clear on how you're measuring the memory utilization? Linux will have "free" memory drop to near zero but the memory is "available", just recycled.   If you leave the process running for a long time, do you eventually encounter an out-of-memory situation?

I'll take a look at the code, which manipulates udev handles... it's possible there's a handle leak...

**Comment by Sebastian-0** [comment]
I'm measuring the size of resident anonymous memory (RSSAnon in `/proc/[pid]/status`). I get the same memory usage if I look in other tools like ksysguard (KDE task manager). I haven't encountered OOM, but on the other hand I haven't left it running long enough.

**Comment by dbwiddis** [comment]
Well, I've been able to reproduce something similar using your code.  I don't get an error but the process just dies somewhere between the 50,000th and 51,000th iteration.  Given that Linux has a maximum of 65536 handles, this does indeed look like a handle leak.  Unfortunately, I've been staring at the code for an hour and can't see an obvious leak.   

Which means it's a non-obvious one. 😬

**Comment by Sebastian-0** [comment]
But we know that it worked (or appeared to work?) in 3.12.2 so in essence we could binary search over versions until we find the change that introduced the problem. I took a quick look at the old version and the code hasn't changed that much so if the bug is in OSHI (and not in JNA) it should be possible to find.

**Comment by dbwiddis** [comment]
Already ahead of you on that.  :). It worked fine in 4.3.0.  I suspect #1114 broke it.  Still confirming...

**Comment by dbwiddis** [comment]
Binary search ended up slower than just iterating backwards... it worked fine in 4.5.2 but not 4.6.0.  Also the speed of the updates is noticeably different...

**Comment by dbwiddis** [comment]
OK, I think I found it.  The speed issues are from an intentional move away from a cached mounts map for thread safety and aren't a problem.  But a change in the logic did introduce a leak: [the `break;` on line 123](https://github.com/oshi/oshi/blob/1e56bf1be27f44fdedcfb98dc65f95443cccb5da/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxDisks.java#L122) ends up bypassing the [udev_device_unref() on line 147](https://github.com/oshi/oshi/blob/1e56bf1be27f44fdedcfb98dc65f95443cccb5da/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxDisks.java#L147).

**Comment by Sebastian-0** [comment]
Great! I hope that fixes the issue :) I can try to validate it on my side later today.

**Comment by dbwiddis** [comment]
I'm updating SNAPSHOT right now with a very temporary fix (just adding `Udev.INSTANCE.udev_device_unref(device);` before the `break;`) if you'd like to test that and confirm (although it's obvious now).  It's late here (2:30am) so I'm off to bed and will commit a permanent fix tomorrow with a clear head (and caffeine.)

**Comment by Sebastian-0** [comment]
I can confirm that this seems to have solved my issue, however my task manager will have to run for a while before I can say for sure. Thanks for the quick response and release!

**Comment by dbwiddis** [comment]
Your code snippet was actually the perfect way to test this and I'm pretty confident this particular one was squashed.  Let's hope there's no others!
