### ISSUE TITLE
AIX UNIX ppc64 7 or higher support

### ISSUE THREAD

**Issue by battousai-dev** [oshi/oshi#1166]
is there a plan to support the aix unix ppc/ppc64 platform?

**Comment by dbwiddis** [comment]
I would love to create an AIX port but I do not have access to an AIX machine to develop/test.

**Comment by dbwiddis** [comment]
Do you know anyone with an AIX machine that I could coach through the steps to extend capability, and/or any way that I could access one to do it myself?

**Comment by Space2Man** [comment]
Hi,

I can't promise anything yet but maybe I get access to an AIX machine, then I could try to help ... what infos would you need?

Best regards, Space

**Comment by dbwiddis** [comment]
It would be good to know if anything in the existing ports does work, for starters.  I'd start by adding AIX to the `PlatformEnum`, and then in `SystemInfo` try adding it to the case statements for either FreeBSD or Solaris and see if anything works.  

Whatever doesn't work, itemize and find code for on various AIX "cheat sheets" on the net. Run commands and save their output in text files that could be referenced to write code.

**Comment by dbwiddis** [comment]
Managed to get a diagnostic version of AIX installed in `qemu`.  Pretty limited.
```
# uname -a
AIX 000000000000 2 7 000000000000

# mount
  node       mounted        mounted over    vfs       date        options      
-------- ---------------  ---------------  ------ ------------ --------------- 
         /dev/ram0        /                jfs    Jan 01 00:00 rw              
         /dev/ramdisk0    /mnt             jfs    May 10 02:23 rw,nointegrity  
         /mnt             /tmp             namefs May 10 02:23 rw     
         
# lscfg
INSTALLED RESOURCE LIST

The following resources are installed on the machine.
+/- = Added or deleted from Resource List.
*   = Diagnostic support not available.
        
  Model Architecture: chrp
  Model Implementation: Uni-Processor, PCI bus
        
+ sys0               System Object
+ sysplanar0         System Planar
* vio0               Virtual I/O Bus
* vscsi0             n/a
* cd0                n/a
* vsa0               LPAR Virtual Serial Adapter
* vty0               Asynchronous Terminal
* pci0               PCI Bus
+ L2cache0           L2 Cache
+ mem0               Memory
+ proc0              Processor

# df
Filesystem    512-blocks      Free %Used    Iused %Iused Mounted on
/dev/ram0         393216    104808   74%     1122     3% /
/dev/ramdisk0    1048576   1015560    4%       17     1% /mnt
/mnt             1048576   1015560    4%       17     1% /tmp
```
No internet access to even attempt to download and run oshi... :grin:

**Comment by dbwiddis** [comment]
This is going to happen. :)

```
Welcome to AIX7 ...member of polarhome.com realm
oshi@gate.polarhome.com's password:
Last login: Sat Jun 13 21:27:19 DFT 2020 on ssh from 192.168.10.36
Last login: Sat Jun 13 21:27:19 DFT 2020 on ssh from 192.168.10.36
[YOU HAVE NEW MAIL]
---------------------------
Your system limitations are:
---------------------------
Disk quotas for user oshi (uid 4795):
     Filesystem   blocks      quota    limit    grace    files      quota    limit    grace
          /home      456          0   204800                17          0     5000
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) soft
file size               (blocks, -f) 1048575
max memory size         (kbytes, -m) 32768
open files                      (-n) 200
pipe size            (512 bytes, -p) 64
stack size              (kbytes, -s) 32768
cpu time               (seconds, -t) 2000
max user processes              (-u) 128
virtual memory          (kbytes, -v) unlimited
---------------------------
Host aix7.polarhome.com at your service.
AIX aix7 1 7 000ACFDE4C00 powerpc AIX
 23:54pm  up 12 days 13:48,  3 users,  load average: 2.16, 2.31, 2.57
-bash-4.2$ uname -a
AIX aix7 1 7 000ACFDE4C00 powerpc AIX
```

**Comment by dbwiddis** [comment]
Some notes on where to find things when I get around to doing this:
 - [ ] System config [quick reference](http://softpanorama.org/Commercial_unixes/AIX/Reference/getting_system_configuration_parameters_in_aix.shtml)
 - [ ] Useful commandlines `prtconf`, `lscfg`, `lsdev`, `lsattr`, `oslevel`, `lslpp`, `lsvg`, `lslv`, `netstat` (see above link)
 - [ ] Process and Thread Data from `/proc`: `/proc/pid/` + `status`, `psinfo`, `lwp/tid/lwpstatus`, `lwp/tid/lwpsinfo` 
 - [ ] Sessions using getutxent like other unixes
 - [ ] CPU, memory, disk, partition, network [from perfstat](https://www.ibm.com/support/knowledgecenter/ssw_aix_72/performancetools/idprftools_perfstat_glob.html)
 - [ ] See `man knlist`,

**Comment by dbwiddis** [comment]
```
2020-06-27 20:06:24.484 [INFO] SystemInfoTest - Initializing System...
2020-06-27 20:06:26.785 [INFO] SystemInfoTest - Checking computer system...
2020-06-27 20:06:27.529 [INFO] SystemInfoTest - Printing Operating System and Hardware Info:
IBM AIX 7 (AIX) build 1
```

![image](https://user-images.githubusercontent.com/9291703/85929048-65a97200-b866-11ea-88f6-a23bb0da4b9d.png)

**Comment by dbwiddis** [comment]
> I can't promise anything yet but maybe I get access to an AIX machine, then I could try to help .

@Space2Man if you have access to an AIX machine with root access, you can help with a few things I can't test on my non-root shell.

For starters, is there a way to know if you are operating with elevated permissions?  Is the output of `sudo -v` different?  Are there environment variables that only exist when you `getconf` under sudo?

**Comment by dbwiddis** [comment]
```
IBM AIX 7.1.0.0 (powerpc) build 7100-00-03-1115
Booted: 2020-06-16T09:12:00Z
Uptime: 11 days, 14:26:11
Running without elevated permissions.
Sessions:
 md, pts/0, 2020-06-26 14:57, (46.19.33.18)
 oshi, pts/1, 2020-06-27 04:45, (73.169.134.6)
System: manufacturer=IBM, model=9114-275, serial number=IBM,0110ACFDE
 Firmware: manufacturer=IBM, name=3F080425, description=unknown, version=RG080425_d79e22_r, release date=unknown
```
