### ISSUE TITLE
swap memory of windows

### ISSUE THREAD

**Issue by battousai-dev** [oshi/oshi#1175]
hi, i'm currently doing some qualifications of oshi version: 4.6.1. it will be use for our project. How oshi get the total swap memory and swap used of windows? is there computation or reference to check or verify if the total swap memory and swap used was correct?

**Comment by dbwiddis** [comment]
You can inspect the source of [WindowsVirtualMemory](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsVirtualMemory.java).  The total paging size file is retrieved from the WinAPI's native [GetPerformanceInfo()](https://docs.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-getperformanceinfo) function, then subtracting PhysicalTotal from the CommitLimit.  Swap usage is then calculated as a percent of that total using the Performance Counter "Paging File/% Usage".

You should be able to verify the paging file size through the Windows system properties (System>Advanced>Performance) and/or locating the `pagefile.sys` (in root of C: drive as default, but hidden) and checking its size, and the percentage use using the above-referenced counter in PerfMon.exe or using WMI (command line `wmic path Win32_PerfRawData_PerfOS_PagingFile`).

**Comment by dbwiddis** [comment]
FYI on my current machine, 
Oshi's output: `{"swapTotal":9040408576,"swapUsed":1572646912}`

The actual pagefile:
```
C:\>dir /a pagefile.*
04/22/2020  01:04 AM     9,040,408,576 pagefile.sys
```
The percent usage (units are in 4096-byte pages):
```
C:\>wmic path Win32_PerfRawData_PerfOS_PagingFile get Name,PercentUsage,PercentUsage_Base
Name                 PercentUsage  PercentUsage_Base
\??\C:\pagefile.sys  383947        2207131
_Total               383947        2207131
```
383,947 * 4096 = 1,572,646,912
2,207,131 * 4096 = 9,040,408,576

**Comment by battousai-dev** [comment]
thanks @dbwiddis!

I executed the command systeminfo. 
C:\>systeminfo

sample result:
OS Name:                   Microsoft Windows Server 2012 R2 Standard
OS Version:                6.3.9600 N/A Build 9600
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Server
OS Build Type:             Multiprocessor Free
Registered Owner:          Windows User
Registered Organization:   
Original Install Date:     12/11/2015, 1:56:11 AM
System Boot Time:          4/22/2020, 12:48:34 AM
System Manufacturer:       innotek GmbH
System Model:              VirtualBox
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 9 GenuineIntel ~2712 Mhz
BIOS Version:              innotek GmbH VirtualBox, 12/1/2006
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-06:00) Central Time (US & Canada)
**Total Physical Memory:     15,409 MB
Available Physical Memory: 8,165 MB
Virtual Memory: Max Size:  18,225 MB
Virtual Memory: Available: 8,608 MB
Virtual Memory: In Use:    9,617 MB**

The oshi and systeminfo have different values compare with virtual memory and swap memory. Did you consider the values of systeminfo when getting the swap memory and swap total?

**Comment by dbwiddis** [comment]
@battousai-dev ... Welcome to the same confusion I encountered trying to develop this. :) 

What Windows calls "Virtual Memory" includes **both** the physical memory and the swap file.  So it essentially means "all memory available to processes".  On my system, I just ran `systeminfo` and it told me I had `17,718 MB` virtual memory, and `8,117 MB` physical memory.  Doing a little math on my calculator that's a difference of 9601 MB.  

I'm not sure if that's MB or MiB but I do know my swap file size is exactly 10,067,161,088 right now.

9601 * 1024 * 1024 = 10,067,378,176.  (So I guess it was MiB and there's probably some round-off error somewhere.)

If you take OSHI's values for total physical memory and add the total swap file size you should probably get a number that matches the "Max Size" of "Virtual Memory" (with the proper units of MiB!)

Similarly you should take the "In Use" number from the above output and subtract off the "used" physical memory (Total - available) and you'll get the portion of the swap file in use, so using the numbers above, (15409-8165) = 7244 MiB used physical. Subtract that from 9,617 and you have 2373 MiB used swap. So hopefully OSHI's swap used was close to 2,488,270,848...

**Comment by dbwiddis** [comment]
[This Wikipedia article on "Commit Charge"](https://en.wikipedia.org/wiki/Commit_charge) describes what your above output calls "Virtual Memory"

**Comment by battousai-dev** [comment]
@dbwiddis thanks!
