### ISSUE TITLE
oshi 5.0.0 memory virtual in use

### ISSUE THREAD

**Issue by battousai-dev** [oshi/oshi#1195]
i want to clarify the value of virtual in use. Is this in use or free?

oshi values:
memory oshi: Available: 5.8 GiB/15.0 GiB
Memory total: 16157036544
Memory free: 6237302784
Memory used: 9919733760
swap total: 2952790016
swap used: 126771200
swap free: 2826018816
**virtual in use: 6474678272 = 6.47 GB (getVirtualMemory().getVirtualInUse())**
virtual max: 19109826560
memory page size in: 4096
memory virtual page in:  7590956
memory virtual page out: 160643

systeminfo:
Total Physical Memory:     15,409 MB
Available Physical Memory: 6,074 MB
Virtual Memory: Max Size:  18,225 MB
Virtual Memory: Available: 6,609 MB
**Virtual Memory: In Use:    11,616 MB**

sigar values:
memFreePercentage=42.984807796198794, 
memFree=6347313152, 
memUsedPercentage=57.015192203801206, 
memTotal=16157036544, 
memActualFree=6945071104, 
memUsed=9809727488, 
memRam=15408,
memActualUsed=9211965440
swapFree=6518706176,
swapPageIn=597762048,
swapUsed=12591120384,
swapPageOut=160643, 
swapTotal=19109826560

**Comment by dbwiddis** [comment]
Thanks for finding the first bug in 5.0.0 (and also 4.7.1).  🤦 

Yes, it's supposed to be "in use" but it appears I subtracted off "in use" from "max" to get free:
`perfInfo.CommitLimit.longValue() - perfInfo.CommitTotal.longValue()` should just be `perfInfo.CommitTotal.longValue()`.  Guess we'll have 5.0.1 and 4.7.2 soon...
