### ISSUE TITLE
Refactor duplicated queryTcpnetstat method

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1200]
I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to an open source project on GitHub before.

The main goal of this task is to learn the process for submitting a PR -- the GitHub equivalent of writing a "Hello World!" program.  If you already know the PR workflow, please leave this issue for someone else!

Please comment to "claim" this issue if you want to work on it.  If someone else has claimed this (look at "Assignees" to the right) please let them attempt it.

This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. :-) 

There is a duplicated method `queryTcpnetstat()` in both [MacInternetProtocolStats.java](https://github.com/oshi/oshi/blob/dcc0ed036aed92220c78ed2a515ec8c991dd3066/oshi-core/src/main/java/oshi/software/os/mac/MacInternetProtocolStats.java#L136) and [FreeBsdInternetProtocolStats.java](https://github.com/oshi/oshi/blob/dcc0ed036aed92220c78ed2a515ec8c991dd3066/oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdInternetProtocolStats.java#L94).  Your task, should you choose to accept it:

1. Create a new class in `oshi.driver.unix`. I'd suggest `NetStatTcp` or `NetStat`.  
2. Copy the `queryTcpnetstat()`method over from either of the above classes to the new class, but make it `public` and add javadocs.
3. Delete the method from the above classes and redirect the memoized method to point to the new location.
4. Update imports as required (your IDE may do this for you).

You may find it easier to create the new class by starting with a copy of any of the existing classes in the `oshi.driver` packages, which will include a lot of the boilerplate you want to repeat (license, ThreadSafe annotation, public final class keywords, private constructor.

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  We'll follow those steps, and I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- Make the changes described above.
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

**Comment by zhoujc999** [comment]
Hi @dbwiddis,
May I work on this issue?

**Comment by dbwiddis** [comment]
It's all yours, @zhoujc999 !

**Comment by Manas-Goel** [comment]
Hey @dbwiddis , I would like to work on this issue. Is it still open?

**Comment by dbwiddis** [comment]
Sorry, @Manas-Goel it was claimed a few hours before you asked. I might have another small project you can work on if you'd like?

**Comment by Manas-Goel** [comment]
@dbwiddis Sure. I will try my best.

**Comment by dbwiddis** [comment]
@Manas-Goel at the bottom of the `LinuxGlobalMemory` class is a method `parseMeminfo()`.  Currently it only looks for `"kB"` to multiply the value by 1024.  I'd like to change that to also multiply `"MB"` by 1024*1024 (or use `<< 20`).  Even better, it would be an improvement if we could do the math based only in the first character (`split[2].charAt(0)`).

**Comment by dbwiddis** [comment]
Actually, @Manas-Goel a better thing is just to delete that method and instead call `ParseUtil.parseDecimalMemorySizeToBinary()` that does the same thing, better.

**Comment by Manas-Goel** [comment]
Thanks @dbwiddis . I will try to do it.

**Comment by Manas-Goel** [comment]
I made my first pull request 😄 @dbwiddis

**Comment by zhoujc999** [comment]
Hi @dbwiddis,
I made my first pull request.
