### ISSUE TITLE
OSHI 10th anniversary virtual happy hour 🍾🙌🎉

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1201]
[OSHI was started](https://code.dblock.org/2010/06/23/introducing-oshi-operating-system-and-hardware-information-java.html) on June 23, 2010, and we're coming up on the project's 10 year anniversary! 

In celebration of this milestone, I'd like to host an online happy hour were we can all bring our favorite beverage 🍷 🍺 🥃 (or the official "OSHI Martini" 🍸 in the comment below) and toast the project's success!  

I'm setting the date for this meetup at Tuesday, 23 June 2020 at 1pm PDT / 4pm EDT / 2000 GMT /  9pm BST / 10pm CEST.  [Here's a countdown to the event](https://www.timeanddate.com/countdown/generic?iso=20200623T13&p0=234&msg=OSHI+10th+Anniversary+online+meetup&font=cursive).

Here's the meeting info:
[Join Zoom Meeting](https://us04web.zoom.us/j/76760427867?pwd=cE9PNUhSMmNwR04rTjdlTDZWMVRBQT09)
Meeting ID: 767 6042 7867
Password: 9Yb1k0

[Add to Google Calendar](https://us04web.zoom.us/meeting/upIqcemsrDwiHNNaev16THMd1z-ZeHPvTZ69/calendar/google/add)
[Add to Outlook Calendar](https://us04web.zoom.us/meeting/upIqcemsrDwiHNNaev16THMd1z-ZeHPvTZ69/ics)

**Comment by dbwiddis** [comment]
As promised, a bartender has concocted a custom celebratory cocktail for us!  Introducing...

### The OSHI Martini

#### Ingredients:
 - 3 oz. Sobieski Vodka or espresso flavored vodka
 - 3/4 oz. Drambuie Liquor
 - 3/4 oz. white grape juice
 - Orange peel

#### Directions:
In a martini shaker or tall glass filled with ice, combine the vodka, Drambuie, and white grape juice. Shake well and pour into a martini glass. Using a match or lighter, carefully and lightly burn and smoke the orange peel to create a toasted orange essence for garnish. Twist the peel over the cocktail and garnish drink.

#### Tasting notes:
This drink is a wonderful combination of “hard” and “soft” elements quite befitting to the OSHI project. Vodka is a neutral spirit which falls in the realm of soft; however, Sobieski vodka is made from rye. The rye base will compliment the hardness of the scotch whiskey essence of the Drambuie. Soft pops in again with the undertones of honey and vanilla in the Drambuie along with the complimenting sweetness of the white grape juice. The final addition, the burned orange peel, will add another complex or hard element to the drink. This drink is very luxurious and yet a perfect celebratory, summer cocktail.

While the Java language suggests that coffee would be an appropriate element, not everyone enjoys that flavor in a martini. By substituting espresso vodka for the Sobieski, those who would enjoy the taste of a toasty java will enjoy this versatile recipe. The honey, vanilla and smoked orange essence all blend well with a coffee flavor.

**Comment by dblock** [comment]
Love this! I accidentally stumbled upon this issue (although I do have this date on my calendar ;)). 

I suggest doing a `git log` and extracting emails for all contributors with [fue](https://github.com/dblock/fue) and letting them know directly about the event.

**Comment by dbwiddis** [comment]
Invites sent!  A few contributors like @Space2Man and @YoshiEnVerde didn't leave real email addresses in their commits, though. Tsk. 😄

**Comment by dbwiddis** [comment]
Reminder!  6 days away!

**Comment by dbwiddis** [comment]
This is happening tomorrow!

Meeting Info:
[Join Zoom Meeting](https://us04web.zoom.us/j/76760427867?pwd=cE9PNUhSMmNwR04rTjdlTDZWMVRBQT09)
Meeting ID: 767 6042 7867
Password: 9Yb1k0

[Add to Google Calendar](https://us04web.zoom.us/meeting/upIqcemsrDwiHNNaev16THMd1z-ZeHPvTZ69/calendar/google/add)
[Add to Outlook Calendar](https://us04web.zoom.us/meeting/upIqcemsrDwiHNNaev16THMd1z-ZeHPvTZ69/ics)

**Comment by dbwiddis** [comment]
![image](https://user-images.githubusercontent.com/9291703/85358379-6938a400-b4c8-11ea-8e0b-c44beaa0ad21.png)

**Comment by Space2Man** [comment]
Hi
still there?

**Comment by dbwiddis** [comment]
Logging back in!
