### ISSUE TITLE
swap memory computation of different OS

### ISSUE THREAD

**Issue by battousai-dev** [oshi/oshi#1202]
hi, i want to confirm if the computation of swap memory for windows 2019 and RHEL 7.6 (Red Hat) is same approach? The result of swap memory of RHEL 7.6 matches with sigar data. 

Here's the data from different OS:
OS: Windows 2019 

 OSHI 5.0.1 data: 
 Memory total: 8589463552 
 Memory free: 1490542592 
 Memory used: 7098920960 
 swap total: 5368709120 
 swap used: 1682198528 
 swap free: 3686510592 
 virtual use: 11396337664 
 virtual max: 13958172672 
 memory page size in: 4096 
 memory swap page in: 70277728 
 memory swap page out: 21729555 

 systeminfo data: 
 OS Name: Microsoft Windows Server 2019 Standard 
 Total Physical Memory: 8,192 MB 
 Available Physical Memory: 1,512 MB 
 Virtual Memory: Max Size: 13,312 MB 
 Virtual Memory: Available: 2,714 MB 
 Virtual Memory: In Use: 10,598 MB 

OS: RHEL 7.6 

 OSHI 5.0.1 data: 
 Memory total: 21001953280 
 Memory free: 8823791616 
 Memory used: 12178161664 
 **swap total: 17179860992** 
 **swap used: 3024175104** 
 **swap free: 14155685888** 
 virtual use: 15202336768 
 virtual max: 38181814272 
 memory page size in: 8192 
 memory swap page in: 0 
 memory swap page out: 0 

 sigar 1.6.4 data: 
 memTotal=21474836480, 
 memFree=637018112, 
 memUsed=20837818368, 
 memActualFree=1341264032, 
 memRam=20480, 
 memActualUsed=20133572448 
 **swapFree=14155685888,** 
 swapPageIn=3531882, 
 **swapUsed=3024175104,** 
 swapPageOut=507040, 
 **swapTotal=17179860992**

**Comment by dbwiddis** [comment]
I'm not sure I understand your question.  You have bolded the "swap free/used/total" numbers which are identical for OSHI and SIGAR in your example.  

I do see a difference in the swap pages in and out. OSHI's are 0.  It would be helpful to see the output of `/proc/vmstat`.  OSHI reads from the `pgpgin` and `pgpgout` fields while SIGAR reads from the `pswpin` field and the one immediately after it (`pswpout` I assume).  This may be a bug.

I also see a difference in total memory, which is also a surprise. Both are reading the `MemTotal` field of `/proc/meminfo` and total physical memory shouldn't change.

**Comment by dbwiddis** [comment]
Also, both SIGAR and OSHI read the "SwapTotal" and "SwapFree" fields of `/proc/meminfo` so it does not surprise me that they are identical.

**Comment by battousai-dev** [comment]
is windows vs unix have different approach when computing the swap values?

**Comment by dbwiddis** [comment]
Yes, as the different OS's have different commands available to calculate these.  Windows has an API available in their standard DLL files, while Linux uses the `/proc` filesystem to provide user access to system stats.  There are some native C library functions for some of these things, but the flexibility of some of the `/proc` results are enough that they are the best source.  (And as a pseudo-filesystem they don't involve disk access.)

Swap files are different as well. Windows just has a singular swap file which is in the filesystem like a normal file.  Linux generally uses a separate partition for swap.  It's possible to create a file and designate it as additional swap as well.

**Comment by dbwiddis** [comment]
I'm still very interested in the contents of `/proc/meminfo` and `/proc/vmstat` on that RHEL system, though.  The memory total for OSHI isn't a multiple of 2, so I assume there's a math error somewhere in that computation.  (Also it's off the SIGAR multiple of 2 answer by a factor of ~1.024, implying that someone is multiplying by 1000 instead of 1024 somewhere.)

Also looking in to whether swapping (entire process) vs. paging (a memory page) is the more appropriate in/out measure for the swapfile, and curious how OSHI has 0 there.

**Comment by battousai-dev** [comment]
Thanks for info. I appreciated it.

**Comment by dbwiddis** [comment]
No problem. There still is a difference in sigar's use of "swap" vs. oshi's use of "pages" and I'd really love to see the output of `/proc/meminfo` and `/proc/vmstat` on that RHEL system you were using to evaluate whether I should change oshi's code.

**Comment by battousai-dev** [comment]
Here's the result of the ffg command on RHEL 7.6:
/proc/meminfo
MemTotal:       20541384 kB
MemFree:          557424 kB
MemAvailable:    5517432 kB
Buffers:           54356 kB
Cached:         10445872 kB
SwapCached:         1136 kB
Active:         15439216 kB
Inactive:        3426072 kB
Active(anon):   12361476 kB
Inactive(anon):  1521688 kB
Active(file):    3077740 kB
Inactive(file):  1904384 kB
Unevictable:          12 kB
Mlocked:              12 kB
SwapTotal:       1048572 kB
SwapFree:        1028000 kB
Dirty:               196 kB
Writeback:             0 kB
AnonPages:       8364084 kB
Mapped:          4892696 kB
Shmem:           5518104 kB
Slab:             470468 kB
SReclaimable:     332220 kB
SUnreclaim:       138248 kB
KernelStack:       38320 kB
PageTables:       278544 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    11319264 kB
Committed_AS:   20612552 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      238808 kB
VmallocChunk:   34359310332 kB
HardwareCorrupted:     0 kB
AnonHugePages:   3932160 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      116544 kB

/proc/vmstat
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 1  0  20572 412480  54244 10914764    0    0     6    34    4    8  6  2 92  0  0

**Comment by dbwiddis** [comment]
Wow, thanks.... completely different vmstat format than other linuxes.

**Comment by dbwiddis** [comment]
Actually that looks like the `vmstat` command rather than `cat /proc/vmstat`. Any chance of the other one?

**Comment by battousai-dev** [comment]
cat /proc/vmstat:
nr_free_pages 135990
nr_alloc_batch 3370
nr_inactive_anon 380418
nr_active_anon 3092967
nr_inactive_file 475943
nr_active_file 769776
nr_unevictable 3
nr_mlock 3
nr_anon_pages 1110546
nr_mapped 1223044
nr_file_pages 2625521
nr_dirty 64
nr_writeback 0
nr_slab_reclaimable 83055
nr_slab_unreclaimable 34535
nr_page_table_pages 70656
nr_kernel_stack 2396
nr_unstable 0
nr_bounce 0
nr_vmscan_write 5533
nr_vmscan_immediate_reclaim 0
nr_writeback_temp 0
nr_isolated_anon 0
nr_isolated_file 0
nr_shmem 1379518
nr_dirtied 48669169
nr_written 38440328
numa_hit 2954257169
numa_miss 0
numa_foreign 0
numa_interleave 27841
numa_local 2954257169
numa_other 0
workingset_refault 2770103
workingset_activate 915216
workingset_nodereclaim 0
nr_anon_transparent_hugepages 1920
nr_free_cma 0
nr_dirty_threshold 395539
nr_dirty_background_threshold 131846
pgpgin 27562898
pgpgout 168780971
pswpin 580
pswpout 5533
pgalloc_dma 8
pgalloc_dma32 78054420
pgalloc_normal 2954677757
pgalloc_movable 0
pgfree 3032868826
pgactivate 12371096
pgdeactivate 4724247
pgfault 4972615398
pgmajfault 5990
pglazyfreed 0
pgrefill_dma 0
pgrefill_dma32 771953
pgrefill_normal 4129864
pgrefill_movable 0
pgsteal_kswapd_dma 0
pgsteal_kswapd_dma32 740824
pgsteal_kswapd_normal 4281212
pgsteal_kswapd_movable 0
pgsteal_direct_dma 0
pgsteal_direct_dma32 0
pgsteal_direct_normal 0
pgsteal_direct_movable 0
pgscan_kswapd_dma 0
pgscan_kswapd_dma32 765418
pgscan_kswapd_normal 4371952
pgscan_kswapd_movable 0
pgscan_direct_dma 0
pgscan_direct_dma32 0
pgscan_direct_normal 0
pgscan_direct_movable 0
pgscan_direct_throttle 0
zone_reclaim_failed 0
pginodesteal 0
slabs_scanned 978944
kswapd_inodesteal 1773
kswapd_low_wmark_hit_quickly 30
kswapd_high_wmark_hit_quickly 357
pageoutrun 903
allocstall 0
pgrotated 6101
drop_pagecache 0
drop_slab 0
numa_pte_updates 0
numa_huge_pte_updates 0
numa_hint_faults 0
numa_hint_faults_local 0
numa_pages_migrated 0
pgmigrate_success 0
pgmigrate_fail 0
compact_migrate_scanned 0
compact_free_scanned 0
compact_isolated 0
compact_stall 0
compact_fail 0
compact_success 0
htlb_buddy_alloc_success 0
htlb_buddy_alloc_fail 0
unevictable_pgs_culled 0
unevictable_pgs_scanned 0
unevictable_pgs_rescued 183
unevictable_pgs_mlocked 186
unevictable_pgs_munlocked 183
unevictable_pgs_cleared 0
unevictable_pgs_stranded 0
thp_fault_alloc 64539
thp_fault_fallback 3217022
thp_collapse_alloc 1896
thp_collapse_alloc_failed 60871
thp_split 282
thp_zero_page_alloc 1
thp_zero_page_alloc_failed 0
balloon_inflate 0
balloon_deflate 0
balloon_migrate 0

**Comment by dbwiddis** [comment]
Great, thanks.  Ultimately OSHI and sigar differ in which pair of these stats are reported, and I'm not sure which is better.  I'll keep looking.
```
pgpgin 27562898
pgpgout 168780971
```
or
```
pswpin 580
pswpout 5533
```

**Comment by dbwiddis** [comment]
Closing this, tracking the change in #1223
