### ISSUE TITLE
Handle leak in WindowsPowerSource

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1205]
### First Timers Only

I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to an open source project on GitHub before.

The main goal of this task is to learn the process for submitting a PR -- the GitHub equivalent of writing a "Hello World!" program.  If you already know the PR workflow, please leave this issue for someone else!

Please comment to "claim" this issue if you want to work on it.  If someone else has claimed this (look at "Assignees" to the right) please let them attempt it.

This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. 😄 

### The bug you are fixing

In the `WindowsPowerSource` method `getPowerSource()`, a [handle is created on line 176](https://github.com/oshi/oshi/blob/5b994e4c5650944afb34678fe71ad1e0461f1288/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsPowerSource.java#L176).  It is intended to be [closed on line 300](https://github.com/oshi/oshi/blob/5b994e4c5650944afb34678fe71ad1e0461f1288/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsPowerSource.java#L300).  However, [the `break;` statement on line 296](https://github.com/oshi/oshi/blob/5b994e4c5650944afb34678fe71ad1e0461f1288/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsPowerSource.java#L296) bypasses this closing code.  The code needs to be changed to ensure that handle is closed.

### What to do to fix the bug

1. Define a new `boolean` local variable just before the `for` loop on line 156 to flag whether a battery has been found, initialized to false.
2. In place of the current line 296 `break` statement, toggle the boolean variable to true.
3. Alter the iteration test in the `for` loop at line 156 to also test that the boolean you defined is still false.

### How to submit your change to the repository

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  We'll follow those steps, and I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- Make the changes described above.
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

### Bonus points

This is a little bit more advanced so don't worry about it if you don't want to.  The identical bug exists on the `4.X` branch.  Commit the same fix there (you might find `git cherry-pick` useful!) and submit a second PR against that branch.

**Comment by Bob160** [comment]
May I handle this, @dbwiddis ?

**Comment by dbwiddis** [comment]
Sure, @Bob160! Have at it!

**Comment by Bob160** [comment]
Hello @dbwiddis, wondering where this file is located? Seen an 'AbstractPowerSource.java' but the line numbers mentioned in the issue description do not match the lines in the code.

**Comment by dbwiddis** [comment]
There are links in the original issue posting to the file in OSHI's online code.  It's at 
`oshi/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsPowerSource.java`

**Comment by dbwiddis** [comment]
How's it going, @Bob160 ?  I'm going to want to push another patch release soon for a different bug and would like to include this.  Are you making progress?  Need any assistance?

**Comment by Bob160** [comment]
Hello @dbwiddis. I'm still working on it. Kindly give me some time. Thanks

**Comment by yadunandanbhat** [comment]
Is this still open sir?

**Comment by dbwiddis** [comment]
Sorry, @yadunandanbhat it seems @Bob160 is still working through it.  I can find other things for you to do if you would like! :)

**Comment by yadunandanbhat** [comment]
Yes sir!

**Comment by dbwiddis** [comment]
I'll post a new issue in a moment.

**Comment by Bob160** [comment]
@dbwiddis, I'm still waiting for your guidance on this. I'm not familiar with Java at all. I am willing to attempt this while holding your hand but if you're not okay with that, feel free to reassign this issue to someone else.

Thanks

**Comment by dbwiddis** [comment]
Hi @Bob160. Sorry that I missed your question a few lines up about moving the break.  The original issue actually said to replace the break with a boolean, not move it.  It looks like @yadunandanbhat has taken this one on instead, though. 

The main goal of this was to submit a PR which you have already done on a different issue. :)

**Comment by yadunandanbhat** [comment]
Oh! Sorry sir!

**Comment by yadunandanbhat** [comment]
But still, it would be nice to know if it's correct or not?

**Comment by dbwiddis** [comment]
I'm not sure what question is being asked?   Your PR looks good, other than the minor comments, @yadunandanbhat .
