### ISSUE TITLE
Question regarding removal of slowFields from getProcesses() on Windows

### ISSUE THREAD

**Issue by Space2Man** [oshi/oshi#1206]
Hi,

just a small question regarding the removal of the slowFields setting in getProcesses(). You state:

> The OperatingSystem methods fetching OSProcess information using a slowFields boolean have been removed, as the behavior they enabled is now done by default.

With the new version you do not fetch the values anymore which were previously fetched if slowFields == true (group, groupID, cmdLine). Instead you return them only when they are queried, right?

**Comment by dbwiddis** [comment]
That is exactly right. Each OS is different, but for Windows the command line, user, and group IDs are not fetched until requested.  So performance with `slowFields` false should be identical.  

In 4.x with `slowFields` enabled (or by default for requesting a collection of pids such as getting child processes) all those fields were requested all the time, which was a massive performance hit with the group info, so 5.x is a definite improvement there.

However, the former implementation of command lines (with slowFields true) fetched them all at once. On my system that's ~200-250 ms.  Fetching each one is ~50 ms with the WMI overhead so if you need more than 4 or 5 you're worse off.  So I added a config file setting to "batch" those queries. Fetching one grabs the whole list (and caches it) so all processes running when the first one was fetched will be retrieved quickly.

**Comment by dbwiddis** [comment]
Given the one-time-only config file setting I might alter the internal implementation slightly to use an overloaded method (Windows only) to permit users to specifically use batch mode without the config.
