### ISSUE TITLE
OSHI-5.0.1: NPE in getDisks()

### ISSUE THREAD

**Issue by Space2Man** [oshi/oshi#1208]
Hi,

following setup on my system:

```
$ cat /proc/partitions 
major minor  #blocks  name

 259        0  488386584 nvme0n1
 259        1     307200 nvme0n1p1
 259        2  488074784 nvme0n1p2
 254        0  488072736 dm-0
```

dm-0 is basically luks encryption on top of nvme0n1p2. For some reason it wants to add the partition  nvme0n1p1 to the partition list of dm-0 which is null because dm-0 has no partitions. I think you can reproduce it if you add e.g. an USB stick which has no partitions on it ...

**Comment by dbwiddis** [comment]
Hmm. Looks like we need some defaults in the HWDiskStore constructor.

**Comment by Space2Man** [comment]
Or this assumption is wrong in case there is a disk/device without any partitions ...

>                     // `store` should still point to the HWDiskStore this partition is attached to.
>                     // If not, it's an error, so skip.

**Comment by Space2Man** [comment]
Is it a valid assumption that the name of the disk is always part of the name of the partition?

/dev/sda1 -> ok
/dev/nvme0n1p1 -> ok

Are there cases where this assumption is not true?

**Comment by Space2Man** [comment]
Or do we need to exclude /dev/dm-* as well?

**Comment by dbwiddis** [comment]
Interestingly I think that comment predated the current code implementation.  I think there was an udev command line way back when.  As far as names, I'm not sure.  I suspect Linux `sysfs` docs would be authoritative here.

**Comment by Space2Man** [comment]
I have no experience in regards to this udev implementation here... but found something like this:

```
    // i wanted to get only partitions, so parent is empty
    udev_device *parent = 
        udev_device_get_parent_with_subsystem_devtype(dev, "block", "disk");
    if (!parent)
        continue;
```

Maybe you can check if the parent of the partition is the store that's currently in use ...

**Comment by Space2Man** [comment]
something like this:

`Udev.INSTANCE.udev_device_get_parent_with_subsystem_devtype(device, "block", "disk")`

And then check if that's the same device as the one from the store ....

**Comment by Space2Man** [comment]
Or (thinking out loud) ... just check if there is a partition table ... if there is no partition table the partition obviously belongs to a different disk ... but if the partition was just created (is there a race condition?) ... it might still fail ...

**Comment by Space2Man** [comment]
FYI: it only shows  up when I run updateAttributes() ... so with a store set ... if store == NULL then it detects all disks ...

**Comment by dbwiddis** [comment]
Thanks for digging into this. No time to look at it today but I like the "get_parent" suggestion and I'll see what I can figure out.  By the way, I [found this](https://whatsondoc.azurewebsites.net/?p=5134):

> The /dev/sdX representations are made in the order the drives are initialized during the boot cycle. Whole devices are ordered from /dev/sda onwards, with partitions on those disks being shown as /dev/sda1, /dev/sda2, /dev/sda3 etc.

**Comment by dbwiddis** [comment]
(The result of the above comment is that I believe a simple "contains" or "indexOf ... == 0" test would work for the parent of a partition.)

**Comment by dbwiddis** [comment]
For clarity, my initial comment about "defaults" refers to the 4.X implementation which had a default empty array: `private HWPartition[] partitions = new HWPartition[0];`

This is why the NPE is new behavior in 5.X, but that's the symptom of an underlying problem that's been there a while.  As you've pointed out, the assumption of disk store to partition while iterating `udev` is probably wrong, which is behavior that needs to be addressed in both branches.

**Comment by dbwiddis** [comment]
Looks like `udev_device_get_parent()` is the way to go:

/dev/sda:disk
 parent:null

/dev/sda1:partition
 parent:/dev/sda

/dev/sr0:disk
 parent:null

**Comment by dbwiddis** [comment]
This should be fixed by #1209 which I've pushed to SNAPSHOT.  Any chance you can test it?

**Comment by Space2Man** [comment]
Did some quick test and no NPE anymore ... I will double-check with debugger if the values are sane on my system ...

**Comment by Space2Man** [comment]
Looking good from my side ...

**Comment by Space2Man** [comment]
Just some FYI regarding the reason why 5.0.1 is a *BIG* step forward. We are monitoring processes and on some old 2008 Windows servers we saw that the update of the process list sometimes took ~1.5h ... the same update now takes ~1s ... I think it's caused by the querying of the group/groupID which we do not use but was queried anyway with the old version. And we have ~500 processes running and since we need the commandLine we update that in batched mode and all in all this is a massive improvement!

So thanks a LOT! If you ever come to Germany I owe you some :beers:

**Comment by dbwiddis** [comment]
Yeah, being able to separate out that process code per-OS was actually my main goal for 5.x (and I could probably have done so without the more intrusive change from arrays to lists).  Originally on my test Win7 system that group code wasn't a big deal, but on a corporate system with larger group lists, it got insane.  

You can toast me with a 🍺online next month, see #1201 :)

**Comment by dbwiddis** [comment]
By the way, another issue prompted me to look into the group query code which gets *all* groups.  There's an api call to get only the primary group which is a 1000x faster call.  I'll be backporting that to 4.7.x which should improve things a lot from the 1.5h run time issues.

**Comment by Space2Man** [comment]
Oh, cool. Is it faster for both paths (batched and non-batched)?

**Comment by dbwiddis** [comment]
There's no batched option for it, it's always been a per-process thing.

Looking at the javadocs I think I originally only did groups for the current process because of the slowness, and somehow lost track of that during the many refactorings...
