### ISSUE TITLE
 Could not initialize class oshi.jna.platform.linux.Libc$Sysinfo

### ISSUE THREAD

**Issue by yeahCaesar** [oshi/oshi#1210]
The problem is just as the title and it is similar with https://github.com/oshi/oshi/issues/338 too.But my oshi-core is 3.4.0 with openjdk1.8 and glibc2.17.Don't know why I have the issue.
![image](https://user-images.githubusercontent.com/19277364/81645345-03361700-945c-11ea-9564-35919bf8cb19.png)

**Comment by dbwiddis** [comment]
Are you able to update to a more recent version?  I see back in 3.4.0 I combined some of the various platform C libraries and it might be misreading "c" vs. "libc".   3.13.5 is the latest 3.X version.

**Comment by dbwiddis** [comment]
Or, of course, you could update to the latest release, 5.0.1 :)

**Comment by yeahCaesar** [comment]
Okay . let me have a try

**Comment by yeahCaesar** [comment]
I've tried oshi-core 3.5.0 and 3.13.5,  but the exception is still there.There is another exception [ java.lang.UnsatisfiedLinkError: /tmp/jna-3506402/jna6307814886269756539.tmp: /tmp/jna-3506402/jna6307814886269756539.tmp: failed to map segment from shared object: Operation not permitted ] ,  raleted to this exception?

**Comment by dbwiddis** [comment]
Those other errors are related to the JNA dependency and the native library it installs.  So this isn't an OSHI problem in particular, but something about your OS setup.  What OS?  

How are you compiling your code? Are you using Maven or another dependency manager? What version of JNA are you using?  I'm guessing there are problems finding libraries but I really don't have much to go on here.

**Comment by yeahCaesar** [comment]
centos7 in aws, maven.   Is jna in OSHI? I thinl it is 4.5.2. 
![image](https://user-images.githubusercontent.com/19277364/81657815-c3c2f700-946a-11ea-866c-b93505dc5e95.png)

**Comment by dbwiddis** [comment]
Not really sure what the problem is, although I suspect configuration/permissions with your cloud server.  I would suggest trying with the newest versions of both OSHI and JNA, although I don't know if that's going to help you.

**Comment by yeahCaesar** [comment]
It is caused by the  UnsatisfiedLinkError. I resolved the issue with using a  tmp dir created by myself rather than the centos /tmp.
