### ISSUE TITLE
Broken links in CHANGELOG

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1211]
### First Timers Only

I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to an open source project on GitHub before.

The main goal of this task is to learn the process for submitting a PR -- the GitHub equivalent of writing a "Hello World!" program.  If you already know the PR workflow, please leave this issue for someone else!

Please comment to "claim" this issue if you want to work on it.  If someone else has claimed this (look at "Assignees" to the right) please let them attempt it.

This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. 😄 

### The bug you are fixing

This project was started by @dblock and a few years ago we switched to the @oshi organization.  #880 tried to remove all references to the old links, but missed the changelog! 

### What to do to fix the bug

Search and replace all links of the form `https://github.com/dblock/oshi/pull` to read `https://github.com/oshi/oshi/pull`.

### How to submit your change to the repository

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  We'll follow those steps, and I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- Make the changes described above.
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

**Comment by i-shivamsoni** [comment]
#1212 I have fixed this, kindly review it.

**Comment by yadunandanbhat** [comment]
Is this still open?
