### ISSUE TITLE
OSHI 5.0.x: OSFileStore: mount point is not set for name 

### ISSUE THREAD

**Issue by Space2Man** [oshi/oshi#1213]
Hi, it's me again :)

I think I hit a bug (did not have time to check yet). I have this filesystem:

`/dev/nvme0n1p1  300M    424K  299M    1% /boot/efi`

This get's translated into the following OSFileStore:

```
logicalVolume = ""
description = "Local Disk"
fsType = "vfat"
freeSpace = 313507840
usableSpace = 313507840
totalSpace = 313942016
freeInodes = 0
totalInodes = 0
name = "/dev/nvme0n1p1"
volume = "/dev/nvme0n1p1"
label = "/dev/nvme0n1p1"
mount = "/dev/nvme0n1p1 /boot/efi vfat rw,noatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro 0 0"
options = "rw,noatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro"
uuid = "2973-ccf9"
```

Ok, I have no logicalVolume (correct) but I would expect the mountpoint /boot/efi being the name.
Some further infos:

```
# grep boot /proc/mounts 
/dev/nvme0n1p1 /boot/efi vfat rw,noatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro 0 0
[SpaceBook ~]# blkid | grep /dev/nvme0n1p1
/dev/nvme0n1p1: UUID="2973-CCF9" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="fa543fc1-38b0-4f5c-8d8b-8b55219e4e4b"

```

In 4.7.x I think mount was the mountpoint which now seems to be the full mount options. I think this should be mentioned in the Upgrade doc as well.

**Comment by Space2Man** [comment]
And on Windows it's like this:

`{"volume":"\\\\?\\Volume{0489563d-aaf5-11e2-8d28-806e6f6e6963}\\","type":"NTFS","mount":"C:\\","freeSpace":21482774528,"usableSpace":21482774528,"options":"rw,reparse,sparse,trans,journaled,quota,casess,oids,casepn,efs,streams,unicode,acls,fcomp","freeInodes":0,"UUID":"0489563d-aaf5-11e2-8d28-806e6f6e6963","label":"SM08209_System","totalSpace":96633614336,"description":"Fixed drive","logicalVolume":"","name":"SM08209_System (C:\\)","totalInodes":0}`

To me it's not clear which field should contain which values.

**Comment by Space2Man** [comment]
Or the linux "mount" is just wrong and contains the full line from /proc/mounts and not the 2nd value (mountpoint) only ... because on Windows mount is the letter where the drive is "mounted" ...

**Comment by dbwiddis** [comment]
Yeah, `mount` should be `/boot/efi`.  Clearly I missed changing a variable name somewhere in copypaste.

Thanks for beta-testing... I had thought about making a release candidate but everytime I do that, no bugs are reported until the day after the actual release. :D

**Comment by dbwiddis** [comment]
The problem is in `LinuxFileSystem` where I use the `mount` string rather than creating a new variable from `split[1]`.

**Comment by dbwiddis** [comment]
Or, rather, I do... it's called `path`.

**Comment by Space2Man** [comment]
> Yeah, `mount` should be `/boot/efi`. Clearly I missed changing a variable name somewhere in copypaste.
> 
> Thanks for beta-testing... I had thought about making a release candidate but everytime I do that, no bugs are reported until the day after the actual release. :D

Hehe, I know the feeling :)

**Comment by Space2Man** [comment]
I will test it tomorrow ...
