### ISSUE TITLE
Add messages to unit test assertions

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1215]
### Hacktoberfest

~I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to an open source project on GitHub before.~

I'm reopening this issue for #Hacktoberfest2020.  This is an easy PR for those of you who want T-shirts. :)

~The main goal of this task is to learn the process for submitting a PR -- the GitHub equivalent of writing a "Hello World!" program.  If you already know the PR workflow, please leave this issue for someone else!~

This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. 😄 

### What you're changing

A key to making sure OSHI code is working properly is unit testing.  Every time we make a change to the code, these tests run to verify the output is as expected.  

While these tests point out failures, many times the log messages simply point to the line number of the error without providing more information.

The JUnit `Assert` class methods have an optional `message` parameter that can be included for more detailed logs.   OSHI has not used these very much in the past but would like to add them going forward.  While it's mostly an administrative chore fixing old ones, these are a perfect exercise for a first PR!

### What to do 

1. Find a test class under the `oshi-core` directory tree `src\test\java`.  There are many to choose from!
2. Look for methods like `assertEquals(foo, bar);`
3. Add a message parameter: `assertEquals("foo should equal bar", foo, bar);`

Repeat as much as you like.  Don't worry about trying to get them all (there are literally hundreds of them) but it would be nice to do a whole class at a time, or at least a whole method. I'll leave this Issue open for other first timers to revisit!

### How to submit your change to the repository

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  We'll follow those steps, and I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- Make the changes described above.
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

**Comment by tomokos2** [comment]
Hi, I would like to work on this.

**Comment by dbwiddis** [comment]
Sure, @tomokos2.  Feel free to pick one, or if you want a suggestion I can help.  The "equals" ones tend to be less important to document than the "assertTrue(a >= b)" version.  The various API classes are probably more useful than the util classes.

**Comment by tomokos2** [comment]
Thank you! For now, I have chosen to document the `hardware\NetworksTest`, and have created a pull request for it. When updating `CHANGELOG.md`, however, I did not guess the correct pull request number. I hope that this can be changed later?

**Comment by tausiflife** [comment]
Hi! I'd like to help :)

**Comment by dbwiddis** [comment]
Great, @tausiflife !  Pick a class and work on it, or if you want a suggestion I can offer one. :)

**Comment by tschens95** [comment]
Hello, I would like to work on this and help you!

**Comment by dbwiddis** [comment]
Hi @tschens95!  Plenty of classes left for you to choose from, and a few examples of users who have gone before you!

**Comment by Roeezz** [comment]
Hi, I'm new and would like to help with this in my spare time. Can you suggest a class to start?

**Comment by dbwiddis** [comment]
Hi, @Roeezz, the `CentralProcessorTest` class in the `oshi.hardware` package is a good one.

**Comment by dPramod** [comment]
Hello @dbwiddis  , Thank you for this opportunity ! I have updated for one of the test class. Enjoyed working on it. Thank you again !.

**Comment by zachsez** [comment]
Hi, is there a way to filter which tests run with `mvn test` I only want to run the tests I'm changing during development.

**Comment by dbwiddis** [comment]
You can do `mvn -Dtest=ClassNameHere test` to only test the one class.   

Alternately if you are using an IDE, you can run the tests from within there. For example, I use Eclipse and I can right-click a file in the explorer and "Run as... JUnit test"

**Comment by zachsez** [comment]
Is it the source class or the test class name?
`mvn -Dtest=NetworkParams test`
or
'mvn -Dtest=NetworkParamsTest test`

**Comment by Roeezz** [comment]
You want to run the tests.

**Comment by dbwiddis** [comment]
@Roeezz beat me to the answer. The second option!  You could also do `mvn test -Dtest=NetworkParamsTest`, I don't think the order matters.

**Comment by zachsez** [comment]
I've tried both orders no luck. This is the error message I'm getting, I'm running the command from `..\oshi`: 
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (run-unit-tests) on project oshi-parent: No tests were executed!  (Set -DfailIfNoTests=false to ignore this error.) -> [Help 1]`

**Comment by dbwiddis** [comment]
Reopening this issue for #Hacktoberfest2020

**Comment by 24apurv** [comment]
Hey I would like to work on this. Adding messages to the test classes left in oshi\oshi-core\src\test\java\oshi\hardware.

**Comment by dbwiddis** [comment]
Excellent! Looking forward to your PR!

**Comment by j4ckofalltrades** [comment]
@dbwiddis I'd like to help as well. The `oshi/oshi-core/src/test/java/oshi/software/os` package looks like a good place to start, unless you have any other suggestions.

**Comment by dbwiddis** [comment]
Go for it, @j4ckofalltrades !
