### ISSUE TITLE
OS user sessions

### ISSUE THREAD

**Issue by battousai-dev** [oshi/oshi#1221]
Hi, this is the last piece or module that i'm working of migrating to oshi from sigar. Do you support this sigar API?

public void testWho() {
	try {
		Sigar sigar = new Sigar();
		Who[] who = sigar.getWhoList();
		if (who != null && who.length > 0) {
			for (int i = 0; i < who.length; i++) {
				System.out.println("\n~~~~~~~~~" + String.valueOf(i) + "~~~~~~~~~");
				Who _who = who[i];
				System.out.println("getDevice() = " + _who.getDevice());
				System.out.println("getHost() = " + _who.getHost());
				System.out.println("getTime() = " + _who.getTime());
				System.out.println("getUser() = " + _who.getUser());
			}
		}
	} catch (SigarException e) {
		e.printStackTrace();
	}
}

sample output:
getDevice() = console
getHost() = NT AUTHORITY
getTime() = unknown
getUser() = LOCAL SERVICE

getDevice() = console
getHost() = NT AUTHORITY
getTime() = unknown
getUser() = NETWORK SERVICE

**Comment by dbwiddis** [comment]
OSHI doesn't currently have this capability.  There was a request for something similar in #434 but it was vague enough, I wasn't that interested, and nobody wanted it enough to more clearly specify the request or submit a PR.

So what fields do you need?  Is this the current logged in user?

**Comment by dbwiddis** [comment]
Looking at the current implementation in SIGAR, it's just a front-end parsing the `who` command on *nix systems to return an array of active user sessions. 

Windows is the only native implementation, using the registry `HKEY_USERS` for local users, `WTSQuerySessionInformation` for WTS, and `NetSessionEnum` at level 10 for network.

**Comment by battousai-dev** [comment]
The fields I need are i mentioned above. We have used sigar api very long time (2012). We want to maintain or improve our monitoring apps using third party apis. I think yes and active user sessions.

**Comment by dbwiddis** [comment]
Great... expect that in 5.1.0 (and 4.8.0) within a couple of weeks.

**Comment by dbwiddis** [comment]
Hey @battousai-dev, I have a draft of the OS Session implementation in #1231.  It's available in SNAPSHOT.   Would you be able to test it?

Quick summary:
 - getSessions() method on the OperatingSystem interface
 - OSSession object that gives the info you get from `who`: username, device, login time, and host (if connecting remotely).

The SystemInfoTest prints the session summary near the top of the log.

I've implemented Windows, Mac, and Linux, and have a default version that parses `who` that works on the other Unixes, although I'm going to try to port the native code there (Utmpx is POSIX-compliant, which is good, but not thread safe, bleh!).   Still a bit of work to do but I'd really like as much testing/feedback as I can get right now.

@Space2Man would appreciate you testing as well, since you have a bunch of remote windows servers and that's the one that needs the most poking and prodding.

**Comment by battousai-dev** [comment]
hi @dbwiddis,

i tested the os user session using 5.1.0 snapshot. here's the sample result:
Oshi data:
"Users":[{"host":"NT AUTHORITY","time":"unknown","user":"LOCAL SERVICE","device":"Console"},
{"host":"NT AUTHORITY","time":"unknown","user":"NETWORK SERVICE","device":"Console"},
{"host":"PHLSF82025","time":"unknown","user":"ldap","device":"Console"},
{"host":"PHLSF82025","time":"unknown","user":"db2admin","device":"Console"},
{"host":"NT SERVICE","time":"unknown","user":"MSSQL$SQLDEVSERVER","device":"Console"},
{"host":"NT SERVICE","time":"unknown","user":"SQLTELEMETRY$SQLDEVSERVER","device":"Console"},
{"host":"NT SERVICE","time":"unknown","user":"MSSQLFDLauncher$SQLDEVSERVER","device":"Console"},
{"host":"NT SERVICE","time":"unknown","user":"MSSQL$SQLEXPRESS","device":"Console"},
{"host":"NT SERVICE","time":"unknown","user":"MSSQLFDLauncher$SQLEXPRESS","device":"Console"},
{"host":"NT AUTHORITY","time":"unknown","user":"SYSTEM","device":"Console"}],


Sigar data:
"Users":[{"host":"NT AUTHORITY","time":"unknown","user":"LOCAL SERVICE","device":"console"},
{"host":"NT AUTHORITY","time":"unknown","user":"NETWORK SERVICE","device":"console"},
{"host":"PHLSF82025","time":"unknown","user":"ldap","device":"console"},
{"host":"PHLSF82025","time":"unknown","user":"db2admin","device":"console"},
{"host":"NT SERVICE","time":"unknown","user":"MSSQL$SQLDEVSERVER","device":"console"},
{"host":"NT SERVICE","time":"unknown","user":"SQLTELEMETRY$SQLDEVSERVER","device":"console"},
{"host":"NT SERVICE","time":"unknown","user":"MSSQLFDLauncher$SQLDEVSERVER","device":"console"},
{"host":"NT SERVICE","time":"unknown","user":"MSSQL$SQLEXPRESS","device":"console"},
{"host":"NT SERVICE","time":"unknown","user":"MSSQLFDLauncher$SQLEXPRESS","device":"console"},
{"host":"NT AUTHORITY","time":"unknown","user":"SYSTEM","device":"console"}],

**Comment by dbwiddis** [comment]
Looks identical to me except for the capitalization of console. :)

Would be nice to also test with a network user if possible, to check two things: 1: format of IP address, and 2: make sure login time stays "the same" (within 1 second) after a period of inactivity.

**Comment by dbwiddis** [comment]
Actually the 2 things I still need tested:
 1. RDP user IP parsing makes sense
 2. Network user connect time makes sense (if possible to connect this way)

**Comment by dbwiddis** [comment]
(And just updated the snapshot with some tweaks on both of the above.)

**Comment by dbwiddis** [comment]
OK, I was able to do an RDP connection and verify IP address. Not sure I even know how to create a non-RDP network connection.  I'm going to go ahead and merge the class.  Let me know if you find any issues later.

**Comment by battousai-dev** [comment]
hi @dbwiddis, do you have timeline when 5.1.0 MS build to be release?

**Comment by dbwiddis** [comment]
> do you have timeline when 5.1.0 MS build to be release?

The day before the next bug report.  :) 

I was originally thinking closer to the end of the month, but if you need a non-SNAPSHOT release I can probably get it out tomorrow.

**Comment by battousai-dev** [comment]
> > do you have timeline when 5.1.0 MS build to be release?
> 
> The day before the next bug report. :)
> 
> I was originally thinking closer to the end of the month, but if you need a non-SNAPSHOT release I can probably get it out tomorrow.

thanks. thats great.

**Comment by dbwiddis** [comment]
> > do you have timeline when 5.1.0 MS build to be release?
> 
> The day before the next bug report. :)

For the record, I just found a memory leak in LinuxHWDiskStore.  Right on time....

**Comment by battousai-dev** [comment]
> > > do you have timeline when 5.1.0 MS build to be release?
> > 
> > 
> > The day before the next bug report. :)
> 
> For the record, I just found a memory leak in LinuxHWDiskStore. Right on time....

noted.

**Comment by Space2Man** [comment]
> > > do you have timeline when 5.1.0 MS build to be release?
> > 
> > 
> > The day before the next bug report. :)
> 
> For the record, I just found a memory leak in LinuxHWDiskStore. Right on time....

Hi, is the leak fixed in 5.1.0? Did it exist in 5.0.2 as well? Can't see a commit that sounds like a fix for memory leak... Thanks, Space

**Comment by dbwiddis** [comment]
It wasn’t a leak.  I thought it was and tried to fix it and got double-free errors.  I blame confusing docs. :)

**Comment by Space2Man** [comment]
Thanks for the quick response!
