### ISSUE TITLE
Change linux swapin/swapout counters to read swaps, not all pages

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1223]
### First Timers Only

I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to an open source project on GitHub before.

The main goal of this task is to learn the process for submitting a PR -- the GitHub equivalent of writing a "Hello World!" program.  If you already know the PR workflow, please leave this issue for someone else!

This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. 😄 

### What you're changing

When implementing page swap counters in response to #504, I made the choice on Linux to use `/proc/vmstat`'s entries for `pgpgin` and `pgpgout`, and similar `kstat` entries on Solaris.  However, this ends up measuring all pages read into and out of memory, not specifically the swap file.

It is more consistent to instead use `pswpin` and `pswpout` (Linux)/`pgswapin` and `pgswapout` (Solaris) which actually measures the page swaps.

### What to do 

1. Find the [LinuxVirtualMemory.java](https://github.com/oshi/oshi/blob/87914c5fa673d1731c2309aeecf8ab918ab5afeb/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxVirtualMemory.java#L129) class.
2. Replace `pgpgin` on line 129 with `pswpin` and `pgpgout` on line 132 with `pswpout`.
3. Find the [SolarisVirtualMemory.java](https://github.com/oshi/oshi/blob/31fd7d2a803781b040f36510aab12b7ab67caaa8/oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisVirtualMemory.java#L104) class.
4. Replace `pgpgin` on line 104 with `pgswapin` and `pgpgout` on line 112 with `pgswapout`.
5. If desired, update the changelog.

### How to submit your change to the repository

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  We'll follow those steps, and I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- Make the changes described above.
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

**Comment by Roeezz** [comment]
I can do that. Would probably take no time.
