### ISSUE TITLE
OS processes Shmem RedHat (RHEL 7.6)

### ISSUE THREAD

**Issue by battousai-dev** [oshi/oshi#1238]
hi, working with qualification of RHEL platform.
How do you get the ShMem from oshi for redhat? I'm getting values of Shmem from sigar. 
Here's the sample data from sigar:

{"PTime":"Apr15","ShMem":"973M","User":"oracle","Mem":"3.5G","State":"S","CTime":"3:43","ProcName":"ora_dbw0_dsadb","PID":"17786"},{"PTime":"Apr15",**"ShMem":" 30M"**,"User":"oracle","Mem":"3.4G","State":"S","CTime":"2:8","ProcName":"ora_lgwr_dsadb","PID":"17788"},{"PTime":"Apr15","ShMem":" 75M","User":"oracle","Mem":"3.4G","State":"S","CTime":"12:8","ProcName":"ora_ckpt_dsadb","PID":"17790"},{"PTime":"Apr15",**"ShMem":" 20M**","User":"oracle","Mem":"3.4G","State":"S","CTime":"0:18","ProcName":"ora_lg00_dsadb","PID":"17792"},{"PTime":"Apr15","ShMem":"231M","User":"oracle","Mem":"3.4G","State":"S","CTime":"1:16","ProcName":"ora_smon_dsadb","PID":"17794"},{"PTime":"Apr15","ShMem":" 18M","User":"oracle","Mem":"3.4G","State":"S","CTime":"0:18","ProcName":"ora_lg01_dsadb","PID":"17796"},{"PTime":"Apr15","ShMem":" 28M","User":"oracle","Mem":"3.4G","State":"S","CTime":"0:20","ProcName":"ora_reco_dsadb","PID":"17798"},{"PTime":"Apr15","ShMem":" 14M","User":"oracle","Mem":"3.4G","State":"S","CTime":"0:59","ProcName":"ora_lreg_dsadb","PID":"17800"},{"PTime":"Apr15","ShMem":" 13M","User":"oracle","Mem":"3.4G","State":"S","CTime":"0:54","ProcName":"ora_pxmn_dsadb","PID":"17802"},{"PTime":"Apr15","ShMem":"248M","User":"oracle","Mem":"3.5G","State":"S","CTime":"15:50","ProcName":"ora_mmon_dsadb","PID":"17804"},{"PTime":"Apr15","ShMem":" 68M","User":"oracle","Mem":"3.4G","State":"S","CTime":"51:33","ProcName":"ora_mmnl_dsadb","PID":"17806"},{"PTime":"Apr15","ShMem":" 12M","User":"oracle","Mem":"3.4G","State":"S","CTime":"0:22","ProcName":"ora_d000_dsadb","PID":"17808"},{"PTime":"Apr15","ShMem":" 12M","User":"oracle","Mem":"3.4G","State":"S","CTime":"0:21","ProcName":"ora_s000_dsadb","PID":"17810"},{"PTime":"Apr15","ShMem":" 15M","User":"oracle","Mem":"3.4G","State":"S","CTime":"0:41","ProcName":"ora_p000_dsadb","PID":"17827"},{"PTime":"Apr15","ShMem":" 15M","User":"oracle","Mem":"3.4G","State":"S","CTime":"0:42","ProcName":"ora_p001_dsadb","PID":"17829"},{"PTime":"Apr15","ShMem":" 13M","User":"oracle","Mem":"3.4G","State":"S","CTime":"0:27","ProcName":"ora_tmon_dsadb","PID":"17831"},{"PTime":"Apr15","ShMem":" 13M","User":"oracle","Mem":"3.4G","State":"S","CTime":"1:16","ProcName":"ora_tt00_dsadb","PID":"17833"},{"PTime":"Apr15","ShMem":" 15M","User":"oracle","Mem":"3.4G","State":"S","CTime":"3:1","ProcName":"ora_smco_dsadb","PID":"17837"},{"PTime":"Apr15","ShMem":" 18M","User":"oracle","Mem":"3.4G","State":"S","CTime":"0:22","ProcName":"ora_aqpc_dsadb","PID":"17848"},{"PTime":"Apr15","ShMem":" 12M","User":"oracle","Mem":"3.4G","State":"S","CTime":"0:40","ProcName":"ora_p002_dsadb","PID":"17853"},{"PTime":"Apr15","ShMem":" 11M","User":"oracle","Mem":"3.4G","State":"S","CTime":"0:39","ProcName":"ora_p003_dsadb","PID":"17855"},{"PTime":"Apr15","ShMem":" 11M","User":"oracle","Mem":"3.4G","State":"S","CTime":"0:41","ProcName":"ora_p004_dsadb","PID":"17857"},{"PTime":"Apr15","ShMem":" 11M","User":"oracle","Mem":"3.4G","State":"S","CTime":"0:39","ProcName":"ora_p005_dsadb","PID":"17859"},{"PTime":"Apr15","ShMem":" 12M","User":"oracle","Mem":"3.4G","State":"S","CTime":"0:39","ProcName":"ora_p006_dsadb","PID":"17861"},{"PTime":"Apr15","ShMem":" 11M","User":"oracle","Mem":"3.4G","State":"S","CTime":"0:40","ProcName":"ora_p007_dsadb","PID":"17863"},{"PTime":"Apr15","ShMem":"397M","User":"oracle","Mem":"3.5G","State":"S","CTime":"6:53","ProcName":"ora_cjq0_dsadb","PID":"17865"},{"PTime":"Apr15","ShMem":" 14M","User":"oracle","Mem":"3.4G","State":"S","CTime":"0:26","ProcName":"ora_qm02_dsadb","PID":"18020"},{"PTime":"Apr15","ShMem":" 44M","User":"oracle","Mem":"3.4G","State":"S","CTime":"0:27","ProcName":"ora_q002_dsadb","PID":"18024"},{"PTime":"Apr15","ShMem":" 19M","User":"oracle","Mem":"3.4G","State":"S","CTime":"0:19","ProcName":"ora_q003_dsadb","PID":"18026"},{"PTime":"Apr15","ShMem":" 26M","User":"oracle","Mem":"3.9G","State":"S","CTime":"2:33","ProcName":"ora_pmon_ora18c","PID":"18108"},

Here's the sample data from oshi api:
[{"PTime":"Jan19","ShMem":"-","User":"root","Mem":"3M","State":"SLEEPING","ProcName":"\/usr\/lib\/systemd\/systemd","CTime":"3:40","PID":"1"},{"PTime":"Jan19","ShMem":"-","User":"root","Mem":"0","State":"SLEEPING","ProcName":"kthreadd","CTime":"0:0","PID":"2"},{"PTime":"Jan19","ShMem":"-","User":"root","Mem":"0","State":"SLEEPING","ProcName":"ksoftirqd\/0","CTime":"0:0","PID":"3"},{"PTime":"Jan19","ShMem":"-","User":"root","Mem":"0","State":"SLEEPING","ProcName":"","CTime":"0:0","PID":"5"},{"PTime":"Jan19","ShMem":"-","User":"root","Mem":"0","State":"SLEEPING","ProcName":"migration\/0","CTime":"0:0","PID":"7"},{"PTime":"Jan19","ShMem":"-","User":"root","Mem":"0","State":"SLEEPING","ProcName":"rcu_bh","CTime":"0:0","PID":"8"},{"PTime":"Jan19","ShMem":"-","User":"root","Mem":"0","State":"SLEEPING","ProcName":"rcu_sched","CTime":"0:0","PID":"9"},{"PTime":"Jan19","ShMem":"-","User":"root","Mem":"0","State":"SLEEPING","ProcName":"lru-add-drain","CTime":"0:0","PID":"10"},{"PTime":"Jan19","ShMem":"-","User":"root","Mem":"0","State":"SLEEPING","ProcName":"watchdog\/0","CTime":"0:0","PID":"11"},{"PTime":"Jan19","ShMem":"-","User":"root","Mem":"0","State":"SLEEPING","ProcName":"watchdog\/1","CTime":"0:0","PID":"12"},{"PTime":"Jan19","ShMem":"-","User":"root","Mem":"0","State":"SLEEPING","ProcName":"migration\/1","CTime":"0:0","PID":"13"},{"PTime":"Jan19","ShMem":"-","User":"root","Mem":"0","State":"RUNNING","ProcName":"ksoftirqd\/1","CTime":"0:0","PID":"14"},{"PTime":"Jan19","ShMem":"-","User":"root","Mem":"0","State":"SLEEPING","ProcName":"","CTime":"0:0","PID":"16"},{"PTime":"Jan19","ShMem":"-","User":"root","Mem":"0","State":"SLEEPING","ProcName":"kdevtmpfs","CTime":"0:0","PID":"18"},{"PTime":"Jan19","ShMem":"-","User":"root","Mem":"0","State":"SLEEPING","ProcName":"netns","CTime":"0:0","PID":"19"},{"PTime":"Jan19","ShMem":"-","User":"root","Mem":"0","State":"SLEEPING","ProcName":"khungtaskd","CTime":"0:0","PID":"20"},{"PTime":"Jan19","ShMem":"-","User":"root","Mem":"0","State":"SLEEPING","ProcName":"writeback","CTime":"0:0","PID":"21"},{"PTime":"Jan19","ShMem":"-","User":"root","Mem":"0","State":"SLEEPING","ProcName":"kintegrityd","CTime":"0:0","PID":"22"},{"PTime":"Jan19","ShMem":"-","User":"root","Mem":"0","State":"SLEEPING","ProcName":"bioset","CTime":"0:0","PID":"23"},{"PTime":"Jan19","ShMem":"-","User":"root","Mem":"0","State":"SLEEPING","ProcName":"bioset","CTime":"0:0","PID":"24"}

**Comment by dbwiddis** [comment]
ShMem is a Linux-only statistic (SIGAR does not implement for WIndows, macOS, FreeBSD, or Solaris), so OSHI doesn't include it at the cross-platform API level.  

There is a driver class `ProcessStat` in the `oshi.driver.linux.proc` class which can return all the elements from `/proc/[pid]/stat`, but it appears ShMem isn't there either.  It's one of the few statistics that's only in `/proc/[pid]/statm`.

**Comment by dbwiddis** [comment]
This method will get you the ShMem for a process, in units of pages.  Get the pageSize from the memory class to convert to bytes.

```
    public static long getShMemPages(int pid) {
        String statm = FileUtil.getStringFromFile(String.format("/proc/%d/statm", pid));
        String[] split = ParseUtil.whitespaces.split(statm);
        if (split.length > 2) {
            return ParseUtil.parseLongOrDefault(split[2], 0L);
        }
        return 0L;
    }
```

**Comment by battousai-dev** [comment]
> This method will get you the ShMem for a process, in units of pages. Get the pageSize from the memory class to convert to bytes.
> 
> ```
>     public static long getShMemPages(int pid) {
>         String statm = FileUtil.getStringFromFile(String.format("/proc/%d/statm", pid));
>         String[] split = ParseUtil.whitespaces.split(statm);
>         if (split.length > 2) {
>             return ParseUtil.parseLongOrDefault(split[2], 0L);
>         }
>         return 0L;
>     }
> ```

is the method available with 5.1.0 build so that i can implement it? if yes, how can i implement the above method?

**Comment by dbwiddis** [comment]
That method doesn’t exist anywhere but uses existing OSHI code.  But it will get you the answer you need. 

If you want to submit a PR to add that code to the ProcessStat class, that’s not a bad idea.  But you’d have to wait for the next release before you could use it. :)

**Comment by dbwiddis** [comment]
To implement it just make it a method in your own code!

**Comment by battousai-dev** [comment]
is PR? pull request?

**Comment by dbwiddis** [comment]
Yep.  See the CONTRIBUTING file for details.

**Comment by battousai-dev** [comment]
> Yep. See the CONTRIBUTING file for details.

thanks!

**Comment by dbwiddis** [comment]
Just copied relevant parts of the `/proc/pid/stat` driver in #1240. Essentially the code I posted above but grabs all the fields of `/proc/pid/statm`.

**Comment by battousai-dev** [comment]
> Just copied relevant parts of the `/proc/pid/stat` driver in #1240. Essentially the code I posted above but grabs all the fields of `/proc/pid/statm`.

Do you have date when 5.2.0 to be release?

**Comment by dbwiddis** [comment]
There have been no significant changes since 5.1.0, so I am not planning any release.  If anything, I'd push out a 5.1.1, but ideally I'd like to wait for any other change requests (are you done porting SIGAR?) or bugs that might be reported from other users switching to 5.x (which has been out only 3 weeks so far).

Other than some refactoring and javadocs, the only change was the addition of a driver for `/proc/pid/statm` which is a more generalized method than the 4 lines of code I posted above.
These changes are available in the latest SNAPSHOT which you can include in your maven build if you want access to the new method before it's released.

If there is a reason you can not use a SNAPSHOT build, then the solution posted above in this thread is equivalent to the change.

**Comment by battousai-dev** [comment]
> There have been no significant changes since 5.1.0, so I am not planning any release. If anything, I'd push out a 5.1.1, but ideally I'd like to wait for any other change requests (are you done porting SIGAR?) or bugs that might be reported from other users switching to 5.x (which has been out only 3 weeks so far).
> 
> Other than some refactoring and javadocs, the only change was the addition of a driver for `/proc/pid/statm` which is a more generalized method than the 4 lines of code I posted above.
> These changes are available in the latest SNAPSHOT which you can include in your maven build if you want access to the new method before it's released.
> 
> If there is a reason you can not use a SNAPSHOT build, then the solution posted above in this thread is equivalent to the change.

thanks for quick response.
