### ISSUE TITLE
macOS 10.16 support

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1260]
Apple will announce the name of version 10.16 on [June 22](https://developer.apple.com/wwdc20/).  The mac version parsing should be updated to use a properties file rather than annually adding to the switch/case statements.

**Comment by dbwiddis** [comment]
@JapneetSingh5 I have another small task I can assign you if you want to pitch in.

**Comment by JapneetSingh5** [comment]
Thankyou, will love to do it!

**Comment by dbwiddis** [comment]
@JapneetSingh5 - Check out the AbstractNetworkIF class `toString()` method.  I'd like to combine the IP4 / netmask and IP6 / prefixlength outputs.

Current:
```
IPv4: [10.0.0.50]
Netmask:  [24]
IPv6: [2601:600:807f:a85d:0:0:0:1f36, 2601:600:807f:a85d:a428:ea9:db69:8012]
Prefix Lengths:  [64, 64]
```

Desired:
```
IPv4: [10.0.0.50/24]
IPv6: [2601:600:807f:a85d:0:0:0:1f36/64, 2601:600:807f:a85d:a428:ea9:db69:8012/64]
```

**Comment by JapneetSingh5** [comment]
Working on it.

**Comment by JapneetSingh5** [comment]
I have added a pull request, but I feel it isn't the right way to do it. Would love to have your advice.

**Comment by hkbiet** [comment]
> Sure, @hkbiet, it's all yours! I hope I've described the task well enough!

Thank you so much for the opportunity @dbwiddis  , i did learn a couple of things doing this , i did the changes as asked and ran mvn test and locally it gave no errors but whence i created the pull request it is showing some errors on it on GIthub, request you to please have a look and advise/guide if there is anything wrong from my end.

Looking for more such opportunities !

Thanks !

**Comment by dbwiddis** [comment]
So it seems the new [OS name is Big Sur](https://www.apple.com/macos/big-sur-preview/?cid=wwa-us-kwgo-mac-slid---Brand-macOS-AppleLive-&mtid=20925top39173&aosid=p238&mnid=sgWrY4UaQ-dc_mtid_20925top39173_pcrid_443885735952_pgrid_109924092224_&anonymizeip=set).  Now it's just a quick text file edit!

**Comment by dbwiddis** [comment]
And it's OS 11, not 10.16.  Interesting!  The X is gone!
