### ISSUE TITLE
Mac thread counting ignores function return value on failure

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1263]
### First Timers Only

I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to an open source project on GitHub before.

The main goal of this task is to learn the process for submitting a PR -- the GitHub equivalent of writing a "Hello World!" program.  If you already know the PR workflow, please leave this issue for someone else!

This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. 😄 

### The bug you are fixing

In the  `MacOperatingSystem` `getThreadCount()` method, the native `proc_pidinfo()` function is called to get information on the process.  However, if this function fails (common for permission errors if running non-sudo) the data in the structure is undefined, most likely left over values from the previous iteration.  This incorrectly sums up total threads.

### What to do 

1. In [MacOperatingSystem](https://github.com/oshi/oshi/blob/895f47d3231fe3fc57ad069985ebb082377ac515/oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java#L234) line 234, add an integer to check the return type of the function call.
2. Test that this return value is non-negative before incrementing the `numberOfThreads` variable on the next line.  
   - (It should be sufficient to test the return is not -1; the return should actually be 96, the bytes in the returned structure, which you could get from `taskInfo.size()`.)

### How to submit your change to the repository

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  We'll follow those steps, and I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- Make the changes described above.
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

**Comment by berdesourabh** [comment]
Hi, Can I work on this issue?

**Comment by dbwiddis** [comment]
Hi, @berdesourabh, thank you for wanting to help.  A brief glance at your history shows that you've already committed to several github repositories, and I'd really like to reserve this "simple" one for someone who's brand new to the git / github environment.  IF you'd like to contribute something of more substance to this project, there are several complex methods that could use some refactoring which I can point you to.

**Comment by berdesourabh** [comment]
@dbwiddis I may have looked into many issues but have not contributed any. But if you have anything else that I can work on that would be great.

**Comment by dbwiddis** [comment]
@berdesourabh check out the [Sonar issues](https://sonarcloud.io/project/issues?id=com.github.oshi%3Aoshi-parent&resolved=false) with high cognitive complexity, and the [Scrutinizer](https://scrutinizer-ci.com/g/oshi/oshi/?branch=master) Latest alerts which are mostly complex methods.  Refactor the native calls into appropriate `oshi.driver` package classes.

**Comment by berdesourabh** [comment]
@dbwiddis Great! I'll look into them. Thanks!

**Comment by dbwiddis** [comment]
Feel free to open a new issue for each one you want to address if you have any questions, to keep this issue's comments on topic for this issue. :)

**Comment by dbwiddis** [comment]
I've opened #1264 with links to suggestions for other things you can work on, so this issue's comments can stay focused on this single code fix. :smile:

**Comment by markkulube** [comment]
@dbwiddis I will work on it. Please assign. Thanks!
