### ISSUE TITLE
How to configure the logger to stop writing to console "Failed to add PDH Counter"?

### ISSUE THREAD

**Issue by AcidS76** [oshi/oshi#1265]
Hi, I'm new to this component and it's very cool. I have a problem that when I execute it, I get so many these errors in console:

[main] WARN oshi.util.platform.windows.PerfDataUtil - Failed to add PDH Counter: \Processore(_Total)\% DPC Time, Error code: 0xC0000BB8
[main] ERROR oshi.util.platform.windows.PerfCounterQueryHandler - Failed to add counter for PDH object: Processore

And I would love to put these messages in a log file, not in console. As my logger, the project where I use oshi is java.util.logging.Logger., My goal is to stop to get these messages outside a logger.. Possible? I tried to configure log4j2 with a xml file but nothing changed...

**Comment by dbwiddis** [comment]
OSHI just uses the `slf4j` facade, but you still need to include the appropriate api for your chosen logger.  You mention both `java.util.logging` and `log4j2` so I'm not sure which one you have configured.

For JUL, you need [`slf4j-jdk14`](https://mvnrepository.com/artifact/org.slf4j/slf4j-jdk14) (or an earlier version) as well as [`slf4j-api`](https://mvnrepository.com/artifact/org.slf4j/slf4j-api).

For log4j2, you need [either `log4j-slf4j-impl` or `log4j-slf4j18-impl`](https://logging.apache.org/log4j/2.0/log4j-slf4j-impl/index.html).  

Each of those should have the ability to suppress log messages for a particular class.

I do wonder if you have counters disabled, or if OSHI's localization is broken.  Do you have that counter in `perfmon.exe`?

**Comment by dbwiddis** [comment]
I've added #1266 which should reduce the logspam by remembering the failure and not trying again (should help performance as well)... also lowered the PerfCounterQueryHandler level to WARN.  It's in SNAPSHOT now if you want to try it.

**Comment by dbwiddis** [comment]
Hi, @AcidS76 I hope the answer above and changes in #1266 solve your problem. I'm closing this issue but feel free to re-open if you need more assistance.
