### ISSUE TITLE
Add page fault info to OSProcess

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1270]
PR #1258 adds minor and major page faults to the threads.  This data is also available (by major/minor) for processes on Linux, FreeBSD ~and Solaris~ and macOS.  Windows just has a single page faults value that includes both.

**Comment by dbwiddis** [comment]
Linux: in the `stat` already retrieved, add fields 10 and 12 (majflt, minflt)
Unix: in `ps` output already retrieved, add majflt, minflt
macOS: in the `ProcTaskInfo` structure already retrieved, `pti_faults` is (probably) all faults `pti_pageins` are major faults.
Windows: existing registry/perfcounter query, add `PageFaultsPersec` as WMI name, "Page Faults/sec" as counter name. These are total faults, Windows doesn't have hard page faults at the process level.

**Comment by tausiflife** [comment]
I have added this info for Linux and FreeBSD. Couldn't find faults for Solaris. As i see we haven't added it for Solaris threads as well. For macOS if `pti_faults = all faults` and `pti_pageins = major faults`, does it mean `minor faults = pti_faults - pti_pageins` ?

**Comment by dbwiddis** [comment]
Hmm, yeah, we'll have to leave blank (report 0) for Solaris and note that in the docs as well as the Windows exception.

I completely understand your question on macOS and have been trying to find the answer.  I think I need to compare outputs with the result of `getrusage()` to see which it is, but haven't gotten to actually doing that.  For now assume minor = faults - pageins, while I try to figure it out for sure.

**Comment by dbwiddis** [comment]
OK, it definitely looks like `pti_faults` is the sum of major and minor, so you should subtract off `pti_pageins` from `pti_faults` to get the minor faults.  In a loop the `ru_*` numbers are always the same or higher since they are measured after the `pti_*` numbers.  But they are below pti, by approximately the pageins/majflt amount.

```
pti_faults=11377, pti_pageins=0, ru_minflt=11377, ru_majflt=0
pti_faults=11405, pti_pageins=0, ru_minflt=11405, ru_majflt=0

pti_faults=10798, pti_pageins=0, ru_minflt=10798, ru_majflt=0
pti_faults=11195, pti_pageins=4, ru_minflt=11191, ru_majflt=4

pti_faults=10867, pti_pageins=0, ru_minflt=10868, ru_majflt=0
pti_faults=10872, pti_pageins=0, ru_minflt=10873, ru_majflt=0
pti_faults=10890, pti_pageins=2, ru_minflt=10889, ru_majflt=3
pti_faults=10928, pti_pageins=3, ru_minflt=10927, ru_majflt=3
pti_faults=11305, pti_pageins=3, ru_minflt=11302, ru_majflt=3
pti_faults=11335, pti_pageins=4, ru_minflt=11331, ru_majflt=4
pti_faults=11349, pti_pageins=11, ru_minflt=11339, ru_majflt=11
pti_faults=11384, pti_pageins=11, ru_minflt=11373, ru_majflt=11

```

**Comment by dbwiddis** [comment]
Here's another one in case there was any doubt:
`pti_faults=10751, pti_pageins=215, ru_minflt=10542, ru_majflt=215`
