### ISSUE TITLE
Warning log when oshi.properties not found

### ISSUE THREAD

**Issue by ngyukman** [oshi/oshi#1285]
Hi, 

Thanks for the useful library
We have a warning log `No default configuration found` when loading oshi where the `Thread.currentThread().getContextClassLoader()` is not the classloader that loads the oshi jar 

https://github.com/oshi/oshi/blob/1e56bf1be27f44fdedcfb98dc65f95443cccb5da/oshi-core/src/main/java/oshi/util/FileUtil.java#L226

I have a proposal that if the resources is empty from the given classloader, we could try the ClassLoader of GlobalConfig.class.getClassLoader()

do you think it make sense?
I can create the pull request if it looks good to you

**Comment by dbwiddis** [comment]
I will freely admit that classloading is a mystery to me many times.  I'm more than happy to accept a "fallback" attempt you think will work.

**Comment by ngyukman** [comment]
thanks, I will try to make the fix for it

**Comment by dbwiddis** [comment]
Fixed in #1287
