### ISSUE TITLE
Cannot get Logical Partition from Windows(win 8.1 and win 10) from USB mobile hard drive

### ISSUE THREAD

**Issue by AnakinHou** [oshi/oshi#1305]
Hello, I used oshi new version on  15 July, it works very well, but I think I found a bug. It cannot get Logical Partition from windows. 

I have a local Hard Drive and I plugin a USB mobile Hard Drive on my computer,  just like this: partition C: D: E: F: G: are my local Hard Drive, C: is windows 10 system.   I: J: K: L: M: N: are USB mobile Hard Drive,  K: L: M: N: are logical partitions in them.

The problem with the oshi code is I can got C: D: E: F: G:  I:  J:  N:  working ,   but not K: L: M: working, 
it's means on the log list I can see C: D: E: F: G:  and I:  J:  N: , but not K: L: M: 

I think this  isn't working  because  K: L: M: N:  are logical partitions, they have same partition name.

And I found the Class File oshi.hardware.platform.windows.WindowsHWDiskStore,  method  getDisk() and queryPartitionMaps()  have problems , maybe you need fix it up. 

I already fixed it up by myself. if you need the code I can send it to you.

**Comment by dbwiddis** [comment]
Thanks for the report.  It would be great if you can submit the fix as a PR.

**Comment by AnakinHou** [comment]
Hi Dude, I modified WindowsHWDiskStore to fix that get logical partition on windows correctly, but all the logical partitions are same size, I have not found a method to correct it, sorry about that
