### ISSUE TITLE
NPE if Bytes read is null in ProcessPerformanceData.buildProcessMapFromRegistry

### ISSUE THREAD

**Issue by mushion22** [oshi/oshi#1319]
Have come across a scenario where a Windows 2016 system is somehow returning null for 'IO Read Bytes/sec' for the System Idle process (process id 0). 

When ProcessPerformanceData.buildProcessMapFromRegistry tries to create the PerfCounterBlock, it casts ProcessInformation.ProcessPerformanceProperty.READTRANSFERCOUNT from the processInstanceMap to Long (object). 

However, the constructor of PerfCounterBlock takes a long (primative). Thus unboxing occurs, ie, the compiler adds .longValue() to the end of the Long object. Seeing as the object is null, this causes a NullPointerException. 

ie, it becomes

((Long)processInstanceMap
              .get(ProcessInformation.ProcessPerformanceProperty.READTRANSFERCOUNT)).longValue()

It is unclear why this machine is returning null for that field - am investigating that. Other "identical" machines are fine.

**Comment by dbwiddis** [comment]
Thanks for this report. It certainly seems like a rare edge case.  

That `EnumMap` is built by cross-referencing the Enum name to a registry key in `HkeyPerformanceDataUtil.readPerfDataFromRegistry()`.  It looks like it's hitting line 184 and inserting `null` into the map there.  (Perhaps inserting 0 is a better idea and will probably fix this bug.)  This indicates the countersize map got a value other than 4 or 8, though, which shouldn't happen.

It's possible the registry may be corrupt in some way.  Can you try rebuilding performance counters? [Here are the instructions](https://support.microsoft.com/en-us/help/2554336/how-to-manually-rebuild-performance-counters-for-windows-server-2008-6) for server 2008, I think they're the same for 2016.

**Comment by mushion22** [comment]
Will see if we can - this is coming from the install of a monitoring tool (AppDynamics) at a client site, so will see if they will allow us to rebuild the registry on these machines. It's only happening on 2 of ~12 machines, the others are all fine. 

It may be useful to add a system property or config flag somewhere to skip the use of registry and force the fallback to WMI. 

I should have included a stack trace: 
```
java.lang.NullPointerException: null
	at oshi.driver.windows.registry.ProcessPerformanceData.buildProcessMapFromRegistry(ProcessPerformanceData.java:89) ~[oshi-core-5.1.0.jar:5.1.0]
	at oshi.software.os.windows.WindowsOperatingSystem.queryProcessMapFromRegistry(WindowsOperatingSystem.java:346) ~[oshi-core-5.1.0.jar:5.1.0]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-5.1.0.jar:5.1.0]
	at oshi.software.os.windows.WindowsOperatingSystem.processMapToList(WindowsOperatingSystem.java:325) ~[oshi-core-5.1.0.jar:5.1.0]
	at oshi.software.os.windows.WindowsOperatingSystem.getProcesses(WindowsOperatingSystem.java:287) ~[oshi-core-5.1.0.jar:5.1.0]
```

For testing I wrote a simple program to independently get a list of processes then find which one was the problem. It occurs on the System Idle process on these 2 machines (proc ID 0). 

WindowsOperatingSystem.getProcess(0) throws the NPE.

```
import com.opencsv.CSVReader;
import org.apache.commons.io.IOUtils;
import org.apache.commons.lang3.math.NumberUtils;
import oshi.software.os.OSProcess;
import oshi.software.os.windows.WindowsOperatingSystem;

import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.util.List;

public class App 
{
    public static void main( String[] args )

    {
        System.out.println( "Getting Process List" );


        try {
            Process p = Runtime.getRuntime().exec
                    (System.getenv("windir") + "\\system32\\" + "tasklist.exe /fo csv /nh");

            List<String[]> procs = new CSVReader(new InputStreamReader(p.getInputStream())).readAll();
            System.out.println("Found " + procs.size() + " processes");
            for (String[] proc : procs){
                int procId = NumberUtils.toInt(proc[1]);
                System.out.println("Inspecting process: " +procId +": " + proc[0]);
                WindowsOperatingSystem os = new WindowsOperatingSystem();
                OSProcess winproc = os.getProcess(procId);
                if (null == winproc){
                    System.out.println("Could not get process info for process (might have died since the first lookup): " +procId +": " + proc[0]);
                    continue;
                }
                String name = winproc.getName();
                String commandline = winproc.getCommandLine();

                System.out.println(String.format("Name: %s, Command Line: %s, Bytes Read: %d, Bytes Written: %d",name, commandline, winproc.getBytesRead(), winproc.getBytesWritten()));
            }
            long l = 
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

**Comment by dbwiddis** [comment]
> It may be useful to add a system property or config flag somewhere to skip the use of registry and force the fallback to WMI.

That should happen anyway if the registry query fails.  The problem is that we don't cause it to fail.  

Is it only process 0 that does this?  Or are you just hitting it on process 0 as the first one of several to check?

**Comment by dbwiddis** [comment]
Looking into this, I don't think the PID is relevant. The counter block would apply to any pid.  The question I have is:
 - Is this simply a case where this particular counter is missing/removed?   Rebuilding would fix.   We could add zero to the value map instead of null and everything else would/should work.
 - Is this a case where more data is corrupt and we're getting random values?  We should simply do "return null" at that point in the code and ignore the registry, using a fallback.

I'm favoring the second option, with a log message.  Along with a config option as you mention.

**Comment by mushion22** [comment]
> The problem is that we don't cause it to fail.
Yeah the NPE isn't caught so it throws it all the way back to the parent. 

 > Is it only process 0 that does this? Or are you just hitting it on process 0 as the first one of several to check?

Good question, I'll revise my program to handle the NPE and continue so can see if it's just that process, or wider corruption in those machines. 

Have asked if we can rebuild the registry on one of them - it's in a user testing environment so might not be possible for some time. Haven't been able to reproduce the behavior elsewhere.

**Comment by dbwiddis** [comment]
I'm pretty sure it's more than process 0, based on the structure. The question I do have is whether any data is valid, or it's just that one counter.  

I'll commit a fix throwing null and get snapshot updated shortly.

**Comment by dbwiddis** [comment]
#1320 should fix this by just aborting the whole registry procedure if it encounters this situation, and also providing a config file override to not even bother trying. Let me know if this works for you.

**Comment by mushion22** [comment]
> I'm pretty sure it's more than process 0, based on the structure. The question I do have is whether any data is valid, or it's just that one counter.

Adjusted my program to iterate all processes, and indeed its for processes. The NPE only happens on the line for READTRANSFERCOUNT, so I suspect it does not affect other counters.  

> Let me know if this works for you.

Will try soon. 

I also wrote a dump from the perf data block below.

```
WinPerf$PERF_DATA_BLOCK(allocated@0x1b4c7690 (88 bytes) (shared from allocated@0x1b4c7690 (118784 bytes) (shared from allocated@0x1b4c7690 (118784 bytes) (shared from allocated@0x1b4c7690 (118784 bytes))))) {
  char Signature[4]@0x0=[C@5a61f5df
  int LittleEndian@0x8=0x0001
  int Version@0xC=0x0001
  int Revision@0x10=0x0001
  int TotalByteLength@0x14=0x5CE0
  int HeaderLength@0x18=0x0078
  int NumObjectTypes@0x1C=0x0001
  int DefaultObject@0x20=0x00EE
  WinBase$SYSTEMTIME SystemTime@0x24=WinBase$SYSTEMTIME(allocated@0x1b4c76b4 (16 bytes) (shared from allocated@0x1b4c7690 (88 bytes) (shared from allocated@0x1b4c7690 (118784 bytes) (shared from allocated@0x1b4c7690 (118784 bytes) (shared from allocated@0x1b4c7690 (118784 bytes)))))) {
    short wYear@0x0=0x7E4
    short wMonth@0x2=0x08
    short wDayOfWeek@0x4=0x03
    short wDay@0x6=0x0C
    short wHour@0x8=0x05
    short wMinute@0xA=0x1B
    short wSecond@0xC=0x0A
    short wMilliseconds@0xE=0x3B7
  }
  WinNT$LARGE_INTEGER PerfTime@0x38=WinNT$LARGE_INTEGER(allocated@0x1b4c76c8 (8 bytes) (shared from allocated@0x1b4c7690 (88 bytes) (shared from allocated@0x1b4c7690 (118784 bytes) (shared from allocated@0x1b4c7690 (118784 bytes) (shared from allocated@0x1b4c7690 (118784 bytes)))))) {
    WinNT$LARGE_INTEGER$UNION u@0x0=WinNT$LARGE_INTEGER$UNION(allocated@0x1b4c76c8 (8 bytes) (shared from allocated@0x1b4c76c8 (8 bytes) (shared from allocated@0x1b4c7690 (88 bytes) (shared from allocated@0x1b4c7690 (118784 bytes) (shared from allocated@0x1b4c7690 (118784 bytes) (shared from allocated@0x1b4c7690 (118784 bytes))))))) {
      WinNT$LARGE_INTEGER$LowHigh lh@0x0=WinNT$LARGE_INTEGER$LowHigh(allocated@0x1b4c76c8 (8 bytes) (shared from allocated@0x1b4c76c8 (8 bytes) (shared from allocated@0x1b4c76c8 (8 bytes) (shared from allocated@0x1b4c7690 (88 bytes) (shared from allocated@0x1b4c7690 (118784 bytes) (shared from allocated@0x1b4c7690 (118784 bytes) (shared from allocated@0x1b4c7690 (118784 bytes)))))))) {
        WinDef$DWORD LowPart@0x0=1651530679
        WinDef$DWORD HighPart@0x4=37
      }
      long value@0x0=0x2562705BB7
    }
  }
  WinNT$LARGE_INTEGER PerfFreq@0x40=WinNT$LARGE_INTEGER(allocated@0x1b4c76d0 (8 bytes) (shared from allocated@0x1b4c7690 (88 bytes) (shared from allocated@0x1b4c7690 (118784 bytes) (shared from allocated@0x1b4c7690 (118784 bytes) (shared from allocated@0x1b4c7690 (118784 bytes)))))) {
    WinNT$LARGE_INTEGER$UNION u@0x0=WinNT$LARGE_INTEGER$UNION(allocated@0x1b4c76d0 (8 bytes) (shared from allocated@0x1b4c76d0 (8 bytes) (shared from allocated@0x1b4c7690 (88 bytes) (shared from allocated@0x1b4c7690 (118784 bytes) (shared from allocated@0x1b4c7690 (118784 bytes) (shared from allocated@0x1b4c7690 (118784 bytes))))))) {
      WinNT$LARGE_INTEGER$LowHigh lh@0x0=WinNT$LARGE_INTEGER$LowHigh(allocated@0x1b4c76d0 (8 bytes) (shared from allocated@0x1b4c76d0 (8 bytes) (shared from allocated@0x1b4c76d0 (8 bytes) (shared from allocated@0x1b4c7690 (88 bytes) (shared from allocated@0x1b4c7690 (118784 bytes) (shared from allocated@0x1b4c7690 (118784 bytes) (shared from allocated@0x1b4c7690 (118784 bytes)))))))) {
        WinDef$DWORD LowPart@0x0=2533111
        WinDef$DWORD HighPart@0x4=0
      }
      long value@0x0=0x0026A6F7
    }
  }
  WinNT$LARGE_INTEGER PerfTime100nSec@0x48=WinNT$LARGE_INTEGER(allocated@0x1b4c76d8 (8 bytes) (shared from allocated@0x1b4c7690 (88 bytes) (shared from allocated@0x1b4c7690 (118784 bytes) (shared from allocated@0x1b4c7690 (118784 bytes) (shared from allocated@0x1b4c7690 (118784 bytes)))))) {
    WinNT$LARGE_INTEGER$UNION u@0x0=WinNT$LARGE_INTEGER$UNION(allocated@0x1b4c76d8 (8 bytes) (shared from allocated@0x1b4c76d8 (8 bytes) (shared from allocated@0x1b4c7690 (88 bytes) (shared from allocated@0x1b4c7690 (118784 bytes) (shared from allocated@0x1b4c7690 (118784 bytes) (shared from allocated@0x1b4c7690 (118784 bytes))))))) {
      WinNT$LARGE_INTEGER$LowHigh lh@0x0=WinNT$LARGE_INTEGER$LowHigh(allocated@0x1b4c76d8 (8 bytes) (shared from allocated@0x1b4c76d8 (8 bytes) (shared from allocated@0x1b4c76d8 (8 bytes) (shared from allocated@0x1b4c7690 (88 bytes) (shared from allocated@0x1b4c7690 (118784 bytes) (shared from allocated@0x1b4c7690 (118784 bytes) (shared from allocated@0x1b4c7690 (118784 bytes)))))))) {
        WinDef$DWORD LowPart@0x0=981628992
        WinDef$DWORD HighPart@0x4=30830697
      }
      long value@0x0=0x1D670693A827840
    }
  }
  int SystemNameLength@0x50=0x001E
  int SystemNameOffset@0x54=0x0058
}
memory dump
[50004500]
[52004600]
[01000000]
[01000000]
[01000000]
[e05c0000]
[78000000]
[01000000]
[ee000000]
[e4070800]
[03000c00]
[05001b00]
[0a00b703]
[00000000]
[b75b7062]
[25000000]
[f7a62600]
[00000000]
[4078823a]
[6970d601]
[1e000000]
[58000000]
```

**Comment by dbwiddis** [comment]
Thanks for the `PERF_DATA_BLOCK`. It's also followed by a `PERF_OBJECT_TYPE` and then several `PERF_COUNTER_DEFINITION` objects.  It's one of those counter definitions that's either missing (more likely) or corrupt.

**Comment by dbwiddis** [comment]
I'm going to go ahead and merge my fix in #1320.  Are you okay working with the SNAPSHOT for now? There are a few other tweaks I want to make before another release.

**Comment by mushion22** [comment]
Apologies for the delay, had another client to deal with. 

5.3.0-SNAPSHOT worked correctly without exceptions from my sample app.

I'll see if I can test with the AppDynamics agent also.

**Comment by dbwiddis** [comment]
No worries on my end. I'm stalling for time. :)

I'll probably cut a release over the weekend with the fix currently in snapshot.
