### ISSUE TITLE
Error when trying to get memory info in Windows

### ISSUE THREAD

**Issue by monkiki** [oshi/oshi#1324]
It works in Linux, but the same code fails on Windows:
```
java.lang.NoClassDefFoundError: Could not initialize class oshi.hardware.platform.windows.WindowsGlobalMemory
	oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.createMemory(WindowsHardwareAbstractionLayer.java:55)
	oshi.util.Memoizer$1.get(Memoizer.java:87)
	oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:78)
```

This is the Maven dependency:
```xml
<dependency>
  <groupId>com.github.oshi</groupId>
  <artifactId>oshi-core</artifactId>
  <version>5.2.4</version>
</dependency>
```

And this is the code:
```java
SystemInfo si = new SystemInfo();
HardwareAbstractionLayer hal = si.getHardware();
GlobalMemory mem = hal.getMemory();
long total = mem.getTotal();
long free = mem.getAvailable();
```

**Comment by dbwiddis** [comment]
Have you reviewed [this FAQ entry](https://github.com/oshi/oshi/blob/master/FAQ.md#how-do-i-resolve-jna-noclassdeffound-errors)?

`NoClassDefFound` errors are nearly always the incorrect JNA version loaded from somewhere as a transitive dependency.

In the case of `WindowsGlobalMemory` it's likely not finding the JNA 5.3.0 implementation of `VersionHelpers`.

**Comment by monkiki** [comment]
I've read the FAQ but I'm not sure overwriting the **jna.version** property is a good idea for Spring Boot project. Anyway thanks for the quick response :)

**Comment by dbwiddis** [comment]
JNA changes are usually additive for user mappings and backwards compatibility is always maintained within a major version.  Moving between major versions (e.g., 4.X to 5.X) can sometimes break things.

That said, both OSHI and JNA are used in many Spring Boot projects with that override.  I've even seen internal projects from Spring that specify 5.5.0 (but you should use 5.6.0 to be compatible with the new macOS). I've never heard of any reports about Spring Boot's dependencies breaking on the latest JNA.  As a committer on the JNA project, I'd be very interested in knowing if there are any problems.

**Comment by monkiki** [comment]
Thanks for the info. I will try to use a updated JNA version soon and will inform if something breaks.

Best regards.
