### ISSUE TITLE
PI Voltage Readout doesnt work

### ISSUE THREAD

**Issue by eliteSchwein** [oshi/oshi#1325]
Hey!

The Voltage Readout doesnt work on a raspberry (zero w)

https://img.eliteschw31n.de/PEBE2/PErOYEDA53.png/raw

The command itself works

The Feedback:
https://img.eliteschw31n.de/PEBE2/BarIgAfa49.png/raw

Code:

```
round(sensors.getCpuVoltage(), 4)

private double round(double value, int places) {
        if (places < 0) throw new IllegalArgumentException();

        long factor = (long) Math.pow(10, places);
        value = value * factor;
        long tmp = Math.round(value);
        return (double) tmp / factor;
    }
```

OS:Raspbian
Kernel: 5.4.51+
Code Name:buster
Version:10

**Comment by dbwiddis** [comment]
Well, this part is clearly failing the parsing:
        if (voltageStr.startsWith("volt=") && voltageStr.endsWith("V")) {
            return ParseUtil.parseDoubleOrDefault(voltageStr.replaceAll("\\^[0-9]+(\\.[0-9]{1,4})?$", ""), 0d);
        }

I don't even remember writing that. :) 

The curious thing is that's an identical regexp to the temperature one, which appears to work.  Or does your pi get its temperature from elsewhere?

In any case, that parsing needs to be fixed.

**Comment by eliteSchwein** [comment]
see https://img.eliteschw31n.de/PEBE2/PErOYEDA53.png/raw

**Comment by dbwiddis** [comment]
Yes, I saw that in your initial posting. The regexp simply doesn't work (never did). And I clearly wrote it in #928, but don't know what I was thinking. :)

**Comment by eliteSchwein** [comment]
i added now some Description to the OS

**Comment by dbwiddis** [comment]
I've fixed this in #1327, which you can test using the latest SNAPSHOT.

**Comment by eliteSchwein** [comment]
uhh can i enable snapshot in maven?

**Comment by dbwiddis** [comment]
Remind me how so I can put the instructions in the FAQ. :)

**Comment by eliteSchwein** [comment]
https://img.eliteschw31n.de/PEBE2/diNAbUsO12.png/raw Nope

my maven entry:

<dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>
            <version>5.3.0-SNAPSHOT</version>
        </dependency>

**Comment by eliteSchwein** [comment]
![image](https://user-images.githubusercontent.com/39838619/91642545-7758f280-ea2c-11ea-9cd2-eb071398b1f1.png)


oh i can upload pictures directly to github? didnt know that

**Comment by eliteSchwein** [comment]
![image](https://user-images.githubusercontent.com/39838619/91642618-1ed62500-ea2d-11ea-8040-3bf4ce56d663.png)

**Comment by dbwiddis** [comment]
Yeah, I knew that part there's elsewhere in your pom that you have to tell it where the snapshot lives. Unless it's at the default location...

Don't know why your volts aren't working. If I hardcode the string "volt=1.2000V" in the code it returns properly.
What does `vcgencmd measure_temp` return?

**Comment by eliteSchwein** [comment]
![image](https://user-images.githubusercontent.com/39838619/91642643-475e1f00-ea2d-11ea-9d12-55f0c664f092.png)
the temp is fine

**Comment by dbwiddis** [comment]
My point is that I don't have a pi to test the command on, so I hardcoded the resulting string for testing and it works.

**Comment by eliteSchwein** [comment]
hmm strange....

**Comment by dbwiddis** [comment]
Where's your code for parsing the voltage result?

**Comment by eliteSchwein** [comment]
https://github.com/eliteSchwein/PrinterCord/blob/master/src/main/java/de/eliteschw31n/commands/ServerInfo.java#L73

**Comment by dbwiddis** [comment]
And temperature is working but voltage is not.  It's practically the same code.

**Comment by dbwiddis** [comment]
Yes, it should be 1.2V.
Can you add some debugging code temporarily?
```
String voltageStr = ExecutingCommand.getFirstAnswer("vcgencmd measure_volts core");
System.out.println("Command result:" + voltageStr);
System.out.println("Parsed:" + voltageStr.replaceAll("[^\\d|\\.]+", ""));
```

**Comment by eliteSchwein** [comment]
![image](https://user-images.githubusercontent.com/39838619/91643091-8d68b200-ea30-11ea-9338-e4644e06feee.png)

**Comment by eliteSchwein** [comment]
````System.out.println("Command result:" + voltageStr);
        System.out.println("Parsed:" + voltageStr.replaceAll("[^\\d|\\.]+", ""));
        System.out.println("getVoltage:" + sensors.getCpuVoltage());````

![image](https://user-images.githubusercontent.com/39838619/91643321-601d0380-ea32-11ea-8a55-0c1ed61a6b7e.png)

**Comment by eliteSchwein** [comment]
i thing you forgot to merge it in here (the pull request is still open)

**Comment by dbwiddis** [comment]
Only thing I can guess is it's failing the initial temperature read and getting that cpu temperature from somewhere else.

I just tried a less strict parsing for temperature, can you update to the newest snapshot and test?

**Comment by eliteSchwein** [comment]
well its still merging... but i am ready to build

**Comment by dbwiddis** [comment]
I'm building the snapshot off my branch, so I don't need to merge it yet.  The most recent snapshot has the fix.

**Comment by eliteSchwein** [comment]
well i use maven.... and not the jar

**Comment by dbwiddis** [comment]
The snapshot is uploaded to maven central's snapshot repository.  Just re-build and it should fetch the latest.

**Comment by eliteSchwein** [comment]
the version is still 5.3.0-Snapshot?

**Comment by dbwiddis** [comment]
Yes.

**Comment by eliteSchwein** [comment]
still 0.0 V

**Comment by eliteSchwein** [comment]
![image](https://user-images.githubusercontent.com/39838619/91644169-e12bc900-ea39-11ea-9aad-c92189d25799.png)

**Comment by dbwiddis** [comment]
You don't need to send a screencap of the 0.0V each time. :)

I am at a complete loss for why temperature works but voltage does not.

**Comment by eliteSchwein** [comment]
i do now

```double cpuVoltage;
        if (ExecutingCommand.getFirstAnswer("vcgencmd measure_volts core") != null) {
            cpuVoltage = Double.valueOf(ExecutingCommand.getFirstAnswer("vcgencmd measure_volts core").replaceAll("[^\\d|\\.]+", ""));
        } else {
            cpuVoltage = sensors.getCpuVoltage();
        }```

**Comment by eliteSchwein** [comment]
https://github.com/eliteSchwein/PrinterCord/actions/runs/230380969 btw with snapshot my ci didnt build it

**Comment by dbwiddis** [comment]
In your code above, you'll never get null.  You should check for empty string instead. 

I'll push the patch as 5.2.5, probably tomorrow.

**Comment by eliteSchwein** [comment]
okay thanks for the information and also thanks for the patch
