### ISSUE TITLE
Wrong CPU Usage

### ISSUE THREAD

**Issue by eliteSchwein** [oshi/oshi#1326]
Hey, might be my Fault...

I get the Wrong CPU Usage...

My Code:
https://github.com/eliteSchwein/PrinterCord/blob/master/src/main/java/de/eliteschw31n/Main.java#L77
https://github.com/eliteSchwein/PrinterCord/blob/master/src/main/java/de/eliteschw31n/commands/ServerInfo.java#L68

https://img.eliteschw31n.de/PEBE2/GeWiQOVA60.png/raw
https://img.eliteschw31n.de/PEBE2/yoWuvIkI58.png/raw

It can be a code fail on my side... if it is please send me how to make it properly :)

**Comment by dbwiddis** [comment]
Looks like you're updating the previous ticks in a separate thread every second, but then calling the "between ticks" method.  Because of the memoizer's caching you have a 30% chance those are identical values.

Your "previous ticks" needs some way to note how long ago those ticks were.  Perhaps that timer loop can store the ticks in a "current ticks" variable.  In the loop, copy current to previous, then update current.

**Comment by eliteSchwein** [comment]
okay,good that you mention that it could be a seperate task, i updated it now, so it saves the double in main aswell

**Comment by eliteSchwein** [comment]
okay it made it even worser

**Comment by dbwiddis** [comment]
Not sure why you're saving the double.

The processor ticks are where the information is.  When you call the "between ticks" method you need to make sure you are passing it an "older" version of the ticks, from however long ago you want to make the measurement.

**Comment by eliteSchwein** [comment]
cpuLoad = centralProcessor.getSystemCpuLoadBetweenTicks(cpuPrevTicks);
            cpuPrevTicks = centralProcessor.getSystemCpuLoadTicks();

in the timer should be right or?

**Comment by dbwiddis** [comment]
Yes, if you put that in the timer and then just fetch the cpuLoad, it should work.

**Comment by eliteSchwein** [comment]
well it gaves me 0% usage....

**Comment by eliteSchwein** [comment]
well sh*t happens... next time i should start the timer

**Comment by dbwiddis** [comment]
Heh.   How are you manipulating non-final variables from within the timer?

**Comment by dbwiddis** [comment]
```
    public static void main(String[] args) {
        SystemInfo systemInfo = new SystemInfo();
        HardwareAbstractionLayer hardwareAbstractionLayer = systemInfo.getHardware();
        CentralProcessor centralProcessor = hardwareAbstractionLayer.getProcessor();
        final long[] cpuPrevTicks = centralProcessor.getSystemCpuLoadTicks();
        Timer timer = new Timer(1000, e -> {
            System.out.println("CPU Load: " + centralProcessor.getSystemCpuLoadBetweenTicks(cpuPrevTicks));
            long[] ticks = centralProcessor.getSystemCpuLoadTicks();
            for (int i = 0; i < cpuPrevTicks.length; i++) {
                cpuPrevTicks[i] = ticks[i];
            }
        });
        System.out.println("Startup Done!");
        timer.start();
    }
```
Output:
```
Startup Done!
CPU Load: 0.0633315593400745
CPU Load: 0.026282853566958697
CPU Load: 0.024299065420560748
CPU Load: 0.02862476664592408
...
```

**Comment by eliteSchwein** [comment]
`Exception in thread "TimerQueue" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
        at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807)
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
        at java.awt.Toolkit.getEventQueue(Toolkit.java:1736)
        at java.awt.EventQueue.invokeLater(EventQueue.java:1294)
        at javax.swing.SwingUtilities.invokeLater(SwingUtilities.java:1295)
        at javax.swing.Timer$1.run(Timer.java:614)
        at javax.swing.Timer$1.run(Timer.java:612)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.swing.Timer.post(Timer.java:612)
        at javax.swing.TimerQueue.run(TimerQueue.java:186)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by dbwiddis** [comment]
Don't see anything OSHI related in that stack trace. :)

**Comment by eliteSchwein** [comment]
yeah config issue from java itself

**Comment by eliteSchwein** [comment]
okay i fixed it https://github.com/eliteSchwein/PrinterCord/blob/master/src/main/java/de/eliteschw31n/Main.java#L78

Sorry for disturbing you with my stupidness
