### ISSUE TITLE
NoSuchMethodError on Baseboard#getManufacturer

### ISSUE THREAD

**Issue by MrExplode** [oshi/oshi#1333]
I get the following error from this call: `new SystemInfo().getHardware().getComputerSystem().getBaseboard().getManufacturer()`

`java.lang.NoSuchMethodError: com.sun.jna.platform.win32.Ole32.CoInitializeSecurity(Lcom/sun/jna/platform/win32/WinNT$SECURITY_DESCRIPTOR;ILcom/sun/jna/Pointer;Lcom/sun/jna/Pointer;IILcom/sun/jna/Pointer;ILcom/sun/jna/Pointer;)Lcom/sun/jna/platform/win32/WinNT$HRESULT;
	at oshi.util.platform.windows.WmiQueryHandler.initCOM(WmiQueryHandler.java:197)
	at oshi.util.platform.windows.WmiQueryHandler.queryWMI(WmiQueryHandler.java:132)
	at oshi.driver.windows.wmi.Win32BaseBoard.queryBaseboardInfo(Win32BaseBoard.java:57)
	at oshi.hardware.platform.windows.WindowsBaseboard.queryManufModelVersSerial(WindowsBaseboard.java:75)
	at oshi.util.Memoizer$1.get(Memoizer.java:87)
	at oshi.hardware.platform.windows.WindowsBaseboard.getManufacturer(WindowsBaseboard.java:52)`

oshi version: 5.2.5
I removed an other jna dependecy from the project, tried, then added the latest, (5.6.0) tried, same result.

**Comment by dbwiddis** [comment]
Make sure you add dependencies (at 5.6.0) for both the base JNA project (`jna`) and the user mappings (`jna-platform`).  If you have a parent pom such as Spring Boot that includes JNA, update the `jna.version` to 5.6.0.

**Comment by MrExplode** [comment]
I've added both dependencies, `jna` and `jna-platform`

**Comment by dbwiddis** [comment]
The error message indicates your project still has an older version of the Ole32 class, prior to the `CoInitializeSecurity` method being added (5.0.0), indicating you still have a 4.X (or earlier) version of `jna-platform` in your project, possibly from another dependency.   Please show me your `pom.xml` or provide a link to a copy of it.

**Comment by dbwiddis** [comment]
Were you able to resolve this?

**Comment by dbwiddis** [comment]
Since I've identified the steps you need to fix this, I'm closing the issue.  If you haven't resolved the problem, feel free to reopen with a copy of your `pom.xml` for further assistance.

**Comment by MrExplode** [comment]
Sorry for the late reply. I managed to fix the error. As you said it was the older dependency. It's name was platform.jar so I didn't noticed it first.
