### ISSUE TITLE
does oshi support overlay filesystem types?

### ISSUE THREAD

**Issue by brettbandy22** [oshi/oshi#1339]
When I run oshi.SystemInfoTest I do not see my overlay filesystem in the list.

File System:
 File Descriptors: 195440/58657580
 /dev/mapper/3624a9370cb6d0b7215af4a2e00013c4d (Local Disk) [xfs] 26.2 GiB of 30.0 GiB free (87.5%), 15.7 M of 15.7 M files free (100.0%) is /dev/mapper/3624a9370cb6d0b7215af4a2e00013c4d ...
 /dev/sdb1 (Local Disk) [xfs] 354.5 GiB of 357.4 GiB free (99.2%), 187.5 M of 187.5 M files free (100.0%) is /dev/sdb1  ...
 /dev/sdb2 (Local Disk) [xfs] 662.4 GiB of 1.4 TiB free (46.3%), 143.5 M of 150.0 M files free (95.7%) is /dev/sdb2  ...
 /dev/sdb2 (Local Disk) [xfs] 662.4 GiB of 1.4 TiB free (46.3%), 143.5 M of 150.0 M files free (95.7%) is /dev/sdb2  ...
 /dev/sdb1 (Local Disk) [xfs] 354.5 GiB of 357.4 GiB free (99.2%), 187.5 M of 187.5 M files free (100.0%) is /dev/sdb1 ...

When I run mount I see the overlay mount point

overlay on / type overlay (rw,relatime,...)

This is being run docker container running Centos.

**Comment by dbwiddis** [comment]
Issue #438 may be relevant.   That format for `mount` seems unusual.  Can you post the actual output?

**Comment by brettbandy22** [comment]
mount output:

overlay on / type overlay (rw,relatime,lowerdir=l/ZX33FJHR6ZKNQPAUNEBITYBL4W:l/K2SUYJLJZ3OKTYWD657I3NRZS6:l/POXRC354LXC53CJ23X6KMN3XUH:l/TD56VRMZCXHKNQ4CARJYW7IRM3:l/TBSCYPMIZ47S4I4W7SUFNUG5AO:l/US2CNAEDPILLUHYZKGAR6T6MRP:l/5TWLT27ADIRBLZBVMCYDYL4PCN:l/67ZXXSGKGQDSDWG6PTFAAW3AWV:l/FRYHPY5J2MLNLACJP6EPHR34Q4:l/KXXG63ZIHAUCIUIRU62DPZTBRF:l/N5JRGJHBB2ALYTBLHWQFVDTEOF:l/F5R62ISBRHTFDCJ6TYKSZR3WQJ:l/3CIGP5XZGYOQEAFCTTQMSGYXEB:l/7WXK6YTHFP7O67VUEEFEHV2DVK:l/ZVQBN5UWXCY7XUPLDSGYM4VJMZ:l/37SBPZFUR6H5ELFC7T5KPKNILK:l/BGTIGCOFSI3MOGTEO7UTNE2GYN:l/OGKX4N34ZRQRNJEPYMDWWJ33LR:l/VVIBOCQL5NB5UXP6GVUDNT4D6X:l/AL4ZLVM6322QUBYES3OJ5EEEOK:l/LXJNXL23INBCK2F3TM2X2BNADT:l/LY23HDXGJZIRDDOSAGLD2CJPRT:l/ZIQQVHPF33AUE6T2UJ3SSO66XX:l/ZHWF425G3TU3T6JKUXYSBKNNV7:l/FZK6J2OK3RMZKCZT643EFZG6DJ:l/LURMT5KAKGXHHLY7M7OZ3BR4AA:l/54CCKZFOXAPJZB2N4CA2F64XF7:l/3TQUA7X5P5DERSMUWJ5Z6Q7EF5:l/GIR3XZKZ4EIUKPCOG6Q4KVNSNM:l/5ZMBPY6FBYU3S6OPKZ6YS522SV:l/YLOEPIM6HSVQNBETFUM6MYG4FZ:l/FPMVIEUG4PP2PPMX2K62UBUOOX:l/UIBE7N4ZYCQ3DO7V6VF2TAHKX6:l/Z3NAWDYO2U37UIOABHTWVXYXDP:l/O5LJDQQUUO5YHJP4XTYIHJKPKK:l/GE6UBUWYBNVQEXXXJBLNWJA6EK:l/JDA2ZGRZKEZYEH75TTK7YDCPFL:l/6UZFCH5CRZXVOEDPFVH7L4Z4PO:l/COQDPXKCH7GZNP6OK6J5HASQEO:l/G3NDW7QH5JG6HHZTZRZOEPDCDT:l/K35D4OJF45OQOEZGWKRQJCZIKP:l/UP3BYCXQ4PLUEY25J3OF56YI7M:l/ZNHP7L3TJWIYWK7JMXZNIPEX5L:l/WYEE2VFUUAO25J2VOXPUJGATKI:l/B7LPMKTOTR445GCQCR4VGMFMWS:l/A4KT7NVQW6Z2XWXF6H5OUWUFDX:l/V6QRNTVYLKIGYEXQ64UZJXMUCR:l/SK7SCIAHD245VTFQXZ2KZT563K:l/LSTCJ6PWLAGLYLZ3TK5NWHTPFJ:l/UM7JCDI75D6Z4F5YM4GKEU7W46:l/4PRHEVTQHOMGBUAEKRSOVKIFPG:l/ZDZBY2QKGJGHTXJ6JQXQT3WDXP:l/M4EG24DUOE7A6BHFONYZDGNIEI:l/RFR74PDAIFSXCOSZDPA3GTUMUY:l/UJJZRVLPRES6PJGHTX6KCLR4HX:l/XJI4KH4WPQQPVBF66MDGXAFJS3:l/UDSBLE4SUFOIGR5VOAP5YZE4Q2:l/2PFDHV6KXWEKLSXZBCQESNKC3R:l/MV7C2PAWFWQT33UCH4DDNJQAYY:l/PUHP42JK2BCHOI5W2F2WXUJ375:l/AOPBLCCQS7S6OL4RMVYV22B77N:l/BSLMHBCXDUIPCNYACMSY2S7UBU:l/DK5HAH7MF2X6G5CN2JYIXZTG2I:l/BMLDJMFBRTTQKLUWY674TLW64C:l/27OCZSK53JRUHLHAFRK4TJMDYB:l/EXKZ5XMXK7SSAL66QJU7X5EAFV:l/J5M27KVB7T2PKERQZ2DMOMNHT6:l/UM5MYNOW7KPTH4HIYGD2NT7BOB:l/JHMMSQB3LD5WICOISJIBRINBEL:l/SCXVBGHZCCGRY5TMJIN36TZCD2:l/OBYMBTMZQEFL5YNQEKKNWWSJSH:l/U35FQBRTGNO46YSNEDKVFDNY5J:l/7IG6UH4BZTCAIAPTIBDDET3C7C:l/3RQZVBEFDMU7UBF5KF6CRIWMYA:l/BZE6HULA5WP2IWZEYFZXWKGSXO:l/RCOF5MGPUAN7WQYNPRPX5TL74K:l/2X4MOCDCU2HDXIIFGNDUFQUEBD:l/RNWZQ34MIM4TSGDPTSQMXW3SQM:l/DD2BVIMXWL6TED2FFDMUUXJ6TR:l/ID44LFIORJHE3G2HRHEWNFOXDQ,upperdir=2b8af7af6bbe35a8d1a98f1046a228e2de331704078720f1cfccf2fd054e1732/diff,workdir=2b8af7af6bbe35a8d1a98f1046a228e2de331704078720f1cfccf2fd054e1732/work)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,size=65536k,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,relatime,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (ro,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/freezer type cgroup (ro,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/devices type cgroup (ro,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/perf_event type cgroup (ro,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/pids type cgroup (ro,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/memory type cgroup (ro,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/blkio type cgroup (ro,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (ro,nosuid,nodev,noexec,relatime,cpuacct,cpu)
cgroup on /sys/fs/cgroup/cpuset type cgroup (ro,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (ro,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (ro,nosuid,nodev,noexec,relatime,net_prio,net_cls)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
/dev/mapper/3624a9370cb6d0b7215af4a2e00013c4d on /pvc-vol type xfs (rw,relatime,nouuid,attr2,discard,inode64,noquota)
/dev/sdb1 on /dev/termination-log type xfs (rw,nodev,noatime,nodiratime,attr2,nobarrier,inode64,noquota)
/dev/sdb2 on /etc/resolv.conf type xfs (rw,nodev,noatime,nodiratime,attr2,nobarrier,inode64,noquota)
/dev/sdb2 on /etc/hostname type xfs (rw,nodev,noatime,nodiratime,attr2,nobarrier,inode64,noquota)
/dev/sdb1 on /etc/hosts type xfs (rw,nodev,noatime,nodiratime,attr2,nobarrier,inode64,noquota)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
tmpfs on /run/secrets/kubernetes.io/serviceaccount type tmpfs (ro,relatime)
proc on /proc/bus type proc (ro,relatime)
proc on /proc/fs type proc (ro,relatime)
proc on /proc/irq type proc (ro,relatime)
proc on /proc/sys type proc (ro,relatime)
proc on /proc/sysrq-trigger type proc (ro,relatime)
tmpfs on /proc/acpi type tmpfs (ro,relatime)
tmpfs on /proc/kcore type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/keys type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/timer_list type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/timer_stats type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/sched_debug type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/scsi type tmpfs (ro,relatime)
tmpfs on /sys/firmware type tmpfs (ro,relatime)

**Comment by dbwiddis** [comment]
OSHI does explicitly exclude `overlay` filesystem types as a pseudo filesystem.

If you would like special treatment of this for a particular use case, I'd welcome a PR.

**Comment by dbwiddis** [comment]
Closed in #1358
