### ISSUE TITLE
Operating System Usage Info

### ISSUE THREAD

**Issue by Shikari0744** [oshi/oshi#1340]
**1 :** Can anyone tell me how to calculate Network Usage per process(for any process pid say 1234) ?

**Comment by Shikari0744** [comment]
> **1 :** Can anyone tell me how to calculate Network Usage per process(for any process pid say 1234) ?

@dbwiddis

**Comment by dbwiddis** [comment]
The subject line says Disk but you are asking for Network.

The OSProcess object includes getters for disk usage (`getBytesRead()` and `getBytesWritten()`) but does not provide per-process network statistics.

**Comment by Shikari0744** [comment]
One more thing that I like to add is, **getProcessCpuLoadBetweenTicks()** gives me wrong values :
I am using it like that. Tell me If I am doing wrong : - 
```
import oshi.SystemInfo;
import oshi.hardware.CentralProcessor;
import oshi.software.os.OSProcess;
import oshi.software.os.OperatingSystem;
import oshi.util.Util;

public class CpuUsage {
    public static void main(String[] args) throws InterruptedException {
        SystemInfo systemInfo = new SystemInfo();
        OperatingSystem operatingSystem = systemInfo.getOperatingSystem();
        CentralProcessor centralProcessor = systemInfo.getHardware().getProcessor();
        int cpuNumber = centralProcessor.getLogicalProcessorCount();
        OSProcess osProcess;
        osProcess=operatingSystem.getProcess(8764);
        while(true) {
            double res=osProcess.getProcessCpuLoadBetweenTicks(osProcess);
            System.out.println("Percentage: "+(res/cpuNumber)+" %");
            System.out.println("***********************************************************\n");
            Util.sleep(5000);
        }
    }
}

```

**Comment by Shikari0744** [comment]
In order to avoid this statement : - **if(previousTime !=0) { ... }** 
I need to initialize the previousTime variable to some value . 
I tried initializing the values with getUpTime() or getUserTime() or 0 but I am getting very higher values for those processes whose cpu usage are greater than 80%(in Task Manager) 
**Code : -**
```
 public Map<String, Double> measure() {
        Map<String,Double> cpuUsage = new HashMap<>();
        OSProcess process;
        SystemInfo systemInfo = new SystemInfo();
        OperatingSystem os = systemInfo.getOperatingSystem();
        CentralProcessor processor = systemInfo.getHardware().getProcessor();
        process = os.getProcess(os.getProcessId());
        int cpuNumber = processor.getLogicalProcessorCount();
        long currentTime = process.getKernelTime() + process.getUserTime();
        if (previousTime !=0)
        {
            long timeDifference = currentTime - previousTime;
            double processCpu = (100d * (timeDifference / ((double) 5000)))  / (os.getFamily().equalsIgnoreCase("windows")?cpuNumber:1 );
            cpuUsage.put("cpuUsage",processCpu);
            Util.sleep(5000);
        }
        previousTime = currentTime;
        return cpuUsage;
    }
```

**Any solution for this ?**
It would be big help ...

**Comment by Shikari0744** [comment]
> 
> 
> One more thing that I like to add is, **getProcessCpuLoadBetweenTicks()** gives me wrong values :
> I am using it like that. Tell me If I am doing wrong : -
> 
> ```
> import oshi.SystemInfo;
> import oshi.hardware.CentralProcessor;
> import oshi.software.os.OSProcess;
> import oshi.software.os.OperatingSystem;
> import oshi.util.Util;
> 
> public class CpuUsage {
>     public static void main(String[] args) throws InterruptedException {
>         SystemInfo systemInfo = new SystemInfo();
>         OperatingSystem operatingSystem = systemInfo.getOperatingSystem();
>         CentralProcessor centralProcessor = systemInfo.getHardware().getProcessor();
>         int cpuNumber = centralProcessor.getLogicalProcessorCount();
>         OSProcess osProcess;
>         osProcess=operatingSystem.getProcess(8764);
>         while(true) {
>             double res=osProcess.getProcessCpuLoadBetweenTicks(osProcess);
>             System.out.println("Percentage: "+(res/cpuNumber)+" %");
>             System.out.println("***********************************************************\n");
>             Util.sleep(5000);
>         }
>     }
> }
> ```

@dbwiddis

**Comment by dbwiddis** [comment]
You don't need to quote your own content and ping me within 24 hours. I'm subscribed to this project and get every message, but might not be in your time zone and able to immediately respond.  

Your implementation for `getProcessCpuLoadBetweenTicks()` isn't correct:
```
osProcess=operatingSystem.getProcess(8764);
while(true) {
    double res=osProcess.getProcessCpuLoadBetweenTicks(osProcess);
    System.out.println("Percentage: "+(res/cpuNumber)+" %");
    System.out.println("***********************************************************\n");
    Util.sleep(5000);
}
```
The first call populates the `osProcess` object with ticks at time 0. 

Then, in the loop:

- First iteration, time 0: There is no delay before the second call, so it would return identical values to the first object. The default behavior in this case is to return the cumulative (since process start) CPU usage.
- Second iteration, time 5s: This gives you what you expect, the CPU usage for the past 5 seconds.
- Third iteration, time 10s: This gives you CPU usage between your initial stored value at time 0 and now, CPU usage for the past 10 seconds.
- Fourth iteration, time 15s: CPU usage for the past 15 seconds.
- And so on.

You will probably see the results you want if you collect the new process object in the loop right after getting the load between ticks:
```
osProcess=operatingSystem.getProcess(8764);
while(true) {
    double res=osProcess.getProcessCpuLoadBetweenTicks(osProcess);
    osProcess = os.getProcess(os.getProcessId()); // The ticks you just calculated
    System.out.println("Percentage: "+(res/cpuNumber)+" %");
    System.out.println("***********************************************************\n");
    Util.sleep(5000);
}
```
The first iteration, with no time delay, will still return "cumulative since start" but after that you'll get the CPU usage for the last 5 seconds each time.

**Comment by dbwiddis** [comment]
Also please don't change the subject line and ask a new question, as that's confusing to future readers.  Just open a new issue for a new question.

**Comment by Shikari0744** [comment]
```
public static void main(String[] args) throws InterruptedException {
        SystemInfo systemInfo = new SystemInfo();
        OperatingSystem operatingSystem = systemInfo.getOperatingSystem();
        CentralProcessor centralProcessor = systemInfo.getHardware().getProcessor();
        int cpuNumber = centralProcessor.getLogicalProcessorCount();
        while(true) {
            OSProcess osProcess;
            int pid = 6888;
            osProcess = operatingSystem.getProcess(pid);
            double res=osProcess.getProcessCpuLoadBetweenTicks(osProcess);
            System.out.println("Percentage: "+(res/cpuNumber)+" %");
            System.out.println("***********************************************************\n");
            Util.sleep(2000);
        }
```

Is this what you meant ?
Using OSProcess inside while loop, but still I am not getting the expected value. If you have an implementation for that can you please shared ?

**It would be big help .**

**Comment by dbwiddis** [comment]
Keep an instantiation `OSProcess oldProcess;` outside of the loop. You will re-use this variable.

Remember this is the "old" process. You want this to be "old" when you call `getProcessCpuLoadBetweenTicks()` with it.

Call `getProcessCpuLoadBetweenTicks()` first (referencing an "old" process), and after you've called that, update the `osProcess` variable to the current time  (`getProcess()`).

```
OSProcess oldProcess;
int pid = 6888;
while(true) {
    OSProcess osProcess = operatingSystem.getProcess(pid);
    double res=osProcess.getProcessCpuLoadBetweenTicks(oldProcess);
    oldProcess = osProcess;
    System.out.println("Percentage: "+(res/cpuNumber)+" %");
    System.out.println("***********************************************************\n");
    Util.sleep(2000);
}
```
