### ISSUE TITLE
Determining supported and unsupported metrics

### ISSUE THREAD

**Issue by rnaval** [oshi/oshi#1341]
Is there a way for a calling application to know if a metric is supported by the OS or not?

For example, in a Windows machine, it is mentioned that some values are not supported i.e (http://oshi.github.io/oshi/oshi-core/apidocs/oshi/hardware/CentralProcessor.html):

"Nice and IOwait per processor information is not available on Windows, and IOwait and IRQ information is not available on macOS, so these ticks will always be zero."

So if I call `getProcessorCpuLoadTicks()` on Windows, I get an array where the Nice and IOWait values are 0.

As a calling application, I only know that I have no ticks for Nice and IOWait, not that they are unsupported.

For linux kernels, this is a bit more complex as well (See https://man7.org/linux/man-pages/man5/proc.5.html):
- IOWait is only available from Linux 2.5.41 
- IRQ and SoftIRQ is only available from Linux 2.6.0
- Steal is only available from 2.6.11

Is there are recommended way to check if a metric is supported via some sort of discovery or something? Or is it up to the calling application to check the OS and weed out unsupported metrics?

**Comment by dbwiddis** [comment]
Unfortunately other than "reading the javadoc" when implementing methods, there is not.  

I made the decision early on to return "sensible defaults" in most cases.  There has been ongoing discussion on this, see https://github.com/oshi/oshi6/issues/2 ... it is envisioned for a future complete rewrite to handle this properly.

**Comment by rnaval** [comment]
For the case of ticks, can't the `UNKNOWN` case be represented by `-1` instead of `0`? This should be able to distinguish the case where metric is unknown vs. the case where the metric is indeed 0. Or is there an issue if we do this?

**Comment by dbwiddis** [comment]
In theory, yes.  In practice, then you'd have to introduce special handling in all the code that adds up ticks from various sources, to add back the -1 that's not really a -1. 

Switching to a nullable or optional type really is probably the way to go in the long term.

**Comment by rnaval** [comment]
OK agreed. I'll close this issue for now. Will revisit once we start using OSHI6.
