### ISSUE TITLE
getVendorFreq() returns -1 for an AMD processor on Windows

### ISSUE THREAD

**Issue by rnaval** [oshi/oshi#1344]
When `cpuName` obtained is something like "AMD Ryzen 5 3600 6-core Processor", `getVendorFreq()` returns -1.

This seems to be caused by the way that it parses the `cpuName` value here:

https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/hardware/CentralProcessor.java#L461

It seems that it cannot find the `@` character which usually denotes the frequency (for Intel Processors at least)

EDIT: This was tested in a Windows Machine.

**Comment by dbwiddis** [comment]
So, how does one find the vendor advertised frequency for an AMD chip?

**Comment by rnaval** [comment]
In this case, it is that "obvious" 3600 - but looking at various AMD cpu types, it does not seem that they have a consistent convention in place like the Intel ones.

For example, it can have "AMD EPYC 7571" - no frequency whatsoever.

Maybe this can be obtained in linux via `/proc/cpuinfo`. 

For windows, no idea yet (that oshi does not do) - but DirectX Diagnostics seem to be able to get it properly, e.g.

![image](https://user-images.githubusercontent.com/12891375/94546932-e75bd200-0291-11eb-8d61-0421a802629d.png)

Not sure how they do it though.

**Comment by dbwiddis** [comment]
I've seen the value Windows returns for "max" frequency often match exactly, which is a reasonable fallback. But then, that's also accessible to the user. 

The "Vendor" frequency as part of the "Processor Identifier" object could be seen as a parallel to the CPUID 16h instruction for "Processor Base Frequency", but that only works on newer Intel (and some AMD?) processors.  We could add a lookup table, but that seems like a hack.   Note that native programs in C (e.g., DirectX Diagnostics) can access that, but machine level instructions don't work in Java.

I'm thinking a fallback to "Max" on some operating systems would be appropriate.   As that is accessible to users already that's not a high priority for me to work on, but I'll probably get around to it eventually.  I'd welcome a PR.

**Comment by dbwiddis** [comment]
See #1296 for more detailed discussion on frequencies that may be relevant.

**Comment by rnaval** [comment]
For one of the tests we did, `getMaxFreq()` seems to have been behaving oddly for the 48-CPU AMD EPYC 7571, running on Windows Server 2019 64-bit.

Values were fluctuating, e.g.

644293308000000 Hz then
1854837472000000 Hz then 
1535333756000000 Hz then
642434308000000 Hz then

Note that the vendor frequency is supposed to be 2.2.GHz.

These were taken across 20s intervals. Was under the impression that the max frequency, if ever it would change, would only be increasing.

**Comment by dbwiddis** [comment]
Well, that's really interesting.  I had the same impression.  OSHI gets its values from [PROCESSOR_POWER_INFORMATION](https://docs.microsoft.com/en-us/windows/win32/power/processor-power-information-str) which defines `MaxMhz` as:
> The maximum specified clock frequency of the system processor, in megahertz.

It's clearly listed separately from the throttling limit, `MhzLimit`:
> The limit on the processor clock frequency, in megahertz. This number is the maximum specified processor clock frequency multiplied by the current processor thermal throttle limit.

At this point, I'm getting rather confused.

**Comment by dbwiddis** [comment]
Any chance you can see if this registry key has the vendor freq?

`HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\CentralProcessor\0` and look for `~MHz`.
