### ISSUE TITLE
runNative locale issues on linux

### ISSUE THREAD

**Issue by XakepSDK** [oshi/oshi#1347]
This code will not work as expected if locale in not english or C
https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java#L123

Proposed fix: set env. variable `LC_ALL=C`
I can't make PR because i don't have sane internet right now.

**Comment by dbwiddis** [comment]
Will that setting be limited to just the thread that runs it?  Should this be applied to every command line call?

**Comment by XakepSDK** [comment]
Should be applied to every command line call. Something like `Runtime.exec(cmd, new String[] { "LC_ALL=C" })`
I think this is needed on all systems except windows.
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap07.html (7.2 POSIX Locale)

**Comment by dbwiddis** [comment]
OK, so it looks like the easiest solution is in `ExecutingCommand` to prepend every *nix commandline with `LC_ALL=C`.  For Windows, the only command line we use is `route` so I'll have to see if there's an equivalent.

**Comment by dbwiddis** [comment]
It appears `LANGUAGE=C` works for Windows.  Alternately the combination `LANGUAGE= LC_ALL=C`.

**Comment by dmitraver** [comment]
Hi, I can pick this up.

**Comment by dbwiddis** [comment]
Great, thanks!

You might find `SystemInfo.getCurrentPlatformEnum()` useful for detecting if on Windows or *nix.

**Comment by dmitraver** [comment]
@dbwiddis, perfect, thanks for the tip, was having exactly this question in mind :)

**Comment by dbwiddis** [comment]
And @XakepSDK 's suggestion to use the 3-argument `exec()` is probably good too.  Good luck!

**Comment by dmitraver** [comment]
@dbwiddis 
I'm about to make a PR, however I noticed that this tests fails for me on master **InternetProtocolStatsTest.testIPStats(InternetProtocolStatsTest.java:67)**

`assertTrue(tcp6.getSegmentsSent() >= 0);`

I have -467 returned there. I'm running it on MacOS 10.14.2. Do you have any ideas why that could happen?

**Comment by dbwiddis** [comment]
See #1352.  I'm curious what xcode version you have?

Bottom line, you can ignore it.  I'm trying to figure out how to deal with it.

**Comment by dmitraver** [comment]
I don't have xcode installed but CommandLineTools. I will make a PR then.
