### ISSUE TITLE
OSHI-Core-5.2.5 causes WMI Provider Host WmiPrvSE.exe process CPU to spike up to 40% on Windows Server 2016

### ISSUE THREAD

**Issue by RajeshPutta87** [oshi/oshi#1351]
Hi Team,

I am from AppDynamics. We have AppDynamics Machine Agent component (java based component) to capture infrastructure level metrics. We use OSHI 5.2.5 with in Machine Agent component to collect some infrastructure metrics (like Process Metrics,
CPU, Memory) 

Machine Agent 20.9.0 uses OSHI-core 5.2.5 version. This environment causes WMI Provider host WmiPrvSE.exe process CPU to spike at every 30 seconds interval whenever we collect metrics. Once the collection is done, CPU goes normal and again spikes up to 40% whenever we collect.

Machine Agent 20.5.1 uses OSHI-core 4.1.1 version. This environment doesn't cause any CPU issues.

Also when we fall back to Sigar based collection, we do not see any issues with CPU.

Please find the Webex video recording which demonstrates the issue. 

Recording URL: https://cisco.webex.com/recordingservice/sites/cisco/recording/playback/16203e5e90154e9d955500089d27d060
Recording password: YzikV6Y8

In the recording you can find WmiPrvSE.exe host process CPU consumption differences first when tried with Machine Agent 20.9.0 using OSHI-core 5.2.5 and other Machine Agent 20.5.1 using OSHI-core 4.1.1. 

Also please find attached dumps collected when the CPU spikes here
https://drive.google.com/file/d/1BMHsBKunCafTggJXylGQHbqRJqY3hkss/view?usp=sharing

Dumps are collected using ProcDump utility

procdump64.exe -ma -c 20-s 3 -n 3 <PID Or PName>
procdump64.exe -ma -c 15-s 3 -n 3 <PID Or PName>

Please review it and let us know your thoughts about any issues with OSHI-core 5.2.5 version.

Thanks

Rajesh

**Comment by dbwiddis** [comment]
Hi Rajesh, thanks for the report.  I'll try to help with as much insight as I can, but 4.1.1 (Oct 2019) to 5.2.5 (Aug 2020) is a big gap and I don't see anything obvious in the change log other than the 5.x refactoring.

I haven't looked at the dumps yet, but some initial thoughts:
 - Most of the WMI information fetched by OSHI is for rarely changing information. You stated "CPU, Memory, and Process information".
   - CPU information does not use WMI, unless the performance counters it is fetching from are misconfigured, where it uses WMI as a backup.  Is this an identical machine/perfmon config using both versions?
   - Memory information only uses WMI for the "Physical Memory" Part which should not need to be repeatedly fetched.
   - Process information only uses WMI for the command line.  This was refactored in 5.0.0 to change from a single query to per-process query, but a configurable option was added in 5.0.2 to allow "cache" queries.  If you are fetching all command lines for all processes every 30 seconds, this is a likely source of a problem.  Set the config parameter `oshi.os.windows.commandline.batch` to `true` in the config file or programmatically using the constant `WindowsOSProcess.OSHI_OS_WINDOWS_COMMANDLINE_BATCH`.
   - If you are fetching other information every 30 seconds, consider whether you can reduce the polling interval.  USB Device information is a known performance hit.

**Comment by RajeshPutta87** [comment]
Hi Daniel,

Thanks for the suggestions. Please let me know if we can do a Webex session so that we can directly work on the environment. If you are ready to do a Webex session, please let me know what time and time zone works for you.

Thanks
Rajesh

**Comment by dbwiddis** [comment]
Let's try some of the obvious things first, with debugging steps recorded here on GitHub so they can be helpful to others (or even myself) later.  Have you tried the batch configuration for Process Command Lines?

**Comment by RajeshPutta87** [comment]
Hi Daniel,

Thanks for the update. Please let me know where do i need to set this parameter ->oshi.os.windows.commandline.batch. Which file you want me to set that parameter. Please provide clear details.

Thanks
Rajesh

**Comment by dbwiddis** [comment]
That parameter is in the [`oshi.properties`](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/resources/oshi.properties) file deployed with the JAR. 

You can also programmatically change this when your application starts up using:
```
GlobalConfig.set(WindowsOSProcess.OSHI_OS_WINDOWS_COMMANDLINE_BATCH, true);
```

**Comment by RajeshPutta87** [comment]
Hi Daniel,

Thanks for the update. I have made changes to the jar and rebuilt it. Post that i tested with those changes. I can see a significant improvement in terms of CPU usage. We are going to try those changes with customer 

Btw do you have any plans of releasing oshi core jar from your end with those changes as other users will also get benefitted out of it in case they run into issues.

Thanks
Rajesh

**Comment by dbwiddis** [comment]
> Btw do you have any plans of releasing oshi core jar from your end with those changes 

The existing JAR enables that through either config or programmatic config change. The only difference I could make is which to choose for the default.  I may consider clarifying the documentation to make this particular choice more clear, but I don't see a need to change the compiled code here.

**Comment by RajeshPutta87** [comment]
Sure thank you

**Comment by appdashishmehta** [comment]
Update:

We added the following parameter programmatically and verified it taking effect at runtime:
`GlobalConfig.set(WindowsOSProcess.OSHI_OS_WINDOWS_COMMANDLINE_BATCH, true);`

**Comment by RajeshPutta87** [comment]
Daniel,

We can close this issue. Please update your documentation so that it will help others as well

Thanks once again

Regards
Rajesh

**Comment by dbwiddis** [comment]
FAQ and Javadocs clarified in this commit: https://github.com/oshi/oshi/commit/fec46c1831e94fba3e650117bc01f1e3b2a574c9
