### ISSUE TITLE
OSProcess not showing process name

### ISSUE THREAD

**Issue by dazhitchman** [oshi/oshi#1364]
The OSProcess fails to get the name of the running process if the running user doesn't have permission to the /proc/{pid}/cmdline
e.g. this process ( as reported by ps -ef )
`root           6       2  0 Oct14 ?        00:00:00 [kworker/0:0H-kblockd]`
returns en empty string for the name of the process
`(LinusOSProcess.java:337) --> this.name = status.getOrDefault("Name", "");`

The name is available in the /proc/{pid}/stat file which is already parsed into the statArray.
e.g. 
`6 (kworker/0:0H-kblockd) I 2 0 0 0 -1 69238880 0 0 0 0 0 0 0 0 0 -20 1 0 20 0 0 18446744073709551615 0 0 0 0 0 0 0 2147483647 0 0 0 0 17 0 0 0 0 0 0 0 0 0 0 0 0 0 0`

It would be trivial to extract the process name from the stat file when the cmdline access returns null

**Comment by dbwiddis** [comment]
The name and command line are two different things.  `/proc/[pid]/cmdline` is the full command line including path and arguments.  The name comes from `/proc/[pid]/status`.  Does that file have permission issues?

I'm fine with using `/proc/[pid]/stat` as a backup.  

FYI the stat array is numeric and ignores the name, but we do have the string `stat`.  The same backup should be used for the process State, which also pulls from `/proc/[pid]/status` but could be parsed from `stat` as a backup.

**Comment by J-Jimmy** [comment]
I'd like to work on this, I won't be able to start before sunday, but im confident to finish it on sunday aswell.

**Comment by dbwiddis** [comment]
Sounds good.  I would like to cut a release on Sunday for the Windows processor bugfixes, but I'll hold off for this one as well!

**Comment by dazhitchman** [comment]
On a quick side note (as Im new to this forum). Is raising an issue the best way to discuss feature requests / developer contributions. I had some questions/ideas for AIX Impl of PerfstatProcess

**Comment by dbwiddis** [comment]
Absolutely. It’s the preferred method actually.  Worst case I close it.  Best case we discuss a great feature.

**Comment by dazhitchman** [comment]
I’m happy to take the code change if you run out of time Sascha. 
Darren

**Comment by dbwiddis** [comment]
In the interest of making sure this bug(?)fix gets in by this weekend when I plan to release the other fix, I'm okay with whoever gets this done the soonest.  I'm trying to keep "easy" PRs available for Hacktoberfest, but fixing bugs doesn't need to wait.

**Comment by dbwiddis** [comment]
Fixed in #1368

**Comment by dazhitchman** [comment]
Good work. Thanks
