### ISSUE TITLE
Total number of inodes less than free inodes

### ISSUE THREAD

**Issue by J-Jimmy** [oshi/oshi#1367]
So I just setup the WSL2 with Ubuntu 20.04 LTS on Win10 and cloned the repo there.
When I run the tests in the master branch, I get this exception:

java.lang.AssertionError: Total number of inodes should be greater than or equal to number of free inodes on non-Windows systems

Here the details about the mount point throwing this exception:
logicalVolume = ""
description = "Mount Point"
fsType = "9p"
freeSpace = 4869537792
usableSpace = 4869537792
totalSpace = 126641762304
freeInodes = 1000000
totalInodes = 999
name = "tools"
volume = "tools"
label = "tools"
mount = "/init"
options = "ro,dirsync,relatime,aname=tools;fmask=022,loose,access=client,trans=fd,rfd=6,wfd=6"
uuid = ""

It may be relevant that my ssd has only 8GB of disk space left, however the WSL2 initialized the Ubuntu system with 250GB storage (my SSD has 128GB in total).
It may be that the system is completely wrong initialized and if that doesn't concern OSHI you may just close this issue.

**Comment by dbwiddis** [comment]
Do you have an independent command in the filesystem to check the inode values?  `sudo df -ih /init` should work.   It's possible that filesystem should be excluded from the test.

**Comment by dbwiddis** [comment]
It's also possible that any "read only" filesystem returns an invalid value for inodes and should be excluded from that test.

**Comment by J-Jimmy** [comment]
Filesystem     Inodes IUsed IFree IUse% Mounted on
tools             999 -976K  977K     - /init

**Comment by dbwiddis** [comment]
Negative 967K used?  Heh.  

So OSHI is faithfully reporting the stats from the filesystem.  I don't see a bug in OSHI but we should figure out under what circumstances the test fails.  The `999` looks rather suspicious as a hardcoded field, perhaps looking at the source code would reveal when it's used, and we could suppress the test in those cases.

**Comment by dbwiddis** [comment]
I'm confident this is an external bug, but not sure where. It seems to have to do with quotas on shared drives..  Here's a [similar bug on RHEL](https://bugzilla.redhat.com/show_bug.cgi?id=1665990).  Here's another (possibly the same bug) [report](https://access.redhat.com/solutions/2917041).

Not sure if the difference is in a common bug in the kernel that persists across distributions, but perhaps you can find out more.

**Comment by dbwiddis** [comment]
I'll go ahead and close this as OSHI is simply reporting what the OS reports.  If you are able to identify a repeatable condition when this occurs that should be excluded from tests, feel free to reopen this issue.
