### ISSUE TITLE
AdjustTokenPrivileges failed log error when not running with elevated permissions

### ISSUE THREAD

**Issue by jflefebvre06** [oshi/oshi#1372]
Hello,

After switching to 5.3.0/5.3.1 I get the error above, any idea ?

[ERROR] oshi.software.os.windows.WindowsOperatingSystem [main] AdjustTokenPrivileges failed. Error: 1300

**Comment by dbwiddis** [comment]
Well, that error is a result of [this change](https://github.com/oshi/oshi/commit/0ff7434a6e600e8b86842c733e20e76108dc8366).

Previously, the "failure" was always occurring, but silently.

The [AdjustTokenPrivileges function](https://docs.microsoft.com/en-us/windows/win32/api/securitybaseapi/nf-securitybaseapi-adjusttokenprivileges) can return success without actually working. In that case it returns `ERROR_NOT_ALL_ASSIGNED`:
> The token does not have one or more of the privileges specified in the _NewState_ parameter. The function may succeed with this error value even if no privileges were adjusted. The _PreviousState_ parameter indicates the privileges that were adjusted.

In the remarks:
> The _NewState_ parameter can specify privileges that the token does not have, without causing the function to fail. In this case, the function adjusts the privileges that the token does have and ignores the other privileges so that the function succeeds. Call the `GetLastError` function to determine whether the function adjusted all of the specified privileges. The _PreviousState_ parameter indicates the privileges that were adjusted.

I did not expect this case to occur, as only one privilege is being adjusted (enabling debug) so I didn't create a more verbose error message using the states above, but it appears to have "partially" failed in your case.  It may be that your account does not have the required permissions level to enable debug privilege.

The code will continue to execute in this case, but you may find you're not able to obtain some information about other processes.

**Comment by dbwiddis** [comment]
[This MSDN page describes the missing access right](https://docs.microsoft.com/en-us/previous-versions/ms813847(v=msdn.10)) on the user executing OSHI.  I'll update the errror message to be more verbose.

**Comment by dbwiddis** [comment]
On further reading, this is a normal, expected error when not running OSHI as administrator.  
 * The log message should be downgraded to either INFO or DEBUG.
 * A split between "failed" (returns false, log error) and a secondary check LastError = "Not All Assigned" (expected for non-admin) should be done, [similar to this example](https://docs.microsoft.com/en-us/windows/win32/secauthz/enabling-and-disabling-privileges-in-c--).

I'll get this update into 5.3.2.  For now, the issue is cosmetic, and the error message can be ignored.

**Comment by jflefebvre06** [comment]
Hello @dbwiddis 
Thanks for your reply
