### ISSUE TITLE
Outofmemoryerror occurred

### ISSUE THREAD

**Issue by dwj1979** [oshi/oshi#1392]
I am using oshi to obtain the utilization rate of system resources. However, the following OutOfMemoryError has occurred frequently in the system recently. 

java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: GC overhead limit exceeded

By analyzing dumplog (using jhat java_pid8732.hprof ), it is found that there are a large number of oshi's instances, as follows:

Instance Counts for All Classes (excluding platform)
811603 instances of class oshi.util.platform.windows.PerfCounterQueryHandler

my code be excuted every second in the timer job:
List<HWDiskStore> diskStores = hal.getDiskStores();
        for (HWDiskStore disk : diskStores) {
            List<HWPartition> partitions = disk.getPartitions();
            if (partitions == null) {
                continue;
            }
            //获取系统盘和云雀安装盘的磁盘信息
            for (HWPartition part : partitions) {
                System.out.println(part.getMountPoint())
            }
        }

**Comment by dbwiddis** [comment]
Which version of OSHI are you using?  

This could be the bug reported in #1244 and fixed in #1245 in versions 4.8.1 (for 4.X branch) and 5.1.1.

**Comment by dwj1979** [comment]
thank you for answer。
version: 5.1.0

**Comment by dbwiddis** [comment]
Upgrading to the latest version should solve the problem. :)

**Comment by dwj1979** [comment]
I have upgraded to the latest version, but the memery consumption has been increasing。

**Comment by dbwiddis** [comment]
It's normal for heap to increase with a high heap limit, as objects are created and destroyed, but garbage collection will kick in eventually.

**Comment by dwj1979** [comment]
i use the following code, jvm args:  -Xms200m -Xmx200m, although memery consumption has reached 600m, GC has not been recycled。 
public static void main(String[] args) {
        SystemInfo info = new SystemInfo();
        List<HWDiskStore> disks = info.getHardware().getDiskStores();
        while (true) {
            for (HWDiskStore disk : disks) {
                disk.updateAttributes();
            }
        }
    }

**Comment by dbwiddis** [comment]
The `-Xmx` value is just the heap memory. From [Oracle docs](https://docs.oracle.com/cd/E13150_01/jrockit_jvm/jrockit/geninfo/diagnos/garbage_collect.html):
> Java objects reside in an area called the heap. The heap is created when the JVM starts up and may increase or decrease in size while the application runs. When the heap becomes full, garbage is collected. During the garbage collection objects that are no longer used are cleared, thus making space for new objects.
>
> Note that the JVM uses more memory than just the heap. For example Java methods, thread stacks and native handles are allocated in memory separate from the heap, as well as JVM internal data structures.

600m total memory for a 200m heap limit seems reasonable.  [This SO post](https://stackoverflow.com/questions/14763079/what-are-the-xms-and-xmx-parameters-when-starting-jvm) indicates a 128m limit and 550m peak.

Are you still getting OutOfMemory errors?

**Comment by dwj1979** [comment]
but the memery consumption has been increasing。now has reached 1.2G

**Comment by dwj1979** [comment]
please try the code:

public static void main(String[] args) {
SystemInfo info = new SystemInfo();
List disks = info.getHardware().getDiskStores();
while (true) {
for (HWDiskStore disk : disks) {
disk.updateAttributes();
}
}
}

**Comment by dbwiddis** [comment]
Are you still getting OutOfMemory errors?

**Comment by dwj1979** [comment]
have not throw  OutOfMemoryErrors

**Comment by dwj1979** [comment]
but the memery consumption has been increasing。

**Comment by dbwiddis** [comment]
I can run that code with no problem. I use 2G heap and my memory peaks out at about 1.5 GiB.  How are you measuring memory usage?

**Comment by dwj1979** [comment]
using taskManager

**Comment by dbwiddis** [comment]
The JVM doesn't have a memory limit, and will use as much OS memory as is conveniently available for a variety of things to improve performance.  You're seeing JVM memory being used, not your heap memory which is limited by `Xmx`.

If you run your program long enough, you'll see it level out. If you start up another program that needs memory, you might see it decrease.

**Comment by dbwiddis** [comment]
See [this article](http://karunsubramanian.com/uncategorized/why-is-there-a-discrepancy-between-windows-task-manager-memory-and-java-heap/) for example.

**Comment by dwj1979** [comment]
thank you answer
