### ISSUE TITLE
Virtual memory percentages

### ISSUE THREAD

**Issue by rnaval** [oshi/oshi#1393]
Is it correct to derive virtual memory usage % based on the values from `getVirtualInUse()` and `getVirtualMax()`? i.e. something like:

```
virtual memory usage % = 100.0 * getVirtualInUse() / getVirtualMax()
```

Noticed that this sometimes gives values that are over 100% - is this related to the maximum value being a "soft-limit" as mentioned in the documentation? Is there a way to derive percentages correctly?

Thanks.

**Comment by dbwiddis** [comment]
This is a situation where it's platform dependent.  I tried to make it clear in the [`VirtualMemory`](https://oshi.github.io/oshi/apidocs/oshi/hardware/VirtualMemory.html) javadocs.  You might also find the discussion in #1182 useful.

For all OS's other than Windows and Linux, it's simple.  "Max" is the sum of physical and swap, and "in use" is the percentage of that total used (used physical + used swap).

Windows and Linux have different memory models, however:
 * Windows is very strict about allocating memory.  When a process requests memory it is immediately "assigned" to that process, even if it hasn't been used yet.  In this way, Windows always guarantees that memory will be available.  The terms [CommitCharge](https://en.wikipedia.org/wiki/Commit_charge) and CommitLimit apply here.  So virtual in use / virtual max would be the % of the total (physical+swap) which is assigned (committed) to programs, even if the programs aren't accessing that memory (it will not show as physical memory used, but will show up as "cached" in the Task manager).   And if Windows needs more memory, it will just expand the swap file, so it's not really a problem if it's close to 100%. 
 * Linux is different.  It may be configured with an overcommit ratio, allowing multiple processes to have the same (physical) memory assigned (committed) to them before expanding the swap file, essentially playing a game of probability on whether it can expand the swap file in time if multiple processes request the same memory that it has promised to both.  The same terminology of "Commit Limit" applies (the max committed before expanding the swap file) but here, the value "used" is actually the physical + swap used, so assuming "identical" programs it could give you a lower percent usage than Windows would.

Ultimiately, "Virtual in use" and "Virtual max" are a good ratio for all the *Nix systems in truly showing used/accessed, vs. physical+swap total, and excluding cached.   Windows includes cached in the "in use" value.

**Comment by dbwiddis** [comment]
I realize I may have overcomplicated the question.  More simply:

On Linux, it's possible with some overcommit settings for the "virtual max" to be lower than the sum of physical and swap memory.  In this case if you're running close to the limit you could have "in use" in excess of this number.  

My recommendation would be to separately use the physical "available" and "total" and swap "used" and "total" on all operating systems for consistent results. The other values are present to match up with operating system displays like task manager, but are misleading.
