### ISSUE TITLE
CPU ticks returned between ticks sometimes drop to 0 in a fairly busy system

### ISSUE THREAD

**Issue by rnaval** [oshi/oshi#1396]
It seems that computing the tick count in between intervals sometimes give us 0 for all Tick types.

Test environment is a CentOS 6 machine.

We currently use `getProcessorCpuLoadBetweenTicks` and `getSystemCpuLoadBetweenTicks` to get the CPU usage in a given interval.

To get this, we do the following:

1. For first sampling, get the tick counts via `getProcessorCpuLoadTicks` and `getSystemCpuLoadTicks`
2. Next sampling, pass the values in step 1 to `getProcessorCpuLoadBetweenTicks` and `getSystemCpuLoadBetweenTicks` and get the tick count for that interval (interval in this case is 10s)

As mentioned in the issue, we somehow get 0 for all of the tick types that we get, and misleadingly, set the CPU utilisation to 0 in this case.

Note that this is a fairly busy system, and it's really strange that we get 0 for all ticks when using those methods. Any ideas why this might be the case.

**Comment by dbwiddis** [comment]
It's hard to say without more debugging information. If this is a reproducible issue, printing out the value of the ticks (before/after) when this occurs would help debug.

**Comment by dbwiddis** [comment]
The ticks in Linux are pretty simple, reading `/proc/stat`.  It might return 0 if that attempt returns an invalid file in some way.

**Comment by rnaval** [comment]
Currently getting these - will keep you posted @dbwiddis

**Comment by dbwiddis** [comment]
Spent some more time looking in to this today.  There's really not much that would explain the symptoms of "all 0" other than temporary failures to read `/proc/stat`.   Generally, returning 0 and expecting the user to handle it is the default, except that the appropriate way to handle it is to re-try, and given the memoized return value, a retry wouldn't change for 300ms.

I'll look into doing a single automatic retry within OSHI's code.
