### ISSUE TITLE
getMaxFreq() seems to return an incorrectly converted value

### ISSUE THREAD

**Issue by rnaval** [oshi/oshi#1397]
`getMaxFreq()` seems to return a doubly converted value when there are no system-wide policies obtained.

Obtained frequency is converted here: https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java#L273

But the obtained frequency in /proc/cpuinfo is already being converted here: https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java#L240

So what we get in this case is:
Expected: 2400085000Hz 
Actual:      2400085000000Hz

Test environment is:
```
lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 44
Model name:            Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
Stepping:              2
CPU MHz:               2400.085
BogoMIPS:              4800.17
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              12288K
NUMA node0 CPU(s):     0,1
```

**Comment by dbwiddis** [comment]
OSHI parses the value in `/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq` (or `cpuinfo_cur_freq`).

Per [the documentation](https://www.kernel.org/doc/Documentation/cpu-freq/user-guide.txt) this value is in KHz.  What are those values on your system?

**Comment by dbwiddis** [comment]
Oh, wait, I see the issue; max initializes as the max current (already in Hz units) but the calculation to find the max assumes it's zero.
