### ISSUE TITLE
Could not get display on ubuntu 12.04

### ISSUE THREAD

**Issue by bibitoo** [oshi/oshi#1401]
I found run command "xrandr --verbose" on java runtime.exe with default env not response anything, like this:
`Runtime.getRuntime().exec("xrandr --verbose".split(" "), new String[] { "LC_ALL=C" });`
But when I run with null env, everything fine.
`Runtime.getRuntime().exec("xrandr --verbose".split(" "), null);`
When I add display env, It work too.
`Runtime.getRuntime().exec("xrandr --verbose".split(" "), new String[] { "LC_ALL=C", "DISPLAY=:0"  });`
Maybe add env parameter "DISPLAY=:0"  on ExecutingCommand.getDefaultEnv() should fix this.

**Comment by dbwiddis** [comment]
Thanks for the report!

We added the `LC_ALL=C` to be robust to international environments, so it is a surprise to me that it breaks this.

Do we have any documentation of why `xrandr` may require special treatment?

**Comment by bibitoo** [comment]
I think xrandr may require DISPLAY environment only. I did not search any document, just test it.
if I use DISPLAY enviroment only, I can get the right result.
`Runtime.getRuntime().exec("xrandr --verbose".split(" "), new String[] { "DISPLAY=:0" });`

**Comment by dbwiddis** [comment]
Does that limit the return to a single display, though?

What about using other switches on `xrandr` such as `--nograb` or `--screen 0`?

**Comment by dbwiddis** [comment]
If it works with the null environment I'm tempted to just go that route.  EDID is a standard acronym that likely won't change with localization.
