### ISSUE TITLE
Linux: OSFileStore.getUUID() returns empty string for logical volumes

### ISSUE THREAD

**Issue by kmagsuciitrs** [oshi/oshi#1404]
I am running Centos 8 with xfs logical volumes. I observed that `OSFileStore.getUUID()` returns an empty string for logical volumes.

OSFileStore.toString() logs:

OSFileStore [name=/dev/mapper/cl-home, volume=**/dev/mapper/cl-home**, label=/dev/mapper/cl-home, logicalVolume=/dev/dm-2, mount=/home, description=Local Disk, fsType=xfs, options="rw,seclabel,relatime,attr2,inode64,noquota", _**uuid=**_, freeSpace=23570378752, usableSpace=23570378752, totalSpace=25036152832, freeInodes=12221161, totalInodes=12230656]

OSFileStore [name=/, volume=**/dev/mapper/cl-root**, label=/, logicalVolume=/dev/dm-0, mount=/, description=Local Disk, fsType=xfs, options="rw,seclabel,relatime,attr2,inode64,noquota", _**uuid=**_, freeSpace=43595587584, usableSpace=43595587584, totalSpace=51275485184, freeInodes=24903194, totalInodes=25049088]

I was expecting the UUIDs displayed by `blkid` to be returned by `getUUID()` as well:
[user@localhost collection_agent]$ sudo blkid
/dev/sda1: UUID="d854c229-a879-4d54-a13f-eaf5691365ee" TYPE="ext4" PARTUUID="fca292db-01"
/dev/sda2: UUID="3Lseo1-axnA-vW38-xPYx-xEWa-m84g-NFoOgi" TYPE="LVM2_member" PARTUUID="fca292db-02"
**/dev/mapper/cl-root**: UUID="_**76ff6525-4041-4bd3-8df4-42d1a4bcb62b**_" TYPE="xfs"
/dev/mapper/cl-swap: UUID="e9ae5882-7cd2-4380-b8ae-38b263e8cc16" TYPE="swap"
**/dev/mapper/cl-home**: UUID="_**8de6b57c-5fd5-47a0-b64a-afa7b2590c2f**_" TYPE="xfs"

When trying to the resolve the uuid in https://github.com/oshi/oshi/blob/f79bcd7f72a688da67b6c985d102f32c07ff166b/oshi-core/src/main/java/oshi/software/os/linux/LinuxFileSystem.java#L134 it seems the uuids are mapped to the logical devices, ex. /dev/dm-0, /dev/dm-2, but no mapping has yet been established with the volumes, ex. dev/mapper/cl-root, dev/mapper/cl-home, so the uuids are not matched to the volumes. I am not sure though if this behavior is as intended.

**Comment by dbwiddis** [comment]
Thanks for the report.

OSHI's logical volume support is still lacking in a few details, as you can see.  I'd appreciate a PR to fix this!

**Comment by dbwiddis** [comment]
@tausiflife is this something you think you can look into?

**Comment by tausiflife** [comment]
yes sure. I will have a look.
