### ISSUE TITLE
/proc/cpuinfo on Orange Pi

### ISSUE THREAD

**Issue by MarkJeronimus** [oshi/oshi#1406]
On my Orange Pi One, running Armbian, the contents of `/proc/cpuinfo` is:

```
Processor	: ARMv7 Processor rev 5 (v7l)
processor	: 0
...
```
(https://pastebin.com/FNJqgy29)

The CPU info is not listed after the column `model name` but after the column `Processor` (with a capital P). As far as I can see, only one of either will be present, but not both.

Extra information:
```
$ uname -a
Linux orangepione 3.4.113-sun8i #2 SMP PREEMPT Wed May 8 15:09:43 CEST 2019 armv7l armv7l armv7l GNU/Linux
```

**Comment by dbwiddis** [comment]
Yay for standards.
