### ISSUE TITLE
CPU Load vs Winidows Tasks

### ISSUE THREAD

**Issue by aldrato** [oshi/oshi#1407]
Hello, initially congratulations on the project, it is fantastic!
I would like to ask a question, I am making a program to monitor the machine, and I used the same code as the oshi-demo to obtain the CPU load, but I realized that the value of the total CPU load is different from what is shown in the Windows tasks.
Is this correct or is there really a difference?

**Comment by dbwiddis** [comment]
For *nix systems, usage is referenced to the work done by a single processor, so it is possible for CPU load to exceed 100% in a multi-core system.  A single thread maxing out CPU will give near 100% usage, and any other work done by other threads/processors will exceed that.

Windows references CPU usage to the entire system by dividing by the total number of logical processors, so it's not possible (using default settings) to exceed 100%.  Maxing out a single thread in a system with 4 logical processors will show 25% CPU usage.

The GUI in `oshi-demo`  does have a selection option to "divide by number of logical processors" which is selected by default on windows, and not on other systems.
