### ISSUE TITLE
Return device/filesystem label on linux

### ISSUE THREAD

**Issue by thomaskoren** [oshi/oshi#1408]
`OSFileStore.getName()` and `getLabel()` return same value on Linux (Ubuntu 20.10), which is incorrect.

The reason for this behavior is given in javadoc of `getLabel()`: "The volume label of the file system, on Windows. Other operating systems is redundant with the name." But this assumption is wrong.

e.g. an exFAT file system on an USB drive mounted on linux typically has a `name` like `dev/sda1`. This is equivalent to/redundant with `volume`.

But `label`might be something like "My Thumbdrive" and should be returned by `getLabel()`.

**Comment by dbwiddis** [comment]
Where is that label programmatically on linux?

**Comment by thomaskoren** [comment]
If you mean in oshi: That information is not available in `OSFileStore` or `HWPartition` as far as I could see.

If you mean in linux generally: One way to get the label could be
`sudo lsblk -o name,mountpoint,label,uuid`

I have no "vanilla java" solution and was hoping for oshi to have something.

**Comment by dbwiddis** [comment]
Yes, I meant in Linux.  For performance reasons, we try to avoid command line calls when possible, particularly if they require sudo.  Currently we get all the other Linux filesystem info from `/proc/mount`.

The `lsblk` command is associated with the hardware device (`HWDiskStore`) and looking into that command's source code, it looks like there can sometimes be a `LABEL` property that can be fetched from Udev.  So it seems reasonable to add such a field to the `HWDiskStore`.

However, I'm trying to re-think the entire way we try to bridge disk stores, file systems, and logical volumes, so I'm not eager to add this to the API just yet.  If someone really wants it earlier, I'll accept a PR.

**Comment by thomaskoren** [comment]
Thanks for your response. Totally understand your tendency to avoid cli calls.

Jjust for future reference: yes, `udev` is a non-sudo alternative:
e.g. `ls -l /dev/disk/by-label`

**Comment by dbwiddis** [comment]
So I spent some time looking into this. I think there's definitely room to add a "label" at the hardware (device) level, using `udev` as the source for Linux.  Not sure if that's the disk store or partition or both, but it might be useful to add.  I'll do a bit more looking around at whether other OS's have similar fields we can use.

**Comment by dbwiddis** [comment]
Seems this is easily solved at the filesystem level: `mount -l` appends the label (if assigned using `e2label` to the end of the output.  I'll add this to the parsing.  This may differ from the (HWDiskStore) block-level label in `lsblk`.
