### ISSUE TITLE
how to get directory used size?

### ISSUE THREAD

**Issue by XinSuiNian** [oshi/oshi#1415]
If i want to get directory used size, What should I do ?
Such as  directory is  '/opt/data ' (linux) or 'C:\data' (windows) . What should I do? Does oshi support ?

**Comment by dbwiddis** [comment]
OSHI does not provide statistics at that level of detail, as they are easily available in core Java.  

OSHI can give you stats for a filesystem, so if you chose to mount `C:\data` as a `Z:\` drive, or add `/opt/data` to your linux `mount` list, you'd probably get that information.

OSHI's `Util` package does include an `ExecutingCommand` class that you could pass an appropriate command to (e.g.,  `ExecutingCommand.runNative("du -sh /opt/data");` for *nix systems, but there is no equivalent for Windows.

Your best cross-platform bet is probably just to write your own core Java method that uses `listFiles()` on the directory, summing up the `length()` of the iterated files.  [Here is an example.](https://www.baeldung.com/java-folder-size)
