### ISSUE TITLE
Find out which thread is running on which CPU

### ISSUE THREAD

**Issue by stefan-reich** [oshi/oshi#1416]
I'd like this

**Comment by dbwiddis** [comment]
I'm tempted to simply answer "why?"

Some challenges:
 - In general, a thread may run on any processor in the affinity mask of its owning process.  OSHI does provide [process-level affinity](https://oshi.github.io/oshi/apidocs/oshi/software/os/OSProcess.html#getAffinityMask()). 
 - Threads can (and do, often, with context switches) move around to different CPUs. Even if I told you that thread 123 was running on processor 1 when you queried the data, it might be running on processor 0 by the time you have a chance to even process the earlier result.
 - In Linux, the value is available from `/proc/<pid>/task/<tid>/stat` or by parsing the PSR column in the output of `ps -mo pid,tid,psr -p <pid>` but is only valid if the thread is currently running (if it's sleeping, the value is invalid; it's not running on any cpu. The number shows where it last ran, which may not be where it will run when it wakes up).  This doesn't work with other *nix platforms, though.
 - The Windows API doesn't provide that information for other than the current thread.  A thread does have a [ProcessThread.ProcessorAffinity](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processthread.processoraffinity?view=net-5.0) mask limiting the processors on which it can run, but it only has a setter. You can not "get" that mask.  
   - You can set a thread to run on a particular processor (or "prefer" a processor) but you won't know if it actually is doing so, unless you are inside the thread itself and call [GetCurrentProcessorNumber](url)([Ex](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getcurrentprocessornumberex)).
   - You can get the "Ideal" processor for a thread with [GetThreaIdealProcessorEx](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getthreadidealprocessorex), but it's not a guarantee.
 - macOS [thread policy is (still) experimental](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Multithreading/CreatingThreads/CreatingThreads.html). Apple believes they know better than users how to schedule threads and provide very little information.
 - AIX, Solaris, and FreeBSD have ways to see the thread affinity settings, but not the individual processor.

In sum, the information you seek is Linux-only, is only valid for running threads, and changes often enough that in the overwhelming majority of cases, the information is irrelevant or possibly even wrong.

In the corner case where you actually do have a thread you want to monitor on Linux, this info is easily accessible by reading a file or executing a command line, for which utilities are available in the `FileUtil` and `ExecutingCommand` classes to parse that information.   Or, you can use one of many excellent profiling/debugging utilities specific to an operating system and able to access much lower level hardware calls like CPUID, which can do a proper job of it.

**Comment by stefan-reich** [comment]
Hi Dan, thanks a lot for your very detailed answer. I see it's difficult, and it's not totally important. Just my natural curiosity to look at the bare metal in a way. I do think threads hop around between cores usually so yeah maybe this information is not that useful. Thanks again.

**Comment by dbwiddis** [comment]
It is an interesting question and would be fun to monitor a Linux system for a few hours to just see how often threads switch CPUs.  I suspect, however, that for an external monitoring system, "sleeping" threads are going to be all too common.  Adding instrumentation to nearly every routine to report its current thread info to a log file somewhere might be more accurate!
