### ISSUE TITLE
Mac os cannot get hard drive information

### ISSUE THREAD

**Issue by cnwayne88** [oshi/oshi#1417]
getFileSystem().getFileStores() error

**Comment by dbwiddis** [comment]
You need to provide a lot more details for anyone to be able to even suggest how to troubleshoot this.

**Comment by dbwiddis** [comment]
I'm closing this issue as there are no details and there's nothing I can do to help. If you are still having problems, feel free to comment here with details such as error message, stack trace, symptoms, or any information at all besides that you have an error.
