### ISSUE TITLE
Give the user the ability to control COM initialization

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1418]
While still negligible on a per-call basis, COM overhead is still one of the largest performance impacts on Windows.

Earlier versions of OSHI initialized COM once and tried to uninitialize with a shutdown hook.  This design patttern was removed to make all com calls thread safe.  However, that's still a lot of unneeded and repetitive code *if* the user wants to take control of handling it.

The user should be able to initialize and uninitialize COM themselves, and that state should be checked by the code to avoid redundant initialization/uninitialization.  This will not be thread-safe, but as an opt-in, users can handle that themselves.

**Comment by dblock** [comment]
If you `CoInitialize` once in an app, subsequent calls should be mostly noop. Is that the case?

**Comment by dbwiddis** [comment]
It may be a noop in multithreaded mode but each thread calling in apartment threaded mode would have some resources to identify that apartment.  Haven't really looked into what's actually happening, but the docs are clear.

Subsequent calls if COM is already initialized return S_FALSE and [the docs]((https://docs.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-coinitializeex)) say explicitly those must be balanced:
> Multiple calls to CoInitializeEx by the same thread are allowed as long as they pass the same concurrency flag, but subsequent valid calls return S_FALSE. To close the COM library gracefully on a thread, each successful call to CoInitialize or CoInitializeEx, including any call that returns S_FALSE, must be balanced by a corresponding call to CoUninitialize.

And also [here](https://docs.microsoft.com/en-us/windows/win32/api/objbase/nf-objbase-coinitialize):
> To close the COM library gracefully, each successful call to CoInitialize or CoInitializeEx, including those that return S_FALSE, must be balanced by a corresponding call to CoUninitialize. However, the first thread in the application that calls CoInitialize with 0 (or CoInitializeEx with COINIT_APARTMENTTHREADED) must be the last thread to call CoUninitialize. Otherwise, subsequent calls to CoInitialize on the STA will fail and the application will not work.

Ideally, OSHI would initialize COM once, do everything it needs to, and uninitialize when done.  That was the original implementation involving a shutdown hook, but those might not execute if the process is killed or crashes.  The intent of this Issue is to give the user that explicit control in their application.

**Comment by dblock** [comment]
My general recommendation from past life is for a library to never initializes COM and leave this to the caller application because the threading model is, for one, the choice of the application. Not sure how that makes sense or manifests itself in a hybrid Java/COM app though.

**Comment by dbwiddis** [comment]
Agreed, and that (leaving initialization and threading model choice) is what I want to enable.  

Technically thread model choice is something the calling app can enforce by initializing first, as OSHI will do the "second" initialization using the same model.  But if the calling app has already initialized there's no need for OSHI to initialize.  What I'm basically wanting to enable is the calling app's ability to tell OSHI "I'm handling COM so you don't have to."

As for hybrid Java/COM, [the JVM](https://github.com/openjdk/jdk/blob/6bab0f539fba8fb441697846347597b4a0ade428/src/java.desktop/windows/native/libawt/java2d/d3d/D3DPipelineManager.cpp#L947) does [COM initialization](https://github.com/openjdk/jdk/blob/26a7b0dddd562ba4b45b6a504f020e54606bcc44/src/java.desktop/windows/native/libjsound/PLATFORM_API_WinOS_DirectSound.cpp#L480) in [a few places](https://github.com/openjdk/jdk/blob/c6543f1a2a41fb33f51ec98df886193580777f1f/src/java.desktop/windows/native/libawt/windows/ShellFolder2.cpp#L297) so it's not wrong to do what we currently do (initialize briefly and then uninit).  It's just not needed if we can rely on the user to have initialized (and knows they shouldn't uninitialize until done).

As far as actually coding it up, it actually is already enabled and just requires the user to extend the class.  The [`WmiQueryHandler`](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/util/platform/windows/WmiQueryHandler.java) is designed to permit subclassing.  A user could simply override the `queryWmi()` method to remove the COM initialization from it, and then use the (public) initialize and uninitialize methods separately.  So this issue may just be a contribution to `oshi-demo` demonstrating how to do it.

**Comment by dbwiddis** [comment]
That moment when you spend 3 hours debugging and eventually realize [you've hit a JDK bug](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8233837).

Also:
```
Collecting statistics with default COM setup
Average ms per rep: 10.614741
Collecting statistics with user-init COM setup
Average ms per rep: 6.561526
```
