### ISSUE TITLE
can't get the value of part.getMountPoint() in linux

### ISSUE THREAD

**Issue by dwj1979** [oshi/oshi#1420]
hello, 
i can get the value of **part.getMountPoint()** in windows, but can't get the value in linux.

sample code as following:

        List<HWDiskStore> diskStores = hal.getDiskStores();
        for (HWDiskStore disk : diskStores) {
            List<HWPartition> partitions = disk.getPartitions();
            if (partitions == null) {
                continue;
            }

            for (HWPartition part : partitions) {
                System.out.println(part.getMountPoint());
            }
       }

**Comment by dbwiddis** [comment]
Linux gets partition mount points from `/proc/mounts`. What is the contents of that pseudo-file?

**Comment by dbwiddis** [comment]
@dwj1979 are you still having this problem? I can't help any more without you providing the `/proc/mounts` output for your system.

**Comment by dbwiddis** [comment]
I'm closing this issue as you haven't followed up with any information I can use to help, so I am assuming you figured out the problem and this is resolved. Feel free to comment here with the requested information and I'll reopen it if you still need help.
