### ISSUE TITLE
Changes between versions

### ISSUE THREAD

**Issue by SimunKaracic** [oshi/oshi#1421]
I was wondering how I can keep track of what changed when bumping version of oshi.

Do you have something like release notes, or should I read the commits?

**Comment by hazendaz** [comment]
https://github.com/oshi/oshi/blob/master/CHANGELOG.md

**Comment by hazendaz** [comment]
@dbwiddis It may be useful to also add the change notes to the releases in github for clarity there or at very least just link them back to the changelog.

**Comment by SimunKaracic** [comment]
Any of those two options would be great! 

Thanks for the link @hazendaz

**Comment by dbwiddis** [comment]
Between the CHANGELOG linked above and the UPGRADING document for major version bumps, I thought it was pretty well documented already.    But linking from the on-site release should be pretty easy to accomplish.

**Comment by dbwiddis** [comment]
I've gone through and updated everything 4.X and newer and consider that good enough.
