### ISSUE TITLE
Migrate appvoyer/travisci to github actions

### ISSUE THREAD

**Issue by hazendaz** [oshi/oshi#1423]
Integrated github actions is mature enough at this point that we should actively look at migration.  This is more important due to lack of stability around travis and cost structure changes there recently.  I can pick this up as I have been porting others over last week or so and its a rather clean and general easier to understand setup but certainly welcome any help and the old systems don't need remove right away :)

**Comment by dbwiddis** [comment]
No overall objection here, but I'd like a bit more detail on Github actions.   Is its platform coverage better (I think it is?). Does it integrate with the static analyzers we use (I'm thinking Coverity and Sonar)?

What are the travis stability issues?    I do know they're changing cost structure for paid projects (travis.com) and presume they're getting first crack at the servers, which appear to be quota limited for the free (travis.org) projects.  It's an impact during weekday daytime, but isn't a problem at all on the weekends or late nights on the west coast.   I also participate in other open source projects which have been invited to switch to travis.com (still for free) so I assume this is all just a temporary transition headache.

Would love to get an initial setup done, and reduce the number of travis jobs.   Let me know how I can hep.

**Comment by dbwiddis** [comment]
Also while you're setting up, something to think about.  I'd like to eventually have an artifact (`oshi-jpms`) that requires JDK9+ to build (probably will target 11) that will build a modular version of oshi.  Tests on JDK 8 need to be able to skip that module while tests on JDK 11 should include it.  Hopefully that's enabled. :)

**Comment by hazendaz** [comment]
@dbwiddis I'm migrating over 'waffle' now.  Its mostly done.  You can see the results [here](https://github.com/Waffle/waffle/actions) and see the setup [here](https://github.com/Waffle/waffle/tree/master/.github/workflows).  Sonar and coverity addressed at this point.  Coverity was a bit painful but now it's copy past.

I'm sure I'm hitting travis issues more frequently than most developers might as most of my work has been around the CI setup across many repos.  It rarely runs IMO at this point and indications throughout there blog kind of indicates they plan to charge for open source at some point.  Not sure of all the details but after nearly all year waiting for what seems forever for builds to even run and way too many strange failures, I've gave up hope before even reading that.

With github, its built in, so it makes sense just to do it here.  For what I've learned thus far, there are quite a few more systems available.  Now that may still be limited to linux, mac, and windows.  But that was more than I had setup on most projects and at least for waffle solves some major issues as appvoyer wasn't ever that good (probalby an opinion as it was discovered years without running with no indication as to why).

Anyway, this seems much smoother than expected and its super clear to separate out files and have specific things run in a much more managed way with ease.  My day job actually centers soley around getting this kind of stuff going and this simply is a lot more evolved than what I have in my day job which is years in and huge support level so that is just another 'great job github' 👍 I've seem a few little annoying issues but sort of expected that and think its been long enough wait for this to mature :)

**Comment by dbwiddis** [comment]
Well, good to see my employer is doing something right! Now if only they let us use github instead of Azure DevOps, life would be sweet! ;)

**Comment by hazendaz** [comment]
@dbwiddis Looks like I don't have ability to release to sonatype for oshi.  I thought I had that before but might have been just under dblock.  I did find this. https://issues.sonatype.org/browse/OSSRH-28459.  It looks like it was requested but possibly missed as comments only indicate you were setup.

**Comment by hazendaz** [comment]
I added a note on there to add myself and dblock.  This is important only in how I'm setting up github actions and automating push of snapshots to here https://oss.sonatype.org/content/repositories/snapshots/com/github/oshi.

**Comment by hazendaz** [comment]
I created a new ticket out there as I'm not sure how they pick that up these days.  They used to accept a ticket getting a comment onto it to look at but just in case.  New ticket https://issues.sonatype.org/browse/OSSRH-62325.

**Comment by dbwiddis** [comment]
Let me know when you're at a point where you want to try to release with the new system (and document it!).  I can probably knock out a few bugfix issues for a patch release.

**Comment by dbwiddis** [comment]
OK, I took your fantastic start and tweaked a few things tonight.  I'm pretty happy with where it is mostly.
 - Full 4 x 3 matrix on pushes to master (which includes merged PRs). By limiting branch to master, will reduce impact on users with feature branches intended for PRs.
 - Abbreviated 1 x 3 matrix (all os on JDK8) on pull requests (any branch).
 - Added the all-important status badge to the readme because badges! (gotta catch 'em all)
 - Deleted the old (Attic) sonar project after synchronizing "wontfix" issues.
 - Reduced the travis-CI matrix to one run on each OS, plus an extra one on Linux ARM.  Idea here is that different hardware/containers from different CI providers can help identify unique issues.
 - Left the appveyor setup alone. Could delete, but I'd still want a single test but I'd still one one for unique hardware as referenced above, and this is rarely a limiting factor on tests.

Current things still to-do:
 - Sonatype (ossrh snapshot) deploy still doesn't work. I tried putting my own credentials (that I use for snapshot deployments from my local machine) into Github but they didn't help.  I'll leave this to you to keep playing with.
 - Would be nice to figure out coverity on new workflows, but I'm content with the existing setup leveraging travis.

**Comment by dbwiddis** [comment]
Hmm. It appears both travis and appveyor are executing twice now. That's odd. Not sure why.

**Comment by dbwiddis** [comment]
Ok, I think this is all set.  Sonatype seems to be pushing snapshots on every push, and coverity is working via workflow from master on cron (or by demand), with the travis branch deleted.

Travis and Appveyor are now both redundant, keeping them around as extra platform tests while free, but they're ok to delete if either becomes too problematic.
