### ISSUE TITLE
Network MTU returned as -1 when a loopback interface has the maximum value 

### ISSUE THREAD

**Issue by mfujitaitrs** [oshi/oshi#1424]
On a Windows environment:

Software Loopback Interface's network MTU is currently reported as -1 which corresponds to unknown or unavailable.  
However, upon comparing against _Get-NetIPInterface_ and _netsh interface ipv4 show interface_, loopback's value for MTU is 4294967295. 

```
Get-NetIPInterface:

ifIndex InterfaceAlias                  AddressFamily NlMtu(Bytes) InterfaceMetric Dhcp     ConnectionState PolicyStore
------- --------------                  ------------- ------------ --------------- ----     --------------- -----------
1       Loopback Pseudo-Interface 1     IPv6            4294967295              75 Disabled Connected       ActiveStore
1       Loopback Pseudo-Interface 1     IPv4            4294967295              75 Disabled Connected       ActiveStore

netsh interface ipv4 show interface:

Idx     Met         MTU          State                Name
---  ----------  ----------  ------------  ---------------------------
  1          75  4294967295  connected     Loopback Pseudo-Interface 1
```
As seen [on this reference](https://social.technet.microsoft.com/Forums/office/en-US/eb1c8794-c5e5-4ee1-9b0d-298d10890e5d/what-is-the-mtu-size-of-loopback?forum=winservergen), it translates to 0xFFFFFFFF, the maximum possible value for an MTU. 
Given that Oshi returns -1, is there are way to distinguish if the loopback has an unknown MTU or has the max value?

**Comment by dbwiddis** [comment]
The MTU is a carry-through from the JDK's `NetworkInterface` class, in which [`getMTU()`](https://docs.oracle.com/javase/8/docs/api/java/net/NetworkInterface.html#getMTU--) returns an `int`, which are always signed in Java.  This value is apparently unsigned 32-bit values at the native level (the JDK derives the value from the 32-bit `dwMtu` field in the [`MIB_IFROW`](https://docs.microsoft.com/en-us/windows/win32/api/ifmib/ns-ifmib-mib_ifrow) structure for that interface).

So -1 does not represent an error here; it faithfully reports the JDK's value, which is either correct or throws a SocketException, and reasonable to convert to a `long` using `mtu & 0xffff_ffffL` (OSHI provides `ParseUtil.unsignedIntToLong()` that does this, and this is probably the best way to handle it at the user level right now.

Alternately, you might consider that MTU is meaningless for local interfaces, and ignore the numeric value (which is essentially "infinite" for practical purposes).

Newer Windows versions (Vista+) use `MIB_IFROW2` which has a 64-bit value and may correctly return the max unsigned int value inside that ULONG (or might return max unsigned long; I haven't checked).  We could use OSHI to read that and overwrite the current value, but we're still stuck in the situation of having a 32-bit unsigned value that Java doesn't handle.

A good long term solution would be to change OSHI's MTU to `long` type.  However, that would be an API breaking change so will have to wait for the next major version bump.  

I think the best thing to do at this point is to update the javadoc to highlight the unsigned nature of the `int`, and change the `toString()` to use the conversion mentioned above, and add this variable to process ID to be upgraded to `long` with the next major version bump.
