### ISSUE TITLE
getCodeName returning null for macOS 11.1 and 11.2

### ISSUE THREAD

**Issue by jimbostimilon** [oshi/oshi#1456]
Using OSHI 5.3.6, when I call getCodeName on macOS 11.1 or 11.2, it returns `null`.

I think this is because macOS is no longer using minor version numbers for new releases e.g. 10.14 Mojave/10.15 Catalina.

11.0 is Big Sur, but so is 11.1 and 11.2.

**Comment by dbwiddis** [comment]
Indeed, that's the case.  I should have noted that when I did my 11.1 upgrade earlier this week.  Is 11.2 out already? That was fast.

This can be immediately worked around by [updating the config file](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/resources/oshi.macos.versions.properties#L26) to manually assign 11.1 and 11.2 the same code name.

Long term fix is to alter `parseCodeName()` in `MacOperatingSystem` to account for this new scheme.

**Comment by jimbostimilon** [comment]
11.2 is the current developer beta version.

**Comment by dbwiddis** [comment]
[So I see.](https://en.wikipedia.org/wiki/MacOS_Big_Sur#Release_history)

**Comment by dbwiddis** [comment]
```
Apple macOS 11.1 (Big Sur) build 20C69
Booted: 2020-12-15T15:55:43Z
Uptime: 2 days, 11:16:45
```
