### ISSUE TITLE
Command lines are limited to the executable when getting via `getCommandLine`

### ISSUE THREAD

**Issue by rnaval** [oshi/oshi#1459]
Noticed that the command lines obtained via `getCommandLine` are limited to only the executable.

For example, in a java process, we only have `/usr/lib/jvm/jre-1.8.0/bin/java` - we seem to be missing the jar or classpaths.

Is this expected?

**Comment by dbwiddis** [comment]
In general, the full command line is expected, but the format returned by `getCommandLine()` is platform dependent.  [From the javadocs](https://oshi.github.io/oshi/apidocs/oshi/software/os/OSProcess.html#getCommandLine()):
> The format of this string is platform-dependent and may require the end user to parse the result.
On Linux and macOS systems, the string is null-character-delimited, to permit the end user to parse the executable and arguments if desired. Further, the macOS variant may include environment variables which the end user may wish to exclude from display.
>
> On Solaris, the string is truncated to 80 characters.

Which operating system are you using? Based on your other issue, it seems to be Linux (CentOS) so you may not be handling the embedded null characters.

**Comment by dbwiddis** [comment]
I've verified the code is pulling the path directly from `/proc/[pid]/cmdline` on Linux, which I'll assume you're using based on the file path.  As mentioned, that's a null-delimited string.  I'll close this issue, feel free to follow up if you still are having issues.
