### ISSUE TITLE
Oshi core 5.4.1 not working on Apple M1

### ISSUE THREAD

**Issue by occhioni-esteco** [oshi/oshi#1508]
Hi, 
today i tried to switch from Oshi core 5.4.0 to 5.4.1 and i noticed a lot of exceptions while running the library. 

`java.lang.NullPointerException
         at oshi.hardware.platform.mac.MacCentralProcessor.appleArmCpu(MacCentralProcessor.java:257)
	at oshi.util.Memoizer$1.get(Memoizer.java:87)
	at oshi.hardware.platform.mac.MacCentralProcessor.queryProcessorId(MacCentralProcessor.java:90)
	at oshi.util.Memoizer$1.get(Memoizer.java:87)
	at oshi.hardware.common.AbstractCentralProcessor.getProcessorIdentifier(AbstractCentralProcessor.java:104)`

Seems that the method
`cpu.getParentEntry("IODeviceTree")`
returns a null object. 

I reverted back Oshi to 5.4.0 and everything works fine. 

HW and SW specs to help for the throubleshooting: 
Java JDK AdoptOpenJdk 11.0.9+11
Jna 5.6.0
MBP 13,3" 
macOS BigSur 11.1 
Apple M1 chip

**Comment by dbwiddis** [comment]
It's the continuing saga of #1483.  I did already find and fix the null derefrence in c300490d114f903fa9e31f21f8041a6fefa1d744, so snapshot should "work" for you, where "work" means doesn't crash.

Hunting down the right combination to find the clues to the processor architecture in the registry while under Rosetta is proving to be a challenge...

**Comment by dbwiddis** [comment]
Can you please check whether #1509 solves this?  I've also pushed it to SNAPSHOT.   Looking for the CPU Identification info (family, architecture).

**Comment by occhioni-esteco** [comment]
Tried with 5.4.2-SNAPSHOT (Build-Time: 2021-01-26 17:00:12) works fine! Thanks

**Comment by dbwiddis** [comment]
Can you tell me what you see for the architecture and the processor ID fields? :)

**Comment by occhioni-esteco** [comment]
Fields from CentralProcessorIdentifier
- CpuFamily: 0x1b588bb3
- processorID: 0100000c1b588bb3
- microArchitecture: ARM64 SoC: Firestorm + Icestorm

**Comment by dbwiddis** [comment]
Fantastic, thanks!
