### ISSUE TITLE
Filtering the Process list by name or group (or anything)

### ISSUE THREAD

**Issue by rnaval** [oshi/oshi#1514]
Hello,

Is there currently a way to filter what processes to query in terms of the process name or the process group or something?

Based on the oshi documentation, we can only use:
- [getProcesses()](https://oshi.github.io/oshi/apidocs/oshi/software/os/OperatingSystem.html#getProcesses()) - get all of the processes
- [getProcesses​(int limit, OperatingSystem.ProcessSort sort)](https://oshi.github.io/oshi/apidocs/oshi/software/os/OperatingSystem.html#getProcesses(int,oshi.software.os.OperatingSystem.ProcessSort)) - get X processes sorted using criteria ProcessSort
- [getProcesses​(java.util.Collection<java.lang.Integer> pids)](https://oshi.github.io/oshi/apidocs/oshi/software/os/OperatingSystem.html#getProcesses(java.util.Collection)) - get processes based on the supplied pids.

The current use case is that a user wants to monitor a specific set of processes only. The first API returns too much information (especially for busy systems), and the second and third ones cannot be used for that use case.

Thanks!

**Comment by dbwiddis** [comment]
There is [getChildProcesses()](https://oshi.github.io/oshi/apidocs/oshi/software/os/OperatingSystem.html#getChildProcesses(int,int,oshi.software.os.OperatingSystem.ProcessSort)) which returns children of a particular process.   Beyond that, you generally need to query the whole list and iterate it, filtering on the criteria of your choice.

**Comment by dbwiddis** [comment]
Thinking about this, I think there's an opportunity to improve the API.  

Currently the sorting is simply controlled by an enum to pre-populated `Comparator<OSProcess>` values, but there's no reason we couldn't have an overloaded getter that takes that `Comparator` as an argument (or `null` to remain unsorted).  Similarly, we could have a `Predicate<OSProcess>` argument permitting the user to define a filtering criteria (with `null` meaning no filtering).

I don't think there will be that much performance difference from taking the existing list and tossing it into a `stream()` with the same `Comparator` and/or `Predicate` but it would be a nice addition.

**Comment by dbwiddis** [comment]
@rnaval can you please take a look at the implementation in #1526 and see if it works for your use case?

I've deprecated `getProcesses​(int limit, OperatingSystem.ProcessSort sort)` and now have `getProcesses(Predicate<OSProcess> filter, Comparator<OSProcess> sort, int limit)`.

So to search by process name, you could do, for example:
```
Predicate<OSProcess> chromeProcessFilter = p -> p.getName().equalsIgnoreCase("Chrome");
OperatingSystem os = new SystemInfo().getOperatingSystem();
List<OSProcess> chromeProcList = os.getProcesses(chromeProcessFilter, ProcessSorting.CPU_DESC, 0);
```
