### ISSUE TITLE
How to obtain graphics card information？

### ISSUE THREAD

**Issue by shenmeiqian** [oshi/oshi#1515]
I don't know。

**Comment by dbwiddis** [comment]
Your question is incredibly vague.   What specifically do you need?

**Comment by dbwiddis** [comment]
As specified in the [Usage section of the README](https://github.com/oshi/oshi#usage), and [also referenced in the FAQ](https://github.com/oshi/oshi/blob/master/FAQ.md#what-is-the-intended-use-of-the-api):
> Create a new instance of SystemInfo

and
> Use the getters from SystemInfo to access hardware or operating system components

For graphics cards:
```
SystemInfo si = new SystemInfo();
HardwareAbstractionLayer hal = si.getHardware();
List<GraphicsCard> cards = hal.getGraphicsCards();
```
