### ISSUE TITLE
Memory values do not match the ones in "top" on linux

### ISSUE THREAD

**Issue by LukasHanusek** [oshi/oshi#1516]
Using Debian 10, Java 8, OSHI seems to be outputing very strange memory usage per process.

While top shows 473m:
![image](https://user-images.githubusercontent.com/48738910/106936547-045f5080-671d-11eb-89ed-d0d52edd96e9.png)

OSHI is outputting 392m:
`os.getProcess(pid).getResidentSetSize() /1024L /1024L;`

EDIT:
I tried to increase the load of the tested application, and the total memory usage went up to 562m, while OSHI value went even lower, now OSHI outputs 389m
![image](https://user-images.githubusercontent.com/48738910/106938305-18a44d00-671f-11eb-825a-20a102e6fe92.png)

On Windows 10 I was getting much more accurate results. Is there any way how to get values as close as possible to those shown by the top command ? Thanks.

**Comment by dbwiddis** [comment]
OSHI gets its Linux values for Process RSS directly from [`/proc/[pid]/stat`](https://man7.org/linux/man-pages/man5/proc.5.html).  

However, from the man page:
```
              (24) rss  %ld
                     Resident Set Size: number of pages the process has
                     in real memory.  This is just the pages which count
                     toward text, data, or stack space.  This does not
                     include pages which have not been demand-loaded in,
                     or which are swapped out.  This value is
                     inaccurate; see /proc/[pid]/statm below.
```
which in turn says:
```
       /proc/[pid]/statm
              Provides information about memory usage, measured in
              pages.  The columns are:

                  size       (1) total program size
                             (same as VmSize in /proc/[pid]/status)
                  resident   (2) resident set size
                             (inaccurate; same as VmRSS in /proc/[pid]/status)
```
Which leads to:
```
       /proc/[pid]/status
              Provides much of the information in /proc/[pid]/stat and
              /proc/[pid]/statm in a format that's easier for humans to
              parse.  Here's an example:

                  $ cat /proc/$$/status
                  Name:   bash
                  Umask:  0022
                  State:  S (sleeping)
<snip>
                  VmRSS:       13484 kB
```
but the entry for VmRSS refers back to `statm`:
```
              VmRSS  Resident set size.  Note that the value here is the
                     sum of RssAnon, RssFile, and RssShmem.  This value
                     is inaccurate; see /proc/[pid]/statm above.
```
So to execute this endless loop we see:
```
              Some of these values are inaccurate because of a kernel-
              internal scalability optimization.  If accurate values are
              required, use /proc/[pid]/smaps or
              /proc/[pid]/smaps_rollup instead, which are much slower
              but provide accurate, detailed information.
```
Ah!   So there's the solution.  However "much slower" is not something I'd like turned on by default.

I welcome suggestions for how you'd like access to this information.  Separate getter method?  Config switch?  Util method?

**Comment by LukasHanusek** [comment]
Currently my process in top, takes 345m, in /proc/pid/status, values RssAnon and VmRSS are pretty close:
![image](https://user-images.githubusercontent.com/48738910/106959907-a2faaa00-673b-11eb-985d-3cb1fed53a1b.png)

However, OSHI returns 289m now. If you say that OSHI takes this value from there I dont understand why it is so much lower then.

**Comment by dbwiddis** [comment]
OSHI, specifically, takes its value from the 24th field in `/proc/pid/stat`.  
```
this.residentSetSize = statArray[ProcPidStat.RSS.ordinal()] * PAGE_SIZE;
// where the ordinal is: RSS(24)
```
> RssAnon and VmRSS are pretty close

From what I can tell, the values in `/proc/pid/stat` and `/proc/pid/statm` are identical, and match `/proc/pid/status` which is in kB units rather than pages.   Per the manpage and hinted at by the indentation in your output, `VmRSS` is the sum of `RssAnon`, `RssFile`, and `RssShmem`.

As mentioned above, according to the man page it is possible to parse the output of `/proc/[pid]/smaps` to get a more accurate value at the cost of more time.

Here's the code you could use in your own app if you chose:
```
private static long getAccurateRss(int pid) {
    String procPidSmaps = String.format("/proc/%d/smaps", pid);
    for (String s : FileUtil.readFile(procPidSmaps)) {
        if (s.startsWith("Rss:")) {
            return ParseUtil.getFirstIntValue(s) * 1024L;
        }
    }
}
```
I benchmarked the above code vs. the existing code:
```
proc/pid/stat avg value 98776.6366208 kB
proc/pid/stat time (ns) 29507.7993

proc/pid/smaps avg value 132262.8612096 kB
proc/pid/smaps time (ns) 1574260.6307
````
The existing proc read takes 0.03 milliseconds.  The new "accurate" code takes 1.6 milliseconds.  Probably acceptable for a single process, but querying a whole process list will add up to noticeable delay.

It's reasonable to include the more accurate value, but not as a default.

**Comment by LukasHanusek** [comment]
Alright, thanks for the detailed answer.

**Comment by LukasHanusek** [comment]
The best option I found is to get the value directly from top. I am aware that this is very time demanding, but I am just generating charts on a separated thread, so I do not really care how much it will take. 
`top -b -n 2 -d 0.2 -p " + pid + " | tail -1 | awk '{print $6}'`

But it seems like Java ProcessBuilder cannot execute this command chain (top: unknown option '|'), this is kinda offtopic, but if anyone knows what the problem is here I would really appareciate it. Thanks.

**Comment by dbwiddis** [comment]
I've found Java Process builder doesn't work well with piped commands.  

OSHI's `ExecutingCommand` class has several methods which abstract that code, e.g.,
```
List<String> top = ExecutingCommand.runNative("top -b -n 2 -d 0.2 -p " + pid);
if (!top.isEmpty()) {
    String tail = top.get(top.size() - 1);
    String split = ParseUtil.whitespaces.split(tail);
    if (split.length > 5) {
        return split[5];
    }
}
```

From an efficiency standpoint, however, executing and parsing a command line is likely to require more overhead than parsing a line from a `proc` pseudofile as I suggested above.

**Comment by LukasHanusek** [comment]
Thanks, the solution you posted works well. Since your solution eliminated the use of piped commands, do you think this solution could somehow lead to memory leaks (either on system side or my java app side) ? That is the only thing I am really concerned about, since I want to use this solution to generate process statistics over long period of time.

**Comment by dbwiddis** [comment]
My original solution is merely reading a file and doesn't hold on to any variables. The only "leak" would be not closing the file, but it's read with Java's built in `Files.readAllLines()` which claims to close the file even when there are exceptions.

The tradeoff in Java vs. executing a command line might be generation of more objects that are garbage collected, temporarily increasing heap memory used.

**Comment by dbwiddis** [comment]
Circling back to what OSHI should do:   I went through the process of deciding we needed a generic method to read a key/value map from a file, and realize it's already done in `FileUtil.getKeyValueMapFromFile()`.  So the following should work (untested):
```
Map<String, String> smapsMap = FileUtil.getKeyValueMapFromFile("/proc/" + pid + "/smaps", ":");
String accurateRSS = smapsMap.get("Rss");
// accurateRSS is either null or of the form "1234 kB"
```
Which I believe is sufficient to address this and we don't need any other new code.

**Comment by dbwiddis** [comment]
But I will update the javadocs to highlight this and suggest the above workaround.
