### ISSUE TITLE
Get PID of process started by ProcessBuilder

### ISSUE THREAD

**Issue by Dakado** [oshi/oshi#1519]
I need to use Java 8, so there is not the new method added in Java 9: java.lang.Process.pid(), is there any other way I can get PID of a process I just started via my Java application ?

**Comment by dbwiddis** [comment]
OSHI's `OperatingSystem` class includes a [`getProcessId()`](https://oshi.github.io/oshi/apidocs/oshi/software/os/OperatingSystem.html#getProcessId()) method which returns the current Java process PID.   If you can execute that from within that process and communicate it back to the parent, that would work.

You could also use [`getChildProcesses()`](https://oshi.github.io/oshi/apidocs/oshi/software/os/OperatingSystem.html#getChildProcesses(int,int,oshi.software.os.OperatingSystem.ProcessSort)) using that PID to iterate the children, which should include any `ProcessBuilder`-spawned processes.

**Comment by Dakado** [comment]
The problem is, that `getChildProcesses()` returns the process of the shell interpreter and not the actual started process by the shell interpreter:

![image](https://user-images.githubusercontent.com/1333978/107081219-a56c0b00-67f2-11eb-8757-fcd775c61ffd.png)
On this image, I started another Java process (under a different linux user using su) via ProcessBuilder but only 6062 is included in the child list.

**Comment by dbwiddis** [comment]
Perhaps you need to recursively find the shell interpreter’s children.  Grandchildren!

**Comment by dbwiddis** [comment]
Other than the "external" approaches above, the original suggestion to have the child process communicate its status (e.g., output something to stdout that is read by the parent, or use shared memory, etc.) may be the only other option.

**Comment by Dakado** [comment]
Solved by:

    int finalPID = getMaxChild(process.pid());
    public int getMaxChild(int pid) {
        List<OSProcess> procs = os.getChildProcesses(pid, Integer.MAX_VALUE, null);
        if (procs.size() == 0) return pid;
        for (OSProcess osp : procs) {
            return getMaxChild(osp.getProcessID());
        }
        return 0;
    }

Where variable "process" is instance of java.langProcess created by calling java.lang.ProcessBuilder.start()

**Comment by dbwiddis** [comment]
Great, recursion is fun!

If I may suggest on code review of your snippet:
 - No need to test `procs.size() == 0` as it will just skip the iteration in that case and you could return `pid` instead of 0.
 - `procs.isEmpty()` is preferred anyway. :)
 - return 0 is not good, there can be a process 0 (system process) and you'd start iterating at the top of the tree again!
 - This does seem to only return the "first" child/grandchild/etc. so may break if there are already other child processes existing.  You may want to use sorting to get the "youngest" process (replace `null` as the third argument with `ProcessSort.NEWEST`).

**Comment by Dakado** [comment]
Thanks, after 10 hours of trying to get the process id, updating from java 8 to java 9 to even get process.pid() method, I did not even notice checking size is useless before a for loop. Thanks for the suggestions!

**Comment by dbwiddis** [comment]
By the way, JDK9 also brings `ProcessHandle` that has a lot more capability including a `children()` method, that's probably more efficient than OSHI's methods.  I had thought you were using JDK 8.

**Comment by Dakado** [comment]
Originally my intension was to make it work with java 8 (because of some old environments I need to deploy to), but considering how much easier it is on java 9 I ultimately decided to update.

**Comment by dbwiddis** [comment]
In which case: 
```
ProcessHandle.of(process.pid()).descendants()
   .sorted((ph1, ph2) -> ph1.info().startInstant().compareTo(ph2.info().startInstant()))
   .reverseOrder() // not sure if Instant sorting gives oldest or youngest?
   .findFirst()
    .get();
```

**Comment by dbwiddis** [comment]
If you're using Java 9:
```
import java.time.Instant;

public class Test {
    public static void main(String[] args) {
        System.out.println("Newest Grandchlid: " + findGrandChild());
    }

    private static long findGrandChild() {
        return ProcessHandle.current()
                .descendants()
                .sorted((ph1, ph2) -> ph2.info().startInstant().orElse(Instant.EPOCH)
                        .compareTo(ph1.info().startInstant().orElse(Instant.EPOCH)))
                .findFirst().orElse(ProcessHandle.current()).pid();
    }
}
```
