### ISSUE TITLE
HWPartition uuid is always empty on windows

### ISSUE THREAD

**Issue by ymortier** [oshi/oshi#1521]
I used OSHI 4.0.0 and i have updated to OSHI 5.4.1. The uuid attribute of an instance of HWPartition is always empty on windows.

Here is a test code runnable on 4.0.0:

``` java
		SystemInfo systemInfo = new SystemInfo();
		System.out.println("**** File stores ****");
		OSFileStore[] fileStores = systemInfo.getOperatingSystem().getFileSystem().getFileStores();
		for (OSFileStore osFileStore : fileStores) {
			System.out.println("mount: " + osFileStore.getMount());
			System.out.println("uuid: " + osFileStore.getUUID());
		}
		
		
		System.out.println("**** Disk stores ****");
		HardwareAbstractionLayer hardware = systemInfo.getHardware();
		HWDiskStore[] diskStores = hardware.getDiskStores();
		for (HWDiskStore hwDiskStore : diskStores) {
			HWPartition[] partitions = hwDiskStore.getPartitions();
			for (HWPartition partition : partitions) {
				System.out.println("mount: " + partition.getMountPoint());
				System.out.println("uuid: " + partition.getUuid());
			}
		}
```

UUID of partitions are printed to the console.

If i run the following code with OSHI 5.4.1:

``` java
		SystemInfo systemInfo = new SystemInfo();
		
		System.out.println("**** File stores ****");
		boolean onlyLocalStores = true;
		List<OSFileStore> fileStores = systemInfo.getOperatingSystem().getFileSystem().getFileStores(onlyLocalStores);
		for (OSFileStore osFileStore : fileStores) {
			System.out.println("mount: " + osFileStore.getMount());
			System.out.println("uuid: " + osFileStore.getUUID());
		}
		
		
		System.out.println("**** Disk stores ****");
		HardwareAbstractionLayer hardware = systemInfo.getHardware();
		List<HWDiskStore> diskStores = hardware.getDiskStores();
		for (HWDiskStore hwDiskStore : diskStores) {
			List<HWPartition> partitions = hwDiskStore.getPartitions();
			for (HWPartition partition : partitions) {
				System.out.println("mount: " + partition.getMountPoint());
				System.out.println("uuid: " + partition.getUuid());
			}
		}
```

All uuids are the empty string for instances of HWPartition.

I think it is regression in this commit: 3ea29d2f809c9ef3ed032a8bc63eee82baae906e 
On line 303 of oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsHWDiskStore.java the uuid parameter is always the empty string. Is it desired? (https://github.com/oshi/oshi/commit/3ea29d2f809c9ef3ed032a8bc63eee82baae906e#diff-8baf6b00b7b0c94ae5a772ea57319fff4bb8fe309e4e7e554f382dad622a03abR303)
See issue: #1307

**Comment by dbwiddis** [comment]
Thanks for the detailed report and analysis.  #1523 should fix this; available in SNAPSHOT if you can test.

**Comment by ymortier** [comment]
Wow, you are fast! It works as expected with #1523. Thank you!

**Comment by dbwiddis** [comment]
It's always fast when I get enough detail to identify the problem, and put back the code that got removed in the regression. ;)

Really appreciate the detailed bug reports.
