### ISSUE TITLE
UsbDevice.serialNumber is always empty on windows

### ISSUE THREAD

**Issue by ymortier** [oshi/oshi#1522]
I used OSHI 4.0.0 and i have updated to OSHI 5.4.1. The serialNumber attribute of an instance of UsbDevice is always empty on windows.

It is a regression introduced by 00ba7d66a476cc76361efd8bfc7029d8135cfdb6.

The serialNumber is computed at line [154 of WindowsUsbDevice](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsUsbDevice.java#L154). But this computation is performed only if the  `pnpDeviceId` is in the `deviceStringCache` map. This map is filled too late (see [line 164](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsUsbDevice.java#L164)).

**Comment by dbwiddis** [comment]
### First Timers Only

I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to an open source project on GitHub before.

The main goal of this task is to learn the process for submitting a PR -- the GitHub equivalent of writing a "Hello World!" program.  If you already know the PR workflow, please leave this issue for someone else!

This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. 😄 

### The bug you are fixing

In the  `WindowsUsbDevice` `queryDeviceStringsMap` method, a refactoring left an empty map whose keys are used as a filter. This filter can simply be removed.

### What to do 

In [WindowsUsbDevice](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsUsbDevice.java#L153) line 153, remove the `if ... containsKey` conditional, so every result from the loop is added to the map.

### How to submit your change to the repository

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  We'll follow those steps, and I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- Make the changes described above.
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:
