### ISSUE TITLE
Current frequency on amd ryzen is always equals base frequency

### ISSUE THREAD

**Issue by Rudolf-Barbu** [oshi/oshi#1525]

**Comment by dbwiddis** [comment]
See discussion on #1297.  This requires elevated permissions to return an accurate frequency.

**Comment by Rudolf-Barbu** [comment]
Sorry it was my fault. Performance profile with 100% of minimum CPU state was setted on my computer. However, it seems like Intel processors have other implenmentation of frequency control.
