### ISSUE TITLE
linux get porcess commandline trapped

### ISSUE THREAD

**Issue by Anonymenus** [oshi/oshi#1532]
at linux hosts ,only if I call the method process.getCommandLine(),then the for loop is trapped. 
SystemInfo systemInfo = new SystemInfo();
        List<OSProcess> procs = systemInfo.getOperatingSystem().getProcesses();
        log.info("process size " + procs.size());
        for (OSProcess process: procs) {
            log.info(process.getName() + "--------name");
            log.info(process.getName() + process.getCommandLine());
        }

**Comment by dbwiddis** [comment]
Can you clarify what you mean by "trapped"?   

The `getCommandLine()` method simply returns the stored `String` field in the `OSProcess` object.  If there were a problem reading the command line (`simply reading `/proc/pid/cmdline`) it would happen when the `OSProcess` object was instantiated.  The only situation I can think of that would cause a problem in the middle of your loop above is if the `String` triggered poor behavior in the logger.

**Comment by Anonymenus** [comment]
<img width="602" alt="屏幕快照 2021-02-20 上午10 04 47" src="https://user-images.githubusercontent.com/19319821/108579718-2d115800-7363-11eb-8365-8f1dc7662e73.png">
<img width="1680" alt="屏幕快照 2021-02-20 上午8 52 51" src="https://user-images.githubusercontent.com/19319821/108579721-2edb1b80-7363-11eb-94e7-b70eba52d39d.png">
is that normal， the return value like that

**Comment by Anonymenus** [comment]
I remove all the log.info code, then no trapped happened
