### ISSUE TITLE
NetworkIF.isConnectorPresent() on Windows

### ISSUE THREAD

**Issue by dornand** [oshi/oshi#1534]
Hello.

I'm doing some testing with OSHI 5.5.0 on a Windows 10 x64 machine.
And i'm wondering whether the bit order on `WindowsNetworkIF.CONNECTOR_PRESENT_BIT` might be wrong.

For my physical ethernet adapter i'm getting the value of `MIB_IF_ROW2.InterfaceAndOperStatusFlags`
5 with a cable connected
21 with no cable connected

I checked [https://docs.microsoft.com/en-us/windows/win32/api/netioapi/ns-netioapi-mib_if_row2](https://docs.microsoft.com/en-us/windows/win32/api/netioapi/ns-netioapi-mib_if_row2)
and it would make much more sense, if the `ConnectorPresent` would be the 3rd bit and not the 6th.
Then 5 would be `HardwareInterface & ConnectorPresent`
and 21 `HardwareInterface & ConnectorPresent & NotMediaConnected`.

Can anyone confirm this?

**Comment by dbwiddis** [comment]
I think you're correct and this is a bug.  I originally assumed bit fields just filled in order, but [this documentation for Bit Fields](https://docs.microsoft.com/en-us/cpp/cpp/cpp-bit-fields?view=msvc-160) indicates the first element goes into the lowest bits.

> Microsoft Specific
>
> The ordering of data declared as bit fields is from low to high bit, as shown in the figure above.

This may not be the only place I've made this assumption.

**Comment by dbwiddis** [comment]
### First Timers Only

I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to an open source project on GitHub before.

The main goal of this task is to learn the process for submitting a PR -- the GitHub equivalent of writing a "Hello World!" program.  If you already know the PR workflow, please leave this issue for someone else!

This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. 😄 

### The bug you are fixing

In the  `WindowsNetworkIF` class, `updateAttributes` method, a bitmask is used to isolate the bit defining whether the connector is present.  The bit assumes big-endian order, but Windows bit fields are in little-endian order.

### What to do 

In [WindowsNetworkIF](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsNetworkIF.java#L52) line 52, change the value of the `CONNECTOR_PRESENT_BIT` constant from `0b00100000` to `0b00000100`.

### How to submit your change to the repository

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  We'll follow those steps, and I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- Make the changes described above.
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:
