### ISSUE TITLE
Fatal Error SIGSEGV in docker on Alpine Linux 3.13

### ISSUE THREAD

**Issue by Florian-Limpoeck** [oshi/oshi#1547]
I am currently using OSHI 5.3.6. When running the following command in docker with AdoptOpenJDK (11.0.10+9) i get a Fatal Error.

**Command**:
```
public static void main(final String @NotNull [] args) throws Exception {
        SystemInfo systemInfo = new SystemInfo();
        systemInfo.getHardware().getDiskStores();
}
```

**Error**:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fb105920958, pid=1, tid=36
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.10+9) (build 11.0.10+9)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (11.0.10+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0xb4958]
[error occurred during error reporting (printing problematic frame), id 0xb, SIGSEGV (0xb) at pc=0x00007fb1058ed980]
```

After some research i found out the line 164 in LinuxHDWDiskStore.java is causing that error.
`enumerate.scanDevices();`

I also tried OSHI 5.5.1 => same result

Regards
Florian

**Comment by dbwiddis** [comment]
This is just a native call to `udev_enumerate_scan_devices()`.  I don't see anything in OSHI or JNA that does anything that could cause this problem.

A [web search](https://www.google.com/search?q=udev_enumerate_scan_devices+sigsegv&rlz=1C5CHFA_enUS859US859&oq=udev_enumerate_scan_devices+sigsegv) indicates some potential hardware/software/microcode issues.

What is the underlying Linux distribution?  Does `lsblk` work on the affected container?

**Comment by Florian-Limpoeck** [comment]
Thx for fast reply.

**Linux Distribution:**
Alpine Linux v3.13

`lsblk`
doesnt work

`udevadm info -e`
works

**Comment by dbwiddis** [comment]
> lsblk
> doesnt work

This suggests a possible common cause.  Which version of `systemd` is installed?  It looks like there may have been previous bugs fixed there which caused problems if devices (usb, etc.) were connected at startup. See [here](https://bugzilla.redhat.com/show_bug.cgi?id=1738623), [here](https://bugzilla.redhat.com/show_bug.cgi?id=1079514), and [here](https://bugzilla.redhat.com/show_bug.cgi?id=1295979).

**Comment by dbwiddis** [comment]
[This](https://gitlab.alpinelinux.org/alpine/aports/-/issues/12314) may be related.

**Comment by dbwiddis** [comment]
> `lsblk`
> doesnt work

This suggests a possible common cause in the `udev` environment on the target machine.

This [Alpine Linux bug](https://gitlab.alpinelinux.org/alpine/aports/-/issues/12314) is recent, associated with `udev` block devices, and is possibly related.

**Comment by dbwiddis** [comment]
@Florian-Limpoeck Alpine Linux 3.13.3 [has been released](https://alpinelinux.org/posts/Alpine-3.13.3-released.html).  Can you test to see if the above noted bug fix resolves this?

**Comment by dbwiddis** [comment]
I'm going to close this issue assuming it was as a result of the above referenced bug in Alpine Linux.  

If you are still experiencing the problem on a 3.12 or earlier, or a 3.13.3 or later version of Alpine Linux, feel free to reopen and comment with more details.
