### ISSUE TITLE
Improve process descendant tree traversal with non-recursive algorithm

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1553]
### First Timers Only / Up For Grabs

I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/) and [up-for-grabs.net](https://up-for-grabs.net/#/).  That means that I:
 - prefer a PR for this one from someone who's never contributed to an open source project on GitHub before.  
 - will also accept a PR from a computer science student.  

If you're an experienced programmer familiar with git and GitHub, please leave this issue for someone else!

The main goal of this task is to learn the process for submitting a PR -- the GitHub equivalent of writing a "Hello World!" program.  This will get you started on the road to being an active contributor to the open source community.

As a secondary goal, this is an ideal issue for a Computer Science student learning about recursion and data structures to put that knowledge into practice in a helpful way!

### Your task

I recently added a `getDecendantProcesses()` method to the `OperatingSystem` interface, implementing with a recursive algorithm to traverse the tree of process children.   While resulting in less overall code, recursive programming is less efficient in both cpu time and memory requirements than non-recursive alternatives, and error prone (yes, I did have to tweak the code twice after the initial implementation to avoid `StackOverflow` errors.

This [website](https://www.geeksforgeeks.org/inorder-tree-traversal-without-recursion/) outlines an efficient non-recursive algorithm using a `Stack` to traverse a binary tree. Our tree isn't binary, but that algorithm can be adjusted for more than two child nodes.  There are also many `Queue`-based algorithms such as [this](https://www.thejavaprogrammer.com/breadth-first-search-bfs-java-program/).  Or the JDK has an [array-based](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/lang/ProcessHandleImpl.java#L441) solution.

### What to do 

Review the existing recursive `addChildrenToDescendantSet()` methods in:
 - [AbstractOperatingSystem](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/software/common/AbstractOperatingSystem.java#L147) line 147
 - [AbstractOperatingSystem](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/software/common/AbstractOperatingSystem.java#L181) line 181
 - [SolarisOperatingSystem](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java#L141) line 141

Replace these methods with a non-recursive algorithm.  Refactor to add helper methods as needed.

Note the following special cases you need to handle:
 - The methods presently take a boolean `recurse` argument selecting between "one generation" (children) and "all generations" (descendants) when you traverse the tree. While the argument name should change, you'll still need to handle both options.
 - On some operating systems, the "parent process id" is the same as the "process id" for a process with no parent.  Exclude the process itself from any collection of its children.
 - While possibly not needed, excluding any process already in the collection of descendants is a good idea
 - It's probably a good idea to construct and return the descendant set as part of the new methods instead of requiring the caller to pass the set as an argument.

Bonus points:
 - Alter the existing `getChildProcesses()` and `getDescendantProcesses()` which call the above methods to add an additional stream `filter()` ensuring the child/descendant process start time is no earlier than the parent's start time.

### How to submit your change to the repository

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  We'll follow those steps, and I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- Make the changes described above.
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

**Comment by jspinn** [comment]
I would like to work on this as a first time contributor. Do I need to be assigned to this issue or can I just submit a PR when I finish?

**Comment by dbwiddis** [comment]
It's yours!  I'll go ahead and assign this to you!  Let me know if you need any help!    One thought I've had since writing the issue is that you could take the version with a `List` argument, construct the map from it, and then call the one with the `Map` argument. That would reduce redundancy.

**Comment by jspinn** [comment]
@dbwiddis  Since I'm changing the methods from void to returning the set, should my code still pass the build test or is it normal for it to fail?

**Comment by dbwiddis** [comment]
You’ll have to edit how the methods in the <platform>OperatingSystem classes call that method.

**Comment by dbwiddis** [comment]
In other words, replace code like
```
Set<Integer> descendantPids = new HashSet<>();
addChildrenToDescendantSet(foo, parentPid, descendantPids, false);
```
with
```
Set<Integer> descendantPids = getChildrenOrDesendants(foo, parentPid, false);
```

**Comment by jspinn** [comment]
Thanks for your guidance! I just submitted a PR and I apologize if I'm completely off base with my changes. I'm still a student and have never contributed to a code base that wasn't mine before.

**Comment by dbwiddis** [comment]
You're not off base at all!  Good job, just a few minor comments on code review. Thanks for getting involved with open source! Your contribution is really appreciated.
