### ISSUE TITLE
IllegalStateException: Unmapped relationship

### ISSUE THREAD

**Issue by davidgiga1993** [oshi/oshi#1554]
A user of my software has the following issue when getting the hardware details:
```
IllegalStateException: Unmapped relationship: 7 in 
com.sun.jna.platform.win32.WinNT$SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX.fromPointer():3033
com.sun.jna.platform.win32.Kernel32Util.getLogicalProcessorInformationEx():715
oshi.driver.windows.LogicalProcessorInformation.getLogicalProcessorInformationEx():61
oshi.hardware.platform.windows.WindowsCentralProcessor.initProcessorCounts():155
oshi.hardware.common.AbstractCentralProcessor.<init>():73
oshi.hardware.platform.windows.WindowsCentralProcessor.<init>():66
oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.createProcessor():60
oshi.util.Memoizer$1.get():87
oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor():68
```

All I know so far is that it's Windows 10, I don't have any more hardware details so far.

Is this a known issue / is there a fix for it? I'm currently using `oshi-core:5.3.6`

**Comment by dbwiddis** [comment]
I'd point out the fact that the error occurs in JNA, except [I was the one](https://github.com/java-native-access/jna/pull/1064) who submitted that JNA PR. So I guess I should look into it. :-)

(For Info: @matthiasblaesing -- based on your suggestion [here](https://github.com/matthiasblaesing/oshi/commit/ca4a6e11fc35216cd40e662060fc056f0cc2e6a9)

The error message itself isn't that helpful: it indicates a relationship value of 7 but only 0, 1, 2, 3, and 4 are mapped.  See [SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX ](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-system_logical_processor_information_ex).

So it's likely the starting memory address is calculated improperly, and here's where it gets interesting.  The returned array increments by the structure "size" field, but looking at the returned value from the `fromPointer()` method at the top of the stack trace, it's the structures from the union, omitting the first two `relationship` and `size` fields.   I see in the implementation that these extend from `SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX` so those two fields are supposed to be included, but they are not listed in the `@FieldOrder` so they aren't populated from native memory. 

Which makes me ask the question at the sixth stage of debugging: "How did this ever work?"

Or maybe they are and I don't understand how inheritance and field order work together.  In which case something is amiss with reading the `size`.

In any case, I'm going to need some time to figure out what's happening here.   Some helpful debugging information from your user would be as much as they can describe about their processors, specifically number of packages/sockets, number of physical processors/cores, number of logical processors (hyperthreading), whether there are processor groups (more than 64 logical processors), and the arrangement of NUMA nodes and caches.

**Comment by dbwiddis** [comment]
OK, so I see in JNA's `Structure` class (line 1017) how it handles inheritance, and it does iterate up the superclass(es) and prepends those fields.  So it's not anything that obvious, and actually very mysterious at this point.

**Comment by davidgiga1993** [comment]
Thanks for your feedback! Yes I somehow expected it's a JNA issue. Sadly I can't contact the user since the crash data is anonymized so I hope he sends a mail to me asking for support. Then I can get some more details.

**Comment by dbwiddis** [comment]
If it ends up being a repeatable/reproducible problem I can try to add a lot more instrumentation to figure it out, but otherwise I'd assume some temporary glitch somewhere, possibly in Windows itself.  I'll leave this issue open for a while in case there's follow up.

**Comment by awallgren** [comment]
This is 100% repeatable for me on a machine with an AMD Ryzen 9 3950x 16-core processor (running Windows 10), so perhaps it's related to that processor architecture?

**Comment by dbwiddis** [comment]
Perhaps so!  Any chance you can run some instrumented code tests?  Basically take a copy of JNA's `com.sun.jna.platform.win32.Kernel32Util.getLogicalProcessorInformationEx()` method and use the Structure's `toString()` to print out every iteration through the loop so I can see the native values?

**Comment by awallgren** [comment]
Happy to do that -- I'll report back what I find.

**Comment by awallgren** [comment]
@dbwiddis Here's what I see -- let me know if this is the information you're looking for.

Kernel32Util.getLogicalProcessorInformationEx calls Kernel32.INSTANCE.GetLogicalProcessorInformationEx twice; the first time it gets a ERROR_INSUFFICIENT_BUFFER (which seems to be expected as it passed in 1 as the buffer size). The bufferSize that comes back is 4624, and it then makes the second call to Kernel32.INSTANCE.GetLogicalProcessorInformationEx.

It then loops through that buffer, parsing out the SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX objects.

The first time through the loop, at offset 0, it sees RelationProcessorPackage and returns:

>WinNT$PROCESSOR_RELATIONSHIP(allocated@0x1d6bf4d0330 (48 bytes) (shared from allocated@0x1d6bf4d0330 (4624 bytes) (shared from allocated@0x1d6bf4d0330 (4624 bytes) (shared from allocated@0x1d6bf4d0330 (4624 bytes))))) {
  int relationship@0x0=0x0003
  int size@0x4=0x0030
  byte flags@0x8=0x0
  byte efficiencyClass@0x9=0x0
  byte reserved[20]@0xA=[B@40d480ca
  short groupCount@0x1E=0x01
  WinNT$GROUP_AFFINITY groupMask[1]@0x20=[Lcom.sun.jna.platform.win32.WinNT$GROUP_AFFINITY;@35123634
}

The second time through the loop, at offset 48, it sees RelationProcessorCore and returns:

>WinNT$PROCESSOR_RELATIONSHIP(allocated@0x1d6bf4d0360 (48 bytes) (shared from allocated@0x1d6bf4d0360 (4576 bytes) (shared from allocated@0x1d6bf4d0360 (4576 bytes) (shared from allocated@0x1d6bf4d0330 (4624 bytes))))) {
  int relationship@0x0=0x0000
  int size@0x4=0x0030
  byte flags@0x8=0x1
  byte efficiencyClass@0x9=0x0
  byte reserved[20]@0xA=[B@68c53fee
  short groupCount@0x1E=0x01
  WinNT$GROUP_AFFINITY groupMask[1]@0x20=[Lcom.sun.jna.platform.win32.WinNT$GROUP_AFFINITY;@4f4121d2
}

The third time through the loop, at offset 96, it sees the "7" and throws the IllegalStateException.

**Comment by dbwiddis** [comment]
Well, evertyhing looks normal here.  The groupCount on the second iteration indicates only one element in the group mask, so the size of 0x30 (48) seems correct.

Can you use `dump()` on the buffer that got returned and post those bytes?  Don't need all 4624 yet, since we know the problem is at offset 96, but the first 192 bytes would be good.

**Comment by awallgren** [comment]
Here's the output of memory.dump(0, 192):
>memory dump
[03000000]
[30000000]
[00000000]
[00000000]
[00000000]
[00000000]
[00000000]
[00000100]
[ffffffff]
[00000000]
[00000000]
[00000000]
[00000000]
[30000000]
[01000000]
[00000000]
[00000000]
[00000000]
[00000000]
[00000100]
[03000000]
[00000000]
[00000000]
[00000000]
[07000000]
[30000000]
[00000000]
[00000000]
[00000000]
[00000000]
[00000000]
[00000100]
[03000000]
[00000000]
[00000000]
[00000000]
[02000000]
[38000000]
[01084000]
[00800000]
[02000000]
[00000000]
[00000000]
[00000000]
[00000000]
[00000000]
[03000000]
[00000000]

**Comment by dbwiddis** [comment]
Well, I'm now baffled.  There's no alignment issue.  There is indeed a relationship value of 7 which is [not documented](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ne-winnt-logical_processor_relationship).  It appears to have the same fields offset as the processor relationship.  This is either a bug or a new change in Windows that hasn't hit the docs yet (perhaps a "logical processor"?).

```
00[03000000] relationship 00000003
04[30000000] size 00000030
08[00000000] flags 00 efficiency 00 reserved (0-1)
0c[00000000] reserved (2-5)
10[00000000] reserved (6-9)
14[00000000] reserved (10-13)
18[00000000] reserved (14-17)
1c[00000100] reserved (18-19) groupcount 0001
20[ffffffff] group mask (all 32 low bit)
24[00000000] group mask (0 high bit)
28[00000000] group 0000, reserved (0)
2c[00000000] reserved (1-2)

30[00000000] relationship 00000000
34[30000000] size 00000030
38[01000000] flags 01 (HT) efficiency 00 reserved (0-1)
3c[00000000] reserved (2-5)
40[00000000] reserved (6-9)
44[00000000] reserved (10-13)
48[00000000] reserved (14-17)
4c[00000100] reserved (18-19) groupcount 0001
50[03000000] group mask (bits 0-1)
54[00000000] group mask (0 high bit)
58[00000000] group 0000, reserved (0)
5c[00000000] reserved (1-2)

60[07000000] relationship 00000007
64[30000000] size 00000030
68[00000000] flags 00 efficiency 00 reserved (0-1)
6c[00000000] reserved (2-5)
70[00000000] reserved (6-9)
74[00000000] reserved (10-13)
78[00000000] reserved (14-17)
7c[00000100] reserved (18-19) groupcount 0001
80[03000000] group mask (bits 0-1)
24[00000000] group mask (0 high bit)
28[00000000] group 0000, reserved (0)
2c[00000000] reserved (1-2)

90[02000000] relationship 00000002
94[38000000] size 00000038
98[01084000] level 01 associativity 08 linesize 0040
9c[00800000] cachesize 00008000
a0[02000000] type 00000002 (data)
a4[00000000] reserved (0-3)
a8[00000000] reserved (4-7)
ac[00000000] reserved (8-11)
b0[00000000] reserved (12-15)
b4[00000000] reserved (16-19)
b8[03000000] group mask (bits 0-1)
bc[00000000] group mask (0 high bit)
```

**Comment by awallgren** [comment]
I'm running an Insider version of Windows 10, so perhaps that's related. Let me set up a plain vanilla Windows 10 instance and try it there.

**Comment by dbwiddis** [comment]
My suspicion is that Windows has been trying to tackle AMD Ryzen SMT bugs (like [this one](https://www.guru3d.com/news-story/microsoft-confirms-windows-bug-is-holding-back-amd-ryzen,21.html) and may have created a new enum value for the new cores.   If you can locate your header files, the new value [here](https://github.com/hughbe/windows-sdk-headers/blob/e83bf2af3df09ec5420725bd79ccfe1bb534722c/Include/10.0.19041.0/km/miniport.h#L5785) would be useful.

**Comment by dbwiddis** [comment]
Interestingly, the [SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX ](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-system_logical_processor_information_ex) provide this tidbit:

> Future versions of Windows may support additional values for the Relationship member.

So we can't say they didn't warn us... 😀

**Comment by awallgren** [comment]
I didn't have the Windows DDK installed, but I pulled the latest one I could find (from https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewWDK) and that enum doesn't have a value for 7 either, as far as I can tell:
>typedef enum _LOGICAL_PROCESSOR_RELATIONSHIP {
    RelationProcessorCore,
    RelationNumaNode,
    RelationCache,
    RelationProcessorPackage,
    RelationGroup,
    RelationProcessorDie,
    RelationNumaNodeEx,
    RelationAll = 0xffff
} LOGICAL_PROCESSOR_RELATIONSHIP;

**Comment by dbwiddis** [comment]
You beat me by six minutes to finding that.  Looks like 6 values as-of 20279, the latest build with SDK released, but they've apparently added more since then.

Since the fix needs to be done in JNA I'll open an issue there to track.

**Comment by dbwiddis** [comment]
Interestingly, the `SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX` structure still includes only the four structures in the union, so it's likely the new enum values map to the existing ones in some way (e.g., it appears whatever the mysterious enum value 7 is maps to `PROCESSOR_RELATIONSHIP`.  I'd guess the ProcessorDie one does too, and I'd guess NumaNodeEx maps to `NUMA_NODE_RELATIONSHIP`.  

_Struct_size_bytes_(Size) struct _SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX {
    LOGICAL_PROCESSOR_RELATIONSHIP Relationship;
    DWORD Size;
    union {
        PROCESSOR_RELATIONSHIP Processor;
        NUMA_NODE_RELATIONSHIP NumaNode;
        CACHE_RELATIONSHIP Cache;
        GROUP_RELATIONSHIP Group;
    } DUMMYUNIONNAME;
};

**Comment by awallgren** [comment]
I've updated and can confirm that this symptom has disappeared from my system. 👍
