### ISSUE TITLE
Can't access to the processes

### ISSUE THREAD

**Issue by jan-tennert** [oshi/oshi#1561]
Hey I just want to access to the Processes with:
```
fun main() {
    val si = SystemInfo()
    for (process in si.operatingSystem.processes) {
        println(process.path)
    }
}
```

And I'm getting this error:
```
[main] WARN oshi.util.platform.windows.PerfCounterWildcardQuery - Disabling further attempts to query Process.

[main] WARN oshi.util.platform.windows.WmiQueryHandler - COM exception: Invalid Query: SELECT NAME,PRIORITY,CREATIONDATE,PROCESSID,PARENTPROCESSID,READTRANSFERCOUNT,WRITETRANSFERCOUNT,PRIVATEPAGECOUNT,PAGEFAULTSPERSEC FROM Win32_Process WHERE NOT Name LIKE"%_Total"
```

Java Version: 1.8 / 8
Kotlin Version: 1.4.30
Dependency Manager: Maven
OS: Windows

**Comment by dbwiddis** [comment]
> WHERE NOT Name LIKE"%_Total"

The lack of a space between LIKE and the quotation mark is a bug. However, this WMI query is the second fallback, after a direct registry query and attempt to use the Performance counters fails.  Are the performance counters intentionally disabled?

**Comment by jan-tennert** [comment]
No I don't think so. This is the only code the compiler is running currently. Do I have to enable them?

**Comment by dbwiddis** [comment]
They should be enabled by default on most systems.  You should be able to run `perfmon.exe` and see reasonable output for the `Process` counters.

See https://leansentry.zendesk.com/hc/en-us/articles/360038645792-How-to-Fix-performance-counter-issues for some steps you can take.

**Comment by jan-tennert** [comment]
Okay I followed the steps in this article and enabled the performance counters. But that didn't help this problem

**Comment by dbwiddis** [comment]
I just merged a fix, it should be available in the SNAPSHOT version.  I'll cut a new release as soon as JNA 5.8.0 is released, probably later this week.
