### ISSUE TITLE
Can't access to prozessor information

### ISSUE THREAD

**Issue by jan-tennert** [oshi/oshi#1563]
I'm trying to get the CPU Usage with:

```kotlin
private var prevTicks = LongArray(CentralProcessor.TickType.values().size)

fun getCPUUsage(): Double {
    val cpuLoad: Double = getProcessor().getSystemCpuLoadBetweenTicks(prevTicks) * 100
    prevTicks = getProcessor().systemCpuLoadTicks
    return cpuLoad
}
```

But I'm getting this error:

`WARN oshi.util.platform.windows.PerfCounterWildcardQuery - Disabling further attempts to query Processor Information.`

Weird because yesterday it worked. Did I miss something?

OS: Windows
Java: 8
Kotlin: newest
OSHI: newest

**Comment by dbwiddis** [comment]
This is the same issue with performance counters as I commented in in #1561.  Something happened to disable your Windows Performance Counters.

https://docs.microsoft.com/en-us/troubleshoot/windows-server/performance/manually-rebuild-performance-counters

**Comment by dbwiddis** [comment]
Of note, the log warning when performance counters are disabled indicates it's going to switch to using the WMI fallback, so things should generally still work. They are just going to be a lot slower.

**Comment by jan-tennert** [comment]
K. I don't know whats wrong with this. Although I have originally programmed this for my RPi. The processes working perfect but CPU doesn't show the right number.

**Comment by dbwiddis** [comment]
Your RPi would be using the Linux branch of the code which pulls data from an entirely different source on that OS.

On windows the CPU data comes from the processor performance counters, either directly (fast, primary) or indirectly via WMI (slower, backup) but it's the same counters and same calculation either way.  There are many online troubleshooting suggestions for performance counter failures, that you haven't given me enough information to suggest any more specific than the links I've provided.

Can you be more specific about "CPU doesn't show the right number"?  Windows scales CPU usage on the task manager in a different way than Linux does.

**Comment by jan-tennert** [comment]
So I have the same code as above and it shows numbers like:

0.142394234324
0.144454534543
0.145045045444

**Comment by dbwiddis** [comment]
where is `systemCpuLoadTicks` defined or updated?  If it's a zero array you're getting the cumulative CPU since startup rather than the usage between ticks

**Comment by jan-tennert** [comment]
Uhm it's kotlin so the same as
`CentralProcessor.getSystemCpuLoadTicks()`

**Comment by dbwiddis** [comment]
Sorry, not that familiar with kotlin, so just saw that.  Also given you multiply by 100 already those seem to be incredibly small values.  Seeing the raw tick values might be more helpful.

**Comment by jan-tennert** [comment]
You mean: `getProcessor().systemCpuLoadTicks`?
This gives me: 0.31429672963776256

**Comment by dbwiddis** [comment]
`getProcessor().systemCpuLoadTicks` should give you an array of seven (Long) integer values, not a single number.

**Comment by jan-tennert** [comment]
Gives me this numbers:
```
12680
0
18440
4901870
4180
0
350
0
```

**Comment by dbwiddis** [comment]
OK.... those look like reasonable values.  As a one-time snapshot we can only measure cumulative time but the used time/total time is 31470/4937520 or 0.006374.  (0.6374%).  This is what you get with a zero array of previous ticks (the first call) or any other error in the lookup.

So with you calling the method repeatedly, it should be measuring the delta between them.  

It seems you're not saving the previous ticks in a way that they are accessible the next time the method is called.  In plain Java that'd be a class variable. I'm not sure how kotlin maps to that, but that's where you should focus your debugging.

**Comment by jan-tennert** [comment]
Okay thanks

**Comment by dbwiddis** [comment]
One other thing to note:  the ticks are fetched using a memoizer so you need to wait in betwen calls.  If no ticks elapse it will fall back to the cumulative value.  So the numbers you see would be expected if running in a loop with no delay.  But polling every second should give you values between the intervals.
