### ISSUE TITLE
Not able to retrieve current OSProcess from operating system

### ISSUE THREAD

**Issue by occhioni-esteco** [oshi/oshi#1565]
Hi 
executing the following command:

```
SystemInfo systemInfo = new SystemInfo();
OperatingSystem operatingSystem = systemInfo.getOperatingSystem();
OSProcess process = operatingSystem.getProcess(operatingSystem.getProcessId());
```

is returning null OSProcess in a specific environment. 

I can't find the cause of if because i am not the owner of the system. 
What could be the causes? There is a workaround in order to retrieve the current OSProcess? 
Seems that with oshi 4.2.0 the same system was able to retrieve the OSProcess correctly. 

oshi-core: 5.4.0
jna: 5.6.0
Java JDK AdoptOpenJdk 11.0.9+11

CPU: AMD EPYC 7702 64-Cores processor  
OS: Windows Microsoft 10.0

In case of needs of tests the owner of the system can run them for us. 

Thanks in advance

**Comment by mprins** [comment]
> in a specific environment

this doesn't mean anything to us... please describe what is specific about it?

what does the logging say?

some things were fixed in the current release, please try that.

**Comment by dbwiddis** [comment]
The `getProcess(pid)` method is documented to return null if the process ID is not found in the process list. You should always be checking for null...

Although a process should normally be able to see itself so that's strange.  OSHI gathers the process info from the performance counters, first attempting via the registry (HKEY_PERFORMANCE_DATA) and secondly by perfmon, with WMI as a backup.  

If this is happening only on one machine, I'd investigate something amiss in the registry performance counters, or disabled performance counters on that machine.

**Comment by dbwiddis** [comment]
Some troubleshooting steps that would be useful:
 - Run in a command window either `wmic Process get ProcessId,Name`_ or `wmic path Win32_Process get ProcessId,Name` and look for the problematic process.
 - Run `perfmon.exe` from the command line (or type in the start menu search).  Attempt to add a counter for the "Process/ID Process" for the problematic program.
![image](https://user-images.githubusercontent.com/9291703/110667401-0f275e00-817f-11eb-9995-52036e76d6b0.png)

**Comment by occhioni-esteco** [comment]
Hi @dbwiddis thanks for the troubleshooting steps! Very helpful!

First the easy answer:

> Is there any chance the process ID is larger than the max value of a 32-bit signed integer? This is a known shortcoming in OSHI but this could happen if the PID was a 32-bit unsigned value above Integer.MAX_VALUE.

Not in this case. 


Anyway, I tried the troubleshooting steps on the machine and the result i get with 

`wmic Process Where Name="SSCE.exe" get ProcessId,Name`
or
`wmic path Win32_Process Where Name="SSCE.exe" get ProcessId,Name`

is:
```
N�a�m�e� � � � � � �P�r�o�c�e�s�s�I�d� � �
�
�S�S�C�E�.�e�x�e� � �1�4�5�8�8� � � � � � �
```

I didn't know why i get this chars �. Maybe is just some enconding issue while creating the log file. 
Anyway.. if removed what i get is
```
Name   ProcessId
SSCE.exe  14588
``

(where SSCE.exe was the name of the java process running with oshi library)

The curious thing is that if i try to run the following:
`.\bin\pslist.exe SSCE -nobanner`
What i get is: 
```
Processor performance object not found on SN-35545
Try running Exctrlst from microsoft.com to repair the performance counters.
```

So there could be some issues on that machine with the performance counters.. Il'try to repair them in the meantime. Maybe will solve the issue.

**Comment by dbwiddis** [comment]
Good luck on the counter repair.   On OSHI's side, it's reasonable to add a test whether the process map is empty (which it never should be) after the counter lookup.  Apparently in your case it just failed with an empty map.
