### ISSUE TITLE
getNetworkIFs() not working

### ISSUE THREAD

**Issue by iFlyinq** [oshi/oshi#1568]
I don't get any exception and it never reaching '2', what could be the problem? The whole thread freezes

```SystemInfo systemInfo = new SystemInfo();
        try {
            System.out.println(1);
            systemInfo.getHardware();
            System.out.println(11);
            systemInfo.getHardware().getNetworkIFs();
            System.out.println(2);
        } catch (Exception exception) {
            exception.printStackTrace();
        }
```

Version: 5.6.0

**Comment by dbwiddis** [comment]
Which operating system?

**Comment by iFlyinq** [comment]
Debian

**Comment by dbwiddis** [comment]
Can you check whether 5.5.1 works?  We recently added a change to look up the model from udev to identify the alias. (See #1541 ) which I don't think would cause a hang, but would like to rule that out.

**Comment by iFlyinq** [comment]
> Can you check whether 5.5.1 works? We recently added a change to look up the model from udev to identify the alias. (See #1541 ) which I don't think would cause a hang, but would like to rule that out.

Yeah sure, give me a minute!

**Comment by iFlyinq** [comment]
> Can you check whether 5.5.1 works? We recently added a change to look up the model from udev to identify the alias. (See #1541 ) which I don't think would cause a hang, but would like to rule that out.

Works like a charm!

**Comment by dbwiddis** [comment]
Well, then.  Something's up with `udev`.  The problem would be [this method](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxNetworkIF.java#L72) 

Can you create a copy of that method and add output to it and see where it might be hanging?

**Comment by iFlyinq** [comment]
> Well, then. Something's up with `udev`. The problem would be [this method](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxNetworkIF.java#L72)
> 
> Can you create a copy of that method and add output to it and see where it might be hanging?

Hmm, seems like [this line](https://github.com/oshi/oshi/blob/ed77b532c79a19ad2c1a21c1ea7060f069c0362f/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxNetworkIF.java#L74) is causing it.

**Comment by dbwiddis** [comment]
I did a web search for "debian gnu/linux 10 (buster) udev hangs" and got a few interesting hits.  
 - https://www.debian.org/releases/stable/amd64/release-notes/ch-information.en.html#migrate-interface-names
 - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=925146

There may be others.

See if `udevadm info /sys/class/net/<ifname>` gives output.

At this point I think it's a bug in your distro's `udev` but not sure what.

**Comment by iFlyinq** [comment]
![image](https://user-images.githubusercontent.com/20583400/111043886-724a1680-8445-11eb-81d4-f4fc62e523e4.png)
Got this as reply

**Comment by dbwiddis** [comment]
Well that looks like normal output.  Still, it's hanging on the native call to `udev_new()`.  I have no idea why that might happen unless there's a bug.

**Comment by iFlyinq** [comment]
I guess you can close the issue than

**Comment by iFlyinq** [comment]
I guess I'll close the issue than.

**Comment by dbwiddis** [comment]
Can you check whether you're using the latest version of libudev for your distribution?  I'm searching for any relevant bugs with that or systemd.

**Comment by iFlyinq** [comment]
> Can you check whether you're using the latest version of libudev for your distribution? I'm searching for any relevant bugs with that or systemd.

Everything is up to date.

**Comment by dbwiddis** [comment]
Do you see a similar hang with OSHI's disk store methods which also use udev (`systemInfo.getHardware().getDisks()`)?

**Comment by iFlyinq** [comment]
> Do you see a similar hang with OSHI's disk store methods which also use udev (`systemInfo.getHardware().getDisks()`)?

You mean getDiskStores?

**Comment by dbwiddis** [comment]
Yep, sorry, going off memory here!

**Comment by iFlyinq** [comment]
> Works like a charm!

**Comment by dbwiddis** [comment]
OK, that baffles me because `LinuxHWDiskStore` calls that same `udev_new()` function on line 159.  And it's irrelevant at that point in the code whether we're looking at network interfaces or disks.

**Comment by iFlyinq** [comment]
> OK, that baffles me because `LinuxHWDiskStore` calls that same `udev_new()` function on line 159. And it's irrelevant at that point in the code whether we're looking at network interfaces or disks.

Nevermind, I was wrong sorry. 
```        System.out.println(1);
        for (HWDiskStore diskStore : Astrax.getSystemInfo().getHardware().getDiskStores()) {
            System.out.println(diskStore.getName());
        }
        System.out.println(2);
```
![image](https://user-images.githubusercontent.com/20583400/111051537-11760a80-8454-11eb-81c9-50cda3f9cf4a.png)

**Comment by iFlyinq** [comment]
Forgot to upgrade oshi again

**Comment by dbwiddis** [comment]
So the diskstore behavior *also* changed between 5.5.1 and 5.6.0?  But there were no changes to that class. Now I'm *really* confused.

**Comment by iFlyinq** [comment]
Same for me, I probably did something wrong during the first test or forgot to disable the auto-updater or something, please don't mind.

**Comment by dbwiddis** [comment]
OK.  I do see a bug in the network method in udev -- we never release the context object (so we have a "handle leak").  

Suggestion:  reboot, and before you test the network code again, test the disk interface code and see if it works.

**Comment by iFlyinq** [comment]
> OK. I do see a bug in the network method in udev -- we never release the context object (so we have a "handle leak").
> 
> Suggestion: reboot, and before you test the network code again, test the disk interface code and see if it works.

I'll reply within 24 hours with the result, thanks for handling this soo quickly.

**Comment by dbwiddis** [comment]
I'll go ahead and fix the bug while you wait so you have a new snapshot to test.

**Comment by dbwiddis** [comment]
And you'd think I'd have remembered #521 and not made the same mistake, eh? ☹️

**Comment by iFlyinq** [comment]
You're doing as good as you can, sure of that 😉 



> I'll go ahead and fix the bug while you wait so you have a new snapshot to test.

Amazing, thanks!
