### ISSUE TITLE
Getting Processor ID's for multiple Processors in Windows

### ISSUE THREAD

**Issue by rnaval** [oshi/oshi#1580]
Is there a way to get the processor ID per processor? For example, in windows, we see this via WMI:

![image](https://user-images.githubusercontent.com/12891375/112236805-6a844080-8c95-11eb-8cbc-34ac843c69dd.png)

But based on the oshi API available, we only get 1 processor identifier here: [getProcessorIdentifier](https://oshi.github.io/oshi/apidocs/oshi/hardware/CentralProcessor.html#getProcessorIdentifier())

From which we can get the its processor ID here: [getProcessorID](https://oshi.github.io/oshi/apidocs/oshi/hardware/CentralProcessor.ProcessorIdentifier.html#getProcessorID())

In the windows test case highlighted in the image above, we only get the processor ID for `CPU0` - is there a way to get the one for `CPU1`?

As an additional note, oshi returns `2` when calling [getPhysicalProcessorCount](https://oshi.github.io/oshi/apidocs/oshi/hardware/CentralProcessor.html#getPhysicalProcessorCount()) in the windows test case above.

**Comment by dbwiddis** [comment]
This is a good idea but I suggest we implement as part of a new topology API for #1571.

**Comment by dbwiddis** [comment]
Looked into this a bit today and Windows is the only OS that makes it easy to get multiple CPUIDs (which are an Intel thing anyway, and the world is moving away from that)...  but it's possible you can just use the same code OSHI uses internally if you want all of them:
```
WmiResult<ProcessorIdProperty> processorId = Win32Processor.queryProcessorId();
for (int cpu = 0; cpu < processorId.getResultCount(); cpu++) {
    String perProcCpuid = WmiUtil.getString(processorId, ProcessorIdProperty.PROCESSORID, cpu);
    // do whatever you want with perProcCpuid
} 
```

**Comment by dbwiddis** [comment]
> i think we might need to change `queryProcessID` to return `List<ProcessIdentifier>` (never empty only null so then we can always just assume .get(0)) in AbstractCentralProcessor ? 

Given this is an internal implementation I'm not overly opposed here, but I'd prefer to think about what we actually plan to do with the list in future code (specifically how to implement #1571) before we put a lot of work into changing the code.   General thoughts here:
 - there is value in exposing a method (see above comment) to expose the windows values so users don't have to rewrite that code
 - I'm not fond of changing the api without a consistent/scalable/cross-platform alternative.  
 - ProcessorId is an Intel-only thing.  AMD chips and System-on-chip are becoming more prevalent and we really need to figure out how we want to represent this (again referencing #1571). Shoehorning all these new concepts into the existing API is probably not the best choice.

> ive looked at: WindowsCentralProcessor could iterate over the cpu index LinuxCentralProcessor for default cases would create a new instance of `ProcessorIdentifier` (as it looks like each processor get seperated by blank lines), FreeBsdCentralProcessor to parse the dmesg.boot file differently etc... 

Remember we'd like to get the answer natively when possible.  For Linux I see `/dev/cpu/<num>/cpuid` which you can read values from directly (see [here](https://man7.org/linux/man-pages/man4/cpuid.4.html)).  Not sure how Linux handles non-x86/x64 chips though! 

> not sure ... whether the new topology api solves this 

It hasn't been written, so nobody's sure. I do think that this future api would be a good home for this, as there are probably likely similar bits of information we'll want to put on a per-package/per-core/per-logicalcpu basis.  We might be able to leverage the existing `LogicalProcessor` class and just add information to it.

> sidenote: https://oshi.github.io/oshi/oshi-core/apidocs/oshi/hardware/CentralProcessor.html typo at 'ghe' => 'the', 'replationship' => 'relationship', as well as 'hexidecimal' => 'hexadecimal' ? not sure if i should create a PR for all the minor things i found

Feel free to create a "fix typos" PR, but try to minimize noise:
 - if you're only fixing typos, try to fix all the typos you see
 - if you're fixing typos while editing a single class file, feel free to add that on to the code fix

But don't combine a bunch of typo fixes in unrelated files to a code fix change. :)

**Comment by adrian-kong** [comment]
> * there is value in exposing a method (see above comment) to expose the windows values so users don't have to rewrite that code
this would only be the windows if u do linux u'd have to reparse the /proc file which was why i thought changing to list was good unless theres a different way, ill take a look into /dev/cpu/<num>/cpuid and see if theres other alternatives but this is very interesting

**Comment by dbwiddis** [comment]
> why i thought changing to list was good ...

At present I think keeping the same API with an overall singular "processor ID" is good to keep.  I'm all for a list output somewhere, but as a separate method and/or integrated into another existing API (e.g., LogicalProcessor)

**Comment by dbwiddis** [comment]
@rnaval and @adrian-kong I added a proposal on #1571 that you may want to comment on.
