### ISSUE TITLE
UsbDevice.serialNumber is always empty for Android device

### ISSUE THREAD

**Issue by tzah4748** [oshi/oshi#1598]
**Using OSHI 5.7.0** I am always getting empty serial number.

I've already seen #1522 and the fix that was made #1524 for it.
So I went over to the code to look at the fixed part...
`WindowsUsbDevice`, line 150 the query for serial numbers returns result count of 0 and the `for` loop does nothing.

**Using standard Windows 10 with Java SDK 13 as Project SDK.**

**Comment by dbwiddis** [comment]
The serial number only works for disk drives or other physical media that appears in the [`Win32_DiskDrive`](https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-diskdrive) class.  Can you see your USB device in this command line?
```
wmic path Win32_DiskDrive get Caption, Name, PNPDeviceID, SerialNumber
```
OSHI's query of that class filters by the PNPDeviceIDs it has already seen.

**Comment by tzah4748** [comment]
Sadly, no.
I don't see my device using that command.

I'll explain what I am trying to do, I would appreciate you telling me if its feasible or out of OSHI's scope.

**I am trying to detect if a certain USB Device is an Android device and get its Serial Number as its shown by the ADB.**

1. I can safely assume that a USB Device is **Android** device with **USB Debugging Enabled** by checking if one of the interfaces that the USB device has, is the **ADB Interface**.
2. After that I am trying to achieve the device's Serial Number...
I found that sometimes (Using "No Data Transfer" mode in the device) the `Unique Device ID` can contain the device's serial number:
uniqueDeviceID - `USB\VID_18D1&PID_4EE7\2040C3`
The ADB SerialNumber - 2040C3

However when I change the device's protocol to MTP/PTP the uniqueDeviceID returns something else entirely so the serial number can't be inferred from it any longer.
`serialNumber` is always empty String.
![image](https://user-images.githubusercontent.com/37114431/113676289-ef734f00-96c4-11eb-95bc-c198e06318e5.png)

**Comment by dbwiddis** [comment]
OK, as currently written OSHI can't find that, and you've already tried the PNPDeviceID (the `uniqueDeviceID` for Windows in OSHI) route.  There is another more convoluted method to attempt to retrieve serial numbers that I haven't added to OSHI (because it's convoluted!) and I suspect that under the hood it may be what Windows uses anyway to fill in that PNPDeviceID.  It involves getting a handle to the device using `DeviceIoControl()` with `IOCTL_STORAGE_QUERY_PROPERTY`.  The problem there is I need to get a "File Handle" to the device using `CreateFile()` but I'm not sure what text string I need to give (possibly the PNPDeviceID with some characters prepended).

The required methods are already in JNA, so they should be accessible to you in OSHI if you want to try them out:
```
HANDLE h = Kernel32.INSTANCE.CreateFile(someStringHere, 0, 0, 0, OPEN_EXISTING, 0, 0);
```
This is where I don't know what the string is.  It's `"\\\\.\\PhysicalDrive0"` for physical disks (substitute N for the number. you only need half the slashes, but they are escaped.). It might be `"\\\\?\\USB#VID_18D1&PID_4EE7#2040C3"` (or the other device ID you get).  (Side note: I think you need to `CloseHandle` when you're done with this.)

Then call [`Kernel32.INSTANCE.DeviceIOControl()`](https://docs.microsoft.com/en-us/windows/win32/api/ioapiset/nf-ioapiset-deviceiocontrol) with the appropriate control codes.

**Comment by dbwiddis** [comment]
OK, played around with this a little and have some progress and something you can experiment with.  

Here's the code to query my C: drive directly using the IOCTL codes.  For reference:
 - Model (Product ID) is HFM512GDGTNG-87A0A
 - Serial number is ACE4_2E00_0502_2B01. (yes that includes the trailing period)

I've successfully queried the info with the code below.  So all you need to do is figure out what string to pass for your USB device.

This might be a nice addition to OSHI as a backup serial device query (or maybe even primary as it saves a WMI call).
```
import com.sun.jna.Memory;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.Structure.FieldOrder;
import com.sun.jna.platform.win32.Kernel32;
import com.sun.jna.platform.win32.WinNT;
import com.sun.jna.platform.win32.WinNT.HANDLE;
import com.sun.jna.ptr.IntByReference;

public class IoctlTest {

    private static final int IOCTL_STORAGE_QUERY_PROPERTY = 0x2D1400;
    private static final int StorageDeviceProperty = 0;
    private static final int PropertyStandardQuery = 0;

    @FieldOrder({ "PropertyId", "QueryType", "AdditionalParameters" })
    public static class STORAGE_PROPERTY_QUERY extends Structure {
        public int PropertyId;
        public int QueryType;
        public byte[] AdditionalParameters = new byte[1];
    }

    @FieldOrder({ "Version", "Size", "DeviceType", "DeviceTypeModifier", "RemovableMedia", "CommandQueueing",
            "VendorIdOffset", "ProductIdOffset", "ProductRevisionOffset", "SerialNumberOffset", "BusType",
            "RawPropertiesLength", "RawDeviceProperties" })
    public static class STORAGE_DEVICE_DESCRIPTOR extends Structure {
        public int Version; // Size of the base structure
        public int Size; // Total size of data
        public byte DeviceType;
        public byte DeviceTypeModifier;
        public byte RemovableMedia;
        public byte CommandQueueing;
        public int VendorIdOffset;
        public int ProductIdOffset;
        public int ProductRevisionOffset;
        public int SerialNumberOffset;
        public int BusType;
        public int RawPropertiesLength;
        public byte[] RawDeviceProperties = new byte[1];

        STORAGE_DEVICE_DESCRIPTOR(Pointer p) {
            super(p);
            read();
        }
    }

    public static void main(String[] args) {
        String device = "\\\\.\\PhysicalDrive0";
        HANDLE h = Kernel32.INSTANCE.CreateFile(device, 0, 0, null, WinNT.OPEN_EXISTING, 0, null);
        if (h != null) {
            try {
                // Set up information we're requesting in input
                STORAGE_PROPERTY_QUERY spq = new STORAGE_PROPERTY_QUERY();
                spq.PropertyId = StorageDeviceProperty;
                spq.QueryType = PropertyStandardQuery; // may want to use PropertyExistsQuery to test

                // Get size to retrieve
                IntByReference lpbytesReturned = new IntByReference();
                int bufferSize = 8; // Enough to get the Size field of the return
                Memory buffer = new Memory(bufferSize);
                boolean success = Kernel32.INSTANCE.DeviceIoControl(h, IOCTL_STORAGE_QUERY_PROPERTY, spq.getPointer(),
                        spq.size(), buffer, bufferSize, lpbytesReturned, null);
                if (!success) {
                    System.out.println("Failed call to get size: " + Kernel32.INSTANCE.GetLastError());
                }

                // Allocate the size and call again
                bufferSize = buffer.getInt(Integer.BYTES);
                buffer = new Memory(bufferSize);
                success = Kernel32.INSTANCE.DeviceIoControl(h, IOCTL_STORAGE_QUERY_PROPERTY, spq.getPointer(),
                        spq.size(), buffer, bufferSize, lpbytesReturned, null);
                if (!success) {
                    System.out.println("Failed call to get data: " + Kernel32.INSTANCE.GetLastError());
                }

                // Put results into structure
                STORAGE_DEVICE_DESCRIPTOR sdd = new STORAGE_DEVICE_DESCRIPTOR(buffer);

                System.out.println("Serial Number Offset: " + sdd.SerialNumberOffset);
                System.out.println("Serial Number: " + sdd.getPointer().getString(sdd.SerialNumberOffset, "UTF8"));
                System.out.format("Vendor ID: 0x%04x%n", sdd.getPointer().getShort(sdd.VendorIdOffset));
                System.out.format("Product ID: 0x%04x%n", sdd.getPointer().getShort(sdd.ProductIdOffset));
                System.out.println("Data as string: "
                        + new String(sdd.getPointer().getByteArray(sdd.Version, sdd.Size - sdd.Version)));
            } finally {
                Kernel32.INSTANCE.CloseHandle(h);
            }
        }
    }
}
```

**Comment by dbwiddis** [comment]
Output of the above code:
```
Serial Number Offset: 139
Serial Number: ACE4_2E00_0502_2B01.
Vendor ID: 0x0028
Product ID: 0x4648
```

**Comment by dbwiddis** [comment]
And from [this site](https://www.codeguru.com/cpp/w-p/system/misc/article.php/c15963/DevicePath-Information.htm) it appears the magical string to query the device is:
 - Prefix: `\\?\` (double the slashes to escape them in a Java string)
 - PNPDeviceId with the `\` replaced by `#`.  In the examples they're all lowercase but that may not matter
 - Another `#` followed by the Class GUID (this is available in our existing WMI query as another column that we don't fetch).  You can find your device's one for testing using `wmic path Win32_PnPEntity get ClassGuid,Name,PNPDeviceID`.

**Comment by tzah4748** [comment]
First of all, thanks for all the valuable information!

I've tried the code you provided and it didn't work for me...
The magical string I generated was "\\?\USB#VID_2717&PID_FF18#2040c3#{a5dcbf10-6530-11d2-901f-00c04fb951ed}"
But it didn't work, my knowledge in what you did is very little so I couldn't understand what the problem was...
Below is the output of the failed attempts, my guess is that the query is a little off in buffer sizes or offsets? just a guess though.
```
Failed call to get size: 6
Failed call to get data: 6
Serial Number Offset: 20
Serial Number: 
Vendor ID: 0x0400
Product ID: 0x1ac0
Exception in thread "main" java.lang.IndexOutOfBoundsException: Invalid offset: -745334080
	at com.sun.jna.Memory.boundsCheck(Memory.java:352)
	at com.sun.jna.Memory$SharedMemory.boundsCheck(Memory.java:223)
	at com.sun.jna.Memory$SharedMemory.boundsCheck(Memory.java:223)
	at com.sun.jna.Memory.read(Memory.java:375)
	at com.sun.jna.Pointer.getByteArray(Pointer.java:689)
	at IoctlTest.main(IoctlTest.java:89)
```

**Comment by tzah4748** [comment]
I found a way this can be done using the VID PID and the WMI.
I am not sure if this is a valid way for all Android devices, but I've tried a few and it always worked for me.

The query I used in the cmd as follows :
`wmic path Win32_PnPEntity where "DeviceID like 'USB\\VID_XXXX&PID_YYYY\\%'" get DeviceID`
This query always returned :
`USB\VID_XXXX&PID_YYYY\SerialNumber(AsShownByADB)`

**Comment by dbwiddis** [comment]
The error code 6 is likely a bad string in the path (I saw that when I was experimenting with backslashes in my sample.). Did you double the actual number of slashes in your string?   Can you try making the whole string lowercase?

> The query I used in the cmd as follows :
`wmic path Win32_PnPEntity ...`

That is exactly the source of the "unique object ID" in OSHI, which you said works sometimes based on the device protocol.

**Comment by dbwiddis** [comment]
Hm... [this page](https://www.silabs.com/community/interface/knowledge-base.entry.html/2013/11/21/windows_usb_devicep-aGxD) suggests you might try this as a prefix:
`\?usb#vid_vvvv&pid_pppp ...`

FYI, that third field in the device ID is always the "unique" part of the identifier.  It's either the serial number, hex numbers for the serial number, or if there is no SN detected (using the IOCTL method above) a machine-generated unique ID / instance which will include the `&` character.   So you can test whether `&` is in the final string.

**Comment by tzah4748** [comment]
I did use double slashes in my String, showing pictures for my attempt -

Some examples of the queries to get the DeviceID - Notice how on MTP (As well as PTP) the last query returns 3 different results for the same device.
In the workaround I did I used the 3rd query (in the picture) to always get the serial number even when the device is in MTP mode.
![image](https://user-images.githubusercontent.com/37114431/113994642-3ba5c700-985e-11eb-932e-bae3b7590100.png)

Using the following query `wmic path Win32_PnPEntity where "name like 'Pocophone F1'" get DeviceID, ClassGuid` , I get the result `{88bae032-5a81-49f0-bc3d-a4ff138216d6}  USB\VID_18D1&PID_4EE7\2040C3` and I tried the following codes -

All the codes were tested with lower and capital as well.
- `String device = "\\\\?\\USB#VID_18D1&PID_4EE7#2040c3#{88bae032-5a81-49f0-bc3d-a4ff138216d6}";`
- `String device = "\\?\\USB#VID_18D1&PID_4EE7#2040C3#{88bae032-5a81-49f0-bc3d-a4ff138216d6}";`
- `String device = "\\?#USB#VID_18D1&PID_4EE7#2040C3#{88bae032-5a81-49f0-bc3d-a4ff138216d6}";`
- `String device = "\\??\\USB#VID_18D1&PID_4EE7#2040C3#{88bae032-5a81-49f0-bc3d-a4ff138216d6}";`

All the options failed on error code 6.

**Comment by dbwiddis** [comment]
Thanks for all the details!  

It appears the serial number is part of the device ID of the composite device, while the individual devices below it just have machine-assigned unique IDs.  This means the information should be available to you in OSHI if you look at the `uniqueDeviceID` of the "parent" device in this case.  

Also I think the other code may work with the correct GUID.  I've been hacking away at this myself and think perhaps we're using the wrong GUID.  You may need [GUID_DEVINTERFACE_USB_DEVICE](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/guid-devinterface-usb-device) which is `{A5DCBF10-6530-11D2-901F-00C04FB951ED}`.

I've been able to get the device path programmatically using [SetupDiGetClassDevs](https://docs.microsoft.com/en-us/windows/win32/api/setupapi/nf-setupapi-setupdigetclassdevsw) using either the above GUID or alternatively the one for the USB Device Controllers (and `\\?\` seems to be the right prefix based on those).  And I can programmatically get all the Device ID strings using [CM_Get_Device_ID](https://docs.microsoft.com/en-us/windows/win32/api/cfgmgr32/nf-cfgmgr32-cm_get_device_idw) navigating the USB tree down from the controller hubs (basically replicating what OSHI is doing but faster/natively). I still haven't managed to connect the two, but I have hope that once I figure out which GUID to use this will work!

**Comment by dbwiddis** [comment]
Given the above, I'd suggest one last try:
```
String device = "\\\\?\\usb#vid_18d1&pid_4ee7#2040c3#{a5dcbf10-6530-11d2-901f-00c04fb951ed}";
```

**Comment by dbwiddis** [comment]
Also I saw in the docs a USBVIEW application mentioned but didn't realize until just now it's [open sourced](https://github.com/microsoft/Windows-driver-samples/tree/master/usb/usbview).  I've already figured out on my own essentially [the code here](https://github.com/microsoft/Windows-driver-samples/blob/master/usb/usbview/enum.c) for the device controllers, and it looks like the rest of the file gives info on enumerating the hubs and devices!

Interestingly it seems `\\.\` may be a good prefix?  The device path is generated for hubs in this line
```
hr = StringCchCopyN(deviceName, cchFullHubName, "\\\\.\\", cchHeader);
```
Also I am seeing in that code that you don't need the device path for child devices, you just get it from the hub and then recursively find the handle for devices under it without needing the path.

So.... I think I've got all the code needed to totally rewrite OSHI's USB code.   Now I just need the time!

**Comment by tzah4748** [comment]
Tried all the options you give above, nothing worked 😢

Still, if you say you got all the information you need to enhance OSHI that is very good news 👍🏼

**Comment by dbwiddis** [comment]
In the mean time a quick summary of all of the above:
 - OSHI exposes the PNPDeviceID as the `uniqueDeviceID` field.  
 - This appears to contain the serial number for your device with "No Data Transfer"
 - With data transfer enabled, your device appears to be a composite device, and the serial number would be available from the `uniqueDeviceID` of the parent device.
 - In the longer term, I'll be rewriting OSHI's USB code to gather information via IOCTL rather than WMI (which is what WMI does under the hood anyway).  This should improve performance by skipping the COM calls, and possibly enable querying the serial number directly.

**Comment by dbwiddis** [comment]
So I've had a fun week exploring the USBVIEW app and digging deep into the IOCTL codes just to try to get a serial number. I found out how to get to them and realized they existed in exactly the cases you noted before, as part of a device ID, and exactly matched it.  

And I confirmed looking at the innards of the generation of PNP Device IDs that the when the serial number exists (wireless devices or storage devices) it is used in that field; otherwise an ID is generated containing an `&`, among other things.

I did discover that the config manager functions (that I knew could generate the tree) also included lookups for the name/description and a vendor...  giving us all the information we currently had. Plus with the added knowledge about the serial number...

So at the end of the day, I tossed most of the code I wrote in the last 5 days and now have a very quick iteration using the config manager functions.

**Old way, taking 281 ms**:
```
 Intel(R) 82801FB/FBM USB Universal Host Controller - 2658 (Intel)
 |-- USB Root Hub ((Standard USB Host Controller))
     |-- USB Composite Device ((Standard USB Host Controller))
         |-- USB Input Device ((Standard system devices))
             |-- Parallels USB Mouse Synchronization Device (Parallels)
         |-- USB Input Device ((Standard system devices))
             |-- HID-compliant mouse (Microsoft)
 Intel(R) 82801FB/FBM USB2 Enhanced Host Controller - 265C (Intel)
 |-- USB Root Hub ((Standard USB Host Controller))
     |-- USB Composite Device ((Standard USB Host Controller))
         |-- FaceTime HD Camera (Microsoft)
     |-- USB Printing Support (Microsoft)
         |-- HP Color LaserJet 2800 Series PS (HP)
     |-- USB Printing Support (Microsoft)
         |-- HP Color LaserJet 2800 Series PS (HP)
     |-- Virtual Printer (HP Officejet 4630 series [71721E] (Fax))
```
**New way, taking 31 ms** (serial numbers in square brackets, note s/n propagates to children of a composite device which aren't really devices, just extra interfaces on the same device)
```
 Intel(R) 82801FB/FBM USB Universal Host Controller - 2658 (Intel)
 |-- USB Root Hub ((Standard USB Host Controller))
     |-- USB Composite Device ((Standard USB Host Controller)) [s/n: PW3.0]
         |-- USB Input Device ((Standard system devices)) [s/n: PW3.0]
             |-- Parallels USB Mouse Synchronization Device (Parallels) [s/n: PW3.0]
         |-- USB Input Device ((Standard system devices)) [s/n: PW3.0]
             |-- HID-compliant mouse (Microsoft) [s/n: PW3.0]
 Intel(R) 82801FB/FBM USB2 Enhanced Host Controller - 265C (Intel)
 |-- USB Root Hub ((Standard USB Host Controller))
     |-- USB Composite Device ((Standard USB Host Controller)) [s/n: 0X8020000005AC8514]
         |-- 0x203a:0xfff9 (Microsoft) [s/n: 0X8020000005AC8514]
     |-- USB Printing Support (Microsoft) [s/n: TAG1C6A7C5FE]
         |-- HP Color LaserJet 2800 Series PS (HP) [s/n: TAG1C6A7C5FE]
     |-- USB Printing Support (Microsoft) [s/n: TAG11D87ACA0]
         |-- HP Color LaserJet 2800 Series PS (HP) [s/n: TAG11D87ACA0]
     |-- Virtual Printer (HP Officejet 4630 series [71721E] (Fax)) [s/n: TAG1F1FC736E]
```

Some final testing and I'll get a PR going.

**Comment by tzah4748** [comment]
This is such great news and good findings, I love promoting and improving open source libraries!

It only makes sense that different interfaces of the same device should point to the same actual s/n or the top parent.

I appreciate all your hard work to make this working better and faster than before!
