### ISSUE TITLE
hope to support jvm process monitor

### ISSUE THREAD

**Issue by angelyouyou** [oshi/oshi#1604]
support jvm process monitor

**Comment by mprins** [comment]
I'm not sure what you mean or want (there is no such thing as "jvm process monitor" AFAIK), so this is likely out of scope for Oshi as:
> OSHI is a free JNA-based (native) Operating System and Hardware Information library for Java.

**Comment by dbwiddis** [comment]
Hi, @angelyouyou, I'm closing this issue because it's really vague what you mean. 

If you do happen to mean "jvm process" monitoring, you might find the discussion on #249 useful.
