### ISSUE TITLE
Loopback network interface test is redundant

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1606]
Profiling shows the largest CPU impact in OSHI is associated with network interface queries.  Running all queries from `SystemInfoTest` in a loop results in 1/3 of CPU time being associated with the `isLocalInterface()` method, split equally between calls to (JDK methods) `networkInterface.isLoopback()` and `networkInterface.getHardwareAddress()`.  

This delay is evident in logs: querying network interfaces while excluding local addresses (on Windows) takes 2.1 seconds out of a total of 7 seconds to run `SystemInfoTest`.

These calls should be cached or memoized in some manner.

**Comment by dbwiddis** [comment]
One very fast and easy fix is to remove the individual isLoopback check and just test for the hardware address being null (which includes the loopback test internally and returns null if so.)

**Comment by dbwiddis** [comment]
On Windows, the JDK native implementation queries the same `IFROW` that OSHI does, so we could consider (on Windows) not doing the (slow) pre-filtering of loopback interfaces; just collect them all and ignore them during iteration if `dwType == MIB_IF_TYPE_LOOPBACK` (Vista+) or `IfType == IF_TYPE_SOFTWARE_LOOPBACK` (XP).

**Comment by dbwiddis** [comment]
### First Timers Only

I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to an open source project on GitHub before.

The main goal of this task is to learn the process for submitting a PR -- the GitHub equivalent of writing a "Hello World!" program.  If you already know the PR workflow, please leave this issue for someone else!

This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. 😄 

### The improvement you are making

In the  `AbstractNetworkIf` `isLocalInterface()` method, the code makes two checks: whether the interface is loopback, and whether it has a null hardware address.   In the JDK source code, the hardware address check also checks for loopback interfaces and returns null, making this check redundant.  Since these two checks are among the slowest existing Windows methods in OSHI, eliminating the redundancy is a good thing.

### What to do 

1. In [AbstractNetworkIf](https://github.com/oshi/oshi/blob/15164b832a9706e58f81734a32bb2c9a84f78226/oshi-core/src/main/java/oshi/hardware/common/AbstractNetworkIF.java#L176) at line 176, change the conditional to remove the loopback check only check for a null Hardware Address.
2. Add a comment above the method noting that the hardware address check also checks for loopback.

### How to submit your change to the repository

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  We'll follow those steps, and I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- Make the changes described above.
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

**Comment by barddoo** [comment]
Hey sir, I can take this

**Comment by dbwiddis** [comment]
Great, @barddoo!
