### ISSUE TITLE
CFStringRef#stringValue fails if string consists entirely of 3-byte UTF characters

### ISSUE THREAD

**Issue by caifenglin** [oshi/oshi#1611]
version:<oshi.version>5.7.1</oshi.version>
java.lang.IllegalArgumentException: CFString conversion fails or the provided buffer is too small.
	at com.sun.jna.platform.mac.CoreFoundation$CFStringRef.stringValue(CoreFoundation.java:502)

**Comment by dbwiddis** [comment]
This error occurs in JNA. I need more context to determine what the problem may be.

The code is here:

https://github.com/java-native-access/jna/blob/master/contrib/platform/src/com/sun/jna/platform/mac/CoreFoundation.java#L490-L502

It gets the character length of the string using `CFStringGetLength()`;
It gets the max length in bytes that could possibly fit using UTF8 encoding;
It allocates a buffer of that size and fetches the string.

Possible problems:
 - The data is in a format other than UTF8 (?)
 - The length of the string changes during method execution

**Comment by dbwiddis** [comment]
Looks like this can happen if the string consists completely of 3-byte unicode characters.  I'll fix this upstream https://github.com/java-native-access/jna/issues/1342
