### ISSUE TITLE
getVersion for Windows 7 comes through as Windows 6.1 SP1

### ISSUE THREAD

**Issue by jimbostimilon** [oshi/oshi#1612]
This seems like a similar issue to https://github.com/oshi/oshi/issues/1518

Using OSHI 5.7.1, `getOperatingSystem().getVersionInfo().toString()` for Windows 7 comes through as 6.1 SP1 build 7601 even though I can see in `oshi.windows.versions.properties` that 6.1 should map to one of these:
```
6.1.nt=7
6.1=Server 2008 R2
```

I'm using the jar from maven and it definitely has the oshi.windows.versions.properties file in there.

Windows XP also seems to show the same problem (comes through as 5.1 SP3 Build 2600), but Windows 10 comes through correctly. I'm sure this used to work correctly in OSHI 3.13.6.

**Comment by dbwiddis** [comment]
Ugh. I’m computerless for the weekend. Will look into it.

**Comment by dbwiddis** [comment]
Can you tell me the values in Win32_OperatingSystem?
```
wmic path Win32_OperatingSystem get BuildNumber,Version
```

**Comment by jimbostimilon** [comment]
Windows 7:
```
C:\Windows\system32>wmic path Win32_OperatingSystem get BuildNumber,Version
BuildNumber  Version
7601         6.1.7601
```

Winxp:
```
C:\Program Files\Support Tools>wmic path Win32_OperatingSystem get BuildNumber,V
ersion
BuildNumber  Version
2600         5.1.2600
```

**Comment by dbwiddis** [comment]
This is odd as it works on my Win 7 (Home) VM.  Are there any log messages about the config file?

**Comment by jimbostimilon** [comment]
No nothing in the logs at all.

**Comment by dbwiddis** [comment]
Well, I couldn't find anything obvious, but in the process realized that the JDK did all the same things OSHI did (with minor differences) in populating the `os.name` system property, so I drastically simplified the code which should now work.
