### ISSUE TITLE
macOS Big Sur: Crash in HardwareAbstractionLayer#getDiskStores()

### ISSUE THREAD

**Issue by Nibby** [oshi/oshi#1630]
Users of our application have reported two stacktraces using the following code on macOS Big Sur:
```java
SystemInfo si = new SystemInfo();
HardwareAbstractionLayer hal = si.getHardware();
List<HWDiskStore> diskStores = hal.getDiskStores();
```
Exception message 1:
```
java.lang.ClassCastException: Unable to cast to CFString. Type ID: 0
at com.sun.jna.platform.mac.CoreFoundation$CFStringRef.<init>(CoreFoundation.java:460)
at oshi.hardware.platform.mac.MacHWDiskStore.getDisks(MacHWDiskStore.java:359)
at oshi.hardware.platform.mac.MacHardwareAbstractionLayer.getDiskStores(MacHardwareAbstractionLayer.java:75)
```
Exception message 2:
```
java.lang.IllegalArgumentException: Allocation size must be greater than zero
at com.sun.jna.Memory.<init>(Memory.java:112)
at com.sun.jna.platform.mac.CoreFoundation$CFStringRef.stringValue(CoreFoundation.java:495)
at oshi.hardware.platform.mac.MacHWDiskStore.getDisks(MacHWDiskStore.java:360)
at oshi.hardware.platform.mac.MacHardwareAbstractionLayer.getDiskStores(MacHardwareAbstractionLayer.java:75)
```
Oshi lib version 5.6.1.

I was not able to reproduce the issue in my local 10.16 development environment, and is possibly related to a specific hardware setup.

**Comment by dbwiddis** [comment]
Ugh. This looks like the same type of bug as #1627, but in the HWDiskStore rather than the OSFileStore.  An expected value is no longer in the registry and returns null.  The null check in this code should be on `result` rather than on `model`.
```
                    Pointer result = diskInfo.getValue(cfKeyMap.get(CFKey.DA_DEVICE_MODEL));
                    CFStringRef modelPtr = new CFStringRef(result);
                    model = modelPtr.stringValue();
                    if (model == null) {
                        model = Constants.UNKNOWN;
                    }
```
In the other report, the user was on macOS 11.4 beta, do you know which version your users are using? That would be useful information.

I can (and will) move the null check which will avoid the exception but also leave us with a blank model.  A bigger issue is the fact that it appears macOS may be changing where this information is, and it'd be useful to find out.   Adding @brettwooldridge  to the conversation to see if we can hunt down what's changing here.

**Comment by dbwiddis** [comment]
The above comment refers to Exception 1 (Unable to cast to CFString. Type ID: 0).  Exception 2 (Allocation size must be greater than zero) was fixed in JNA 5.7.0 which is required by OSHI 5.5.0 and later.

**Comment by dbwiddis** [comment]
Exception 2 stack trace line number `MacHWDiskStore.java:360` points to an OSHI version between 5.0.0 and 5.3.7 and can be resolved by upgrading the OSHI version.

**Comment by dbwiddis** [comment]
Exception 1 stack trace line number `MacHWDiskStore.java:359` also points to an OSHI version between 5.0.0 and 5.3.7.

**Comment by brettwooldridge** [comment]
Verified fixed.

**Comment by dbwiddis** [comment]
Thanks for confirming the exception is fixed.  This is still not finding text strings (model) for some devices.  Is this just an occasional error that may be a race condition (e.g., time machine disconnecting) or is it happening for all disks (pointing to a change in 11.4) or consistently for a single device?

**Comment by brettwooldridge** [comment]
It was happening consistently when starting our app.  Every single time.  I did not try unplugging various devices, so I can't say it was one particular device.

**Comment by dbwiddis** [comment]
Unplugging shouldn't be necessary; but it would be helpful knowing if "unknown" model is appearing for just one device (pointing to something unusual about that device) or for all devices (pointing to some major change in macOS 11.4)
