### ISSUE TITLE
How can I obtain the CPU information of local system?

### ISSUE THREAD

**Issue by angelyouyou** [oshi/oshi#1634]
How can I obtain the CPU information of local system? They are different below.

**1. When I call getProcessor to format the object, I obtain the original CPU information not local system format.**

```
public static CentralProcessor getCpuInfo() {
        SystemInfo si = new SystemInfo();

        return si.getHardware().getProcessor();
    }

LOGGER.info("getCPUInfo().toJSONString()=\n{}", JSON.toJSONString(getCPUInfo()));
```

I got the string below:
```
cpuVendor=GenuineIntel, cpuName=GenuineIntel, cpuFamily=6, cpuModel=61, 
cpuStepping=4, processorID=bfebfbff000306d4, cpuIdentifier=Intel64 Family 6 Model 61 Stepping 4, 
microArchictecture=Broadwell (Client), cpu64bit=true, cpuVendorFreq=2700000000)
```

**2. When I call the toString of getProcessor(), I got the local system string.**

```
public static String getCPUInfoString() {
        SystemInfo si = new SystemInfo();

        return si.getHardware().getProcessor().toString();
    }

LOGGER.info("getCPUInfoString().toString()=\n{}", getCPUInfoString().toString());
```

I got the string below:
```
Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
 1 physical CPU package(s)
 2 physical CPU core(s)
 4 logical CPU(s)
Identifier: Intel64 Family 6 Model 61 Stepping 4
ProcessorID: BFEBFBFF000306D4
Microarchitecture: Broadwell (Client)
```

**Comment by mprins** [comment]
Why do you expect a `toString()` of an object (CentralProcessor) to be the same as that of an object (CentralProcessor) 
 serialized to json and then stringified from json to be the same?

It's pretty clear that to String is an Override in CentralProcessor when you check the class documentation

**Comment by angelyouyou** [comment]
> Why do you expect a `toString()` of an object (CentralProcessor) to be the same as that of an object (CentralProcessor)
> serialized to json and then stringified from json to be the same?
> 
> It's pretty clear that to String is an Override in CentralProcessor when you check the class documentation

OK.Thanks.
I just think the toString of CentralProcessor is likely standard. 
Have a good day.

**Comment by dbwiddis** [comment]
> I just think the toString of CentralProcessor is likely standard.

I'm not sure there's a such thing as a "standard" `toString`, and no particular formatting should be assumed or relied on.

JSON generators tend to use reflection and populate fields based on `get*()` methods, so are at least more consistent with the defined API.
