### ISSUE TITLE
Add support to get statistics of the specify udp or tcp port.

### ISSUE THREAD

**Issue by angelyouyou** [oshi/oshi#1647]
Add support to get statistics of the specify udp or tcp port.
On linux platform，IPTABLE can be used.such as
iptables -A INPUT -p tcp --dport 8080

**Comment by dbwiddis** [comment]
I'm not clear what functionality you are asking for.  The `iptables` command adds firewall rules, it does not collect statistics.  The [`InternetProtocolStats#getConnections()`](https://oshi.github.io/oshi/oshi-core/apidocs/oshi/software/os/InternetProtocolStats.html#getConnections()) method provides an iteration of existing connections by protocol and port as you have in your example.

**Comment by angelyouyou** [comment]
> I'm not clear what functionality you are asking for. The `iptables` command adds firewall rules, it does not collect statistics. The [`InternetProtocolStats#getConnections()`](https://oshi.github.io/oshi/oshi-core/apidocs/oshi/software/os/InternetProtocolStats.html#getConnections()) method provides an iteration of existing connections by protocol and port as you have in your example.

@dbwiddis 
I mean to add traffic statistics based on port number, not the total of udp or tcp.

**Comment by dbwiddis** [comment]
> I mean to add traffic statistics based on port number, not the total of udp or tcp.

This is out of scope for OSHI.

OSHI is an information library, and all its methods are essentially "read only".  It is designed to be as close to stateless as possible.

By default, linux (or any OS) does not log or record IP statistics per-port.  The `iptables` commands can allow you to set rules (this is the out-of-scope part) and begin collecting at a certain time, gathering the statistics later.   

OSHI does provide the `ExecutingCommand` class that would enable you to pass such commands and collect stats yourself using the functionality of `iptables`, but this is not something that will be added to the API.

**Comment by angelyouyou** [comment]
> > I mean to add traffic statistics based on port number, not the total of udp or tcp.
> 
> This is out of scope for OSHI.
> 
> OSHI is an information library, and all its methods are essentially "read only". It is designed to be as close to stateless as possible.
> 
> By default, linux (or any OS) does not log or record IP statistics per-port. The `iptables` commands can allow you to set rules (this is the out-of-scope part) and begin collecting at a certain time, gathering the statistics later.
> 
> OSHI does provide the `ExecutingCommand` class that would enable you to pass such commands and collect stats yourself using the functionality of `iptables`, but this is not something that will be added to the API.

OK. Thanks for your help.
