### ISSUE TITLE
OpenGL problem and Failed to add PDH Counter - minecraft

### ISSUE THREAD

**Issue by malufreitas2006** [oshi/oshi#1659]
Hi! So, I'm trying to open my Minecraft on the new 1.17 version and I actually can't do it. It crashes and says: GLFW error 65542> WGL: The driver does not appear to support OpenGL. Please make sure you have up-to-date drivers (see aka.ms/mcdriver for instructions).

and the game output says:

13:00:39.360
Preparing to launch minecraft client for 1.17
13:00:52.031
Checking installations.
13:00:52.033
Minecraft client 1.17 is ready to start.
13:00:52.033
Starting!
13:00:52.981
Using default game log configuration client-1.12.xml (outputs XML)
13:00:56.004
Failed to add PDH Counter: \Arquivo de paginação(_Total)\% Usage, Error code: 0xC0000BB8
13:00:56.008
Failed to add counter for PDH object: Arquivo de paginação
13:00:56.008
Disabling further attempts to query Paging File.
Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
13:01:15.724
Setting user: penny20222
13:01:16.063
Backend library: LWJGL version 3.2.2 build 10
13:02:46.285
Failed to create window: 
dpq$a: GLFW error 65542: WGL: The driver does not appear to support OpenGL
	at dpq.b(SourceFile:218)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
	at dpq.<init>(SourceFile:92)
	at enw.a(SourceFile:21)
	at dvo.<init>(SourceFile:483)
	at net.minecraft.client.main.Main.main(SourceFile:179)
	Process ended with exit code 0
	
	And I don't know what to do. I tried downloading the OpenGL dll on my computer, and even tried to update my drivers, but nothing got to a result.

**Comment by dbwiddis** [comment]
I see you closed this, so not sure if you resolved it or realized the GLFW error is not associated with OSHI. 

For the OSHI portion, there's a problem with your localized counter names, but it was just a warning and should use a fallback to WMI for that data.
