### ISSUE TITLE
Hello I would like to know how many versions of JDK7 are supported

### ISSUE THREAD

**Issue by Tuzhiqiang1996** [oshi/oshi#1667]
I'm running a JDK7 environment in my own project and I don't know which version of JDK7 the dependency supports

**Comment by dbwiddis** [comment]
As addressed in the [FAQ](https://github.com/oshi/oshi/blob/master/FAQ.md#what-minimum-java-version-is-required) OSHI 3.x (latest version 3.13.6) supports Java 7, but has not seen any new features since mid-2019.
