### ISSUE TITLE
Error code: 0xC0000BB8

### ISSUE THREAD

**Issue by MarcBalduf** [oshi/oshi#1668]
Failed to add PDH Counter: \Auslagerungsdatei(_Total)\% Usage, Error code: 0xC0000BB8

oshi.util.platform.windows.PerfCounterQueryHandler
main
Failed to add counter for PDH object: Auslagerungsdatei

oshi.util.platform.windows.PerfCounterQuery
main
Disabling further attempts to query Paging File.

**Comment by dbwiddis** [comment]
Please ensure you are using the latest version of OSHI.  Your log error indicates a localization issue that was fixed in 5.7.5.

**Comment by dbwiddis** [comment]
Closing this issue as I believe the reported problem has already been fixed and released. If this is not the case, feel free to reply and I'll reopen the issue.
