### ISSUE TITLE
Memory leak in getUsbDevices

### ISSUE THREAD

**Issue by botto** [oshi/oshi#1670]
I'm seeing a memory leak when repeatedly doing `getUsbDevices` running on a Linux machine.

The test program I used was:
```
import oshi.SystemInfo;
import oshi.hardware.HardwareAbstractionLayer;

public class main {
    private static final HardwareAbstractionLayer hal = new SystemInfo().getHardware();
    public static void main(String[] args) {
        while (true) {
            hal.getUsbDevices(false);
        }
    }
}
```

and the result I got over a a 22 min run. Those dips are me hitting the `Perform GC`
![image](https://user-images.githubusercontent.com/175029/122809470-0e49b080-d2c6-11eb-9d21-c57f979887c5.png)

**Comment by dbwiddis** [comment]
I'm not sure this is evidence of a leak.  The memory goes on the stack from the creation of objects for the USB Devices, and the many strings used in the process of creating them, so if you can release it with GC it's not a leak -- a leak would eventually result in an out of memory error.

That said, I'm looking at the code in `LinuxUsbDevice` to confirm:
 - `udev` context object allocted line 86 is unreferenced line 151
 - `enumerate` enumerator allocated line 88 is unreferenced line 150
 - `devices` variable line 91 is just a pointer to structure in the existing enumerator and doesn't allocate anything. Same for the `dev_list_entry` in the loop.
 - `dev` object allocated line 111 is unreferenced line 147

Do you have other evidence of a memory leak?

**Comment by botto** [comment]
Sorry, there was a test I missed before opening this. Setting a constrained maximum memory and letting it run. I've never got a OOM error so I'll close this.
