### ISSUE TITLE
HELP!!! How to access the portableDevice's storage!

### ISSUE THREAD

**Issue by deaconWong** [oshi/oshi#1688]
HELP!!! How to access the portableDevice's storage!
HELP!!! How to access the portableDevice's storage!
HELP!!! How to access the portableDevice's storage!

**Comment by dbwiddis** [comment]
If you need help (which apparently you do!) you need to provide more information.

What operating system?  What portable device?  Is it mounted as a filesystem?  Where do you see it in your other operating system displays?

**Comment by deaconWong** [comment]
> If you need help (which apparently you do!) you need to provide more information.
> 
> What operating system? What portable device? Is it mounted as a filesystem? Where do you see it in your other operating system displays?

yeah...I wanna access to the android mobile device's mass storage

**Comment by dbwiddis** [comment]
Have you mounted it as a drive?   It will show up on OSHI's OSFileSystem list.

Its raw storage should probably show up on the HWDiskStore list.

The name of the device will probably show up in your USB device list.

Beyond that, unless you show me the difference between something you see in your operating system (File Explorer) vs. OSHI's output, I'm really not sure what  you're asking.

**Comment by deaconWong** [comment]
HWDiskStore and OSFileStore can't get the android's mass storage!
UsbDevice can get the deviceId, how to open the device using the deviceId

**Comment by dbwiddis** [comment]
That's out of scope for OSHI.  OSHI just reports the information from the operating system (that you have a device connected but no drive or filesystem).

Some answers here:  https://superuser.com/questions/1157661/how-to-mount-an-android-smartphone-as-a-drive-in-windows

**Comment by deaconWong** [comment]
THKs

**Comment by deaconWong** [comment]
THKs
