### ISSUE TITLE
It's time for OSHI 6.x

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1694]
As the 5.x branch is becoming increasingly stable (evidenced by fewer bug reports) I think it's time to begin the transition to OSHI 6.x.

I've been considering many of the comments and requests in issues/PRs both here and at the [OSHI6](https://github.com/oshi/oshi6) site.  While I don't think we need to do all of the things proposed there (such as automatic code generation), there have been many good suggestions, ideas, and discussions and I've settled on a path forward that I think will address most of them.

I'd appreciate comments on this issue from @dblock, @mprins, @hazendaz, @cilki, @YoshiEnVerde, @spyhunter99, @Space2Man, @tausiflife, and anyone else who would like to see more (or less) than what I'm outlining here.

# Overall vision:
 - Maintain the same API (with minor adjustments)
 - Maintain compatibility with Java 8
 - Completely rewrite the implementations, separating API from the data fetching layer
 - Maximize compatibility (provide some information on "unsupported" OS's)
 - Minimize code duplication (reuse code as much as possible)
 - Reduce the size of classes loaded
 - Full user control over exception handling
 - Smart caching; minimal use of static variables
 - Separate API test (current situation) and platform-specific driver tests (we don't have these)

# Specifics:

## Maintain the same API (with minor adjustments)

To ease transition of existing codebases, we will keep the existing API interfaces.  Some adjustments include:
 - Removal of deprecated code
 - Change of return types as noted in #1425
 - Change package root from `oshi` to `com.github.oshi`

## Maintain compatibility with Java 8

I'm committed to full support of JDK 8 through its EOL (March 2025) and the `oshi-core` artifact will retain this compatibility.

I have plans to create a dependency-free, performance-sensitive, modular, scaled-down artifact (`oshi-ffi`?) returning only the most used features (CPU, Memory, Process information) leveraging features of Project Panama. This will be a long-term development project with 0.x versions supporting latest JDK versions as long as the FFI features are still incubating.

## Completely rewrite the implementations, separating API from the data fetching layer

Existing cross-platform APIs
 - Cross platform "Impl" classes implementing the API:
   - Methods in this implementation layer will load and cache (memoized) a platform specific "Driver" classes
     - There will be an `interface` for the driver used in remaining code
     - Platform-speicific (some common to multiple platforms) driver implementations will fetch the native bits
     - Tests will be written to target the drivers
     - Drivers may return `null` results or throw exceptions when they fail
   - Successful queries will return results from the driver to the user
   - Failed result queries will be passed to a `handleXException()` method in a user-overridable class
     - The default behavior of these handlers will be either (based on config) customized exceptions or graceful failures 
     - Users may override handler methods to throw their own exceptions, log (or suppress/swallow/change level), or take any other desired actions

## Maximize compatibility (provide some information on "unsupported" OS's)

Use core Java methods (e.g., System properties) to provide partial information, particuarly things like OS, version, and architecture.

## Minimize code duplication (reuse code as much as possible)

Use common drivers for common methods (a lot of *nix command results)

## Reduce the size of classes loaded

Split up large classes into more targeted classes (e.g., ParseUtil is way too big)

## Full user control over exception handling

Overridable classes as mentioned above; possibly offer two defaults based on a a one-line configuration parameter "throw exceptions" or "catch and log exceptions".

## Smart caching; minimal use of static variables

One motivation for a complete rewrite is to avoid putting `static` variables in from the start, using instance variables or memoizers.

## Separate API test (integration testing/current situation) and platform-specific driver tests (we don't currently have these)

We presently test the same API on all OS's.  We do not verify sane output from platform-specific drivers.  We need to do this, even if we simply output the results to a log for human review.

**Comment by tausiflife** [comment]
Its great to know that 5.x branch has stabilized. I really like the idea of completely rewrite implementation, however i don't understand driver classes. Don't we have driver classes already for this? 
Separate API test - Could you please elaborate what you mean? 
What do you think about adding JMX as was requested in https://github.com/oshi/oshi/issues/1312 ? This could be added later as I don't see the urgency.

**Comment by mprins** [comment]
+1 on keeping Java 8 support and (trying) to keep the current API.

As a side note we could setup some tooling to help with the QA side of these goals eg. using PMD/Checkstyle and the enforcer  plugin. In the Geotools and Geoserver projects we've implemented some of these and they help keeping the code quality up to par.

**Comment by dbwiddis** [comment]
> Don't we have driver classes already for this?

We started doing this somewhere in the middle (following the original discussion on the oshi6 project site), so "newer" code has it, but there's still lots of code in the older classes that doesn't follow this model.  This will be a way to finish that transition cleanly.

What we don't currently have is "Driver API" classes that allow us to write a single implementing class and push the platform selection logic into the "driver loading" process.  That's the biggest change I'm looking at here, but I think it will help drive clean, modular code.   Implementing class methods will all simply be something like:

```
int getThatInfo() {
    InfoDriver foo = loadInfoDriver(); // loads common or platform specific
    try {
        return foo.getInfo();
    } catch (UnimplementedException ue) {
        InfoHandler.handleUnimplementedGetInfo(ue);
    } catch (FetchingException fe) {
        InfoHandler.handleFetchingExceptionGetInfo(fe);
    }
}
```
> Separate API test - Could you please elaborate what you mean?

Have a look at [this site](https://sormuras.github.io/blog/2018-09-11-testing-in-the-modular-world.html).  We currently don't really test more than the API (integration testing as described on that site).  So for things like Windows Performance Counters (with WMI backup) we only test one or the other and show it provides a sane result.  But we've had some longstanding bugs in that process that we didn't catch _because_ of that graceful fallback.

So we would test both Perf Counters, _and_ the WMI Query, as well as separately (it) the graceful fallback mechanism.

> What do you think about adding JMX

I honestly don't know what's really being asked for.  If there's something that needs to be done at the design stage (drivers returning beans?), now is the time to bring it up.

> using PMD/Checkstyle 

We do use checkstyle, at least, as part of the test suite (see `SourceCodeTest`), and Appveyor enforces it too.  I think it's also in one of the reports on the generated site.   PMD tests are mostly integrated (or patterns ignored) in our other CI testing tools like Sonar.

**Comment by dbwiddis** [comment]
It begins..... https://github.com/dbwiddis/oshi/tree/master/oshi-core/src/main/java/com/github/oshi

**Comment by dbwiddis** [comment]
So, I got started 12 days ago... and stopped... and realized a few things in the process.
 - It doesn't save anything over the existing setup, and actually adds duplication.
 - It's adding a lot of complexity to the existing setup for not much extra gain, leading to a bigger possibility of errors.
 - By changing the package and classes so much it prevents reviewing the changes in a diff, leading to a bigger possibility of errors.
 - The intent to change the package names to match the reverse DNS module name is intended for the modular version. I might want to reserve that for the new Panama-based version.
 - I'd like to toss out a bunch of tasks for next month's Hacktoberfest, and had envisioned a template people could follow to help me with the transition.  Unfortunately I don't think that will work.

So, I'm going to back up and just make incremental changes to the existing setup.  I will go ahead and move more things to driver classes, and I can set up some hacktoberfest tasks to write tests, but a whole redesign is probably not going to happen. :(
