### ISSUE TITLE
Received : java.lang.NullPointerException: OSProcess is null, while calling operatingSystem.getProcess(processId) 

### ISSUE THREAD

**Issue by Akash-Anand0744** [oshi/oshi#1704]
**Environment Details :** 
Edition : Windows 10 Enterprise Edition
Processor : Intel(R) Xeon(R) GOLD 6242 CPU @2.80Ghz 2.79Ghz
RAM : 8gb
Version : 1909
System type: 64-bit operating system, x64-based processor

**Question1 :** Does oshi api supports all kind of windows 10 operating system ? because in other windows 10 enterprise editions I don't see this issue.

**Question 2** : I am running the service as System local. And, I believe system local has access to windows registry keys an all so should not be a problem here.
I did some troubleshooting steps as mentioned below : 
_**cmd :**  wmic path Win32_Process Where ProcessId=XXXX  get ProcessId,Name,WindowsVersion,OSName
**returns :** No instance is available_
I believe the windows version is not listing the process while running the WMI command. I know that oshi find the process details from windows registry key and secondly from perfmon. 

**Note :** We are using oshi-core version, 5.2.5 and jna version 5.6.0.

**Comment by Akash-Anand0744** [comment]
sure got it !!
I'll check once with latest oshi-core and jna version. 

**Stack Trace :** 
```
Caused by: java.lang.NullPointerException: OSProcess is null
INFO   | jvm 4    | 2021/08/10 16:34:36 | WrapperSimpleApp Error: 	at java.util.Objects.requireNonNull(Objects.java:228)
INFO   | jvm 4    | 2021/08/10 16:34:36 | WrapperSimpleApp Error: 	at io.cloudslang.worker.monitor.metric.WorkerPerfMetric.getProcess(WorkerPerfMetric.java:41)
INFO   | jvm 4    | 2021/08/10 16:34:36 | WrapperSimpleApp Error: 	at io.cloudslang.worker.monitor.PerformanceMetricsCollector.<init>(PerformanceMetricsCollector.java:70)
INFO   | jvm 4    | 2021/08/10 16:34:36 | WrapperSimpleApp Error: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO   | jvm 4    | 2021/08/10 16:34:36 | WrapperSimpleApp Error: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
INFO   | jvm 4    | 2021/08/10 16:34:36 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 4    | 2021/08/10 16:34:36 | WrapperSimpleApp Error: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
INFO   | jvm 4    | 2021/08/10 16:34:36 | WrapperSimpleApp Error: 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:212)
INFO   | jvm 4    | 2021/08/10 16:34:36 | WrapperSimpleApp Error: 	... 33 more
```
**Java Version** : java version "1.8.0_261"

**Code :**  : 
```
OperatingSystem operatingSystem = systemInfo.getOperatingSystem();
        int processId = operatingSystem.getProcessId();
        return requireNonNull(operatingSystem.getProcess(processId), "OSProcess is null");
```

**Comment by Akash-Anand0744** [comment]
That is fine, our code doesn't handle the null pointer. But my point here is that it should not be null.
Basically it returns the 'processId' as mentioned in the code but during this operation i.e., `operatingSystem.getProcess(processId)` it returns null and the result cannot be null in our case

**Comment by Akash-Anand0744** [comment]
> 
> 
> You have failed to provide your Java version.
> 
> When you check the release notes quite a few problems on Windows have been resolved over the last year. Please try the current release.
> 
> see also #1565 which your issue seems to duplicate.
> As documented here: [#1565 (comment)](https://github.com/oshi/oshi/issues/1565#issuecomment-795709655) returning `null` is documented and you should check for that

I can get it but here we added the code to check for empty list. In my case it returns the processId as mentioned in the last comment and fails at the next steps

**Comment by dbwiddis** [comment]
> But my point here is that it should not be null.

How are you certain that process ID exists?

You've stated a WMI query filtering for the process returns "No Instance."

You have not told me whether that process exists in the performance counters, which is where OSHI gets its process information.  Does it?  

If it's not in the performance counters or in WMI, where would you suggest OSHI get the process details to return something other than null?

**Comment by dbwiddis** [comment]
Hey @Akash-Anand0744, haven't heard from you on this issue.   I'm intending to close this as "this method is documented as returning null if the process doesn't exist."  If there is any other reason you think we should make a change to OSHI please let me know.
