### ISSUE TITLE
udev library issue

### ISSUE THREAD

**Issue by ykxkeghm1t** [oshi/oshi#1714]
My monitor runs on a very old Linux system and does not have the udev library. How do I not use the udev library

**Comment by dbwiddis** [comment]
Given that OSHI supports Linux distros 2.6 and later, udev has been an assumption.  There's not really a built in backup.

In modern distros, udev is just an abstraction to things you could obtain from sysfs and/or the /dev directory, but those haven't been coded up.

So unfortunately the answer is either:
 - Install udev on your system if possible to build it from source
 - Don't use OSHI's features that rely on UDEV (generally disk devices and usb devices) and program your own workarounds
 - Upgrade to a newer distribution

**Comment by ykxkeghm1t** [comment]
Ok, thank you

**Comment by dbwiddis** [comment]
If it's helpful, the initial implementation of Linux USB Devices did not use Udev and you can see it here:
https://github.com/oshi/oshi/blob/287732b3adc266be6716ac88a5e599afbcbbfc71/src/main/java/oshi/hardware/platform/linux/LinuxUsbDevice.java

You could probably adapt something similar to the disks, although the initial implementation used udev so there's nothing previous you could use as an example.
