### ISSUE TITLE
why OSProcess has no port info

### ISSUE THREAD

**Issue by Anonymenus** [oshi/oshi#1720]
It already exits pid info, I thought it will be nice if add port info.  It is no too much harder to get port info through pid, is there any problem when get port info that I have no realize.

**Comment by dbwiddis** [comment]
I'm not sure where to get the information other than parsing `netstat` or `lsof`.  

I tend to avoid adding things that don't have a faster native option, although this is reasonably consistent cross-platform and obtaining a list of open ports/pids seems like it would fit somewhere in the InternetProtocol class (but probably not OSProcess).    PR welcome.

**Comment by dbwiddis** [comment]
Actually, the [InternetProtocolStats](https://oshi.github.io/oshi/oshi-core/apidocs/oshi/software/os/InternetProtocolStats.html) class does have a `getConnections()` method which displays Process PID attached to an active connection.

Not sure that applies to a port that's just open and listening though.  But does that answer the need?

**Comment by Anonymenus** [comment]
getConnections() can work, thank you
