### ISSUE TITLE
Incorrect use of Reference Equality for INVALID_HANDLE_VALUE

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1765]
### First Timers Only

I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to an open source project on GitHub before.

The main goal of this task is to learn the process for submitting a PR -- the GitHub equivalent of writing a "Hello World!" program.  If you already know the PR workflow, please leave this issue for someone else!

This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. 😄 

### The bug you are fixing

In [multiple places](https://github.com/oshi/oshi/search?q=INVALID_HANDLE_VALUE), OSHI retrieves a `HANDLE` to a Windows Device.   Errors retrieving this return the null handle object `INVALID_HANDLE_VALUE`.   However, OSHI incorrectly uses reference equality to test these return values.  We should instead be using object equality (`.equals()`).

### What to do 

1. Fix the following 3 lines of code to replace the use of `==` with `.equals()` and `!=` with `! ... .equals()`:
   - `DeviceTree.java` [line 94](https://github.com/oshi/oshi/blob/d535f0e3af8c69e71349515c00cab2e63b5f5f00/oshi-core/src/main/java/oshi/driver/windows/DeviceTree.java#L94)
   - `WindowsPowerSource.java` [line 154](https://github.com/oshi/oshi/blob/15164b832a9706e58f81734a32bb2c9a84f78226/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsPowerSource.java#L154)
   - `WindowsFileSystem.java` [line 184](https://github.com/oshi/oshi/blob/15164b832a9706e58f81734a32bb2c9a84f78226/oshi-core/src/main/java/oshi/software/os/windows/WindowsFileSystem.java#L184)

2. Add a CHANGELOG entry crediting yourself for the bug fix.

### How to submit your change to the repository

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  We'll follow those steps, and I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- Make the changes described above.
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

**Comment by mythili-rajaraman** [comment]
@dbwiddis , I would like to pick this up.

**Comment by dbwiddis** [comment]
All yours, @mythili-rajaraman !
