### ISSUE TITLE
Unnecessary parentheses

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1766]
### First Timers Only

I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to an open source project on GitHub before.

The main goal of this task is to learn the process for submitting a PR -- the GitHub equivalent of writing a "Hello World!" program.  If you already know the PR workflow, please leave this issue for someone else!

This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. 😄 

### The bug you are fixing

In `ParseUtil` [line 999](https://github.com/oshi/oshi/blob/7bbc4545160c233e798a258af672bb3de91c076f/oshi-core/src/main/java/oshi/util/ParseUtil.java#L999) there is an extra set of parentheses.  

### What to do 

Remove the extra parentheses.

### How to submit your change to the repository

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  We'll follow those steps, and I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- Make the changes described above.
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

**Comment by trantran199** [comment]
can I try it? can you guide me?

**Comment by adrian-kong** [comment]
> can I try it? can you guide me?

i think someone did it already #1769

but contributing is really easy just follow https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md

**Comment by dbwiddis** [comment]
@trantran199 someone else got this one but I have another simple change you can do if you wish.  About to post a new issue for it.
