### ISSUE TITLE
Should not rely on default platform charset

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1770]
### First Timers Only

I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to an open source project on GitHub before.

The main goal of this task is to learn the process for submitting a PR -- the GitHub equivalent of writing a "Hello World!" program.  If you already know the PR workflow, please leave this issue for someone else!

This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. 😄 

### The bug you are fixing

In `ParseUtil` lines [1347](https://github.com/oshi/oshi/blob/7bbc4545160c233e798a258af672bb3de91c076f/oshi-core/src/main/java/oshi/util/ParseUtil.java#L1347), [1381](https://github.com/oshi/oshi/blob/7bbc4545160c233e798a258af672bb3de91c076f/oshi-core/src/main/java/oshi/util/ParseUtil.java#L1381) and [1385](https://github.com/oshi/oshi/blob/7bbc4545160c233e798a258af672bb3de91c076f/oshi-core/src/main/java/oshi/util/ParseUtil.java#L1385), a `new String()` is created from bytes, but relies on the default platform character set.

### What to do 

Add a parameter `StandardCharsets.UTF_8` to each of the above 3 lines of code to produce consistent behavior regardless of platform default character set.

### How to submit your change to the repository

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  We'll follow those steps, and I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- Make the changes described above.
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

**Comment by barismutan** [comment]
Hello, can I please work on this?

**Comment by dbwiddis** [comment]
Alll yours @barismutan !

**Comment by hkimbrough22** [comment]
Hi @dbwiddis, would I be able to help with this or is this a one-person job?

**Comment by dbwiddis** [comment]
It's a 1-person job but if you want something to do, check out #1773... can you go through all 3 SysctlUtil classes and change the failure messages from log level ERROR to WARN?

**Comment by dbwiddis** [comment]
Fixed in #1777
