### ISSUE TITLE
Enums should be immutable

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1771]
### First Timers Only

I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to an open source project on GitHub before.

The main goal of this task is to learn the process for submitting a PR -- the GitHub equivalent of writing a "Hello World!" program.  If you already know the PR workflow, please leave this issue for someone else!

This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. 😄 

### The bug you are fixing

[All fields in an enum class should be final](https://errorprone.info/bugpattern/ImmutableEnumChecker).

### What to do 

Add the `final` modifier to the following enum fields:

 - `name` in `PlatformEnum`: oshi-core/src/main/java/oshi/PlatformEnum.java Line 84
 - `index` in `TickType`: oshi-core/src/main/java/oshi/hardware/CentralProcessor.java Line 291
 - `order` in `ProcPidStat`: oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java Line 424
 - `size` in  `LwpsInfoT`: oshi-core/src/main/java/oshi/driver/unix/aix/PsInfo.java Line 81
 - `size` in `PsInfoT`: oshi-core/src/main/java/oshi/driver/unix/aix/PsInfo.java Line 124
 - `size` in `LwpsInfoT`: oshi-core/src/main/java/oshi/driver/unix/solaris/PsInfo.java Line 95
 - `size` in `PsInfoT`: oshi-core/src/main/java/oshi/driver/unix/solaris/PsInfo.java Line 147

### How to submit your change to the repository

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  We'll follow those steps, and I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- Make the changes described above.
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

**Comment by LENHUTDUY-8120** [comment]
Assign me! please

**Comment by dbwiddis** [comment]
Fixed in #1772
