### ISSUE TITLE
Failed sysctl call: hw.cpufrequency_max, Error code: 2

### ISSUE THREAD

**Issue by chenxiwen** [oshi/oshi#1773]
i'm using m1 macbookpro with macOS of 12.0.1
the oshi version is 5.8.3

i found "Failed sysctl call: hw.cpufrequency_max, Error code: 2" error will show out when the first time calling HardwareAbstractionLayer.getProcessor.getMaxFreq method

it's not serious but just...
maybe it can be handled :)

**Comment by dbwiddis** [comment]
It is "handled" and you just get a log message. :)

This is somewhat expected on the M1.  

We could reduce the level to warning, which seems reasonable.  

You could also configure your logger not to log errors in the SysctlUtil class.

We can also look into skipping the frequency check for M1 chips.  Is that the only log message you get?

**Comment by dbwiddis** [comment]
Here's [3 log messages](https://github.com/oshi/oshi/search?q=SYSCTL_FAIL) that should be changed from error to warning.

**Comment by chenxiwen** [comment]
> It is "handled" and you just get a log message. :)
> 
> This is somewhat expected on the M1.
> 
> We could reduce the level to warning, which seems reasonable.
> 
> You could also configure your logger not to log errors in the SysctlUtil class.
> 
> We can also look into skipping the frequency check for M1 chips. Is that the only log message you get?

yeah, that's what i mean, i can handle it by changing logger level, but you know, if the message is warning or info with a notice just let developers known it's nothing serious for your software or system, that will be better for me.

Thanks for replying :)

**Comment by dbwiddis** [comment]
I think for now just reducing the log level will work.  I didn't see an easy/general way to identify M1 chips to suppress the test entirely, though, and don't (yet) have an M1 machine to explore or test on.

**Comment by chenxiwen** [comment]
so,  shall we leave this issue open? Maybe someone has the same question, they can find the answer more easier :)

**Comment by dbwiddis** [comment]
Leave it open until someone submits a PR to change the log message level :)

**Comment by dbwiddis** [comment]
Reduced log level to warning in #1773.
