### ISSUE TITLE
Windows Error Version Returns

### ISSUE THREAD

**Issue by Anonymenus** [oshi/oshi#1775]
I use version `oshi-core-5.8.0.jar`.when I  getVersion on the `windows server 2016` with function `systemInfo.getOperatingSystem().getVersionInfo().getVersion()`, it returns `NT (unknow)`
<img width="688" alt="屏幕快照 2021-11-16 下午12 50 31" src="https://user-images.githubusercontent.com/19319821/141941479-c2a9f6db-9c53-420f-a1e8-db35c367a780.png">
<img width="831" alt="屏幕快照 2021-11-16 下午3 22 49" src="https://user-images.githubusercontent.com/19319821/141941497-60e3ed52-48ff-464e-966b-665ae1084096.png">

<img width="294" alt="屏幕快照 2021-11-16 下午3 21 44" src="https://user-images.githubusercontent.com/19319821/141941509-18af68ae-cb9b-43f5-96c0-5b411cd7d3d1.png">

**Comment by Anonymenus** [comment]
`System.getProperty("os.name");` returns `NT (unknown)`

**Comment by Anonymenus** [comment]
Is there any solutions to solve this problem

**Comment by dbwiddis** [comment]
OSHI gets its version directly from the `os.name` System Property:
```java
String version = System.getProperty("os.name");
if (version.startsWith("Windows ")) {
    version = version.substring(8);
}
```
As you have observed, the incorrect version number is being reported by the JDK.  That logic is [here](https://github.com/openjdk/jdk/blob/master/src/java.base/windows/native/libjava/java_props_md.c#L498-L578), ultimately parsing the major and minor version numbers and build number from `OSVERSIONINFOEX` to produce the version string, and apparently failing.  Looking through the history of `java_props_md.c` it's entirely possible that a very old (pre-2017) version of Java may cause this problem.

What version of Java are you using?

**Comment by Anonymenus** [comment]
the old one, `version 2015`,then I upgrade the `jdk`, solved.  too much machines to upgrade . Crying........

**Comment by dbwiddis** [comment]
Glad it got solved. :)
