### ISSUE TITLE
OSProcess calculateCpuPercent isn't recognized as a function

### ISSUE THREAD

**Issue by AwesomeDude091** [oshi/oshi#1778]
OSProcess calculateCpuPercent isn't recognized as a function, please help!

Here is my build.gradle:

`   implementation 'org.jetbrains:annotations:22.0.0'
    implementation 'commons-io:commons-io:2.11.0'
    implementation 'org.apache.commons:commons-collections4:4.4'
    implementation 'log4j:log4j:1.2.17'
    implementation 'com.github.oshi:oshi-core:5.8.3'`

**Comment by dbwiddis** [comment]
See the [UPGRADING](https://github.com/oshi/oshi/blob/8b9be87fba0b074790e31a19a82ecabbea71e8af/UPGRADING.md) document.

> The deprecated `OSProcess` method `calculateCpuPercent()` was removed, replaced by `getProcessCpuLoadCumulative()`.
