### ISSUE TITLE
I made a gadget that could be used as another demo project

### ISSUE THREAD

**Issue by rememberber** [oshi/oshi#1806]
I made a gadget that could be used as another demo project:
https://github.com/rememberber/MooInfo

**Comment by dbwiddis** [comment]
Wow!  Way cool!  Thanks for sharing!

**Comment by hazendaz** [comment]
@rememberber Looks awesome!  Definitely going to check that out!

**Comment by dbwiddis** [comment]
Added to the readme in https://github.com/oshi/oshi/commit/0baef91ec0b022ba6380356d9ad1c4971302885a

**Comment by dblock** [comment]
Super cool!
