### ISSUE TITLE
Unable to load library 'udev' 

### ISSUE THREAD

**Issue by Anonymenus** [oshi/oshi#1833]
The old issue.   https://github.com/oshi/oshi/issues/271 And I meet this problem again 

<img width="1271" alt="img_dev_001" src="https://user-images.githubusercontent.com/19319821/148033999-6c0f063c-54b7-417d-b703-e119933ae7fb.png">
<img width="1382" alt="img_dev_002" src="https://user-images.githubusercontent.com/19319821/148034003-532d67fa-be67-4c13-b0b7-ccef629329c7.png">

And  I found the same Version server with the lower  glibc, and it goes well
<img width="350" alt="屏幕快照 2022-01-04 下午4 47 42" src="https://user-images.githubusercontent.com/19319821/148034208-9465f958-3458-4a30-95e8-b244c357cbd9.png">

**Comment by mprins** [comment]
Not providing version and os information does make it virtually impossible to help you.

please read up on https://marker.io/blog/write-bug-report and amend your report

**Comment by dbwiddis** [comment]
1. The stack trace tells you your error: Native library (linux-x68-64/library.so) not found in resource path (... truncated so I can't see where it even looked...)
2. The problem occurs in the upstream JNA dependency. While I also support that project and am knowledgeable about errors like this, this is the wrong place to file this report, so I'm closing it here.

Please address your question to the jna-users mailing list: https://groups.google.com/g/jna-users although you may wish to search that mailing list for similar questions in the past.

When you ask on the JNA mailing list:
1. Please identify what operating system you are using.  You referencedd #271 implying CentOS; the solution is in that issue, install libudev.  If some other OS, do you have libudev installed?
2. If it is installed, where is it located?  Do not truncate the resource path search shown in your stack trace.  Screen captures are rarely helpful to others wanting to help you debug.

**Comment by Anonymenus** [comment]
ok ,thanks for your advise, I will address question to the jna, and no screen captures.
