### ISSUE TITLE
ARM Neoverse-N1

### ISSUE THREAD

**Issue by GilbertoKPL** [oshi/oshi#1843]
on an Oracle vps cloud with ARM Neoverse-N1 is returning empty cpu Identifier in linux.

I put 'Unknown' to represent the void.

![image](https://user-images.githubusercontent.com/73399601/148853851-e95d9534-235f-4d60-8aff-7d541862b63d.png)

**Comment by dbwiddis** [comment]
The "CPU Identifier" is generally specific to Intel chips, with a binary code encoding family, model, and stepping.

For other architectures, we've tried to put in any sort of consistent equivalent.  For ARM chips, that should be the MIDR.  

The output of your `/proc/cpuinfo` would allow me to identify why it's missing.
