### ISSUE TITLE
Can we remove maven-scm-plugin?

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1854]
So I found out elsewhere that Jgit 6 requires Java 11.

All well and good and I didn't do due diligence before merging #1807, which should have broken something in our build on JDK8.

But this didn't break any builds, so I dug into the pom to see where jgit is even used.  It's listed as a dependency of the `maven-scm-plugin`.

But we don't use any goals associated with that plugin, meaning it's only relevant for command-line usage.

But a scan of [the goals](https://maven.apache.org/scm/maven-scm-plugin/) doesn't show me anything that I can't do (better) in git (which Is, I suppose, the whole purpose of the plugin, as a front-end to do git commands from within the pom).

It got added way back in 2015 along with a lot of stuff brought over from waffle: https://github.com/hazendaz/oshi/blob/d2d02aba73eb914c39991fdd3a68de582bb6a479/pom.xml

So I looked over in waffle's pom and see it's unused there, too.  Some spelunking into history shows it may have been used with the `buildnumber-maven-plugin` back in the svn days for getting the latest commit id (from svn). But with the switch to git (see https://github.com/Waffle/waffle/pull/90) and the `git-commit-id-plugin` I think it's leftover stale code.

Can we remove it?  (By it, I mean `maven-scm-plugin`, `maven-scm-provider-jgit`, and `jgit`.)

**Comment by hazendaz** [comment]
Seems legit.  I was thinking off top of my head that it had something to do with site distribution but wagon-scm is doing that (we probably have wagon-git listed which is deprecated and now deleted from the 2.x milestone).  The scm data otherwise is inside release plguin so lets go for it and see on next release if any issues at all.  If not, then fully confirmed.

**Comment by dbwiddis** [comment]
Well, release today went off fine but it was insanely slow publishing the site.  Nearly 30 minute delay after these lines:
```
    [INFO] --- maven-site-plugin:3.10.0:deploy (default-deploy) @ oshi-core ---
    [INFO] Pushing /Users/danielwiddis/git/oshi/target/checkout/oshi-core/target/site
    [INFO]    >>> to github:ssh://oshi.github.io/oshi/oshi-core
```
Multiply by 4 for shaded, demo, and dist, and it was nearly a 2 hours process.

Don't know if that was jgit, or just something odd about github today.

**Comment by hazendaz** [comment]
Drop wagon-git (not a maven solution and abandoned now).  Maven wagon can handle this now.  (so long as not a super pom as it gets confused and not case with oshi).  Change wagon-ssh (deprecated and deleted in 2.0 milestone) to wagon-scm

Then change the extension to from wagon-ssh to wagon-scm.

'''
            <extension>
                <groupId>org.apache.maven.wagon</groupId>
                <artifactId>wagon-scm</artifactId>
                <version>${wagon.version}</version>
            </extension>
```

For properties, just drop the abandoned one and remove the -xxx from teh second one

```<wagon-git.version>2.0.3</wagon-git.version><!-- https://github.com/trajano/wagon-git/issues/18 -->
  <wagon-ssh.version>3.5.1</wagon-ssh.version>
```
to 
```
<wagon.version>3.5.1</wagon.version>
```

And make ```<url>github:ssh://oshi.github.io/oshi/</url>``` <url>scm:git:git@github.com:oshi/oshi.git</url> in ```<site>``` distribution.

Then test that by running 'mvn site' followed by 'mvn:deploy'.

**Comment by hazendaz** [comment]
In the URL that is replaced with you may have to make the colon a forwards slash. 

It seems to work fast on projects without super pom now without issue.  Problem I have is that I have a super pom used all over and it tries to use the super pom as location to create pom.  So what ends up happening for me is that it creates a site and tries to deploy but does so locatally as it is totally confused on where to go.  I'm hoping to figure that out soon.  So I'd say try above first then if forced to use slash instead of colon try that.  And see if that improves speed.

**Comment by dbwiddis** [comment]
Wouldn't it have been faster to make a PR than to type all those instructions? 😀

**Comment by hazendaz** [comment]
possibly but half on here and half on work and work is not working for me ;)  So trying to focus there.

**Comment by hazendaz** [comment]
@dbwiddis If you are trying to work this, I can do it now.  Was fighting a really dumb problem all night.  Had a dependency tree run to file and it kept blowing up on our CI.  Finally dawned on me to just run a build locally and truned out it was failing with missing lib.  So 5 hours later... :(

**Comment by dbwiddis** [comment]
I do have several browser tabs open looking at docs and the waffle pom for reference as well.  The one hitch in your instructions is our java11 release.

Currently the java11 site deployment goes to the same URL plus a /java11, see here:
https://oshi.github.io/oshi/java11/

So I'm not sure how to configure the distribution management as you have it with a .git extension.

**Comment by hazendaz** [comment]
ok - I can tackle this.  I don't have the same changes over in waffle yet.  I only learned about a week or two back that wagon-ssh was deprecated and I got off wagon-git a while back but its far from perfect and kind of wish I had not moved.  But I think I figured more out in last 48 hours.  The super pom problem has a fix from maven I had to back off as I use that in spotbugs maven plugin and it broke old artifactory instances.  So maybe its all good now in that situation too.  Since oshi doesn't have that situation this should work like it did for me on super pom I have setup.  its at hazendaz/base-parent.

I'm also thinking the dummy checks in site plugin to just track dependencies with versions plugin can be removed since we use dependabot and I think it auto updates extensions too.

**Comment by hazendaz** [comment]
There is one other thing that needs done to make it work.  If you see on waffle I likely noted site as gh-pages-scm, that is because I needed to support old and new given repos I have this in and the logic in settings.xml is different.

**Comment by hazendaz** [comment]
settings.xml

```
    <server>
      <id>gh-pages-scm</id>
      <configuration>
        <scmVersionType>branch</scmVersionType>
        <scmVersion>gh-pages</scmVersion>
      </configuration>
    </server>
```

**Comment by dbwiddis** [comment]
OK I'll let you handle it.

And we can probably just use the same URL. Originally I had it writing somewhere else because I was releasing the jdk8 build first and then java11, so the site would get overwritten.  But I've switched to doing the java11 first (should update releasing) so we can just leave the same gh-pages url and not worry that the java11 one gets published first as it'll be overwritten by the regular one.

**Comment by dbwiddis** [comment]
Or even better than same-url I can just remove the site deployment goal on the java11 side. :)

**Comment by hazendaz** [comment]
scm plugin agreed can go, there was no reason for that.  Its not used as you had noted.

scm though is used.  The maven documentation IMHO needs serious consideration on actually updating it so its not stating maven 2 as primary way to setup site distribution.  The '''<extenstion>``` is listed as primarly way to do it then a little note says, maven 3 users use the site plugin directly.  To me they could just delete maven 2, I've never even seen maven 2 used anywhere so its a bit odd to continue to document it.  That said, the slow build I see as well.  I updated a number of other unrelated things so I'll be bringing in some changes over next week or so.  I'm going to call it a night and just let this run then check in the morning to see how long it takes.  Not exactly sure why this is taking so long.  Waffle does too.  But I've never had others take so long.  Maven does seem to do things incredibly backwards here.

What I mean by that...you have to run the site first then deploy it so that is really mvn site followed by mvn site:deploy as far as I know.  So you have the site sitting in the target directory.  Wagon performs a checkout which looks like all immediately to Temp space.  It then appears to copy one file at a time to new location.  They even claim they do no cleanup of old stuff so it doesn't make any sense that they don't just copy recursvely, commit, and push.  That would take seconds not hours.  In fact, I'm pretty sure that is how the other plugin was working.  Also jgit provider doesn't work nor do they have it documented so I'm using git natively with the gitexe.  One would think just change with jgit to get that one but it then complains it doesn't know what git is.  I know they have been really improving this but it feels like its still quit a mess.  So I'll keep looking around as this has basically killed all my projects anyways that use a super pom and the solution they added does not resolve in IDEs properly nor work.  So maybe the answer is skip site on release, just run site and write a small script to do the real work which would resolve the entire issue much quicker.

On a side note, going to add a cache to the license plugin like we have in impsort and formatter.  It needs it badly, its far too slow to process.  It locks there everytime :(  But that is typical its the worst processing.

**Comment by dbwiddis** [comment]
Re-closing this issue. I tried implementing the scm plugin using your steps above and it was painful. I CTRL-C'd at some point.    The existing deployment doesn't take very long... may have just been super slow that day.
