### ISSUE TITLE
Use Maven Profiles for finer-grained control over releases

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1862]
We should switch our pom to use [Maven Profiles](https://maven.apache.org/guides/introduction/introduction-to-profiles.html) to help address several current workflows and issues we're trying to address with band-aid fixes.
1. JPMS release
2. Site publishing
3. Shaded JAR vs. JMPS conflicts

**JPMS.**  I decided against an MRJAR for the modular build, instead doing a full release of a separate project.  Initially I thought I might try to make some JDK11+ optimizations in the code, but eventually decided it wasn't worth the effort.  Right now it's essentially a clone of master with a few things changed in the POM files (for maven coordinates or site publishing) or removed from the POM (for compatibility or speed), plus the module descriptor and a related config file adding command lines for the test environment.  See this commit that basically sums up the differences:  https://github.com/oshi/oshi/commit/ff455f78a81b8f677357ed15b3e69bb4c974fa3b

One problem here is that my current approach (fork the master branch, apply the above commit, and regularly cherry-pick every other commit, occasionally restarting from a fresh fork) is manually intensive (with lots of silly conflict resolution in the cherry-picking). Another problem is that the Java11 SNAPSHOT doesn't get updated until I go through the above exercise.

All of this can be handled in the POM with profiles.  The incompatible or time-consuming plugins/goals (animal-sniffer) can be configured to only run on a jdk8 profile (the default) and we can streamline a jdk11 release by only including things necessary to publish the artifacts.  We can configure the snapshot deployment GHA to run both profiles sequentially.

**Site Publishing.**  I'll admit that I've never really used the site.   OK, not never.  Maybe once or twice.  It never made any sense to me that the reports on things to fix (PMD, Checkstyle, etc.) got published on a release... those are the things that should have been fixed *before* the release!  In any case, our Sonarqube integration and other code quality tools (LGTM, Scrutinizer, Sonatype-lift, Coverity, CodeQL) are pretty dang good at catching things, and I'm not sure any of the reporting is really that useful.

Now with #1819 there's an interest in reorganizing the documentation, and in fact our "site" now looks different.  But in my experience unless you have your own custom URL the place most people will visit is the README so it is the place that needs tuning up.  There are lots of things we could do (bumping stuff down into a single directory to make the content appear earlier, streamlining content with links to pages) to improve the site.  But that should be updated when there's a major change to the docs, not just on release.

Plus it's now become a painful part of the release:

> Not exactly sure why this is taking so long.  Waffle does too.  But I've never had others take so long.  Maven does seem to do things incredibly backwards here.
> 
> What I mean by that...you have to run the site first then deploy it so that is really mvn site followed by mvn site:deploy as far as I know.  So you have the site sitting in the target directory.  Wagon performs a checkout which looks like all immediately to Temp space.  It then appears to copy one file at a time to new location.  They even claim they do no cleanup of old stuff so it doesn't make any sense that they don't just copy recursvely, commit, and push.  That would take seconds not hours.  In fact, I'm pretty sure that is how the other plugin was working.  

_Originally posted by @hazendaz in https://github.com/oshi/oshi/issues/1854#issuecomment-1018287534_

We can just remove the site stuff from the regular profile and deploy it only when we want to (trigger the site GHA or push master to site branch I think does it).

**Shaded JAR.**

The thing that triggered the shaded jar incompatibility was an automatic module name, our first step toward JPMS support before actually making a modular release.  Since we have a full modular release with a full module descriptor, we could probably remove that, to see if that fixes the javadoc plugin issues.  (That will change the module name back to the default "oshi.core" but people shouldn't be using that, and perhaps that "breakage" will be a forcing function to switch to the correct artifact.  In fact, it may actually be Harmful™️ to have both; people can include `oshi-core` in a modular project now when they should be including `oshi-core-java11`.

This is one other thing we can do with the profiles, only do the `oshi-core-java11` release with the modular stuff, and put the rest of the "jdk8 support" release back into full "we don't talk about that" mode.

**Comment by dbwiddis** [comment]
PR #1864 implements the first idea above.  Unfortunately maven doesn't allow variables/substitutions in the artifact ID (the "Maven Way" is to use a classifier) but a wrapper script makes it simple.  Tested on snapshot deployments; it will be interesting to see if it works with the deploy plugin on the next release.

I did not change site publishing with this PR as that can/should be addressed separately (as in, not publishing the site on deploy at all).

**Comment by dbwiddis** [comment]
#3 implemented but not with profiles. I just killed the shaded jar. 

So we're down to #2, removing the site deployment from the build.  We already have a site publishing GHA we can use on demand.  We can even trigger it on the release commit if we want.  Do we need anything else?

**Comment by hazendaz** [comment]
I think given state of scm currently with behaviour that it makes sense to just use the github action for it.  From what I've seen that is fast and easy and just an extra push.  Github automatically turns around with a separate action and publishes it out so its clearly done.  So maybe that is just as good as it gets for now.
