### ISSUE TITLE
oshi 6.1.1 release: malformed pom files

### ISSUE THREAD

**Issue by retrofun** [oshi/oshi#1931]
gradle complains about
```
[Fatal Error] oshi-core-6.1.1.pom:4:10: Already seen doctype.
```
oshi-core-6.1.1.pom:

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE project>

    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

pom files of previous releases don't contain ```<!DOCTYPE project>```.

**Comment by dbwiddis** [comment]
Well I'm happy to remove those.  I put them in to get Eclipse to stop complaining but apparently it was the wrong solution....

**Comment by dbwiddis** [comment]
Fixing in #1933, will cut another release tonight
