### ISSUE TITLE
mac oshi Unable to load library 'IOKit': Native library (darwin/libIOKit.dylib) not found in resource path

### ISSUE THREAD

**Issue by spiritn** [oshi/oshi#1941]
SystemInfo si = new SystemInfo();
HardwareAbstractionLayer hardware = si.getHardware();
 UsbDevice[] usbDevices = hardware.getUsbDevices(false);
then log:
Unable to load library 'IOKit': Native library (darwin/libIOKit.dylib) not found in resource path

**Comment by dbwiddis** [comment]
What version of OSHI and JNA?

**Comment by dbwiddis** [comment]
See #1289
