### ISSUE TITLE
spotless misconfigured (minor issues - missing all possible files)

### ISSUE THREAD

**Issue by hazendaz** [oshi/oshi#1957]
I tried to use the spotless here as shown.  *.xml for example is incorrect.  That only will touch the root directory.  The <includes> is maven based type of includes.  Each that is *.xxx will need to be **/*.xxx to be accurate.  I didn't have time now to address as I'm working this at work but wanted to note it so its not forgotten.  Otherwise spotless worked out really well from what I can see.

**Comment by dbwiddis** [comment]
In #1902 it seemed to have no problem finding pom.xml files in subdirectories.

**Comment by hazendaz** [comment]
very odd, would not do that for me.  Looked at the `<includes>` tag which is maven baseda nd to go into sub directories it needs the **/.  I was testing this with pom files (made up ones in single subfolder) as well as shell scripts and yaml files.  Spotless did nothing but to the root pom.xml for me.  As soon as I added the **/*.xml (same with others), it suddenly worked.  It doesn't state that on their website so not entirely sure why the difference then.  I find it odd that it worked for one case but not another.  I tried 3 different projects before looking at other includes usage and seeing that other plugins all required **/ to get to all files so I did the same then it worked.  Well if it works then, I guess ok, but might not hurt to add that just in case.

**Comment by hazendaz** [comment]
I wonder if on pom.xml it was simply smarter if that was in modules to build.  The fake one for that file I tested I simply just made an unrelated directory.  I wasn't trying to really care about pom files as I use sortpom for those.  But I was curious about doing this with yaml, yml, and sh.  We have some nested setup and it was not reaching any of those until I did this.

**Comment by dbwiddis** [comment]
I’ll take a look tonight.  

Pom could have been same for as a module but it did get yaml files in .github and a java file buried deep in the subdirs…

**Comment by dbwiddis** [comment]
Also I got the idea from junit so I will investigate their config as well.

**Comment by dbwiddis** [comment]
OK, you're completely right here and I was confused.  

The `yml` files it got in #1902 were in the root directory, not `.github`.  (Which I discovered when troubleshooting and seeing lots of extra whitespace!)  It did get the subdirectory `pom.xml` files because that was the current directory when running that module, and the java version has a default includes of `src/main/java/**/*.java` (and the equivalent test path).

So I'll fix this up.

**Comment by hazendaz** [comment]
After further testing as well, some other notes.

- doesn't seem to understand multi-module build.  If you look at their defaults for java, they call out src folders.  That is rather typical as I don't think there is a good way otherwise but would be nice if it knew the modules and didn't do those directories by default when in wrong folder.  That is probably a maven 4 thing in concept.  Haven't seen a plugin that really handles that well (would need to know the module name and ignore it by default).  Just mentioning since this is multi module build.
- it hits target too.  In many cases that is ok and might be wanted.  In a case I had, we use makeself which creates a shell script.  This is in a multi module build, it is really a tar.gz as shell so it got really confused on that.

I don't think either issue is a problem that really exists with spotless.  It works well from what I've seen thus far.  I had a project of shell scripts and it was able to go flush trailing space and was rather quick.  So that was a plus.  For my needs, due to how it handled target and combination of makeself along with wanting a super pom, I had to error on side of caution and just drop target from processing.  Not a big deal.  Plugin is great otherwise and does so much :)

**Comment by dbwiddis** [comment]
I just realized I edited your comment instead of replying to it. It's been a long day.

**Comment by dbwiddis** [comment]
> doesn't seem to understand multi-module build.  If you look at their defaults for java, they call out src folders.  

I'm sure you can always just configure it in the module(s) with java code.  I don't think it hurts anything for our setup, though as those dirs don't exist.

> it hits target too.  

If you do **/* then yes. So perhaps a more targeted (pun intended) include? :)

> Plugin is great otherwise and does so much :)

Yeah, I've considered using it instead of the license plugin, too.  That's in the "too much work right now for too little marginal benefit" category.
