### ISSUE TITLE
CentralProcessor#getCurrentFreq returns wrong value on windows

### ISSUE THREAD

**Issue by Superice666** [oshi/oshi#1980]
As you know, many PC's CPU's are overclockable. This means that the actual CPU frequency can be greater than the maximum CPU frequency. But now OSHI use `percentMaxList.get(cpu) * maxFreq` to calculate frequency and that causes the wrong value.

**Comment by dbwiddis** [comment]
OSHI obtains it’s information from the frequency performance counters.  

Where in the windows API is the value you think OSHI should report instead?

**Comment by Superice666** [comment]
@dbwiddis Sorry, I have no ideas.

**Comment by dbwiddis** [comment]
As far as I’m aware, more accurate values than what is provided are chip-dependent and require machine language queries of the chip itself if they are supported. That’s not possible from Java. 

Frequencies are constantly changing with CPU load as well.  By the time you measure it, it is probably different. :)

**Comment by dbwiddis** [comment]
Closing this as I think #966 fully addresses why it can't be done.
