### ISSUE TITLE
how to check cpu occupancy of logical processors

### ISSUE THREAD

**Issue by kingkong3** [oshi/oshi#2014]
Nice to meet you.

I checked the NUMA number assigned to each processor through the logical processor.

But I need to check the CPU occupancy of each processor, but I don't know what to do.

Also, I checked and used "getProcessorCpuLoadBetweenTicks" through googling, but it doesn't work properly.

SystemInfo si = new SystemInfo(); 
CentralProcessor cpu = si.getHardware().getProcessor();

cpu.getProcessorCpuLoadBetweenTicks(cpu.getProcessorCpuLoadTicks());
==> print just 0.0 0.0 0.0 0.0 .... 

I would appreciate it if you could give me an answer.

**Comment by dbwiddis** [comment]
> I checked the NUMA number assigned to each processor through the logical processor.
> 
> But I need to check the CPU occupancy of each processor, but I don't know what to do.

You would use the same `LogicalProcessor` class and identify the physical processor number.  Logical processors sharing the same physical processor "occupy" the same CPU.    Note on some operating systems (e.g., Windows) there isn't a system generated number, so OSHI assigns one.  On others (e.g., Linux) the number is assigned by the system.

For example, this code:
```java
for (LogicalProcessor p : new SystemInfo().getHardware().getProcessor().getLogicalProcessors()) {
    System.out.println(p.toString());
}
```
generates this output on my system:
```text
LogicalProcessor [processorNumber=0, coreNumber=0, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=1, coreNumber=0, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=2, coreNumber=1, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=3, coreNumber=1, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=4, coreNumber=2, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=5, coreNumber=2, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=6, coreNumber=3, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=7, coreNumber=3, packageNumber=0, numaNode=0, processorGroup=0]
```
The `coreNumber` is the value of `getPhysicalProcessorNumber()`.  You can see logical processors 0 and 1 share a core (labeled 0), 2 and 3 share a core (labeled 1), etc.


> `cpu.getProcessorCpuLoadBetweenTicks(cpu.getProcessorCpuLoadTicks());`

You have to collect ticks over a timespan to measure this properly, e.g., 
```java
long[][] oldTicks = cpu.getProcessorCpuLoadTicks();
Thread.sleep(1000);
cpu.getProcessorCpuLoadBetweenTicks(oldTicks);
```

**Comment by kingkong3** [comment]
Thank you for your kind reply.

I'm curious about CpuLoadTicks.

Does it show each cpu load from the time of oldTicks until "cpu.getProcessorCpuLoadBetweenTicks(oldTicks);" is called?


And is the returned value the average value of the interval in the graph of the task manager?

![image](https://user-images.githubusercontent.com/23719336/165003685-754c1ff9-0a6e-447b-b841-34100c6a47b7.png)


Thank you for your reply.

**Comment by dbwiddis** [comment]
The "CpuLoadBetweenTicks" methods are entirely convenience calculations left over from earlier versions of OSHI.  

From a "raw data" standpoint, OSHI reports the "CpuLoadTicks" which are milliseconds idle, or non-idle (in various states).  Consider this simplified example:
> Time 0:00:00: Idle: 100, Active: 900
> Time 0:00:01: Idle: 300, Active: 1700

One second has elapsed.  During this time, the CPU was idle 200 ms of the time and active 800 ms of the time.  If you simply collected `getProcessorCpuLoadTicks()` at the two timestamps you could do this calculation yourself and you would get 0.8 (80% CPU load) as a result.    The "between ticks" calculation does this math for you.

With regard to your specific question:
 >  do you mean that 4% was used?

Yes, that would mean that if you added up the ticks difference between "oldTicks" and when you called the method, 96% of them would have been "idle" and the remaining 4% would have been either system, user, or one of the various other counters.

**Comment by kingkong3** [comment]
Thank you for your continued kind reply.

I actually couldn't understand a couple of things, so I'm writing an answer again

![image](https://user-images.githubusercontent.com/23719336/165049103-4c5301da-cb71-4997-80b2-ecf9f57fc5e1.png)

If you print out my server's Logical Processor, it looks like the picture above

By the way, I wonder if the INDEX of the array value returned through "cpu.getProcessorCpuLoadBetweenTicks(oldTicks);" is mapped to the processor number of the logical process

![image](https://user-images.githubusercontent.com/23719336/165049840-29dcb08f-40a9-4db5-b63d-c48ad93db1f5.png)

And I wonder if the numBer expressed in DOS window is the same numBer number expressed in Windows Task Manager


Once again... Please answer.

**Comment by dbwiddis** [comment]
Yes, the index in `cpu.getProcessor<anything>()` is going to match the same order as processors are printed out, so in your picture you have correctly labeled the values.

You have two physical packages, each of which is also a numa node.  Package 0 contains physical cores 0 thru 7. Each core has 2 logical processors; core 0 had LP 0 and 1, core 1 has LP 2 and 3, etc.   Package 1 is similar with cores 8-15. Core 8 has LPs 16 and 17, core 9 has LP 18 and 19, etc.

So CPU usage of core 1 is 1.6% on LP 0 and 1.57498...% on LP1.  The *nix standard is just to add those (so about 3.2%) but that's also referenced to a potential max of 3200%. Windows references to 100%, so you'd average them for a per-core output, or divide by the average 16 for a contribution to whole-system CPU.

With regard to Windows CPU numbering, it should be the same _order_.  The only difference with windows *might* be that it may re-start the numbering at 0 for a new NUMA node, e.g., for your output the "numa,logical" pairs in OSHI go 0,0; 0,1; 0,2; ... 0,15; 1,16; 1, 17; ... 1,31.  For Windows numbering it *might* go go 0,0; 0,1; 0,2; ... 0,15; 1,0; 1, 1; ... 1,15.  I don't have enough data on systems with multiple NUMA nodes to know that for sure.  How are yours numbered on the task manager?

**Comment by kingkong3** [comment]
Thank you for your continued kind reply.

umm... What does my number mean in Task Manager?

I didn't understand exactly, so I captured my task manager.

- CPU NUMA node graph on the Performance tab

![image](https://user-images.githubusercontent.com/23719336/165191152-0a5fb797-1bc0-4b69-af9d-5125e751c28b.png)

- The Processor Specification window that appears in Task Manager's Preference Settings.

![image](https://user-images.githubusercontent.com/23719336/165191216-11bbf0ff-e40c-4e8a-a166-d3f806eaf54e.png)
![image](https://user-images.githubusercontent.com/23719336/165191228-b8173c06-7d65-4ed0-9565-66959bf43aa7.png)

**Comment by dbwiddis** [comment]
Your Task Manager shows processors 0 thur 15 on both numa nodes 0 and 1.

The OSHI logical processors 16 through 31 on NUMA node 1 correspond to Task Manager processors 0 through 15.

The difference is in the way the "bitmask" is used internally in Windows to identify logical processor numbers.

**Comment by dbwiddis** [comment]
Your task manager graph for NUMA node 0 shows the CPU usage of all the NUMA node 0 logical processors (0 thru 15).  It would be the sum of the individual processor counts divided by 16.   The graph for NUMA node 1 is for the node 1 logical processors (16 thru 31, which Task Manager labels as 0 thru 15).

**Comment by kingkong3** [comment]
Wow, thank you for your quick reply.

I'm writing additional questions and I'm going to post them again because there's an answer.

Based on the above, when we calculated the CPU load every second and looked at the aggregation results by Numa, it seems that the result is the opposite of the NUMA number in the DOS window.

Data obtained through "cpu.getProcessor<anything>()" were aggregated by assigning 0-15 to NUMA 0 and 16-31 to NUMA 1 in the order of indexes.

![image](https://user-images.githubusercontent.com/23719336/165192329-ad1a1f2d-b1eb-4ebe-9788-725d6f608f61.png)

**Comment by dbwiddis** [comment]
OK, I see what you're reporting and I agree that it looks backwards between 0 and 1.  But there's a lot more to it, particularly with the task manager.

The numbering of the processors comes from the Windows API GetLogicalProcessorInformationEx.  This identifies logical processors which share physical processors and NUMA nodes but does not provide a "numbering" method.   There is a "group mask" which is a 64-bit value associated with Processor groups and we use that for the logical processor number 0 thru 63.

The usage stats come from the performance counters which use "instances" labeled by numa node and "logical processor" however it appears these reset to 0 when counting them up.

Because of the mismatch in numbers, OSHI doesn't try to line them up one for one.  But we do "sort" the lists by Numa node (first) and logical processor (second) to attempt to line them up.

One problem with the task manager is that it reports "work completed" while OSHI reports "time that a processor is not idle".  

Loading the performance monitor (perfmon.exe) and looking at the % Processor time for each processor and trying to align it with the Task Manager would be helpful.

**Comment by kingkong3** [comment]
Your kind reply was very helpful to me as a novice developer.

Thank you very much indeed.

If you have any questions about oshi in the future, can I post the question on the issue tab with a similar procedure?

**Comment by dbwiddis** [comment]
Of course... and if the processor numbering can be improved, happy to attempt to do that! :)

**Comment by kingkong3** [comment]
> Of course... and if the processor numbering can be improved, happy to attempt to do that! :)

You too!
