### ISSUE TITLE
Exception unexpected registry type 1, expected REG_DWORD

### ISSUE THREAD

**Issue by yaroslav4167** [oshi/oshi#2015]
### This problem similar: https://github.com/oshi/oshi/issues/2011
```
Your Hardware ID:
Stacktrace:
java.util.zip.Inflater.inflateBytes (null:-2)
java.util.zip.Inflater.inflate (null:-1)
java.util.zip.InflaterInputStream.read (null:-1)
sun.misc.Resource.getBytes (null:-1)
sun.misc.URLClassPath$JarLoader$2.getBytes (null:-1)
java.net.URLClassLoader.defineClass (null:-1)
java.net.URLClassLoader.access$100 (null:-1)
java.net.URLClassLoader$1.run (null:-1)
java.net.URLClassLoader$1.run (null:-1)
java.security.AccessController.doPrivileged (null:-2)
java.net.URLClassLoader.findClass (null:-1)
java.lang.ClassLoader.loadClass (null:-1)
sun.misc.Launcher$AppClassLoader.loadClass (null:-1)
java.lang.ClassLoader.loadClass (null:-1)
Main.main (Main.java:11)
Stacktrace end
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Create HWIDProvider instance: 228 ms
Bitness: 64, totalMemory: 34252374016(31,900 GB), battery true, TIME: 22 ms
Processors || logical: 16 physical 8 freq 2904000000, TIME: 58 ms
Exception in thread "main" java.lang.ExceptionInInitializerError
        at oshi.driver.windows.perfmon.PhysicalDisk.queryDiskCounters(PhysicalDisk.java:80)
        at oshi.hardware.platform.windows.WindowsHWDiskStore.queryReadWriteStats(WindowsHWDiskStore.java:244)
        at oshi.hardware.platform.windows.WindowsHWDiskStore.getDisks(WindowsHWDiskStore.java:181)
        at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getDiskStores(WindowsHardwareAbstractionLayer.java:76)
        at HWIDProvider.getHWDiskID(HWIDProvider.java:46)
        at Main.main(Main.java:27)
Caused by: java.lang.RuntimeException: Unexpected registry type 1, expected REG_DWORD
        at com.sun.jna.platform.win32.Advapi32Util.registryGetIntValue(Advapi32Util.java:1149)
        at com.sun.jna.platform.win32.Advapi32Util.registryGetIntValue(Advapi32Util.java:1120)
        at com.sun.jna.platform.win32.Advapi32Util.registryGetIntValue(Advapi32Util.java:1095)
        at oshi.driver.windows.perfmon.PerfmonDisabled.isDisabled(PerfmonDisabled.java:63)
        at oshi.driver.windows.perfmon.PerfmonDisabled.<clinit>(PerfmonDisabled.java:44)
        ... 6 more
```
### **Registry:**
![image](https://user-images.githubusercontent.com/18057310/164510502-b36b2950-7602-4788-bce1-384a8256e93b.png)
![image](https://user-images.githubusercontent.com/18057310/164510552-4174c477-9696-4d99-b86d-c5db0fea4fe5.png)
![image](https://user-images.githubusercontent.com/18057310/164510576-f573cc07-4edb-4bce-80e4-aabd48af26df.png)

**System:** Windows 10 (21H2 19044.1645)

**CCleaner version:** 5.91.9537

**OSHI:** 6.1.6
**JNA:** 5.11.0

**Comment by dbwiddis** [comment]
See the top image with the PerfOs registry path.

The fifth key down "Disable Performance Counters" is type `REG_SZ` (null delimited string).  That is what is causing the error.  Change that value to type `REG_DWORD`, or simply delete it.

![image](https://user-images.githubusercontent.com/9291703/164515397-43d5b890-3f79-41d2-8477-8330a91e28e4.png)

**Comment by yaroslav4167** [comment]
Maybe this can be fix in the oshi?  This problem has already happened to several people.  and I'm talking about those who only informed me.

**Comment by dbwiddis** [comment]
> Maybe this can be fix in the oshi? This problem has already happened to several people. and I'm talking about those who only informed me.

I was already working on that in #2016 ... note this isn't "fixing" the invalid values, it's just ignoring them.

OSHI isn't causing the problem here, it's just detecting a bug in some other software.  Those encountering this problem should find out what software they're using that's setting the invalid registry value.

**Comment by dbwiddis** [comment]
Here's a completely different software crashing on the same error.  It would be helpful if whatever third party software is corrupting the key got fixed.  https://www.den4b.com/forum/viewtopic.php?id=2477

**Comment by dbwiddis** [comment]
Of note you can work around the problem by explicitly setting in the config that the counters are not disabled:
```
GlobalConfig.set(GlobalConfig.OSHI_OS_WINDOWS_PERFOS_DIABLED, false);
GlobalConfig.set(GlobalConfig.OSHI_OS_WINDOWS_PERFPROC_DIABLED, false);
GlobalConfig.set(GlobalConfig.OSHI_OS_WINDOWS_PERFDISK_DIABLED, false);
```
