### ISSUE TITLE
Machine Agent: Unable to see process related data for Windows Server in the logs

### ISSUE THREAD

**Issue by RajeshBabuJangili** [oshi/oshi#2027]
Hi Daniel, please check below details and help me to resolve this problem...

•	The customer is using Windows Server 2016 and MA version 21.12.6 which consists of the OSHI version 5.7.4
•	The latest MA 22.3 also uses OSHI version 5.7.4
•	In the logs, we're seeing empty processes and perfProcesses due to which unable to see process-related data in the controller 
        UI

{log}
vvhn2159==> [extension-scheduler-pool-2] 30 M‰r 2022 10:55:28,550 DEBUG WindowsRawCollector - OSHI output (processes): {} 
vvhn2159==> [extension-scheduler-pool-2] 30 M‰r 2022 10:55:28,550 DEBUG WindowsRawCollector - OSHI output (perfProcesses): {} 
vvhn2159==> [extension-scheduler-pool-2] 30 M‰r 2022 10:55:28,550 DEBUG WindowsRawCollector - OSHI OSProcess cache: empty
{log}

•	Provided customer a custom build, this included the same logic as the machine agent uses to fetch the process-related data
•	Upon executing MAWindowsCustomBuild-1.0.jar which uses OSHI 5.7.4 as expected we saw an empty process and perfProcess 
        data.
•	Hence, provided another custom build MAWindowsCustomBuild-2.0.jar which uses OSHI 6.1.6, and using this we were able to 
        see the process and perfProcess data.
•	While using OSHI 5.7.4, in the above code, we use os.getProcess(0, null) where the limit is 0 and sort is null
•	In the case of OSHI 6.1.6, os.getProcesses(limit, sort) is deprecated and consists 3 parameters limit, sort, and filter (newly 
        added) 
•	List<OSProcess> getProcesses(Predicate<OSProcess> filter, Comparator<OSProcess> sort, int limit);
•	In MAWindowsCustomBuild-2.0.jar, I have used the limit as 0 itself, sort as null itself, and filter as null 

•	customer wants metrics using OSHI and not sigar
machine agent is currently using OSHI 5.7.4 and we're not seeing process-related metrics in the logs
hence, in build 1 with OSHI 5.7.4 it returned empty process output
in build 2 with OSHI 6.1.6 we're able to see process-related output

Please let me know if you need any other information.

Regards,
Rajesh

**Comment by dbwiddis** [comment]
I'm not sure what the question here is.    It appears something is broken in some earlier version but that's almost a year old (5.7.4 was released in May 2021, and there have been 441 commits since then.). 

It appears that things seem to work in the current 6.1.6 version.   

There's nothing I can do to change earlier versions that have been released, and the bug appears fix, so what action is requested here?

**Comment by dbwiddis** [comment]
Hi @RajeshBabuJangili, checking in on this issue.  From what I understand, the current version works for you.   I'm closing this issue assuming there's nothing else I can do.  If you have a specific ask, feel free to re-open it.
