### ISSUE TITLE
[Mac] OperatingSystem.getProcesses doesn't return kernel_task

### ISSUE THREAD

**Issue by mgroth0** [oshi/oshi#2038]
I'm trying to develop an alternative to Activity Monitor and this library is proving essential, but there is an issue.

When I sort Activity Monitor by "% CPU", `kernel_task` is often at the top. But when I run `os.getProcesses(null, OperatingSystem.ProcessSorting.CPU_DESC, 10)`, `kernel_task` is never in the list.

Is `kernel_task` a special kind of process that oshi can't access? Or is there a way I can get it?

OS: Mac 12.3.1
oshi: 6.1.6

**Comment by dbwiddis** [comment]
Are you running with elevated permissions?

**Comment by dbwiddis** [comment]
OK, two things here.

First, without elevated permissions, OSHI will only see its own processes.

Second, it looks like PID 0 (kernel_task) is explicitly excluded from the list.  This is probably a mistake, and I'm not sure why I left it like that.

https://github.com/oshi/oshi/blob/356942e1974ba7d7cd824f64175ca06001411928/oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java#L182-L183

**Comment by dbwiddis** [comment]
Seems I put in the "don't use PID 0" in response to https://github.com/oshi/oshi/issues/395

But it works now and it seems the underlying error (allocating array size) fixed the problem.  So this check for 0 can just be removed.
