### ISSUE TITLE
Missing child processes in OperatingSystem#getChildProcesses

### ISSUE THREAD

**Issue by marcelkliemannel** [oshi/oshi#2053]
Hi,

I'm using version 6.1.6 on a Mac and trying to get all child processes via `oshi.software.os.OperatingSystem#getChildProcesses`. 

My problem is, that I don't get all children I would expect (e.g., in comparison to a run of `pgrep -P $parentPID` in the terminal). And I don't know if this is a bug or if I misunderstand something about the method entirely.

What I do not quite understand is the following line:
https://github.com/oshi/oshi/blob/356942e1974ba7d7cd824f64175ca06001411928/oshi-core/src/main/java/oshi/software/common/AbstractOperatingSystem.java#L119
The idea here is (as far as I understand) that we have a list containing both the parent process and all of its children, and the stream is supposed to extract the parent process from this list. But the filter will never find the parent process because it is looking for a process whose parent PID matches the parameter `parentPid`. And such a process will always be a child process but never the actual parent process. Therefore, should it not be `filter(p -> p.getProcessID() == parentPid)`?

The problem with a wrong select `parent` is the incorrect `parentStartTime` used for the filter in the following line:
https://github.com/oshi/oshi/blob/edbc60f4456307b9efa217fed6b7d6a6794bb4b2/oshi-core/src/main/java/oshi/software/common/AbstractOperatingSystem.java#L125
If child processes have been running longer than the selected `parent`, those are filtered out here. But since `parent` is not the actual parent, some children may be missing in the end result (which would be included if the correct start time would be used).

Below is a screenshot from a breakpoint in the method, which I called via `getChildProcesses(5265, null, ProcessSorting.NO_SORTING, 0)`:
<img width="634" alt="Screen Shot 2022-06-04 at 20 03 23" src="https://user-images.githubusercontent.com/3964073/172019986-492a49dd-674f-45c2-916e-ca883bd937a4.png">

As you can see, the selected `parent` is a child process and not a process for the `parentPid` parameter.

**Comment by dbwiddis** [comment]
> Therefore, should it not be `filter(p -> p.getProcessID() == parentPid)`?

You are absolutely correct.  Currently it's returning one of the children.

Can you submit a PR to fix that?
