### ISSUE TITLE
Can the usage of each core of a multi-core CPU be obtained?

### ISSUE THREAD

**Issue by ZQ-starry** [oshi/oshi#2067]
It is now known that the OSHI tool can obtain the utilization rate of the CPU, but can this tool obtain the utilization rate of each core of a multi-core CPU?

**Comment by dbwiddis** [comment]
The `CentralProcessor` API includes `getSystemCpuLoadTicks()` (and `getSystemCpuLoadBetweenTicks()`) for system-level statistics, and `getProcessorCpuLoadTicks()` (and `getProcessorCpuLoadBetweenTicks()`) for similar values at the logical processor level.   Other methods expose the processor topology so you could roll up to physical core, physical package/socket, or NUMA node if you desired.

**Comment by ZQ-starry** [comment]
So，getProcessorCpuLoadTicks() (and getProcessorCpuLoadBetweenTicks()) . Can these two methods help me to read the CPU's usage per logical processor?

**Comment by dbwiddis** [comment]
Yep.  :) 

![image](https://user-images.githubusercontent.com/9291703/173479659-e9b589f5-ec1f-45d6-aea8-5d4366a12c0e.png)

**Comment by ZQ-starry** [comment]
Do you have a sample program to obtain the Processor Cpu usage in the figure?

**Comment by dbwiddis** [comment]
The above is in the `oshi-demo` project as part of the GUI. That's the [`ProcessorPanel`](https://github.com/oshi/oshi/blob/master/oshi-demo/src/main/java/oshi/demo/gui/ProcessorPanel.java).

Here's code for the system CPU load, just change "system" to "processor" and output the arrays:

```
    public static void main(String[] args) {
        SystemInfo systemInfo = new SystemInfo();
        HardwareAbstractionLayer hardwareAbstractionLayer = systemInfo.getHardware();
        CentralProcessor centralProcessor = hardwareAbstractionLayer.getProcessor();
        final long[] cpuPrevTicks = centralProcessor.getSystemCpuLoadTicks();
        Timer timer = new Timer(1000, e -> {
            System.out.println("CPU Load: " + centralProcessor.getSystemCpuLoadBetweenTicks(cpuPrevTicks));
            long[] ticks = centralProcessor.getSystemCpuLoadTicks();
            for (int i = 0; i < cpuPrevTicks.length; i++) {
                cpuPrevTicks[i] = ticks[i];
            }
        });
        System.out.println("Startup Done!");
        timer.start();
    }
```
Output:
```
Startup Done!
CPU Load: 0.0633315593400745
CPU Load: 0.026282853566958697
CPU Load: 0.024299065420560748
CPU Load: 0.02862476664592408
...
```

_Originally posted by @dbwiddis in https://github.com/oshi/oshi/issues/1326#issuecomment-683316188_
