### ISSUE TITLE
Negative/Wrong CPU (G)Hz values for OCPU

### ISSUE THREAD

**Issue by Osiris-Team** [oshi/oshi#2079]
One of my users gets negative CPU GHz values:
Current CPU GHz: -1.0E-9 
CPU max GHz: -1.0E-9 

His system details:
[23-06-2022 19:33:04][AP][DEBUG][Main] DEBUG DETAILS:
[23-06-2022 19:33:04][AP][DEBUG][Main] SYSTEM OS: Linux
[23-06-2022 19:33:04][AP][DEBUG][Main] SYSTEM OS ARCH: aarch64
[23-06-2022 19:33:04][AP][DEBUG][Main] SYSTEM VERSION: 5.4.17-2136.307.3.5.el8uek.aarch64
[23-06-2022 19:33:04][AP][DEBUG][Main] JAVA VERSION: 17.0.1
[23-06-2022 19:33:04][AP][DEBUG][Main] JAVA VENDOR: Oracle Corporation https://java.oracle.com/
[23-06-2022 19:33:04][AP][DEBUG][Main] WORKING DIR: /home/opc

Issues happen on latest oshi snapshot and on 6.0.0.

The way I am retrieving cpu info (works perfectly on my system and many others) is like this:
```java
            //...
            float oneGigaHertzInHertz = 1000000000.0f;
            SystemInfo si = new SystemInfo();
                    while (true) {
                        // Hardware info:
                        HardwareAbstractionLayer hal = si.getHardware();
                        CentralProcessor cpu = hal.getProcessor();
                        GlobalMemory memory = hal.getMemory();
                        // Calc average frequency in mhz
                        long currentFrq = 0;
                        int i = 0;
                        if (cpu != null) {
                            for (long frq :
                                    cpu.getCurrentFreq()) {
                                currentFrq = currentFrq + frq;
                                i++;
                            }
                            currentFrq = currentFrq / i;
                        }

                        if (cpu != null) {
                            dos.writeFloat((cpuSpeed = (currentFrq / oneGigaHertzInHertz)));
                            dos.writeFloat((cpuMaxSpeed = (cpu.getMaxFreq() / oneGigaHertzInHertz)));
                            dos.writeByte((cpuUsage = (byte) Math.round(cpu.getSystemCpuLoad(1000) * 100)));
                        } else {
                            dos.writeFloat(0);
                            dos.writeFloat(0);
                            dos.writeByte((byte) 0);
                        }
                        //...
                   }
```
There are no exceptions thrown anywhere.

**Comment by Osiris-Team** [comment]
Just found out that the dude has an OCPU (https://blogs.oracle.com/cloud-infrastructure/post/vcpu-and-ocpu-pricing-information)

**Comment by Osiris-Team** [comment]
Regular linux commands to show cpu speed information simply don't work for that one....

**Comment by dbwiddis** [comment]
How about the contents of `/sys/devices/system/cpu/cpuN/cpufreq/scaling_cur_freq` or `/sys/devices/system/cpu/cpuN/cpufreq/cpuinfo_cur_freq`?  (Replace N with core #.)

is there a similar `ocpu` entry on the syspath?

How about `/proc/cpuinfo`?

Looks like there are instructions [here](https://support.oracle.com/knowledge/Oracle%20Linux%20and%20Virtualization/2104337_1.html) behind a paywall.

**Comment by dbwiddis** [comment]
Also `lshw -class processor`

**Comment by Bitslayn** [comment]
I tried accessing their support page with my oracle accounts though I wasn't allowed access. Checking back at the email I got when creating the server, it stated "You have been associated to a cloud subscription and granted access to a Support Identifier for Oracle Support." but never actually had the identifier in the email. I'm assuming this is due to the fact I own a free server through a trial rather than paying for a premium service.

**Comment by Bitslayn** [comment]
> How about the contents of `/sys/devices/system/cpu/cpuN/cpufreq/scaling_cur_freq` or `/sys/devices/system/cpu/cpuN/cpufreq/cpuinfo_cur_freq`? (Replace N with core #.)
> 
> is there a similar `ocpu` entry on the syspath?
> 
> How about `/proc/cpuinfo`?
> 
> Looks like there are instructions [here](https://support.oracle.com/knowledge/Oracle%20Linux%20and%20Virtualization/2104337_1.html) behind a paywall.

I'll look at those directories to see what I can find

**Comment by Bitslayn** [comment]
```[opc@minecraft-server ~]$ cd /sys/devices/system/
clockevents/ clocksource/ container/   cpu/         edac/        memory/      node/
[opc@minecraft-server ~]$ cd /sys/devices/system/cpu/cpu
cpu0/    cpu1/    cpu2/    cpu3/    cpufreq/ cpuidle/
[opc@minecraft-server ~]$ cd /sys/devices/system/cpu/cpu0/
driver/        hotplug/       power/         subsystem/
firmware_node/ node0/         regs/          topology/
[opc@minecraft-server ~]$ cd /sys/devices/system/cpu/cpufreq/
[opc@minecraft-server cpufreq]$ tree
.

0 directories, 0 files

**Comment by Bitslayn** [comment]
> Also `lshw -class processor`

```
[opc@minecraft-server ~]$ sudo lshw -class processor
  *-cpu
       description: CPU
       vendor: QEMU
       physical id: 400
       bus info: cpu@0
       version: virt-4.2
       slot: CPU 0
       size: 2GHz
       capacity: 2GHz
       configuration: cores=4 enabledcores=4 threads=1
```

**Comment by dbwiddis** [comment]
It should have seen the `capacity:` line in the `lshw` command.  Of course, that requires elevated permissions.

**Comment by dbwiddis** [comment]
Actually, the `lshw` is in the max frequency.   

Bottom line:  The javadocs note that this method is an "attempt", and the information is not always available or requires installation of a package.  If you can find anywhere in the target system where the information is available that OSHI does not already check, I'd be happy to add it.  Otherwise it's probably good to code up a fallback assumption that the "vendor frequency" is the best guess.

**Comment by Bitslayn** [comment]
I was able to find this resource https://docs.oracle.com/en/learn/system_monitoring_linux8/index.html#introduction I'll see if this works and message back

**Comment by Bitslayn** [comment]
https://docs.oracle.com/en/industries/communications/session-border-controller/8.4.0/mtg/platform-information.html#GUID-18D89C7A-EEE0-43EE-99C8-FAAFB3790E02

**Comment by dbwiddis** [comment]
Looks like `show platform cpu` just gives the nominal speed of the CPU, same as OSHI's "Vendor frequency".

**Comment by dbwiddis** [comment]
Closing this as it doesn't seem to be supported.
