### ISSUE TITLE
Remove useless public constructor for abstract class

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#2096]
### First Timers Only

I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a Pull Request (PR) for this one from someone who's never contributed to an open source project on GitHub before.

The main goal of this task is to learn the process for submitting a PR -- the GitHub equivalent of writing a "Hello World!" program.  If you already know the PR workflow, please leave this issue for someone else!

This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. 😄 

### The change you are making 

Abstract classes should not have public constructors.

In the `AbstractInternetProtocolStats` class, there is an unnecessary `public` constructor, probably left over from a copy/paste operation.
https://github.com/oshi/oshi/blob/edbc60f4456307b9efa217fed6b7d6a6794bb4b2/oshi-core/src/main/java/oshi/software/common/AbstractInternetProtocolStats.java#L36-L38

It should be either made `protected` or, in this case, since it accomplishes nothing, simply removed.

### What to do 

Remove the constructor. 

### How to submit your change to the repository

Here are the steps to get a PR merged here.
- Read the [Contributing](https://github.com/oshi/oshi/blob/master/src/site/markdown/Contributing.md) file for reference.  We'll follow those steps, and I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- Make the changes described above.
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

**Comment by victorjbassey** [comment]
@dbwiddis  I want to take this. But the link to the CONTRIBUTING file returns a 404

**Comment by dbwiddis** [comment]
All yours!  

And sorry, redid the site a few months ago.  New location is here:  https://github.com/oshi/oshi/blob/master/src/site/markdown/Contributing.md

**Comment by dbwiddis** [comment]
Fixed in #2099
