### ISSUE TITLE
Private methods that don't access instance data should be static

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#2105]
### First Timers Only

I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a Pull Request (PR) for this one from someone who's never contributed to an open source project on GitHub before.

The main goal of this task is to learn the process for submitting a PR -- the GitHub equivalent of writing a "Hello World!" program.  If you already know the PR workflow, please leave this issue for someone else!

This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. 😄 

### The change you are making 

In the `LinuxCentralProcessor` class, there are two methods which fetch system topology as part of initializing the class.
https://github.com/oshi/oshi/blob/78ad16237985994cb21ef89248f715f2353f6968/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java#L195
and
https://github.com/oshi/oshi/blob/78ad16237985994cb21ef89248f715f2353f6968/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java#L228

Neither method accesses or alters the state of the object, and thus should be made `static`.

### What to do 

Add the `static` keyword to the above two methods.

### How to submit your change to the repository

Here are the steps to get a PR merged here.
- Read the [Contributing](https://github.com/oshi/oshi/blob/master/src/site/markdown/Contributing.md) file for reference.  We'll follow those steps, and I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- Make the changes described above.
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

**Comment by DennisPersaud** [comment]
Hello Daniel, I'm going to give this a shot.
