### ISSUE TITLE
Use vmactions GitHub action for solaris x86 test

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#2117]
We've been using a `vmactions` GitHub Action for Freebsd for a while.  They've recently added support for more operating systems!  The OpenBSD test was just updated in #2116, allowing me to shut down the OpenBSD VM at my house.  Now I just have a Solaris VM running there...

But we can shut that one down too with the Solaris GHA here: https://github.com/vmactions/solaris-vm 

Let's keep the existing SPARC test but replace the x86 test with the above.

**Comment by SalvadorRomo** [comment]
Hi Can I work on this? I'm a Software Engineer, and  I'm a big fan of this library beacuse in my last postion I pushed it to use it to  an a alternative of sblim-sfcb( cim broker) beacause that product in which I implemented it was about to get Hadware and Software Info.  Regards!!

**Comment by dbwiddis** [comment]
Hey @SalvadorRomo, great to hear you're a fan.  By all means, please feel free to take this on!  Holler if you need any help.

**Comment by SalvadorRomo** [comment]
Great, Thks a lot. Sure! I will start working on this staring this Monday.

**Comment by dbwiddis** [comment]
OK, thi

**Comment by dbwiddis** [comment]
So it's not working.... tail end of the log shows
```
OK, Ready!
envs:
Running prepare: pkg_add curl
pkg_add maven
/usr/bin/ssh -t solaris
Pseudo-terminal will not be allocated because stdin is not a terminal.
Last login: Mon Jul 18 20:57:34 2022 from 10.0.2.2
Oracle Corporation	SunOS 5.11	11.4	Aug 2018
-bash: line 1: pkg_add: command not found
-bash: line 2: pkg_add: command not found
Error: The process '/usr/bin/ssh' failed with exit code 127
```
Looks like the Solaris syntax is `pkgadd` without the underscore.   I think that's the source of the exit code 127.

**Comment by dbwiddis** [comment]
Yeah, but I'm not sure we need those packages.  We can use the maven wrapper so we don't need maven, and I'm not sure curl is needed either.  I'm playing around with some settings, you can focus on the JMX stuff :)

**Comment by dbwiddis** [comment]
Well, progress.  The maven wrapper is running. But there is no JDK installed, hahaha.... working on it

**Comment by dbwiddis** [comment]
Finallly got it all working, but the test takes 30 minutes after all the loading of the VM, downloading a compatible JDK, and running tests -- which fail on no partitions.  I'm just going to revert to the test I was doing on my Synology. :|
