### ISSUE TITLE
Need help to understand the cause of NPE

### ISSUE THREAD

**Issue by techpavan** [oshi/oshi#2132]
Team,

In one of the environments, we encountered the below exception. This was a one off case amongst too many successful deployments. Thus, there is no reproducer. Needed your help in understanding what could be the cause of this so that we know steps to avoid / resolve this.

```
Caused by: java.lang.NullPointerException
	at oshi.software.os.linux.LinuxNetworkParams.getDomainName(LinuxNetworkParams.java:80) ~[oshi-core-6.0.0.jar!/:6.0.0]
```

**Comment by dbwiddis** [comment]
That stack trace points to the last of these lines:
https://github.com/oshi/oshi/blob/d198e972f8d5d9fcfdec8868462df591e6bffc02/oshi-core/src/main/java/oshi/software/os/linux/LinuxNetworkParams.java#L71-L80

I don't think it's possible for `info` to be null there, so `ai_canonname` must be.

The [docs](https://man7.org/linux/man-pages/man3/getaddrinfo.3.html) for the structure say:
> If hints.ai_flags includes the AI_CANONNAME flag, then the ai_canonname field of the first of the addrinfo structures in the returned list is set to point to the official name of the host.

In this case it appears that has returned a null pointer in the structure for some reason, so we should add a null check here.

**Comment by techpavan** [comment]
Thanks a lot for a very fast turn around. You made the change and even released it within few hours of reporting. And I checked that this `ai_canonname` is not referenced anywhere else and hence the null check that's added should be sufficient.

BTW, this fix is actually a safety net, but the `null` came up because the environment was not setup properly. Are there any commands or steps to analyze why the null occurred at first? That should help understand issue with environment and probably a way to avoid in future.

**Comment by techpavan** [comment]
Thanks again. Will try to obtain the outputs and compare against the working ones.
