### ISSUE TITLE
Turn off file not found or not readable messages off globally.

### ISSUE THREAD

**Issue by MikeyCarter** [oshi/oshi#2149]
Not running this java package as root so this is expected.... how do I turn off these warnings?   Can't see the forest for the trees.

```
2022-07-29 13:33:25.188+0000 [id=6654]	WARNING	oshi.util.FileUtil#readAllBytes: File not found or not readable: /proc/2046861/environ
2022-07-29 13:33:25.249+0000 [id=6654]	WARNING	oshi.util.FileUtil#readAllBytes: File not found or not readable: /proc/1999/environ

```

**Comment by dbwiddis** [comment]
> how do I turn off these warnings?

Your logging platform should have the ability to change log warning level by class.  Change the level for the FileUtil class to ERROR.

You could also avoid calling `getEnvironmentVariables()` on your `OSProcess` objects if the process owner isn't the same as the current process.

Finally, the FileUtil.readAllBytes() takes an optional boolean argument whether to log failures (defaults true).  You could replace calls in OSHI to `OSProcess.getEnvironmentVariables()` with your own similar method to the below, but adding `false` as an additional argument.
https://github.com/oshi/oshi/blob/210d54ee711a4153d569410a914bdd68e4c1564d/oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java#L145-L148
