### ISSUE TITLE
Update JUnit EnabledOnOS for OpenBSD and FreeBSD

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#2154]
In JUnit 5.9, the `@EnabledOnOS` annotation was expanded to include OpenBSD and FreeBSD.

We have a few tests still using the `OS.OTHER` enum which now actually excludes testing on those platforms.

Tests using `OS.OTHER` should use the appropriate `OS` enum, and the `Platform.is*BSD()` conditional removed.  For example,
```java
@EnabledOnOs(OS.OTHER)
class DiskDriversTest {
    @Test
    void testDiskDrivers() {
        if (Platform.isFreeBSD()) {
```
should be changed to
```java
@EnabledOnOs(OS.FREEBSD)
class DiskDriversTest {
    @Test
    void testDiskDrivers() {
```
[FreeBSD Tests](https://github.com/oshi/oshi/search?q=isFreeBsd)

[OpenBSD Tests](https://github.com/oshi/oshi/search?q=isOpenBsd)

**Comment by raysonkoh** [comment]
Hi @dbwiddis, I am interested in working on this issue, if it is still up for grabs. :)
