### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: Unable to load library 'udev':

### ISSUE THREAD

**Issue by amnoah** [oshi/oshi#2172]
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: Unable to load library 'udev':

Full error: https://paste.plox.host/ekiqaqebeb.sql
Full code: https://pastebin.com/jY4LTNZk

**Comment by dbwiddis** [comment]
The stack trace points to line numbers for a 6.1.x or earlier version of OSHI:

> [22:30:32] [AWT-EventQueue-0/WARN]:     at oshi.hardware.platform.linux.LinuxHWDiskStore.getDisks(LinuxHWDiskStore.java:168)
> [22:30:32] [AWT-EventQueue-0/WARN]:     at oshi.hardware.platform.linux.LinuxHWDiskStore.getDisks(LinuxHWDiskStore.java:159)

This exception is caught as of #2034 which went in as part of OSHI 6.2.0.

You are running in a container without udev:
> /home/container/bundler

While OSHI no longer throws the exception, you will also not get certain information such as disks.  This is fine if you're not retrieving that information; otherwise consider adding the udev dll to your container.

**Comment by amnoah** [comment]
I'm not using 6.1.x... so that is odd. In specific I'm using version 6.2.2. 
Here is my dependency declaration from my pom.xml.

```   <dependencies>
        <dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>
            <version>6.2.2</version>
        </dependency>
    </dependencies>

**Comment by dbwiddis** [comment]
You may have a different version in a transitive dependency.  What does `mvn dependency:tree` tell you?

In #2092 apparently an older Spring Boot caused the issue.

**Comment by amnoah** [comment]
Full paste: https://pastebin.com/jg3W6Drn

**Comment by dbwiddis** [comment]
Well, that's odd.  

Line numbers in JNA point to a pre-5.12.1 version as well, they match `NativeLibrary` between July 2020 and May 2022, so 5.7 thru 5.11.

What are the dependencies of the wrapper code you're running around your own?

**Comment by dbwiddis** [comment]
Are you using a parent pom?

**Comment by dbwiddis** [comment]
I see you closed this so I assume it was resolved. To help others, care to share what configuration was causing the issue?

**Comment by amnoah** [comment]
> I see you closed this so I assume it was resolved. To help others, care to share what configuration was causing the issue?

I'm not exactly sure if I was able to fix it or not - the user who reported it had a very specific use case scenario that I'm unable to reproduce.
I closed the issue as I cannot reproduce it myself and I also do not currently have the time to handle the issue report properly.

**Comment by dbwiddis** [comment]
> Yes, I am. I can provide the pom to all of my modules and the parent if need be.

A parent pom's dependencies may take precedence over their own declared dependencies.  This was a problem with the Spring Boot Starter Parent for some time.

Investigate the parent pom for oshi and/or JNA dependencies.  If they are defined with a version property, override that version property in the user's POM.

**Comment by dbwiddis** [comment]
Also while the newest version will catch the exception, it won't give the hardware info. The user [should install libudev](https://pkgs.alpinelinux.org/package/edge/main/x86_64/eudev-dev).

**Comment by amnoah** [comment]
The parent pom has no dependencies whatsoever. None of the modules have any dependency overlap so I use the parent pom to just declare them.
Parent pom: https://gist.github.com/amnoah/c14c48aea3fc943ea15a0c24a89f2543

**Comment by dbwiddis** [comment]
Given the POM definitions shown, this is impossible to reproduce. The only other thing I can think of is older/cached versions somewhere.  Without direct access to troubleshoot why versions aren't being updated, I can only guess.

The advice to install libudev (in the container) still applies.

**Comment by amnoah** [comment]
Yeah... I'll pass that along to them.

Thank you for all of your help and time.
