### ISSUE TITLE
The results returned by getFileStores are repeated and the size is the same, in the docker swarm environment

### ISSUE THREAD

**Issue by zjjay** [oshi/oshi#2183]
Version：6.2.2
Code：new oshi.SystemInfo().getOperatingSystem().getFileSystem().getFileStores()

The results：

[{
		"name": "/",
		"volume": "overlay",
		"label": "/",
		"mount": "/",
		"options": "rw,relatime,lowerdir=/docker_images/overlay2/l/XZ4MMAPUEAYQVQOHURBOYJATFR:/docker_images/overlay2/l/UD6IJY6PRFEJIJASR2FND7KTGB:/docker_images/overlay2/l/EX6YL2NYJB3HZ725CH5CW3PO7Y:/docker_images/overlay2/l/AMAVSRC7S6RMCL3RC5UXGG2HV5:/docker_images/overlay2/l/JA3QDIVKXDULDUP2PCURDESRVA:/docker_images/overlay2/l/TZKFBDLZQGS73SF4HFWPTZBPIT:/docker_images/overlay2/l/H7CCWXXQJTE56TEGGTXD3HAJFJ:/docker_images/overlay2/l/3CIAQ4XGTQWUHXRF2LDMPQCUPV:/docker_images/overlay2/l/K3KFAFYHDJKZDXIR37N3H4ZJHZ:/docker_images/overlay2/l/OIOJSWMXJM7IVA3YQ3LOC2LDSP:/docker_images/overlay2/l/WZP62VNES2QO6LELHVKU545FQP:/docker_images/overlay2/l/QJR2K3EFYZPBFTQHTCAHTGU5NX:/docker_images/overlay2/l/4C63G6F5ABPFBG43UGK5G4GE7B:/docker_images/overlay2/l/NOXDIV3XH7NGN26OVVQEUJHCXY,upperdir=/docker_images/overlay2/eec79755c2096a5aff495daa8ad15e35183c7afc3bdd4341de01e59974156017/diff,workdir=/docker_images/overlay2/eec79755c2096a5aff495daa8ad15e35183c7afc3bdd4341de01e59974156017/work",
		"uuid": "",
		"logicalVolume": "",
		"description": "Mount Point",
		"freeSpace": 39948795904,
		"usableSpace": 37698818048,
		"totalSpace": 52709240832,
		"freeInodes": 3105449,
		"totalInodes": 3276800,
		"type": "overlay"
	}, {
		"name": "/dev/vda1",
		"volume": "/dev/vda1",
		"label": "/dev/vda1",
		"mount": "/op/logs",
		"options": "rw,relatime,data=ordered",
		"uuid": "",
		"logicalVolume": "",
		"description": "Local Disk",
		"freeSpace": 39948795904,
		"usableSpace": 37698818048,
		"totalSpace": 52709240832,
		"freeInodes": 3105449,
		"totalInodes": 3276800,
		"type": "ext4"
	}, {
		"name": "/dev/vda1",
		"volume": "/dev/vda1",
		"label": "/dev/vda1",
		"mount": "/op/db",
		"options": "rw,relatime,data=ordered",
		"uuid": "",
		"logicalVolume": "",
		"description": "Local Disk",
		"freeSpace": 39948795904,
		"usableSpace": 37698818048,
		"totalSpace": 52709240832,
		"freeInodes": 3105449,
		"totalInodes": 3276800,
		"type": "ext4"
	}, {
		"name": "/dev/vda1",
		"volume": "/dev/vda1",
		"label": "/dev/vda1",
		"mount": "/etc/resolv.conf",
		"options": "rw,relatime,data=ordered",
		"uuid": "",
		"logicalVolume": "",
		"description": "Local Disk",
		"freeSpace": 39948795904,
		"usableSpace": 37698818048,
		"totalSpace": 52709240832,
		"freeInodes": 3105449,
		"totalInodes": 3276800,
		"type": "ext4"
	}, {
		"name": "/dev/vda1",
		"volume": "/dev/vda1",
		"label": "/dev/vda1",
		"mount": "/etc/hostname",
		"options": "rw,relatime,data=ordered",
		"uuid": "",
		"logicalVolume": "",
		"description": "Local Disk",
		"freeSpace": 39948795904,
		"usableSpace": 37698818048,
		"totalSpace": 52709240832,
		"freeInodes": 3105449,
		"totalInodes": 3276800,
		"type": "ext4"
	}, {
		"name": "/dev/vda1",
		"volume": "/dev/vda1",
		"label": "/dev/vda1",
		"mount": "/etc/hosts",
		"options": "rw,relatime,data=ordered",
		"uuid": "",
		"logicalVolume": "",
		"description": "Local Disk",
		"freeSpace": 39948795904,
		"usableSpace": 37698818048,
		"totalSpace": 52709240832,
		"freeInodes": 3105449,
		"totalInodes": 3276800,
		"type": "ext4"
	}]

**Comment by mprins** [comment]
When you look closely these have different mount point, but they all point to the same underlying device which makes sense IMO

**Comment by zjjay** [comment]
> When you look closely these have different mount point, but they all point to the same underlying device which makes sense IMO

Then I know why, thanks
