### ISSUE TITLE
CPU Cache

### ISSUE THREAD

**Issue by CheeseTastisch** [oshi/oshi#2190]
Hey,
is it possible to find out the L1, L2 and L3 cache of a processor via the API?

**Comment by mprins** [comment]
I don't think it's currently supported, (can't find it in CentralProcessor/PhysicalProcessor)
It could be added by parsing eg. `lscpu` (Linux) output eg. so you are welcome to provide a pull request
```
└─ $ ▶ lscpu
...
Caches (sum of all):     
  L1d:                   256 KiB (8 instances)
  L1i:                   256 KiB (8 instances)
  L2:                    4 MiB (8 instances)
  L3:                    32 MiB (2 instances)

```
or 
```
└─ $ ▶ getconf -a | grep CACHE
LEVEL1_ICACHE_SIZE                 32768
LEVEL1_ICACHE_ASSOC                
LEVEL1_ICACHE_LINESIZE             64
LEVEL1_DCACHE_SIZE                 32768
LEVEL1_DCACHE_ASSOC                8
LEVEL1_DCACHE_LINESIZE             64
LEVEL2_CACHE_SIZE                  524288
LEVEL2_CACHE_ASSOC                 8
LEVEL2_CACHE_LINESIZE              64
LEVEL3_CACHE_SIZE                  33554432
LEVEL3_CACHE_ASSOC                 0
LEVEL3_CACHE_LINESIZE              64
LEVEL4_CACHE_SIZE                  
LEVEL4_CACHE_ASSOC                 
LEVEL4_CACHE_LINESIZE    
```

I don't think there's a `sysctl` for OpenBSD

@dbwiddis Might have better/other suggestions

**Comment by dbwiddis** [comment]
Yes, we'd need to find the information in other OS's, but I believe that should be available.  The bigger question is what sort of data structure applies and how to model this.  Are these caches common to all the processors?  Can there be more than one of them?

I think the answer is yes.  We currently fetch logical/physical processor info on Windows from `GetLogicalProcessorInformationEx` and in its returned objects it includes a `RelationCache` identifying processors which share a cache.  That provides a [`CACHE_RELATIONSHIP`](https://learn.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-cache_relationship) structure with data... probably a good template for an OSHI object.

Results on Winodws, mac, and Linux are probably enough to add a cross-platform feature. We can add them from the BSDs, solaris, and AIX if they are reasonably easy to obtain there as well.  

Can you get started with the new interface method (probably `getCaches()` on the CentralProcessor interface) and probably a new `ProcessorCache` class (similar to LogicalProcessor and PhysicalProcessor) that contains the data in that `CACHE_RELATIONSHIP` structure?    If you can implement on any OS the community can help with the other ones.

**Comment by dbwiddis** [comment]
Looks like on Solaris [you can parse `prtpicl` output.](https://blogs.oracle.com/solaris/post/solaris-tips-cpu-cache-sizes-changing-system-date)

**Comment by CheeseTastisch** [comment]
I will start working and will try to implemnt windows, linux and macOS for the start, maby i will add some other OS later

**Comment by dbwiddis** [comment]
On AIX it's in `vmstat -v`.

**Comment by mprins** [comment]
OpenBSD provides it in `dmesg` I see, so it is probably available programmatically somewhere.

afaik each cpu core can have these eg.

```
OpenBSD 6.2 (GENERIC.MP) #0: Wed Oct  4 05:08:15 UTC 2017
    visa@octeon:/usr/src/sys/arch/octeon/compile/GENERIC.MP
....
mainbus0 at root
cpu0 at mainbus0: CN50xx CPU rev 0.1 500 MHz, Software FP emulation
cpu0: cache L1-I 32KB 4 way D 8KB 64 way, L2 128KB 8 way
cpu1 at mainbus0: CN50xx CPU rev 0.1 500 MHz, Software FP emulation
cpu1: cache L1-I 32KB 4 way D 8KB 64 way, L2 128KB 8 way
```
I bet that at some point there will/may be CPU's that have different values for different cores as well eg. big/little ARM...

**Comment by dbwiddis** [comment]
@mprins it's in dmidecode -t cache (or 7) but that requires elevated permissions.   But dmesg is a good backup.

**Comment by dbwiddis** [comment]
> afaik each cpu core can have these eg.

Logical or physical core?  And is that the same cache shared across multiple cores?

The Windows implementation will associate each cache with one or more logical processors, so that seems reasonable to do elsewhere, if possible.

**Comment by mprins** [comment]
this has some pictures: https://superuser.com/questions/1073937/what-does-l4-cache-hold-on-some-cpus including L4 cache

**Comment by dbwiddis** [comment]
Yep, so different level caches associated with different groups of processors.... Windows handles that with the groupmasks.

Suggestion:
 - have a Cache object with fields for level, associativity, lineSize and cacheSize.  Give them an index number based on the order they are found (for lack of any other numbering system)
 - in the LogicalProcessor class add a field with a list of cache index numbers it's associated with

**Comment by dbwiddis** [comment]
[Linux has the data stored in sysfs](https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-devices-system-cpu), e.g., `/sys/devices/system/cpu/cpu0/cache/index2/size`.  I think this is the best source.  It may be fetchable via udev.

**Comment by CheeseTastisch** [comment]
How can i use udev? Is there a documentation of it anywhere?

**Comment by dbwiddis** [comment]
> How can i use udev? Is there a documentation of it anywhere?

Docs for Udev are at JNA: http://java-native-access.github.io/jna/5.12.1/javadoc/com/sun/jna/platform/linux/Udev.html

For an example in OSHI, Check out [`readTopologyFromUdev()`](https://github.com/oshi/oshi/blob/ef88fa4d96cd8c7fd717855cadaac446c0f93c6d/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java#L204) in the `LinuxCentralProcessor` class.  It gets you as far as enumerating the CPUs (so up to cpu0 in the example above).  You may need to do another layer of enumeration of CACHE below that to get the index #s, and then get the size property from them.

There's also a fallback non-UDEV option to just navigate the sysfs files in [`readTopologyFromSysfs()`](https://github.com/oshi/oshi/blob/ef88fa4d96cd8c7fd717855cadaac446c0f93c6d/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java#L237).  You'll probably have to do both. :)

You can probably piggyback on these existing methods and insert your new code within them.

**Comment by dbwiddis** [comment]
macOS sysctls and system_profiler from my machine.  
```
hw.perflevel0.l1icachesize: 32768
hw.perflevel0.l1dcachesize: 32768
hw.perflevel0.l2cachesize: 262144
hw.perflevel0.l3cachesize: 16777216
hw.cacheconfig: 16 2 2 16 0 0 0 0 0 0
hw.cachesize: 34359738368 32768 262144 16777216 0 0 0 0 0 0
hw.cachelinesize: 64
hw.l1icachesize: 32768
hw.l1dcachesize: 32768
hw.l2cachesize: 262144
hw.l3cachesize: 16777216
machdep.cpu.cache.linesize: 64
machdep.cpu.cache.L2_associativity: 4
machdep.cpu.cache.size: 256

$ system_profiler SPHardwareDataType;
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro15,1
      Processor Name: 8-Core Intel Core i9
      Processor Speed: 2.3 GHz
      Number of Processors: 1
      Total Number of Cores: 8
      L2 Cache (per Core): 256 KB
      L3 Cache: 16 MB
```
We'd prefer the sysctl as it's a native call, but the other output informs it: note the L2 is 256 KB (262144) per core so that sysctl value is a per-core value.

The `hw.cachesize` sysctl gives you all 3 numbers in order, prepended by some other very large number.  Might take some research to interpret what they all mean.

Also be aware M1 (and M2) may have changed the sysctl so we may have to dig into that as well.

**Comment by CheeseTastisch** [comment]
My MacBook (M2) has with `sysctl` the following output:
```
hw.perflevel0.l1icachesize: 196608
hw.perflevel0.l1dcachesize: 131072
hw.perflevel0.l2cachesize: 16777216
hw.perflevel1.l1icachesize: 131072
hw.perflevel1.l1dcachesize: 65536
hw.perflevel1.l2cachesize: 4194304
hw.cacheconfig: 8 1 4 0 0 0 0 0 0 0
hw.cachesize: 3703324672 65536 4194304 0 0 0 0 0 0 0
hw.cachelinesize: 128
hw.l1icachesize: 131072
hw.l1dcachesize: 65536
hw.l2cachesize: 4194304
```

`system_profiler` doesn't include Cache at all.

**Comment by dbwiddis** [comment]
Glad you've got an M2.  I'll buy one as soon as it's available in 16" size :)

Looks like plenty to go with here.  `machdep` isn't available, nor system profiler.  Don't see anything about an L3 cache though.

I looked in the IO Registry and didn't see anything there, either.

**Comment by CheeseTastisch** [comment]
So it seems like there are many differences between each operating system and even different processors. Therefore, it is very likely that some information is only available on some operating systems or some processors.

**Comment by dbwiddis** [comment]
That's generally true of most things on OSHI. :)

**Comment by CheeseTastisch** [comment]
Hey @dbwiddis,

I haven't had much time lately and I won't have much time in the near future either.
So it won't be possible for me to really work on this.
So it would make sense to add the "up for grabs" tag.

**Comment by dbwiddis** [comment]
Sounds good.  Hack to regret is coming too.  :)

**Comment by dbwiddis** [comment]
I created an API and implemented on Windows in #2198.  Would be interesting to see output on a physical windows machine, as my VM shows lots of caches but they don't line up with my virtual processors well :)

```
Topology:
 LogProc  P/E Proc  Pkg NUMA PGrp Caches
       0    P    0    0    0    0    0
       1    P    1    0    0    0    3
       2    P    2    0    0    0    3
       3    P    3    0    0    0    3
       4    P    4    0    0    0    3
       5    P    5    0    0    0    3
       6    P    6    0    0    0    3
       7    P    7    0    0    0    3
ProcessorCache [cacheNumber=0, level=1, associativity=8, lineSize=64, cacheSize=52, type=2]
ProcessorCache [cacheNumber=1, level=1, associativity=8, lineSize=64, cacheSize=52, type=1]
ProcessorCache [cacheNumber=2, level=2, associativity=4, lineSize=64, cacheSize=52, type=0]
ProcessorCache [cacheNumber=3, level=3, associativity=16, lineSize=64, cacheSize=52, type=0]
ProcessorCache [cacheNumber=4, level=1, associativity=8, lineSize=64, cacheSize=52, type=2]
ProcessorCache [cacheNumber=5, level=1, associativity=8, lineSize=64, cacheSize=52, type=1]
ProcessorCache [cacheNumber=6, level=2, associativity=4, lineSize=64, cacheSize=52, type=0]
ProcessorCache [cacheNumber=7, level=1, associativity=8, lineSize=64, cacheSize=52, type=2]
ProcessorCache [cacheNumber=8, level=1, associativity=8, lineSize=64, cacheSize=52, type=1]
ProcessorCache [cacheNumber=9, level=2, associativity=4, lineSize=64, cacheSize=52, type=0]
ProcessorCache [cacheNumber=10, level=1, associativity=8, lineSize=64, cacheSize=52, type=2]
ProcessorCache [cacheNumber=11, level=1, associativity=8, lineSize=64, cacheSize=52, type=1]
ProcessorCache [cacheNumber=12, level=2, associativity=4, lineSize=64, cacheSize=52, type=0]
ProcessorCache [cacheNumber=13, level=1, associativity=8, lineSize=64, cacheSize=52, type=2]
ProcessorCache [cacheNumber=14, level=1, associativity=8, lineSize=64, cacheSize=52, type=1]
ProcessorCache [cacheNumber=15, level=2, associativity=4, lineSize=64, cacheSize=52, type=0]
ProcessorCache [cacheNumber=16, level=1, associativity=8, lineSize=64, cacheSize=52, type=2]
ProcessorCache [cacheNumber=17, level=1, associativity=8, lineSize=64, cacheSize=52, type=1]
ProcessorCache [cacheNumber=18, level=2, associativity=4, lineSize=64, cacheSize=52, type=0]
ProcessorCache [cacheNumber=19, level=1, associativity=8, lineSize=64, cacheSize=52, type=2]
ProcessorCache [cacheNumber=20, level=1, associativity=8, lineSize=64, cacheSize=52, type=1]
ProcessorCache [cacheNumber=21, level=2, associativity=4, lineSize=64, cacheSize=52, type=0]
ProcessorCache [cacheNumber=22, level=1, associativity=8, lineSize=64, cacheSize=52, type=2]
ProcessorCache [cacheNumber=23, level=1, associativity=8, lineSize=64, cacheSize=52, type=1]
ProcessorCache [cacheNumber=24, level=2, associativity=4, lineSize=64, cacheSize=52, type=0]
```

**Comment by dbwiddis** [comment]
For mac: first 4 numbers of `sysctl hw.cachesize` are system memory, L1, L2, L3 size.  L1 and L2 are per-core.  Looks like the M2 has no L3 cache?

**Comment by dbwiddis** [comment]
Linux is done.
```
 Topology:
  LogProc  P/E Proc  Pkg NUMA PGrp Caches
        0    P    0    0    0    0    0,1,2,3
        1    P    1    0    0    0    0,4,5,6
ProcessorCache [cacheNumber=0, level=3, associativity=12, lineSize=64, cacheSize=49152, type=UNIFIED]
ProcessorCache [cacheNumber=1, level=2, associativity=20, lineSize=64, cacheSize=1280, type=UNIFIED]
ProcessorCache [cacheNumber=2, level=1, associativity=8, lineSize=64, cacheSize=32, type=INSTRUCTION]
ProcessorCache [cacheNumber=3, level=1, associativity=12, lineSize=64, cacheSize=48, type=DATA]
ProcessorCache [cacheNumber=4, level=2, associativity=20, lineSize=64, cacheSize=1280, type=UNIFIED]
ProcessorCache [cacheNumber=5, level=1, associativity=8, lineSize=64, cacheSize=32, type=INSTRUCTION]
ProcessorCache [cacheNumber=6, level=1, associativity=12, lineSize=64, cacheSize=48, type=DATA]
```

**Comment by dbwiddis** [comment]
AIX seems to only show L2 cache...
```
> lsattr -EOl L2cache0
#size
512
```

**Comment by dbwiddis** [comment]
Current status: 
 - [x] Windows: Done, but weird values from VM/Hypervisor. Need testing on metal.
 - [x] Linux: Done.  Some weird values on VM but enough metal testing to validate.
 - [ ] macOS: Can be easily done with sysctl, probably do that last
 - [ ] Solaris: I don't think it's possible.
 - [ ] FreeBSD/OpenBSD: Hopeful that either dmidecode or dmesg can give all required details
 - [x] AIX: Only L2 size available in OS; hardcoded values for POWER7, POWER8, and POWER9 architectures.
