### ISSUE TITLE
Improve processing speed with parallel streams

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#2196]
While doing some benchmarking on the FFM project I realized there are many places in OSHI that can benefit from simply adding `parallel()` to existing streams, particularly in the getProcess implementations.

This is a relatively simple code change with a potentially big payoff.

**Comment by b0n541** [comment]
I would like to tackle that issue. Could you point me to the place where I can find the "getProcess" implementations, please?

**Comment by dbwiddis** [comment]
Hey @b0n541 thanks for stepping up!  

First place to fix is the `OperatingSystem` interface.  The `getProcesses()` method that takes a `Collection<Integer>` argument could use both a `distinct()` and `parallel()` just before the `map(this::getProcess)`.  `AbstractOperatingSystem` has several methods using the streams (including the child and dependent processes).

Each of the platform-dependent subclasses of `AbstractOperatingSystem` has several methods associated with processes that either use the stream or have a for-loop that could be turned into a stream and parallelized.
