### ISSUE TITLE
Question: How I can monitor Memory and CPU usage of other process

### ISSUE THREAD

**Issue by HomminLee** [oshi/oshi#2199]
I want to monitor  CPU usage of other process. But`OSProcess` class do not have cpu field.

<img width="668" alt="image" src="https://user-images.githubusercontent.com/25881185/193024343-72566e94-d658-45ed-9609-8e11cf32ca25.png">

How can I calculate to get %CPU?

**Comment by mprins** [comment]
Use [`getVirtualSize()`](https://www.oshi.ooo/oshi-core-java11/apidocs/com.github.oshi/oshi/software/os/OSProcess.html#getVirtualSize()) and [`getProcessCpuLoadBetweenTicks(oshi.software.os.OSProcess)`](https://www.oshi.ooo/oshi-core-java11/apidocs/com.github.oshi/oshi/software/os/OSProcess.html#getProcessCpuLoadBetweenTicks(oshi.software.os.OSProcess)) of the `OSProcess` that you are interested in

**Comment by HomminLee** [comment]
> Use [`getVirtualSize()`](https://www.oshi.ooo/oshi-core-java11/apidocs/com.github.oshi/oshi/software/os/OSProcess.html#getVirtualSize()) and [`getProcessCpuLoadBetweenTicks(oshi.software.os.OSProcess)`](https://www.oshi.ooo/oshi-core-java11/apidocs/com.github.oshi/oshi/software/os/OSProcess.html#getProcessCpuLoadBetweenTicks(oshi.software.os.OSProcess)) of the `OSProcess` that you are interested in

Thanks a lot.

**Comment by dbwiddis** [comment]
> [`getProcessCpuLoadBetweenTicks(oshi.software.os.OSProcess)`](https://www.oshi.ooo/oshi-core-java11/apidocs/com.github.oshi/oshi/software/os/OSProcess.html#getProcessCpuLoadBetweenTicks(oshi.software.os.OSProcess)) 

For clarity, this requires saving the old ticks and computes the difference between timestamps, which is usually what people want when monitoring current usage.

The screen capture in the original is of `top` which (like `ps`) displays cumulative usage since the process start.  That's [`getProcessCpuLoadCumulative()`](https://www.oshi.ooo/oshi-core-java11/apidocs/com.github.oshi/oshi/software/os/OSProcess.html#getProcessCpuLoadCumulative())

**Comment by dbwiddis** [comment]
Also the `top` display is asking about percentage which requires division by total memory.   These calculations are actually demonstrated in the `SystemInfoTest.java`:
https://github.com/oshi/oshi/blob/8b928460ffe8bf0726a9b485b9ae618cb79c998b/oshi-core/src/test/java/oshi/SystemInfoTest.java#L274-L281
