### ISSUE TITLE
Allow suppressing sysctl error for known error conditions

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#2206]
Too many of these in test logs:
> Warning:  2022-10-02 07:11:40.966 [WARN] MacOSProcess - Failed sysctl call for process arguments (kern.procargs2), process 10323 may not exist. Error code: 22

Also with the cache implementation in #2198 we'll be intentionally checking for some platform-specific sysctls that may not be there.

We have a boolean in the FileUtil classes optionally suppressing log messages.  We should add the same to the sysctls.

See also #2149 on Linux with essentially the same issue.

**Comment by pavangole** [comment]
Hello @dbwiddis . I want to fix this issue. As this is my first time I don't know much about sysctls. Will you help me? Additionally, will you provide a location where to write the code and where to take references? Thank you.

**Comment by dbwiddis** [comment]
Hey @pavangole ... the one most wanted doesn't use the util class. You can find the `MacOSProcess` class in the `oshi.software.os.mac` package. There's a `sysctl` call there inside the `queryArgsAndEnvironment()` method.   Make that log warning conditional on a global config parameter similar to what was done for Linux proc (look at `LinuxOSProcesss` and the `LOG_PROCFS_WARNING` constant and its use.

Also, if you like ... the `SyscltUtil` class is in `oshi.util.platform.mac`.   I actually already did the change for the one with the `int` default, which you can use as an example for the others.  This is optional.

**Comment by pavangole** [comment]
What I understand is that I have to create a global config variable if it is set then we don't have to give log messages. Please correct me If I am wrong.

**Comment by dbwiddis** [comment]
@pavangole that's correct.  See how LOG_PROCFS_WARNING is implemented and implement something similar for MAC_SYSCTL_WARNING (or another name you choose).

**Comment by pavangole** [comment]
I tried to follow the contributing guidelines but it is giving errors. I tried mvn clean test command and it is showing following output.

![image](https://user-images.githubusercontent.com/64621994/195361983-69d1b8f8-aaaa-4eb8-9d22-85f583114ebf.png)

**Comment by dbwiddis** [comment]
Further up it should tell you what failed.

**Comment by pavangole** [comment]
This is the error.

![image](https://user-images.githubusercontent.com/64621994/195393088-30c7d63d-56b8-4639-bec5-2be68443eaaa.png)

**Comment by dbwiddis** [comment]
Further up it should tell you exactly which test failed.

**Comment by pavangole** [comment]
These are the 2 methods that failed. @dbwiddis guide me on how to solve this problem and successfully run mvn on the system so I can further write the code.
![image](https://user-images.githubusercontent.com/64621994/195551001-c9d4122a-b668-4ef0-b565-52e66ccfdbd3.png)

**Comment by dbwiddis** [comment]
These are normal errors for non-intel processor and not having legal installed.  You can contribute even with these errors.  

I will update the contributor guide later to note this is ok.

**Comment by pavangole** [comment]
I successfully wrote the code.
The changes made by me are:
In oshi.properties added new property
`oshi.os.mac.sysctl.logwarning=false`

Read the property value in `Globalconfig.java`
`public static final String OSHI_OS_MAC_SYSCTL_LOGWARNING = "oshi.os.mac.sysctl.logwarning";`

And Finally, use it in `MacOSProcess.java`
` private static final boolean LOG_MAC_SYSCTL_WARNING = GlobalConfig.get(GlobalConfig.OSHI_OS_MAC_SYSCTL_LOGWARNING,
        false);`

Add suppress the warning in `queryArgsAndEnvironment()`

`if (pid > 0 && LOG_MAC_SYSCTL_WARNING) `

**Comment by dbwiddis** [comment]
> But when I ran the `mvn license: format` command it gave the following error.

I recently changed the licenses to be done by spotless, so I'll have to remove that instruction from the contributing guide!
