### ISSUE TITLE
Sequence to get HDD serial number is getting changed

### ISSUE THREAD

**Issue by DeepsUttekar** [oshi/oshi#2208]
Hello team,

I am using oshi library to get HDD serial number  hardwareAbstractionLayer.getDiskStores(). this returns List<HWDiskStore> and then I am using HDD serial number from 1st record  and use it in my business logic.

But recently I have found that, if I connect USB drive and run my application, above API returns list but 1st record as USB and 2nd one as Integrated drive. So if I continue using 1st record HDD serial number, my business logic fails as it is receiving different serial number

Is there any way by which I can get primary HDD number even if there are  multiple external drives are attached

**Comment by dbwiddis** [comment]
>  I am using HDD serial number from 1st record and use it in my business logic.

OSHI doesn't guarantee any ordering of drives.  I had a look at the various `getDisks()` implementations:
 - Windows: in the order from the WMI query result, which internally navigates the device tree
 - macOS: in the order from the IORegistry (device tree equivalent)
 - Linux: in the order returned by Udev iterating block devices
 - FreeBSD: in the order returned by sysctl kern.disks
 - OpenBSD: in the order encountered at boot using dmesg
 - Solaris: inserted in a map in order from lshal, but no guarantee on map key ordering
 - AIX: intentionally sorted by the major value of the partitions

> Is there any way by which I can get primary HDD number even if there are multiple external drives are attached

I'm not sure it's a guarantee, but in my experience the primary disk tends to have a lower "major" number.  This is apparently the assumption used in the AIX implementation.   You might consider sorting your returned list similarly to see if it helps:
```java
return storeList.stream()
    .sorted(Comparator.comparingInt(
        s -> s.getPartitions().isEmpty() ? Integer.MAX_VALUE : s.getPartitions().get(0).getMajor()))
    .collect(Collectors.toList());
```

**Comment by dbwiddis** [comment]
Another option similar to the above is to inspect the partition mount points.  I would expect whichever partition is mounted at `/` (*nix) or `C:\` (Windows) to be on the primary drive.
