### ISSUE TITLE
Add max file descriptors per process

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#2215]
See commentary [here](https://stackoverflow.com/a/74101019/1161484).

OSHI currently returns the systemwide limit in `getMaxFileDescriptors()`.  On some OS's there is a per-process limit, for which we could add a `getMaxFileDescriptorsPerProcess()`.
 - on Linux, `/proc/sys/fs/nr-open` or `/proc/self/limits`.
 - on macOS and FreeBSD, sysctl `kern.maxfilesperproc`
 - on Windows, try [`_getmaxstdio`](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/getmaxstdio?view=msvc-170) or hardcode 16 * 1024 * 1024 = 16,777,216.
 - on OpenBSD, try [`getdtablesize()`](https://man.openbsd.org/getdtablesize.3) or `getrlimit()` with `RLIMIT_NOFILE`.
 - on Solaris, try `getrlimit()` or [these options](https://www.thegeekdiary.com/solaris-how-to-set-limit-on-the-maximum-number-of-open-files-per-process/)
 - on AIX try `/etc/security/limits`, if it's not there assume unlimited

**Comment by gitseti** [comment]
When I get to it, I would gladly contribute a PR to this. :) 

For now, just some thoughts / questions:
- Would it make sense to also offer a method to get the per-process soft limit for open files, sth. like `getMaxFileDescriptorsSoftLimitPerProcess`?
- On Linux `/proc/sys/fs/nr-open` does return the hard limit for open files afaik, but not the soft limit. Using `getrlimit()` would return both limits. Also another option would be to read out `/proc/{current-pid}/limits`.
- Afaik, macOS, FreeBSD and OpenBSD also support the `getrlimit()` POSIX function, so it might be worth to think about using the same implementation to get the limits. Or are there any concerns about using JNA calls instead of reading out the files?

**Comment by dbwiddis** [comment]
Thanks for volunteering to add this new capability. 

> Would it make sense to also offer a method to get the per-process soft limit for open files

I'll admit I'm not an expert in these metrics, so I'll defer to your choice here.  I'm all for adding as much information as is generally needed, and if there are different hard and soft limits that are easily available, that's great... just make sure the javadocs are clear.  I'm not sure if the per-process limit differs across different process, in which case:
 - we may want a systemwide "default" or report values for "current process"
 - we may want something on the OSProcess object to get the value per-process

I generally prefer to include metrics that are cross-platform, so if it's a Linux-only thing that anyone can easily query via procfs, it may not be as useful to add.

Totally fine to use `getrlimit()` and other POSIX-standard functions via JNA, and probably preferred.  Note that while the function signature is standard, the header files may differ between OS's.

> Is there a way to change the per-process limit for an individual process

We've pretty much stuck to a "read only" approach here, and turned down requests for features to "kill a process" for example.  So I'd be opposed to a function to set the limit rather than just read it.  Hopefully that's functionality you can easily add in your own application.

> So to sum it up - What do you think about having these three new methods

Definitely OK with 1.  OK with 2 and 3 in concept but not sure of location (OperatingSystem vs. FileSystem vs. OSProcess).  If they're all systemwide limits I'd tend to want them all in the same spot (FileSystem) or if they're per-process, then on the OSProcess object.

**Comment by gitseti** [comment]
> I'm not sure if the per-process limit differs across different process

[I did some tests](https://gist.github.com/gitseti/aa862407379a3a1a4f3872023bfb46c6) on Ubuntu 22.04 to check if the per-process limits can differ.

1. On a fresh installation the output is:

```
java -XX:-MaxFDLimit -jar OpenFileLimits.jar # flag is needed so that the jvm does not set soft limit = max limit

Open File Limits using getrlimits():
1048576
1048576

Open File Limits reading nr_open:
1048576

Open File Limits reading /proc/self/limits:
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             7610                 7610                 processes 
Max open files            1048576              1048576              files     
Max locked memory         258269184            258269184            bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       7610                 7610                 signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us        
```

2. If I now decrease the soft limit and execute the jar with `-XX:-MaxFDLimit`, then the output is the following:
```
ulimit -Sn 100
java -XX:-MaxFDLimit -jar OpenFileLimits.jar # flag is needed so that the jvm does not set soft limit = max limit

Open File Limits using getrlimits():
1048576
100

Open File Limits reading nr_open:
1048576

Open File Limits reading /proc/self/limits:
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             7610                 7610                 processes 
Max open files            100                  1048576              files     
Max locked memory         258269184            258269184            bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       7610                 7610                 signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us        
```

3. If I now also set the hard limit the output is the following:
```
ulimit -n 500
ulimit -Sn 100
java -XX:-MaxFDLimit -jar OpenFileLimits.jar # flag is needed so that the jvm does not set soft limit = max limit

Open File Limits using getrlimits():
500
100

Open File Limits reading nr_open:
1048576

Open File Limits reading /proc/self/limits:
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             7610                 7610                 processes 
Max open files            100                  500                  files     
Max locked memory         258269184            258269184            bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       7610                 7610                 signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us        
```

So it seems there is this global config `/proc/sys/fs/nr-open`, which provides a kind of default hard limit, wheras `/proc/self/limits` provides the actual soft and hard limits for the process. 

So there is a system-wide limit and a process-specific limit.

**Comment by gitseti** [comment]
> Definitely OK with 1. OK with 2 and 3 in concept but not sure of location (OperatingSystem vs. FileSystem vs. OSProcess). If they're all systemwide limits I'd tend to want them all in the same spot (FileSystem) or if they're per-process, then on the OSProcess object.

As mentioned above, `getrlimits()` seems to be the only reliable option to get the process-specific soft and hard open file limit across different OSs. But this option can only get the limits for the executing process and not any process, so I'm a bit undecided if it should go to `OSProcess`. That's why I just moved it up to `OperatingSystem` in the suggestion.

For Linux it would be possible to get process-specific limits via `/proc/{pid}/limits`, but as there is no equivalent on macOS this functionality may be too OS-specific for OSHI?

**Comment by dbwiddis** [comment]
> As mentioned above, `getrlimits()` seems to be the only reliable option to get the process-specific soft and hard open file limit across different OSs. But this option can only get the limits for the executing process and not any process, so I'm a bit undecided if it should go to `OSProcess`. That's why I just moved it up to `OperatingSystem` in the suggestion.

It's not unreasonable, particularly since we have the current process PID there.  But I think I'm still leaning toward OSProcess, as that's where we already have a `getOpenFiles()` method that is directly comparable.  It's your feature so I don't want to dictate the choice, just offering my input.

> For Linux it would be possible to get process-specific limits for any process via `/proc/{pid}/limits`, but as there is no equivalent on macOS this functionality may be too OS-specific for OSHI?

Also in my browsing to find the answer on the linked SO post I'm pretty sure I saw command line options in other OS's.  The [link for Solaris](https://www.thegeekdiary.com/solaris-how-to-set-limit-on-the-maximum-number-of-open-files-per-process/) above shows command-line per-process options.  

In any case, having those 3 methods, and having the Linux (and possibly Solaris) methods report for the given PID and other OS's report for the current process (regardless of the PID) seems reasonable if documented.

**Comment by dbwiddis** [comment]
> Therefore, I think using a JNA call to `getrlimits()` could be the better option to get the correct process-specific limits. I'm not sure if the optimzation of reading the `/proc/self/limits` is worth the added code or if we should just reuse `getrlimits` call with adjusted resource for the different OS's.

I'm not sure that's an optimization! 😁   They probably all read the same underlying code, and I think a direct OS call (`getrlimits()`) will cut out the formatting to String (by kernel) and parsing back to Integer (by Java) steps that procfs requires.  So I'm all for that approach.

**Comment by gitseti** [comment]
> I'm not sure that's an optimization! 😁 They probably all read the same underlying code, and I think a direct OS call (getrlimits()) will cut out the formatting to String (by kernel) and parsing back to Integer (by Java) steps that procfs requires. So I'm all for that approach.

Ah that's true. I just forgot that the loading of the native library takes some time. 😄

**Comment by gitseti** [comment]
⬆️ I decided to split the system-wide per-process limits of `getMaxFileDescriptorsPerProcess()` and the process-specific limits in two PRs. The first one should be reviewable. :)

**Comment by dbwiddis** [comment]
> Ah that's true. I just forgot that the loading of the native library takes some time. 😄

Native library loading is a one-time event (which is probably already done for other calls using the system library), as is mapping the function as a pointer in that library.  It's safe to say a POSIX-standard function, if implemented, is the most preferred implementation.

**Comment by gitseti** [comment]
⬆️  I added the second part. Currently, it is a draft because I don't know how I can call `_getmaxstdio` via JNA. Maybe you can give me some input on that? :) 
Besides that it should be ready for review.
