### ISSUE TITLE
Memory exception windows

### ISSUE THREAD

**Issue by 564667471** [oshi/oshi#2221]
![内存溢出1](https://user-images.githubusercontent.com/18342736/197720023-82045b0c-2652-4332-95eb-2a01af1f9fd7.png)
![内存溢出2](https://user-images.githubusercontent.com/18342736/197720039-ed984e0a-bc30-4540-9d56-b31088f85e44.png)

**Comment by dbwiddis** [comment]
It's not clear what the problem is here.  You are showing increasing memory as you loop fetching ticks and collecting FileSystem info, but that could just be normal Java heap usage.
