### ISSUE TITLE
6.3.0 throws exception on AIX from AixCentralProcessor.java:113

### ISSUE THREAD

**Issue by mnellemann** [oshi/oshi#2228]
Hi,

After upgrading oshi-core from 6.2.2 to 6.3.0 I started getting errors when running on AIX:

```
java.lang.ArithmeticException: divide by zero
        at oshi.hardware.platform.unix.aix.AixCentralProcessor.initProcessorCounts(AixCentralProcessor.java:113)
        at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:65)
        at oshi.hardware.platform.unix.aix.AixCentralProcessor.<init>(AixCentralProcessor.java:38)
        at oshi.hardware.platform.unix.aix.AixHardwareAbstractionLayer.createProcessor(AixHardwareAbstractionLayer.java:55)
        at oshi.util.Memoizer$1.get(Memoizer.java:61)
        at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48)
        at sysmon.plugins.os_base.BaseProcessorExtension.getMetrics(BaseProcessorExtension.java:84)
```

Call in my code is from [BaseProcessorExtension.java:84](https://bitbucket.org/mnellemann/sysmon/src/63d2fbd7800c217284a67583e3085fa1110f1ab1/plugins/os-base/src/main/java/sysmon/plugins/os_base/BaseProcessorExtension.java#lines-84), which works as expected with 6.2.2. 

Code is tested on a Power9 LPAR (VM/Guest) running AIX 7200-05-04-2220.
```System configuration: type=Dedicated mode=Capped smt=8 lcpu=8 mem=4096MB ```

Works fine on Linux - have not tested on any other OS.

Have I missed something important in the release notes?

**Comment by mprins** [comment]
that seems to be a regression from #2198 see my comment: https://github.com/oshi/oshi/pull/2198/files#r1008699766

I think `lpPerPp` should be a float or double

**Comment by dbwiddis** [comment]
> I think `lpPerPp` should be a float or double

Not really, as it should never be a fraction.   The root cause appears to be that not all physical processors were in use, leading to a case where (current) logical processors was less than the (max) physical processors:
```java
int physProcs = (int) config.numProcessors.max;
int lcpus = config.lcpus;
int lpPerPp = lcpus / physProcs;
```
where `config.numProcessors` has these options:
```java
class perfstat_value_t extends Structure {
    public long online;
    public long max;
    public long min;
    public long desired;
}
```
Quick fix (and should go in anyway) would be ensuring that the `lpPerPp` value is at least 1, but I'm not sure that's the complete solution.   Other options in addition to this:
 - ensure physical processor count is never higher than logical processor count
 - use a different structure element than `max` to define physical proecessor count (probably `online`).

@mnellemann thanks for this bug report, do you have any suggestions on proper counting of physical processors in your particular configuration?

**Comment by dbwiddis** [comment]
Here's [a thread with some potential output](https://community.ibm.com/community/user/power/communities/community-home/digestviewer/viewthread?GroupId=6049&MID=138050&CommunityKey=daa942cb-b783-4fd3-ba27-a2d7462f9530&ReturnUrl=%2Fcommunity%2Fuser%2Fcommunities%2Fcommunity-home%2Fdigestviewer%3FCommunityKey%3Ddaa942cb-b783-4fd3-ba27-a2d7462f9530).

I rather identify with this comment:
> Even here, the term 'physical CPU' is misleading.

But here's a situation that would have resulted in the bug, stripped to what I think is relevant:
```$ lparstat -i
Type : Shared-SMT
Entitled Capacity : 27.00
Online Virtual CPUs : 56
Maximum Virtual CPUs : 64
Minimum Virtual CPUs : 1
Maximum Physical CPUs in system : 64
Active Physical CPUs in system : 57
Active CPUs in Pool : 57
Physical CPU Percentage : 48.21%
```
This would give OSHI an lp count of 56 on 64 (max) physical processors, so max is wrong, but active would also be wrong.   But it's also in a pool that provides an "entitlement" to the user, e.g., they are allotted processing on 27 of the 56 vCPUs (48.21%) although it is labeled "physical CPU percentage" which would imply 27 of 57 (47.37%).

It gets more complicated when you consider that the logical processor count (and list of LPs) is supposed to align with the per-processor metrics such as CPU ticks. Those are fetched by the [`perfstat_cpu()`](https://www.ibm.com/docs/en/aix/7.1?topic=p-perfstat-cpu-subroutine) function, but the result there is variable:
> This number represents the number of logical processors for which statistics are available. In a dynamic logical partitioning (DLPAR) environment, this number is the highest logical index of an online processor since the last reboot.

I'm thinking it may be best to just have OSHI report the max number of logical processors.  Currently it reports from:
```java
class perfstat_cpu_total_t extends Structure {
    public int ncpus; // number of active logical processors
```
Perhaps it should come from the same structure (and use `.max`) as the physical processors:
```
class perfstat_partition_config_t extends Structure {
    public perfstat_value_t numProcessors; // Number of Configured Physical Processors in frame
    /* Virtual CPU related Configuration */
    public perfstat_value_t vcpus; // Min, Max and Online Virtual CPUs
```
