### ISSUE TITLE
The OSService cannot obtain the registered service. Procedure

### ISSUE THREAD

**Issue by 2539469416** [oshi/oshi#2231]
I register a service in systemctl myself, how do I get it in OSService
Why did the service I signed up for show its status as STOPPED

**Comment by dbwiddis** [comment]
The meaning of "service" is somewhat vague and difficult to quantify cross-platform.  The Javadoc says:
>  This class is provided for information purposes only. Interpretation of the meaning of services is platform-dependent.

For some more background:

> While researching this, it's hard to find a good answer.   Not all services start at boot (e.g., I've set up some windows services using Apache Commons Daemon (a.k.a. procrun))  So just finding the startup doesn't work.
> 
> For the *nix systems, it gets more complex.  Is it just a daemon (a process with no controlling tty?).   Except in graphical *nix systems, the gui processes run without a tty so you'd have to parse some X output to exclude those.
> 
> Is it a process started at boot (check for parent pid = 1, or process uptime close to system uptime)?  A process name ending in 'd'?    Use the `service --status-all` command (it's slow)?   Should you just iterate the contents of /etc/init.d?
> 
> Given your definition, the process list does list start time, so you could reasonably find which processes have an up time within some short interval of up time or parent pid.  That may not match the output from other lists.
> 
> The bottom line is that the term "service" does not have a consistent cross-platform meaning.
> 
> Can you describe your use case for wanting to list services with OSHI?
> 
> _Originally posted by @dbwiddis in https://github.com/oshi/oshi/issues/257#issuecomment-246255114_
      
That said, the Linux implementation considers a service:
 - a child process of PID 0
 - an enabled service from the result of "systemctl list-unit-files"
 - a service in `/etc/init` with a `.conf` extension (assumed STOPPED)

Is there an error in that logic or something that we missed?  Let me know where else we should look.

**Comment by 2539469416** [comment]
Actually my idea is very simple, I just think I can use oshi instead of systemctl in java,I can find my java program using systemctl, but I can only find his startup script in oshi，I hope this information can help you
![image](https://user-images.githubusercontent.com/60280379/199638308-4f8371d2-a950-41cd-9f8c-212b416318c6.png)
![image](https://user-images.githubusercontent.com/60280379/199638550-b979d998-0266-424a-8c50-e00b63104769.png)

**Comment by 2539469416** [comment]
Another question is, why can't HWPartition obtain its used capacity

**Comment by dbwiddis** [comment]
> Actually my idea is very simple, I just think I can use oshi instead of systemctl in java,I can find my java program using systemctl, but I can only find his startup script in oshi，I hope this information can help you 

To be honest I'm still confused as to what you're asking for.  Is there a sysctl command you're using to find it?

> Another question is, why can't HWPartition obtain its used capacity

Depends on what you mean by "used".   Wouldn't a partition either be 100% "used" (from a perspective of overall hard drive space) if allocated?  Hard drives have a capacity and you can see how much of that capacity is "used" by a partition or multiple partitions.

Partitions have mount points that connect to FileStores with the matching mount points, where you can see the used space on the file store.

**Comment by 2539469416** [comment]
> 
I want to use oshi instead of linux in java, I want to use OSService instead of systemctl status, HWPartition instead of df, Can HWPartition obtain the capacity of used space? (Thank you very much for your reply)

**Comment by dbwiddis** [comment]
> I want to use oshi instead of linux in java,

A noble goal. :)

> I want to use OSService instead of systemctl status

I would not advise doing that.  `OSService` is primarily optimized for Windows, and while there is an attempt to give reasonable results on Linux, it's not going to be as accurate as the built in service manager.

> HWPartition instead of df. Can HWPartition obtain the capacity of used space? 

You want to use `OSFileStore` for a `df` equivalent.    File Stores and Partitions share a mount point.  There is an example class on the demo project that (tries to) connect them to each other: https://github.com/oshi/oshi/blob/master/oshi-demo/src/main/java/oshi/demo/DiskStoreForPath.java

**Comment by 2539469416** [comment]
> 
:)
