### ISSUE TITLE
Can I use oshi to get a disk acess time?

### ISSUE THREAD

**Issue by cardosoOReis** [oshi/oshi#2238]
I'm trying to calculate the disk usage, so I have to multiply the average number of transfers per second by the access time for the disk. I know I can get the disk transfer time using oshi, but is there any way I can get the acess time?

**Comment by dbwiddis** [comment]
Unfortunately I'm not sure there are any metrics available that measure "access time".  Can you identify any existing source of data that OSHI could obtain these values from?

**Comment by dbwiddis** [comment]
Hey @cardosoOReis I'm not entirely clear on the definition of "access time" but OSHI does provide the total number of reads and writes on the `HWDiskStore` object, along with the total transfer time.

It sounds to me like the "disk usage" metric you seek would just be a delta in `getTransferTime()` divided by the elapsed time between those measurements.

**Comment by cardosoOReis** [comment]
I'm so sorry but I don't understand what you mean with "a delta in getTransferTime() divided by the elapsed time between those measurements.". Do I need to divide the transfer time by the elapsed time two times and get the difference?
Also, if it helps, I found this link https://www.ibm.com/docs/en/informix-servers/14.10?topic=performance-disk-utilization, wich says this: 
> To calculate the processing time at the disk, multiply the number of disk transfers by the average access time. 
That's where I got the idea to get the acess time

**Comment by dbwiddis** [comment]
> I don't understand what you mean with "a delta in getTransferTime() divided by the elapsed time between those measurements.".

Here's some sample OSHI code:
```java
public class Test {

    public static void main(String[] args) {
        HWDiskStore disk = new SystemInfo().getHardware().getDiskStores().get(0);
        System.out.format("Reads: %d, Writes: %d, XferTime: %d, Timestamp: %d%n", disk.getReads(), disk.getWrites(),
                disk.getTransferTime(), disk.getTimeStamp());
        Util.sleep(10000);
        disk.updateAttributes();
        System.out.format("Reads: %d, Writes: %d, XferTime: %d, Timestamp: %d%n", disk.getReads(), disk.getWrites(),
                disk.getTransferTime(), disk.getTimeStamp());
    }
}
```
Here's the output:
```
Reads: 70472443, Writes: 62744300, XferTime: 30886365, Timestamp: 1667953835809
Reads: 70476812, Writes: 62744787, XferTime: 30887206, Timestamp: 1667953845847
```
So we slept for 10 seconds (actually, 10038 milliseconds).  During that time:
 - 70476812-70472443 = 4369 reads occurred
 - 62744787-62744300 = 487 writes occurred
 - 30887206-30886365 = 841 milliseconds of transfer time occurred

From this we can conclude:
 - The disk was transferring data 841 / 10038 of the time (8.3%)
 - The transfer rate was (4369+487)/841 = 5.77 transfers per millisecond - 5774 transfers per second.

The link you provided talks about the access time which is a manufacturer specification for your disk, and suggests you add 20%.

**Comment by cardosoOReis** [comment]
Thank you so much Daniel, this really clears up things for me.  Thanks for helping my dude ^^
