### ISSUE TITLE
AIX disk reads - high readings on idle systems

### ISSUE THREAD

**Issue by mnellemann** [oshi/oshi#2239]
Hi,

It looks like there could be something wrong with AIX disk reads.
On various systems just idling (and no services running) I get high artificial readings from at least 1 device.
The write numbers looks better and more realistic.

Has anyone else seen something similar ?

![aix-disk-reads2](https://user-images.githubusercontent.com/5939693/200501511-ce8c58da-d298-4b75-9bf4-d12b28747ac9.png)
![aix-disk-reads3](https://user-images.githubusercontent.com/5939693/200501521-9b49a9d8-b2be-4dd7-880d-9685c7732f62.png)
![aix-disk-reads4](https://user-images.githubusercontent.com/5939693/200501524-93a956e8-1cf0-4416-ab4d-b9f097b87f53.png)
![aiz-disk-reads1](https://user-images.githubusercontent.com/5939693/200501527-c6d864da-8a10-4177-8e1a-772961980dc2.png)

/Mark

**Comment by dbwiddis** [comment]
Taking a look at the charts, the numbers are indicative of some sort of mathematical issue. 49.8MiB/s on one chart, 99.5MiB/s on another (double the value).  Then there's 3.08MiB/s and 6.16MiB/s, also double.  And the first values are 16x the second values...

**Comment by mnellemann** [comment]
I have done some iostat readings and made a graph of the same time-period.
To me it looks like there's almost no writes at all. 
Let me know if I can provide more details or tests.

[iostat.log](https://github.com/oshi/oshi/files/9968699/iostat.log)


![aix-disk-io](https://user-images.githubusercontent.com/5939693/200771076-07880641-ab62-47e4-bfdf-587fdc61d3b0.png)

**Comment by dbwiddis** [comment]
Can you share the math used to calculate the levels shown on the charts?

**Comment by mnellemann** [comment]
Hi,

The numbers are [written](https://bitbucket.org/mnellemann/sysmon/src/c503032d94d5f32c710aaf48f5101e95a4604b27/plugins/os-base/src/main/java/sysmon/plugins/os_base/BaseDiskExtension.java#lines-102) (as is from oshi) to an InfluxDB database.

In Grafana I use non_negative_difference() on the values to see display throughput.


Numbers in the database looks like:

```SQL
> SELECT * FROM base_disk WHERE hostname = 'pvs-fra2-aix01' ORDER BY time DESC LIMIT 25;
name: base_disk
time                hostname       iotime name   queue read        write
----                --------       ------ ----   ----- ----        -----
1667988104598000000 pvs-fra2-aix01 54610  hdisk0 0     16624121856 3550781952
1667988094653000000 pvs-fra2-aix01 54610  hdisk0 0     16621966336 3550740992
1667988084662000000 pvs-fra2-aix01 54610  hdisk0 0     16619810816 3550704128
1667988074657000000 pvs-fra2-aix01 54609  hdisk0 0     16617655296 3550667264
1667988064604000000 pvs-fra2-aix01 54598  hdisk0 0     16615499776 3550630400
1667988054604000000 pvs-fra2-aix01 54588  hdisk0 0     16613344256 3550269952
1667988044652000000 pvs-fra2-aix01 54587  hdisk0 0     16611188736 3550228992
1667988034657000000 pvs-fra2-aix01 54585  hdisk0 0     16609033216 3550192128
1667988024644000000 pvs-fra2-aix01 54584  hdisk0 0     16606877696 3550155264
1667988014592000000 pvs-fra2-aix01 54584  hdisk0 0     16604722176 3550114304
1667988004612000000 pvs-fra2-aix01 54573  hdisk0 0     16602566656 3550077440
1667987994599000000 pvs-fra2-aix01 54573  hdisk0 0     16599829504 3549544960
1667987984651000000 pvs-fra2-aix01 54573  hdisk0 0     16597673984 3549483520
1667987974643000000 pvs-fra2-aix01 54573  hdisk0 0     16595518464 3549450752
1667987964649000000 pvs-fra2-aix01 54573  hdisk0 0     16593362944 3549409792
1667987954613000000 pvs-fra2-aix01 54573  hdisk0 0     16591207424 3549372928
1667987944643000000 pvs-fra2-aix01 54572  hdisk0 0     16589051904 3549336064
1667987934652000000 pvs-fra2-aix01 54570  hdisk0 0     16586896384 3549061632
1667987924629000000 pvs-fra2-aix01 54570  hdisk0 0     16584740864 3549020672
1667987914604000000 pvs-fra2-aix01 54570  hdisk0 0     16582585344 3548983808
1667987904661000000 pvs-fra2-aix01 54570  hdisk0 0     16580429824 3548946944
1667987894646000000 pvs-fra2-aix01 54570  hdisk0 0     16578274304 3548910080
1667987884595000000 pvs-fra2-aix01 54567  hdisk0 0     16576118784 3548873216
1667987874651000000 pvs-fra2-aix01 54567  hdisk0 0     16573963264 3548557824
1667987864613000000 pvs-fra2-aix01 54567  hdisk0 0     16571807744 3548520960
```

<img width="1192" alt="aix-disk-grafana" src="https://user-images.githubusercontent.com/5939693/200810034-1c63b5df-e8ae-4a5c-acaf-607a233d5456.png">

**Comment by dbwiddis** [comment]
The interwebs suggest troubleshooting to find the offending process. One candidate is "Background Medium Scan"

**Comment by mnellemann** [comment]
Thank you @dbwiddis for looking into this.
This is probably not due to OSHI, but something else, but especially strange as some of the AIX'es have much higher constant reads. 
I will investigate some more and if nothing new comes up, I will close this ticket.

**Comment by mnellemann** [comment]
I will try to dig into this when I have more time.
As this is most likely not related to OSHI, I am closing the issue.

**Comment by dbwiddis** [comment]
@mnellemann Good luck!  I've still been occasionally looking around for what might cause this, and I'm really suspecting some flavor of a background disk integrity scanner (that only runs when idle).  Hope you find it!

**Comment by mnellemann** [comment]
@dbwiddis I did some more testing.

I created a [basic C-program](https://bitbucket.org/mnellemann/aix-disk-stats) to just confirm the readings, and I got the same numbers as I get through OSHI.

This still puzzled me, so I got in touch with AIX devs to confirm I was testing and interpreting the numbers correctly. When they ran my test code they did not get the same constant reads that I get on multiple systems.

It got me thinking - what was the common thing running on all the systems I did my testing on? My very own [agent](https://bitbucket.org/mnellemann/sysmon) using the OSHI library. So somehow my code results in these constant reads. I will try to do some more testing to see if I can narrow down the cause.

Below you can clearly see when I turn my agent off and on :)

```
# ./aix-disk-perfstat
Mon Nov 14 21:39:43 2022 - hdisk0 => reads: [ blocks:  125335662 (       0 ), bytes: 4042316800 (       0 ) ], writes: [ blocks:   55549905 (       0 ), bytes: 2671747584 (       0 ) ]
Mon Nov 14 21:39:53 2022 - hdisk0 => reads: [ blocks:  125339872 (    4210 ), bytes: 4044472320 ( 2155520 ) ], writes: [ blocks:   55549977 (      72 ), bytes: 2671784448 (   36864 ) ]
Mon Nov 14 21:40:03 2022 - hdisk0 => reads: [ blocks:  125344082 (    4210 ), bytes: 4046627840 ( 2155520 ) ], writes: [ blocks:   55550433 (     456 ), bytes: 2672017920 (  233472 ) ]
Mon Nov 14 21:40:13 2022 - hdisk0 => reads: [ blocks:  125348292 (    4210 ), bytes: 4048783360 ( 2155520 ) ], writes: [ blocks:   55550513 (      80 ), bytes: 2672058880 (   40960 ) ]
Mon Nov 14 21:40:23 2022 - hdisk0 => reads: [ blocks:  125352502 (    4210 ), bytes: 4050938880 ( 2155520 ) ], writes: [ blocks:   55550625 (     112 ), bytes: 2672116224 (   57344 ) ]
Mon Nov 14 21:40:33 2022 - hdisk0 => reads: [ blocks:  125352646 (     144 ), bytes: 4051012608 (   73728 ) ], writes: [ blocks:   55550689 (      64 ), bytes: 2672148992 (   32768 ) ]
Mon Nov 14 21:40:43 2022 - hdisk0 => reads: [ blocks:  125352646 (       0 ), bytes: 4051012608 (       0 ) ], writes: [ blocks:   55550697 (       8 ), bytes: 2672153088 (    4096 ) ]
Mon Nov 14 21:40:53 2022 - hdisk0 => reads: [ blocks:  125352646 (       0 ), bytes: 4051012608 (       0 ) ], writes: [ blocks:   55550697 (       0 ), bytes: 2672153088 (       0 ) ]
Mon Nov 14 21:41:03 2022 - hdisk0 => reads: [ blocks:  125352646 (       0 ), bytes: 4051012608 (       0 ) ], writes: [ blocks:   55551345 (     648 ), bytes: 2672484864 (  331776 ) ]
Mon Nov 14 21:41:13 2022 - hdisk0 => reads: [ blocks:  125352654 (       8 ), bytes: 4051016704 (    4096 ) ], writes: [ blocks:   55551449 (     104 ), bytes: 2672538112 (   53248 ) ]
Mon Nov 14 21:41:23 2022 - hdisk0 => reads: [ blocks:  125357272 (    4618 ), bytes: 4053381120 ( 2364416 ) ], writes: [ blocks:   55552593 (    1144 ), bytes: 2673123840 (  585728 ) ]
Mon Nov 14 21:41:33 2022 - hdisk0 => reads: [ blocks:  125361482 (    4210 ), bytes: 4055536640 ( 2155520 ) ], writes: [ blocks:   55552665 (      72 ), bytes: 2673160704 (   36864 ) ]
Mon Nov 14 21:41:43 2022 - hdisk0 => reads: [ blocks:  125365692 (    4210 ), bytes: 4057692160 ( 2155520 ) ], writes: [ blocks:   55552745 (      80 ), bytes: 2673201664 (   40960 ) ]
Mon Nov 14 21:41:53 2022 - hdisk0 => reads: [ blocks:  125369902 (    4210 ), bytes: 4059847680 ( 2155520 ) ], writes: [ blocks:   55552817 (      72 ), bytes: 2673238528 (   36864 ) ]
Mon Nov 14 21:42:03 2022 - hdisk0 => reads: [ blocks:  125374112 (    4210 ), bytes: 4062003200 ( 2155520 ) ], writes: [ blocks:   55553553 (     736 ), bytes: 2673615360 (  376832 ) ]
Mon Nov 14 21:42:13 2022 - hdisk0 => reads: [ blocks:  125378322 (    4210 ), bytes: 4064158720 ( 2155520 ) ], writes: [ blocks:   55553625 (      72 ), bytes: 2673652224 (   36864 ) ]
Mon Nov 14 21:42:23 2022 - hdisk0 => reads: [ blocks:  125382532 (    4210 ), bytes: 4066314240 ( 2155520 ) ], writes: [ blocks:   55553697 (      72 ), bytes: 2673689088 (   36864 ) ]
Mon Nov 14 21:42:33 2022 - hdisk0 => reads: [ blocks:  125386742 (    4210 ), bytes: 4068469760 ( 2155520 ) ], writes: [ blocks:   55553777 (      80 ), bytes: 2673730048 (   40960 ) ]
Mon Nov 14 21:42:43 2022 - hdisk0 => reads: [ blocks:  125390952 (    4210 ), bytes: 4070625280 ( 2155520 ) ], writes: [ blocks:   55553849 (      72 ), bytes: 2673766912 (   36864 ) ]
Mon Nov 14 21:42:53 2022 - hdisk0 => reads: [ blocks:  125395162 (    4210 ), bytes: 4072780800 ( 2155520 ) ], writes: [ blocks:   55553921 (      72 ), bytes: 2673803776 (   36864 ) ]
Mon Nov 14 21:43:03 2022 - hdisk0 => reads: [ blocks:  125399372 (    4210 ), bytes: 4074936320 ( 2155520 ) ], writes: [ blocks:   55554497 (     576 ), bytes: 2674098688 (  294912 ) ]
Mon Nov 14 21:43:13 2022 - hdisk0 => reads: [ blocks:  125403582 (    4210 ), bytes: 4077091840 ( 2155520 ) ], writes: [ blocks:   55554577 (      80 ), bytes: 2674139648 (   40960 ) ]
Mon Nov 14 21:43:23 2022 - hdisk0 => reads: [ blocks:  125407792 (    4210 ), bytes: 4079247360 ( 2155520 ) ], writes: [ blocks:   55554649 (      72 ), bytes: 2674176512 (   36864 ) ]
Mon Nov 14 21:43:33 2022 - hdisk0 => reads: [ blocks:  125412002 (    4210 ), bytes: 4081402880 ( 2155520 ) ], writes: [ blocks:   55554721 (      72 ), bytes: 2674213376 (   36864 ) ]
Mon Nov 14 21:43:43 2022 - hdisk0 => reads: [ blocks:  125412002 (       0 ), bytes: 4081402880 (       0 ) ], writes: [ blocks:   55554793 (      72 ), bytes: 2674250240 (   36864 ) ]
Mon Nov 14 21:43:53 2022 - hdisk0 => reads: [ blocks:  125412002 (       0 ), bytes: 4081402880 (       0 ) ], writes: [ blocks:   55554793 (       0 ), bytes: 2674250240 (       0 ) ]
Mon Nov 14 21:44:03 2022 - hdisk0 => reads: [ blocks:  125412002 (       0 ), bytes: 4081402880 (       0 ) ], writes: [ blocks:   55555537 (     744 ), bytes: 2674631168 (  380928 ) ]
Mon Nov 14 21:44:13 2022 - hdisk0 => reads: [ blocks:  125412002 (       0 ), bytes: 4081402880 (       0 ) ], writes: [ blocks:   55555537 (       0 ), bytes: 2674631168 (       0 ) ]
```

**Comment by dbwiddis** [comment]
Well that's curious!

And that's a lot of bandwidth.  I know OSHI reads `procfs` for process info, but on Linux that's a pseudo filesystem. I wonder if it's counting as a read on AIX?

**Comment by dbwiddis** [comment]
Quick update.  I've reproduced the high reads by just spamming SystemInfoTest and narrowed it down to something in the `getDisks()` sequence.

I also found a bug (2 actually) where the change we just put in for logical processor counts breaks the default load between ticks calculations on AIX...

**Comment by dbwiddis** [comment]
Further digging shows use of `ls` and `lscfg` and `lspv` to get disk info.  That's only on initial reading of the disks, not on update of statistics, but if your metric collection always reads a new set of disks and partitions, this could be the source of the problem.

**Comment by dbwiddis** [comment]
OK, looks like [here](https://bitbucket.org/mnellemann/sysmon/src/c503032d94d5f32c710aaf48f5101e95a4604b27/plugins/os-base/src/main/java/sysmon/plugins/os_base/BaseDiskExtension.java#lines-85) you are fetching a new list of HWDiskStore every 10 seconds.  I suspect (but haven't confirmed) that the `lspv` command (specifically `lspv -p hdisk0` or similar) to grab partition info is generating all the reads.

Open to ideas on whether OSHI or your agent should try to optimize/memoize any of this.

**Comment by mnellemann** [comment]
Ahh, interesting. 
I can move ```List<HWDiskStore> diskStores = hardwareAbstractionLayer.getDiskStores();``` so it's only called once or seldom. I guess that it's possible that a new disk could get online, which I would not detect without refreshing my List once in a while.
I thought all the information was sourced from [libperfstat.h](https://www.ibm.com/docs/en/aix/7.3?topic=files-libperfstath-file) somehow.

**Comment by dbwiddis** [comment]
> Ahh, interesting. I can move `List<HWDiskStore> diskStores = hardwareAbstractionLayer.getDiskStores();` so it's only called once or seldom. 

Probably the best plan for most Unixes.

> I guess that it's possible that a new disk could get online, which I would not detect without refreshing my List once in a while. 

Yeah, a layered refresh is kinda needed for that.

> I thought all the information was sourced from [libperfstat.h](https://www.ibm.com/docs/en/aix/7.3?topic=files-libperfstath-file) somehow.

Well, the stats themselves are, you can do an `store.updateAttributes()` as often as you want to update reads/writes/etc. without impacting reads.  But the whole "where are the disks and where are their partitions" isn't easy to do without command line, on AIX at least.

**Comment by dbwiddis** [comment]
I can also look into caching the lspv call.

**Comment by mnellemann** [comment]
Great to know, thanks.
I will refactor my code (anyway) and see how it turns out in relation to the disk readings.

**Comment by mnellemann** [comment]
Looks much better already - many thanks.

```
# ./aix-disk-perfstat
Tue Nov 15 09:01:13 2022 - hdisk0 => reads: [ blocks:  142069778 (       0 ), bytes: 4020249600 (       0 ) ], writes: [ blocks:   56360689 (       0 ), bytes: 3086868992 (       0 ) ]
Tue Nov 15 09:01:23 2022 - hdisk0 => reads: [ blocks:  142069778 (       0 ), bytes: 4020249600 (       0 ) ], writes: [ blocks:   56360689 (       0 ), bytes: 3086868992 (       0 ) ]
Tue Nov 15 09:01:33 2022 - hdisk0 => reads: [ blocks:  142069778 (       0 ), bytes: 4020249600 (       0 ) ], writes: [ blocks:   56360689 (       0 ), bytes: 3086868992 (       0 ) ]
Tue Nov 15 09:01:43 2022 - hdisk0 => reads: [ blocks:  142069778 (       0 ), bytes: 4020249600 (       0 ) ], writes: [ blocks:   56360689 (       0 ), bytes: 3086868992 (       0 ) ]
Tue Nov 15 09:01:53 2022 - hdisk0 => reads: [ blocks:  142069778 (       0 ), bytes: 4020249600 (       0 ) ], writes: [ blocks:   56360689 (       0 ), bytes: 3086868992 (       0 ) ]
Tue Nov 15 09:02:03 2022 - hdisk0 => reads: [ blocks:  142069778 (       0 ), bytes: 4020249600 (       0 ) ], writes: [ blocks:   56361105 (     416 ), bytes: 3087081984 (  212992 ) ]
Tue Nov 15 09:02:13 2022 - hdisk0 => reads: [ blocks:  142069778 (       0 ), bytes: 4020249600 (       0 ) ], writes: [ blocks:   56361105 (       0 ), bytes: 3087081984 (       0 ) ]
Tue Nov 15 09:02:23 2022 - hdisk0 => reads: [ blocks:  142069778 (       0 ), bytes: 4020249600 (       0 ) ], writes: [ blocks:   56361105 (       0 ), bytes: 3087081984 (       0 ) ]
Tue Nov 15 09:02:33 2022 - hdisk0 => reads: [ blocks:  142069778 (       0 ), bytes: 4020249600 (       0 ) ], writes: [ blocks:   56361105 (       0 ), bytes: 3087081984 (       0 ) ]
Tue Nov 15 09:02:43 2022 - hdisk0 => reads: [ blocks:  142069778 (       0 ), bytes: 4020249600 (       0 ) ], writes: [ blocks:   56361105 (       0 ), bytes: 3087081984 (       0 ) ]
Tue Nov 15 09:02:53 2022 - hdisk0 => reads: [ blocks:  142069778 (       0 ), bytes: 4020249600 (       0 ) ], writes: [ blocks:   56361105 (       0 ), bytes: 3087081984 (       0 ) ]
Tue Nov 15 09:03:03 2022 - hdisk0 => reads: [ blocks:  142069778 (       0 ), bytes: 4020249600 (       0 ) ], writes: [ blocks:   56361417 (     312 ), bytes: 3087241728 (  159744 ) ]
Tue Nov 15 09:03:13 2022 - hdisk0 => reads: [ blocks:  142069778 (       0 ), bytes: 4020249600 (       0 ) ], writes: [ blocks:   56361417 (       0 ), bytes: 3087241728 (       0 ) ]
Tue Nov 15 09:03:23 2022 - hdisk0 => reads: [ blocks:  142069778 (       0 ), bytes: 4020249600 (       0 ) ], writes: [ blocks:   56361417 (       0 ), bytes: 3087241728 (       0 ) ]
```

**Comment by mnellemann** [comment]
Just wanted to show how it looks after refreshing list of disk-stores hourly.
It's still a high number of reads though, and strange that it's different for hdisk0 vs hdisk1/hdisk2.
Maybe it depends on the use (lv's or fs's) of the device.

<img width="815" alt="oshi-diskstores" src="https://user-images.githubusercontent.com/5939693/201930790-218aa51b-3a23-4252-a7f1-c2f138b90b83.png">

```
+ hdisk0           U78D2.001.WZS0B5H-P1-C50-C1-L1     NVMe 4K Flash Disk
+ hdisk1           U78D2.001.WZS0B5H-P1-C50-C1-L2     NVMe 4K Flash Disk
+ hdisk2           U78D2.001.WZS0B5H-P1-C50-C1-L3     NVMe 4K Flash Disk
```

**Comment by dbwiddis** [comment]
Great to see the improvement.

I'll try to figure out a way to cache or memoize the partitions per-disk.  

If you have any insight into a better way than `lspv` to get the sizes of partitions, that would also be a better way of doing it than we currently do.   I'm limited to playing with the AIX boxes on the GNU compile farm, and to be honest a lot of the AIX porting work was "just get it working" without really looking at performance improvements, so I appreciate your reports here.

**Comment by mnellemann** [comment]
I will keep it in mind and do some more testing :)

After a brief look at the files in ```oshi-core/src/main/java/oshi/driver/unix/aix``` and looking at the commands being called, a suggestion is to add the '-n' flag to the ```ls /dev``` command. It shaved alot of time of (in my test) and would avoid lookup of user/group info for each file. I was not able to test any modifications to the code - have to spend some more time looking into tests and how to build.

```diff
diff --git a/oshi-core/src/main/java/oshi/driver/unix/aix/Ls.java b/oshi-core/src/main/java/oshi/driver/unix/aix/Ls.java
index 4c7c5d1526..c720cb1a06 100644
--- a/oshi-core/src/main/java/oshi/driver/unix/aix/Ls.java
+++ b/oshi-core/src/main/java/oshi/driver/unix/aix/Ls.java
@@ -32,9 +32,13 @@ public final class Ls {
          $ ls -l /dev
         brw-rw----  1 root system 10,  5 Sep 12  2017 hd2
         brw-------  1 root system 20,  0 Jun 28  1970 hdisk0
+
+        $ ls -n /dev
+        brw-rw----    1 0        0            10,  5 Feb 11 2022  /dev/hd2
+        brw-------    1 0        0            19,  1 Feb 11 2022  /dev/hdisk1
          */
         Map<String, Pair<Integer, Integer>> majMinMap = new HashMap<>();
-        for (String s : ExecutingCommand.runNative("ls -l /dev")) {
+        for (String s : ExecutingCommand.runNative("ls -n /dev")) {
             // Filter to block devices
             if (!s.isEmpty() && s.charAt(0) == 'b') {
                 // Device name is last space-delim string
diff --git a/oshi-core/src/main/java/oshi/driver/unix/aix/Lspv.java b/oshi-core/src/main/java/oshi/driver/unix/aix/Lspv.java
index 6fa89a19d1..0fe3b05862 100644
--- a/oshi-core/src/main/java/oshi/driver/unix/aix/Lspv.java
+++ b/oshi-core/src/main/java/oshi/driver/unix/aix/Lspv.java
@@ -66,7 +66,7 @@ public final class Lspv {
         // Convert to megabytes
         ppSize <<= 20;
         /*-
-         $ lspv -p hdisk0
+         $ lspv -L -p hdisk0
         hdisk0:
         PP RANGE  STATE   REGION        LV NAME             TYPE       MOUNT POINT
         1-1     used    outer edge    hd5                 boot       N/A
@@ -96,7 +96,7 @@ public final class Lspv {
         Map<String, String> mountMap = new HashMap<>();
         Map<String, String> typeMap = new HashMap<>();
         Map<String, Integer> ppMap = new HashMap<>();
-        for (String s : ExecutingCommand.runNative("lspv -p " + device)) {
+        for (String s : ExecutingCommand.runNative("lspv -L -p " + device)) {
             String[] split = ParseUtil.whitespaces.split(s.trim());
             if (split.length >= 6 && "used".equals(split[1])) {
                 // Region may have two words, so count from end

```

**Comment by dbwiddis** [comment]
Thanks for the suggestion on -n.

I did just trace through every command used for AIX disks, and indeed the `lspv` calls are definitely a problem:
```bash
iostat -d  | grep hdisk1 && lspv -L hdisk1 > /dev/null && iostat -d  | grep hdisk1 && lspv -p hdisk1 > /dev/null && iostat -d | grep hdisk1
```
```
Disks:         % tm_act     Kbps      tps    Kb_read   Kb_wrtn
hdisk1            5.1     544.6      12.1    7154095  11178465549
hdisk1            5.1     544.6      12.1    7155147  11178465565
hdisk1            5.1     544.6      12.1    7156200  11178465585
```
That's 1052 or 1053 KiB for each call.  I could trivially cut the time in half by combining the two calls as you suggest:
```bash
iostat -d | grep hdisk1 && lspv -L -p hdisk1 > /dev/null && iostat -d | grep hdisk1
```
```
Disks:         % tm_act     Kbps      tps    Kb_read   Kb_wrtn
hdisk1            5.1     544.7      12.1    7157252  11178989602
hdisk1            5.1     544.7      12.1    7158305  11178989795
```
However inspecting the output of that, I only get the same output as `-p`, the `-L` seems lost.

**Comment by dbwiddis** [comment]
Eh, actually the `-L` is combinable but the output for just plain `lspv` which is needed for some size values doesn't match the `-p` variant that shows where that's used.   Amusingly, there's a `-m` that gives similar input in a longer form -- and takes a lot more disk too.

I'm thinking at this point caching is the right way to go.  People don't repartition their drives without shutting down, right?

**Comment by mnellemann** [comment]
I think it's a common use-case to add extra disks to extend volumes on running systems.
But - in this case, it's also reasonable to reload any code using OSHI.
Another way could be to call a *reload* method on the *store*, so your application could be in charge of when (if at all needed) to reload.

**Comment by dbwiddis** [comment]
> But - in this case, it's also reasonable to reload any code using OSHI.

While not 100% consistent, I've been trying over the years to conform to a pattern of "If you create a new SystemInfo() object, you re-load everything." 

Not sure exactly where to stick such a cache to follow this pattern (possibly its own class) but I'll try to keep to that.

**Comment by dbwiddis** [comment]
I just ended up implementing a static cache for this in a `ConcurrentHashMap`. Trying to implement "reload on new SystemInfo" was too hacky.   I really don't think partitions on a disk will ever change while a JVM is running and this is a safe assumption.

Should be available for you to test in snapshot. Working toward a 6.4.0 release sometime soon-ish.
