### ISSUE TITLE
Maven plugin configuration

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#224]
Short list of issues related to Maven plugins, arranged in roughly decreasing priority order.  All are probably fixable with a few lines in the `pom.xml` or other config files by a knowledgeable person.  I'll research and fix what I can but will need help on this one.

**maven-javadoc-plugin**
- Breaks the build during `release:perform` step.  
- The error message is: `[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.5.1:site (default-site) on project oshi-parent: failed to get report for org.apache.maven.plugins:maven-javadoc-plugin: Failed to execute goal on project oshi-json: Could not resolve dependencies for project com.github.dblock:oshi-json:jar:3.0: Failure to find com.github.dblock:oshi-core:jar:3.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced`
- The error occurs when the goals `deploy site-deploy` (the default) are executed together on a multi module project.  [This StackOverflow post](http://stackoverflow.com/questions/23120594/failed-to-resolve-artifact-when-i-run-mvn-deploy-site-deploy-but-works-fine-if) describes a similar problem (but no solution).  There's also a [post on the maven mailing list](https://mail-archives.apache.org/mod_mbox/maven-users/201304.mbox/%3CCAB56zCUv2pm8YjhUxObTDUo5tR4Hj7UCshCP_RxXarHqrZ4itQ@mail.gmail.com%3E) describing a similar situation (again, no solution).
- The workaround is to run `mvn install` to put a version of the code in my local repository.  Unfortunately the way `mvn release:prepare` works, the `pom.xml` version I need to install is the tag in the first of its two commits.   So after I run the prepare step, I back up to the tag on my local repository, install, then pull to catch up again, and it works.  I'm thinking that step could be automated somewhere in the release process.

**maven-source-plugin**
- In a review of our pom by another maven expert, it was suggested to [override the default configuration](https://github.com/dblock/oshi/blob/master/pom.xml#L337) of the `attach-sources` id to speed up the build, [citing this JIRA](https://issues.apache.org/jira/browse/MSOURCES-13). Why it overrides instead of implementing the [upcoming Maven 3.4.0 behavior here](https://issues.apache.org/jira/browse/MNG-5940) which supposedly fixes it, I don't know.  
- The bottom line is that with the override in, sources weren't being uploaded to the central repository so the package in the staging repository couldn't be closed/released. Without the override, we're running `generate-sources` twice which slows down the build but is, at least, harmless. 
- Would be nice to get to the bottom of this and implement a fix that actually works.

**jacoco-maven-plugin**
- I managed to get this configured correctly to [report to coveralls](https://coveralls.io/github/dblock/oshi?branch=master) as part of our [Travis](https://github.com/dblock/oshi/blob/master/.travis.yml#L7) builds.  However, the [JaCoCo page on the site](http://dblock.github.io/oshi/jacoco-aggregate/index.html) shows all zeroes.  Probably related, I get this log printout during deployment of `oshi-dist`: `Skipping JaCoCo execution due to missing execution data file.`  
- A review of commits to `gh-pages` shows that the last commit removed the data (jacoco.xml); it was present in the previous commit for `oshi-json` which replaced the data in the commit before that for `oshi-core`.
- There is a report page for `oshi-json` [here](http://dblock.github.io/oshi/oshi-json/jacoco-aggregate/index.html) but the coverage doesn't match coveralls.  And the `oshi-core` report [here](http://dblock.github.io/oshi/oshi-core/jacoco-aggregate/index.html) is empty.
- This is probably some simple configuration where we need to either tell it this is a multimodule build and to combine all the data (as apparently happens with coveralls) or to publish the reports for each module separately instead of overwriting each other.

**maven-surefire-plugin**
- [The report is empty](http://dblock.github.io/oshi/surefire-report.html).  There's actually a report for the modules, however, [here](http://dblock.github.io/oshi/oshi-core/surefire-report.html) and [here](http://dblock.github.io/oshi/oshi-json/surefire-report.html) but it's not linked anywhere.
- The problem/fix is probably related to the jacoco config above.

**maven-pmd-plugin** and **findbugs-maven-plugin**
- No longer seeing either of these reports on the site. 
- Both reports are available at the subdirectory level http://dblock.github.io/oshi/oshi-core/findbugs / http://dblock.github.io/oshi/oshi-json/findbugs and http://dblock.github.io/oshi/oshi-core/pmd / http://dblock.github.io/oshi/oshi-json/pmd so the problem is that the site plugin isn't seeing them
- It looks like the pmd plugin takes `<aggregate>true</aggregate>` but not sure if that's all that's needed.
- Findbugs needs configuring to remove common non-bugs like "unused" and "unread" fields of structures (I think I know how to do this).

**maven-checkstyle-plugin**
- Checkstyle [reports 4374 errors](http://dblock.github.io/oshi/checkstyle-aggregate.html). I need to tell it to ignore certain types of errors that result from our formatting (trailing spaces after the \* in javadoc headers, for example, no javadoc for every single private variable, etc. to filter down the list to things that are actually meaningful to check.

**Comment by dbwiddis** [comment]
@hazendaz Have you had a chance to look in to any of these yet?  I'm planning on a 3.1 release next week sometime.  No big deal if you don't have the time, as I've got sufficient workarounds.

**Comment by hazendaz** [comment]
Oops sorry...forgot there where still outstanding concerns.  I was actually looking over things this last weekend.  I didnt have in my mind any issues.  Ill take a look tonight using your list.

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Jul 27, 2016 at 4:58 AM -0400, "dbwiddis" <notifications@github.com<mailto:notifications@github.com>> wrote:


@hazendaz<https://github.com/hazendaz> Have you had a chance to look in to any of these yet? I'm planning on a 3.1 release next week sometime. No big deal if you don't have the time, as I've got sufficient workarounds.

-

**Comment by hazendaz** [comment]
I had some other pressing issues.  Will look this weekend.

**Comment by dbwiddis** [comment]
Take your time. It's low priority.

**Comment by dbwiddis** [comment]
Made an attempt to look into these with the 3.1.1 release.  Despite two glasses of an excellent value (good but cheap) merlot, made little progress.    Update on what I looked into:

**maven-javadoc-plugin**  -  Didn't even look at this. Content with my workaround until someone with more time on their hands can solve this.  

**maven-source-plugin** - Didn't look at this either. Question will be moot with maven 3.4.  It's working now and inclined to ignore this issue unless someone who knows what they are doing can spend 5 seconds saying "oh, do this!"

**jacoco-maven-plugin** - Looks like a potential solution [here](https://github.com/trautonen/coveralls-maven-plugin/issues/64#issuecomment-73384393).

**maven-pmd-plugin** - Tried the `<aggregate>true</aggregate>` config option but it doesn't seem to have done anything useful.  Might even have made it worse.

**findbugs-maven-plugin** - No official multi-module support but [a workaround here](http://stackoverflow.com/questions/34829200/aggregate-findbugs-report-in-maven-3-0-5).

**Comment by hazendaz** [comment]
Not sure why you are specifically having any issues.  I run all of these on large scale multimodule projects and all fully work without error.  Can you post again what specific issues you currently have?

Get Outlook for Android<https://aka.ms/ghei36>



On Fri, Aug 5, 2016 at 3:56 AM -0400, "dbwiddis" <notifications@github.com<mailto:notifications@github.com>> wrote:


Made an attempt to look into these with the 3.1.1 release. Despite two glasses of an excellent value (good but cheap) merlot, made little progress. Update on what I looked into:

maven-javadoc-plugin - Didn't even look at this. Content with my workaround until someone with more time on their hands can solve this.

maven-source-plugin - Didn't look at this either. Question will be moot with maven 3.4. It's working now and inclined to ignore this issue unless someone who knows what they are doing can spend 5 seconds saying "oh, do this!"

jacoco-maven-plugin - Looks like a potential solution here<https://github.com/trautonen/coveralls-maven-plugin/issues/64#issuecomment-73384393>.

maven-pmd-plugin - Tried the <aggregate>true</aggregate> config option but it doesn't seem to have done anything useful. Might even have made it worse.

findbugs-maven-plugin - No official multi-module support but a workaround here<http://stackoverflow.com/questions/34829200/aggregate-findbugs-report-in-maven-3-0-5>.

-

**Comment by hazendaz** [comment]
Try lloking at me base parent project.

Get Outlook for Android<https://aka.ms/ghei36>



On Fri, Aug 5, 2016 at 3:56 AM -0400, "dbwiddis" <notifications@github.com<mailto:notifications@github.com>> wrote:


Made an attempt to look into these with the 3.1.1 release. Despite two glasses of an excellent value (good but cheap) merlot, made little progress. Update on what I looked into:

maven-javadoc-plugin - Didn't even look at this. Content with my workaround until someone with more time on their hands can solve this.

maven-source-plugin - Didn't look at this either. Question will be moot with maven 3.4. It's working now and inclined to ignore this issue unless someone who knows what they are doing can spend 5 seconds saying "oh, do this!"

jacoco-maven-plugin - Looks like a potential solution here<https://github.com/trautonen/coveralls-maven-plugin/issues/64#issuecomment-73384393>.

maven-pmd-plugin - Tried the <aggregate>true</aggregate> config option but it doesn't seem to have done anything useful. Might even have made it worse.

findbugs-maven-plugin - No official multi-module support but a workaround here<http://stackoverflow.com/questions/34829200/aggregate-findbugs-report-in-maven-3-0-5>.

-

**Comment by hazendaz** [comment]
Site plugin doesn't appear to have any issues.  However, I would suggest adding the site files to the submodules as well.  The reason being that if you were to run site off a submodule it will not produce the same as it does off parent.  That could be possible issue there.  I was able to run site and deploy without any issues but think you are already there too as there was a cut from a few days ago.

Jacoco looks like it is working properly.  That is what is used on coveralls and the fact that it states 92% seems correct.

Javadoc plugin, I don't see any issues with this.

Findbugs/pmd, not sure what you are trying to get out of those.  They are based on module and will report on module.  I think you are wanting them aggregated but not sure how that really matters.  The point to those is for us the developers to fix broken stuff in the code.  I don't think we need them aggregated as they are specific to a module.

You might want to reach out to sonarqube.com and get this project registered.  They offer free hosting for open source now (beta invite).  Sonarqube will aggregate what you are after and internally is basically all these various scanning tools.

**Comment by hazendaz** [comment]
I just rebased.  there are issues with Javadoc as it's not finished in a small area.  I'm fixing that.  Also, site on each submodule was an issue even on gh-pages so fixed that too.  I'll get a PR shortly for those small issues.

**Comment by dbwiddis** [comment]
findbugs/pmd is fine on submodule (where it actually displays).  The issue is there is no link from the main site to get to them... you have to manually edit/remember the URL.   Not a big deal as I can have Coverity report from both of those, and remove them as plugins.  Glad to know Sonar is supporting open source now.

The only issue that's really a concern is the error I got from the javadoc plugin during the normal release process.

**Comment by hazendaz** [comment]
When you are ready for next release, you want to have me push the release?  Might be useful to see if we both have same issue.  I submitted a PR for javadoc fix (small one).  I need to research the site a bit more.  I pushed up snapshot but not exactly what I wanted from that.  Leaves a dead readme link and makes me want to review master again.  I'll have something on that later but will be messing with gh pages for a bit to just confirm things.

**Comment by dbwiddis** [comment]
Sure.... code is in for 3.2 now, just waiting for the individual who requested #242 to test the #244 fix... but if you have spare time I've done testing myself so it should be good

**Comment by dbwiddis** [comment]
(Also merge #244 before releasing!)  You can always just push the release but drop rather than release the maven staging... and delete the tags on github.  I've done that plenty of time for failed releases.

**Comment by dbwiddis** [comment]
OK, all pull requests merged.  If you want to cut a 3.2 release you can, otherwise I'll probably wait a bit to play around with the various analysis tools and try to tune things up.

**Comment by hazendaz** [comment]
I can try tonight but need to look at unit tests.  I have some failures during build :(

Get Outlook for Android<https://aka.ms/ghei36>



On Mon, Aug 8, 2016 at 1:30 AM -0400, "dbwiddis" <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, all pull requests merged. If you want to cut a 3.2 release you can, otherwise I'll probably wait a bit to play around with the various analysis tools and try to tune things up.

-

**Comment by dbwiddis** [comment]
We're [on Sonar](https://sonarqube.com/dashboard/index/com.github.dblock:oshi-parent).  

Haven't yet figured out how to set it up in maven yet but I'm sure I'll get there.

**Comment by hazendaz** [comment]
Add the sonar token in your local .m2/settings similar to this.

```xml
    <profile>
      <id>sonar</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <sonar.host.url>https://sonarqube.com/</sonar.host.url>
        <sonar.login>{token}</sonar.login>
      </properties>
    </profile>
```

Then run mvn sonar:sonar.

You can also add this plugin if using eclipse.

http://eclipse.sonarlint.org/

That adds a little server like tab where you can add multiple sonars.  This replaces the legacy sonar integration.  This also lints the projects which is much nicer than in the past.

And finally, I think you can add this into the builds.  mybatis-3 module has done that already so you might be able to figure that out from there.  I haven't gotten that far yet.

*** might be a few before I can attempt a release.  So if you are already there, go ahead and I can just try the false releases laster that you mentioned (push then drop).  I had to switch gears back to long overdue formatter maven plugin getting released to bring it up to mars/neon support plus some things over at mybatis of pressing need.  Probably will be a week before I free up any extra time.  I'm trying to make some travel plans (work and pleasure) at the same time so pretty busy ***

**Comment by dbwiddis** [comment]
Take your time, really.  I only pushed out 3.1 a week ago so I'm in no hurry to push 3.2 (and then get a new feature request the same day, likely).  And now I have a whole bunch of new issues Sonar wants me to fix. :)

Can you tell me where your tests are failing, though, so I can see if I can figure it out?

**Comment by hazendaz** [comment]
```code
Running oshi.hardware.SensorsTest
[main] ERROR oshi.util.platform.windows.WmiUtil - Could not connect to namespace root\OpenHardwareMonitor. Error code = 0x8004100e
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.036 sec <<< FAILURE! - in oshi.hardware.SensorsTest
testSensors(oshi.hardware.SensorsTest)  Time elapsed: 0.035 sec  <<< FAILURE!
java.lang.AssertionError
        at oshi.hardware.SensorsTest.testSensors(SensorsTest.java:38)
```

**Comment by dbwiddis** [comment]
The error is expected if you don't have OHM.  The failed test is a temperature below 0C (or above 100C). I can easily trap that bit but I'm curious how it got there.  Any chance you can tell me if any of these returns an actual value?
```
wmic /NAMESPACE:\\root\cimv2 PATH Win32_Temperature GET CurrentReading
wmic /NAMESPACE:\\root\cimv2 PATH Win32_TemperatureProbe GET CurrentReading
wmic /NAMESPACE:\\root\cimv2 PATH Win32_PerfFormattedData_Counters_ThermalZoneInformation GET Temperature
wmic /NAMESPACE:\\root\wmi PATH MSAcpi_ThermalZoneTemperature GET CurrentTemperature
```

**Comment by hazendaz** [comment]
1) Error: Description = Not found
2) Blank
3) Temperature 303 301
4) Node - BITFENIXGHOST ERROR: Description = Access denied

I'm running windows 10 professional.  If those values after temperature are expected to be something reasonable then it's probably not reporting correctly.  I think I'd be on fire otherwise.  More likely has something to do with access denied.

**Comment by dbwiddis** [comment]
No... the problem is that it's not properly parsing #3 with the 303 301  (2 different CPU temperatures I presume).  It's supposed to be in 10 x degress Kelvin (above 2715, usually around 3300-3400 or so).    I'll have to dig around to see what units the 303 and 301 are in.

**Comment by dbwiddis** [comment]
Annd.... supposed to be degrees kelvin.  (32C is a very cool CPU!)  So I'll fix that calculation.

**Comment by hazendaz** [comment]
Nice!  So that means I did something right when I built my first ever PC after years of suffering with HP and the likes.

**Comment by dbwiddis** [comment]
Yep!  Well below the average range: http://www.computerhope.com/issues/ch000687.htm  (My Macbook Pro i7 runs about 65-70 usually.)  I've just committed a fix.

**Comment by hazendaz** [comment]
build is working for me now.  Thanks.

**Comment by dbwiddis** [comment]
Excellent. mybatis-3 just runs the mvn commandline in the after-success script. Easy enough to set up.

**Comment by dbwiddis** [comment]
Re-summarizing issues in brief.  Detail in the top issue.  The first one listed is really the main concern here; the rest are mostly just being a perfectionist.

**maven-javadoc-plugin**

- Breaks during `release:perform`.  Tags are fine, upload to staging is fine, but it fails pushing to gh_pages. Error message about not finding dependencies for the other modules (e.g., `oshi-json` can't locate the dependency for `oshi-core`.)  
- Workaround is to run `mvn install` with the pom.xml file pointing to the version being released. 
- Note that `release:prepare` advances to this version, tags it, then advances again, so in order to `mvn install` you have to back up one commit to the tag.
- Would be nice to try to 'mvn install' at the tag during the `release:prepare` step.

**maven-source-plugin**

- Review comments in `pom.xml`.  Low priority, will be irrelevant in maven 3.4 anyway.

**jacoco-maven-plugin**

- Is working correctly (as evidenced by values in coveralls, codecov, etc.) but the report on the site shows all zeroes (probably the `dist` version is the one showing).   Really probably don't need the report on the site at all... can the report just be removed?

**maven-surefire-plugin**, **maven-pmd-plugin** and **findbugs-maven-plugin**

All report at the subdirectory level (e.g., oshi/oshi-core/findbugs) but there are no links from the main site to the module sites, and the module site reports are empty.  Probably an easy configuration somewhere.  Also, as all of these are duplicated by other tools (sonarqube, coverity) they can also just be removed.

**maven-checkstyle-plugin**

More of a note to self to figure out how to configure it to ignore certain errors.  Or remove it since Sonar, etc. also do this.

P.S. SonarLint is AWESOME.

**Comment by hazendaz** [comment]
@dbwiddis Javadoc plugin issue.  It should be fixed now.  When you release again can you see if it's working properly?  I ran into the same issue and sort of surpised I didn't see it before.  I did some research and found that maven fixed it on 2.10.4.  It was in 2.10.3.  It may or may not have existed for years.  I think I had issues on waffle before getting it released and at multiple times had messed around with configuration on it.  I thought I had fixed the issues there but maybe I had been doing your same work around and/or was getting versions build before it uploaded.  Not sure and not ringing any bells.  Anyway, maven talks about it [here](https://issues.apache.org/jira/browse/MJAVADOC-437).

**Comment by dbwiddis** [comment]
I'm pretty sure I saw that issue at some point in my searchings, but a look at git history shows I was using 2.10.4 when I saw the error (and have been since the multi-module build).

That said, I just tried editing the pom version (to 3.3-TEST) and running `mvn deploy site-deploy` and it appeared to work.  

Anyway, I'll try it again with `release:perform` next time and see if it's still there.

**Comment by hazendaz** [comment]
I agree the history looked like it must have been ok at the time it was reported.  I had some suspicion it would work.

I'm going to run a release on waffle today as well.  I'm betting I was seeing the issue but was not realy realizing why it was failing.  In my day job, we had some networking issues that were causing errors during release so I had been doing that work around for better part of a year.  That issue was resolved then I ran into this.  I recalled you running into this so immediately I pulled up this issue to take a look and sure enough that was my problem.  Due to the way we do things at the day job it will be a while before I can confirm a fix but waffle generally has the same setup and was the model for maven use on oshi so hopefully we can at least put that to bed entirely.

At the very least it is encouraging that your test worked and if waffle works, I'll feel a bit better.  To be honest I cannot remember actually having this issue until now but with so much on my mind and life in general, it's easy to miss things like this.

**Comment by dbwiddis** [comment]
Still had the javadoc plugin issue on release.  Had to back up to the tag, `mvn install`, catch up to latest rev and release.

**Comment by hazendaz** [comment]
Bummer.  Thought we had that fixed.  Ill be releasing waffle today.  Ill let you know if i run into similar issues.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dbwiddis** [comment]
On the bright side, the site looks good with all the other issues apparently fixed!

**Comment by hazendaz** [comment]
ok - so waffle released without any problems.  It has 22 modules.  At one point had same issue as impacting this library.  So at least that worked and should give us something to look at that might find this issue.  If I get some time I'll look a little deeper at it.

**Comment by hazendaz** [comment]
I see this all went out as dblock still.  I'll task myself with getting that all fixed which will give a reason to perform another release ;)

**Comment by Nadahar** [comment]
Regarding CheckStyle, we have checked in [CheckStyle.xml](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/CheckStyle.xml) in our repository root and use the following configuration:
```xml
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-checkstyle-plugin</artifactId>
	<version>2.17</version>
	<configuration>
		<configLocation>CheckStyle.xml</configLocation>
	</configuration>
</plugin>
```
You'll obviously have to adapt the settings to match your style.

**Comment by svjava** [comment]
can some one help me in in release:perform step
My project has 10 modules, all these modules has java doc(supported in java 1.7). 
as I am using java 1.8 with Maven, while doing the release:perform step, I am unable to proceed further because of bad java doc(many java doc errors are showing up). I can able to see the java doc errors for one module, rest of all modules are just skipped. 
Can some one help me, how to view all java doc errors in all modules in one shot(rather than fixing java doc errors in one module and running all commands till release:perform, and view next module java doc errors). I mean I want to see all module's java doc errors in one shot rather than viewing one module java doc errors.
I want to fix all java doc errors, with no configure changes in pom.
Thanks in advance for the help.!

**Comment by dbwiddis** [comment]
There is still some issue I have with the release:perform step if you do not have a copy of the release tag in your local repository... scroll up for details but the workaround is that inbetween release:prepare and release:perform, you back up one commit (to the release tag), run mvn install, catch up your commits to the latest (prep for next...) then release:perform.

**Comment by svjava** [comment]
Thanks for the prompt reply. I can able to create the tag, and while I perform the release:perform step, latest committing changes are showing in the tag, those fixed java doc error are now gone, now the next module errors are showing up. Fixing one module java doc errors and repeating all steps consuming more time. Rather is there any tweak in command I have to do to list all java doc errors in all modules. I can able to see java doc errors, while doing release:perform step, until that step no java doc errors were shown. 
Thanks @dbwiddis

**Comment by hazendaz** [comment]
Run the javadoc plugin cycle during a normal build.  It will flush out the bad javadoc.  See maven page for command to use.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dbwiddis** [comment]
CLosing and continuing to track remaining issues in #473
