### ISSUE TITLE
how to get dns config of different network interface 

### ISSUE THREAD

**Issue by helloannali** [oshi/oshi#2240]
hello
if some device have multi network interface, how i get dns config of the different network interface?

**Comment by helloannali** [comment]
oh,both the network interface gateway info

**Comment by dbwiddis** [comment]
As far as I know, the DNS configuration is normally an Operating System level setting, independent of the network interfaces themselves.  OSHI provides the OS-level settings including DNS in [`OperatingSystem.getNetworkParams()`](https://www.oshi.ooo/oshi-core-java11/apidocs/com.github.oshi/oshi/software/os/OperatingSystem.html#getNetworkParams()) and interface level settings in [`HardwareAbstractionLayer.getNetworkIFs()`](https://www.oshi.ooo/oshi-core-java11/apidocs/com.github.oshi/oshi/hardware/HardwareAbstractionLayer.html#getNetworkIFs()), which do not include DNS.

**Comment by helloannali** [comment]
ok,thank you.
another question, latest version support route info?

**Comment by dbwiddis** [comment]
Other than the "default route" which is part of the Network Params mentioned above, no... or at least not yet.  What type of information would you want/need from such a feature?

**Comment by helloannali** [comment]
sorry, another question: how i get duplexMode?

**Comment by dbwiddis** [comment]
> sorry, another question: how i get duplexMode?

I don't think that's currently available in OSHI.
