### ISSUE TITLE
GetExtendedTcpTable return 122，

### ISSUE THREAD

**Issue by SilenceRainly** [oshi/oshi#2242]
```java
private static List<IPConnection> queryTCPv4Connections() {
        List<IPConnection> conns = new ArrayList<>();
        // Get size needed
        try (CloseableIntByReference sizePtr = new CloseableIntByReference()) {
            int ret = IPHLP.GetExtendedTcpTable(null, sizePtr, false, AF_INET, TCP_TABLE_OWNER_PID_ALL, 0);
            if (ret == WinError.ERROR_SUCCESS) {
                // Get buffer and populate table
                int size = sizePtr.getValue();
                Memory buf = new Memory(size);
                do {
                    ret = IPHLP.GetExtendedTcpTable(buf, sizePtr, false, AF_INET, TCP_TABLE_OWNER_PID_ALL, 0);
                    if (ret == WinError.ERROR_INSUFFICIENT_BUFFER) {
                        size = sizePtr.getValue();
                        buf.close();
                        buf = new Memory(size);
                    }
                } while (ret == WinError.ERROR_INSUFFICIENT_BUFFER);
                MIB_TCPTABLE_OWNER_PID tcpTable = new MIB_TCPTABLE_OWNER_PID(buf);
                for (int i = 0; i < tcpTable.dwNumEntries; i++) {
                    MIB_TCPROW_OWNER_PID row = tcpTable.table[i];
                    conns.add(new IPConnection("tcp4", ParseUtil.parseIntToIP(row.dwLocalAddr),
                            ParseUtil.bigEndian16ToLittleEndian(row.dwLocalPort),
                            ParseUtil.parseIntToIP(row.dwRemoteAddr),
                            ParseUtil.bigEndian16ToLittleEndian(row.dwRemotePort), stateLookup(row.dwState), 0, 0,
                            row.dwOwningPid));
                }
                buf.close();
            }
        }
        return conns;
    }
```

**Comment by dbwiddis** [comment]
I don't understand what the question is.  Error 122 is `WinError.ERROR_INSUFFICIENT_BUFFER` and there is a loop that continues (increasing buffer size) as long as that return value is seen; only exiting when it does not see that error message.

Where are you seeing this error message reported?

**Comment by SilenceRainly** [comment]
![image](https://user-images.githubusercontent.com/37230683/202347185-0ea54e7c-c13c-4eb2-9a02-3a0dd18b110f.png)
I don't see any code to increase the buffer.The version I use is 6.3.1.

**Comment by dbwiddis** [comment]
Per the [docs for GetExtendedTcpTable](https://learn.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getextendedtcptable),

> `[in, out] pdwSize`
> 
> The estimated size of the structure returned in _pTcpTable_, in bytes. If this value is set too small, **ERROR_INSUFFICIENT_BUFFER** is returned by this function, and this field will contain the correct size of the structure.

So if `ret` is 122, this code is invoked:
```java
                    if (ret == WinError.ERROR_INSUFFICIENT_BUFFER) {
                        size = sizePtr.getValue();
                        buf.close();
                        buf = new Memory(size);
                    }
```
The `getValue()` call obtains "the correct size" and is used to resize the buffer for the subsequent call.

**Comment by SilenceRainly** [comment]
![image](https://user-images.githubusercontent.com/37230683/202348957-29b43d04-1a23-49b2-a98a-1bed09cb42d5.png)
But the first if judgment doesn't even go in

**Comment by dbwiddis** [comment]
OK, I at least understand what you're reporting -- that 122 is a potential return from the first call to get the size.

However, the size passed initially should be 0:  `new CloseableIntByReference()` should contain a value of 0, but your debug shows it has a size of 12564.  Where is that 12564 coming from?

**Comment by SilenceRainly** [comment]
![image](https://user-images.githubusercontent.com/37230683/202349716-9ff0ffbd-60bf-4195-afed-842d652025a5.png)
It's 0 before the method is called and then it changes

**Comment by dbwiddis** [comment]
Hmm.  So it returns that error value even with a null buffer and 0 size?  In which case, this method should never have worked.   Or maybe something changed...

**Comment by dbwiddis** [comment]
Huh.  How did I miss this in the docs?



ERROR_INSUFFICIENT_BUFFER | This error is also returned if the pTcpTable parameter is NULL.
-- | --

**Comment by SilenceRainly** [comment]
Therefore, the connection I get for windows is always empty. Could you please fix it?

**Comment by dbwiddis** [comment]
Looks like I messed this up in #2081 as part of 6.3.1.

**Comment by SilenceRainly** [comment]
Am I going to use 6.2.1?

**Comment by dbwiddis** [comment]
> Am I going to use 6.2.1?

You should use 6.3.2. :)

6.2.0 or earlier didn't have the bug, was the point I was making.

**Comment by SilenceRainly** [comment]
The maven repository doesn't have version 6.3.2

**Comment by SilenceRainly** [comment]
![image](https://user-images.githubusercontent.com/37230683/202379065-be6a94ec-94c9-40ef-89dc-469460e1e7fc.png)
Please upload it. Thank you

**Comment by dbwiddis** [comment]
It was released (and uploaded) 9 hours ago. It takes 2-3 hours to show up in the search but the artifact was there when I made the comment, so it could have been downloaded.
