### ISSUE TITLE
Support for more operating systems

### ISSUE THREAD

**Issue by 879611427** [oshi/oshi#2250]
Can support more operating systems？openEuler、KylinOS

**Comment by dbwiddis** [comment]
Hi, @879611427.

Compatibility starts with identifying the operating system.  Currently the JDK does that with the `os.name` system property.  Are those operating systems Linux or FreeBSD-based, or do they present a unique string that the JDK would report?

Note that OSHI depends on JNA, which in turn depends on the ability to build its native binaries on publicly accessible versions of those OS's.  Are there servers available for open source projects to compile on either of those OS's?

The next generation of OSHI will use the JDK's foreign function and memory capabilities so will require an OS that supports the latest OpenJDK builds.  Do either of those OS's have plans to release JDK21 alongside the mainline OS's?
