### ISSUE TITLE
get cpu cores usage ?

### ISSUE THREAD

**Issue by SudoDios** [oshi/oshi#2256]
Hi.
How to get cpu cores usage ?
![screenSh](https://user-images.githubusercontent.com/62701838/205151443-809d8131-79c0-40b2-8d00-a13f83a424c4.png)

**Comment by dbwiddis** [comment]
https://github.com/oshi/oshi/blob/05f75479f73cbd65df5143bda14344e492d93db6/oshi-core/src/test/java/oshi/SystemInfoTest.java#L244
https://github.com/oshi/oshi/blob/05f75479f73cbd65df5143bda14344e492d93db6/oshi-core/src/test/java/oshi/SystemInfoTest.java#L246-L247
https://github.com/oshi/oshi/blob/05f75479f73cbd65df5143bda14344e492d93db6/oshi-core/src/test/java/oshi/SystemInfoTest.java#L270-L274

**Comment by SudoDios** [comment]
Thankful 👍
