### ISSUE TITLE
Sensor readings on macOS do not work on Apple Silicon

### ISSUE THREAD

**Issue by frankelyns** [oshi/oshi#2266]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/37787156/205445018-8efe86a1-7583-4e1a-be79-65e2dd58b38e.png">
<img width="746" alt="image" src="https://user-images.githubusercontent.com/37787156/205445032-4fa120b4-528f-4d03-a77d-cbd5a5807f2d.png">

**Comment by dbwiddis** [comment]
Looks like the [sensor keys changed for M1 (and M2) macs](https://github.com/exelban/stats/blob/25e7e38eb9878d252f2e9c0b458e897ddcf1b6a5/Modules/Sensors/values.swift#L200C16-L322).

I don't have either an M1 or M2 to test which would be necessary to fix this, but it seems relatively easy for those who do.  A PR is welcome.

**Comment by frankelyns** [comment]
> 看起[M1（和M2）mac的传感器按键发生了变化](https://github.com/exelban/stats/blob/25e7e38eb9878d252f2e9c0b458e897ddcf1b6a5/Modules/Sensors/values.swift#L200C16-L322)。
> 
> 我没有 M1 或 M2 来测试解决这个问题所必需的，但是对于那些有的人来说似乎很容易。欢迎 PR。

I see. Thank you.
