### ISSUE TITLE
SystemCpuLoadTicks all 0's on Windows 2016 environment

### ISSUE THREAD

**Issue by RajeshPutta87** [oshi/oshi#2273]
Hi OSHI Team,

This is for Windows 2016 environment.

We are using following snippet from OSHI (oshi-core-6.1.6.jar) to fetch SystemCpuLoadTicks and idleTicks, stealTicks, systemTicks , userTicks,

CODE SNIPPET :

        SystemInfo si = new SystemInfo();
        HardwareAbstractionLayer hal = si.getHardware();
        CentralProcessor cpuInfo = hal.getProcessor();
        long[] loadTicks = cpuInfo.getSystemCpuLoadTicks();
        log.debug("OSHI library output (SystemCpuLoadTicks): " + Arrays.toString(loadTicks));
        long idleTicks = loadTicks[CentralProcessor.TickType.IDLE.getIndex()];
        long stealTicks = loadTicks[CentralProcessor.TickType.STEAL.getIndex()];
        long systemTicks = loadTicks[CentralProcessor.TickType.SYSTEM.getIndex()]
                + loadTicks[CentralProcessor.TickType.IRQ.getIndex()]
                + loadTicks[CentralProcessor.TickType.SOFTIRQ.getIndex()];
        long userTicks = loadTicks[CentralProcessor.TickType.USER.getIndex()];
        long timeStamp = idleTicks + stealTicks + systemTicks + userTicks;

OUTPUT:

OSHI library output (SystemCpuLoadTicks): [0, 0, 0, 0, 0, 0, 0, 0]
OSHI library output (cpusPerf): {_Total=WindowsRawData.CpuPerf(timestamp=0, idleTicks=0, stealTicks=0, systemTicks=0, userTicks=0)}

But we are consistently getting all 0's for ticks . We understand that this is an issue with environment. 

Wanted to find out what does OSHI rely on to fetch those SystemCpuLoadTicks and idleTicks, stealTicks, systemTicks , userTicks details. (Like any WMI query/counters). Please provide details so that we can directly execute and validate it on environment.

Any recommendations to address the issue would be much appreciated.

Thanks in advance

Regards
Rajesh

**Comment by dbwiddis** [comment]
> Wanted to find out what does OSHI rely on to fetch those SystemCpuLoadTicks and idleTicks, stealTicks, systemTicks , userTicks details. (Like any WMI query/counters). Please provide details so that we can directly execute and validate it on environment.

OSHI uses the performance counters for this information, specifically, the "Processor Information" counters:
https://github.com/oshi/oshi/blob/59b8f19c601a7aba2c5db862295dd52bc473a315/oshi-core/src/main/java/oshi/driver/windows/perfmon/ProcessorInformation.java#L41-L45

It attempts to query the performance counters via the PDH API first. These can be checked on a local machine by running `PerfMon.exe` and adding a counter for "Processor Information" with each of the above counter names (in parentheses).

If that fails, it falls back to (slower) WMI queries from the table [`Win32_PerfRawData_Counters_ProcessorInformation`](https://wutils.com/wmi/root/cimv2/win32_perfrawdata_counters_processorinformation/) (the constants in all caps). 

Common issues for failures include corrupt or disabled performance counters, or running in some sort of containerized/virtual/hypervisor environment which does not expose the underlying OS performance counters.

It looks like you previously reported this issue with Windows 2019 Containers in https://github.com/oshi/oshi/discussions/2271 which suggests several debugging steps.  Those would equally apply to Windows 2016.

**Comment by dbwiddis** [comment]
Do you have any logging enabled which produces messages when these failures occur?  The logging in the latest versions should have much more detailed information on exactly where the failure is.

**Comment by RajeshPutta87** [comment]
Hi Daniel,

This is what we see in our logs. We are using (oshi-core-6.1.6.jar). Is the logging not available in (oshi-core-6.1.6.jar)

The server is missing these WMI classes. The WMI repository could be corrupted: [Win32_PerfRawData_PerfOS_System- Error number: 0. Error description: The WMI class was not found in the compiled dictionary]

**Comment by dbwiddis** [comment]
> Is the logging not available in (oshi-core-6.1.6.jar)

There is some general "performance counters may be disabled or corrupt" logging in earlier versions, however, there is much more detailed analysis of whether it's disabled (Registry PerfOS key) and there was a localization bug in versions before 6.2.1 which gave spurious messages.

> The server is missing these WMI classes. The WMI repository could be corrupted 
 [Win32_PerfRawData_PerfOS_System-

This is a very useful indication of an underlying issue with your Performance Counter setup.  While the `System` counters aren't associated with the CPU ticks, they are feteched for other OSHI output and point to a common underlying cause.

Check this key in your registry: `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance`

It should either not exist, or have the DWORD value 0.  If it has any other value or isn't a DWORD, it may have disabled your PerfOS counters.

See also [this article](https://learn.microsoft.com/en-us/troubleshoot/windows-server/performance/manually-rebuild-performance-counters)

**Comment by dbwiddis** [comment]
Hey @RajeshPutta87 just checking in.  I'm curious if you were able to use this information to identify the problem you were seeing?

**Comment by RajeshPutta87** [comment]
@dbwiddis  We are still verifying based on your recommendations. We will let you know as we verify things.

Thanks
Rajesh

**Comment by RajeshPutta** [comment]
Hi @dbwiddis  Your recommendations helped address the problem. Thank you

Could you also please share your recommendations based on my comments on https://github.com/oshi/oshi/discussions/2271 for other issue.

Regards
Rajesh Putta
