### ISSUE TITLE
oshi.driver.unix.NetStat queryTcpStats  use wrong string to match active connection

### ISSUE THREAD

**Issue by leizhiyuan** [oshi/oshi#2299]
```
 case "active connection openings":
                    connectionsActive = ParseUtil.parseLongOrDefault(split[0], 0L);
                    break;
```

the real result in linux is 

```
IcmpMsg:
    InType3: 50
    InType8: 5761998
    OutType0: 5761998
    OutType3: 11972
Tcp:
    4421778 active connections openings
    1098842 passive connection openings
    9389255 failed connection attempts
    109820 connection resets received
    33 connections established
    77695030 segments received
    79734105 segments send out
    108216 segments retransmited
    0 bad segments received.
    177546 resets sent

```

one is          active connection openings
the other is active connections openings

the difference is there has an "s"

**Comment by dbwiddis** [comment]
What's an "s" between friends? :)

PR to fix welcome!

**Comment by dbwiddis** [comment]
Looks like this may be a platform-dependent typo and both the with and without-s cases should be included.

**Comment by leizhiyuan** [comment]
> connection

connection and connections

if you confirmed , I will fix it

**Comment by dbwiddis** [comment]
```
oshi@gcc103:~$ uname -a
Linux gcc103.fsffrance.org 6.0.0-rc5-asahi-00001-gc62bd3fe430f #1 SMP Sun Sep 18 18:07:57 CEST 2022 aarch64 GNU/Linux
oshi@gcc103:~$ netstat -st
IcmpMsg:
    InType3: 5
    InType8: 8830
    OutType0: 8830
    OutType3: 157
Tcp:
    211 active connection openings
    1850 passive connection openings
```

**Comment by dbwiddis** [comment]
Where are you seeing the version with the "s"?
```
oshi@gcc186:~$ uname -a
Linux gcc186.osuosl.org 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux
oshi@gcc186:~$ netstat -st
IcmpMsg:
    InType0: 323
<snip>
    OutType14: 25
Tcp:
    419959 active connection openings
    1137010 passive connection openings
```

**Comment by leizhiyuan** [comment]
https://github.com/ecki/net-tools/blame/4030929bb6f3ee6f465c76869d7a49424df45d9e/statistics.c#L172

I use 

netstat -st4 to see 

maybe the old netstat does the wrong thing

**Comment by leizhiyuan** [comment]
https://github.com/ecki/net-tools/commit/614e15d6f4e32d094288414f6bf086d9761539f8

yes。。 they fixed

**Comment by dbwiddis** [comment]
Have tried Debian, Ubuntu, and whatever magic they use on an apple M1.
```
oshi@gcc92:~$ uname -a
Linux gcc92 5.19.0-1012-generic #13~22.04.1-Ubuntu SMP Thu Jan 12 15:34:31 UTC 2023 riscv64 riscv64 riscv64 GNU/Linux
oshi@gcc92:~$ netstat -st
IcmpMsg:
    InType0: 1
    InType3: 150
    InType5: 19
    InType8: 300478
    InType11: 1
    OutType0: 300478
    OutType3: 4404
Tcp:
    4825 active connection openings
    43208 passive connection openings
```

**Comment by dbwiddis** [comment]
> [ecki/net-tools@614e15d](https://github.com/ecki/net-tools/commit/614e15d6f4e32d094288414f6bf086d9761539f8)
> 
> yes。。 they fixed
> 
> <img alt="image" width="1154" src="https://user-images.githubusercontent.com/2684384/215694577-c1f070c7-2ec9-4f7d-adde-bce9e9079b2c.png">

Ah, ok, so it's a bug elsewhere?  So we don't need to fix?

**Comment by leizhiyuan** [comment]
> > [ecki/net-tools@614e15d](https://github.com/ecki/net-tools/commit/614e15d6f4e32d094288414f6bf086d9761539f8) > > yes。。 they fixed > > <img alt="image" width="1154" src="https://user-images.githubusercontent.com/2684384/215694577-c1f070c7-2ec9-4f7d-adde-bce9e9079b2c.png"> > Ah, ok, so it's a bug elsewhere? So we don't need to fix it?

Yes, we can try to update the version of netstat, oshi doesn't need to be compatible in this situation.
