### ISSUE TITLE
FreeBSD CPU counts not accurate on FreeBSD 13.1

### ISSUE THREAD

**Issue by decketron** [oshi/oshi#2309]
cpu count on FreeBSD is calculated from output of 
  sysctl kern.sched.topology_spec        
And parsing the resulting <groups> XML.
Comment states:
	* If there is no level 3, then all logical processors are physical
	
I have a Dell XPS 8500:
  kern.ostype: FreeBSD
  kern.osrelease: 13.1-RELEASE-p2
  kern.osrevision: 199506
  kern.version: FreeBSD 13.1-RELEASE-p2 n245412-484f039b1d0 TRUENAS
  hw.model: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
  kern.smp.topology: 0
  kern.smp.cores: 4
  kern.smp.threads_per_core: 2
  kern.smp.cpus: 8
  hw.ncpu: 8  
	# sysctl kern.sched.topology_spec
	kern.sched.topology_spec: ```

```
<groups>
	 <group level="1" cache-level="3">
	  <cpu count="8" mask="ff,0,0,0">0, 1, 2, 3, 4, 5, 6, 7</cpu>
	  <children>
	   <group level="2" cache-level="2">
		<cpu count="2" mask="3,0,0,0">0, 1</cpu>
		<flags><flag name="THREAD">THREAD group</flag><flag name="SMT">SMT group</flag></flags>
	   </group>
	   <group level="2" cache-level="2">
		<cpu count="2" mask="c,0,0,0">2, 3</cpu>
		<flags><flag name="THREAD">THREAD group</flag><flag name="SMT">SMT group</flag></flags>
	   </group>
	   <group level="2" cache-level="2">
		<cpu count="2" mask="30,0,0,0">4, 5</cpu>
		<flags><flag name="THREAD">THREAD group</flag><flag name="SMT">SMT group</flag></flags>
	   </group>
	   <group level="2" cache-level="2">
		<cpu count="2" mask="c0,0,0,0">6, 7</cpu>
		<flags><flag name="THREAD">THREAD group</flag><flag name="SMT">SMT group</flag></flags>
	   </group>
	  </children>
	 </group>
	</groups>  

```  
  
And a Dell OptiPlex 7020:
  kern.ostype: FreeBSD
  kern.osrelease: 13.1-RELEASE-p2
  kern.osrevision: 199506
  kern.version: FreeBSD 13.1-RELEASE-p2 n245412-484f039b1d0 TRUENAS
  hw.model: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  hw.ncpu: 4
  kern.smp.topology: 0
  kern.smp.cores: 4
  kern.smp.threads_per_core: 1
  kern.smp.cpus: 4
  hw.ncpu: 4
  
  # sysctl kern.sched.topology_spec
	kern.sched.topology_spec: <groups>
	 <group level="1" cache-level="3">
	  <cpu count="4" mask="f,0,0,0">0, 1, 2, 3</cpu>
	 </group>
	</groups>

For both FreeBSD machines, CentralProcessor returns lists of only length 1 for:
  List<LogicalProcessor> getLogicalProcessors();
  List<PhysicalProcessor> getPhysicalProcessors();

  "hwManuf" : "Dell Inc.",
  "hwModel" : "XPS 8500",
  "pCpus" : 1,
  "vCpus" : 1,
  "cpuName" : "Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz",
  "cpuFam" : "6",
  "cpuModel" : "58",
  "cpuMicroArch" : "Ivy Bridge (Client)",
  "cpuIdent" : "Intel64 Family 6 Model 58 Stepping 9",
  "cpuVendor" : "GenuineIntel",
  "cpuMaxSpeed" : 3401000000,

  "hwManuf" : "Dell Inc.",
  "hwModel" : "OptiPlex 7020",
  "pCpus" : 1,
  "vCpus" : 1,
  "cpuName" : "Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz",
  "cpuFam" : "6",
  "cpuModel" : "60",
  "cpuMicroArch" : "Haswell (Client)",
  "cpuIdent" : "Intel64 Family 6 Model 60 Stepping 3",
  "cpuVendor" : "GenuineIntel",
  "cpuMaxSpeed" : 3401000000,

The comment and the logic don't match what I observe for p/v cpus on my Dell
machines.
  
I beleive that the kern.sched.topology_spec <group> parsing needs to be enhanced 
and/or consider additional system properties to correctly detect CPUs and cores 
on FreeBSD.

**Comment by decketron** [comment]
I think the issue is in the regex:
private static final Pattern CPUMASK = Pattern.compile(".*<cpu\\s.*mask=\"(?:0x)?(\\p{XDigit}+)\".*>.*</cpu>.*");

Which doesn't seem to allow for the ',' in the CSV values I observe:
    // Like:
    // <cpu count="8" mask="ff,0,0,0">0, 1, 2, 3, 4, 5, 6, 7</cpu>
    // <cpu count="4" mask="f,0,0,0">0, 1, 2, 3</cpu>
    // <cpu count="2" mask="3,0,0,0">0, 1</cpu>

`The current code expects the mask to be a single long:

                Matcher m = CPUMASK.matcher(topo);
                if (m.matches()) {
                    // Regex guarantees parsing digits so we won't get a
                    // NumberFormatException
                    switch (groupLevel) {
                    case 1:
                        group1 = Long.parseLong(m.group(1), 16);
                        break;
                    case 2:
                        group2.add(Long.parseLong(m.group(1), 16));
                        break;
                    case 3:
                        group3.add(Long.parseLong(m.group(1), 16));
                        break;
                    default:
                        break;
                    }
                }

Given the observed FreeBSD output, a regex that parses the observed CSV of 
values and extracts the first hex digit might look something like:

private static final Pattern CPUMASK = Pattern.compile(".*<cpu\\s.*mask=\"(\\p{XDigit}+)(,.*)*\".*>.*</cpu>.*");

But I don't know about backwards compatability or if there are examples
from older versions for FreeBSD to test against.



`

**Comment by dbwiddis** [comment]
Thanks for the report and more importantly the sample output.

In my development I was limited to VMs or my firewall running FreeBSD which doesn't use SMT.

We should be able to replace the parsing to include the comma and parse the logical CPU ranges.

I may not get to this for a few days so if you'd like to take a crack at a PR it'd be welcome.

**Comment by decketron** [comment]
Thanks, I am in no hurry.  
I would love the opportunity to submit a PR if you give me a day or 2.
Thanks for the great project in general.

**Comment by dbwiddis** [comment]
That'd be great. You might consider updating `ParseUtil.parseHyphenatedIntList()` to handle commas in addition to the range notation.

**Comment by decketron** [comment]
I am a new github user so I am still reading about forking vs branching,
personal access tokens, and creating PRs.
In the meantime I was playing with some changes like:


diff --git
a/oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
b/oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
index 7c665f7ace..94466bd086 100644
---
a/oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
+++
b/oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
@@ -40,7 +40,7 @@ final class FreeBsdCentralProcessor extends
AbstractCentralProcessor {

     private static final Logger LOG =
LoggerFactory.getLogger(FreeBsdCentralProcessor.class);

-    private static final Pattern CPUMASK =
Pattern.compile(".*<cpu\\s.*mask=\"(?:0x)?(\\p{XDigit}+)\".*>.*</cpu>.*");
+    private static final Pattern CPUMASK =
Pattern.compile(".*<cpu\\s.*mask=\"(\\p{XDigit}+),.*\".*>.*</cpu>.*");

     private static final long CPTIME_SIZE;
     static {
@@ -167,7 +167,17 @@ final class FreeBsdCentralProcessor extends
AbstractCentralProcessor {
              <cpu count="2" mask="3">0, 1</cpu>
              <flags><flag name="THREAD">THREAD group</flag><flag
name="SMT">SMT group</flag></flags>
             </group>
-        *
+            ...
+
+        * On FreeBSD 13.1, the output may contain a csv value for the mask:
+        <groups>
+         <group level="1" cache-level="3">
+          <cpu count="8" mask="ff,0,0,0">0, 1, 2, 3, 4, 5, 6, 7</cpu>
+          <children>
+           <group level="2" cache-level="2">
+            <cpu count="2" mask="3,0,0,0">0, 1</cpu>
+            ...
+
         * Opens with <groups>
         * <group> level 1 identifies all the processors via bitmask,
should only be one
         * <group> level 2 separates by physical package
diff --git a/oshi-core/src/main/java/oshi/util/ParseUtil.java
b/oshi-core/src/main/java/oshi/util/ParseUtil.java
index c27feaf7a6..2befe980ee 100644
--- a/oshi-core/src/main/java/oshi/util/ParseUtil.java
+++ b/oshi-core/src/main/java/oshi/util/ParseUtil.java
@@ -1023,22 +1023,28 @@ public final class ParseUtil {
      * Parse a space-delimited list of integers which include hyphenated
ranges to a list of just the integers. For
      * example, 0 1 4-7 parses to a list containing 0, 1, 4, 5, 6, and 7.
      *
+     * Also support comma separated entries like 0, 2-5, 7-8, 9
+     *
      * @param str A string containing space-delimited integers or ranges
of integers with a hyphen
      * @return A list of integers representing the provided range(s).
      */
     public static List<Integer> parseHyphenatedIntList(String str) {
         List<Integer> result = new ArrayList<>();
-        for (String s : whitespaces.split(str)) {
-            if (s.contains("-")) {
-                int first = getFirstIntValue(s);
-                int last = getNthIntValue(s, 2);
-                for (int i = first; i <= last; i++) {
-                    result.add(i);
-                }
-            } else {
-                int only = ParseUtil.parseIntOrDefault(s, -1);
-                if (only >= 0) {
-                    result.add(only);
+        String[] csvTokens = str.split(",");
+        for (String csvToken : csvTokens) {
+            csvToken = csvToken.trim();
+            for (String s : whitespaces.split(csvToken)) {
+                if (s.contains("-")) {
+                    int first = getFirstIntValue(s);
+                    int last = getNthIntValue(s, 2);
+                    for (int i = first; i <= last; i++) {
+                        result.add(i);
+                    }
+                } else {
+                    int only = ParseUtil.parseIntOrDefault(s, -1);
+                    if (only >= 0) {
+                        result.add(only);
+                    }
                 }
             }
         }
diff --git a/oshi-core/src/test/java/oshi/util/ParseUtilTest.java
b/oshi-core/src/test/java/oshi/util/ParseUtilTest.java
index 59366b072a..4b43b958a6 100644
--- a/oshi-core/src/test/java/oshi/util/ParseUtilTest.java
+++ b/oshi-core/src/test/java/oshi/util/ParseUtilTest.java
@@ -520,6 +520,12 @@ class ParseUtilTest {
         assertThat(parsed, contains(0, 2, 3, 4, 5, 7));
         assertThat(parsed, not(hasItems(1)));
         assertThat(parsed, not(hasItems(6)));
+
+        s = "0, 2-5, 7-8, 9";
+        parsed = ParseUtil.parseHyphenatedIntList(s);
+        assertThat(parsed, contains(0, 2, 3, 4, 5, 7, 8, 9));
+        assertThat(parsed, not(hasItems(1)));
+        assertThat(parsed, not(hasItems(6)));
     }

     @Test

**Comment by dbwiddis** [comment]
Hard to read the diff in proportional font and GitHub won't let me edit an email reply, so mostly a general answer here.

As for the regex I'm not sure the one you used will work for the case where there is no comma (the current single int case).  `[0-9](,\s*[0-9])*` should probably work.

I think the ParseUtil method will work as-is if you just replace commas with spaces.

**Comment by dbwiddis** [comment]
Hard to read the diff in proportional font and GitHub won't let me edit an email reply, so mostly a general answer here.

As for the regex I'm not sure the one you used will work for the case where there is no comma (the current single int case).  `\d+(,\s*\d+)*` should probably work.

I think the ParseUtil method will work as-is if you just replace commas with spaces.

**Comment by adrian-kong** [comment]
repasting above with colours ^^

```diff
diff --git
a/oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
b/oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
index 7c665f7ace..94466bd086 100644
---
a/oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
+++
b/oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
@@ -40,7 +40,7 @@ final class FreeBsdCentralProcessor extends
AbstractCentralProcessor {

     private static final Logger LOG =
LoggerFactory.getLogger(FreeBsdCentralProcessor.class);

-    private static final Pattern CPUMASK =
Pattern.compile(".*<cpu\\s.*mask=\"(?:0x)?(\\p{XDigit}+)\".*>.*</cpu>.*");
+    private static final Pattern CPUMASK =
Pattern.compile(".*<cpu\\s.*mask=\"(\\p{XDigit}+),.*\".*>.*</cpu>.*");

     private static final long CPTIME_SIZE;
     static {
@@ -167,7 +167,17 @@ final class FreeBsdCentralProcessor extends
AbstractCentralProcessor {
              <cpu count="2" mask="3">0, 1</cpu>
              <flags><flag name="THREAD">THREAD group</flag><flag
name="SMT">SMT group</flag></flags>
             </group>
-        *
+            ...
+
+        * On FreeBSD 13.1, the output may contain a csv value for the mask:
+        <groups>
+         <group level="1" cache-level="3">
+          <cpu count="8" mask="ff,0,0,0">0, 1, 2, 3, 4, 5, 6, 7</cpu>
+          <children>
+           <group level="2" cache-level="2">
+            <cpu count="2" mask="3,0,0,0">0, 1</cpu>
+            ...
+
         * Opens with <groups>
         * <group> level 1 identifies all the processors via bitmask,
should only be one
         * <group> level 2 separates by physical package
diff --git a/oshi-core/src/main/java/oshi/util/ParseUtil.java
b/oshi-core/src/main/java/oshi/util/ParseUtil.java
index c27feaf7a6..2befe980ee 100644
--- a/oshi-core/src/main/java/oshi/util/ParseUtil.java
+++ b/oshi-core/src/main/java/oshi/util/ParseUtil.java
@@ -1023,22 +1023,28 @@ public final class ParseUtil {
      * Parse a space-delimited list of integers which include hyphenated
ranges to a list of just the integers. For
      * example, 0 1 4-7 parses to a list containing 0, 1, 4, 5, 6, and 7.
      *
+     * Also support comma separated entries like 0, 2-5, 7-8, 9
+     *
      * @param str A string containing space-delimited integers or ranges
of integers with a hyphen
      * @return A list of integers representing the provided range(s).
      */
     public static List<Integer> parseHyphenatedIntList(String str) {
         List<Integer> result = new ArrayList<>();
-        for (String s : whitespaces.split(str)) {
-            if (s.contains("-")) {
-                int first = getFirstIntValue(s);
-                int last = getNthIntValue(s, 2);
-                for (int i = first; i <= last; i++) {
-                    result.add(i);
-                }
-            } else {
-                int only = ParseUtil.parseIntOrDefault(s, -1);
-                if (only >= 0) {
-                    result.add(only);
+        String[] csvTokens = str.split(",");
+        for (String csvToken : csvTokens) {
+            csvToken = csvToken.trim();
+            for (String s : whitespaces.split(csvToken)) {
+                if (s.contains("-")) {
+                    int first = getFirstIntValue(s);
+                    int last = getNthIntValue(s, 2);
+                    for (int i = first; i <= last; i++) {
+                        result.add(i);
+                    }
+                } else {
+                    int only = ParseUtil.parseIntOrDefault(s, -1);
+                    if (only >= 0) {
+                        result.add(only);
+                    }
                 }
             }
         }
diff --git a/oshi-core/src/test/java/oshi/util/ParseUtilTest.java
b/oshi-core/src/test/java/oshi/util/ParseUtilTest.java
index 59366b072a..4b43b958a6 100644
--- a/oshi-core/src/test/java/oshi/util/ParseUtilTest.java
+++ b/oshi-core/src/test/java/oshi/util/ParseUtilTest.java
@@ -520,6 +520,12 @@ class ParseUtilTest {
         assertThat(parsed, contains(0, 2, 3, 4, 5, 7));
         assertThat(parsed, not(hasItems(1)));
         assertThat(parsed, not(hasItems(6)));
+
+        s = "0, 2-5, 7-8, 9";
+        parsed = ParseUtil.parseHyphenatedIntList(s);
+        assertThat(parsed, contains(0, 2, 3, 4, 5, 7, 8, 9));
+        assertThat(parsed, not(hasItems(1)));
+        assertThat(parsed, not(hasItems(6)));
     }
```

but yea * agree with @dbwiddis single int case for regex

**Comment by dbwiddis** [comment]
Good point on the hex digits, and also the fact that we're grabbing "everything up to `</cpu>`" it seems fine to leave it the way you have it.  So looks good to me once you figure out the PR workflow. :)

**Comment by dbwiddis** [comment]
PR approved and merged.  Does that close this issue or is there more work needed?

**Comment by decketron** [comment]
I believe I am all set, thanks everyone for the hand holding and the
opportunity to be a part of this.

**Comment by dbwiddis** [comment]
Awesome.  I'll get this out in a release sometime next week.

**Comment by dbwiddis** [comment]
Hey @decketron it seems the fix isn't quite right. It's failing CI tests:
```
Error:  Failures (2):
JUnit Jupiter:SystemInfoTest:testPlatformEnum()
  MethodSource [className = 'oshi.SystemInfoTest', methodName = 'testPlatformEnum', methodParameterTypes = '']
  => java.lang.NumberFormatException: For input string: "7,0,0,0"
     java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
     java.base/java.lang.Long.parseLong(Long.java:692)
     oshi.hardware.platform.unix.freebsd.FreeBsdCentralProcessor.parseTopology(FreeBsdCentralProcessor.java:205)
     oshi.hardware.platform.unix.freebsd.FreeBsdCentralProcessor.initProcessorCounts(FreeBsdCentralProcessor.java:105)
     oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:65)
     oshi.hardware.platform.unix.freebsd.FreeBsdCentralProcessor.<init>(FreeBsdCentralProcessor.java:39)
     oshi.hardware.platform.unix.freebsd.FreeBsdHardwareAbstractionLayer.createProcessor(FreeBsdHardwareAbstractionLayer.java:43)
     oshi.util.Memoizer$1.get(Memoizer.java:61)
     oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48)
     oshi.SystemInfoTest.main(SystemInfoTest.java:94)
     [...]
JUnit Jupiter:CentralProcessorTest
  ClassSource [className = 'oshi.hardware.CentralProcessorTest', filePosition = null]
  => java.lang.NumberFormatException: For input string: "7,0,0,0"
     java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
     java.base/java.lang.Long.parseLong(Long.java:692)
     oshi.hardware.platform.unix.freebsd.FreeBsdCentralProcessor.parseTopology(FreeBsdCentralProcessor.java:205)
     oshi.hardware.platform.unix.freebsd.FreeBsdCentralProcessor.initProcessorCounts(FreeBsdCentralProcessor.java:105)
     oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:65)
     oshi.hardware.platform.unix.freebsd.FreeBsdCentralProcessor.<init>(FreeBsdCentralProcessor.java:39)
     oshi.hardware.platform.unix.freebsd.FreeBsdHardwareAbstractionLayer.createProcessor(FreeBsdHardwareAbstractionLayer.java:43)
     oshi.util.Memoizer$1.get(Memoizer.java:61)
     oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48)
     oshi.hardware.CentralProcessorTest.setUp(CentralProcessorTest.java:40)
     [...]
```
