### ISSUE TITLE
Remove LGTM, investigate GitHub equivalent

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#2317]
https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/

**Comment by mprins** [comment]
I run codeql like this: https://github.com/B3Partners/brmo/blob/master/.github/workflows/codeql-analysis.yml
problems show up in the security tab of the repo

**Comment by dbwiddis** [comment]
Yeah, we already have codeql installed, I seem to remember more other types of PR checks from LTGM, though.  

This could just be a "remove it" case, though.

**Comment by dbwiddis** [comment]
Audited the CodeQL workflow, which matches what LGTM recommended. Removed the run on doc files and removed LGTM badges in b1c936074115f12025ea3c13697fdc8d94152216
