### ISSUE TITLE
CentralProcessor::getCurrentFreq() returns -1 on Oracle Linux VM

### ISSUE THREAD

**Issue by zackmtaylor** [oshi/oshi#2319]

**Comment by dbwiddis** [comment]
Duplicate of #2079 

If you know where this information is available to the operating system, let me know, otherwise I can't make up a number.

**Comment by zackmtaylor** [comment]
If I run `sudo dmidecode -t 4` I get the following:
```
# dmidecode 3.3
Getting SMBIOS data from sysfs.
SMBIOS 3.0.0 present.

Handle 0x0400, DMI type 4, 42 bytes
Processor Information
        Socket Designation: CPU 0
        Type: Central Processor
        Family: Other
        Manufacturer: QEMU
        ID: 00 00 00 00 00 00 00 00
        Version: virt-4.2
        Voltage: Unknown
        External Clock: Unknown
        Max Speed: 2000 MHz
        Current Speed: 2000 MHz
        Status: Populated, Enabled
        Upgrade: Other
        L1 Cache Handle: Not Provided
        L2 Cache Handle: Not Provided
        L3 Cache Handle: Not Provided
        Serial Number: Not Specified
        Asset Tag: Not Specified
        Part Number: Not Specified
        Core Count: 2
        Core Enabled: 2
        Thread Count: 1
        Characteristics: None
```
This shows the max and current speed of the CPU. Does this work or do you need a location similar to `/proc/cpuinfo` to read?

**Comment by dbwiddis** [comment]
A few answers to that:
 - I could use dmidecode but it requires elevated permission. I seem to recall a very thorough investigation of this some time ago where it was shown the "Current Speed" here isn't really accurate (I doubt it exactly equals max speed)
 - Similarly with `lscpu` which also requires root
 - Currently OSHI checks `/sys/devices/system/cpu/cpuX/cpufreq/scaling_cur_freq` or `/sys/devices/system/cpu/cpuX/cpufreq/cpuinfo_cur_freq` and if those don't exist, guesses from a field ending in "cpu mhz" in `/proc/cpuinfo` which doesn't require sudo.

I can add any other fallbacks if they reliably report the "current" frequency as different from "max" or "vendor" frequency.  I'm not so sure `dmidecode` does that, particularly on a VM.

I'm skeptical that on any virtual machine, the concept of "current frequency" has any real meaning.

**Comment by zackmtaylor** [comment]
I can't find anything other than `dmidecode` which doesn't seem suitable or maybe even accurate. Closing this with that.
