### ISSUE TITLE
OSHI Windows process collection is taking huge time

### ISSUE THREAD

**Issue by RajeshPutta** [oshi/oshi#2325]
Hi OSHI Team,

We are using following API's specific to OSHI for collecting process details from Windows OS
```java
SystemInfo si = new SystemInfo();
OperatingSystem os = si.getOperatingSystem();

log.debug("Starting OSHI process collection");
for (OSProcess osProcess: os.getProcesses(null, null, 0)) {
    int processID = osProcess.getProcessID();
    String processKey = processID + osProcess.getName();
    log.debug("Process key: " + processKey);
    procMap.put(String.valueOf(processID), WindowsRawData.WinProcess.builder()
        .pid(processID)
        .commandLine(osProcess.getCommandLine())
        .name(osProcess.getName())
        .ppid(osProcess.getParentProcessID())
        .owner(osProcess.getUser()).build());
    procPerfMap.put(String.valueOf(processID), WindowsRawData.PerfWinProcess.builder()
        .pid(processID)
        .elapsedTime(osProcess.getUpTime())
        .workingSet(osProcess.getResidentSetSize())
        .threadCount(osProcess.getThreadCount())
        .virtualBytes(osProcess.getVirtualSize())
        // OSHI method allows for null input, will default to cumulative load
        .cpuPercent(osProcess.getProcessCpuLoadBetweenTicks(oshiOsProcessCache.getIfPresent(processKey)))
        .build());
    // Always update the OSProcess in the cache to maintain accurate snapshot
    oshiOsProcessCache.put(processKey, osProcess);
}
log.debug("OSHI process collection Ended");
```
We have a strict interval to report Windows specific monitoring data along with processes from OSHI calls every 60 seconds (1 minute). 

We have noticed that OSHI process collection is taking more than 1 minute as seen here.

Can you think about optimising these calls so that process collection should not take hug amount of time. Also please let us know if you recommend any other OSHI calls which can help to optimise process collection time.

ENVIRONMENT DETAILS:
```json
"operatingSystem": {
      "name": "Windows",
      "release" : "Microsoft Windows Server 2012 R2 Datacenter",
      "architecture" : "64-bit"
```

Please check the timestamp of start and end collection times for OSHI process collection which is crossing more than 1 minute

For example in RUN 1,you can see start time is 07 Nov 2022 12:26:58,937 and endTime is 07 Nov 2022 12:29:50,518 which is taking closer to 3 minutes.

RUN 1:

~/Downloads/c50Logs/logs/machine-agent.log:13595: VMIKSA69901C50==> [extension-scheduler-pool-9] 07 Nov 2022 12:26:58,937 DEBUG WindowsRawCollector - Process collection started
~/Downloads/c50Logs/logs/machine-agent.log:14647: VMIKSA69901C50==> [extension-scheduler-pool-9] 07 Nov 2022 12:29:50,518 DEBUG WindowsRawCollector - Process collection ended
*******

RUN 2:
~/Downloads/c50Logs/logs/machine-agent.log:16626: VMIKSA69901C50==> [extension-scheduler-pool-9] 07 Nov 2022 12:31:31,687 DEBUG WindowsRawCollector - Process collection started
~/Downloads/c50Logs/logs/machine-agent.log:16803: VMIKSA69901C50==> [extension-scheduler-pool-9] 07 Nov 2022 12:32:17,219 DEBUG WindowsRawCollector - Process collection ended
*******

RUN 3:
~/Downloads/c50Logs/logs/machine-agent.log:16859: VMIKSA69901C50==> [extension-scheduler-pool-9] 07 Nov 2022 12:32:34,712 DEBUG WindowsRawCollector - Process collection started
~/Downloads/c50Logs/logs/machine-agent.log:18569: VMIKSA69901C50==> [extension-scheduler-pool-9] 07 Nov 2022 12:34:14,682 DEBUG WindowsRawCollector - Process collection ended
*******

RUN 4:
~/Downloads/c50Logs/logs/machine-agent.log:18610: VMIKSA69901C50==> [extension-scheduler-pool-1] 07 Nov 2022 12:34:34,930 DEBUG WindowsRawCollector - Process collection started
~/Downloads/c50Logs/logs/machine-agent.log:19328: VMIKSA69901C50==> [extension-scheduler-pool-1] 07 Nov 2022 12:35:47,694 DEBUG WindowsRawCollector - Process collection ended
*******

RUN 5:
~/Downloads/c50Logs/logs/machine-agent.log:19372: VMIKSA69901C50==> [extension-scheduler-pool-9] 07 Nov 2022 12:35:57,978 DEBUG WindowsRawCollector - Process collection started
~/Downloads/c50Logs/logs/machine-agent.log:20715: VMIKSA69901C50==> [extension-scheduler-pool-9] 07 Nov 2022 12:37:04,154 DEBUG WindowsRawCollector - Process collection ended
*******

RUN 6:
~/Downloads/c50Logs/logs/machine-agent.log:20784: VMIKSA69901C50==> [extension-scheduler-pool-8] 07 Nov 2022 12:37:27,749 DEBUG WindowsRawCollector - Process collection started
~/Downloads/c50Logs/logs/machine-agent.log:21495: VMIKSA69901C50==> [extension-scheduler-pool-8] 07 Nov 2022 12:38:37,640 DEBUG WindowsRawCollector - Process collection ended
*******

RUN 7:
~/Downloads/c50Logs/logs/machine-agent.log:21550: VMIKSA69901C50==> [extension-scheduler-pool-8] 07 Nov 2022 12:38:56,812 DEBUG WindowsRawCollector - Process collection started
~/Downloads/c50Logs/logs/machine-agent.log:22277: VMIKSA69901C50==> [extension-scheduler-pool-8] 07 Nov 2022 12:39:59,266 DEBUG WindowsRawCollector - Process collection ended
*******

RUN 8:
~/Downloads/c50Logs/logs/machine-agent.log:22860: VMIKSA69901C50==> [extension-scheduler-pool-7] 07 Nov 2022 12:40:16,492 DEBUG WindowsRawCollector - Process collection started
~/Downloads/c50Logs/logs/machine-agent.log:23252: VMIKSA69901C50==> [extension-scheduler-pool-7] 07 Nov 2022 12:41:25,723 DEBUG WindowsRawCollector - Process collection ended
*******

RUN 9:
~/Downloads/c50Logs/logs/machine-agent.log:23834: VMIKSA69901C50==> [extension-scheduler-pool-7] 07 Nov 2022 12:42:04,706 DEBUG WindowsRawCollector - Process collection started
~/Downloads/c50Logs/logs/machine-agent.log:24366: VMIKSA69901C50==> [extension-scheduler-pool-7] 07 Nov 2022 12:44:19,103 DEBUG WindowsRawCollector - Process collection ended
*******

RUN 10:
~/Downloads/c50Logs/logs/machine-agent.log:24421: VMIKSA69901C50==> [extension-scheduler-pool-7] 07 Nov 2022 12:44:39,183 DEBUG WindowsRawCollector - Process collection started
~/Downloads/c50Logs/logs/machine-agent.log:25829: VMIKSA69901C50==> [extension-scheduler-pool-7] 07 Nov 2022 12:45:24,488 DEBUG WindowsRawCollector - Process collection ended
*******

RUN 11:
~/Downloads/c50Logs/logs/machine-agent.log:25868: VMIKSA69901C50==> [extension-scheduler-pool-7] 07 Nov 2022 12:45:48,676 DEBUG WindowsRawCollector - Process collection started
~/Downloads/c50Logs/logs/machine-agent.log:26574: VMIKSA69901C50==> [extension-scheduler-pool-7] 07 Nov 2022 12:46:34,773 DEBUG WindowsRawCollector - Process collection ended
*******

RUN 12:
~/Downloads/c50Logs/logs/machine-agent.log:26620: VMIKSA69901C50==> [extension-scheduler-pool-7] 07 Nov 2022 12:46:59,918 DEBUG WindowsRawCollector - Process collection started
~/Downloads/c50Logs/logs/machine-agent.log:27891: VMIKSA69901C50==> [extension-scheduler-pool-7] 07 Nov 2022 12:48:14,230 DEBUG WindowsRawCollector - Process collection ended
*******

RUN 13:
~/Downloads/c50Logs/logs/machine-agent.log:27932: VMIKSA69901C50==> [extension-scheduler-pool-9] 07 Nov 2022 12:48:40,172 DEBUG WindowsRawCollector - Process collection started
~/Downloads/c50Logs/logs/machine-agent.log:28042: VMIKSA69901C50==> [extension-scheduler-pool-9] 07 Nov 2022 12:48:46,845 DEBUG WindowsRawCollector - Process collection ended

*******
RUN 14:
~/Downloads/c50Logs/logs/machine-agent.log:28064: VMIKSA69901C50==> [extension-scheduler-pool-9] 07 Nov 2022 12:48:48,370 DEBUG WindowsRawCollector - Process collection started
~/Downloads/c50Logs/logs/machine-agent.log:28175: VMIKSA69901C50==> [extension-scheduler-pool-9] 07 Nov 2022 12:48:55,655 DEBUG WindowsRawCollector - Process collection ended
*******

RUN 15:
~/Downloads/c50Logs/logs/machine-agent.log:28214: VMIKSA69901C50==> [extension-scheduler-pool-9] 07 Nov 2022 12:48:57,112 DEBUG WindowsRawCollector - Process collection started
~/Downloads/c50Logs/logs/machine-agent.log:28858: VMIKSA69901C50==> [extension-scheduler-pool-9] 07 Nov 2022 12:49:03,885 DEBUG WindowsRawCollector - Process collection ended
*******

RUN 16:
~/Downloads/c50Logs/logs/machine-agent.log:28881: VMIKSA69901C50==> [extension-scheduler-pool-11] 07 Nov 2022 12:49:06,182 DEBUG WindowsRawCollector - Process collection started
~/Downloads/c50Logs/logs/machine-agent.log:29024: VMIKSA69901C50==> [extension-scheduler-pool-11] 07 Nov 2022 12:49:20,442 DEBUG WindowsRawCollector - Process collection ended
*******

RUN 17:
~/Downloads/c50Logs/logs/machine-agent.log:29050: VMIKSA69901C50==> [extension-scheduler-pool-11] 07 Nov 2022 12:49:24,662 DEBUG WindowsRawCollector - Process collection started
~/Downloads/c50Logs/logs/machine-agent.log:29193: VMIKSA69901C50==> [extension-scheduler-pool-11] 07 Nov 2022 12:49:42,822 DEBUG WindowsRawCollector - Process collection ended
*******

RUN 18:
~/Downloads/c50Logs/logs/machine-agent.log:29227: VMIKSA69901C50==> [extension-scheduler-pool-11] 07 Nov 2022 12:49:45,916 DEBUG WindowsRawCollector - Process collection started
~/Downloads/c50Logs/logs/machine-agent.log:29559: VMIKSA69901C50==> [extension-scheduler-pool-11] 07 Nov 2022 12:50:00,047 DEBUG WindowsRawCollector - Process collection ended
*******

**Comment by RajeshPutta** [comment]
Please do note that there are no hidden environment issues like high CPU/Memory. Windows server is properly sized.

**Comment by mprins** [comment]
Did you RTFM?: https://github.com/oshi/oshi/blob/master/src/site/markdown/Performance.md

Also since you are reporting data from almost 6 months ago, please upgrade to the current release (6.4.0)

**Comment by dbwiddis** [comment]
Hi @RajeshPutta.  As @mprins has noted there are several configuration settings you can change to improve your performance.  Specifically:
 - The likely source of your issues given the code you've posted are the individual WMI queries for process command lines.  
   - Do you need the command lines?  Often the process name is enough. Consider not grabbing info you don't need. 
   - If you do need all the command lines, you should [batch](https://github.com/oshi/oshi/blob/master/src/site/markdown/Performance.md#windows-process-command-lines) command line WMI queries to reduce these from a 50ms-per-process call to a single 200ms call.
   - You can also [control your own COM initialization](https://github.com/oshi/oshi/blob/master/src/site/markdown/Performance.md#windows-wmi-query-com-initialization) to shave off a few more milliseconds.
 - You have not indicated which OSHI version you are using. There were significant performance improvements including eliminating excessive heap usage in the process queries in 6.2.x, and parallelizing streams in 6.3.x.

In addition, in your own code I see you are keeping an `oshiOsProcessCache`.  The entire first set of information in your `procMap` doesn't change. You could completely skip updating it if the process already exists in your cache with a process start time no later than your previous query timestamp.  (This is the same logic the caching command lines logic uses.)

**Comment by dbwiddis** [comment]
Closing this.  Feel free to re-open if you still have these issues after taking the recommended actions above.
