### ISSUE TITLE
Relax slf4j OSGi requirement to include slf4j 1

### ISSUE THREAD

**Issue by Artur-** [oshi/oshi#2326]
Many existing libraries are still using slf4j. When you are deploying to OSGi, it would be preferrable if you can deploy only slf4j 1 even though oshi is using slf4j 2. To my understanding they are API compatible.

e.g. Jetty has defined a range of `[1.7,3.0)`  https://github.com/eclipse/jetty.project/blob/e6de81084d8f69007102bd3a6a12ad67555e3eb6/pom.xml#L22

**Comment by dbwiddis** [comment]
Hey @Artur- took a quick look at implementing this so I can cut a new release, but I have no experience with OSGi.  It looks like a line needs to be added somewhere in here, but I'm not sure what.
https://github.com/oshi/oshi/blob/b8527282d949d5c2ad7655b59d24f87c0a83210b/pom.xml#L312-L322

If this is a feature you want in the next release, I really need you or another OSGi user to do this fix.

**Comment by hazendaz** [comment]
There has been a lot of chatter on slf4j around osgi.  Bet you can find help from there.  Latest release of 2.x got some osgi automated fixes so probably worth checking that pom.  No experience either here just noting possible place to check.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mshabarov** [comment]
@dbwiddis thanks for fast reply!
I've made a patch here https://github.com/oshi/oshi/pull/2329. With this patch I have no more "missing requirement" errors in our OSGi environment, that I had with oshi-core 6.4.0. Could you please review.

**Comment by dbwiddis** [comment]
> @dbwiddis thanks for fast reply! I've made a patch here #2329. With this patch I have no more "missing requirement" errors in our OSGi environment, that I had with oshi-core 6.4.0. Could you please review.

Reviewed.  Inclined to approve as is based on your report that "it works" but do have one comment.

Will try to get a 6.4.1 release out this weekend.
