### ISSUE TITLE
Update links to Central Repository

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#2334]
Our README (and counterpart index.md for site) points to `search.maven.org`.  This now results in:
> On February 23, 2023, we started redirecting users from search.maven.org to central.sonatype.com. Launched in September of 2022, central.sonatype.com provides the main functionality of search.maven.org with enhanced search results, including security vulnerability and software quality information.

The links should be updated to https://central.sonatype.com/artifact/com.github.oshi/oshi-core/6.4.1

**Comment by mprins** [comment]
Why not point to https://repo.maven.apache.org/maven2/com/github/oshi/oshi-core/6.4.1/ instead, as that is the actual location of the files and Sonatype just provides a fancy frontend that, in part, serves to market their services

**Comment by dbwiddis** [comment]
Done in 87096514b3b8e5fe5a89dbd1f91fdbecdd73597a
