### ISSUE TITLE
Reading product_uuid takes a long time

### ISSUE THREAD

**Issue by Artur-** [oshi/oshi#2342]
One of our users sees the following when using oshi:

```
08:55:13 [DEBUG] Reading file /sys/devices/virtual/dmi/id/product_uuid
08:55:27 [DEBUG] Reading file /sys/devices/system/cpu/cpu0/topology/core_id
08:55:27 [DEBUG] Reading file /sys/devices/system/cpu/cpu0/topology/core_id
08:55:27 [DEBUG] Reading file /sys/devices/system/cpu/cpu0/topology/physical_package_id
08:55:27 [DEBUG] Reading file /sys/devices/system/cpu/cpu0/topology/physical_package_id
```

Is it expected that reading `/sys/devices/virtual/dmi/id/product_uuid` can take 14 seconds?

For me, it takes a few ms

**Comment by dbwiddis** [comment]
Sysfs is a virtual file system so that call takes approximately 0 ms.

Reading `product_uuid` is part of the `ComputerSystem` call, while the CPU calls are part of `CentralProcessor`.  Something is happening in between you collecting information from these.

14 seconds is longer than it usually takes to collect all information from Linux (maybe twice).  What else is happening? Does it involve a network or external disk drive?

**Comment by Artur-** [comment]
The full code is something like
```
        SystemInfo systemInfo = new SystemInfo();
        HardwareAbstractionLayer hardwareAbstractionLayer = systemInfo.getHardware();

        ComputerSystem computerSystem = hardwareAbstractionLayer.getComputerSystem();
        String uuid = computerSystem.getHardwareUUID();

        CentralProcessor centralProcessor = hardwareAbstractionLayer.getProcessor();
        String processorIdentifier = centralProcessor.getProcessorIdentifier().getIdentifier();
```

This should contribute all the log rows above so anything happening between reading `product_uuid` and `core_id` for `cpu0` should be in oshi

**Comment by dbwiddis** [comment]
The code on Linux to query UUID has several fallbacks to deal with permissions issues:
```java
private static String queryUUID() {
    String result = null;
    if ((result = Sysfs.queryUUID()) == null && (result = Dmidecode.queryUUID()) == null
            && (result = Lshal.queryUUID()) == null && (result = Lshw.queryUUID()) == null) {
        return Constants.UNKNOWN;
    }
    return result;
}
```
It is possible that if you aren't running with elevated permissions, some of the earlier queries are failing, and some of the later ones end up collecting a lot more information than we really need for this single query.

As a debugging step, you might try each of those sub-queries to inspect its results and see what's taking the time. The Java code calls and parses command line input so you could see which call here is slow:
 - `dmidecode -t system`
 - `lshal`
 - `lshw -C system`

**Comment by Artur-** [comment]
time lshw -C system
WARNING: you should run this program as super-user.
polaris
description: Computer
width: 64 bits
capabilities: smp vsyscall32
*-pnp00:00
product: PnP device PNP0b00
physical id: 18e
capabilities: pnp
configuration: driver=rtc_cmos
*-pnp00:01
product: PnP device PNP0c02
physical id: 18f
capabilities: pnp
configuration: driver=system
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.

real 0m15.328s
user 0m14.700s
sys 0m0.620s

**Comment by dbwiddis** [comment]
Well, it seems `lshw` is the culprit.  

Unfortunately Linux makes it really hard to get unique identifying information without sudo permissions.  Based on the output it seems we aren't even getting the result we want after all that waiting.

I'm not sure what to do here:
 - brief searches indicate `lshw` is always slow, so maybe we should jsut not check it
 - I'm not sure it ever provides info that the other commands don't
 - I don't know any way to further narrow the search (to make it shorter) with command line switches
 - You can always skip even asking for UUID by testing `isElevated()`.  Apparently lshw is stil slow but at least in this case one of the earlier methods should return a value.

Happy to update the code to make this time delay shorter (or eliminate the check entirely) but I only have a VM to test on.  Let me know how you think this should be addressed.

**Comment by giusdiluca** [comment]
Any idea why on my operating system (Linux Red Hat 7.7) that call is taking 15 s ?

**Comment by dbwiddis** [comment]
A brief survey of the interwebs suggest battery + network card with buggy driver could be at fault.  But honestly I don't know... any way to narrow down the command line to smaller chunks?

**Comment by dbwiddis** [comment]
Going to take a shot at checking `isElevated` before trying known root-only commands.
