### ISSUE TITLE
Memory Leak kstat2

### ISSUE THREAD

**Issue by hetawfik** [oshi/oshi#2348]
We experience memory leak when using OSHI on  Solaris 11.4 environments.
The environment details are :
**Java ;**
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)

**Solaris:**
  Oracle Solaris 11.4 SPARC
  Copyright (c) 1983, 2022, Oracle and/or its affiliates.
  Assembled 25 February 2022

Here is an example source code that demonstrate the issue
```java
import oshi.SystemInfo;
import oshi.software.os.OperatingSystem;

public class Kstat2LeakTest {

	private static SystemInfo sys = new SystemInfo();
	private static OperatingSystem os = sys.getOperatingSystem();
	
	public static void main(String[] args) throws Exception {
		while (true) {
			getSystemUp(os);
		}
	}

	public static void getSystemUp(OperatingSystem os) {
		os.getSystemUptime();
	}
}
```

Attached a jar files used for testing [couldn't attach] :
Run with the following command:
`java  -Xms4m -Xmx4m -jar kstat2-test.jar &`

Inspect open files by process using : `pfiles <pid> | grep -ic kstat@0`
the number of kstat open keeps increasing
Inspect memory usage using : `pmap -xs <pid> | grep -i total `
the resident memory keeps increasing

**Comment by dbwiddis** [comment]
Hey @hetawfik thanks for the report!  

I don't have a Solaris 11.4 machine on which to do long term testing -- I'm limited to the {Gnu Compile Farm machines](https://cfarm.tetaneutral.net/machines/list/) (gcc211 is 11.3) with 11.4 testing on a VM using GitHub Actions, so it'll be really helpful if you can help narrow this down for me.

Looking at the code path I don't see any unclosed files.  `getSystemUptime()` under Kstat2 does:
```java
        if (HAS_KSTAT2) {
            // Use Kstat2 implementation
            return BOOT_UPTIME.get().getA();
        }
```
which memoizes this method:
```java
    private static Pair<Long, Long> queryBootAndUptime() {
        Object[] results = KstatUtil.queryKstat2("/misc/unix/system_misc", "boot_time", "snaptime");

        long boot = results[0] == null ? System.currentTimeMillis() : (long) results[0];
        // Snap Time is in nanoseconds; divide for seconds
        long snap = results[1] == null ? 0L : (long) results[1] / 1_000_000_000L;

        return new Pair<>(boot, snap);
    }
```
Which calls the same Kstat2 query method used for all queries:
```java
    public static Object[] queryKstat2(String mapStr, String... names) {
        if (!SolarisOperatingSystem.HAS_KSTAT2) {
            throw new UnsupportedOperationException(
                    "Kstat2 requires Solaris 11.4+. Use SolarisOperatingSystem#HAS_KSTAT2 to test this.");
        }
        Object[] result = new Object[names.length];
        Kstat2MatcherList matchers = new Kstat2MatcherList();
        KstatUtil.CHAIN.lock();
        try {
            matchers.addMatcher(Kstat2.KSTAT2_M_STRING, mapStr);
            Kstat2Handle handle = new Kstat2Handle();
            try {
                Kstat2Map map = handle.lookupMap(mapStr);
                for (int i = 0; i < names.length; i++) {
                    result[i] = map.getValue(names[i]);
                }
            } finally {
                handle.close();
            }
        } catch (Kstat2StatusException e) {
            LOG.debug("Failed to get stats on {} for names {}: {}", mapStr, Arrays.toString(names), e.getMessage());
        } finally {
            KstatUtil.CHAIN.unlock();
            matchers.free();
        }
        return result;
    }
```
The `Kstat2MatcherList matchers = new Kstat2MatcherList();` allocation is freed in the outer finally block, and the `Kstat2Handle handle = new Kstat2Handle();` is closed in the inner finally block.  That leaves this call as the only interesting one:
```java
Kstat2Map map = handle.lookupMap(mapStr);
```
That's a wrapper function in JNA to `kstat2_lookup_map()` which doesn't have anything in its documentation about allocating any resources that need to be freed.

Anything you can see in this code that I can change?

**Comment by hetawfik** [comment]
What I noticed that this has something to do with parallel GC. In my test I was using 4m heap and then it was very clear the leak after few minutes of execution. Though if I use higher heap for example 16m, it would leak after a longer timer, but if I force GC (jcmd <pid> GC.run) I could instantly see the leak, like right after performing GC and run pfiles, I would see an increase in kstat@0 by one.
So from observation I would say the leak happens when parallel GC runs, and in fact if I switch to Serial GC there is no leak.

**Comment by dbwiddis** [comment]
> What I noticed that this has something to do with parallel GC ... if I force GC (jcmd GC.run) I could instantly see the leak, like right after performing GC and run pfiles, I would see an increase in kstat@0 by one. 

Very interesting!   

I know that Solaris requires some special handling with its streams that aren't closed when a process is destroyed.  See for example this:
https://github.com/oshi/oshi/blob/6e3cd0d6e6fe4e0d775be08826840ad976d5689f/oshi-core/src/main/java/oshi/util/ExecutingCommand.java#L91-L97

I don't see anything in the Kstat2 code that could be causing this but perhaps there's some other process execution going on that's leaving streams improperly closed?

**Comment by dbwiddis** [comment]
Heya @hetawfik, just following up here.  It sounds to me like there's some underlying issue in the Solaris JDK causing this leak, and not OSHI.  Is there any action I can take on OSHI's part to try to mitigate this?

I suspect it may be related to https://github.com/oshi/oshi/pull/1781 but I'm not sure there's anything I can fix.

**Comment by hetawfik** [comment]
Thank you for the feedback @dbwiddis
Would it be possible to have a configuration on OSHI side to disable using kstat2 and to fallback to kstat even if kstat2 is supported by the Solaris platform?

**Comment by hetawfik** [comment]
Thanks @dbwiddis
