### ISSUE TITLE
Collects the kubernetes pod memory usage

### ISSUE THREAD

**Issue by melin** [oshi/oshi#2369]
the application is running in the pod,  need to collect the memory size used by the pod and check whether it exceeds the maximum memory size of the pod. In this case, oomkilled is avoided

https://stackoverflow.com/questions/54531646/checking-kubernetes-pod-cpu-and-memory

![image](https://github.com/oshi/oshi/assets/1145830/01f747c8-c959-4ebb-95d9-c1e2d104f99c)

**Comment by dbwiddis** [comment]
Hey @melin thanks for the request.

OSHI does not directly provide this information.  I previously looked into adding this to the API in https://github.com/oshi/oshi/issues/893  which summarizes why I didn't do so: it essentially is only relevant for one operating system so I'd be creating a lot of API over head for what amounts to reading a file.

I'm open to implementing this if it's more than the above files, for which we have `FileUtil.readLongFromFile()` that can fetch those values for you.
