### ISSUE TITLE
cpu utilization

### ISSUE THREAD

**Issue by ideal005** [oshi/oshi#2372]
Does it support obtaining the CPU utilization rate of the Godson 3a5000 processor

**Comment by mprins** [comment]
probably when you run Linux; we don't have one so you will need to try

**Comment by ideal005** [comment]
This is the problem encountered：java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:164)

The version used is 6.4.2；The output of uname is： Linux host.localdomain 4.19.90-23.19.v2101.a.ky10.loongarch64 #1 SMP Mon Sep 13 22:33:20 CST 2021 loongarch64 loongarch64 loongarch64 GNU/Linux

**Comment by ideal005** [comment]
> 可能在你运行 Linux 的时候；我们没有，所以你需要试试

This is the problem encountered：java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:164)

The version used is 6.4.2；The output of uname is： Linux host.localdomain 4.19.90-23.19.v2101.a.ky10.loongarch64 https://github.com/oshi/oshi/pull/1 SMP Mon Sep 13 22:33:20 CST 2021 loongarch64 loongarch64 loongarch64 GNU/Linux

**Comment by mprins** [comment]
> java.lang.NoClassDefFoundError

this is not an OSHI error but a general Java error; ie. something in the packaging of your application; things are missing (or perhaps duplicated) on the classpath

**Comment by dbwiddis** [comment]
> at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:164)

This line is testing for the existence of the udev library.   The `NoClassDefFound` error is caught in 6.4.2:

https://github.com/oshi/oshi/blob/468708ced5a40eafb934e8fb4e89ecd62058cc73/oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java#L70-L86

That code was part of https://github.com/oshi/oshi/pull/2327 which was part of release 6.4.1.

The underlying issue causing the exception is likely an older version of JNA as a dependency that does not have the `Udev` class which was added in JNA 5.6.0.

Summary:
 - you're using a JNA dependency earlier than 5.6.0
 - you're using OSHI earlier than 6.4.1

**Comment by ideal005** [comment]
> > 在 oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:164)
> 
> 该行测试 udev 库是否存在。错误`NoClassDefFound`在6.4.2被抓到：
> 
> https://github.com/oshi/oshi/blob/468708ced5a40eafb934e8fb4e89ecd62058cc73/oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java#L70-L86
> 
> 该代码是#2327的一部分，它是版本 6.4.1 的一部分。
> 
> 导致异常的潜在问题可能是旧版本的 JNA 作为依赖项，它没有`Udev`在 JNA 5.6.0 中添加的类。
> 
> 概括：
> 
> * 您使用的是早于 5.6.0 的 JNA 依赖项
> * 您使用的 OSHI 早于 6.4.1

However, the jna version used in the project is 5.13.0

       <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>5.13.0</version>
        </dependency>
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna-platform</artifactId>
            <version>5.13.0</version>
        </dependency>
 
        <dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>
            <version>6.4.2</version>
        </dependency>

**Comment by dbwiddis** [comment]
There may be other project dependencies bringing in the older JNA.

https://github.com/oshi/oshi/blob/master/src/site/markdown/FAQ.md#how-do-i-resolve-jna-noclassdeffounderror-or-nosuchmethoderror-issues

Use `mvn dependency:tree` or `mvn help:effective-pom` for more insight on your project's dependency management.

**Comment by dbwiddis** [comment]
Hey @ideal005 just following up, were you able to resolve your dependencies?
