### ISSUE TITLE
Plugin Validation Failing

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#2373]
For tests:
```
[WARNING] 
[WARNING] Plugin validation issues were detected in 2 plugin(s)
[WARNING] 
[WARNING]  * org.jacoco:jacoco-maven-plugin:0.8.10
[WARNING]   Declared at location(s):
[WARNING]    * com.github.oshi:oshi-parent:6.4.3-SNAPSHOT (pom.xml) @ line 736
[WARNING]   Used in module(s):
[WARNING]    * com.github.oshi:oshi-parent:6.4.3-SNAPSHOT (pom.xml)
[WARNING]    * com.github.oshi:oshi-core:6.4.3-SNAPSHOT (oshi-core/pom.xml)
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin is a Maven 2.x plugin, which will be not supported in Maven 4.x
[WARNING]    * Plugin mixes multiple Maven versions: [3.0, 2.0.2]
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-repository-metadata:3.0, org.apache.maven:maven-artifact:3.0]
[WARNING]    * Plugin depends on plexus-container-default, which is EOL
[WARNING] 
[WARNING]  * pl.project13.maven:git-commit-id-plugin:4.9.10
[WARNING]   Declared at location(s):
[WARNING]    * com.github.oshi:oshi-parent:6.4.3-SNAPSHOT (pom.xml) @ line 598
[WARNING]   Used in module(s):
[WARNING]    * com.github.oshi:oshi-parent:6.4.3-SNAPSHOT (pom.xml)
[WARNING]    * com.github.oshi:oshi-core:6.4.3-SNAPSHOT (oshi-core/pom.xml)
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-settings-builder:3.0, org.apache.maven:maven-repository-metadata:3.0, org.apache.maven:maven-artifact:3.0, org.apache.maven:maven-plugin-api:3.0, org.apache.maven:maven-settings:3.0, org.apache.maven:maven-aether-provider:3.0, org.apache.maven:maven-model:3.0, org.apache.maven:maven-core:3.0, org.apache.maven:maven-model-builder:3.0]
[WARNING] 
[WARNING] 
[WARNING] Fix reported issues by adjusting plugin configuration or by upgrading above listed plugins. If no upgrade available, please notify plugin maintainers about reported issues.
```
For spotless:
```
[WARNING] 
[WARNING] Plugin validation issues were detected in 2 plugin(s)
[WARNING] 
[WARNING]  * org.apache.maven.plugins:maven-site-plugin:3.12.1
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin depends on the deprecated Maven 2.x compatibility layer, which may not be supported in Maven 4.x
[WARNING] 
[WARNING]  * org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin depends on the deprecated Maven 2.x compatibility layer, which may not be supported in Maven 4.x
[WARNING] 
[WARNING] 
[WARNING] Fix reported issues by adjusting plugin configuration or by upgrading above listed plugins. If no upgrade available, please notify plugin maintainers about reported issues.
```

**Comment by hazendaz** [comment]
@dbwiddis git-commit-id-plugin is on version 6.0.0, the group id changed.  Switch and that issue goes away.

```
  <groupId>io.github.git-commit-id</groupId>
  <artifactId>git-commit-id-maven-plugin</artifactId>
  <version>6.0.0</version>
```

Jacoco does not have a fix
Spotless does not have a fix

**Comment by hazendaz** [comment]
How these are being seen.  Maven 3.9.x introduced this.  With maven 3.9.3 the order of warnings will be switched so status is after, see this gist https://gist.github.com/cstamas/7c9bddbf4e8d96cdd9b73670d878e997.  That will help in case those are large with issues.  I don't know an ETA on 3.9.3 yet but changes for that were just applied few hours ago and more adjustments are applied as well in relation to how the warnings are appearing.  While there is an ongoing back and forth on why everyone has to see these issues, it has gotten nearly everyone's attention so plugin updates are occurring all over the place.  All this has to do with maven 4 as noted.

**Comment by hazendaz** [comment]
For both spotless and jacoco, last I checked few days back they had not reported such issues yet there and not sure how fast jacoco will actually move as that one is very slow to release but maybe they will speed up since jacoco currently doesn't support jdk 21.

**Comment by dbwiddis** [comment]
> How these are being seen. 

Running `mvn test` and `mvn spotless:apply` on my local branch. 

> Maven 3.9.x introduced this. 

I'm on 3.9.2.

> While there is an ongoing back and forth on why everyone has to see these issues, it has gotten nearly everyone's attention so plugin updates are occurring all over the place. All this has to do with maven 4 as noted.

Good to know.  They're just warnings but were new to me, figured this issue would be a good place to put the "yeah we know, not our circus, not our monkeys."

**Comment by dbwiddis** [comment]
Updated coordinates for git commit id plugin in #2376.  FreeBSD build is failing now on transitive import of package type for the old coordinates in jgit:
```
  [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/eclipse/jgit/org.eclipse.jgit/6.5.0.202303070854-r/org.eclipse.jgit-6.5.0.202303070854-r.jar (3.1 MB at 895 kB/s)
  Warning:  Error injecting: pl.project13.maven.git.GitCommitIdMojo
  java.lang.TypeNotPresentException: Type pl.project13.maven.git.GitCommitIdMojo not present
```
It's curious that it's only FreeBSD failing there....

but looks like a Java versioning thing:
```
 Caused by: java.lang.UnsupportedClassVersionError: pl/project13/maven/git/GitCommitIdMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by hazendaz** [comment]
Plugin requires java 11.  Many do at this point.  Assume trying to use java 8 there?  Would switch as building with 8 provides no value.  Thought that was already done but maybe missed on that specific action.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dbwiddis** [comment]
It's actually OpenBSD.   The action itself runs on Java 11 but looks like it's just using whatever default Java is installed on the VM there.

I assume there's some command to download and install JDK 11+ on OpenBSD but I haven't looked into it yet.  I figure @mprins might have an idea to save me some web searching :)

**Comment by dbwiddis** [comment]
(Which looks like downloading the JDK 11 or JDK 17 tarball from [here](https://cdn.openbsd.org/pub/OpenBSD/snapshots/packages/amd64/) and unzipping it and setting a few environment variables.)

**Comment by mprins** [comment]
The [OpenBSD Maven (3.8.7) port](https://www.ports.to/path/devel/maven.html) 
has a default dependency on >= jdk-8, since we don't explicitly install a JDK:

https://github.com/oshi/oshi/blob/46226fdf0634c490fa182bb86bbe203aa5460b77/.github/workflows/openbsd.yaml#L27
the lowest version that satisfies the requirement is installed.
adding `pkg_add jdk-11.0.18.10.1p0v0` unfortunately there is no "meta package" so this will probably break when upgrading to OpenBSD 7.4

**Comment by dbwiddis** [comment]
In the Solaris workflow we add -Dmaven.gitcommitid.skip=true to the maven execution (and extract java there too)
