### ISSUE TITLE
cpu LogicalProcessor info not correct

### ISSUE THREAD

**Issue by silencewood** [oshi/oshi#2390]
oshi version is 6.4.2
jna version is 5.13.0
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.5 (Santiago)

SystemInfoTest output
Intel Core Processor (Broadwell, IBRS)
 1 physical CPU package(s)
 1 physical CPU core(s)
 1 logical CPU(s)

 cat /proc/cpuinfo |grep processor
processor       : 0
processor       : 1
processor       : 2
processor       : 3

**Comment by dbwiddis** [comment]
Please post (or link to a pastebin) the entire output of `/proc/cpuinfo`.

**Comment by dbwiddis** [comment]
OSHI reads Linux processor information from udev (if available) or sysfs otherwise.

What is the contents of `/sys/devices/system/cpu/` (where there should be multiple CPUs listed)?

**Comment by dbwiddis** [comment]
One more debugging question: are you operating in a VM?  How many processors does the VM have?  It's possible `/proc/cpuinfo` is reporting for the machine while `/sys/devices/system/cpu` is reporting for your VM, which is what OSHI is reporting.

**Comment by silencewood** [comment]
yes is a vm

processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 61
model name      : Intel Core Processor (Broadwell, IBRS)
stepping        : 2
cpu MHz         : 2299.996
cache size      : 4096 KB
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good unfair_spinlock pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm 3dnowprefetch xsaveopt fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm
bogomips        : 4599.99
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 61
model name      : Intel Core Processor (Broadwell, IBRS)
stepping        : 2
cpu MHz         : 2299.996
cache size      : 4096 KB
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good unfair_spinlock pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm 3dnowprefetch xsaveopt fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm
bogomips        : 4599.99
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 61
model name      : Intel Core Processor (Broadwell, IBRS)
stepping        : 2
cpu MHz         : 2299.996
cache size      : 4096 KB
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good unfair_spinlock pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm 3dnowprefetch xsaveopt fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm
bogomips        : 4599.99
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 61
model name      : Intel Core Processor (Broadwell, IBRS)
stepping        : 2
cpu MHz         : 2299.996
cache size      : 4096 KB
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good unfair_spinlock pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm 3dnowprefetch xsaveopt fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm
bogomips        : 4599.99
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:


ls /sys/devices/system/cpu/
cpu0  cpu1  cpu2  cpu3  cpufreq  cpuidle  kernel_max  offline  online  possible  present

**Comment by silencewood** [comment]
is used udev
in oshi version 5.2.2 LogicalProcessor info is correct
I found version 5.2.2 is used /proc/cpuinfo

**Comment by dbwiddis** [comment]
Thanks for the added info.  I may need your additional help debugging exactly what's wrong here.

The fact that you have 4 CPUs in sysfs and OSHI is only showing 1 is definitely an issue/bug.  It would be really helpful if you could trace through OSHI's code and identify what's broken, as of now I'm not really sure:
 - is UDEV giving different results than iterating sysfs?
 - are those sysfs paths missing information that causes it to fail?

Ultimately I'd like to find what primary source is failing so I can return to a backup source with better info.

**Comment by silencewood** [comment]
I test then diffrent os version
in Red Hat Enterprise Linux Server release 7.8 is ok


Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
 2 physical CPU package(s)
 36 physical CPU core(s)
 72 logical CPU(s)
Identifier: Intel64 Family 6 Model 79 Stepping 1
ProcessorID: F1 06 04 00 FF FB EB BF
Microarchitecture: Broadwell (Server)
 Topology:
  LogProc  P/E Proc  Pkg NUMA PGrp
     0,36    P    0    0    0    0
     2,38    P    1    0    0    0
     4,40    P    2    0    0    0
     6,42    P    3    0    0    0


[root@test1 ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.5 (Santiago)
[root@test1 ~]# uname -a
Linux test1 2.6.32-431.el6.x86_64 #1 SMP Sun Nov 10 22:19:54 EST 2013 x86_64 x86_64 x86_64 GNU/Linux
[root@test1 ~]# ls /sys/devices/system/cpu/cpu0
cache  crash_notes  microcode  node0  topology
[root@test1 ~]# udevadm info  --attribute-walk --path=/sys/devices/system/cpu/cpu0
device path not found


[root@test2 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.8 (Maipo)
[root@test2 ~]# uname -a
Linux test2 3.10.0-1127.el7.x86_64 #1 SMP Tue Feb 18 16:39:12 EST 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@test2 ~]# ls /sys/devices/system/cpu/cpu0
cache  cpufreq  cpuidle  crash_notes  crash_notes_size  driver  firmware_node  microcode  node0  online  power  subsystem  thermal_throttle  topology  uevent
[root@test2 ~]# udevadm info  --attribute-walk --path=/sys/devices/system/cpu/cpu0

Udevadm info starts with the device specified by the devpath and then
walks up the chain of parent devices. It prints for every device
found, all possible attributes in the udev rules key format.
A rule to match, can be composed by the attributes of the device
and the attributes from one single parent device.

  looking at device '/devices/system/cpu/cpu0':
    KERNEL=="cpu0"
    SUBSYSTEM=="cpu"
    DRIVER=="processor"
    ATTR{online}=="1"
    ATTR{crash_notes}=="1fff421800"
    ATTR{crash_notes_size}=="368"

  looking at parent device '/devices/system/cpu':
    KERNELS=="cpu"
    SUBSYSTEMS==""
    DRIVERS==""
    ATTRS{kernel_max}=="5119"
    ATTRS{possible}=="0-71"
    ATTRS{online}=="0-71"
    ATTRS{offline}==""
    ATTRS{isolated}==""
    ATTRS{nohz_full}==""
    ATTRS{present}=="0-71"

**Comment by dbwiddis** [comment]
Thanks for these details!

Looks like we should probably test whether the udev/sysfs values work and if not, fallback to the old 5.2.2 behavior.

**Comment by dbwiddis** [comment]
Can you test whether #2396 gives you the correct output?

**Comment by silencewood** [comment]
physical CPU core not correct  yet

Intel Core Processor (Broadwell, IBRS)
 1 physical CPU package(s)
 0 physical CPU core(s)
 4 logical CPU(s)
Identifier: Intel64 Family 6 Model 61 Stepping 2
ProcessorID: D2 06 03 00 FD FB 8B 07
Microarchitecture: Broadwell (Client)
 Topology:
  LogProc  P/E Proc  Pkg NUMA PGrp
Physical Memory: 
 Available: 2.8 GiB/3.7 GiB

in method mapCachesFromLscpu 
        List<String> lscpu = ExecutingCommand.runNative("lscpu -B -C --json");

[root@test1 lib]# lscpu -B -C --json
lscpu: invalid option -- 'B'

Usage:
 lscpu [options]

Options:
 -a, --all               print online and offline CPUs (default for -e)
 -b, --online            print online CPUs only (default for -p)
 -c, --offline           print offline CPUs only
 -e, --extended[=<list>] print out an extended readable format
 -h, --help              print this help
 -p, --parse[=<list>]    print out a parsable format
 -s, --sysroot <dir>     use directory DIR as system root
 -V, --version           print version information and exit
 -x, --hex               print hexadecimal masks rather than lists of CPUs

Available columns:
           CPU  logical CPU number
          CORE  logical core number
        SOCKET  logical socket number
          NODE  logical NUMA node number
          BOOK  logical book number
         CACHE  shows how caches are shared between CPUs
  POLARIZATION  CPU dispatching mode on virtual hardware
       ADDRESS  physical address of a CPU
    CONFIGURED  shows if the hypervisor has allocated the CPU
        ONLINE  shows if Linux currently makes use of the CPU

For more details see lscpu(1).

**Comment by dbwiddis** [comment]
OK, looks like we can't get the detailed cache info so that'll just end up empty.  I'll figure out how I missed that physical core...

**Comment by dbwiddis** [comment]
OK fixed the physical processors.  Should be as good as it's going to get I think.
