### ISSUE TITLE
Can i get Partitions,TcpIp Network Interface, Load,Operating System,Computer System,Network Adapters data through oshi 

### ISSUE THREAD

**Issue by darshanh** [oshi/oshi#2399]
Can i get Partitions,TcpIp Network Interface, Load,Operating System,Computer System,Network Adapters,Network Adapter Configurations,Missing properties and classes Data through oshi ? If yes  please suggest  how i can get these 

Note : currently we are fetching only process related data using oshi 

Thank you

**Comment by dbwiddis** [comment]
> Can i get Partitions,TcpIp Network Interface, Load,Operating System,Computer System,Network Adapters,Network Adapter Configurations,Missing properties and classes Data through oshi ?

From the README:

> Supported Features
> ------------------
> * Computer System and firmware, baseboard
> * Operating System and Version/Build
> * Physical (core) and Logical (hyperthreaded) CPUs, processor groups, NUMA nodes
> * System and per-processor load, usage tick counters, interrupts, uptime
> * Process uptime, CPU, memory usage, user/group, command line args, thread details
> * Physical and virtual memory used/available
> * Mounted filesystems (type, usable and total space, options, reads and writes)
> * Disk drives (model, serial, size, reads and writes) and partitions
> * Network interfaces (IPs, bandwidth in/out), network parameters, TCP/UDP statistics
> * Battery state (% capacity, time remaining, power usage stats)
> * USB Devices
> * Connected displays (with EDID info), graphics and audio cards
> * Sensors (temperature, fan speeds, voltage) on some hardware

I believe that covers most of your list except "Missing properties and classes"; I'm not even sure what that is.

**Comment by darshanh** [comment]
Can i fetch the partitions data using below code, can you please help me on this  : // Partition Collection Code
        List<OSFileStore> fileStores = os.getFileSystem().getFileStores();
        List<WindowsRawData.WinPartition> partitions = new ArrayList<>();

        for (OSFileStore fileStore : fileStores) {
            WindowsRawData.Partition partition = WindowsRawData.Partition.builder()
                    .name(fileStore.getName())
                    .diskReads(fileStore.getDiskReads())
                    .diskWrites(fileStore.getDiskWrites())
                    .diskReadBytes(fileStore.getDiskReadBytes())
                    .diskWriteBytes(fileStore.getDiskWriteBytes())
                    .avgDiskSecPerRead(fileStore.getAvgDiskSecPerRead())
                    .avgDiskSecPerWrite(fileStore.getAvgDiskSecPerWrite())
                    .diskUtilization(fileStore.getDiskUtilization())
                    .build();

            partitions.add(partition);
        }

        rawData.setPartitions(partitions);
    }



As i need below partition data: 
          "name"
"diskReadsPerSec"
            "diskReadBytesPerSec", 
           "diskSecPerRead", "AvgDiskSecPerRead"
            "diskSecPerReadBase", "AvgDisksecPerRead_Base"
         "diskWritesPerSec",
          "diskWriteBytesPerSec",
          "diskSecPerWrite", "AvgDisksecPerWrite"
           "diskSecPerWriteBase", "AvgDisksecPerWrite_Base"
  "diskUtilizationPct", "PercentDiskTime"

**Comment by dbwiddis** [comment]
The code you have iterates over the file stores, which are the software side of partitions.  The [OSFileStore API](https://www.oshi.ooo/oshi-core/apidocs/oshi/software/os/OSFileStore.html) does not include many of the methods you have shown.

Operating systems don't record the information you're requesting (reads/writes) at the partition level, only at the disk level.  If the disk only has one partition (or only one mapped to a file store) then the stats are probably pretty reliable.
```java
SystemInfo si = new SystemInfo();
HardwareAbstractionLayer hal = si.getHardware();
List<HWDiskStore> list = hal.getDiskStores();

for (HWDiskStore disk : list) {
    List<HWPartition> partitions = disk.getPartitions();
    // get stats from disks
    for (HWPartition part : partitions) {
        // get stats from partition, including mount point
    }
}
```
So you can iterate the partitions as above and match up to file stores by mount point, and get the statistics from the disk on which the partition is on.

**Comment by darshanh** [comment]
i am actually looking for data something like : "perfLogicalDisks": {
    "C:": {
      "name" : "C:",
      "diskReadsPerSec" : "12511608",
      "diskReadBytesPerSec" : "290481390080",
      "diskSecPerRead" : "-314480947",
      "diskSecPerReadBase" : "12511608",
      "diskWritesPerSec" : "61383373",
      "diskWriteBytesPerSec" : "798454449152",
      "diskSecPerWrite" : "1223260855",
      "diskSecPerWriteBase" : "61383373",
      "diskUtilizationPct" : "696555842000",
      "diskUtilizationPctBase" : "133304065983371990",
      "freeSpaceMb" : "24457",
      "percentFreeSpace" : "24457",
      "percentFreeSpaceBase" : "81916",
      "perfTicksPerSec" : "14318180",
      "timestamp" : "133304065983371990",
      "timestampTicksPerSec" : "10000000"
    }
    ,
    "D:": {
      "name" : "D:",
      "diskReadsPerSec" : "4999420",
      "diskReadBytesPerSec" : "65491495424",
      "diskSecPerRead" : "-1647151340",
      "diskSecPerReadBase" : "4999420",
      "diskWritesPerSec" : "11406207",
      "diskWriteBytesPerSec" : "124702749696",
      "diskSecPerWrite" : "1202945162",
      "diskSecPerWriteBase" : "11406207",
      "diskUtilizationPct" : "461637413000",
      "diskUtilizationPctBase" : "133304065983371990",
      "freeSpaceMb" : "42523",
      "percentFreeSpace" : "42523",
      "percentFreeSpaceBase" : "127996",
      "perfTicksPerSec" : "14318180",
      "timestamp" : "133304065983371990",
      "timestampTicksPerSec" : "10000000"
    }
    ,
    "_Total": {
      "name" : "_Total",
      "diskReadsPerSec" : "17511028",
      "diskReadBytesPerSec" : "355972885504",
      "diskSecPerRead" : "-1961632287",
      "diskSecPerReadBase" : "17511028",
      "diskWritesPerSec" : "72789580",
      "diskWriteBytesPerSec" : "923157198848",
      "diskSecPerWrite" : "-1868761279",
      "diskSecPerWriteBase" : "72789580",
      "diskUtilizationPct" : "579096627500",
      "diskUtilizationPctBase" : "133304065983371990",
      "freeSpaceMb" : "66980",
      "percentFreeSpace" : "66980",
      "percentFreeSpaceBase" : "209912",
      "perfTicksPerSec" : "14318180",
      "timestamp" : "133304065983371990",
      "timestampTicksPerSec" : "10000000"
    }

**Comment by mprins** [comment]
@darshanh Please check the demo code in https://github.com/oshi/oshi/tree/master/oshi-demo and the API docs for the options Oshi provides

**Comment by darshanh** [comment]
"perfLogicalDisks": {
"C:": {
"name" : "C:",
"diskReadsPerSec" : "11250063",
"diskReadBytesPerSec" : "270031627264",
"diskSecPerRead" : "1932582950",
"diskSecPerRead" : "1969868237",
"diskSecPerReadBase" : "15789730",
"diskWritesPerSec" : "64929079",
"diskWriteBytesPerSec" : "816437689856",
"diskSecPerWrite" : "786163290",
"diskSecPerWriteBase" : "64929079",
"diskUtilizationPct" : "515404127500",
"diskUtilizationPctBase" : "133301674296436845",
"percentFreeSpace" : "67198",
"percentFreeSpaceBase" : "209912",
"perfTicksPerSec" : "14318180",
"timestamp" : "133301674296436845",
"timestampTicksPerSec" : "10000000"
}
},
"logicalDisks": {
"C:": {
"name" : "C:",
"sizeBytes" : "85896196096",
"freeSpaceBytes" : "25870942208",
"driveType" : "3"
}
,
"D:": {
"name" : "D:",
"sizeBytes" : "134214578176",
"freeSpaceBytes" : "44599218176",
"driveType" : "3"
}

**Comment by dbwiddis** [comment]
> i am actually looking for data something like : "perfLogicalDisks"

What you have shown is a Windows-only perfcounter for "Logical Disks".  However, that's just a convenience function that gives you the data for the underlying physical disk.  You can trace it through with the tables LogicalDiskToPartition and then PartitionToPhysicalDisk.

Disk reads/writes are actually recorded at the hardware level by hard drive manufacturers. That's the real source of the data.  OSHI faithfully reports that data on the physical drives.

My answer [here](https://github.com/oshi/oshi/issues/2399#issuecomment-1579897240) showed you how to iterate `HWDiskStore` objects in OSHI. These are the objects with the statistics that you seek.

To correlate these disk stores with file stores, look at the partition mount points.

Running `SystemInfoTest` on a Windows system (see the README) will give you this output:
```
  Disks:
   \\.\PHYSICALDRIVE1: (model: Virtual HD ATA Device Microsoft - S/N: ) size: 15.0 GB, reads: 55 (213 KiB), writes: 2413 (143.6 MiB), xfer: 1347
   |-- Disk #1, Partition #0: Installable File System (Installable File System) Maj:Min=1:0, size: 15.0 GB @ D:\
   \\.\PHYSICALDRIVE0: (model: Virtual HD ATA Device Microsoft - S/N: ) size: 274.9 GB, reads: 50883 (1.0 GiB), writes: 13362 (1.7 GiB), xfer: 203379
   |-- Disk #0, Partition #1: Installable File System (Installable File System) Maj:Min=0:1, size: 274.4 GB @ C:\
```
Note there are two physical disks.  Physical drive 0 has a partition (Disk 0, partition 1) which is mounted as the C drive.  Physical drive 1 has a partition (Disk 1, partition 0) which is mounted as the D drive.  You can see the read/write statistics on the physical disks.

If you iterate the OSFileStores that give you file stores. Note the same mount points on the C and D drives.  On the software side you can see used and free space.
```
File System:
   File Descriptors: 39670/16711680
   3 1/2 Inch Floppy Drive (A:) (Removable drive) [] 0 bytes of 0 bytes free (NaN%), 0 of 0 files free (NaN%) is \\?\Volume{2a20f877-00d2-11ee-a976-806e6f6e6963}\  and is mounted at A:\
   Local Fixed Disk (C:) (Fixed drive) [NTFS] 81.9 GiB of 255.5 GiB free (32.0%), 0 of 0 files free (NaN%) is \\?\Volume{a0ccf69e-0000-0000-0000-501f00000000}\  and is mounted at C:\
   Local Fixed Disk (D:) (Fixed drive) [NTFS] 12.2 GiB of 14.0 GiB free (86.9%), 0 of 0 files free (NaN%) is \\?\Volume{21f8a468-0000-0000-0000-100000000000}\  and is mounted at D:\
```

There is a sample in the oshi-demo project that links disks/partition pairs with filestores, but it's really just as simple as comparing the mount points as you can see above.

**Comment by darshanh** [comment]
i am looking for  these values  
 class PerfLogicalDisk {
        private String name;

        private long diskReadsPerSec;
        private BigInteger diskReadBytesPerSec;
        private long diskSecPerRead;
        private long diskSecPerReadBase;

        private long diskWritesPerSec;
        private BigInteger diskWriteBytesPerSec;
        private long diskSecPerWrite;
        private long diskSecPerWriteBase;

        private BigInteger diskUtilizationPct;
        private BigInteger diskUtilizationPctBase;

        private long freeSpaceMb;
        private int percentFreeSpace;
        private int percentFreeSpaceBase;

        private BigInteger perfTicksPerSec;
        private BigInteger timestamp;
        private BigInteger timestampTicksPerSec;
}
Got confused with your above answer . Can you please guide me to fetch these values

**Comment by dbwiddis** [comment]
You keep asking for raw data without explaining what you want to do with it.  You are asking an [XY problem](https://xyproblem.info/).

What are you actually doing with these values? 

Is it windows-only or cross-platform?  

Why must you do this in Java?

It would be helpful to know what you want to use this information _for_, since you're just listing the values available from the `LogicalDisk` Performance Counter data. 

If you just want those values, you don't need OSHI.  OSHI is a cross-platform API. You look like you want very specific Windows-only abstractions.  If that's the case, Just query [this WMI table](https://wutils.com/wmi/root/cimv2/win32_perfrawdata_perfdisk_logicaldisk/) using `wmic` commandline or `PowerShell` or many COM integrations in MS products, or use the Perfmon command line API to fetch the values you want.
  - If you want to use OSHI to fetch the performance counter values, take a look at the classes in the `oshi.driver.windows.perfmon` package. The `PhysicalDisk` one is a good example as it's behind the same data from a different performance counter.  Just change that to `LogicalDisk` and add enum values for all the counter values you want.
  - You can then use these values for whatever it is your program is doing that you're not telling us.
  - For example, the fields ending in "Base" are just used as the denominator for calculations, often serving as a timestamp or equivalent.  The "Base" values are not available in the OSHI API.

If OSHI's API values are what you really want, so you don't have to recreate the math yourself with all the base counters above, that has been previously answered in this issue.
1. [This comment](https://github.com/oshi/oshi/issues/2399#issuecomment-1579855075) shows you iterating over the [OSFileStore](https://www.oshi.ooo/oshi-core-java11/apidocs/com.github.oshi/oshi/software/os/OSFileStore.html) objects. 
   - That API gives you the "Free Space".  
   - They will also tell you the file system "mount point" for those stores.
3. [This comment](https://github.com/oshi/oshi/issues/2399#issuecomment-1579897240) shows you how to iterate over the physical disks and their partitions.  
   - The partitions also have a mount point.  If the mount point of the partition matches the mount point of the file store, then the enclosing disk statistics apply.  
   - The [HWDiskStore](https://www.oshi.ooo/oshi-core-java11/apidocs/com.github.oshi/oshi/hardware/HWDiskStore.html) API gives you reads, writes, read bytes, write bytes, and transfer time (combined between reads and writes; you can split this time between reads and writes proportionally to calculate the "per sec" values.  
   - The ratio of change in transfer time vs. change in timestamps will give you the disk utilization.
