### ISSUE TITLE
在本地测试报错

### ISSUE THREAD

**Issue by rongyanjuren** [oshi/oshi#2401]
mac电脑，java8，集成后报错，Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jna/platform/unix/LibCAPI$size_t$ByReference，
依赖为<dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>
            <version>6.4.0</version>
        </dependency>，哪位大佬给解决一下呢

**Comment by dbwiddis** [comment]
Even though you have a recent version of OSHI, this error message indicates that you have an older version of JNA loaded as a transitive dependency from another project or operating system configuration.  Use `mvn dependency:tree` to help troubleshoot where else JNA is being brought in from.

[See the FAQ](https://github.com/oshi/oshi/blob/master/src/site/markdown/FAQ.md#how-do-i-resolve-jna-noclassdeffounderror-or-nosuchmethoderror-issues):

> ## How do I resolve JNA `NoClassDefFoundError` or `NoSuchMethodError` issues?
> 
> OSHI uses the latest version of JNA, which may conflict with other dependencies your project (or its parent) includes.
> If you experience a `NoClassDefFoundError` or `NoSuchMethodError` issues with JNA artifacts, you likely have
> an older version of either `jna` or `jna-platform` in your classpath from a transitive dependency on another project.
> Consider one or more of the following steps to resolve the conflict:
>  - Listing OSHI earlier (or first) in your dependency list
>  - Specifying the most recent version of JNA (both `jna` and `jna-platform` artifacts) in your `pom.xml` as dependencies.
>  - If you are using the Spring Boot Starter Parent version 2.2 and earlier that includes JNA as a dependency:
>    - Upgrade to version 2.3 which does not have a JNA dependency (preferred)
>    - If you must use version 2.2 or earlier, override the `jna.version` property to the latest JNA version.
