### ISSUE TITLE
`getent passwd` never quits (or at least not in a reasonable timespan)

### ISSUE THREAD

**Issue by MikeDombo** [oshi/oshi#2405]
On a RedHat enterprise system, we're unable to list child processes because `getent` is hanging: https://github.com/oshi/oshi/blob/6ff3e0ab40565ae26f297cb31b66f57b4732acec/oshi-core/src/main/java/oshi/util/UserGroupInfo.java#L73.

The output keeps scrolling on and on without a limit (seems to be dumping all ldap users or something like that?). Looking at `/etc/passwd` shows a far more reasonable list of users on that device.

Can we avoid calling `getent passwd`? Particularly when I don't even care about the user, I just want (in my use case) to list the child pids and then kill them; I don't need any metadata.

Any reason why reading /etc/passwd is only for Aix, seems that would work for us in this case?

**Comment by dbwiddis** [comment]
In general when writing these routines I preferred command lines to reading files (other than procfs/sysfs), but it does seem that on RHEL/CentOS this was definitely not a good idea.

Happy to switch this to the passwd file (or make passwd checked first and only do this as a backup).  Or make it configurable which option is used in the config file (defaulting to passwd).  Would welcome a PR.

**Comment by MikeDombo** [comment]
Thanks for the reply. Of course I have no data, but it feels that most of the time, people wouldn't be interested in what user the process is running as. Would it make sense to only fetch that "expensive" metadata after it js actually requested? Ie. getUser could be memoized such that getent is called only once and when actually needed.

**Comment by dbwiddis** [comment]
> getUser could be memoized such that getent is called only once and when actually needed.

The user and group maps are currently memoized with a 1-minute expiration to re-fetch; so given typical process-query behavior it would only fetch the information once each minute.

However, the "when actually needed" is probably more important here. 

Some thoughts on fixes:
1. Extend the timeout to longer than 1m.  Perhaps 5m.
2. Don't pre-populate `this.user` and `this.group` when the process is queried.  Make those calls memoized (a second level of memoization with no timeout) and called only when requested.
3. Prioritize using the passwd file (local users) and only check getent passwd if the user isn't found there.

**Comment by dbwiddis** [comment]
Should be fixed in #2407.  Would be great if you could test SNAPSHOT. Let me know if I should prioritize a release ASAP, otherwise will probably do it next weekend.

**Comment by MikeDombo** [comment]
Wow, so fast! Thank you @dbwiddis 
Will try it out most likely later this week. No need for an ASAP release, just whenever you're able.
