### ISSUE TITLE
Unable to get processor.getMaxFreq() and processor.getCurrentFreq() on Windows

### ISSUE THREAD

**Issue by gautier-levert** [oshi/oshi#2412]
Hello,

I'm currently using "oshi-core-java11" v6.4.4 in a JDK17 application.

I try to get CPU frequency on Windows 11 (21H2) but always get the value 0.

Here is a simple example to reproduce the behavior.
```java
final var si = new SystemInfo();
final var hardware = si.getHardware();
final var processor = hardware.getProcessor();

System.out.println("processor.getMaxFreq(): " + processor.getMaxFreq());
System.out.println("processor.getCurrentFreq(): " + Arrays.toString(processor.getCurrentFreq()));
```

And the output I get.
```
processor.getMaxFreq(): 0
processor.getCurrentFreq(): [0, 0, 0, 0]
```

I tried on different Windows machines (VM, laptops and desktops) with the exact same result.

Do you know why I am unable to get processor frequency ? Is there another way to collect this information ?

Thanks in advance for your help.

**Comment by MC-XiaoHei** [comment]
I have encountered the same problem, can this problem be solved?
I use Windows 11 23H2 25926.1000

**Comment by dbwiddis** [comment]
> I have encountered the same problem ... I use Windows 11 23H2 25926.1000

It's possible something changed in the most recent Windows version, but I don't have a Windows machine to test with.

> can this problem be solved?

I don't know without further debugging as requested in [this comment](https://github.com/oshi/oshi/issues/2412#issuecomment-1642763130): 
> Adding some debugging to show the value (toString()) of ppiArray[i] [here](https://github.com/oshi/oshi/blob/4c072a3d98a6f055be2376f5f5c12f5ba821026d/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java#L259C28-L259C28) would help debug further.

**Comment by dbwiddis** [comment]
Set up a Windows VM to test this... CallNtPowerInformation is returning all 0's but not indicating failure.  May be a Windows bug.  Added a fallback to Vendor frequency to work around it.

**Comment by TheodoreSKong** [comment]
Still has this problem on windows 22H2 with oshi 6.4,8

**Comment by dbwiddis** [comment]
> Still has this problem on windows11 22H2 with oshi 6.4,8

Can you be more specific on "this problem"?  OSHI changed the code for getting "max" to fall back to vendor, but if there's no vendor frequency available, that doesn't work, and there's a different question on how to get that.

**Comment by TheodoreSKong** [comment]
Both the GetMaxFreq and GetcurrentFreqmethod return 0. How can I test if the vendor frequency available?

**Comment by dbwiddis** [comment]
`getProcessorIdentifier().getVendorFreq()`

https://www.oshi.ooo/oshi-core-java11/apidocs/com.github.oshi/oshi/hardware/CentralProcessor.ProcessorIdentifier.html#getVendorFreq()

**Comment by TheodoreSKong** [comment]
> `getProcessorIdentifier().getVendorFreq()`
> 
> https://www.oshi.ooo/oshi-core-java11/apidocs/com.github.oshi/oshi/hardware/CentralProcessor.ProcessorIdentifier.html#getVendorFreq()

`long vendorFreq = processor.getProcessorIdentifier().getVendorFreq()` return 2189000000;
while `long[] currentFreq = processor.getCurrentFreq();` return `[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]`,
it seems the vendor freq is availiable, have no idea on what happens

**Comment by dbwiddis** [comment]
OK, reopening this as the max and current should have been set to 2189000000 by https://github.com/oshi/oshi/pull/2436 in 6.4.5.
