### ISSUE TITLE
unable to find class in gradle project

### ISSUE THREAD

**Issue by pavanjoshi914** [oshi/oshi#2419]
![image](https://github.com/oshi/oshi/assets/55848322/39d52cdf-0d44-42b4-8ffa-ef6d97ecaf07)

oshi-core version: 6.4.4 added as a gradle dependency

**Comment by pavanjoshi914** [comment]
@dbwiddis

**Comment by dbwiddis** [comment]
Please either post your build.gradle file or the output of gradle dependencies.

**Comment by pavanjoshi914** [comment]
```plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    compileSdk 34

    defaultConfig {
        applicationId "com.example.cpupulse"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    packagingOptions {
        pickFirst 'META-INF/AL2.0'
        pickFirst 'META-INF/LGPL2.1'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation 'net.java.dev.jna:jna:5.13.0'
    implementation 'net.java.dev.jna:jna-platform:5.13.0'
    implementation "com.github.oshi:oshi-core:6.4.4"
    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'



}
```

**Comment by pavanjoshi914** [comment]
i tried all the solutions mentioned in FAQ. also added rules in proguard for jna 

```
-keep class com.sun.jna.** { *; }
-keep class com.sun.jna.platform.** { *; }
```

**Comment by dbwiddis** [comment]
If JNA shows up on your Gradle dependency tree then it's not a problem with OSHI or dependency management.  I suspect something is still amiss with Proguard.

Can you use verbose to track what Proguard is doing? 

Note the second line is redundant, `com.sun.jna.**` includes the platform packages as well.  You may want to include a line for subclasses though:
```
-keep class com.sun.jna.** { *; }
-keep class * extends com.sun.jna.** { *; }
```

You might try the `-dontoptimize` switch for troubleshooting. If it works, we can fine-tune.

If that fails, I'd suggest asking on the [jna-users mailing list](https://groups.google.com/g/jna-users) to get more eyes on your question.

**Comment by dbwiddis** [comment]
Oops!  I was just looking at other issues and it looks like you have the same problem as #2409 

You're on android so the regular JNA dependency doesn't work.  You need to use the AAR dependency.

See [this comment](https://github.com/oshi/oshi/issues/2409#issuecomment-1616007705) for options to try, with the best one probably being:
```groovy
implementation ('net.java.dev.jna:jna:5.13.0@aar')
  implementation ('net.java.dev.jna:jna-platform:5.13.0@aar')
  implementation group: 'com.github.oshi', name: 'oshi-core', version: '6.4.3' {
    exclude group: 'net.java.dev.jna`
  }
```

**Comment by dbwiddis** [comment]
See also https://github.com/java-native-access/jna/blob/master/www/FrequentlyAskedQuestions.md#jna-on-android

**Comment by pavanjoshi914** [comment]
does jna-platform@aar exist. i am gettin failed to resolve for this package

**Comment by pavanjoshi914** [comment]
i think solution mentioned by you works. Thanks! now i am getting platform specific error. if i run applicationw with just jna@aar and without platform@aar

**Comment by dbwiddis** [comment]
> i think solution mentioned by you works. Thanks! now i am getting platform specific error. if i run applicationw with just jna@aar and without platform@aar

Ah, not sure of this, mostly going by the docs. And it's not clear exactly what config works for you.

I think the JAR for `jna-platform` and AAR for `jna` should work?

```
implementation ('net.java.dev.jna:jna:5.13.0@aar')
implementation ('net.java.dev.jna:jna-platform:5.13.0')
implementation ('com.github.oshi:oshi-core:6.4.4') {
  exclude group: 'net.java.dev.jna` artifact: `jna`
}
```
