### ISSUE TITLE
getProcessor() doesn't return processor name

### ISSUE THREAD

**Issue by pavanjoshi914** [oshi/oshi#2426]
oshi doesn't return processror name such as ``` cortexA55``` . i am looking for something that can give the output of lscpu command (which includes model name) on android. running lscpu is not possible without rooting i think.

**Comment by mprins** [comment]
You have failed to provide your code, ARM cpu's are known in OSHI, see eg. https://github.com/oshi/oshi/blob/fd8e0b5f558fbf0df5a2d9b16b2a4e523837ab33/oshi-core/src/main/resources/oshi.architecture.properties#L253

code like below should get you the processor identifier which can the provide the name, vendor etc.

```java
SystemInfo si = new SystemInfo();
HardwareAbstractionLayer hal = si.getHardware();
CentralProcessor cpu = hal.getProcessor();
ProcessorIdentifier processorIdentifier = cpu.getProcessorIdentifier();

```

**Comment by dbwiddis** [comment]
> running lscpu is not possible without rooting i think.

OSHI can't magically get information that you can't get yourself.    Without elevated privileges, the best it can do is parse `/proc/cpuinfo` for processor identification. For Intel chips, that's family/model/stepping. For ARM chips it's implementer/variant/part/revision.  @mprins has given you the code which extracts this information and (attempts to) match it to a microarchitecture.

**Comment by pavanjoshi914** [comment]
I can see oxd41 part returned but not its mapping actually. thanks for pointing out to the file.  am i missing something?

here is the code
```
  val si = SystemInfo()
        val hal = si.hardware
        val cpu = hal.processor

        val modelTextView = view.findViewById<TextView>(R.id.modelTextView);


        modelTextView.text= cpu.processorIdentifier.toString();

```


here is the output:

![WhatsApp Image 2023-08-07 at 08 55 38](https://github.com/oshi/oshi/assets/55848322/214adda3-63d8-4fb4-8d4a-83aba1b1edd7)

**Comment by dbwiddis** [comment]
You've just output the identifier.  What does `getMicroarchitecture()` return?  The model `0xd41` should resolve Cortex-A78.   

If it doesn't, please let me know what you see for `getVendor()`.

**Comment by dbwiddis** [comment]
Actually, I think I see the issue. The `0x41` which leads that is the vendor.  

OSHI normally parses that with `lscpu` to match it up to the `Architecture` field there, but it seems not to have worked in your case.   It may be we just hardcode the `0x41` code to ARM.

**Comment by dbwiddis** [comment]
I've tried to fix this in #2427.  It's been pushed to SNAPSHOT, can you try to test the fix?

**Comment by dbwiddis** [comment]
is there any whitespace in the vendor string?  I can't see where that wouldn't look up the correct value in the new code.

**Comment by dbwiddis** [comment]
To help me debug, can you please provide the output of `cat /proc/cpuinfo` and (non-elevated) `lscpu` commands?

**Comment by pavanjoshi914** [comment]
sure here it is!

![WhatsApp Image 2023-08-09 at 11 06 17](https://github.com/oshi/oshi/assets/55848322/2cea4ec6-87e2-41fb-b6e2-bf8db9223179)
![WhatsApp Image 2023-08-09 at 11 06 18](https://github.com/oshi/oshi/assets/55848322/767ff13f-7ea8-4e4b-969b-88620a5dcc04)

**Comment by dbwiddis** [comment]
OK, this is interesting.

The `/proc/cpuinfo` is as expected, and the source of the 0x41.

The `lscpu` output has the info we need, but apparently we only parse `Architecture:` to try to get the vendor here which should result in `aarch64` at least... although that's not really the vendor.

The Vendor does show up in the "Vendor ID" field.

And the Model Name is even there... which is Cortex-A55.  But that doesn't match the model from your earlier screencap (0xd41 which is Cortex-A78.). In this output your CPU part is 0xd05 (which is Cortex-A55).  So it looks like you're collecting data on two different devices?

**Comment by pavanjoshi914** [comment]
i have 2x cortex-A78 and 6x cortex-A55 it's an 8 core device

**Comment by dbwiddis** [comment]
Oh, great, hybrid architecture.

I'll do my best to untangle this but it may take me a few days to find the time to dig into it. 

It's really hard without the full output of those commands, and the screencaps are helpful for debugging but not as much for seeing the whole picture and future-proofing.  I'll see if I can find some example outputs online as well.

**Comment by pavanjoshi914** [comment]
I will try and provide full output. need to see how to export the output in termux or something else

**Comment by dbwiddis** [comment]
I've pushed another snapshot with some improved parsing.
