### ISSUE TITLE
Could not initialize class LinuxOperatingSystem - Amazon Linux 2023 aarch64

### ISSUE THREAD

**Issue by gruntus** [oshi/oshi#2429]
Hello

I have been porting a Java 8 rest api to Amazon Linux 2023 aarch64 and was blocked by some code that uses sigar (CPU loading, Disk Store Mounts and Free Space). I decided to swap out sigar and use OSHI but unfortunately i'm getting the following issue:

Caused by: java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.SystemInfo.createOperatingSystem(SystemInfo.java:85) ~[oshi-core-6.4.4.jar:6.4.4]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.4.jar:6.4.4]
	at oshi.SystemInfo.getOperatingSystem(SystemInfo.java:76) ~[oshi-core-6.4.4.jar:6.4.4]

I have followed the doco on JNA versions and dependencies but have not been able to resolve....so here i am ;)

Thanks,
Grant.

**Comment by mprins** [comment]
please show us your dependency management or dependency listing, eg. using `mvn dependency:tree`

`oshi.software.os.linux.LinuxOperatingSystem` is part of the `oshi-core` module and should be available in the classloader

**Comment by dbwiddis** [comment]
The error points to a problem in initializing `LinuxOperatingSystem` in one of the static blocks, however:
 - the attempt to load `udev` already catches that exception
 - the only other library loaded is `c` which would indicate a failure to load the system library.

Docs indicate glibc is already included in Amazon Linux: https://docs.aws.amazon.com/linux/al2023/ug/core-glibc.html

Was there any more to the stack trace indicating exactly where in LinuxOperatingSystem the failure occurred?

**Comment by dbwiddis** [comment]
The other possibility is inability to find JNA's `Native` class which would point to a problem finding JNA at all.

**Comment by gruntus** [comment]
Problem found:

WARNING [http-nio-8080-exec-3] com.sun.jna.Native.loadNativeDispatchLibrary JNA Warning: IOException removing temporary files

java.io.IOException: JNA temporary directory '/opt/tomcat/temp' does not exist

Thanks for assistance and apologies for chewing up your time on this.

**Comment by dbwiddis** [comment]
Given #2430 we probably could do with another entry in the FAQ regarding checking JNA temporary file writing locations...
