### ISSUE TITLE
Hope to provide a method to obtain the mapping relationship between operating system threads and JVM threads.

### ISSUE THREAD

**Issue by tzfun** [oshi/oshi#2438]
I hope to get some information about the operating system thread through the JVM thread ID (tid), such as: native thread id (nid), thread start time, cpu time, etc.

Currently there doesn't seem to be a way to get.

**Comment by dbwiddis** [comment]
According to [this gist](https://gist.github.com/rednaxelafx/843622) we could probably fetch that. 

What's the value of this number and why is it not available in Java itself?

**Comment by dbwiddis** [comment]
Hey @tzfun looking for some follow-up on this.  I know there are two possible thread identifiers, a "userspace" thread ID and a lower-level "pthread".  Currently OSHI ignores the "pthread" option (except as a backup option when there's no other pid available).   

I'm happy to consider adding it, but would like to know how the information might be used to see if it might be useful.  Short-lived threads often no longer exist by the time you ask for information about them, so I am hoping for some clarity on how this information will actually be useful.

**Comment by tzfun** [comment]
@dbwiddis I'm glad to see your reply. In my application scenario, it is mainly used in the following aspects:
1. At the moment of query, obtain the startup time, CPU time, startup address, lock address, etc. of the JVM thread to monitor the health status of the thread. Some of this information requires correspondence between user threads and kernel threads to obtain.
2. At the moment of query, the JVM thread ID can be mapped to the tid file in the Linux system. This file contains more thread-related information.
3. Sort according to the CPU usage of kernel threads, and obtain the stack executed by each kernel thread in the JVM.

In fact, the significance of this requirement is to detect "unhealthy" threads that occupy the CPU or locks for a long time, and there is no need to care about fleeting threads.

**Comment by dbwiddis** [comment]
I'm still a bit confused.

Looking at [this gist](https://gist.github.com/rednaxelafx/843622)
1. There's the Java-level Thread ID, which is already available to you using `java.lang.Thread.getId()`.
2. There's the "Native Thread ID" which is what OSHI currently reports (or at least tries to) as the Thread ID in the OSThread objects.

So both elements are already available, is the issue that they are not connected to each other?

**Comment by tzfun** [comment]
Yes, all the information is available, but need a mapping.

I looked at the implementation in the link, it depends on the interface in some jar packages of hotspot, and this is not universal, there are two main problems:

1. If it is not a hotspot virtual machine, it will not be able to run this code unless all interfaces use reflection calls. In the case of non-hotspot virtual machines, what I hope to get is a readable message instead of an error.
2. Some jar packages that need to rely on JDK must be loaded at runtime or before packaging, which will bring a lot of redundant files.

**Comment by dbwiddis** [comment]
Hey @tzfun I have looked at this multiple times and really don't understand how to integrate this request beyond what's already available.  

We strive for compatibility across operating systems and JVMs and it appears this delves into the inner workings of which JVM is being used, which seems beyond the scope of this project.

I'm happy to consider a community contribution to provide this support, if you'd like to submit a PR.
