### ISSUE TITLE
On Mac listing connections excludes ones that listen on both IPv4 and IPv6

### ISSUE THREAD

**Issue by rieck0** [oshi/oshi#2441]
To observe this, start a python server locally which listens on port 8000 by default on both ipv4 and ipv6:

python3 -m http.server

Then list connections using getConnections() from InternetProtocolStats. IPConnection for port 8000 will be missing.

The issue is here https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/software/os/mac/MacInternetProtocolStats.java#L186 . 

ini.insi_vflag has a value of 3 for connections listening on both ipv4 and ipv6 so queryIPConnection() returns null.

**Comment by dbwiddis** [comment]
Thanks for the report!  Would you be able to submit a PR to fix it?

**Comment by rieck0** [comment]
I can do that. How do you prefer this is fixed? Treat this type of connection as IPv4 type "4" or IPv6 type "6", which would be a simple modification to the code. Treat this type of connection as IPv4 and IPv6 type "46" which is not a supported type by this library.

**Comment by dbwiddis** [comment]
> How do you prefer this is fixed? 

Type `netstat -a` in your terminal.  I'd like OSHI's output to faithfully represent the same thing.  

I'm assuming the connection shows up as two separate lines, one starting `tcp4` and one starting `tcp6`?  If so, that's what I'd like.  One possible solution is to modify that method to return a list and then add both connections to the list, and in the return use `addAll()`.  Or you could return a "46" and then parse it later.

Or if that connection only shows up as 4 or 6 in netstat, then perhaps that's the default we want as well.

**Comment by rieck0** [comment]
The connection shows up as one line probably because it's a single process.

tcp46      0      0  *.irdmi                *.*                    LISTEN

Do you still want two separate connections or one connection of type "tcp46"?

**Comment by dbwiddis** [comment]
If netstat says 'tcp46' then OSHI should too!  Which I guess makes this a rather simple fix... but one that requires having the hardware/software combo to test it!

**Comment by dbwiddis** [comment]
Fixed in #2443
