### ISSUE TITLE
Audit and fix locale- and encoding- specific conversions

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#2451]
Coming from https://github.com/oshi/oshi/pull/2446#discussion_r1315664949

 - [x] Search for uppercase / lowercase conversions and make sure they use `Locale.ROOT`.
 - [x] Search for String format and make sure it uses `Locale.ROOT`.
 - [x] Search for String instantiation (`new String(byte[])`) that does not specify an encoding.
 - [x] Add CI checking such as checkstyle, sonar, or forbidden APIs that automates these checks in the future

**Comment by Taz03** [comment]
assign me pls

**Comment by Taz03** [comment]
should i use `Locale.US` or `Locale.ROOT` because `ROOT` will end up using system default/location specific, and the motive of this pr is to make it independent, so...?

**Comment by mprins** [comment]
> ... will end up using system default/location specific ...

No you're wrong there. Read the API doc: https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#ROOT and use `Locale.ROOT` as the ticket says

**Comment by dbwiddis** [comment]
FYI, this is mostly relevant when parsing output of command lines, for which we use `LC_ALL=C` as the environment. The `ROOT` locale [corresponds to this](https://stackoverflow.com/questions/37804580/equivalent-of-c-c-setlocalelc-all-c-in-java).

**Comment by dbwiddis** [comment]
@Taz03 after merging #2464 and #2466 there are still 12 more locale issues to go after. Here's a handy checklist!
```
Error:  Forbidden method invocation: java.lang.String#toLowerCase() [Uses default locale]
Error:    in oshi.software.os.unix.openbsd.OpenBsdOperatingSystem (OpenBsdOperatingSystem.java:59)
Error:  Forbidden method invocation: java.lang.String#format(java.lang.String,java.lang.Object[]) [Uses default locale]
Error:    in oshi.util.EdidUtil (EdidUtil.java:38)
Error:  Forbidden method invocation: java.lang.String#format(java.lang.String,java.lang.Object[]) [Uses default locale]
Error:    in oshi.util.EdidUtil (EdidUtil.java:[75](https://github.com/oshi/oshi/actions/runs/6443847052/job/17496206786?pr=2467#step:6:76))
Error:  Forbidden method invocation: java.time.LocalDateTime#now() [Uses default time zone]
Error:    in oshi.driver.unix.Who (Who.java:108)
Error:  Forbidden method invocation: java.time.format.DateTimeFormatter#ofPattern(java.lang.String) [Uses default locale]
Error:    in oshi.driver.unix.Who (Who.java:38)
Error:  Forbidden method invocation: java.time.Year#now() [Uses default time zone]
Error:    in oshi.driver.unix.Who (Who.java:44)
Error:  Forbidden method invocation: java.lang.String#toLowerCase() [Uses default locale]
Error:    in oshi.software.os.unix.freebsd.FreeBsdOperatingSystem (FreeBsdOperatingSystem.java:64)
Error:  Forbidden method invocation: java.lang.String#toLowerCase() [Uses default locale]
Error:    in oshi.software.os.unix.freebsd.FreeBsdOSProcess (FreeBsdOSProcess.java:68)
Error:  Forbidden method invocation: java.time.format.DateTimeFormatter#ofPattern(java.lang.String) [Uses default locale]
Error:    in oshi.software.os.OSSession (OSSession.java:20)
Error:  Forbidden method invocation: java.time.format.DateTimeFormatter#ofPattern(java.lang.String) [Uses default locale]
Error:    in oshi.driver.unix.aix.Who (Who.java:26)
Error:  Forbidden method invocation: java.lang.String#toLowerCase() [Uses default locale]
Error:    in oshi.software.os.unix.openbsd.OpenBsdOSProcess (OpenBsdOSProcess.java:61)
Error:  Forbidden method invocation: java.lang.String#format(java.lang.String,java.lang.Object[]) [Uses default locale]
Error:    in oshi.hardware.common.AbstractUsbDevice (AbstractUsbDevice.java:94)
Error:  Scanned 568 class file(s) for forbidden API invocations (in 1.18s), 12 error(s).
```

**Comment by dbwiddis** [comment]
> java.time.LocalDateTime#now() [Uses default time zone]

For this, we intentionally want to know the system time zone for the operating system we're running `who` on, so use use `ZoneId.systemDefault()` and pass that as a ZoneId argument.
