### ISSUE TITLE
too many files open on Solaris os

### ISSUE THREAD

**Issue by worming004** [oshi/oshi#2453]
# The current result
On Solaris 11.4.52.132.2, we've seen a weblogic server opening a lot of files descriptors on /dev/kstat after installing https://github.com/microsoft/ApplicationInsights-Java version 3.4.16.

Regularly, maybe 1 time per hour, the java process open a new file descriptor with this look using _pfiles_
```
1618: S_IFCHR mode:0666 dev:16377,7 ino:592460283 uid:0 gid:3 rdev:131,0
      O_RDONLY|O_LARGEFILE FD_CLOEXEC
      /dev/kstat
      offset:0
```

After weeks of run, the weblogic ends with a "too many open files"

Maybe the problem come directly from ApplicationInsight

# The expected result
is to not get an accumulation of opened file descriptor

**Comment by dbwiddis** [comment]
See https://github.com/oshi/oshi/issues/2348 for a similar report.  This seems an underlying bug in kstat2 in the operating system.

See https://github.com/oshi/oshi/pull/2362 for a workaround using the older (deprecated) kstat.
