### ISSUE TITLE
getPowerSources() returning empty array on Android

### ISSUE THREAD

**Issue by mdffigueira** [oshi/oshi#2479]
I'm using Oshi on my Android project.I'm importing gradle oshi 6.4.0 excluding jna and jna-platform and importing jna@arr:

```
implementation 'net.java.dev.jna:jna:5.13.0@aar'

implementation('com.github.oshi:oshi-core:6.4.0')
          {
              exclude group: 'net.java.dev.jna', module: 'jna'
              exclude group: 'net.java.dev.jna', module: 'jna-platform'
          }
```
I was able to return the available memory, but the battery state is always returning an empty array. The project is being implemented on SDK API 24: Andoid 7.0 version, and I've tried on my fisical Samsung Galaxy S21  and emulated  a Pixel_3a.
Am I missing any detail?

**Comment by dbwiddis** [comment]
> excluding jna and jna-platform

You correctly exclude jna because you're pulling in the aar separately, but you still need jna-platform jar.

> Am I missing any detail?

Our Android "support" was really just using the Linux code branch for android OS.  It works for most things.

OSHI's support on Linux uses libudev and searches the "power_supply" subsystem.  

Other than the jna-platform dependency comment noted above,  that's about as much detail as I can offer, but hopefully it helps you debug.

**Comment by dbwiddis** [comment]
It looks like Android may not have udev but the values are available in sysfs.

Probably would be good to use that as a backup on OSHI when Udev isn't available:
https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-power

**Comment by dbwiddis** [comment]
And if you look at git history of that file, we used to get it via sysfs so should be easy to add.
https://github.com/oshi/oshi/pull/1859

**Comment by dbwiddis** [comment]
I've tried to fix this in #2480.  I've deployed that PR to snapshot.... any chance you can test it?

**Comment by mdffigueira** [comment]
> You correctly exclude jna because you're pulling in the aar separately, but you still need jna-platform jar.

 I've excluded jna-platform because there was a conflict when building.
```
Execution failed for task ':mobilesysteminfo:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'META-INF/AL2.0' from inputs:
      - C:\Users\MiguelFigueira\.gradle\caches\transforms-3\bb87616188c28df608d035078b0e1e77\transformed\jna-5.13.0\jars\classes.jar
      - C:\Users\MiguelFigueira\.gradle\caches\modules-2\files-2.1\net.java.dev.jna\jna-platform\5.12.1\97406a297c852f4a41e688a176ec675f72e8329\jna-platform-5.12.1.jar
     Adding a packagingOptions block may help, please refer to
     https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
     for more information

```
Now I further investigated what consisted adding packagingOptions block and by adding the following configs to build.gradle and I managed to solve the conflict:

```
packagingOptions {
        exclude 'META-INF/AL2.0'
        exclude 'META-INF/LGPL2.1'
    }
```
It's curious that  on other project to manage the laptop system I didn't have this problem on building.

**Comment by mdffigueira** [comment]
> I've tried to fix this in #2480. I've deployed that PR to snapshot.... any chance you can test it?

I'm importing the library directly from maven repository and I'm having difficulties to do the same from that branch. If Is not asking too much can you explain how I should test your fixes?

I'm sorry :/

**Comment by dbwiddis** [comment]
> I'm importing the library directly from maven repository and I'm having difficulties to do the same from that branch. If Is not asking too much can you explain how I should test your fixes?

You could just try to run SystemInfoTest from the command line on your devices directly using the instructions on the README.
```
git clone https://github.com/oshi/oshi.git && cd oshi

./mvnw test-compile -pl oshi-core exec:java \
  -Dexec.mainClass="oshi.SystemInfoTest" \
  -Dexec.classpathScope="test"
```

I did push the code to the maven snapshot repository which requires a bit of configuration to point your maven to that repo for snapshots.  See https://stackoverflow.com/a/7717234/1161484 and just use the 6.4.7-SNAPSHOT version.

There are other ways to use a local JAR file with maven but they are a bit more invasive.

**Comment by dbwiddis** [comment]
You're getting JNA 5.12.1 from some other source, actually.  Gradle dependencies can help you sort out where it's coming from.  

Normally you want jna-platform to match jna version. It might be ok to have a lower jna-platform minor version, but not vice versa.
