### ISSUE TITLE
Could not initialize class com.sun.jna.Native

### ISSUE THREAD

**Issue by yzhang921** [oshi/oshi#2506]
Can somebody help me out? 🙏 
I try to run oshi on aarch64 architecture cpu raise error like below:

<img width="1333" alt="image" src="https://github.com/oshi/oshi/assets/6037522/89e4f34d-a295-4c02-ac86-aefbf6330097">

```xml
<dependency>
    <groupId>com.github.oshi</groupId>
    <artifactId>oshi-core</artifactId>
    <version>6.2.1</version>
</dependency>
```

**Comment by mprins** [comment]
please try with a currently supported version and read the [FAQ](https://www.oshi.ooo/FAQ.html) and similar, already resolved issues: https://github.com/oshi/oshi/issues?q=is%3Aissue+is%3Aclosed+initialize+class+com.sun.jna.Native

You have provided insufficient information to let us help you.

**Comment by yzhang921** [comment]
I have tried to reseach issue history, no clue to help.
Now, this prgram run in a innernal network enviroment. 
What information do you need, I can try to collect when we can.

**Comment by dbwiddis** [comment]
There are [many possibilities](https://www.oshi.ooo/FAQ.html#how-do-i-resolve-jna-noclassdeffounderror-or-nosuchmethoderror-i) but all are associated with not having the correct JNA dependency imported, or not having the JNA native dll stub properly extracted on your system.

The top line of the stack trace indicates failure to instantiate the `NativeLong` class. The only way I can see that failing is if the value `Native.LONG_SIZE` can't be read; this is a native call directly to JNA's temporary DLL (`jnidispatch`).

The top suggestion under the FAQ is most likely to solve your problem:
> JNA needs to write its [native DLL](https://javadoc.io/static/net.java.dev.jna/jna/5.13.0/com/sun/jna/Native.html), usually to a temporary file unless you've configured otherwise. File system permissions or capacity may prevent this from happening. Pre-extracting the DLL and placing it in a known location resolves this.

Likely causes are:
 - the user running OSHi (and thus JNA) doesn't have permissions to extract the library to the tmpdir
 - the tmpdir location is read-only
 - the tmpdir location has no free space

The javadoc for `Native` linked from the FAQ describes the search process. if reading that `Native` class javadoc doesn't help, turn on debug logging and look for a more specific error message.  See also [this StackOverflow answer](https://stackoverflow.com/a/60873876/1161484).

**Comment by small-Teenager** [comment]
check your  jna and jna-platform version is it consistent.
