### ISSUE TITLE
linux Total disk count calculation error

### ISSUE THREAD

**Issue by zzx1314** [oshi/oshi#2539]
![image](https://github.com/oshi/oshi/assets/20176085/d51eac60-9996-4062-a9e1-c470d6d82f68)
[
	{
		"description": "Local Disk",
		"freeInodes": 388405409,
		"freeSpace": 3936022994944,
		"label": "",
		"logicalVolume": "/dev/dm-0",
		"mount": "/",
		"name": "/",
		"options": "rw,relatime,attr2,inode64,noquota",
		"totalInodes": 388762816,
		"totalSpace": 3978987552768,
		"type": "xfs",
		"uUID": "6fce0ca4-b666-4411-b81d-d7b4d2253ea1",
		"usableSpace": 3936022994944,
		"volume": "/dev/mapper/klas-root"
	},
	{
		"description": "Ram Disk",
		"freeInodes": 8069007,
		"freeSpace": 33051250688,
		"label": "tmpfs",
		"logicalVolume": "",
		"mount": "/tmp",
		"name": "tmpfs",
		"options": "rw,nosuid,nodev",
		"totalInodes": 8069740,
		"totalSpace": 33053655040,
		"type": "tmpfs",
		"uUID": "",
		"usableSpace": 33051250688,
		"volume": "tmpfs"
	},
	{
		"description": "Local Disk",
		"freeInodes": 255920,
		"freeSpace": 345280512,
		"label": "",
		"logicalVolume": "",
		"mount": "/boot",
		"name": "/dev/sda2",
		"options": "rw,relatime,attr2,inode64,noquota",
		"totalInodes": 256000,
		"totalSpace": 518684672,
		"type": "xfs",
		"uUID": "e46584b6-625f-491e-bcd0-2db7d8064b98",
		"usableSpace": 345280512,
		"volume": "/dev/sda2"
	},
	{
		"description": "Local Disk",
		"freeInodes": 0,
		"freeSpace": 2135298048,
		"label": "",
		"logicalVolume": "",
		"mount": "/boot/efi",
		"name": "/dev/sda1",
		"options": "rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=ascii,shortname=winnt,errors=remount-ro",
		"totalInodes": 0,
		"totalSpace": 2143281152,
		"type": "vfat",
		"uUID": "4343-1f0c",
		"usableSpace": 2135298048,
		"volume": "/dev/sda1"
	}
]
sum= 
3978987552768+33053655040+518684672+2143281152 = 4,014,703,173,632
I found that the query is slightly larger than the fdisk - l command

**Comment by dbwiddis** [comment]
The "larger" value includes the RAM disk `/tmp`.  In fact OSHI's disk sizes are slightly smaller than your output.

OSHI fetches the disk sizes from `udev` which should also match the device information at `/sys/block/<disk>/<partition>/size`.  These should also exactly match the output of `lsblk`.

`/dev/sda1` shows a partition size in OSHI of 2143281152 bytes = 4186096 512K blocks.
Your `fdisk -l` output shows sda1 at 4194304 blocks, slightly larger by 8208 blocks, 0.2%.

`/dev/sda2` shows a partition size in OSHI of 518684672 bytes = 1013056 512K blocks.
Your `fdisk -l` output shows sda2 at 1134000 blocks, slightly larger by 10944 blocks, 1.07%.

`/` shows a partition size in OSHI of 3978987552768 bytes = 7771460064 512K blocks.
Your `fdisk -l` output shows sda3 at 7808815103 blocks, slightly larger by 37355039 blocks, 0.48%.

Of note, `fdisk` is only calulating size based on the blocks at the start and end of the partitions and uses simple subtraction to count the total blocks/size.

I don't know why sysfs/udev/lsblk shows smaller values than fdisk, but those values are used practically everywhere in Linux for determining block device size, so I'd trust them more than the fdisk output.

**Comment by zzx1314** [comment]
Thank you for your reply. I think I understand now

**Comment by zzx1314** [comment]
![image](https://github.com/oshi/oshi/assets/20176085/155e14f1-ba23-475e-89e9-cbe0eae1e166)
I found that 'lsblk -b' and 'fdisk -l' the calculation results are the same .
But OSHI calculates more than both

**Comment by dbwiddis** [comment]
What does sysfs report?  Should be a file `/sys/block/sda/size` in 512K blocks (7814037168 in your output).

**Comment by dbwiddis** [comment]
Also what does udev say (this is where OSHI gets its value):
```
udevadm info -a -p  $(udevadm info -q path -n /dev/sda)
```

**Comment by dbwiddis** [comment]
> But OSHI calculates more than both

As indicated above, OSHI's values are lower than your `fdisk` output.  Also, OSHI does not "calculate" anything, it is just returning the exact values returned from `udev` (see command in previous comment).

There are a few differences in the output:
 - fdisk includes the swap partition `/dev/mapper/klas-swap` in its total, and in `sda3` total, OSHI does not list it
 - OSHI lists the `/tmp` Ram Drive that is not part of the `sda` disk

There are some size differences between all 3 data sources on the root partition (`udev` which OSHI uses < `lsblk` which uses sysfs values directly <`fdisk` which uses the disk partition table):

| Volume | udev size (bytes) | udev size (blocks) | lsblk size (bytes) | lsblk size (blocks) | fdisk blocks | 
| --- | --- | --- | --- | --- | --- | 
| /dev/mapper/klas-root | 3978987552768 | 7771460064 | 3980931366912 | 7775256576 | 7814037168 | 
| /dev/sda2 | 518684672 | 1013056 | 524288000 | 1024000 | 1024000 | 
| /dev/sda1 | 2143281152 | 4186096 | 2147483648 | 4194304 | 4194304 | 

From what I understand:
 - OSHI / udev is reporting the block device size as seen from userspace
 - lsblk is reporting the block device size as seen from the kernel
 - fdisk is reporting the partition size as seen from the disk hardware

**Comment by dbwiddis** [comment]
Digging a bit more, I see that `udev` gets its size from `ioctl` on the device:
```c
ioctl(fd, BLKGETSIZE64, &sz)
```
OSHI prefers to use this ioctl-based approach:
 - it is a native system call and is thus faster for performance reasons than parsing command-line output
 - ioctl directly queries the device to get the device's reported size.  It's as close to the hardware as we can get. 
 - `fdisk` size is calculated simply from the start and end block of a partition and does not account for any overhead/metadata/reserved space that may reduce the actual block size
 - `lsblk` and `sysfs` values (and `/proc/partitions`) take into account more factors than the raw device size
