### ISSUE TITLE
mac m1 disk usableSpace calculation error

### ISSUE THREAD

**Issue by XuQianJin-Stars** [oshi/oshi#2543]
Oshi
![image](https://github.com/oshi/oshi/assets/10494131/b99059b4-0707-4b00-91bc-3b0f07588a05)
df -lh
![image](https://github.com/oshi/oshi/assets/10494131/d578c92a-8ff9-474d-8670-8ecf0860a1b1)

**Comment by dbwiddis** [comment]
Numbers look correct to me in Gibibytes (GiB):
`/dev/disk3s3` Size 926Gi, Avail 581Gi.

|  | bytes | GB | GiB |
|---|---|---|---|
| total | 994662584320 | 994.6625843 | 926.3517189 |
| usable | 624054513664 | 624.0545137 | 581.1960564 |
