### ISSUE TITLE
Partition detection is not language independent

### ISSUE THREAD

**Issue by lundefugl** [oshi/oshi#255]
On a german Windows 10 system the partition detection don't work.

In `WindowsDisks.java#getDisks` you link the `deviceToPartitionMap` and the `partitionMap`.
The keys in `partitionMap` are not language independent. (see screenshot).

The result is a partion array with `null` values

![win10-partitions](https://cloud.githubusercontent.com/assets/1292880/18119879/1ed46390-6f5d-11e6-97c0-6f037778b59c.png)

**Comment by dbwiddis** [comment]
I'm not sure where this error starts. It looks like Windows returns English for one query and German for the other?

**Comment by dbwiddis** [comment]
The (German) keys in the `partitionMap` come from the `Name` field of the query to `Win32_DiskPartition`.  The (English) values in the `driveToPartitionMap` come from the `Dependent` field (regex parsing device ID) of the query to `Win32_DiskDriveToDiskPartition`.

Why is Windows producing results in multiple languages?  I'm not sure how to control for this.

Is there a matching English field (deviceID, perhaps) in the `Win32_DiskPartition` WMI query that I can switch to?

**Comment by lundefugl** [comment]
> Is there a matching English field (deviceID, perhaps) in the  Win32_DiskPartition  WMI query that I can switch to?

Yes the `DeviceID` is in english - that should work.

In the [MSDN](https://msdn.microsoft.com/en-us/library/aa394135(v=vs.85).aspx) the `Name` property is also called "DisplayName" And the `DeviceID` is called "Key", "Unique identifier", ...
I think it's the correct property.

**Comment by dbwiddis** [comment]
OK, I've switched both map keys to the `DeviceID`.  Check out the SNAPSHOT.

**Comment by lundefugl** [comment]
It works - Thank you.
