### ISSUE TITLE
aws ec2 linux  init error :java.lang.NoclassDefFoundError: Could not initialize class oshi.software,os,linux.LinuxoperatingSystem

### ISSUE THREAD

**Issue by 1ssqq1lxr** [oshi/oshi#2557]
JDK: 17

EC2: 

![dbe17799f1c3a0a8db92b11798561ec](https://github.com/oshi/oshi/assets/19258331/29360d8a-fe7e-4dd0-bdc0-6dd113ee31b0)

error:
![a621036753e1cc2fef56683663bc00a](https://github.com/oshi/oshi/assets/19258331/2dcb31f3-c5ea-48ac-a3b2-08b804dd0baa)

**Comment by 1ssqq1lxr** [comment]
how can i solve？

**Comment by dbwiddis** [comment]
Very likely the same cause as #2556 

JNA classes are failing to load, possibly failing to extract the native DLL.

See the FAQ:
https://github.com/oshi/oshi/blob/master/src/site/markdown/FAQ.md#how-do-i-resolve-jna-noclassdeffounderror-or-nosuchmethoderror-issues

**Comment by 1ssqq1lxr** [comment]
> Very likely the same cause as #2556
> 
> JNA classes are failing to load, possibly failing to extract the native DLL.
> 
> See the FAQ: https://github.com/oshi/oshi/blob/master/src/site/markdown/FAQ.md#how-do-i-resolve-jna-noclassdeffounderror-or-nosuchmethoderror-issues

`   <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>5.14.0</version>
        </dependency>
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna-platform</artifactId>
            <version>5.14.0</version>
        </dependency>
       <dependency>
                <groupId>com.github.oshi</groupId>
                <artifactId>oshi-core</artifactId>
                <version>6.4.10</version>
          </dependency>
`
I have configured maven dependencies, but I still get an error at startup.

**Comment by dbwiddis** [comment]
The occurrence of the exception in initializing the `LinuxOperatingSystem` class indicates that the problem must be in the static initializers.

https://github.com/oshi/oshi/blob/eeabe8f4259a2b928d3511ddd157c4bcdec80598/oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java#L70-L120

The `Udev` class used to be a common problem and has been wrapped, so the only way this exception is occurring is a failure to load the JNA `LinuxLibC` class.

You've indicated in your POM that you have the correct JNA version, so the only logical explanation is that JNA itself is failing to load its native library, the first bullet in the FAQ entry quoted above.

The screencap above shows you using OSHI as a dependency of some other project.   To rule out anything with that project, please try to run OSHI directly by forking/cloning directly:
```bash
git clone https://github.com/oshi/oshi.git && cd oshi

./mvnw test-compile -pl oshi-core exec:java \
  -Dexec.mainClass="oshi.SystemInfoTest" \
  -Dexec.classpathScope="test"
```
If this succeeds, the problem is in whatever program that's including OSHI.

If this fails, the problem is likely JNA's failure to extract its native DLL due to one of many problems:
 - file system permissions
 - file system disk space
 - improperly configured paths

**Comment by dbwiddis** [comment]
Tested on my own ec2 instance:
```
% cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2:-:internal"
HOME_URL="https://amazonlinux.com/"
VARIANT="internal"
```

```
% git clone https://github.com/oshi/oshi.git && cd oshi

./mvnw test-compile -pl oshi-core exec:java \
  -Dexec.mainClass="oshi.SystemInfoTest" \
  -Dexec.classpathScope="test"
Cloning into 'oshi'...
remote: Enumerating objects: 613010, done.
remote: Counting objects: 100% (75614/75614), done.
remote: Compressing objects: 100% (8234/8234), done.
remote: Total 613010 (delta 67087), reused 75302 (delta 66814), pack-reused 537396
Receiving objects: 100% (613010/613010), 304.49 MiB | 42.63 MiB/s, done.
Resolving deltas: 100% (538742/538742), done.

<snip>

2024-01-08 08:01:30.571 [INFO] SystemInfoTest - Initializing System...
2024-01-08 08:01:30.635 [INFO] SystemInfoTest - Checking computer system...
2024-01-08 08:01:30.665 [INFO] SystemInfoTest - Checking Processor...
2024-01-08 08:01:30.684 [INFO] SystemInfoTest - Checking Memory...
2024-01-08 08:01:30.687 [INFO] SystemInfoTest - Checking CPU...
2024-01-08 08:01:31.710 [INFO] SystemInfoTest - Checking Processes...
2024-01-08 08:01:31.746 [INFO] SystemInfoTest - Checking Services...
2024-01-08 08:01:31.918 [INFO] SystemInfoTest - Checking Sensors...
2024-01-08 08:01:31.921 [INFO] SystemInfoTest - Checking Power sources...
2024-01-08 08:01:31.922 [INFO] SystemInfoTest - Checking Disks...
2024-01-08 08:01:31.925 [INFO] SystemInfoTest - Checking Logical Volume Groups ...
2024-01-08 08:01:31.944 [INFO] SystemInfoTest - Checking File System...
2024-01-08 08:01:31.950 [INFO] SystemInfoTest - Checking Network interfaces...
2024-01-08 08:01:31.953 [INFO] SystemInfoTest - Checking Network parameters...
2024-01-08 08:01:31.958 [INFO] SystemInfoTest - Checking IP statistics...
2024-01-08 08:01:31.966 [INFO] SystemInfoTest - Checking Displays...
2024-01-08 08:01:31.970 [INFO] SystemInfoTest - Checking USB Devices...
2024-01-08 08:01:31.971 [INFO] SystemInfoTest - Checking Sound Cards...
2024-01-08 08:01:31.971 [WARN] LinuxSoundCard - No Audio Cards Found
2024-01-08 08:01:31.971 [INFO] SystemInfoTest - Checking Graphics Cards...
2024-01-08 08:01:31.974 [INFO] SystemInfoTest - Printing Operating System and Hardware Info:
GNU/Linux Amazon Linux 2 (Karoo) build 5.4.261-181.360.amzn2int.x86_64
Booted: 2023-12-05T18:21:20Z
Uptime: 33 days, 13:40:09
Running without elevated permissions.
Sessions:
 LOGIN, ttyS0, 2023-12-05 18:26
 LOGIN, tty1, 2023-12-05 18:26
 redacted, pts/0, 2024-01-08 07:59, (111.222.33.44)
System: manufacturer=Amazon EC2, model=c5.2xlarge, serial number=unknown, uuid=unknown
 Firmware: manufacturer=unknown, name=unknown, description=dmi:bvnAmazonEC2:bvr1.0:bd10/16/2017:svnAmazonEC2:pnc5.2xlarge:pvr:rvnAmazonEC2:rn:rvr:cvnAmazonEC2:ct1:cvr:, version=1.0, release date=2017-10-16
 Baseboard: manufacturer=Amazon EC2, model=unknown, version=unknown, serial number=unknown
Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
 1 physical CPU package(s)
 4 physical CPU core(s)
 8 logical CPU(s)
Identifier: Intel64 Family 6 Model 85 Stepping 7
ProcessorID: 1F8BFBFF00050657
Microarchitecture: Cascade Lake
 Topology:
  LogProc  P/E Proc  Pkg NUMA PGrp
      0,4    P    0    0    0    0
      1,5    P    1    0    0    0
      2,6    P    2    0    0    0
      3,7    P    3    0    0    0
```
