### ISSUE TITLE
How to obtain server specified port traffic

### ISSUE THREAD

**Issue by miniso520** [oshi/oshi#2566]
oshi is a great toolkit, but I have a problem now, which is to get the traffic usage of a specified port, including upstream and downstream traffic. I saw the networkIF.getPort() method before, but this method is no longer available. I am currently using version 6.4.0.

**Comment by mprins** [comment]
As these are protocol properties and not hardware they should be exposed through `InternetProtocolStats`

**Comment by dbwiddis** [comment]
That information isn't directly available in any operating system AFAIK, without installing extra monitoring tools.

As @mprins said, the InternetProtocolStats class can get you all the active connections which will include a port and owning process ID, and overall protocol stats for all ports.  

You can go to the OSProcess with that owning process Id process and get network traffic which may include that port and possibly other ports, but only while the process is still active; once the process shuts down that information is no longer available.

With these tools you can reasonably identify real-time high bandwidth processes/ports, but collecting long-term stats just isn't available.

**Comment by miniso520** [comment]
> That information isn't directly available in any operating system AFAIK, without installing extra monitoring tools.
> 
> As @mprins said, the InternetProtocolStats class can get you all the active connections which will include a port and owning process ID, and overall protocol stats for all ports.
> 
> You can go to the OSProcess with that owning process Id process and get network traffic which may include that port and possibly other ports, but only while the process is still active; once the process shuts down that information is no longer available.
> 
> With these tools you can reasonably identify real-time high bandwidth processes/ports, but collecting long-term stats just isn't available.

Thank you very much for your reply. The solution I am using now is to monitor the port traffic through the iptables command, and then calculate it by intercepting the results of the command. But there is a problem with this. If iptables loses the specified port, all the data will be lost. . So I want to see if there is such an API that can be called directly.
