### ISSUE TITLE
arm linux cannot  get cpuName, use processorIdentifer

### ISSUE THREAD

**Issue by 13276965576** [oshi/oshi#2574]
use arthas get cpuName is empty.
os info:ubuntu 20.04.5 LTS (Focal Fossa) build 5.15.0-1022-aws
oshi version :6.4.11

[arthas@1317369]$ ognl -c  31cefde0 '@com.yeastar.cloud.dm.cluster.common.helper.OshiHelper@getHardwareLayer().getProcessor().getProcessorIdentifier()'
@ProcessorIdentifier[
    OSHI_ARCHITECTURE_PROPERTIES=@String[oshi.architecture.properties],
    cpuVendor=@String[ARM],
    cpuName=@String[],
    cpuFamily=@String[8],
    cpuModel=@String[0xd0c],
    cpuStepping=@String[r3p1],
    processorID=@String[C1 D0 3F 41 00 00 00 00],
    cpuIdentifier=@String[ARM Family 8 Model 0xd0c Stepping r3p1],
    cpu64bit=@Boolean[false],
    cpuVendorFreq=@Long[2500000000],
    microArchictecture=@[oshi.util.Memoizer$1@770cb057],
]

**Comment by 13276965576** [comment]
the /proc/cpuinfo info not found model name，
root@b-1:~# cat /proc/cpuinfo | grep "model name" | uniq
root@b-1:~# cat /proc/cpuinfo 
processor	: 0
BogoMIPS	: 243.75
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x3
CPU part	: 0xd0c
CPU revision	: 1

processor	: 1
BogoMIPS	: 243.75
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x3
CPU part	: 0xd0c
CPU revision	: 1

processor	: 2
BogoMIPS	: 243.75
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x3
CPU part	: 0xd0c
CPU revision	: 1

processor	: 3
BogoMIPS	: 243.75
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x3
CPU part	: 0xd0c
CPU revision	: 1

processor	: 4
BogoMIPS	: 243.75
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x3
CPU part	: 0xd0c
CPU revision	: 1

processor	: 5
BogoMIPS	: 243.75
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x3
CPU part	: 0xd0c
CPU revision	: 1

processor	: 6
BogoMIPS	: 243.75
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x3
CPU part	: 0xd0c
CPU revision	: 1

processor	: 7
BogoMIPS	: 243.75
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x3
CPU part	: 0xd0c
CPU revision	: 1
but use lscpu shell，
root@b-1:~# lscpu | grep "Model name"
Model name:                      Neoverse-N1

**Comment by mprins** [comment]
Neoverse n1 was added with id  0xd0c in https://github.com/oshi/oshi/pull/1844

See https://github.com/oshi/oshi/issues/1843#issuecomment-1009473338 and https://github.com/oshi/oshi/issues/2163#issuecomment-1215225783

**Comment by 13276965576** [comment]
i cannot found this file /proc/device-tree/model in server.
root@b-1:~# cat /proc/device-tree/model
cat: /proc/device-tree/model: No such file or directory

**Comment by dbwiddis** [comment]
> root@b-1:~# lscpu | grep "Model name"
> Model name: Neoverse-N1

Note you're running as root.   Are you running OSHI as root?

Linux requires root/sudo for lots of important CPU information.  If you know of any non-root way to get CPU name on your system, let me know.

**Comment by 13276965576** [comment]
yep , run my application by root account.
root@b-1:/usr/local/cluster_java# ps -ef | grep dm
root     3156217       1 13 07:42 pts/0    00:00:33 /usr/local/java/bin/java -agentlib:ByteCodeEncryptor -Xms350m -Xmx350m -XX:+HeapDumpOnOutOfMemoryError -jar /usr/local/cluster_java/dm-cluster.jar --server.port=9008

in server. execute lscpu can get cpu model.
root@b-1:/usr/local/cluster_java# lscpu
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              1
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       ARM
Model:                           1
Model name:                      Neoverse-N1
Stepping:                        r3p1
BogoMIPS:                        243.75
L1d cache:                       512 KiB
L1i cache:                       512 KiB
L2 cache:                        8 MiB
L3 cache:                        32 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; CSV2, BHB
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs

and cannot found /proc/device-tree/model file.

**Comment by dbwiddis** [comment]
OK, thanks for the clarification.

I see OSHI uses `/proc/cpu` as primary and then `/proc/device-tree/model` as a backup for the name.  Since neither exist, that's empty.   

However, the information is there in the cpuModel field to parse the architecture.  `cpuModel=@string[0xd0c],` which should match `arm.0xd0c=Neoverse-N1` in the "Architecture" field (`getProcessorIdentifier().getMicroarchitecture()`).

So the information is available to you; if you'd like to submit a PR to include that as another backup for the model name, it'd be welcome.

It'd also be welcome if ARM followed the same `/proc/cpu` format that Intel does. 😏

**Comment by 13276965576** [comment]
thk，i will submit a PR to hanlder this information.
