### ISSUE TITLE
Got wrong disk stats with redhat 8.5 operating system

### ISSUE THREAD

**Issue by cl728** [oshi/oshi#2580]
operating system: redhat 8.5
oshi version: 6.4.4

Execute the command `cat/proc/diskstats` on the machine，I got the output:
```shell
[root@r85 opt]# cat /proc/diskstats 
   8       0 sda 32328 22 1962654 8212 232293 218027 8828248 79622 0 70686 87835 0 0 0 0
```

In the output above, the number after the device name 'sda' represents disk statistics information. For example, the 0th digit 32328 represents the number of disk reads, the 2nd digit 1962654 represents the number of bytes read from the disk, and so on.

But when I used OSHI to obtain disk statistics information, I found that the data I obtained was incorrect, and the parsed data was shifted one bit to the right. For example, the first digit 22 is considered as READS, the second digit 8212 is considered as READ_BYTES, and so on.

I noticed it's `oshi.util.ParseUtil#parseStringToLongArray(String, int[], int, char)` method encountered an error while parsing disk statistics. This method assumes that the last digit of the parsed string is a number, but I found through debugging that the last digit of the passed in string is a space.

**Comment by dbwiddis** [comment]
Hmm.   

I just searched and found the [`DiskStats`](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/driver/linux/proc/DiskStats.java) class that's supposed to handle this and I don't see that parsing method used.  But it looks like it's not called! 👀 

In `LinuxHWDiskStore` we parse the Udev `stat` system attribute.

Possible fixes:
 - `trim()` the value fetched from `device.getSysAttrValue(STAT)` (2 instances)
 - `trim()` the value internally in `parseStringToLongArray`

And somewhere do a sanity check and use the `DiskStats` class as a backup :| 

Can you submit a PR to fix this?

**Comment by dbwiddis** [comment]
There's also a `countStringToLongArray` that needs the same fix.

**Comment by cl728** [comment]
I found another bug in method `parseStringToLongArray` and `countStringToLongArray`.

```java
public static long[] parseStringToLongArray(String s, int[] indices, int length, char delimiter) {
    // ...
   
    int charIndex = s.length();
    // ...

    while (--charIndex > 0 && parsedIndex >= 0) { 
        // ...
    }

}
```

When the value of `charIndex` is 1, the value of `--charIndex` will be 0, and it can't enter the while loop.
This will result in the first character of the parsed string being ignored for processing.

fixes:
- `trim()` the value internally in `parseStringToLongArray` and `countStringToLongArray`
- use `charIndex-- > 0` instead of `--charIndex > 0` in `parseStringToLongArray` and `countStringToLongArray`

PR: 
https://github.com/oshi/oshi/pull/2588
