### ISSUE TITLE
FlyCI not interacting well with cache action

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#2586]
Coming from https://github.com/oshi/oshi/issues/2585#issuecomment-1962595225

FlyCI actions are taking ~20s longer end-to-end than GitHub actions on M1.

While the actual tests run much faster, the FlyCI run takes about a minute longer before starting tests due to the need to re-download from Maven every time.  It does not seem to be able to make use of the cache from the other runs. 

The cache appears to be restored correctly, but the FlyCI maven run doesn't see the files.

Note the cache was written by a github runner on a previous run using the pom.xml hash as the key.  The repository looks to be the same: `/Users/runner/.m2/repository`.

Compare these two runs, both fetching the `.m2` directory from a previous run.

GitHub M1 runner:

<img width="1158" alt="Screenshot 2024-02-24 at 12 48 33 PM" src="https://github.com/oshi/oshi/assets/9291703/71a69444-46ce-4c12-af30-9ef4b8aa458a">

FlyCI runner:

<img width="1174" alt="Screenshot 2024-02-24 at 12 49 12 PM" src="https://github.com/oshi/oshi/assets/9291703/21a57d9c-632f-4405-b1b8-90b096466a81">

Example dependency:

GitHub M1 runner:

```
[INFO] --- jacoco:0.8.11:prepare-agent (pre-unit-test) @ oshi-parent ---
[INFO] jacoco.java.option set to -javaagent:/Users/runner/.m2/repository/org/jacoco/org.jacoco.agent/0.8.11/org.jacoco.agent-0.8.11-runtime.jar=destfile=/Users/runner/work/oshi/oshi/target/jacoco.exec,excludes=**/driver/**:**/common/**:**/Abstract*:**/annotation/**:**/jna/**:**/platform/**:**/linux/**:**/mac/**:**/windows/**:**/unix/**:**/demo/**
```

FlyCI runner:

```
[INFO] --- jacoco:0.8.11:prepare-agent (pre-unit-test) @ oshi-parent ---
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.24/plexus-utils-3.0.24.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.24/plexus-utils-3.0.24.pom (4.1 kB at 13 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus/4.0/plexus-4.0.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus/4.0/plexus-4.0.pom (22 kB at 90 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/sonatype/forge/forge-parent/10/forge-parent-10.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/sonatype/forge/forge-parent/10/forge-parent-10.pom (14 kB at 54 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.pom (2.4 kB at 9.5 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-components/15/maven-shared-components-15.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-components/15/maven-shared-components-15.pom (9.3 kB at 40 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/16/maven-parent-16.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/16/maven-parent-16.pom (23 kB at 90 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/apache/7/apache-7.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/apache/7/apache-7.pom (14 kB at 56 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.pom (1.4 kB at 5.9 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/doxia/doxia/1.0/doxia-1.0.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/doxia/doxia/1.0/doxia-1.0.pom (9.6 kB at 30 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/10/maven-parent-10.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/10/maven-parent-10.pom (32 kB at 121 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/apache/4/apache-4.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/apache/4/apache-4.pom (4.5 kB at 15 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.agent/0.8.11/org.jacoco.agent-0.8.11.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.agent/0.8.11/org.jacoco.agent-0.8.11.pom (3.5 kB at 13 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.core/0.8.11/org.jacoco.core-0.8.11.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.core/0.8.11/org.jacoco.core-0.8.11.pom (2.1 kB at 8.4 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm/9.6/asm-9.6.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm/9.6/asm-9.6.pom (2.4 kB at 395 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.pom (2.8 kB at 465 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.pom (2.6 kB at 432 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.report/0.8.11/org.jacoco.report-0.8.11.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.report/0.8.11/org.jacoco.report-0.8.11.pom (1.9 kB at 7.8 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.24/plexus-utils-3.0.24.jar
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.24/plexus-utils-3.0.24.jar (247 kB at 1.1 MB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.jar
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.agent/0.8.11/org.jacoco.agent-0.8.11-runtime.jar
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.core/0.8.11/org.jacoco.core-0.8.11.jar
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm/9.6/asm-9.6.jar
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm/9.6/asm-9.6.jar (124 kB at 14 MB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar (72 kB at 4.8 MB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar (52 kB at 2.5 MB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.report/0.8.11/org.jacoco.report-0.8.11.jar
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.jar (10 kB at 43 kB/s)
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.core/0.8.11/org.jacoco.core-0.8.11.jar (210 kB at 850 kB/s)
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar (11 kB at 43 kB/s)
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.agent/0.8.11/org.jacoco.agent-0.8.11-runtime.jar ([301](https://github.com/oshi/oshi/actions/runs/8030710570/job/21938319911#step:5:302) kB at 1.1 MB/s)
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.report/0.8.11/org.jacoco.report-0.8.11.jar (131 kB at 472 kB/s)
[INFO] jacoco.java.option set to -javaagent:/Users/runner/.m2/repository/org/jacoco/org.jacoco.agent/0.8.11/org.jacoco.agent-0.8.11-runtime.jar=destfile=/opt/actions-runner/_work/oshi/oshi/target/jacoco.exec,excludes=**/driver/**:**/common/**:**/Abstract*:**/annotation/**:**/jna/**:**/platform/**:**/linux/**:**/mac/**:**/windows/**:**/unix/**:**/demo/**
```

@radeva @kgantchev any insight here?  Is FlyCI compatible with the [GitHub cache action](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows)?

**Comment by kgantchev** [comment]
@dbwiddis thanks for reaching out. We currently don't have caching. That's something we're working on and we hope we'll have that up and running in the very near future.

**Comment by dbwiddis** [comment]
Great, good to know it's not my config problem.

Interestingly, I tried running maven with the `-X` switch to try to debug why it doesn't find the `.m2` directory, and it seemed to find it just fine in debug mode: https://github.com/dbwiddis/oshi/actions/runs/8033860668

In any case, I'll close this issue since I know you're working on it!

**Comment by kgantchev** [comment]
@dbwiddis I'll still get our team to take a look. Hopefully, they'll also provide additional feedback sometime by Monday.

I really appreciate the fact that you're reaching out. We're always looking for feedback and things to improve.

**Comment by dbwiddis** [comment]
> I have investigated further the issue you have described.

Awesome to hear!  It's not a big deal for us but I hope you're able to improve your product!

> It kind of relies on the fact that artifacts are relative to the user's home directory.
> 
> If you looked at the [Debug runs](https://github.com/oshi/oshi/actions/runs/8033692680/job/21944512921) you have executed here is the cache restore paths for FlyCI:
> 
> ```
> /opt/homebrew/bin/gtar -tf /opt/actions-runner/_work/_temp/ff5a67b5-f3e0-402d-8337-92a45b078357/cache.tzst -P --delay-directory-restore --use-compress-program unzstd
> ../../../.m2/repository/
> ../../../.m2/repository/commons-codec/
> ```

Ah! I had thought it was likely a path thing but hadn't gotten that far yet. 

This means a potential workaround using the `actions/cache` setup would have been to specify the `/opt/actions-runner` path rather than `~`, and keep a separate cache for that action as for the other GHA's.   

While investigating this, I did discover the `setup-java` action has an out-of-the-box solution [hardcoding the `~/.m2` directory](https://github.com/actions/setup-java/blob/7a445ee88d4e23b52c33fdc7601e40278616c7f8/src/cache.ts#L23-L64), however, which is reasonable as that's the Maven default. (And similar for gradle and SBT.)

> We will see how we can handle this case where a cache artifact is reused between GitHub and FlyCI runners.

It seems more important that the artifact is in a consistent place in the operating system, e.g., the `.m2` directory is expected to be in a User's home directory, and the logs show that's where the new artifacts are being written.  In the case where I'm only running the FlyCI runner(s), would it even be saving the `~/.m2` cache to restore it?

**Comment by ligaz** [comment]
Thanks @dbwiddis, this definitely help us improve our product. We have started the process of preparing a new images that will have the "correct" path for the runner (under's user's home directory). We will keep you posted once those images hit production.

**Comment by ligaz** [comment]
Hey @dbwiddis, we just released a new version of our macOS image that has this fix in-place. Can you please re-run your workflow check it on your side (I tested it in my fork and it now correctly restores the maven cache directory)?

**Comment by kgantchev** [comment]
Hi @dbwiddis we would love to get a brief "testimonial" so we can add it to [our case studies section](https://www.flyci.net/case-studies?utm_source=github&utm_medium=community&utm_campaign=recommend). Would you mind sharing your experience with FlyCI so far?

**Comment by dbwiddis** [comment]
Feel free to contact me via email. My email is in my profile.

**Comment by dbwiddis** [comment]
>  Would you mind sharing your experience with FlyCI so far?

As a cross-platform, cross-architecture project, it's important for OSHI to test its code on as many different combinations of operating system and architecture as possible.  Until recently, GitHub did not have runners for Apple Silicon, so it was great to see FlyCI offering an M1 runner with a generous free monthly allowance for open source projects.  Installing it took only a few minutes with a single line of code and a few mouse clicks.

When GitHub made their own runners available it was good to get a side-by-side comparison of the two. Initially FlyCI appeared to be slower, but after reporting it to them they quickly found an incorrect caching configuration and updated their runners within the day.  Other project's claims that they are twice as fast appear consistent with the results I'm seeing.

**Comment by radeva** [comment]
Thanks for all the great feedback @dbwiddis ! The case study about OSHI and FlyCI is now live. You can check it out [here](https://www.flyci.net/case-studies/oshi-leverages-flyci).
