### ISSUE TITLE
Add SMBIOSMemoryType values

### ISSUE THREAD

**Issue by caomeinaitang** [oshi/oshi#2606]
oshi 的源代码如下
 /**
     * Convert memory type number to a human readable string
     *
     * @param type The memory type
     * @return A string describing the type
     */
    private static String memoryType(int type) {
        switch (type) {
        case 1:
            return "Other";
        case 2:
            return "DRAM";
        case 3:
            return "Synchronous DRAM";
        case 4:
            return "Cache DRAM";
        case 5:
            return "EDO";
        case 6:
            return "EDRAM";
        case 7:
            return "VRAM";
        case 8:
            return "SRAM";
        case 9:
            return "RAM";
        case 10:
            return "ROM";
        case 11:
            return "Flash";
        case 12:
            return "EEPROM";
        case 13:
            return "FEPROM";
        case 14:
            return "EPROM";
        case 15:
            return "CDRAM";
        case 16:
            return "3DRAM";
        case 17:
            return "SDRAM";
        case 18:
            return "SGRAM";
        case 19:
            return "RDRAM";
        case 20:
            return "DDR";
        case 21:
            return "DDR2";
        case 22:
            return "DDR2-FB-DIMM";
        case 24:
            return "DDR3";
        case 25:
            return "FBD2";
        default:
            return "Unknown";
        }
    }
    新一代SMBIOSR如下
def convert_smbios_type_to_string(type):
    types = {
        1: "Other",
        2: "Unknown",
        3: "DRAM",
        4: "EDRAM",
        5: "VRAM",
        6: "SRAM",
        7: "RAM",
        8: "ROM",
        9: "Flash",
        10: "EEPROM",
        11: "FEPROM",
        12: "EPROM",
        13: "CDRAM",
        14: "3DRAM",
        15: "SDRAM",
        16: "SGRAM",
        17: "RDRAM",
        18: "DDR",
        19: "DDR2",
        20: "DDR2 FB-DIMM",
        21: "Reserved (DDR3)",
        22: "DDR4",
        23: "LPDDR",
        24: "LPDDR2",
        25: "LPDDR3",
        26: "LPDDR4",
        27: "Logical non-volatile device",
        28: "HBM (High Bandwidth Memory)",
        29: "HBM2 (High Bandwidth Memory 2)",
        30: "DDR5",
        31: "LPDDR5",
        32: "DDR3",
        33: "Hybrid Memory Cube (HMC)",
        34: "HBM3",
        35: "HBM4"
    }

    return types.get(type, "Unknown")

# Example usage
smbios_type = 34
type_string = convert_smbios_type_to_string(smbios_type)
print(type_string)  # Output: HBM3 我未必正确，但是这个确实算上是一个漏洞

**Comment by dbwiddis** [comment]
There are two separate fields in [Win32_PhysicalMemory](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-physicalmemory) WMI table.

OSHI's `memoryType()` method matches the `MemoryType` field.  There's a separate SMBIOSMemoryType field with the values in `smBiosMemoryType()`.

While there may be more types in actual SMBIOS indicated by your compiled C code, they aren't documented at that WMI link above.  But feel free to submit a PR to add them.

**Comment by dbwiddis** [comment]
I have updated the types in #2627 based on the specification here: https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.7.0.pdf (table 77) 

I also verified they aren't changed in the Work In Progress update: https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.8.0WIP50.pdf

The values from DSP0134 do not match the examples you gave above, including Hybrid Memory Cube (HMC) and HBM4. Do you have a source for those?
