### ISSUE TITLE
Configurable /dev and /sys locations

### ISSUE THREAD

**Issue by boemska-aleksandar** [oshi/oshi#2609]
First of all, big thanks for this wonderful project.

We would like to use oshi inside k8s where oshi would collect information in a similar fashion Prometheus node exported does.
For this, we would like to have /dev and /sys locations configurable in the properties file, the same way the /proc location is configurable now.

I also took the inspiration from Golang metrics collection projets like [gopsutil](https://github.com/shirou/gopsutil). Maybe at the same run we could add similar support for configuring alternate locations for /etc, /var, /run, but I'm not sure how much those are used by oshi.

**Comment by dbwiddis** [comment]
> we would like to have /dev and /sys locations configurable in the properties file

Sounds like a great addition!  Feel free to contribute a PR!

> Maybe at the same run we could add similar support for configuring alternate locations for /etc, /var, /run, but I'm not sure how much those are used by oshi.

I know we use [`/etc`](https://github.com/search?q=repo%3Aoshi%2Foshi%20%22%2Fetc%22&type=code) a few places.  We use [`/var`](https://github.com/search?q=repo%3Aoshi%2Foshi%20%22%2Fvar%22&type=code) and [`/var/run`](https://github.com/search?q=repo%3Aoshi%2Foshi%20%22%2Frun%22&type=code) exclusively when looking for the `dmesg.boot` file, so it seems a "path to dmesg" might be a more useful configuration?
