### ISSUE TITLE
Get I/Os per second of each process

### ISSUE THREAD

**Issue by chuck1991** [oshi/oshi#261]
Hi, thanks for sharing this useful project.  

Could I ask if oshi supports to get disk I/Os per second of each process? I tried a little bit but I failed to get it.

Thanks for your reply.

**Comment by dbwiddis** [comment]
No, OSHI doesn't currently track IOPS.  

While the information is available on Windows via WMI (Read/Write Operation/Transfer count on the Win32_Process query we already make), it is not easily available on other operating systems.

Linux has a proc/<pid>/io file with the info, but it requires root/sudo.  Programs like `iotop` and `pidstat` aren't installed by default.

OS X tools like `iotop` and `dtrace` require root, and typically incur a lot of latency as well. 

If someone wants to look into adding this functionality, I'll fully support it, but for me it's a "juice not worth the squeeze" bit of information.

**Comment by dbwiddis** [comment]
Looks like #262 is addressing this for OS X (10.9+) and I can add windows and Linux (requiring sudo).  Haven't looked at the Unices yet.

**Comment by dbwiddis** [comment]
per process IO is tracked for some OS's cumulatively in #262 (some entries require sudo.)  Successive reads with timestamps can determine per-second values.  Closing this as complete as much as it ever will be!
