### ISSUE TITLE
The service “tomcatSrv” unexpectedly stopped

### ISSUE THREAD

**Issue by lcfliuxi** [oshi/oshi#2636]
system: win10
api version: 6.4.7
jdk: 1.8

When I use the OSHI API to get CPU information, the service immediately stops when the code executes HardwareAbstractionLayer hardware = systemInfo.getHardware();
(ps: This issue currently occurs only on one machine.)
![image](https://github.com/oshi/oshi/assets/34911091/1ccc6923-53ce-4105-a328-f3f14368363e)

**Comment by dbwiddis** [comment]
There's really not much information here to go on.

Are there any logs with a stack trace or error messages in them?

Have you tried a newer version?  Have you tried older versions to identify which version introduced this issue?

**Comment by lcfliuxi** [comment]
Thank you for your answer.
1.There is not catch any exceptions, it's just stop the service as i said, and no any logs, so it's bothers me.
2.At present i have't try any other versions, i will try it latter.

**Comment by lcfliuxi** [comment]
> Thank you for your answer. 1.There is not catch any exceptions, it's just stop the service as i said, and no any logs, so it's bothers me. 2.At present i have't try any other versions, i will try it latter.
