### ISSUE TITLE
Hello,how do i obtain memory serial number?

### ISSUE THREAD

**Issue by Tegrason** [oshi/oshi#2644]
Hello,how do i obtain memory serial number?

**Comment by yourancc** [comment]
`        SystemInfo si = new SystemInfo();
        for (PhysicalMemory physicalMemory : si.getHardware().getMemory().getPhysicalMemory()) {
            physicalMemory.getPartNumber();
            System.out.println(physicalMemory.toString());
        }`
Please review the code above to see if it contains the attributes you require ：)

**Comment by Tegrason** [comment]
> ```
>         SystemInfo si = new SystemInfo();
>         for (PhysicalMemory physicalMemory : si.getHardware().getMemory().getPhysicalMemory()) {
>             System.out.println(physicalMemory.toString());
>         }
> ```
> 
> Please review the code above to see if it contains the attributes you require ：)

This is not memory serial number

**Comment by dbwiddis** [comment]
OSHI currently doesn't collect Memory serial numbers.

You are welcome to submit a PR to add that capability, it will be similar to the recent addition of Part Number in #2603 and #2625

**Comment by Tegrason** [comment]
> OSHI currently doesn't collect Memory serial numbers.
> 
> You are welcome to submit a PR to add that capability, it will be similar to the recent addition of Part Number in #2603 and #2625

Okay!
