### ISSUE TITLE
oshi returns wrong data when trying to read temperature

### ISSUE THREAD

**Issue by wowselim** [oshi/oshi#266]
Reading the temperature on an infinite loop always returns `30.0` on my machine.
The docs say it returns the temperature of the cpu or `0` if not available. Other applications read different temperatures that also vary over time.

Please note that my CPU usually does not run below 35°C so the returned value has to be wrong.

![screenshot](http://i.imgur.com/6GRC3pq.png)

**Comment by dbwiddis** [comment]
You didn't state which operating system you use, but looking t the screen capture, it appears to be Windows.  To further troubleshoot, I need to know the output of the following commands:
```
wmic PATH Win32_Temperature get CurrentReading

wmic PATH Win32_TemperatureProbe get CurrentReading

wmic PATH Win32_PerfFormattedData_Counters_ThermalZoneInformation get Temperature

wmic /namespace:\root\wmi PATH MSAcpi_ThermalZoneTemperature GET CurrentTemperature
```

**Comment by wowselim** [comment]
The first and last commands that you posted lead to errors when executed. The first says "Not found" whereas the last reads "Invalid namespace".

![screenshot](https://i.imgur.com/0tbU1bV.png)

**Comment by dbwiddis** [comment]
OSHI is getting its data from the [Win32_PerfFormattedData_Counters_ThermalZoneInformation](http://wutils.com/wmi/root/cimv2/win32_perfformatteddata_counters_thermalzoneinformation/#temperature_properties) WMI property which is returning your temperatures as 303 and 301 degrees Kelvin.   Subtracting 271.15 from the average of 302 gives 30 degrees Celsius.

I'm not sure why the WMI temps don't match your other sources.

**Comment by dbwiddis** [comment]
Closing this as OSHI is returning a correct value for your system's WMI reports (301K = 30C).  If you can find documentation that shows your WMI numbers are something other than degrees Kelvin I'm happy to reopen this and make changes.
