### ISSUE TITLE
How to get the SERIAL NUMBER on Windows

### ISSUE THREAD

**Issue by abrahan-romo** [oshi/oshi#2666]
I am using OSHI version 6.2.2. If I run a short program in my Eclipse IDE, it is capable of collecting the SERIAL NUMBER of a USB Camera attached to my laptop. On the other hand, if I create an independent artifact and run it in a DOS console, I am NOT able to get the SERIAL NUMBER.

How can I give OSHI credentials or authorization to collect the serial number of the USB Camera attached?

**Comment by mprins** [comment]
duplicates https://github.com/oshi/oshi/discussions/2667
