### ISSUE TITLE
oshi shows wrong OS version on Windows 10

### ISSUE THREAD

**Issue by wowselim** [oshi/oshi#267]
Oshi shows my OS as Windows 8.1 when it's actually Windows 10. I don't exactly remember if I upgraded to Windows 10 or did a clean install so that might be related.

![screenshot](https://i.imgur.com/dxCJhns.png)

The method I use for getting the os version is following:
![screenshot2](http://i.imgur.com/CU1O3wj.png)

**Comment by trejkaz** [comment]
Check which version of Java you're running.

**Comment by dbwiddis** [comment]
[This page appears](https://msdn.microsoft.com/en-us/library/windows/desktop/dn481241(v=vs.85).aspx) to explain the reason the Windows 8 version is returned.

OSHI uses `GetVersionEx()` which has apparently been deprecated.  OSHI should be rewritten to use the [version helper functions](https://msdn.microsoft.com/en-us/library/windows/desktop/dn424972(v=vs.85).aspx) if the version is 8.1 or greater.  Or, possibly use a different approach altogether.

**Comment by trejkaz** [comment]
When I researched this one for our own purposes, the "replacements" for GetVersionEx didn't give us a simple representation of the version at all, so they weren't really replacements. Essentially Microsoft got sick of people making assumptions based on the version number, so they nuked the entire facility from orbit and replaced it with this pile of not-quite-the-same APIs.

The best option I saw was that you make sure you keep your application's manifest up to date, and hard-code a huge table of names of Windows versions.

**Comment by dbwiddis** [comment]
I may just parse the output of the `systeminfo` command line. :)

**Comment by CafeLungo** [comment]
I seem to get "10" on Windows 10, but for what I'm doing, I need the extended version info, eg: "10.0.10586". What is the best way to do this, instead of just parsing the command that @dbwiddis suggested, or 'wmic os get version'. Is WindowsOSVersionInfoEx().getVersion() supposed to be returning this extended info, or is it broken on Windows 10, and thus returns only "10". The documentation isn't extremely clear on what I should be expecting from each of the fields in there.

**Comment by kickdev** [comment]
that for control?
![68747470733a2f2f692e696d6775722e636f6d2f6478434a686e732e706e67 1](https://cloud.githubusercontent.com/assets/10669667/20240035/91f43444-a91f-11e6-95b7-c33d6acdc676.png)

**Comment by dbwiddis** [comment]
I've finally got time to work on this, but I'm not yet sure exactly how to approach it.  Also my Windows test environment is version 7, so testing a fix will be difficult.   To summarize this issue:

Microsft deprecated the [GetVersionEx()](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724451(v=vs.85).aspx) function in version 8.1, so for later versions it's simply returning Version 8, or the version specified in the manifest (may be 10).   MS suggests using the [Version Helper Functions](https://msdn.microsoft.com/en-us/library/windows/desktop/dn424972(v=vs.85).aspx) but these are insufficient for the version resolution we want.  At best, we might consider using one of these functions as a test whether `GetVersionEx()` is deprecated, to use an alternative.

Alternative sources of information include:

- Parsing the [ver](https://en.wikipedia.org/wiki/Ver_(command)) command.  This would require [building a table](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724832(v=vs.85).aspx) to correlate this output to the version name.

- Parsing the [systeminfo](https://technet.microsoft.com/en-us/library/bb491007.aspx) command.  This incurs a few seconds of latency as Windows looks for hotfixes (there does not seem to be a way to avoid this).  This doesn't get much more than `ver` does (we get a build number).

- WMI via the [Win32_OperatingSystem](https://msdn.microsoft.com/en-us/library/aa394239(v=vs.85).aspx) class.  `wmic os get Caption,Version,BuildNumber,CSDVersion` is probably all the info we need. 

I'm currently leaning strongly toward the WMI solution.  If those of you on Win10 systems can confirm the above wmic command line returns the information you want (or suggest other info you need) I'll knock this out this week.

**Comment by dbwiddis** [comment]
I went ahead and did the WMI approach in #282, to be committed shortly.  The info is also in the registry, HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion but I'm guessing that's where WMI gets it from and it's more consistent with all the other code to go that route.
