### ISSUE TITLE
LinuxBlockDevStats java.lang.ArrayIndexOutOfBoundsException: 11

### ISSUE THREAD

**Issue by jnthnclt** [oshi/oshi#268]
on GNU/Linux CentOS 6.5 (Final) build 2.6.32-431.el6.x86_64

java.lang.ArrayIndexOutOfBoundsException: 11
    at oshi.hardware.platform.linux.LinuxBlockDevStats.<init>(LinuxBlockDevStats.java:78) 
    at oshi.hardware.platform.linux.LinuxDisks.computeDiskStats(LinuxDisks.java:145)
    at oshi.hardware.platform.linux.LinuxDisks.getDisks(LinuxDisks.java:93) at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.getDiskStores(LinuxHardwareAbstractionLayer.java:70)

**Comment by dbwiddis** [comment]
Can you post the contents of the `/sys/block/<dev>/stat` file causing this issue?  [There should be 11 decimal fields](https://www.kernel.org/doc/Documentation/block/stat.txt).

Looks like with the indexing off-by-one that the code assumes a prepending field as well.

Regardless, an array size check should be inserted to prevent the exception.

**Comment by lu-ko** [comment]
I have the same issue. Content of one of my files:
`27400439    86290 4233662524 110206912 65318263  1864632 9861572544 4168048140        0 90323432 4278221968`

Yes, there are 11 fields, and so I assume that iteration should be from 0 to 10. There is no element with index 11.

**Comment by henryx** [comment]
@lu-ko nice job. If you send a pull request, I merge it and I close the issue

**Comment by dbwiddis** [comment]
To echo @henryx , this looks like a relatively easy fix with a check for the array length and if anyone else can handle this in the next month, that's great.  We'll merge your fix.

Personally, I am unavailable until 2017, and will attempt to handle this then if it's not taken care of before!

**Comment by dbwiddis** [comment]
@lu-ko your commit on your own branch looks good (I've suggested one simplification).  Can you please commit that so I can give you credit for the fix?

**Comment by lu-ko** [comment]
@dbwiddis Thank you for your feedback. I will look at it, probably after Christmas.
