### ISSUE TITLE
Seeing [ERROR] Error reading file /proc/2045181/cmdline. null in log

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#2689]
### Discussed in https://github.com/oshi/oshi/discussions/2685

<div type='discussions-op-text'>

<sup>Originally posted by **wolfs** July 10, 2024</sup>
I am seeing
```
[ERROR] Error reading file /proc/2045181/cmdline. null
[ERROR] Error reading file /proc/1975607/cmdline. null
[ERROR] Error reading file /proc/1962012/cmdline. null
```
in my logs. I think this is because I am calling `OSProcess.queryArguments()`, that uses `FileUtil.readAllBytes()` and the process file is already gone.

https://github.com/oshi/oshi/blob/7023f06b5606d07a7f6dbf6d730beeb05c4f1a9d/oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java#L129-L132

I think the call should be changed to `FileUtil.readAllBytes(String.format(Locale.ROOT, ProcPath.PID_CMDLINE, getProcessID()))), false)`, so it doesn't print out on the error log when reading the file fails.

It seems like `OSProcess.queryCommandline()` already calls a method that does not log on error:
https://github.com/oshi/oshi/blob/7023f06b5606d07a7f6dbf6d730beeb05c4f1a9d/oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java#L118-L121</div>

**Comment by dbwiddis** [comment]
Thanks for the report, @wolfs!

We'd welcome a PR to fix this!

**Comment by wolfs** [comment]
I created https://github.com/oshi/oshi/pull/2692 for doing so.
