### ISSUE TITLE
Feature request: Routing information & DNS settings

### ISSUE THREAD

**Issue by Ryan421** [oshi/oshi#269]
Hello,

Is it possible to add more network information features like routing (at least default gateways), dns settings, hostname into OSHI?

**Comment by dbwiddis** [comment]
I think OSHI already has most of the easily accessible information leveraging Java's `NetworkInterface` class.  You can get the hostname with `InetAddress.getHostName()`.  

Routing information is probably available somewhere from the routing tables but that's a whole lot of command-line parsing for not very much info, and a lot more complexity.  Open to a PR if you've got an idea on how you'd like to add it.

**Comment by dbwiddis** [comment]
I see you've gotten started on this in #294.   FYI:

FreeBSD:
- Hostname, Domain name.  There are commands for these but they simply call the `libc` functions `gethostname()` and `getaddrinfo()` which would be preferred.  (Should try to use this approach for Linux as well.)  
- Gateways: use [route](https://www.freebsd.org/cgi/man.cgi?query=route) and search for the line in the output:
```
$ route -4 get default
... <snip> ...
    gateway: 10.211.55.1
... <snip>

$ route -6 get default
... <snip> ...
    gateway: fe80::21c:42ff:fe00:18%em0
... <snip>
```
- DNS Servers in `resolv.conf` as for Linux.

Solaris:
- Hostname, Domain name.  Same `gethostname()` and `getaddrinfo()`-based commands as FreeBSD and Linux.
- Gateways:  `route get -inet default` produces the same output on Solaris as `route -4 get default` on FreeBSD, and `route get -inet6 default` produces the same as `route -6 get default`.
- DNS Servers in `resolv.conf` as for Linux.

**Comment by dbwiddis** [comment]
OS X:
- Hostname, Domain name:  same approach as described above for FreeBSD, Solaris, and suggested change for Linux.  (Yay standard C library.)
- Gateway:  `route -n get default` gets the same as above for FreeBSD/Solaris ipv4 but doesn't offer a way to get ipv6.   Instead use `netstat -nr` and look for the `G` flag  or the `default` destination:
```
<danielwiddis> [01-03 14:16] ~/git/oshi $ netstat -nr
Routing tables

Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
default            192.168.1.1        UGSc           51        0     en5
default            192.168.1.1        UGScI          12        0     en1
... <snip> ...
Internet6:
Destination                             Gateway                         Flags         Netif Expire
default                                 fe80::%utun1                    UGcI          utun1
... <snip> ...
```
DNS Server: do NOT use `resolv.conf`.  Use `scutil --dns`:
```
<danielwiddis> [01-03 14:16] ~/git/oshi $ scutil --dns
DNS configuration
 
resolver #1
  nameserver[0] : 8.8.8.8
  nameserver[1] : 8.8.4.4
... <snip -- these same two nameservers repeat later in the output> ...
```

**Comment by dbwiddis** [comment]
Finished implementing this in #305.  It's in snapshot now, waiting for tests to run before merging.
