### ISSUE TITLE
Windows - I/O Stats

### ISSUE THREAD

**Issue by wcpfeffer** [oshi/oshi#2720]
Are the Windows read/written bytes per process specifically disk related or are they the total I/O for the process? 

I see the java docs says "Returns: the number of bytes the process has read from disk".  Looking into the source code a bit, I see usages of "IO Read Bytes/sec" and "IO Write Bytes/sec" counters, which I believe include network activity as well.

**Comment by dbwiddis** [comment]
The values come from the registry `HKEY_PERFORMANCE_DATA` which exactly matches the performance counters for `Process` and the corresponding WMI table `Win32_PerfRawData_PerfProc_Process`.   The last one, while the sloweest, has the [best documentation](https://learn.microsoft.com/en-us/previous-versions/aa394323(v=vs.85)):

Yes, it's all IO (to include file, network, and device I/Os):

> **IOReadBytesPerSec**
> 
> Data type: **uint64**
> 
> Access type: Read-only
> 
> Qualifiers: [DisplayName](https://msdn.microsoft.com/en-us/library/aa393650(v=vs.85)) ("IO Read Bytes/sec") , [CounterType](https://msdn.microsoft.com/en-us/library/aa392761(v=vs.85)) (272696576) , [DefaultScale](https://msdn.microsoft.com/en-us/library/aa392761(v=vs.85)) (0) , [PerfDetail](https://msdn.microsoft.com/en-us/library/aa392761(v=vs.85)) (200)
> 
> Rate at which the process is reading bytes from I/O operations. This property counts all I/O activity generated by the process to include file, network, and device I/Os.

> **IOWriteBytesPerSec**
> 
> Data type: **uint64**
> 
> Access type: Read-only
> 
> Qualifiers: [DisplayName](https://msdn.microsoft.com/en-us/library/aa393650(v=vs.85)) ("IO Write Bytes/sec") , [CounterType](https://msdn.microsoft.com/en-us/library/aa392761(v=vs.85)) (272696576) , [DefaultScale](https://msdn.microsoft.com/en-us/library/aa392761(v=vs.85)) (0) , [PerfDetail](https://msdn.microsoft.com/en-us/library/aa392761(v=vs.85)) (200)
> 
> Rate at which the process is writing bytes to I/O operations. This property counts all I/O activity generated by the process to include file, network, and device I/Os.
