### ISSUE TITLE
Site failed to publish for 6.6.4 release

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#2727]
The site failed to publish.  See log at https://github.com/oshi/oshi/actions/runs/10875296495/job/30173544796#step:5:2555
> Error:  Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.20.0:site (default-site) on project oshi-parent: Failed to create context for skin: Cannot use skin: has [1.11.1,2.0.0-M1) Doxia Sitetools prerequisite, but current is 2.0.0-M19 -> [Help 1]

In addition there are warnings about using an old model:

> Warning:  Project does not have a parent.
> Warning:  Site model of 'com.github.oshi:oshi-parent:pom:6.6.4' for default locale is still using the old pre-version 2.0.0 model. You MUST migrate to the new model as soon as possible 

@hazendaz is this an easy fix you're aware of or should I ask my favorite AI chatbot how to solve it? :)

**Comment by hazendaz** [comment]
For now move back to the prior site plugin.  I had commented on the PR for that as its not a drop in place.  Its a major upgrade.  However, the rules to auto merge merged it anyways, see https://github.com/oshi/oshi/pull/2706.

**Comment by dbwiddis** [comment]
Well, automerge assumed semver.... :|

**Comment by hazendaz** [comment]
All good.  Maven doesn't follow rules very well.  That was version 4 milestones.  Then they figured confusion with maven 4.  Not the first time there.  The change to update probably isn't difficult on this project.  Generally site.xml needs updated and if using things like fluido those must jump to the milestone releases.  It's odd to see that.  This has to do with doxia 2 which is still incomplete milestone stages.
