### ISSUE TITLE
Support getting Options of OSFileStore

### ISSUE THREAD

**Issue by CodingFabian** [oshi/oshi#273]
In Sigar there exists FileSystem.getOptions() which returns stuff like "rw,local,rootfs,nfs" 
Would be great if OSFileStore has something similar.

**Comment by dbwiddis** [comment]
OSHI already contains most of the information in this type of query, that is consistently cross-platform.

Some additional information can be retrieved using Java/Swing's FileSystemView, but we had problems with the swing framework and eventually got rid of it.   Given that we already display most/all of what's available in `mount` and similar commands, I'm not sure how we'd implement this cross platform.

**Comment by CodingFabian** [comment]
Sigar gets them this way:
mac:
https://github.com/hyperic/sigar/blob/ad47dc3b494e9293d1f087aebb099bdba832de5e/src/os/darwin/darwin_sigar.c#L2079
win:
https://github.com/hyperic/sigar/blob/ad47dc3b494e9293d1f087aebb099bdba832de5e/go_bindings/Sigar/src/os/win32/win32_sigar.c#L1902
linux:
https://github.com/hyperic/sigar/blob/ad47dc3b494e9293d1f087aebb099bdba832de5e/src/os/linux/linux_sigar.c#L1168 (which is basically https://linux.die.net/man/3/getmntent_r # mnt_opts)
aix:
https://github.com/hyperic/sigar/blob/ad47dc3b494e9293d1f087aebb099bdba832de5e/src/os/aix/aix_sigar.c#L1171
solaris:
https://github.com/hyperic/sigar/blob/ad47dc3b494e9293d1f087aebb099bdba832de5e/src/os/solaris/solaris_sigar.c#L1398


so it seems that on *ix the string is taken from the os. on windows and mac the string is "emulated based on the type" I think thats a reasonable idea.

**Comment by dbwiddis** [comment]
So, I'm wondering what the best approach is for all these sigar-isms.   Implement similarly performing (but different) functionality in oshi, or develop a new project that uses the same API as SIGAR to ease transition.

**Comment by dblock** [comment]
I vote for not caring about Sigar at all.

**Comment by CodingFabian** [comment]
@dblock thats a perfectly reasonable position.
I want to get away from sigar, and there is also a certain loss of capabilities I am willing to incur. But my feature requests are from my user perspective, which you certainly care about. I just used the links to the sigar implementation to document how its done in sigar.

in my opinion for this concrete feature, the mnt_opts in any *ix derivates is a totally reasonable and easy to get information. Similar data is available in other os, and i somehow like the solution of sigar emulating the mnt_opts

**Comment by dbwiddis** [comment]
I'm going to close this, as I think all the information is already available and this provides no added value.  And nobody has commented on this issue in 2 1/2 years.   Feel free to re-open this issue if it's important, and identify what OSHI doesn't currently provide that will enable this desired functionality.

**Comment by dbwiddis** [comment]
Reopening this as I finally found a use case for this that isn't handled by the existing information.

**Comment by dbwiddis** [comment]
For macOS, see the [optnames in mount.c](https://opensource.apple.com/source/diskdev_cmds/diskdev_cmds-593.221.1/mount.tproj/mount.c.auto.html).

FreeBSD already calls `mount`, can pull directly from there.  Solaris reads `/etc/mnttab` and Linux reads `/proc/self/mounts` (should it be `/proc/mounts`?) which I believe have the same info, but should be confirmed.

I don't think there's a direct corresponding value in Windows, although the `lpFileSystemFlags` value available from the `GetVolumeInformation()` call might have some values which corresponds.

**Comment by dbwiddis** [comment]
Better late than never. :)
