### ISSUE TITLE
Can oshi collect the process cpu/memory usage under the pod?

### ISSUE THREAD

**Issue by ruanwenjun** [oshi/oshi#2730]
Hi team,

We have use oshi on physical machine, this works well. Right now, we will migrate to k8s. 

We meet a problem, it seems in k8s, we get the information is under the host machine rather than the pod.

 I am not sure if this is caused by we miss some configuration.

I search from the doc/issue list, didn't find the related information.

Thanks

**Comment by dbwiddis** [comment]
Hi @ruanwenjun,

OSHI is designed to read native statistics.  For containers or pods, we have not added any special casing, as each of these tends to have their own setup and it's largely command-line parsing.   See #2632 for a discussion of possibly creating a cross-(container)-platform representation for containers confirming to OCI.

Pods are closer to VMs than containers, though.   But this still seems something that should be able to be handled at the pod level to prevent user access to the underlying machine, for example https://github.com/rootless-containers/rootlesskit has a few kubernetes projects using it.  (Found using a search; I have no experience with it.)

For most Linux stats, just mounting a custom procfs is likely sufficient.

**Comment by ruanwenjun** [comment]
@dbwiddis Thanks for your quickly reply, I might get your point, I will try to test in more ways.
