### ISSUE TITLE
Support Errors on NetworkIF

### ISSUE THREAD

**Issue by CodingFabian** [oshi/oshi#274]
Sigar has NetInterfaceStat with errors, dropped and overruns - I am not sure if all of them actually make sense, bt it would be great NetworkIF would have some kind of error metric.

**Comment by dbwiddis** [comment]
This seems rather easy to add to the existing interface.  The data is on the objects we already read for bytes sent/received, in most cases.

PR welcome.

**Comment by CodingFabian** [comment]
Sorry for not following up with a PR. I am still getting used to the codebase, it seems it was easy for you, so thank you for doing that addition @dbwiddis !

**Comment by dbwiddis** [comment]
No worries. I left you the process-specific ones, though! ;)

**Comment by CodingFabian** [comment]
ok. maybe next year :)
