### ISSUE TITLE
Maven central

### ISSUE THREAD

**Issue by quantrpeter** [oshi/oshi#2748]
Hi, thanks for the project. Is it on maven central?
thanks
Peter

**Comment by dbwiddis** [comment]
Yep, look for this icon at the top of the README: [![Maven Central](https://img.shields.io/maven-central/v/com.github.oshi/oshi-core.svg?label=Maven%20Central)](https://central.sonatype.com/search?namespace=com.github.oshi&sort=name)

**Comment by quantrpeter** [comment]
great project and thanks
