### ISSUE TITLE
How to get the FIRMWARE VERSION or FIRMWARE LEVEL or BCDLEVEL of a USB Device connected to my laptop on Windows OS ?

### ISSUE THREAD

**Issue by abrahan-romo** [oshi/oshi#2772]
I am using OSHI version 6.6.5 for Java 8. I am exploring all the available getMethods( ) from the USBDevice class, but I do not see any getMethod associated with collecting the FirmwareLevel, FirmwareVersion, FirmwareRevision, or bcdLevel. 

Can I kindly ask you if, is there any another way to collect that value using OSHI 6.6.5 for Java 8?

I really appreciate the feedback, help, and time in advance!

**Comment by dbwiddis** [comment]
Hey @abrahan-romo .

On Windows, OSHI navigates the [Device Tree](https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/device-tree) to iterate USB devices.  We only currently collect a subset of properties, such as `CM_DRP_FRIENDLYNAME`, `CM_DRP_DEVICEDESC`, and `CM_DRP_MFG`.

See here for the list of all properties we could query for: https://learn.microsoft.com/en-us/windows-hardware/drivers/install/accessing-device-instance-spdrp-xxx-properties.  I recall when writing this code that I did try to print them out and didn't find many others useful, and I don't see any associated with firmware.

So the answer is most probably not.

**Comment by abrahan-romo** [comment]
Thanks @dbwiddis, I really appreciate the feedback and answer !!!
