### ISSUE TITLE
Battery info on some Linux systems should exclude AC

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#278]
See https://github.com/openhab/openhab2-addons/issues/1471#issuecomment-264763661

LinuxPowerSource.java should be modified to exclude "AC" as well as "ADP":
`if (psName.startsWith("ADP") || psName.startsWith("AC")) {`

**Comment by DaAwesomeP** [comment]
@dbwiddis This filename seems more standard than just Debian stable. It's present on my OpenSUSE machine too. It may have to do with the kernel version.

Thanks for working on a fix!

**Comment by dbwiddis** [comment]
Reasonable.  I develop/test on an Ubuntu VM and do as much research as I can to see what's common across kernels.  Thanks for posting the needed fix in the other thread, should be quick.
