### ISSUE TITLE
Motherboard

### ISSUE THREAD

**Issue by icirellik** [oshi/oshi#287]
Just wondering if there has been and thought around adding capabilities to retrieve the motherboard serial number?

```
$ sudo dmidecode -t 2
# dmidecode 3.0
Getting SMBIOS data from sysfs.
SMBIOS 3.0.0 present.

Handle 0x0002, DMI type 2, 15 bytes
Base Board Information
	Manufacturer: ASUSTeK COMPUTER INC.
	Product Name: Z170-DELUXE
	Version: Rev 1.xx
	Serial Number: XXXXXXXXXXXXXXX
	Asset Tag: Default string
	Features:
		Board is a hosting board
		Board is replaceable
	Location In Chassis: Default string
	Chassis Handle: 0x0003
	Type: Motherboard
	Contained Object Handles: 0
```

**Comment by dbwiddis** [comment]
See #263 and initial implementation in #264.  That may get part of the way there and if it's easy to grab one more piece of information, we may do so.

Beyond that, the question is whether it is (a) cross-platform and (b) doesn't require sudo everywhere.

**Comment by dbwiddis** [comment]
Working this as part of #289
