### ISSUE TITLE
Relocate coordinates from 'dblock' to 'oshi'

### ISSUE THREAD

**Issue by hazendaz** [oshi/oshi#293]
Since we moved this to an organization, we need to properly rebrand the groupId and anything else that might reflect 'dblock'.  This additionally will mean we need to request access to new group id on sonatype to get releases out.  Will target this change with 3.4.

For waffle, I did not add relocations.  I could do that effort here if needed.  The idea there is that users don't change anything but the version but it simply points over to our new location.  We would not want to carry that on long if we did it which is why I just skipped doing so with waffle.  I think as long as we document it well we don't need to do that but we might also find out later usage is low.  If that happens we might certainly want to upload redirects.

In addition to doing this, I'll take another hard look at the build as javadocs continue to cause issue on release but projects like waffle that this was designed off of for the build no longer have such issues.

**Comment by hazendaz** [comment]
Switch versioning to semantic versioning (ie 3.4.0)

**Comment by dbwiddis** [comment]
Oh, sure, someone had to point out that we're not following [semver](http://semver.org/) standards. ;)

I agree in principle but think a change in maven coordinates should happen with a major version change (e.g., 4.0... or 4.0.0).

**Comment by dbwiddis** [comment]
Just a thought.  You could release 3.3.0 under the new coordinates, with no code changes.  This would allow a somewhat transparent switch for anyone wanting to switch now...

**Comment by dbwiddis** [comment]
@hazendaz I'm looking at cutting the 3.4.0 release on (or about) March 1.  Do you still want to handle this rebrand or should I work on setting up the new coordinates?

**Comment by dbwiddis** [comment]
https://issues.sonatype.org/browse/OSSRH-28459

**Comment by dbwiddis** [comment]
I've updated the coordinates in the `pom.xml` and `assembly.xml` files, and snapshots are now being posted to the new coordinates (with semver-compliant 3.4.0).   Per the above link, OSSRH is set up for us to publish there.

Actions needed on release:
* More links in `README` (release version link, some badges) will need to be updated to the new coordinates.  Should carefully check all other files/links as well.
* We'll need to comment on the above ticket to note that it's been released for them to complete the setup process.

Also, I am researching whether we can/should publish ["minimal relocation" POMs ](https://maven.apache.org/guides/mini/guide-relocation.html) to the old coordinates. Not sure if that's possible with OSSRH.

**Comment by dbwiddis** [comment]
Update: [here's how to do a pom-only release with relocation](https://issues.sonatype.org/browse/OSSRH-4501) to the old coordinates.

**Comment by dbwiddis** [comment]
3.4.0 [has been released to the new coordinates](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.github.oshi%22).

@hazendaz if you're familiar with doing the relocation POMs I'd appreciate it if you can handle that.  If not, I'll figure out how to muddle through it.

**Comment by dbwiddis** [comment]
Actually, I think I got it.  I edited all the poms and ran

> mvn clean verify gpg:sign install deploy -DaltDeploymentRepository=sonatype-nexus-staging::default::https://oss.sonatype.org/service/local/staging/deploy/maven2/

It's complaining that I deleted too much (it still wants developer, scm info) but otherwise looks like the deployment worked.

**Comment by dbwiddis** [comment]
The relocation is live on Central.
