### ISSUE TITLE
More Battery Information

### ISSUE THREAD

**Issue by ejaszewski** [oshi/oshi#306]
The current PowerSource class contains very little information for battery power sources even though more information is available. Some of that information, such as maximum capacity, current capacity, discharge rate, etc., could is either already parsed, or could be calculated using existing information on Linux and Windows.

On Linux, this additional information can be parsed from the same '/uevent' file contains information on the battery's full and current charge in mWh, the battery's current voltage, and the battery's technology.

On Windows, the information for the battery's maximum charge in mWh, and the other information can be calculated using this information (aside from discharge rate).

On Mac OSX, it appears that the required information can be parsed from the ioreg command.

I am happy to get this parsing working on Linux but have no way to test on Windows or Mac OSX. Perhaps the best way to approach this is to have a class for AC power sources and a separate class for Battery power sources, considering that this information doesn't apply to an AC power source.

**Comment by dbwiddis** [comment]
I wouldn't call it 'very little'!  I've got enough to replicate my little battery meter with % remaining, time, and the little lightning bolt when it's charging.  😄 

But sure, no reason we can't include more information.  If you can get the Linux version working and as much implementation as you can on other OS's, I'm happy to finish the porting work (and test).

FYI, on OS X anything you can get with `ioreg` you can get by directly accessing the registry.  We already do so with the [IOKit API which already has several keys](https://developer.apple.com/reference/iokit/iopskeys.h?language=objc) to retrieve power source information. [Review these](https://opensource.apple.com/source/IOKitUser/IOKitUser-755.9.7/ps.subproj/IOPSKeys.h) to see what's available and try to keep the implementation as cross-platform as you can.  Looks like there's plenty there to get the additional information you suggest.

I'm not sure how much useful information there is on AC power sources, beyond "plugged-in" and "charging" types of information, and whether they should have their own class or just be ignored, or have some default values (infinite max capacity, etc.)

**Comment by ejaszewski** [comment]
Just a quick question about the implementation I am currently working on. Mac OSX and Windows can both use undefined or relative units for the battery capacity, meaning that it is not always possible to retrieve the value directly. I am thinking that the workaround would be to use the discharge rate and time remaining to get an estimate using the following formula:
`(power * time) * conversion factor ≈ capacity`

Where on Mac OSX with units, it would be:
`Capacity (mWh) = (voltage mV * current mA * time min) * (1 mW / 1000 µW) * (1 hr / 60 min)`

And on Windows, it would be:
`Capacity (mWh) = (power mW * time sec) * (1 hr / 3600 sec)`

Let me know whether these are okay fallback methods of calculating capacity if the units are relative, or if you think I should try finding other sources of information to parse.

**Comment by dbwiddis** [comment]
Not quite sure I understand the question but if you are asking if it's ok to calculate a default estimate if you can't get it directly, that's fine.

**Comment by dbwiddis** [comment]
Another note: if the missing values can be calculated from the existing values, what are we adding?

**Comment by ejaszewski** [comment]
The discharge rate is not currently in the API, so I will be grabbing that information from IOKit, and will be using the other information in the Windows Device Power API. So at the moment, I am adding discharge rate (mW) and capacity in mWh.

**Comment by dbwiddis** [comment]
Got it, and glad it's you and not me trying to remember my EE201 class.

**Comment by dbwiddis** [comment]
Reviewing the OS X keys, there are three capacity keys.  Current (some percentage of full), Max (what I believe you will be calculating if it's not given), and Design (what's probably on the label and should be left blank/unknown, but if given would give a measure of battery degradation).  Do the other platforms have these three separate capacities?  There would be value to having them.

**Comment by dbwiddis** [comment]
I was just looking at Solaris keys. Looks like most of the code to collect the kstat info (including design vs. current max cap) is already there, you just need to save it. 

FreeBSD example outputs are [here](https://www.cyberciti.biz/faq/freebsd-finding-out-battery-life-state-on-laptop/).  We're already using the sysctl outputs, except for units (# of batteries) which are pretty limited, but it looks like the `acpiconf` output could be usefully parsed.

A request... while you're rewriting this.  Get rid of the constructor with arguments and replace it with setters/getters.

**Comment by ejaszewski** [comment]
Design capacity is present on Linux and Windows, but sometimes has relative units on Windows. Perhaps a battery health value that is calculated by Max/Design might be useful.

As for FreeBSD, I think parsing acpiconf is the way to go. Looks like it provides the necessary information in appropriate units.

Finally, do you have an example of the getter/setter format you want? I might as well redo it while I'm doing other stuff with the power sources.

**Comment by dbwiddis** [comment]
Just a no-arg constructor.  Values should be initialized to defaults and allow being overridden by setters.  The `AbstractComputerSystem`, `AbstractBaseboard`, and `AbstractFirmware` follow this model. 

You'd then change the static method that instantiates them to create the new object and use the setters, rather than passing arguments.

**Comment by dbwiddis** [comment]
Making any progress on this?  Targeting a 3.4.0 release around March 1.

**Comment by ejaszewski** [comment]
Yeah, I should be done by the end of the week.Sorry about the slow progress on this.

**Comment by dbwiddis** [comment]
No need to apologize. Any help, no matter how slow, is appreciated.  It was more for planning purposes whether to wait to release or push ahead.  Last thing I'd want to do is push a release and have you submit your PR later the same day! 😄

**Comment by ejaszewski** [comment]
So, I'm done with Linux, Mac OS, and Windows (barring a couple of minor changes), but I'm not sure how to proceed with Solaris. I know what to do with FreeBSD, but I need to write code to parse acpiconf, so I'm not sure how long that will take. Let me know if I should submit the PR before the Solaris and BSD implementations are done. I'll keep plugging away on it.

**Comment by dbwiddis** [comment]
Go ahead and submit what you have done so far, so I can review and comment on it. It might even be able to make suggestions about the remaining OS implementations

**Comment by dbwiddis** [comment]
Pushing this to 3.5.0 since the changes are non-trivial.  See additional discussion on #322.

**Comment by ejaszewski** [comment]
Bit of an update: I haven't been able to work on this since a couple of weeks ago, bit this next week, I'll be on a Windows 10 laptop so I can get the Windows battery information working. I may need some help with JNA & the Windows API calls though.

**Comment by dbwiddis** [comment]
Good to hear.  Let me review the expectations again so we're all on the same page:
- Add several new private variables to the `AbstractPowerSource` with verbose names including units when applicable.  See below
- Set up reasonable default values on all OS's (or default initialization of the `AbstractPowerSource`).
- Feel free to remove the existing constructor with parameters and just use a no-arg constructor and setters (setting up for v4.0 pattern).

Some thoughts on stored fields (units) and where to get them.  You'll override getters on class-specific ones that do math on fields they don't populate:

Name | Linux | Windows | OS X
------|-------|----------|------
Capacity (%) | capacity | remaining/max | remaining/full
Energy (mWh) | energy_now | remainingCapacity | Charge Remaining
EnergyMax (mWh) | energy_full_design | FullChargedCapacity | Full Charge Capacity
EnergyDesign (mWh) | energy_full_design | DesignedCapacity | full
Power | power_now | rate | ? | volt*amperage?
Voltage (mV) | voltage_now | ? | Voltage
TimeRemaining | energy_now/power_now | estimatedTime | remaining/amperage
Health (%) | max/design | full/design | full/design
CycleCount (int) | cycle_count | CycleCount |  Cycle Count
State (text) | state | ac/charg/discharge | Charge Info 
Technology (text) | technology | Chemistry | ? 

Linux: values from `/sys/class/power_supply/BAT0`.
- We currently just read the `uevent` file.
- We might consider reading the individual files
- we might also consider parsing the `upower -d` output.

Windows: from existing `SystemBatteryState` and [BATTERY_INFORMATION](https://msdn.microsoft.com/en-us/library/aa372661(v=VS.85).aspx) structure

OS X:  try the headers in IOPowerSources.h.  If they don't work, parse the output of `system_profiler SPPowerDataType`:
```
Power:

    Battery Information:

      Model Information:
          Serial Number: D866515S19YFWF8DV
          Manufacturer: SMP
          Device Name: bq20z451
          Pack Lot Code: 0
          PCB Lot Code: 0
          Firmware Version: 702
          Hardware Revision: 1
          Cell Revision: 1206
      Charge Information:
          Charge Remaining (mAh): 8550
          Fully Charged: Yes
          Charging: No
          Full Charge Capacity (mAh): 8713
      Health Information:
          Cycle Count: 2
          Condition: Normal
      Battery Installed: Yes
      Amperage (mA): -1
      Voltage (mV): 12767
<snip>
```

**Comment by colinbobolin** [comment]
Hi @dbwiddis - quick question about this. Do you want the names to match the table given above in the Name column? Should I rename these attributes or just work around the existing names? For instance, remainingCapacity -> energy. Also, do you want each of the attributes listed above implemented in the program, even if they are just derived from other attributes? Thanks.

**Comment by dbwiddis** [comment]
Great question and it's really open-ended.   

The name I put in the table was my original suggestion, but I'm very open to alternative / standard names if you think you have a better idea.  

The only names we are really "stuck" with are the ones in the existing API... so "RemainingCapacity" has to stay as-is and reference the percentage... but we could rename it to something else (e.g., RemainingCapacityPercent) and deprecate the existing term, giving users time to switch to the new one, and eventually remove the old name in a future version.  So all this really means is we can't re-use RemainingCapacity for anything else.... and we'd have to use RemainingCapacityMWh for the Windows value (unless you prefer Energy)...

**Comment by dbwiddis** [comment]
One thought. Deprecate "RemainingCapacity" and point it to "PercentRemaining", then name the Energy one as "EnergyRemaining" (with friends EnergyFull and EnergyDesign) ...

**Comment by dbwiddis** [comment]
More food for thought. Capacity can be either mWh or mAh, where mWh is a unit of "Energy" and mAh is a unit of "Power" and probably better to have.  Or we could have both, and multiply/divide by voltage to convert.

**Comment by colinbobolin** [comment]
Great, thanks for the thorough response. I'll let try to keep you informed.

**Comment by colinbobolin** [comment]
@dbwiddis Do you know if there is a java library available for accessing the `[BATTERY_INFORMATION](https://docs.microsoft.com/en-us/windows/win32/power/battery-information-str)` structure? I see that PowrProf has a SystemBatteryState class, but I can't find anything for BatteryInformation.
If not, I can just cut the number of attributes I am adding to facilitate what is available.

**Comment by dbwiddis** [comment]
JNA is the library that allows access to the Windows API functions, but not everything is mapped.  I see the Kernel32 class has the [DeviceIoControl](http://java-native-access.github.io/jna/5.4.0/javadoc/com/sun/jna/platform/win32/Kernel32.html#DeviceIoControl-com.sun.jna.platform.win32.WinNT.HANDLE-int-com.sun.jna.Pointer-int-com.sun.jna.Pointer-int-com.sun.jna.ptr.IntByReference-com.sun.jna.Pointer-) method mapped, but not this structure.

Although the structure is probably part of the `Kernel32` DLL, structure mappings don't need to stay in the same class so you can probably just add that structure to the existing `PowrProf` class, and see the other structure mappings as examples of what you'll need to do.  See the Windows type mappings [here](https://docs.microsoft.com/en-us/windows/win32/winprog/windows-data-types)... `ULONG` will map to a 32-bit `int` and the `UCHAR` is an 8-bit `byte`.

You'll need to also define the `int` IOCTL_BATTERY_QUERY_INFORMATION somewhere.  It's defined by these macros...
```
#define IOCTL_BATTERY_QUERY_INFORMATION \
        CTL_CODE(FILE_DEVICE_BATTERY, 0x11, METHOD_BUFFERED, FILE_READ_ACCESS)
#define CTL_CODE( DeviceType, Function, Method, Access ) (                 \
    ((DeviceType) << 16) | ((Access) << 14) | ((Function) << 2) | (Method))
#define FILE_DEVICE_BATTERY             0x00000029
#define METHOD_BUFFERED                 0
#define FILE_READ_ACCESS          ( 0x0001 )
```

**Comment by colinbobolin** [comment]
Ah thanks for pointing me to the DeviceIoControl method! I was having trouble navigating the docs. I'll get back to work and start tinkering with things 😉

**Comment by dbwiddis** [comment]
Heheh.   [Here's the C code you'll need to port](https://docs.microsoft.com/en-us/windows/win32/power/enumerating-battery-devices) in order to get the names of the batteries to open handles... this is getting pretty advanced!

**Comment by dbwiddis** [comment]
If you don't want to go that deep into the rabbit hole, you can just write a WMI query and [fetch from the `Win32_Battery` class](https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-battery).

**Comment by colinbobolin** [comment]
I'm up for the challenge. Fortunately I have some good examples to pull from. Thanks for the support.

**Comment by colinbobolin** [comment]
@dbwiddis A few comments/questions:

- I'm going to put off implementing the collection of data from the BatteryInformation structure. Maybe we can do this in another feature branch, but I may have bitten off more than I can chew, and I noticed some of the OSX features may also take similar efforts to dig up. I just want to deliver incrementally for now.

- Should we standardize the default values? I think currently it has been fine since there are only three attributes, but as we unlock more it will quickly become confusing without standards. Can I suggest having -1 represent "attribute not found," (default values), then if the system gets far enough to find the files/attributes in the system, it sets the value accordingly. even if that value is 0. This would require removing the "-1 = Discharging and -2 = Charging" from the _timeRemaining_ and moving this information to a new _state_ attribute. The _timeRemaining_ attribute would then be calculated from the _energyRemaining_ and _voltage_ attributes across each implementation. Let me know what you think, or if this may be too much change without a major version.

- I have a windows desktop and a linux laptop. Is there a way I can test the OSX and Windows implementations from a linux machine? I can test the Unix implementations from Docker images, but nothing of the sort exists for OSX or Windows.

**Comment by dbwiddis** [comment]
That's fine to hold off on BatteryInformation... note that you can temporarily put a WMI Query in there for Win32_Battery, and quickly get the values... I can work on backporting it to the native code later.

I agree in principle with the change from -1 and -2 to a state variable, but since the API specifies those results we need to keep them.. but we can deprecate the existing methods and create new methods with the new structure we want.    Open to other ideas on defaults, and nonsense values (e.g., negative) are a good idea.

I have a mac and can help test/debug/fix any code you write.  You can probably try to figure out a virtual machine solution for Windows.
