### ISSUE TITLE
COM Library dispose : failed to initialize COM library

### ISSUE THREAD

**Issue by math-th** [oshi/oshi#318]
Hi,

I have a problem that cause JVM crash on Windows 10 (not tested on other systems).
I use Oshi in a Java FX Application.
If I require memory information, everything works fine, but if I called **HardwareAbstractionLayer.getProcessor()** I firstly got an error in log :

`[08:48:41.010][ERROR][JavaFX Application Thread][WmiUtil] Failed to initialize COM library. Error code = 0x80010106`

but this doesn't throw any exception on my call to **getProcessor()**.

After that, when my java process exit, the JVM crash on exit :

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000005c8614fa, pid=2444, tid=6096
#
# JRE version: Java(TM) SE Runtime Environment (8.0_73-b02) (build 1.8.0_73-b02)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.73-b02 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [glass.dll+0x214fa]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\LAPTOP-MATHIEU\Dev\FUS\Workspace\life-companion\lc-launcher\hs_err_pid2444.log
```
You can see the [log file here](https://gist.github.com/math-th/dcee7e2ebb72a3e95ee750364614b1e4).

I suppose it's a kind of error on disposing COM Library as I saw that in **WmiUtil** (line 284) that if initialization failed, it try to dispose it. 

Last information : I add Oshi pluign with Maven.

Thank you, I'm available if you need any other information, please excuse my english.

**Comment by dbwiddis** [comment]
It looks like your COM is already initialized outside OSHI and I need to not un-initialize COM on that error code, [see here](https://blogs.msdn.microsoft.com/benkuhn/2006/09/15/handling-coinitialize-and-couninitialize/).

I don't see any WMI calls directly from the `getProcessor()` method call, though.  Is it one of the processor methods that causes the problem?

**Comment by dbwiddis** [comment]
Can you please test if the latest SNAPSHOT fixes this issue?

**Comment by math-th** [comment]
Thanks for your answer, my original code is :
```
		File infoFile = new File(root.getPath() + File.separator + FUSFramework.EXT_NAME_HARDWARE_INFOS);
		try (FileOutputStream fos = new FileOutputStream(infoFile)) {
			Properties props = new Properties();
			//TODO : Issue #318 on Oshi Github
			CentralProcessor processor = this.hardware.getProcessor();
			//			props.setProperty("fus.cpu.general.info", "" + processor);
			//			props.setProperty("fus.cpu.physical.processor.count", "" + processor.getPhysicalProcessorCount());
			//			props.setProperty("fus.cpu.logical.processor.count", "" + processor.getLogicalProcessorCount());
			//			props.setProperty("fus.cpu.identifier", "" + processor.getIdentifier());
			GlobalMemory memory = this.hardware.getMemory();
			props.setProperty("fus.memory.ram.total", "" + memory.getTotal());
			props.setProperty("fus.memory.swap.total", "" + memory.getSwapTotal());
			//Save
			props.store(fos, "LifeCompanion hardware properties - for debug use");
			LOGGER.info("Hardware properties file saved to {}", infoFile);
		} catch (Throwable t) {
			LOGGER.warn("Couldn't create hardware information", t);
		}
```
This cause the JVM to crash on exit (not on call, because the properties file is saved).
**hardware** is a HardwareAbstractionLayer.
If I comment the line **CentralProcessor processor = this.hardware.getProcessor();** the JVM is not crashing and I don't see any error in logs.

I tested with the **3.4-SNAPSHOT** and it worked ! :-)
I just have a normal warning :
**[08:02:36.798][WARN ][JavaFX Application Thread][WmiUtil] COM already initialized.**
But the JVM is not crashing anymore.

Thanks a mil !

**Comment by dbwiddis** [comment]
Thanks for the code.  I did find the WMI code in the initialization of the ProcessorID, so that explains my confusion there.

Glad to see I've diagnosed the problem about COM already being initialized, so OSHI was shutting down the external app's COM (which then caused the crash on shutdown.)
