### ISSUE TITLE
Java 7 support

### ISSUE THREAD

**Issue by Nadahar** [oshi/oshi#326]
I just found your great library as I was searching for a way to get better information for troubleshooting issues in [UniversalMediaServer](https://github.com/UniversalMediaServer/UniversalMediaServer). Universal Media Server is an UPnP/DLNA server that serves media files to DLNA capable devices like mobile phones, "smart" TV's, game consoles etc. We often have to covert content from one format to another on the fly to make it available in a format that the "client" can understand. For this we use mostly non-Java software like FFmpeg. That means that the amount of memory (and the CPU capabilities, load etc) available to the OS is interesting to us, not just what the JVM has been assigned.

Although we want to ditch Java 7 as well, it doesn't seem like we can for quite some time yet without excluding a lot of users. The last time I checked there were still Linux distros out there where Java 8 isn't yet available. Oracle has decided (with good help from Microsoft I suspect) to withdraw their Windows XP support for Java 8 (it was supported in the beginning). [Windows XP is still the 3. most used OS today](https://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0), much larger than any Linux distro or OS X.

I'm guessing that there won't be long until the remaining Linux distros offer OpenJDK8, but the Windows XP situation isn't likely to be solved. 

I just found that Red Hat is offering [OpenJDK 8 for Windows](https://developers.redhat.com/blog/2016/06/27/openjdk-now-available-for-windows/), but I haven't been able to find any information about which Windows versions are supported. Registration is required for download, so I haven't checked it any further.

I'm currently testing out version 2.6.1-Java7, and it seems to provide us with what we need. But, the same consideration might be relevant in your decision-making.

**Comment by dbwiddis** [comment]
Thanks for the suggestion.   I chose Java 8 primarily for two reasons:
* Avoid adding another dependency
* Convenience/clarity of code methods/lambdas

The points you mention are valid reasons to restore Java 7 support.  It shouldn't be too hard.   Steps:
* Add [dependency to threeten.org](http://www.threeten.org/threetenbp/) for the new datetime classes.

**Comment by dbwiddis** [comment]
Another benefit/chore is to restore travis-ci testing on openjdk.

**Comment by ejaszewski** [comment]
Just throwing in my two cents. First off, the OpenJDK wiki shows that OpenJDK 8 and 9 both build on every version of the Linux Kernel they support. Additionally, I found a different set of numbers for XP usage -- less than 5% at [StatCounter](http://gs.statcounter.com/os-market-share/desktop/worldwide/chart.php?bar=1&device=Desktop&device_hidden=desktop&statType_hidden=os&region_hidden=ww&granularity=monthly&statType=Operating%20System&region=Worldwide&fromInt=201701&toInt=201701&fromMonthYear=2017-01&toMonthYear=2017-01&csv=1%7C). Moreover, in StackOverflow's 2016 survey, only 0.4% of developers used Windows XP. This change would also block the move to JNA 4.3, would it not?

**Comment by dbwiddis** [comment]
We can argue about global usage, or we can use stats on who actually uses OSHI and what they want. 

If it's easy to backport (I think it is) I don't see any showstoppers.  I don't see any documentation that JNA 4.3 requires Java 8, either.

The cost of backporting is a loss of some JDK efficiencies (I understand the new map classes are faster, for example) but I don't think these are worth considering at the scale we use them.  I wouldn't mind maintaining two versions, either, if someone could point me to best practices for doing that.  My goal is to keep most of the code the same and just use wrappers to simulate Java 8 methods in Java 7.

**Comment by Nadahar** [comment]
Regarding Linux support, OpenJDK 8 still isn't available for Debian 8/Jessie for example. It's available in testing and unstable, and as a backport - but I tried to get it working an a Debian installation maybe 6 months ago and it wasn't easy enough for me to manage it. I could have put more effort into it, but my point is that it isn't readily available for normal users yet, but as I said it probably won't be too long.

Windows XP is my main concern, and if it's 5% or 10% is still a substantial number of users. Remember that because of Microsofts driver signing, there is no drivers available for newer Windows versions for older hardware - so they have no choice. I don't know if the number of *developers* using a given OS is that interesting.

We have tested JNA 4.3, and we've had no issues with Java 7.

**Comment by dbwiddis** [comment]
I've found the [StreamSupport project](https://github.com/streamsupport/streamsupport) which adds the string joining and many other java 8 features to java 7.

**Comment by Nadahar** [comment]
This might not have much point. I just tested on a Windows XP VM and it seems that you rely on methods not available in the Windows XP API anyway:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Error looking up function 'PdhAddEnglishCounterA': Den angitte prosedyren ble ikke funnet (method not found).

	at com.sun.jna.Function.<init>(Function.java:212)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:541)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:518)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:504)
	at com.sun.jna.Library$Handler.invoke(Library.java:220)
	at com.sun.proxy.$Proxy4.PdhAddEnglishCounterA(Unknown Source)
	at oshi.util.platform.windows.PdhUtil.addCounter(PdhUtil.java:66)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.initPdhCounters(WindowsCentralProcessor.java:154)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.<init>(WindowsCentralProcessor.java:101)
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getProcessor(WindowsHardwareAbstractionLayer.java:55)
```

**Comment by henryx** [comment]
At this moment, this is a great work, because a lot of code is written for Java8. A backport has some advantages (support for old architectures) and disadvantages (abandon new features). But, is to keep in mind, abandon new features is not always a disadvantage. For example, according to [this](https://dzone.com/articles/dark-side-lambda-expressions), lambda are very difficult to debug because it isn't really part of the language. Another, for the same reasons exposed, lambda are more slower than e.g. anonymous class especially when are initializated (see [this](http://www.oracle.com/technetwork/java/jvmls2013kuksen-2014088.pdf) ). So, my opinion is to remain to Java 8 code (surprise!), because for me is too late to return back

**Comment by dbwiddis** [comment]
@Nadahar we no longer use those methods -- you're looking at exceptions in 2.6 code.  There are some Vista-plus methods in use but they're not that common.

I just spent an hour (while on a conference call elsewhere) doing the backport as #327.  It's not working yet for some strange conflict on my hash map implementation -- it claims I've got a conflict with the `getOrDefault()` method (which doesn't exist in Java 7).  Trying to figure that out.

**Comment by Nadahar** [comment]
@dbwiddis That's great news 👍

**Comment by dbwiddis** [comment]
It's not good news yet.  Maven won't compile, the error is:
> [ERROR] /Users/danielwiddis/git/oshi/oshi-core/src/main/java/oshi/util/DefaultHashMap.java:[45,14] name clash: getOrDefault(K,V) in oshi.util.DefaultHashMap and getOrDefault(java.lang.Object,V) in java.util.HashMap have the same erasure, yet neither overrides the other

But the Java 7 version of Hash Map doesn't have such a method.  And I've pointed my maven signatures to Java 7 everywhere.   (Well, obviously I've missed one somewhere.)  Peek at my PR and see if you can figure it out!

**Comment by dbwiddis** [comment]
Ah, solved it.  I need to change my JAVA_HOME environment variable before running maven.  

3.5.0-SNAPSHOT should work with Java 7, try it out!

**Comment by YoshiEnVerde** [comment]
The problem is at file **oshi-core/pom.xml**
Lines 106 to 109.
You have the following 4 config statements for the java compiler:

`<maven.compiler.source>1.8</maven.compiler.source>
<maven.compiler.target>1.8</maven.compiler.target>
<maven.compiler.testSource>1.8</maven.compiler.testSource>
<maven.compiler.testTarget>1.8</maven.compiler.testTarget>`

Those are telling Maven to compile and test for Java 8

Also, line 114: `<signature.artifact>java18</signature.artifact>` will throw an error because it's signing the jar with whatever signature algorithm/format is used by Java 8

**Comment by dbwiddis** [comment]
@YoshiEnVerde Those are changed in #327 .  The problem is that Maven uses JAVA_HOME to find which version to run so I had to change that variable, e.g., 
> JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home mvn clean deploy

**Comment by Nadahar** [comment]
@dbwiddis Yes, ```JAVA_HOME``` has caused issues for me too. I didn't see this in time to tell you though.

Wouldn't it be easier to make sure that the code also compiles on Java 8, that is change the method name to something that doesn't conflict?

**Comment by dbwiddis** [comment]
Doh!  I should have realized the name conflict earlier.  I blame Monday

**Comment by dbwiddis** [comment]
OK, #327 updated with non-conflicting class/methods and it compiles just nicely (on Java 8 with compatibility for Java 7).  I need to write some tests for the new code but it should otherwise be ready to merge soon.
