### ISSUE TITLE
§§ #327 may violate the GPLv2 licence §§

### ISSUE THREAD

**Issue by mgmechanics** [oshi/oshi#331]
I am afraid the the fix for issue #327 could violate the GPLv2 licence. This makes it impossible for our project to use OSHI beyond version 3.4 :-(

The Fix for #327 adds a dependency the code of the project "streamsupport" located on sourceforge.net. Please check https://github.com/oshi/oshi/pull/327/files#diff-1b925e6b754fca883c25528931c99e86.

I checked the license of "streamsupport" (which does not provide a LICENCE file so that I had to look in the headers of the code files): https://sourceforge.net/p/streamsupport/code/ci/default/tree/src/main/java/java8/util/StringJoiner.java

--- snip ---
/*
* Copyright (c) 2013, Oracle and/or its affiliates. All rights reserved.
* DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
*
* This code is free software; you can redistribute it and/or modify it
* under the terms of the GNU General Public License version 2 only, as
* published by the Free Software Foundation.  Oracle designates this
* particular file as subject to the "Classpath" exception as provided
* by Oracle in the LICENSE file that accompanied this code.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
* version 2 for more details (a copy is included in the LICENSE file that
* accompanied this code).
*
* You should have received a copy of the GNU General Public License version
* 2 along with this work; if not, write to the Free Software Foundation,
* Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
*
* Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
* or visit www.oracle.com if you need additional information or have any
* questions.
*/
--- snap ---
I am not a lawyer,
Michael

**Comment by dbwiddis** [comment]
Thanks for brining this to my attention.  I'll look into this and make sure it's resolved prior to 3.5 release.  (For the record, 3.4 and 3.4.1 are identical in function; the former is Java 8 without this dependency, the latter is Java 7 using this dependency.)

Worst case, I can write util classes for the Java8 functionality that I use, which is relatively minor.  Why are "free" licenses such a pain?

**Comment by dbwiddis** [comment]
So, after 15 minutes of non-lawyerly reading, I've come to the conclusion that I either have to change OSHI's license to GPL (which I will not do) or get rid of the dependency.   Bleh.

**Comment by dbwiddis** [comment]
\<vent\>
So, after looking at some source code, it appears streamsupport is GPL2 because they took their code directly from the Oracle source which is GPL2.

So I can use that exact code in Java 8 without any license issues, but if someone copies that code with the same license, I can't use the copy....
\</vent\>

**Comment by mgmechanics** [comment]
> So I can use that exact code in Java 8 without any license issues, but if someone copies that code with the same license, I can't use the copy....

I don't think so because when I build the OSHI project the GPL-licenced code is copied in the JAR file. And, for my understanding this is not covered by the "linking exception" because the code is copyed, not linked.

And: The copyright owner is Oracle, I wouldn't tangle with them.

I am not a lawyer. I just hope to help you.

**Comment by dbwiddis** [comment]
I'm not arguing, I'm venting. :)   Oracle wrote it and Oracle can decide how to license it.  All hail Oracle. :)

I've removed the offending code in #332 and am in the process of releasing 3.4.2.  Again, thanks for brining this to my attention.

**Comment by dbwiddis** [comment]
So, a moot point since I've removed streamsupport, but the [project website](https://github.com/streamsupport/streamsupport) lists in the license section:
`GPL2, CE (GNU General Public License, version 2, with the Classpath Exception)`

There is a [License file there as well](https://github.com/streamsupport/streamsupport/blob/master/LICENSE.txt), which outlines this exception:

>     As a special exception, the copyright holders of this library give you
>     permission to link this library with independent modules to produce an
>     executable, regardless of the license terms of these independent modules,
>     and to copy and distribute the resulting executable under terms of your
>     choice

With the caveat:

> only where Oracle has expressly included in the particular source file's header
> the words "Oracle designates this particular file as subject to the "Classpath"
> exception as provided by Oracle in the LICENSE file that accompanied this code."

Those words were in the StringJoiner file you linked.  So I think we would have been okay there.  I'd have to also check the `Function` class but I suspect it's probably there too.

In any case, I've removed a dependency so that's good :)
