### ISSUE TITLE
Various methods from "Sensors" class return "0.0" or "0"

### ISSUE THREAD

**Issue by aldfrarug** [oshi/oshi#340]
Always when i want to try to read cpu voltage, cpu temperature or cpu fan speeds, the method returns "0.0"(cpu voltage and cpu temperature) and "0"(each int from the given array). I used the following Code:

SystemInfo si = new SystemInfo();
Sensors s = si.getHardware().getSensors();
System.out.println(s.getCpuTemperature());

I ripped the code from your class "SensorsTest".
My hardware is as follows:
CPU: Intel 2500k
Motherboard: AsRock H61-VG4

I dont think that i need to write other hardware specifications.

Just saying: CPUID HWMonitor and other applications like MSI Afterburner are also able to read cpu temperature etc.

If I can help you in any way, please contact me via mail(I never use GitHub): aldfrarug@gmail.com

PS: I also tried jHardware, but also there I wasnt able to read cpu temp etc.

**Comment by dbwiddis** [comment]
Reading sensors is a tricky business which is different based on manufacturers and motherboards and requires some very low level cpuid instructions.   I've documented both [in the API](http://oshi.github.io/oshi/apidocs/oshi/hardware/Sensors.html) and in [the FAQ](https://github.com/oshi/oshi/blob/master/FAQ.md#what-api-features-are-not-implemented-on-some-operating-systems) that 

> Windows sensor (temperature, fans, voltage) readings are drawn from Microsoft's Windows Management Instrumentation (WMI) API; however, most hardware manufacturers do not publish these readings to WMI. If a value is not available through the Microsoft API, Oshi will attempt to retrieve values as published by the Open Hardware Monitor if it is running. 

If you are able to run [Open Hardware Monitor](http://openhardwaremonitor.org/), it publishes its results to WMI, which OSHI then reads.  Unfortunately, it would require an excessive amount of work to essentially reproduce all of the various options (and keep them up to date as new hardware is produced).  "The juice is not worth the squeeze."

**Comment by aldfrarug** [comment]
Thanks for the quick reply:)

The solution with the open hardware monitor worked for me. Its quite easy
to let OHM start minimized on startup. So i think because it isnt an issue
i should delete it, right?
However, thanks for helping ^^

Am 22.03.2017 19:34 schrieb "dbwiddis" <notifications@github.com>:

Reading sensors is a tricky business which is different based on
manufacturers and motherboards and requires some very low level cpuid
instructions. I've documented both in the API
<http://oshi.github.io/oshi/apidocs/oshi/hardware/Sensors.html> and in the
FAQ
<https://github.com/oshi/oshi/blob/master/FAQ.md#what-api-features-are-not-implemented-on-some-operating-systems>
that

Windows sensor (temperature, fans, voltage) readings are drawn from
Microsoft's Windows Management Instrumentation (WMI) API; however, most
hardware manufacturers do not publish these readings to WMI. If a value is
not available through the Microsoft API, Oshi will attempt to retrieve
values as published by the Open Hardware Monitor if it is running.

If you are able to run Open Hardware Monitor
<http://openhardwaremonitor.org/>, it publishes its results to WMI, which
OSHI then reads. Unfortunately, it would require an excessive amount of
work to essentially reproduce all of the various options (and keep them up
to date as new hardware is produced). "The juice is not worth the squeeze."

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/oshi/oshi/issues/340#issuecomment-288497069>, or mute
the thread

**Comment by dbwiddis** [comment]
Glad to know the OHM workaround worked for you!
