### ISSUE TITLE
It does not correspond to sandbox of macOS

### ISSUE THREAD

**Issue by yososs** [oshi/oshi#343]
Temperature can not be obtained with an application created with sandbox enabled with macOS.

Adding the following permission information when creating a native bundle will work on the macOS sandbox, but will not pass the Apple Store review.

>  		<key>com.apple.security.temporary-exception.sbpl</key>
> 		<array>
> 			<string>(allow iokit-open (iokit-user-client-class "AppleSMCClient"))</string>
> 		</array>
>

**Comment by dbwiddis** [comment]
I'm not sure what this means or what I can do about it?

**Comment by yososs** [comment]
To think about this as a problem, you need to be careful about security and compatibility with macOS.

In Java applications, you can create applications compatible with Mac sandbox by using Java Packager.

**Comment by dbwiddis** [comment]
So what changes need to be made to the project?  Is this something that just needs to be documented for anyone building a project that includes OSHI?

**Comment by yososs** [comment]
I am investigating the solution method and I can only share the problem at this stage. If I find a solution, I will share it, please wait.

**Comment by yososs** [comment]
I requested Apple to reconsider, but unfortunately I could not pass the review.

```
		<key>com.apple.security.temporary-exception.iokit-user-client-class</key>
  		<string>AppleSMCClient</string>
```

Reject reason is "Hardware Compatibility", but it was refused by the decision of Apple Security Core team.

The direct way to access AppleSMC to acquire temperature seems to be very difficult to pass the Apple App Store review.

Whether there is another way to get temperature on macOS was not found in my survey.

**Comment by dbwiddis** [comment]
So, what (if anything) do we need to do?

**Comment by trejkaz** [comment]
As a step 1, is there some way to run the tests in the sandbox? Then it would at least give some visibility to the sorts of things which would not be permitted. At the moment, it's a bit hard to tell which things are OK to call and which things aren't.

**Comment by yososs** [comment]
Unless Apple 's policy is changed, it is considered that functions dependent on AppleSMCClient can not be operated in sandbox.

In this project what can be done about this problem,
  I can only think of describing that "Apple's sandbox review will probably be rejected."

**Comment by dbwiddis** [comment]
So this boils down to a choice of "OSHI can provide macOS sensor readings" or "OSHI can be embedded in an app on the app store"?

**Comment by dbwiddis** [comment]
I'm all for updating the docs but would like someone who knows what they're talking about to do that. :)

**Comment by dbwiddis** [comment]
Closing this as it seems to be a macOS specific problem developing apps for the app store.  There is no built-in way of getting this information in macOS, and various other command-line utilities all access SMC the same way OSHI does.  So the only way to get this to work would be to remove the temperature functionality.

As a cross-platform project, that's a non-starter.   It would be easy to fork OSHI and include only macOS code (minus SMC code) and use that as a basis for an App Store product, and I'd suggest that as the way forward.
