### ISSUE TITLE
Feature request: Could OSHI provide the number of open connections?

### ISSUE THREAD

**Issue by mgmechanics** [oshi/oshi#346]
Could OSHI provide the number of open connections? We need only the number, nothing more. TCP is most important.

But: Our servers will open A LOT of connections, sometimes even more than Integer.MAX_VALUE. So counting the lines of /proc/net/tcp{,6} isn't an option because it is incredible slow and takes a huge amount of CPU.

I researched that there is /proc/net/sockstat{,6}. These numbers would fit.

**Comment by dbwiddis** [comment]
The problem with relying on `sockstat` is that it's not cross-platform and doesn't seem consistent with the other network command lines (e.g., `netstat` or `lsof`).  If we were to implement this we would probably want to make a `Connection` class with at least a protocol enum, and source/destination IP/port info but this appears to be something you really want to avoid!

I guess for simply counting established connecctions, `netstat -s` gives sufficient information on all platforms and can be a fallback if `/proc/net/sockstat` isn't available.

On Windows, WMI has the `Win32_PerfFormattedData_Tcpip_TCPv4`(and v6) class with `ConnectionsEstablished` which would probably be preferred to the netstat output.

**Comment by dbwiddis** [comment]
Looks like the `ss -s` command does essentially the same thing as reading the sockstat file.

>        -s, --summary
>               Print summary statistics. This option does not parse socket lists obtaining summary from various sources. It is  use‐
>               ful when amount of sockets is so huge that parsing /proc/net/tcp is painful.
>

**Comment by dbwiddis** [comment]
So I've been musing over this request and have concluded:
- If I add this to OSHI, I will add the entire list of open connections (from `netstat` or `lsof` or similar native code) including source/destination IP, port, and protocol.  That in itself is a reasonable feature request.
- I do not intend to provide the "reduced capability" to just count the connections as you've requested.   OSHI provides enough util classes for you to easily read/parse files on your own if you want that in your own project.

**Comment by dbwiddis** [comment]
Closing this after almost a year of thinking about it.  As in my previous comment, I see no reason to implement the reduced "count" functionality.  There are multiple trivial command-line options that can be parsed for the information for those who need it for limited OS's.   As for the full functionality, I don't see any added value to sticking the output of `netstat` and friends into Java objects.

**Comment by dbwiddis** [comment]
You can certainly use OSHI's util classes like `ExecutingCommand` to return a `List<String>` of the command line output, and then iterate/parse it.  My point above was that there would be little value to creating an entire object to represent each line of the string.

That said, if you'd like to create such an object and make it cross-platform I'd be happy to merge it.
