### ISSUE TITLE
Sensors (temperature, fan speeds, voltage) don't return values on RPi2

### ISSUE THREAD

**Issue by cweitkamp** [oshi/oshi#347]
I am using OSHI with Systeminfo binding for openHAB2. My Setup of openHAB2 framework is on a RPi2 with raspian operating system. The OSHI library returns no values for Sensors (temperature, fan speeds, voltage) - fan speed is obvious because my RPi2 has no fan.

It is possible to read those values on my raspbian with the following two shell commands. I am really sure that they can be read somehow by the OSHI library too.
```
pi@raspberry-openhab:~ $ vcgencmd measure_temp
temp=37.9'C
```
and
```
pi@raspberry-openhab:~ $ vcgencmd measure_volts
volt=1.3125V
```
More info can be found here: [RPI vcgencmd usage](http://elinux.org/RPI_vcgencmd_usage).

Some further research shows that cpu temperature can be found in this file:
```
pi@raspberry-openhab:~ $ cat /sys/class/thermal/thermal_zone0/temp
37932
```

**Comment by dbwiddis** [comment]
OSHI currently checks /sys/class/hwmon/hwmon path. I can add a backup search if that doesn't exist.

**Comment by cweitkamp** [comment]
Sounds good. If that is possible it would be very much appreciated. Let my know if I can help any further.

The /sys/class/hwmon/hwmon path definitely doesn't exist on raspbian.

**Comment by dbwiddis** [comment]
You can help by submitting the PR! :)

Rather than just band-aid raspbian I'm trying to research how to actually find the appropriate paths.   The current OSHI code is based on [this sysfs documentation](https://www.kernel.org/doc/Documentation/hwmon/sysfs-interface).  It implies the source code for `lm-sensors` version 3.0 or earlier may identify where to look.

**Comment by cweitkamp** [comment]
Yes, I like to do that.

Maybe the needed information for temperatures can be found in [this sysfs-api documentation](https://www.kernel.org/doc/Documentation/thermal/sysfs-api.txt).

**Comment by dbwiddis** [comment]
Nice find but that just confirms the `/sys/class/thermal/thermal_zone[0-*]/temp` path.  Which is probably good enough for temp... looks like it hints at possible fans as well at `/sys/class/thermal/cooling_device[0-*]` if the `type` is "fan".

Anyway... I'll let you run with this.

**Comment by cweitkamp** [comment]
PR [#354](https://github.com/oshi/oshi/pull/354).

First attempt: Added additional path for reading temperature. I am happy to hear feedback.

Something to point out:
- This PR contains only the additional path for temperature.
- The `/sys/class/thermal/cooling_device[0-*]` information cannot help. You can find the current cooling state of a cooling device. The value can be any integer numbers between 0 and max_state. But I don't know what that number indicates. Obviously no information about the current `rpm` of a fan which is needed for this library.
- I couldn't find anything about voltage, yet.

**Comment by dbwiddis** [comment]
Is your PR ready to merge? It looks good to me but I don't have the ability to test it.

**Comment by cweitkamp** [comment]
Probably yes. Reading temperature works fine. The other values are still missing. I didn't find any information, yet.

I attached a screenshot showing my openHAB2 setup. I integrated my code into the Systeminfo binding and let it run for several days. If you have a look at the chart you see several changes of the measured cpu temperature.

![bildschirmfoto vom 2017-05-21 12-20-45](https://cloud.githubusercontent.com/assets/5131747/26283057/48151eb0-3e20-11e7-9ade-75f2566c2fef.png)

**Comment by MasterToney** [comment]
Hey! Stumbled across this issue while reading about the SystemInfo Binding from openhab.
Although it has been a while but any chance that this gets merged some time in the future?
I would greatly appreciate it :)

**Comment by dbwiddis** [comment]
I can merge this into SNAPSHOT if you're able to test it

**Comment by dbwiddis** [comment]
Actually... looks like this was already merged?  What's the ask here?

**Comment by MasterToney** [comment]
was it? sorry then i didn't noticed that, just saw it marked as still open and no comment of it getting merged so i assumed i still wasn't. Wrong default assumption  ^^
I'll check wich version the openhab binding uses, with my fresh install it clearly doesn't work ^^.
Anyways, thanks for the quick reply!

**Comment by dbwiddis** [comment]
It looks like we merge the temperature but not the other sensors, so if you can submit a PR for those it would be great.

**Comment by cweitkamp** [comment]
We merged a solution for reading the CPU temperature on Linux devices. We updated  the oshi  version of the systeminfo binding to 3.4.3 afterwards. This version includes the new feature (See https://github.com/openhab/openhab2-addons/pull/2449). This version is available  in the OH2 snapshot.

**Comment by MasterToney** [comment]
Ah, wonderful, have to check it out this weekend, I guess this issue can be closed then?

**Comment by dbwiddis** [comment]
Leaving this open until we figure out the other sensors than temperature.  My son just got a Rpi and I'm trying to bribe him to figure this out for me.  First he needs to save up allowance to buy a case and peripherals. 😁

**Comment by dbwiddis** [comment]
Closing this as the requested issue has been solved a year ago and my note-to-self to leverage my son's Rpi never materialized. :)
