### ISSUE TITLE
Cannot Fetch Model in Raspbian/Ubuntu Mate for Raspberry Pi 3 Model B

### ISSUE THREAD

**Issue by choudharypranay** [oshi/oshi#349]
For Ubuntu Mate:
pi@pi-board:~/nix$ uname -a
Linux pi-board 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l armv7l armv7l GNU/Linux

getHardware().getComputerSystem().getModel() = **unknown**
getHardware().getComputerSystem().getBaseboard().getModel() = **unknown**
getHardware().getProcessor().getModel() = **?**

For Raspbian:
pi@raspberrypi:~/nix $ uname -a
Linux raspberrypi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux

getHardware().getComputerSystem().getModel() = **unknown**
getHardware().getComputerSystem().getBaseboard().getModel() = **unknown**
getHardware().getProcessor().getModel() = **?**

**Comment by dbwiddis** [comment]
On Linux, OSHI populates these values from files in `/sys/devices/virtual/dmi/id/` (specifically `product_name` and `board_name`) and `/proc/cpuinfo`.  Where else is this information available on Raspberry Pi?

**Comment by choudharypranay** [comment]
On Raspbian latest version (March 2018): 

```
**# ls -l /sys/devices/virtual/dmi/id**
ls: cannot access '/sys/devices/virtual/dmi/id': No such file or directory

**# cat /proc/cpuinfo**
processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: BCM2835
Revision	: a02082
Serial		: 00000000dba55ec7
```

# cat /proc/cpuinfo
processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: BCM2835
Revision	: a02082
Serial		: 00000000dba55ec7

**Comment by choudharypranay** [comment]
lshw is able to fetch the details 

```
#lshw -C system
raspberrypi                 
    description: ARMv7 Processor rev 4 (v7l)
    product: Raspberry Pi 3 Model B Rev 1.2
    serial: 00000000dba55ec7
    width: 32 bits
    capabilities: smp

```

**Comment by dbwiddis** [comment]
Seems `cat /sys/firmware/devicetree/base/model` works, as does `cat /proc/device-tree/model`

**Comment by Sami32** [comment]
Oh...​you seem right that `/sys/devices/virtual/dmi/id/` is not in Ubuntu Mate:
https://ubuntu-mate.community/t/missing-dependencies-of-welcome-in-18-04b1/16347/9
