### ISSUE TITLE
oshi 4.3.2 dependencies jna 4.3.0 in springboot start fails

### ISSUE THREAD

**Issue by FanError** [oshi/oshi#351]
java.io.FileNotFoundException: C:\Users\.gradle\caches\modules-2\files-2.1\net.java.dev.jna\jna-platform\4.3.0\112d185ecfff7a3e6c33a114c566f9bf6f832244\lib\jna.jar

https://github.com/spring-projects/spring-boot/issues/8623
https://github.com/java-native-access/jna/issues/776

**Comment by dbwiddis** [comment]
The latest snapshot depends on JNA 4.4.0.  Can you test?

**Comment by dbwiddis** [comment]
Er, nevermind, I see this will be fixed in the next JNA release.  Which I'll update to before the next OSHI release.

**Comment by FanError** [comment]
finally, I reproduce this problem in minimum test environment

https://github.com/spring-projects/spring-boot/issues/9107

**Comment by dbwiddis** [comment]
This is a bug in JNA 4.3 and 4.4.  It will be fixed in JNA 4.5, which I'll leave this issue open to track until it's complete.  In the meantime, if you don't need Java 7, you can use OSHI 3.4.0 to avoid this problem.

**Comment by dbwiddis** [comment]
Looks like JNA 4.5.0 has been released.  I'll update OSHI's dependencies and release 3.5.0 soon.

**Comment by dbwiddis** [comment]
The SNAPSHOT has been updated with JNA 4.5.0 dependency. Can you test to see if this issue is resolved?
