### ISSUE TITLE
Feature request: detect proxy settings

### ISSUE THREAD

**Issue by lundefugl** [oshi/oshi#352]
Is it possible to get the proxy settings in "NetworkParams" ?
Direct in java it is possible to set the option "java.net.useSystemProxies" and read it over class "ProxySelector". 
But after this: it's not possible to deactivate the global proxy usage (has a internal cache ?).

Therefore we need a solution to detect it without set this option.

**Comment by dbwiddis** [comment]
I assume by `ProxySelector` you're referring to [this code](http://stackoverflow.com/questions/4933677/detecting-windows-ie-proxy-setting-using-java/4933746#4933746)?

**Comment by dbwiddis** [comment]
[This thread](http://stackoverflow.com/questions/8078590/java-http-proxy-setting-is-cached-until-jvm-restart) seems to discuss the caching.

**Comment by YoshiEnVerde** [comment]
There's two problems with this:

1. The Standard Java version, without any extra compile dependencies, will not be able to distinguish between a Direct Connection and a PAC (as explained in the second answer of that SO thread)

2. The Compile Library dependant version, using the active fork of Proxy Vole by Markus Bernhardt at [https://github.com/MarkusBernhardt/proxy-vole](url), has the chaching problem **and** doesn't seem to work on every platform supported by OSHI. 
More so, it seems to be a waste of resources to add dependency to _a whole proxy management library_ for just one single minor functionality.

Wouldn't it be easier for your project to just add both dependencies? Then use OSHI for the general info, and ProxyVole for the proxy data?

**Comment by YoshiEnVerde** [comment]
Directly from Oracle's documentation on how proxies work for Java ([https://docs.oracle.com/javase/8/docs/api/java/net/doc-files/net-properties.html](url)), the system property **java.net.useSystemProxies** is only checked on JVM start up, as part of the JVM initialization process.

As such, no, there's just no way to _uncache_ that setting, or move from one to another, without restarting the JVM

**Comment by dbwiddis** [comment]
It's been almost a year. I'm going through the issues with a critical eye.  This seems generally impossible or at least impractical, to support.  For those few who need this functionality, there are other alternatives available.
