### ISSUE TITLE
GetSystemUptime is giving 32 bit result on a 64-bit operating system

### ISSUE THREAD

**Issue by justingh** [oshi/oshi#355]
// Save Windows version info for 32 bit/64 bit branch later
    private static final byte majorVersion;
    static {
        OSVERSIONINFO lpVersionInfo = new OSVERSIONINFO();
        // GetVersionEx() isn't accurate for Win8+ but is sufficient for
        // detecting versions 5.x and earlier
        if (!Kernel32.INSTANCE.GetVersionEx(lpVersionInfo)) {
            majorVersion = lpVersionInfo.dwMajorVersion.byteValue();
        } else {
            majorVersion = 0;
        }
    }

**Comment by dbwiddis** [comment]
Can you tell me your actual OS and what OSHI reports?

**Comment by justingh** [comment]
WIN7(X64)  and Windows server 2012，I use SystemInfoTest to track the problem

**Comment by dbwiddis** [comment]
Where does OSHI tell you your OS is 32-bit?

**Comment by justingh** [comment]
class  WindowsCentralProcessor


    // Save Windows version info for 32 bit/64 bit branch later
    private static final byte majorVersion;
    static {
        OSVERSIONINFO lpVersionInfo = new OSVERSIONINFO();
        // GetVersionEx() isn't accurate for Win8+ but is sufficient for
        // detecting versions 5.x and earlier
        if (!Kernel32.INSTANCE.GetVersionEx(lpVersionInfo)) {
            majorVersion = lpVersionInfo.dwMajorVersion.byteValue();
        } else {
            majorVersion = 0;
        }
    }

**Comment by dbwiddis** [comment]
OK, looks like I didn't do this, which is apparently required for the [GetVersionEx()](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724451(v=vs.85).aspx) function to work...

> Before calling the GetVersionEx function, set the dwOSVersionInfoSize member of the structure as appropriate to indicate which data structure is being passed to this function.

**Comment by dbwiddis** [comment]
Well, passing the right structure size gets a zero return value but still didn't get the version number on my Win7(x64).   So I'll just resort to the simpler `getVersion()`.  Don't know why I didn't do that the first time!

**Comment by justingh** [comment]
But    lpVersionInfo.dwMajorVersion.byteValue()  result is 6,  Why if the condition is
if (!Kernel32.INSTANCE.GetVersionEx(lpVersionInfo)) ，Not for 
 if (Kernel32.INSTANCE.GetVersionEx(lpVersionInfo))

**Comment by dbwiddis** [comment]
My `dwMajorVersion` still returned 0 even when the function succeeded (0 return value which went in the first branch of the conditional).  I don't know why, but the simpler `getVersion()` works with a lot less overhead.

I've simplified that whole block to:
```
private static final byte majorVersion = Kernel32.INSTANCE.GetVersion().byteValue();
```

**Comment by justingh** [comment]
well，I am from China, English is not very good, thank you to provide me with a learning example

**Comment by YoshiEnVerde** [comment]
I went and checked the commits to make sure, and I was right:
That code was there as part of the compatibility fix for old versions of Windows (WinXP and earlier)

**Comment by dbwiddis** [comment]
Yep, but the code was broken. It's fixed now, in the snapshot at least.

**Comment by justingh** [comment]
The code is not resolved  in the snapshot

**Comment by dbwiddis** [comment]
Let me try to be clear on the problem here.

You are reporting that `getSystemUptime()` is still rolling over at 32 bits (your system has been up > 49 days and you're getting smaller numbers).  The 32 vs. 64 bit branch is dependent on the result of the Windows Kernel32 `GetMajorVersion()` function being >= 6. 

So one of two things is happening here:  `GetMajorVersion()` is returning something < 6, or GetTickCount64() is prematurely rolling over.

Do you have the ability to download and execute the source code, and add some debug code to help figure out what's going on here?

**Comment by justingh** [comment]
I have opened the  new source code with IDEA, The code is correct， thanks
