### ISSUE TITLE
Device mapper support on Linux

### ISSUE THREAD

**Issue by darinhoward** [oshi/oshi#360]
Scenario: 

FileSystem.getFileStores() returns a LVM fs: 
`/ (Local Disk) [ext4] 292.6 MiB of 5.3 GiB free (5.4%) is /dev/mapper/ubuntu--vg-root and is mounted at /`

HardwareAbstractionLayer.getDiskStores() returns the corresponding drive the above fs is located: 
`/dev/dm-0: (model: Unknown - S/N: Unknown) size: 5.9 GB, reads: 10129 (158.3 MiB), writes: 15695 (668.0 MiB), xfer: 9236 ms`

But there is no way to link the 2 items together. 

Running ` ls -l /dev/mapper` shows: 
```
lrwxrwxrwx 1 root root       7 May 12 10:19 ubuntu--vg-root -> ../dm-0
```
Which provides the link between the diskstore and filestore. 

Suggest adding in logic to check `/dev/mapper/' - add attribute to diskstore or filestore object.

**Comment by dbwiddis** [comment]
Disk Stores refer to the actual hardware, and are linked to partitions.  Partitions should have a mount point allowing a linking to file stores.  Is that linkage possible in your case?

I don't want to add an entirely new attribute focused on a very narrow capability but if there's some way to pass this information into the existing connections that'd be welcome.

**Comment by darinhoward** [comment]
In the example, there are no partitions being returned for the diskstore `/dev/dm-0`. I'm not familiar with how oshi pulls all this but will take a look.

**Comment by darinhoward** [comment]
After looking at the code I have a couple ideas: 

1) Add new attribute 'mappedVolume' to OSFileStore that provides this new value. 
2) Return an additional OSFileStore object from getFileStores() with the alternate volume name. 

Thoughts?

**Comment by dbwiddis** [comment]
Ah, this looks similar to [what I had to do with OS X](https://github.com/oshi/oshi/blob/f81c39935a8befd1b9568854d711a4494d8911f4/oshi-core/src/main/java/oshi/hardware/platform/mac/MacDisks.java#L89) to handle fileVault encryption and Fusion Drives.

The end state would replace the mount point `/` in your `FileSystem` output with something like `Mapped Device: dm-0`.

**Comment by dbwiddis** [comment]
We were typing at the same time.  I favor your option 1 but don't think we necessarily need a new attribute for a mapped volume (or logical volume) if it makes sense to replace the "Mount Point" with that information.    If, however, you think there's value in separating mount point from this value, I wouldn't object (and would modify the above referenced OS X code to match).

**Comment by darinhoward** [comment]
Added a pull request - https://github.com/oshi/oshi/pull/361
