### ISSUE TITLE
API to read a process' environment variables?

### ISSUE THREAD

**Issue by jjYBdx4IL** [oshi/oshi#369]
For linux, this is easy (/proc/<pid>/environ). But it would be nice to have something like that in a cross-platform manner, esp for Windows. I tag and find stray processes in maven builds by giving them specific environment variables that let me identify them somewhat reliably.

**Comment by dbwiddis** [comment]
This is [far too complex](https://stackoverflow.com/questions/1202653/check-for-environment-variable-in-another-process) for me to even want to do for Windows.

But the skeleton is there for getting the process group if someone wants to build on it.

**Comment by jjYBdx4IL** [comment]
See also https://github.com/java-native-access/jna/issues/820

There is an open source windows process manager app written in C that should provide call the code that is needed, it just cannot be simply copy and pasted because it is under the GPL.

**Comment by dbwiddis** [comment]
I'm closing this as it's pretty much out of scope for OSHI, and nobody's commented on this in over 2 years.

**Comment by basil** [comment]
For what it's worth, extending `OSProcess` with `List<String> getArguments()` and `Map<String, String> getEnvironmentVariables()` could possibly allow the Jenkins project to use OSHI to do process management. Implementing these methods is difficult, but Jenkins already has MIT-licensed, battle-tested implementations for Linux, Windows, macOS, Solaris, and AIX. This code is outside of the core focus of the Jenkins project, and perhaps it might find a better home in a project like OSHI, if FreeBSD and OpenBSD support were added.

One complication is that the Windows implementation for Jenkins is written in C++ code with JNI, not JNA. The code is in [`envvar-cmdline.cpp`](https://github.com/kohsuke/winp/blob/b2dd42c9e9b7f2924a093645251db3368e345a59/native/envvar-cmdline.cpp). Most of the code seems straightforward, but the calls to `ZwQueryInformationProcess` might be tricky to port to JNA. Still, I don't get the sense that this would be prohibitively difficult for someone with Windows and JNA experience. (I personally have never done Windows development.)

> it's pretty much out of scope for OSHI

All of this is to say that if you ever change your mind about this being out of scope for OSHI, I'd be happy to help with the Unix parts, and I don't think the Windows parts would be prohibitively difficult for someone with Windows and JNA experience.

**Comment by dbwiddis** [comment]
Reopening if there is interest.  PRs are welcome.  :)

**Comment by dbwiddis** [comment]
FWIW the Zw-prefixed windows functions are internal.  There are usually API equivalents.  If there is existing JNI code I can probably port it.

**Comment by dbwiddis** [comment]
OK, the `ZwQueryInformationProcess` calls are problematic, not because it's difficult to port to JNA (it's not) but because:
> `ZwQueryInformationProcess` may be altered or unavailable in future versions of Windows. Applications should use the alternate functions listed in this topic.

Fortunately it looks like another user has answered the SO post I linked above with a full working C++ implementation that does not include that function. Much of what it requires is already in JNA or in OSHI already.  So the Windows port looks a lot more doable to me now than it did 4 years ago.

Now if I could find the time... :)
