### ISSUE TITLE
Could not initialize class oshi.jna.platform.linux.Libc$Sysinfo

### ISSUE THREAD

**Issue by Kyle-Wolfe** [oshi/oshi#370]
ERROR oshi.hardware.platform.linux.LinuxCentralProcessor - Failed to get uptime from sysinfo. Could not initialize class oshi.jna.platform.linux.Libc$Sysinfo

running on Ubuntu 14.04

This is probably caused by a mismatched version or missing package, but I am not sure which one.  If you could let me know what packages I should be looking at and what their desired version is that would be very helpful.

**Comment by dbwiddis** [comment]
This looks similar to [this reported bug](https://bugzilla.redhat.com/show_bug.cgi?id=1441998), which indicates the root error (in that case) is:

> /lib64/libc.so.6: version `GLIBC_2.14' not found

It looks like there may be a mismatch between the java version you are using and the C library on your system.  #338 may be relevant as it's the same error message but CentOS rather than Ubuntu -- which means the fix may be easier (upgrading GLIBC).

**Comment by Kyle-Wolfe** [comment]
>$java -version
java version "1.7.0_131"

>$ldd --version
ldd (UBUNTU EGLIBC 2.19-Oubuntu6.11) 2.19

I am unsure if these match, and I do not know how to update GLIBC, I keep coming across it being called libc6 and apt says that libc6 is the newest version.

**Comment by dbwiddis** [comment]
Sounds like that part's up to date.   What versions of OSHI and JNA are you using? Are you stuck on Java 7 or can you try Java 8?  Would be interesting for you to check version 4.3.0 (Java 8) which used an older JNA dependency than 4.3.2.   Can you also check the snapshot version?

**Comment by Kyle-Wolfe** [comment]
I am not sure what version of OSHI or JNA I am running, not sure how to check that.  I am updating to java 8 now

**Comment by dbwiddis** [comment]
The version of both should be identified in the jar you downloaded, or the maven coordinates you specify.  You may have a mismatch with a newer JNA/older OSHI or vice versa or something similar.

**Comment by Kyle-Wolfe** [comment]
updating to java 8 fixed the issue

**Comment by dbwiddis** [comment]
Excellent!
