### ISSUE TITLE
Process.getBytes (Written & Read) gives the same output

### ISSUE THREAD

**Issue by Ben-Mark** [oshi/oshi#373]
Possible bug?
Or am I doing something wrong?
My only goal in this thread is to capture the disk usage of a specific process
Problem: 

- System.out.println(process.getBytesRead());
- System.out.println(process.getBytesWritten());

give the same exact output and not close to what is displayed on the task manager

Code for scenario recreation:

```
	private static void main(String [] argh) throws InterruptedException {
		OSProcess process;
		long currentTime,previousTime = 0,timeDifference;
		double cpu;
		int pid = 1572; <---  determin which proccess you want to track, (run tasklist in your cli)
		SystemInfo si = new SystemInfo();
		OperatingSystem os = si.getOperatingSystem();
		CentralProcessor processor = si.getHardware().getProcessor();
		int cpuNumber = processor.getLogicalProcessorCount();
		boolean processExists = true;
		while (processExists) {
			process = os.getProcess(pid);
			if (process != null) {		
				System.out.println(process.getBytesRead()); ///////////////
				System.out.println(process.getBytesWritten());/////////////Both are the same...
				Thread.sleep(1000);
			} else {
				processExists = false;
			}
		}
	}
```

**Comment by dbwiddis** [comment]
I've checked the code and can't see how they'd be the same.   Source data would be from WMI which you can check via command line:
`wmic path win32_process get processid,readtransfercount,writetransfercount`
