### ISSUE TITLE
Are there any plans to do a minor release with updated dependencies?

### ISSUE THREAD

**Issue by Nadahar** [oshi/oshi#376]
We're having some problems (JNA fatal error - ```EXCEPTION_ILLEGAL_INSTRUCTION```) that seems to be caused by conflicting JNA versions. We use JNA 4.4.0 as a dependency while oshi 3.4.2 has JNA 4.3.0 as its dependency - which means that we've had to ```<exclude>``` oshi's JNA dependency in our POM. JNA has been updated in 855460b5c908c4f91d8739b6647ea32d8519d008 but no release has been made since then. We can't downgrade JNA to 4.3.0 because of other issues.

Are there any plans to do a release in the foreseeable future?

**Comment by dbwiddis** [comment]
I had planned on waiting for JNA 4.5.0 because of #351 but can push something out earlier if needed.  Give me a week or two.

**Comment by Nadahar** [comment]
Great, thank you 👍

**Comment by dbwiddis** [comment]
Just pushed 3.4.3.

**Comment by Nadahar** [comment]
@dbwiddis Great, thanks a lot 😄
