### ISSUE TITLE
Add OS bitness to OperatingSystem

### ISSUE THREAD

**Issue by Nadahar** [oshi/oshi#377]
We're currently using some more or less "hackish" ways to determine OS bitness that isn't completely reliable. It would be great if OSHI could supply this information, for example with ```OperatingSystem.getBitness()```.

This is useful/necessary to know when launching external programs where the binary is different depending on the OS bitness (common under Windows) or other similar situation where decisions have to be made based on the OS bitness as opposed to the JVM bitness which is easily available through ```System.getProperty("os.arch")```.

It could also be useful to be able to inform the user if a 32 bit JVM is being used on a 64 bit OS, which severely limits virtual address space for memory mapping.

Be aware that Windows is "lying" in many circumstances because it is "simulating" a 32 bit environment for 32 bit processes, so a way to determine the bitness that "gets around" this is needed for Windows. I think it should be more straight forward for other OSes. A partial solution can be found [here](http://mark.koli.ch/reliably-checking-os-bitness-32-or-64-bit-on-windows-with-a-tiny-c-app), but I'm not sure how JNA is handling this - if making calls with JNA when using a 32 bit JVM on a 64 bit OS will be seen from Windows as a 32 bit or 64 bit "source", but my guess is that it will be seen as 32 bit. In that case, determining "IsWow64Process" could be the key to differentiate between a "real" 32 bit environment and a simulated one. If the JVM is 64 bit, the OS has to be 64 bit, so that's the easy case.

**Comment by Nadahar** [comment]
@dbwiddis Great, thanks :+1:

**Comment by dbwiddis** [comment]
Only took me a year. :D

**Comment by Nadahar** [comment]
Better late than never :wink:
