### ISSUE TITLE
Possible to add CPU Socket count?

### ISSUE THREAD

**Issue by sfriberg** [oshi/oshi#379]
It is great to be able to separate physical cores (cores) and logical cores (hardware threads) #100, but it would also be interesting if it was possible to determine the number of actual CPUs in the system (sockets).

On Linux the following would extract that information from cpuinfo.

cat /proc/cpuinfo | grep "physical id" | awk '{ print $4 }' | sort | uniq | wc -l

Not sure if the other supported OS versions are able to provide the same information?

**Comment by sfriberg** [comment]
Just spotted #353 so closing this as a it is a duplicate.

**Comment by dbwiddis** [comment]
Feel free to submit a PR against the other issue!  This one shouldn't be too hard, I just don't have the time for it now.
