### ISSUE TITLE
getSystemUptime returns negative value

### ISSUE THREAD

**Issue by mehranjodavi** [oshi/oshi#383]
getSystemUptime method on CentralProcessor interface returned negative value when i run my code in Microsoft Windows Server 2008 R2 SP1 7601.
I realize that this value is not correct value in comparison to real system up time value.
Why this value returned ?

**Comment by dbwiddis** [comment]
What is the value? What should it be?

**Comment by mehranjodavi** [comment]
I think it should always be a positive value but it's a negative value that moving to zero when I call it chronologically.
The method works fine in win 7 and 10 but it's not like that in windows server.

**Comment by dbwiddis** [comment]
The negative value sounds like 32-bit rollover, but 2008 R2 should be 64 bit and match the Windows 7 version number.

OSHI pulls that result straight from JNA's [`Kernel32.getTickCount()`](http://java-native-access.github.io/jna/4.4.0/javadoc/com/sun/jna/platform/win32/Kernel32.html#GetTickCount--) or [`Kernel32.getTickCount64()`](http://java-native-access.github.io/jna/4.4.0/javadoc/com/sun/jna/platform/win32/Kernel32.html#GetTickCount64--) method as applicable.  

The 32-bit version returns an `int` that we divide by 1000; we could always cast to long to do the "unsigned" version of it before the division and double the rollover time period from 49.7 days to 99.4 days.  But I'm curious why it's not using the 64 bit call.

**Comment by mehranjodavi** [comment]
Do you have any suggestion that i can fix it ?

**Comment by dbwiddis** [comment]
Rebooting every 49.7 days will fix it :) :) 

I don't have enough information yet to know exactly what's going on here.  What are the exact numbers you are seeing and expecting?  What is JNA seeing for your major version number?

**Comment by dbwiddis** [comment]
Also adding the value of Max_Integer/1000 should give you the expected result if your up time is between 49.7 and 99.4 days.

**Comment by mehranjodavi** [comment]
major version always is 0.
i figure out below if statement code always evaluate as false then else statement runs.

OSVERSIONINFO lpVersionInfo = new OSVERSIONINFO();
// GetVersionEx() isn't accurate for Win8+ but is sufficient for
// detecting versions 5.x and earlier
if (!Kernel32.INSTANCE.GetVersionEx(lpVersionInfo)) {
            majorVersion = lpVersionInfo.dwMajorVersion.byteValue();
} else {
            majorVersion = 0;
}
