### ISSUE TITLE
Add getOpenFiles() to processes?

### ISSUE THREAD

**Issue by Space2Man** [oshi/oshi#387]
Hi,

is it possible to add a function to get the current number of open files for a process into OSHI?

Thank you for this great library!

Best regards,

    Space

**Comment by dbwiddis** [comment]
Windows: Get `HandleCount` from existing WMI process query
Mac OS and probably all Unix flavors: `lsof -p <pid>`
Linux: count file descriptors in `/proc/<pid>/fd`.

**Comment by seancarroll** [comment]
Does it make sense to follow the established pattern and turn OSProcess into an interface with an abstract class with getOpenFiles as an abstract method?

**Comment by dbwiddis** [comment]
I envisioned this as a new field/method on the existing class.  There's no added cost in Windows and the Linux cost is trivial.  If we want to go with a new pattern then we need to be able to "refresh" all the other attributes as well.  See discussion in #310.
