### ISSUE TITLE
CentOS 6.7: getProcesses(0, null) does not return

### ISSUE THREAD

**Issue by Space2Man** [oshi/oshi#388]
Hi,

I am writing some groovy scripts to monitor processes and their CPU / memory usage. This works  fine on my Windows system but today I wanted to test on some CentOS 6.7 system. Basically I am running the following code:

```si = new SystemInfo()
os = si.getOperatingSystem()
log.info("Fetching osProcesses from ${os}")
def osProcesses = os.getProcesses(0, null)
log.info("Fetching osProcesses complete")
```

The last message in logfile is

`Fetching osProcesses from GNU/Linux CentOS 6.7 (Final) build 2.6.32-573.26.1.el6.x86_64`

How can I debug this? Or is this a  known issue?

Thanks a lot and best regards,

Space

**Comment by Space2Man** [comment]
FYI: I did run the command with `strace -f` and now I am wondering what caused the SIGSEGV ...

```4104  open("/proc/63302/status", O_RDONLY) = 16
4104  read(16, "Name:\tsshd\nState:\tS (sleeping)\nT"..., 8192) = 891
4104  close(16)                         = 0
4104  open("/proc/63304/stat", O_RDONLY) = 16
4104  read(16, "63304 (bash) S 63302 63304 63304"..., 8192) = 204
4104  close(16)                         = 0
4104  open("/proc/63304/status", O_RDONLY) = 16
4104  read(16, "Name:\tbash\nState:\tS (sleeping)\nT"..., 8192) = 894
4104  close(16)                         = 0
4104  write(1, "11:23:38.731 [Timer-0] INFO  com"..., 103) = 103
4104  write(8, "18/Jul/2017 11:23:38,731- INFO  "..., 79) = 79
4104  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x8} ---
4104  rt_sigreturn()                    = 0
4104  lseek(6, 4888927, SEEK_SET)       = 4888927
4104  read(6, "PK\3\4\24\0\10\10\10\0\r\227*J\0\0\0\0\0\0\0\0\0\0\0\0)\0\0\0", 30) = 30
4104  lseek(6, 4888998, SEEK_SET)       = 4888998
4104  read(6, "\205Q\317O\23A\24\376\206\266\254l\27\260\n-E\221\3\36\266\5\263\306\340\241\2511\201\222\220\222"..., 408) = 408
4104  mprotect(0x7f6e54034000, 8192, PROT_READ|PROT_WRITE) = 0
4104  lseek(6, 87643, SEEK_SET)         = 87643
4104  read(6, "PK\3\4\24\0\10\10\10\0DW\362J\0\0\0\0\0\0\0\0\0\0\0\0F\0\0\0", 30) = 30
4104  lseek(6, 87743, SEEK_SET)         = 87743
4104  read(6, "\255Z\v|\224\325\225?g2\231\357\313d\22\302|\204\360\361\220\240AB2\20\tTqP\24\22"..., 4350) = 4350
4104  lseek(6, 4793530, SEEK_SET <unfinished ...>
3955  <... futex resumed> )             = -1 ETIMEDOUT (Connection timed out)
4104  <... lseek resumed> )             = 4793530
4104  read(6,  <unfinished ...>
3955  futex(0x7f6e94182b28, FUTEX_WAKE_PRIVATE, 1) = 0
3955  futex(0x7f6e94182b54, FUTEX_WAIT_BITSET_PRIVATE, 1, {4967731, 745318313}, ffffffff <unfinished ...>
```

Best regards, Space

**Comment by Space2Man** [comment]
According to Oracle docs the SIGSEGV is shown when the JVM does a catch ...

[http://www.ateam-oracle.com/why-am-i-seeing-sigsegv-when-i-strace-a-java-application-on-linux/](url)

But I still do not understand why the getProcesses is not returning ...

**Comment by dbwiddis** [comment]
It looks like it's erroring reading `/proc/<pid>/status` which may be a permissions issue if your `proc` filesystem was mounted using `hidepid=1`.  Can you check read permissions there?   Can you try running your program as root?  Can you try retrieving just one process with a known pid?

**Comment by Space2Man** [comment]
Hi,

```-bash-4.1$ mount -v | grep proc
proc on /proc type proc (rw)
none on /proc/sys/fs/binfmt_misc type binfmt_misc (rw)
```

Looks like /proc is mounted in normal way. I had run it as root with same error and even as normal user I do not get permission error:

```-bash-4.1$ cat /proc/*/status > /dev/null
-bash-4.1$
```

Retrieving info for single pid does not work as well.

**Comment by dbwiddis** [comment]
My next suspicion is this line:
`Libc.INSTANCE.readlink(String.format("/proc/%d/exe", pid), buf, 1023);`

We've had other issues with CentOS and glibc.  See #338.  Can you check your java and glibc versions and investigate anything about that file link that might cause a problem reading it?

**Comment by Space2Man** [comment]
I will check that tomorrow. Thanks for your quick responses!

**Comment by Space2Man** [comment]
System is running glibc 2.12 ... Regarding java versions. I had tested both 1.7 and 1.8 ... I will verify with OSHI-3.3.

**Comment by Space2Man** [comment]
Tested with OSHI-3.4.0 and it works! Thanks for the perfect support. Now I know how to work around this bug. Thanks a lot!
