### ISSUE TITLE
Is it possible to start Windows service from OSHI via WMI?

### ISSUE THREAD

**Issue by Space2Man** [oshi/oshi#393]
Hi,

I am trying to start Windows services which have `StartMode == "Auto"` and `State != "Running"`. I am already able to query all the infos about all configured services via

`WmiUtil.selectObjectsFrom(null, "Win32_Service", svcProperties, where, svcValueTypes)`

Is this possible already with OSHI? I see there is an `execMethod` in WmiUtil but it's private ...

EDIT: State!=Running of course :)

Thanks and best regards,

     Jochen

**Comment by dbwiddis** [comment]
This functionality isn't in OSHI but there's enough of a blueprint of how to do it that you could use as an example.

In the `WMIUtil` class, look at the way the properties `PROCESS_GETOWNER` and `PROCESS_GETOWNERSID` are implemented to call `execMethod()` (yes, it's sort of a hack but it works).  You'd have to do something like that.

**Comment by Space2Man** [comment]
Hi,

I will check that ... thanks!
