### ISSUE TITLE
Doesn't fetch info

### ISSUE THREAD

**Issue by JohnsonJeyaraj** [oshi/oshi#402]
OSHI 
I'm Using OSHI for last one month to Fetching details of OS,Hardware and Network.
but,
yesterday Suddenly,skips these following steps and exit program...
{
 OperatingSystem operatingSystrmInfo = systemInfo.getOperatingSystem();
 NetworkIF[] networkIFs = hardware.getNetworkIFs();
}

**Comment by dbwiddis** [comment]
Can you turn on trace logging so I can see how far it gets?

**Comment by dbwiddis** [comment]
Hey there @JohnsonJeyaraj ... we'd love to try to help but need more information.  If you're still getting this problem can you turn on logging?  If not, we'll close this issue.
