### ISSUE TITLE
Disk store is empty for non root users

### ISSUE THREAD

**Issue by Kaijiro** [oshi/oshi#409]
Hi,

Today I tried to retrieve the disks of my system using OSHI. It worked well on my computer (Ubuntu 16.04) when executing the program with my user.

But when I try with a non-admin / non-root user, the disk store is completely empty.

Any clue of what's happening and/or how to solve this ?

**Comment by dbwiddis** [comment]
Many of the *nix commands only work as root, so this is just one symptom of a larger problem, and the easiest solution is to run oshi (or the program which imports it) with root ownership.

For this specific application, oshi accesses the linux information using udev.  I believe you may be able to chmod or chgrp the `/dev` filesystem to permit access to the user running oshi.

**Comment by Kaijiro** [comment]
Yep, you're right, changing access to `/dev` is the solution.

But for a production environnement, the root solution would not have been acceptable. Thank you for your help :)
