### ISSUE TITLE
Cannot get fully partitions info in Win7

### ISSUE THREAD

**Issue by ScOrPiOzzy** [oshi/oshi#411]
I have two hard drive, one is normal HDD, another one is SSD .  I want get all partitions information in my project.
Here is my code : 
![image](https://user-images.githubusercontent.com/28925952/30730460-cd85a058-9f99-11e7-849f-d53858c1e1f5.png)
The result is:
![image](https://user-images.githubusercontent.com/28925952/30730494-06c24fd8-9f9a-11e7-90fe-1b2b43747f58.png)
In fact, PHYSICALDRIVE1 have 4 partitions, partition F and partition G is missing.  Why?

**Comment by ScOrPiOzzy** [comment]
And this is Disk Management information
![image](https://user-images.githubusercontent.com/28925952/30730836-748f8416-9f9c-11e7-8142-aaeb7b8c519a.png)

**Comment by dbwiddis** [comment]
OSHI gets its partition information from WMI, specifically Win32_DiskPartition.  Does WMI have all your drives listed?

**Comment by ScOrPiOzzy** [comment]
Thank you for the quick reply.
You're right.
![image](https://user-images.githubusercontent.com/28925952/30732412-06a73080-9fa5-11e7-8594-83248152adf4.png)
So what should I do?  I need help.

**Comment by YoshiEnVerde** [comment]
Here's the deal:
**_Win32_DiskPartitions_** returns just that: the disk partitions. **Logical Partitions** is a bit of a misnomer, as they aren't really considered _partitions_, but _drives_.

**_Win32_LogicalDisk_** returns the list of logical drives in the computer.

Finally, WMI keeps an internal relationship graph for all the classes it handles.
Every object WMI handles has a **_GetRelated_** method that can get that relationship.
I have no idea, however, if this relationship thing can be used outside of PowerShell.

**Comment by dbwiddis** [comment]
The `FileSystem` class will identify these LogicalVolumes and indicate where they are mounted.  I would expect that printing out the FileSystem on the above example would show both F: and G: mounted on H:\

**Comment by ScOrPiOzzy** [comment]
@YoshiEnVerde @dbwiddis Thank you for your help!  The problem has been solved. 
![image](https://user-images.githubusercontent.com/28925952/30768878-86131cde-a041-11e7-95b0-9403b3e2d05e.png)
This is what I want:
![image](https://user-images.githubusercontent.com/28925952/30768932-3e436aca-a042-11e7-9436-5a7fa5611871.png)
Thank you again for all of your help!

**Comment by dbwiddis** [comment]
Glad you fixed it!
