### ISSUE TITLE
Division by zero error when getting process info on Linux

### ISSUE THREAD

**Issue by YoshiEnVerde** [oshi/oshi#413]
There seems to be the possibility of an error when gathering some values from the PID file in Linux.
This ends up with some code in LinuxOperatingSystem, dependant on these values, throwing an ArithmeticException (Division by Zero).

This was reported by @SangheeKim at #399

**Comment by YoshiEnVerde** [comment]
We would be better with a full stack trace, but as far as I can tell, this error comes from a misshandling of a possible error within the `init()` method of `LinuxOperativeSystem`:

If the **youngestJiffies** field is set to 0 (which marks an OS-level error when trying to read the list of running processes, we log the error and cancel the **init** method halfway through.

That leaves a few fields set at 0, when they should have some value.
Mainly **bootTime** and **hz**.

Then, at `LinuxOperatingSystem.getProcess()`, there's a division by **hz** that fails.

I'd suggest a small check in that method, where bootTime and hz are used (one time for bootTime, three for hz), to avoid errors (and to log method use when this situation arises)

**Comment by YoshiEnVerde** [comment]
PR opened on #414

**Comment by SangheeKim** [comment]
Thank you for quickly change.
