### ISSUE TITLE
Disk I/O

### ISSUE THREAD

**Issue by OGGeek** [oshi/oshi#417]
Hi, I noticed that i can only retrieve the Write/WriteBytes Read/ReadBytes and transfer time when dealing with disks. 
Is it possible to retrieve the disk read speed and disk write speed.
Thank you

**Comment by dbwiddis** [comment]
To get the speed you need to collect the bytes read and time stamp, wait some time, and repeat, much like calculating cpu usage.

**Comment by OGGeek** [comment]
Thank you for your quick feedback. it worked. 
I did the following:
```
SystemInfo si = new SystemInfo();
HardwareAbstractionLayer hal = si.getHardware();
HWDiskStore[] DiskStores = hal.getDiskStores();
... //get Disk from DiskStores
long oldReadBytesValue = disk.getReadBytes();
long oldTimestamp = disk.getTimeStamp();
DiskStores = hal.getDiskStores();
... //get Disk from DiskStores again for updated value
read speed in KB/s = (disk.getReadBytes() - oldReadBytesValue) / (disk.getTimeStamp()-oldTimestamp) ;
```

One more question, is it feasible to get a percentage of the hard disk IO like the percentage shown under each disk in Windows Task Manager?

**Comment by dbwiddis** [comment]
What is the denominator of that percentage calculation?  Max possible IO of the disk(s)?  I think even in Task Manager it just grabs the IO from each process and adds it up and divides by... something.
