### ISSUE TITLE
Memory speed

### ISSUE THREAD

**Issue by jorgemjorge** [oshi/oshi#419]
Hello, I noticed that I can only retrieve the used/total memory in system.
Is it possible to retrieve the memory clock speed?
Thank you

**Comment by dbwiddis** [comment]
Looks like on windows it can be fetched with the [Win32_PhysicalMemory](https://msdn.microsoft.com/en-us/library/aa394347(v=vs.85).aspx) class (Speed).  

macOS had `system_profiler SPHardwareDataType` with a field `Bus Speed` in earlier versions.  It's now in `system_profiler SPMemoryDataType`.

Linux has `sudo dmidecode --type 17` that can be parsed for Speed.  I suspect this same solution will be required for the Unixes.

PR welcome.

**Comment by dbwiddis** [comment]
The code you'll need to fetch the value from WMI should be something like this:

At the class level, define an enum with the attributes you want, in this case Speed.
```
    enum PhysicalMemoryProperty {
        SPEED;
    }
```
You may also want to add some other attributes from this class while you're at it... MemoryType seems like a good one (integer enum in Windows, String in macOS).  Manufacturer might be nice too.  I realized here this will return one row for each Bank, so you could actually create a subclass of GlobalMemory for a Bank, and store the Bank name, capacity, speed, manufacturer, and type.... or just stick with Speed if you want!

Then you will use this enum and the class to set up a query:
`WmiQuery<PhysicalMemoryProperty> physicalMemoryQuery = new WmiQuery<>("Win32_PhysicalMemor", PhysicalMemoryProperty.class);`

Then you will execute the query:
`WmiResult<PhysicalMemoryProperty> bankMap = wmiQueryHandler.queryWMI(physicalMemoryQuery);`

And store the result.  Hotswapping memory is extremely rare so this is probably safe to put in a lazy getter, fetch once, and forget.
```
if (bankMap.getResultCount() > 0) {
    // fetch from index 0.  If doing multiple banks you'll loop here and increment 
    this.memorySpeed = WmiUtil.getUint32(bankMap, PhysicalMemoryProperty.SPEED, 0);
}
```

**Comment by dbwiddis** [comment]
The macOS values can be fetched from the IO Registry, in preference to text-parsing the `system_profiler` output.  Still can't find a non-sudo answer for Linux.

**Comment by dbwiddis** [comment]
Steps to implement:
1. Create a new class, `PhysicalMemory` or a better name if you can propose one.
2. Create final private fields with getters, set by a constructor, for a set of common fields across OS's.  I think bank/slot name (possibly two variables or combine into one), capacity, speed, vendor/manufacturer (string name or hex code), and type (DDR4, etc.) are likely candidates.  
3. Add a `getPhysicalMemory()` method to `GlobalMemory` which returns an array of `PhysicalMemory` objects.
4. For each OS, add the code that finds these values and creates the array.

For Windows, the `Win32_PhysicalMemory` WMI class should provide all/most of the data.
For Mac, use `system_profiler SPMemoryDataType` output.  While much of this is in the registry, the slot names are not directly aligned and it's missing capacity #s, so the command line is probably better.  For Linux, FreeBSD, and Solaris, parse `dmidecode --type 17` output.  This requires `sudo` so code should handle the expected non-sudo output with "unknown" values.

**Comment by rohitkukreja1508** [comment]
While testing for Windows using SystemInfoTest,I am not getting any results in Win32_PhysicalMemory with windows 10. On debugging, the error code returned is for WBEM_E_INVALID_QUERY. 

`public PhysicalMemory[] getPhysicalMemory() {
	WmiQuery<PhysicalMemoryProperty> physicalMemoryQuery = new WmiQuery<>("Win32_PhysicalMemory", PhysicalMemoryProperty.class);
	WmiQueryHandler wmiQueryHandler = WmiQueryHandler.createInstance();
	WmiResult<PhysicalMemoryProperty> bankMap = wmiQueryHandler.queryWMI(physicalMemoryQuery);
	PhysicalMemory[] physicalMemory =new PhysicalMemory[1];
	PhysicalMemory memory = null;
	System.out.println("PM:" + physicalMemoryQuery.getPropertyEnum() + " " + physicalMemoryQuery.getWmiClassName());
	if (bankMap.getResultCount() > 0) {
	   String bankLabel = WmiUtil.getString(bankMap, PhysicalMemoryProperty.LABEL, 0);
	   long capacity = WmiUtil.getUint64(bankMap, PhysicalMemoryProperty.CAPACITY, 0);
	   long speed = WmiUtil.getUint32(bankMap, PhysicalMemoryProperty.SPEED, 0);
	   String manufacturer = WmiUtil.getString(bankMap, PhysicalMemoryProperty.MANUFACTURER, 0);
	   String type = WmiUtil.getString(bankMap, PhysicalMemoryProperty.TYPE, 0);
	   memory = new PhysicalMemory(bankLabel, capacity, speed, manufacturer, type);
	   System.out.println("Physical Memory = " + memory.getBankLabel() + " " + memory.getType() + " " + memory.getSpeed() + " " 
	   + memory.getCapacity()+" "+ memory.getManufacturer());
	}
	physicalMemory[0] = memory;
   	return physicalMemory;
   }`
Here is the code for getPhysicalMemory. Can you help with this?

**Comment by rohitkukreja1508** [comment]
I am getting WBEM_E_INVALID_QUERY for Win32_PhysicalMemory while querying

**Comment by dbwiddis** [comment]
You may have misspelled a field name.  Can you turn on debug logging and show the query that’s failing?

**Comment by rohitkukreja1508** [comment]
Yes.That was the issue. I was mistyping properties in enum.

**Comment by rohitkukreja1508** [comment]
I am done with the implementation for Windows [https://github.com/oshi/oshi/compare/master...rohitkukreja1508:Physical-memory-speed-implementation?expand=1](here). Should I raise PR now or after completing implementations for other platforms ?

**Comment by dbwiddis** [comment]
Go ahead and submit the PR, as that will allow me (and our CI bots) to make an initial review. You can keep committing to your branch and the PR will update.

**Comment by rohitkukreja1508** [comment]
Can we test  dmidecode for linux,freeBSD on virtualbox? I tried in Ubuntu VirtualBox but didn't get any output.

**Comment by dbwiddis** [comment]
The `dmidecode` command requires elevated permissions to run.  Unfortunately I can't find any non-`sudo` alternative, if you think you can find one please let me know!   I haven't yet taken the time to explore `sysfs` to see if there's anything usable in there.

There are a few ways to try to test `sudo` commands in OSHI:

The easiest is probably to just run OSHI with elevated permissions (start your IDE using `sudo`, for example, or run from command line).  This is most likely the scenario that anyone using this feature will have to do.

You can try changing the permissions on `/usr/sbin/dmidecode`, but that's somewhat of a hack.

From a development/testing perspective, I've usually just run the command on the command line and saved the results in a file.  Then I write the code using OSHI's `FileUtil.readfile()` which produces a list of strings and processes the same as the output of `ExecutingCommand.runNative()`... once you're satisfied with your output you can swap those two commands.

**Comment by rohitkukreja1508** [comment]
I was not able to find any alternative for accessing dmidecode memory device information without sudo. /sys/class/dmi/id has information for some fields which is very limited and does not include fields which we require. Also, dmidecode uses /sys/firmware/dmi/tables/smbios_entry_point and /sys/firmware/dmi/tables/DMI tables to obtain complete DMI information. So, we can try if we get raw SMBIOS tables by reading this though I am not sure if reading these paths requires sudo permissions. I do not have a physical Linux machine and am not able to access these paths through VirtualBox.

**Comment by dbwiddis** [comment]
That's pretty much my conclusion.  I'd suggest just parsing the standard `dmidecode --type 17` output.
