### ISSUE TITLE
network speed 

### ISSUE THREAD

**Issue by NoPerfectName** [oshi/oshi#426]
Hello!When I used the `networkIF.getSpeed()`,I got zero every times,even I use the updateNetworkStats() method and try to surf the Internet in order to speed up. My network bindwidth is normal.Can you answer my question,please?

**Comment by dbwiddis** [comment]
It's possible your OS simply doesn't report the speed attribute.   This is supposed to be the max speed of the interface, not the actual bandwidth you transfer.

**Comment by NoPerfectName** [comment]
my OS is Ubuntu16.4, now I want to get the actual-time network speed,what should I do?

**Comment by dbwiddis** [comment]
You should [`getBytesRecv()`](http://oshi.github.io/oshi/apidocs/oshi/json/hardware/NetworkIF.html#getBytesRecv--), wait some time, `updateNetworkStats()`, and then `getBytesRecv()` again.  Measure the difference in bytes received divided by the difference in [`getTimeStamp()`](http://oshi.github.io/oshi/apidocs/oshi/json/hardware/NetworkIF.html#getTimeStamp--) values and you'll have your download speed.    Do the same for [`getBytesSent()`](http://oshi.github.io/oshi/apidocs/oshi/json/hardware/NetworkIF.html#getBytesSent--) for upload speed.

**Comment by NoPerfectName** [comment]
OK！thank you for you time。
