### ISSUE TITLE
 two computer has the same CPU serial number on the virtual machine

### ISSUE THREAD

**Issue by sp-open** [oshi/oshi#428]
I have two virtual machine on the diffent computer,use oshi get cpu serial number i got a same value 0F81FBFF005006E3.
the virtual machine create by VMware 12

**Comment by dbwiddis** [comment]
What operating system is the VM?  Since it's a sotware-based CPU, it's feasible that whatever method it uses to create the serial number is using the same information.

**Comment by sp-open** [comment]
thank you
the VM operating system is CentOS 6.6

**Comment by sp-open** [comment]
hi dbwiddis，Thank you for your attention
Recent I get cpu serial number on the same hardware，On three computers i get a same value。
I read your code and found that use stepping,model,family and flags in the AbstractCentralProcessor's createProcessorID method ,When the hardware is the same, the serial number is the same.
So is this a bug？

**Comment by dbwiddis** [comment]
The ProcessorID is not the same as the serial number.   Processor ID is what you would get from the CPUID opcode which identifies stepping, model, family, etc.

**Comment by dbwiddis** [comment]
Closing this issue.  Multiple VMs on the same processor will use the same ProcessorID, which is a fallback for System Serial Number if it's not available elsewhere (also likely with a system serial number).   See #296 for what's currently implemented/available and the distinction between Serial Number and Process ID.
