### ISSUE TITLE
User information

### ISSUE THREAD

**Issue by bildechinger** [oshi/oshi#434]
Feature could be added to get user information:

- username
- userid
- home-dir
- real name

On Linux it is simple (getent passwd).

**Comment by henryx** [comment]
On Windows, is possible to use the `Win32_UserAccount` WMI class, but I'm not sure if it returns Active Directory users too

**Comment by BilalAM** [comment]
`getent passwd` also works for Unix systems ( I ran it on GhostBSD) , but it returns a long list of all entries from the database , you have to find your entry.
 I was thinking first getting your usrname by `whoami ` then passing that value to the list of the entries returned by `getent` and simply `.contains()`-ing the usrname to return our entry , then parse it. 
(Or maybe there is a filter for getent where you can pass a value to filter result of which I do not know about it :) )

**Comment by dbwiddis** [comment]
I'm closing this issue as it's been up for a year and the direction is vague enough that I don't see it actually going anywhere.   Feel free to re-open or submit a new issue to clearly specify missing functionality in OSHI.
