### ISSUE TITLE
problem getting total disk size in GB

### ISSUE THREAD

**Issue by sify21** [oshi/oshi#436]
I used following code to get total disk size:
```
/**
     * @return disk size, in GB
     */
    public long getTotalDisk() {
        long total=0;
        for(HWDiskStore d : info.getHardware().getDiskStores()){
            total += d.getSize();
        }
        return Math.round((double)total/1024/1024/1024);
    }
```

'info' is an instance of SystemInfo. It returns the correct size in GB on windows(windows 7), but on linux(centos 7) it needs to be divided by 1000 to get the correct size. Is that a hard driver vendor's  problem? How do I convert disk size to GB correctly?

**Comment by dbwiddis** [comment]
OSHI gets its disk size for Linux from the `udev` system, specifically: `udev_device_get_sysattr_value(device, "size")`

This returns the size in sectors, which is multiplied by a sector size constant of 512.

So if it's wrong, either `udev` is returning the value in 1000s of sectors, or the sector size is 512000.  I'm not familiar with CentOS but if you can take a look at either of those outputs you can help us narrow this down.

**Comment by sify21** [comment]
Hi, here is my disk info using "fdisk -l":
![1](https://user-images.githubusercontent.com/11829223/34192257-e7074d9a-e587-11e7-9faa-238c607f5b79.png)
![2](https://user-images.githubusercontent.com/11829223/34192264-ede3681a-e587-11e7-8372-2b851b97df68.png)
I have a dual system. sda6~8 are centos partitions, formated as ext4. Others are windows ntfs partitions.
In the "getTotalDisk" method, total equals 1000204886016. If divided by 1000, it matches the disk size returned by fdisk.
Right now I don't know how to get the value returned by udev. I'll search for some udev cmd, or write some c code (which I'm not very familiar with) using the udev_device_get_sysattr_value method.

**Comment by dbwiddis** [comment]
I'm a bit confused here.  You said `getTotalDisk` returns 1000204886016 bytes.  That is precisely the number shown in the `fdisk -l` printout above for `/dev/sda`.

**Comment by sify21** [comment]
Oh, I didn't see the bytes, I just focused on the "1000.2 GB". So oshi works correctly. Maybe that's a problem relating to fdisk?
