### ISSUE TITLE
HardwareAbstractionLayer.getProcessor() cause virtual machine stuck at startup time

### ISSUE THREAD

**Issue by sify21** [oshi/oshi#441]
I use Java Service Wrapper to wrap my app as a windows service, and install it in kvm's virtual machine(windows 7) on centos 7. The windows service is auto-start. In my app's startup method, I create a new SystemInfo instance, and call its getHardware().getProcessor() to get cpu info.

At first I set my service's startup timeout a low value, and everytime I start the virtual machine the service fails to start because of timeout. Then I set service's timeout a high value(20 minutes), and I have to wait for 20 minutes to be able to connect to the virtual machine. Also the service fails to start.

I saw a similar question #416 on real machine of windows 10, maybe they are related.

**Comment by YoshiEnVerde** [comment]
Have you tried rummimg your app without the JSW? Just to make sure that this sin't an issue between OSHI and the Java Service Wrapper.

If the issue persists after that, can you gather some more info on **when** the process hangs?

Issue #416 is specific to Windows 10. I did the tests on Windows 7 myself. That said, a new issue with WMI could have been introduced in newer Windows patches.

**Comment by sify21** [comment]
After I connected to the virtual machine, I can start the service successfully. It just can't start the first time after windows reboot. How do I get oshi's to log debug info?

**Comment by dbwiddis** [comment]
> How do I get oshi to log debug info?

OSHI supports the SLF4J interface.  You need to select your own logging system (e.g., logback, log4j, slf4j-simple, etc.) that uses the SLF4J API.  See https://www.slf4j.org/ documentation and FAQ.    You can take a look at the slf4j-simple implementation in OSHI's test classes.

I am aware of long delays accessing WMI information but have no real idea how to address them.

**Comment by sify21** [comment]
This is the info I got when my app runs in JSW:
```
INFO   | jvm 1    | 2018/01/23 10:09:51 | 2018-01-23 10:09:51.706 [WrapperListener_start_runner] DEBUG o.h.common.AbstractCentralProcessor - Oracle MXBean detected.
INFO   | jvm 1    | 2018/01/23 10:09:51 | 2018-01-23 10:09:51.847 [WrapperListener_start_runner] DEBUG oshi.util.platform.windows.WmiUtil - Connected to ROOT\CIMV2 WMI namespace
INFO   | jvm 1    | 2018/01/23 10:09:51 | 2018-01-23 10:09:51.854 [WrapperListener_start_runner] DEBUG oshi.util.platform.windows.WmiUtil - Query: SELECT ProcessorID FROM Win32_Processor 
INFO   | jvm 1    | 2018/01/23 10:09:52 | 2018-01-23 10:09:51.989 [WrapperListener_start_runner] DEBUG oshi.util.platform.windows.WmiUtil - Connected to ROOT\CIMV2 WMI namespace
INFO   | jvm 1    | 2018/01/23 10:09:52 | 2018-01-23 10:09:51.990 [WrapperListener_start_runner] DEBUG oshi.util.platform.windows.WmiUtil - Query: SELECT Name,PercentIdleTime,PercentPrivilegedTime,PercentUserTime,PercentInterruptTime,PercentDPCTime FROM Win32_PerfRawData_Counters_ProcessorInformation WHERE NOT Name LIKE "%_Total"
ERROR  | wrapper  | 2018/01/23 10:11:43 | Startup failed: Timed out waiting for signal from JVM.
ERROR  | wrapper  | 2018/01/23 10:11:43 | JVM did not exit on request, termination requested.
```

**Comment by dbwiddis** [comment]
Thanks for the detailed log.  The log shows two key things:

1. The first WMI query went fine.
2. The second query hung.

I believe this may be an unpredictable bug surrounding how COM is initialized/uninitialized.  I do believe this and #416 are the same bug.   Security only needs to be initialized once (or causes errors).  But I also have to jump through some hoops in case COM has been initialized by the program calling OSHI (possibly the Java service wrapper?)  See #318.  


I believe that the first WMI query is failing to release some resource of some sort, and that's causing the second query to hang (while waiting for the resource to be released.)  I suspect It might be associated with the use of `WBEM_FLAG_RETURN_IMMEDIATELY` to try to speed up the query (the query returns and then the results may be iterated over) if the result iteration somehow is never completed.

I'm not sure what the solution here is, however, and hope some people can help me debug.  Unfortunately without being able to replicate this on my own Windows machine, I'm left guessing.

**Comment by sify21** [comment]
I found a solution to my specific problem. If I change the service's startup type from auto_start to delay_start, things work fine.
```
INFO   | jvm 1    | 2018/01/23 12:38:51 | 2018-01-23 12:38:51.582 [WrapperListener_start_runner] DEBUG o.h.common.AbstractCentralProcessor - Oracle MXBean detected.
INFO   | jvm 1    | 2018/01/23 12:38:51 | 2018-01-23 12:38:51.735 [WrapperListener_start_runner] DEBUG oshi.util.platform.windows.WmiUtil - Connected to ROOT\CIMV2 WMI namespace
INFO   | jvm 1    | 2018/01/23 12:38:51 | 2018-01-23 12:38:51.758 [WrapperListener_start_runner] DEBUG oshi.util.platform.windows.WmiUtil - Query: SELECT ProcessorID FROM Win32_Processor 
INFO   | jvm 1    | 2018/01/23 12:38:51 | 2018-01-23 12:38:51.996 [WrapperListener_start_runner] DEBUG oshi.util.platform.windows.WmiUtil - Connected to ROOT\CIMV2 WMI namespace
INFO   | jvm 1    | 2018/01/23 12:38:51 | 2018-01-23 12:38:51.997 [WrapperListener_start_runner] DEBUG oshi.util.platform.windows.WmiUtil - Query: SELECT Name,PercentIdleTime,PercentPrivilegedTime,PercentUserTime,PercentInterruptTime,PercentDPCTime FROM Win32_PerfRawData_Counters_ProcessorInformation WHERE NOT Name LIKE "%_Total"
INFO   | jvm 1    | 2018/01/23 12:38:57 | 2018-01-23 12:38:57.464 [WrapperListener_start_runner] DEBUG oshi.util.platform.windows.WmiUtil - Connected to ROOT\CIMV2 WMI namespace
INFO   | jvm 1    | 2018/01/23 12:38:57 | 2018-01-23 12:38:57.464 [WrapperListener_start_runner] DEBUG oshi.util.platform.windows.WmiUtil - Query: SELECT PercentInterruptTime,PercentDPCTime FROM Win32_PerfRawData_Counters_ProcessorInformation WHERE Name="_Total"
INFO   | jvm 1    | 2018/01/23 12:38:57 | 2018-01-23 12:38:57.488 [WrapperListener_start_runner] DEBUG o.h.p.w.WindowsCentralProcessor - Initialized Processor
INFO   | jvm 1    | 2018/01/23 12:38:57 | 2018-01-23 12:38:57.519 [WrapperListener_start_runner] DEBUG oshi.util.platform.windows.WmiUtil - Connected to ROOT\CIMV2 WMI namespace
INFO   | jvm 1    | 2018/01/23 12:38:57 | 2018-01-23 12:38:57.519 [WrapperListener_start_runner] DEBUG oshi.util.platform.windows.WmiUtil - Query: SELECT Version,ProductType,BuildNumber,CSDVersion,SuiteMask FROM Win32_OperatingSystem 
INFO   | jvm 1    | 2018/01/23 12:38:57 | 2018-01-23 12:38:57.562 [WrapperListener_start_runner] DEBUG o.s.o.windows.WindowsOSVersionInfoEx - Initialized OSVersionInfoEx
INFO   | jvm 1    | 2018/01/23 12:38:57 | 2018-01-23 12:38:57.589 [WrapperListener_start_runner] DEBUG oshi.util.platform.windows.WmiUtil - Connected to ROOT\CIMV2 WMI namespace
INFO   | jvm 1    | 2018/01/23 12:38:57 | 2018-01-23 12:38:57.589 [WrapperListener_start_runner] DEBUG oshi.util.platform.windows.WmiUtil - Query: SELECT Name,Description,ProviderName,FileSystem,Freespace,Size FROM Win32_LogicalDisk 
INFO   | jvm 1    | 2018/01/23 12:38:57 | 2018-01-23 12:38:57.662 [WrapperListener_start_runner] DEBUG oshi.util.platform.windows.WmiUtil - Connected to ROOT\CIMV2 WMI namespace
INFO   | jvm 1    | 2018/01/23 12:38:57 | 2018-01-23 12:38:57.663 [WrapperListener_start_runner] DEBUG oshi.util.platform.windows.WmiUtil - Query: SELECT DriveType FROM Win32_LogicalDisk WHERE Name = 'C:'
INFO   | jvm 1    | 2018/01/23 12:38:57 | 2018-01-23 12:38:57.671 [WrapperListener_start_runner] DEBUG oshi.util.platform.windows.WmiUtil - Connected to ROOT\CIMV2 WMI namespace
INFO   | jvm 1    | 2018/01/23 12:38:57 | 2018-01-23 12:38:57.672 [WrapperListener_start_runner] DEBUG oshi.util.platform.windows.WmiUtil - Query: SELECT DriveType FROM Win32_LogicalDisk WHERE Name = 'D:'
INFO   | jvm 1    | 2018/01/23 12:38:57 | 2018-01-23 12:38:57.681 [WrapperListener_start_runner] DEBUG oshi.util.platform.windows.WmiUtil - Connected to ROOT\CIMV2 WMI namespace
INFO   | jvm 1    | 2018/01/23 12:38:57 | 2018-01-23 12:38:57.682 [WrapperListener_start_runner] DEBUG oshi.util.platform.windows.WmiUtil - Query: SELECT DriveType FROM Win32_LogicalDisk WHERE Name = 'E:'
```
Though I don't know the reason. Maybe when system boots  up, it's initializing something for wmi, and I can't use oshi at that time?

**Comment by dbwiddis** [comment]
Wow, good info!    What does "delay start" do/mean?   Is it possible there's a "race condition" and this service needs WMI to be initialized before it starts up?

**Comment by sify21** [comment]
You can change the startup type in the service management panel. Right click the service and change its properties. In the startup type selection, there are 4 options: auto-start, auto-start(delay), manual-start and disable. (sorry for the bad interpretation, my operating system is in chinese)

**Comment by dbwiddis** [comment]
OK.... pretty sure the issue was in OSHI starting up before the WMI service (or some other service that provides info to WMI) was fully initialized.

**Comment by AADELDounia** [comment]
Hello, I use Oshi and I have the same problem, please wich is the service that you changed to auto-start-delay?

**Comment by dbwiddis** [comment]
@sify21 indicated they wrapped their Java app using OSHI inside a Java Service Wrapper.   This is the service that needs its startup delayed until all system startup (e.g., WMI) is complete.

**Comment by dbwiddis** [comment]
Consolidating similar issues in #472
