### ISSUE TITLE
No serial number for baseboard on Linux Mint 18.2

### ISSUE THREAD

**Issue by graynk** [oshi/oshi#444]
So I'm running oshi on my Acer laptop with dual boot. On Windows it runs pretty well (even though first WMI call is fairly long, but upon searching I figured there's nothing that can be done about that), but on Linux Mint 18.2 (MATE version) oshi fails to get baseboard serial number (no problem on Windows).

![debug](https://user-images.githubusercontent.com/3626328/35610954-25a63926-0685-11e8-9529-5932da6238bd.png) 
This is how it looks in debug

![sysinfo](https://user-images.githubusercontent.com/3626328/35610949-20f0b668-0685-11e8-8f55-3e9076d7abb1.png)
And this is the system info

Running `sudo dmidecode -t 2` in the terminal returns baseboard information properly, along with serial number

**Comment by dbwiddis** [comment]
Linux intentionally hides identifying information without root permissions.  Are you running OSHI using root/sudo permissions?

**Comment by graynk** [comment]
No, I ran that as a regular user. Sorry, my bad
