### ISSUE TITLE
Network speed in windows

### ISSUE THREAD

**Issue by AntJan** [oshi/oshi#451]
When retreiving the network speed in windows the receivelinkspeed is passed into the networkIf class. 
I find this comment in windowsnetworks.java
 `// These are unsigned longs. netIF setter will mask sign bit.`

And in networkIF.java

`public void setSpeed(long speed) {
        this.speed = speed & 0x7fffffffffffffffL;
    }`

But on my system the receivelinkspeed is already the correct number, so the setSpeed function makes for an incorrect result when using networkIF.getSpeed()

So maybe a test to skip this calculation when on windows?

**Comment by dbwiddis** [comment]
Can you be more specific as to what the "correct number" and "incorrect result" are?

**Comment by AntJan** [comment]
If I use the getSpeed() method I get the following.
Speed:  194693632
Speed:  194.7 Mbps

When I get the speed directly. (same way as in WindowsNetworks.java line 72)
Speed:  1000000000
Speed:  1 Gbps

Also included a screenshot to show this is the result I expected.
![netspeed](https://user-images.githubusercontent.com/36670631/36469275-f84d5e42-16e6-11e8-89b8-5f3d8c7dcfe8.PNG)

**Comment by AntJan** [comment]
I found someone with the same issue and it seems fixed already. #431 

Didn't check that yesterday because I was searching for network speed.
This can be closed.
