### ISSUE TITLE
OperatingSystem.getProcesses open file handles?

### ISSUE THREAD

**Issue by spyhunter99** [oshi/oshi#454]
First of all, this project is awesome. I've been searching for a replacement for sigar for quite a while and this is nearly a perfect fit.

I have a need to query for open file handles, both system wide and per process. I'm sure there's some variance with operation systems but `open file handles` is generally the count of

- open file handles
- open network connections/sockets

This is useful for tracking and identifying runaway processes. Also many operating systems have upper limits on what is allowed thus at least being able to query this is important.

That said, i was browsing through the test classes (oh thank you all!) and the windows implementation `WindowsOperatingSystem` and didn't see anything related to handles. The good news is that windows definitely tracks this and it is available via sigar and task manager. This is also available in linux operating systems using lsof. Could this be added at some point?

**Comment by dbwiddis** [comment]
This has been requested in #387.  You're welcome to code it up!  :)

**Comment by spyhunter99** [comment]
k, on it! I have windows working already

**Comment by dbwiddis** [comment]
More seriously... I'll try to get a release out within the next week or so, but the offer to join the team is a serious one.

**Comment by spyhunter99** [comment]
sure thing. i have a sonatype account already
