### ISSUE TITLE
Issue with getProcessorCpuLoadBetweenTicks

### ISSUE THREAD

**Issue by Vikrantsingh** [oshi/oshi#456]
I'm calling getProcessorCpuLoadBetweenTicks to get cpu load per processor.
It is giving me cpu load very less (<<4%) as compared to htop ~20% (fluctuating).
From the documentation it states that this method "counts ticks for the processors from {@link #getProcessorCpuLoadTicks()} between successive calls"

Do i need to make call to getProcessorCpuLoadTicks() method explicitly with some delay or getProcessorCpuLoadBetweenTicks() will take care of it?

`
SystemInfo systemInfoCapture = new SystemInfo();
print(systemInfoCapture.getHardware().getProcessor().getSystemCpuLoad() *100);

for(double cpuLoad : systemInfoCapture.getHardware().getProcessor().getProcessorCpuLoadBetweenTicks()){
                customDimension.put(Dimensions.Processor, String.valueOf(++counter));
                print(cpuLoad * 100);
            }
`
I'm running this method every 10 seconds.

Could you please let me know, what is going wrong here?

**Comment by dbwiddis** [comment]
If you're running it every 10 seconds, you're getting the average CPU over that 10 second period.  Or at least you're supposed to be...

**Comment by Vikrantsingh** [comment]
Thank you for reply.

Is there a way to get Max CPU?

Do i need to make call to getProcessorCpuLoadTicks() method explicitly with some delay before making call to getProcessorCpuLoadBetweenTicks()?

**Comment by dbwiddis** [comment]
The "between ticks" method is just a convenience method which calls the `get...Ticks` counterpart and does the math for you, intending to provide a parallel method to the built-in Java CPU methods.   But OSHI tries to expose information at the lowest possible level (actual tick counters, with corresponding timestamps).   

The "between ticks" methods are intended to be called no more frequently than once per second.  Other than setting a background process to record these one-second ticks (and saving the max) there's no built in way to get that max.

**Comment by Vikrantsingh** [comment]
okay, got it.
Thank you :)
