### ISSUE TITLE
Units for Power Source/Time Remaining

### ISSUE THREAD

**Issue by spyhunter99** [oshi/oshi#458]
The power source.getTimeRemain() returns an unsigned int, but it's not exactly clear what the unit of measure is. Is it minutes? seconds? etc. Please consider annotating the javadocs to help make this clear

**Comment by dbwiddis** [comment]
I’m looking at the JavaDoc and see it returns a double, documented as seconds.  Are we looking at the same thing?

**Comment by spyhunter99** [comment]
ahh sorry i must have been looking in the windows specific implementation. On my win10 laptop, the value returned is much higher than what the windows estimate for time remaining is. That's the only reason i'm questioning the values returned. For 2hrs remaining, oshi is returning 26000 or so. 2 hrs = 7200 seconds.

**Comment by dbwiddis** [comment]
Well, OSHI is pulling its info [from this structure](https://msdn.microsoft.com/en-us/library/windows/desktop/aa373212(v=vs.85).aspx).  Supposed to be in seconds.  Not sure why it's off so much.

**Comment by dbwiddis** [comment]
Closing this as we have it documented.  MS Engineers apparently have a better way of calculating time remaining than relying on a snapshot of `SYSTEM_BATTERY_STATE` but that's all OSHI can do!
