### ISSUE TITLE
Get process metrics by a list of pids

### ISSUE THREAD

**Issue by spyhunter99** [oshi/oshi#459]
It may be more efficient (on windows) to query for a list of known pids instead of one by one. This would add a new method to support querying a list of process related metrics from the os. I believe right now the options are

 - ask for everything up to a given limit with sorting
 - ask for a single pid's metrics

**Comment by dbwiddis** [comment]
Great idea

**Comment by spyhunter99** [comment]
on it. windows is the only case where a specialized implementation seems feasible

**Comment by dbwiddis** [comment]
It seems reasonable to just have an extra class that blends in seamlessly with the other "get all" and "get PID" class; we can put the functionality in the abstract class and just override it in the Windows version.

**Comment by dbwiddis** [comment]
Fixed in #460
