### ISSUE TITLE
NetworkInterface time since enabled, time since connected

### ISSUE THREAD

**Issue by spyhunter99** [oshi/oshi#462]
I'm not sure if this is universally possible, but if it is, it would be helpful to be able to track this.

**Comment by dbwiddis** [comment]
Most of OSHI's Network code simply wraps and provides additional functionality to the built in Java [NetworkInterface](https://docs.oracle.com/javase/7/docs/api/java/net/NetworkInterface.html) class.  If you can find where to get all this data, more power to you!

**Comment by dbwiddis** [comment]
I started digging around to see if this data was available anywhere.  It's not.  You can generally grep `/var/log/syslog` and find something close if you know what you're looking for.

- Linux: No structure in the kernel.  
- macOS: Closest is "last administrative change" without clear docs on what that means.
- Unix:  Nope.
- Windows: Closest we can get is "reset time" on a deprecated class that might work pre-Vista.  Or return 0. Or return an arbitrary value:
> The length of time, in hundredths of seconds (10^-2 sec), starting from the last computer restart, when the interface entered its current operational state. This value rolls over after 2^32 hundredths of a second.
> The dwLastChange member is not currently supported by NDIS. On Windows Vista and later, NDIS returns zero for this member. On earlier versions of Windows, an arbitrary value is returned in this member for the interfaces supported by NDIS. For interfaces supported by other interface providers, they might return an appropriate value.

In sum... despite the plethora of network information available in Java's built-in class, or the `netstat` commands or `ifconfig` and friends, "up time" just doesn't seem to be a statistic of concern.

There are plenty of utilities to run and monitor a network in real time, e.g., `rtmon`.  However, these must be explicitly started up by the user, or be part of the operating system (e.g., Windows connection statistics dialogue -- which is not exposed in code anywhere).   OSHI has enough information that you could run a service at startup and monitor the connection(s) yourself using OSHI. :)  

But I'm going to close this issue as essentially impossible to implement.
