### ISSUE TITLE
Windows 7 + NetBeans NoClassDefFoundError help

### ISSUE THREAD

**Issue by ASG66** [oshi/oshi#467]
I cannot use any of the get() methods available and this Exception is thrown every time I try to use a get() method. I've individual jar files for each of the dependencies and have added them to the project library. 
BTW, I'm using NetBeans IDE.

I think it is a dependency issue, and if someone can provide me a detailed answer on how to manage dependencies, that'd be great.

`Windows 7: Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: com/sun/jna/platform/win32/Variant$VARIANT`

Thanks!

**Comment by dbwiddis** [comment]
Are you using OSHI by itself or as a dependency of another program?  How have you added your project library to your classpath?

Are you able to use maven to manage dependencies?   I would recommend going that route... a little work up front will save you endless pain.

**Comment by ASG66** [comment]
Yeah, I tried the Maven approach and it downloaded the "jna-platform-4.5.1.jar" file and now it works! Thanks for the answer and also for the excellent library!
