### ISSUE TITLE
Linux - Ubuntu - Battery charge is not showing (displays N/A ) when user plugged the  charger for  Ubuntu device

### ISSUE THREAD

**Issue by sowmyajanardhan** [oshi/oshi#468]
When Ubuntu device is enrolled , battery status  displays N/A when device is plugged in , however battery status shows properly when user dis connects the charger.

**Comment by dbwiddis** [comment]
Can you be more specific on which fields are displaying unexpected values?  For example, while charging, it's expected that you won't have a "remaining capacity" value.

**Comment by dbwiddis** [comment]
Closing this issue as it's unclear, and nothing inside OSHI.  OSHI only displays 3 properties; a power source name (String), capacity (double), and time remaining (double).  

Name is either "Unknown" or derives from `/sys/class/power_supply` directory, so if there's an "N/A" it's coming from the operating system when the battery is being charged.
