### ISSUE TITLE
Next official release timeline?

### ISSUE THREAD

**Issue by detyo** [oshi/oshi#469]
Hi,
  We did some prototyping with OSHI and are now considering to use it in production, however there were some issues that we discovered which ultimately got fixed, but there is no official release since then. Do you have any idea when the next release will be out?

Thanks,
   Detelin

**Comment by dbwiddis** [comment]
OK I think I solved the previous issues.  The temporary files prevent me from using my usual hack to bypass another bug.

Remaining issue is that Central requires javadoc and source for the new oshi-core-shaded project so it's failing closing the staging repository...

**Comment by dbwiddis** [comment]
Figured it out.  Why do simple answers take so long to find?   Release has been cut.

**Comment by lprimak** [comment]
Please don’t commit the generated files. Thank you.

**Comment by dbwiddis** [comment]
@lprimak I set the reduced pom to be ignored, and figured out (after release) that the maven wrapper downloader was a license rewrite issue. Oops.  All good now.

**Comment by lprimak** [comment]
that's great! thank you
