### ISSUE TITLE
Maven plugin configuration (again)

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#473]
Since #224 had a lot of issues in it that are solved, I figured I'd start afresh with a new issue for things that remain outstanding.

`maven-javadoc-plugin` -- breaks during release:perform pushing to gh_pages.  Have not tested this with the new version of the javadoc plugin; this may be fixed. I'll test with the next release.

Sonarlint -- reports the following error.  While this may be an IDE plugin problem, it may require changes to the repository to fix.  Also, I recall reading somewhere that sonarqube plugin may require a different setup as well, so this is my note-to-self to research and fix it.

> Error during analysis
> java.lang.IllegalStateException: Fail to read file '/Users/danielwiddis/git/oshi/oshi-core/target/classes/META-INF/MANIFEST.MF' with encoding 'UTF-8'
> 	at org.sonarsource.sonarlint.core.container.analysis.filesystem.FileMetadata.readFile(FileMetadata.java:163)
>

**Comment by dbwiddis** [comment]
This looks like the a[nswer to the manifest question](https://stackoverflow.com/questions/34674073/how-to-generate-manifest-mf-file-during-compile-phase).

**Comment by hazendaz** [comment]
I'll take a quick look.  I'm not having any issues with any other projects so it's probably something simple that has just been overlooked.  I ran a release on waffle last night without any issues which I think oshi was originally based off of.

**Comment by hazendaz** [comment]
@dbwiddis I'll do some testing to get a full release going on a separate branch so it does not affect master.  I'll let the tags be listed as "-test" so it doesn't conflict with versioning and will delete that later.  First though going through and getting everything up-to-date and applied on master.

**Comment by hazendaz** [comment]
Seems I had 'waffle' configured to not run the site deploy :(  That explains why things were not released in a long time over there and @dblock mentioned long time with no site.  What specific error are you getting currently with the release?  Is it different than before?

**Comment by dbwiddis** [comment]
I haven’t tried recently without the back-up-to-tag and nvm install trick.  It may very well be fixed with the 3.x version of Javadoc plugin.  This was mostly a note to myself to check on the next release. 

#224 has the related error message(s).

**Comment by dbwiddis** [comment]
Related/optional, I had wanted to at some point put all version #s in a separate properties section and reference them later, to avoid having to hunt-and-peck versions when they update.

**Comment by hazendaz** [comment]
Makes sense, I've since started doing that all over, especially helpful for the ones that are versions in multiple places :)  I didn't see anything really out of the norm other than learning I didn't actually distro the waffle site.  The config matched between the two.  Since I didn't have that actually work over there, I may focus attention there to get that working as in theory both should have same issue.  I didn't remember turning that off there but must have due to related issues and had false sense that it worked last night :(

**Comment by dbwiddis** [comment]
Thanks for anything you can figure out.  Again, nothing high priority here as I've worked around it all.  I'm just a perfectionist especially when it comes to automation that should just be automatic!

**Comment by dbwiddis** [comment]
Just pushed a release with no problems, so the earlier issues are gone.  

Also updated sonarlint in Eclipse and fixed the issues there, and updated sonarcloud URLs.

**Comment by hazendaz** [comment]
Awesome

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
