### ISSUE TITLE
Accuracy of HW Disk store get write bytes on windows

### ISSUE THREAD

**Issue by spyhunter99** [oshi/oshi#481]
I made a small app to calculate disk io rates with some tests. On windows, this seems to be reporting at about 33% of the actual bytes written to disk.  Something isn't right

**Comment by dbwiddis** [comment]
Can you share the app so I can reproduce the problem?  Could it be related to compression, cacheing, or sector padding?

**Comment by spyhunter99** [comment]
I can provide a test case

**Comment by dbwiddis** [comment]
So I just played with this myself.  I downloaded [Random Data File Creator (RDFC)](http://www.bertel.de/software/rdfc/index-en.html).

Executing the command `rdfc.exe gig.bin 1 GB` looked like it wrote approximately 1 GB:

>  2018.04.20.09.02.02:  reads: 932343 (33.9 GiB), writes: 920670 (15.9 GiB), xfer: 2963149 ms
>  2018.04.20.09.02.22:  reads: 932654 (33.9 GiB), writes: 958618 (17.0 GiB), xfer: 2984718 ms

I then tried to copy the file to a network drive `copy gig.bin \\foo\bar`:

>  2018.04.20.09.06.35:  reads: 939483 (34.0 GiB), writes: 967784 (17.1 GiB), xfer: 3002951 ms
>  2018.04.20.09.06.45:  reads: 943684 (34.3 GiB), writes: 968956 (17.1 GiB), xfer: 3005402 ms

Only a third of the size, but given how recently the file was created, I assume it may have been cached by the hard drive.   I'll try the move again after a day full of other work on that drive....

**Comment by dbwiddis** [comment]
And since I probably cleared out any disk cache, I repeated the 1 gb binary file copy to a network drive from 2 comments ago.  Looks like 1 GiB got read.

>  2018.04.20.10.21.53:  reads: 1507798 (62.5 GiB), writes: 2008100 (47.4 GiB), xfer: 5291414 ms
>  2018.04.20.10.23.35:  reads: 1511974 (63.5 GiB), writes: 2008792 (47.4 GiB), xfer: 5312803 ms

So I'm comfortable that OSHI (which is reading the counters from WMI which gets them from PerfMon counters) is correctly reporting the disk reads/writes in the absence of disk cache impacts, compression (nonrandom files), etc.

**Comment by spyhunter99** [comment]
@dbwiddis thanks for looking into this. I hadn't considering caching. My test case was basically
HWDisk#getReadBytes
then write 20MBs to a file
HWDisk#getReadBytes

expecting the difference between the two to be close to 20MBs or more.

On a side note, I also track disk read/write rates. If I calculate the disk write rate using the 20MB example and measuring the time it takes to write. I keep pretty close to what is reporting in window's resource monitor. Can we add this to oshi?

**Comment by dbwiddis** [comment]
You can record the written bytes and timestamps, or use the transfer time milliseconds shown in the above log captures, to calculate the write times.   OSHI is intended to provide "snapshot" values as much as possible.

In the future I'd love to integrate with a library like Metrics, that will allow the individual timestamps to be rolled up to longer averages, enable meters, and pretty much be able to replicate the resource monitor.    But I'll need a lot of help to make that happen. :)

**Comment by spyhunter99** [comment]
In perfmon, what field correlates to readBytes and writeBytes? I only see rates and averages. From the oshi code, it's pulling "DiskWriteBytesPerSec" and "DiskReadBytesPerSec" from WMI. I see the comments in the source about it not being an actual rate, however the microsoft docs state the following
`Rate at which bytes are transferred to the disk during write operations.`
https://msdn.microsoft.com/en-us/library/aa394262%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

strange indeed

**Comment by dbwiddis** [comment]
Excellent question.  The counter you linked to is [Win32_PerfFormattedData_PerfDisk_PhysicalDisk](https://msdn.microsoft.com/en-us/library/aa394262%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396).  Note the word "FormattedData".  This counter won't be accurate all at sub-second resolution, and will do the ticks/time math when queried at intervals over one second.  But each time you query it, you reset the time clock.    Originally in OSHI I had to use the rate from this query (actually the underlying PDH counter) to calculate an estimated tick value, which Windows does not expose except through WMI.

However, WMI also exposes a corresponding counter to the one linked above.  The second paragraph notes, 

> This class derives its raw data from the corresponding raw class  [Win32_PerfRawData_PerfDisk_PhysicalDisk](https://msdn.microsoft.com/en-us/library/aa394308(v=vs.85).aspx).  

Note the "RawData" words here.  The fields are named the same (including the "perSec") but the Raw table contains the actual tick/count/byte values without any reference to time (except for the time measures such as transfer time... they contain tick values in 10^-4 second increment).
