### ISSUE TITLE
How to find the allocation unit size of a drives in the system using oshi

### ISSUE THREAD

**Issue by prashanthiradha** [oshi/oshi#482]
I have an issue. Im able to get the drives in the system and the total space of drive. but not able to retrive the virtual memory size and allocation unit size of the drive.
SystemInfo si = new SystemInfo();
OperatingSystem os = si.getOperatingSystem(); 
os.getFileSystem();
OSFileStore[] osfs = fileSystem.getFileStores();
for(OSFileStore os : osfs) {
os.getName();
os.getTotalSpace();
}

How to retrive the allocation unti size of the drives and virtual memory size of the system osing oshi.

**Comment by dbwiddis** [comment]
OSHI does not expose the allocation unit size, but you can retrieve it using the WMIUtil class, looking at Win32_Volume (and matching Label with the drive).

Virtual Memory is on the GlobalMemory class, with the methods regarding the Swap File.

**Comment by dbwiddis** [comment]
Looks like Win32_DiskPartition class also has BlockSize.

**Comment by prashanthiradha** [comment]
Can i do this using JAVA.

**Comment by dbwiddis** [comment]
```
Map<String, List<String>> blockInfo = 
	WmiUtil.selectStringsFrom(null, "Win32_DiskPartition", "Name,BlockSize", null);
List<String> name = blockInfo.get("Name");
List<String> blockSize = blockInfo.get("BlockSize");
for (int i = 0; i<name.size();i++) {
	System.out.println(name.get(i)+":"+ blockSize.get(i));
}
```

Output:

> Disk #0, Partition #0:512
> Disk #0, Partition #1:512

OSHI queries this class in [WindowsDisks.java](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsDisks.java).  We could consider adding block size as a field to the `HWDiskStore` class.

**Comment by prashanthiradha** [comment]
Thanks now im able to get the allocation unit size for my drives in the system. Can you please help me out  to get allocation unit size for virtual memory and physical memory.

**Comment by dbwiddis** [comment]
`WindowsGlobalMemory.java` gets this internally as part of its calculations:

```
private transient PERFORMANCE_INFORMATION perfInfo = new PERFORMANCE_INFORMATION();
if (!Psapi.INSTANCE.GetPerformanceInfo(this.perfInfo, this.perfInfo.size())) {
    LOG.error("Failed to get Performance Info. Error code: {}", Kernel32.INSTANCE.GetLastError());
    return;
}
System.out.println("Memory page size = " + this.perfInfo.PageSize.longValue());
```
