### ISSUE TITLE
Detailed and thorough documentation

### ISSUE THREAD

**Issue by BilalAM** [oshi/oshi#483]
It needs a detailed and thorough documentation like example usages , small concise code samples and such

**Comment by dbwiddis** [comment]
Yes, it does!  Would you like to get it started?   The [Wiki](https://github.com/oshi/oshi/wiki) should be available if you want to sketch a shell of what you want answered I can help fill it out.

**Comment by BilalAM** [comment]
I will definitely contribute on making it , actually I was trying to use it but for some reasons its not downloading the dependencies. The maven dependency I am trying to use is this 
 <dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-parent</artifactId>
            <version>3.5.0</version>
 </dependency> 
So I decided to search for some Getting Started type of guide or tutorials for it but there are none , I guess I am missing something ?

**Comment by BilalAM** [comment]
Ill definitely help and contribute in making short , small and concise Getting Started type tutorials for the wiki !
