### ISSUE TITLE
public method for ticks to milliseconds and back

### ISSUE THREAD

**Issue by spyhunter99** [oshi/oshi#486]
`LinuxOperatingSystem.init hz exposure`
see https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java#L168

Would it be possible to make the algorithms used in the referenced class to be made public? I'm looking for a simple way to convert ticks to milliseconds and back again. This would be particularly useful for calculation process level cpu usage on linux operating systems

**Comment by dbwiddis** [comment]
I don't see any reason why we can't add a `getHz()` method to expose the `hz` value on Linux, and equivalent constants on other OSes.  Feel free to submit a PR!

**Comment by spyhunter99** [comment]
adding the one method is trivial for linux but i don't see anywhere else in the code base where some kind of funky calculations are made in order to calculate it. A static method on LinuxOperatingSystem would probably be sufficient, unless you had other ideas or background knowledge that i don't

**Comment by dbwiddis** [comment]
Thanks for the PR.  I'll take a look at it tomorrow.  However, I'll answer your "ideas" question now...

By exposing it as a single OS method, you require (under the current setup) the user to explicitly cast to the Linux class, to access the class.  As an all-OS method this would be unnecessary.

There are equivalent tick-to-millisecond conversions for other OS's, and in fact, OSHI truncates these extra decimals to milliseconds for other OS's rather arbitrarily (not completely arbitrarily -- Java's use of milliseconds for its current timestamp was a key factor.)

Windows ticks are in 100-nanosecond (1 millionth of a second) units so the "Hz" calculation there would be hardcoded as 10000.  (There could be room in the future to expose the raw tick values that are currently truncated to milliseconds.)  

[MacOS high resolution timers](https://developer.apple.com/library/content/technotes/tn2169/_index.html) actually have time in nanoseconds so Hz would be 1,000,000.

The Unix implementations just return milliseconds so Hz would be 1 for FreeBSD and Solaris.

So my thoughts are less the value of returning the values for all OS's (constants for all but Linux) now, but more an idea of enabling the higher precision return values in a future version (to the nearest ns on macOS and nearest 100-ns on Windows) with a conversion factor available.
