### ISSUE TITLE
Contribute DLL mappings into JNA

### ISSUE THREAD

**Issue by dblock** [oshi/oshi#490]
Looks like a fair amount of Win32 functions at the very least are now implemented in Kernel32 and such. Contribute those into https://github.com/java-native-access/jna

**Comment by dbwiddis** [comment]
Done:
- Latest Kernel32 additions from #489 

To do:
- PSAPI 
- WtsAPI32 but should include more constants
- PowrProf
- Ole32
- Cfgmgr32
- IpHlpAPI

To consider:
- The COM classes and WMIUtil class
