### ISSUE TITLE
Allocation unit\ block size for virtual memory in java  using oshi.

### ISSUE THREAD

**Issue by sarayukrishna** [oshi/oshi#492]
In java using OSHI. how to determine the allocation unit size or block size for virtual memory in windows.

im able to get the allocation unit or partition or block size for all drives in the pc . using

Map<String, List> blockInfo = WmiUtil.selectStringsFrom(null, "Win32_Volume", "Name,BlockSize", null);
List blockSize = blockInfo.get("BlockSize");

Now my need is i need to get the block size for virtual memory too. using win32_volume im not able to get the block size for virtual memory.

**Comment by dbwiddis** [comment]
OSHI internally calculates the page size but does not display this value.  Should be easy to add.  Might consider doing #419 at the same time.

**Comment by dbwiddis** [comment]
Also to be clear, there's two allocation unit sizes at play here.  The block size on the hardware volume is relevant for allocating files to the disk and impacts the access speed.  You've already posted the way to retrieve that. 

The page size is the allocation unit size of memory, whether physical or virtual.
