### ISSUE TITLE
SIGSEGV fatal error on Solaris Central Processor retrieval

### ISSUE THREAD

**Issue by Kald0** [oshi/oshi#493]
Solaris 11.3 SPARC.
Java 1.8.0_161-b12
oshi 3.4.4. and 3.5.0
A SIGSEGV fatal error is thrown when the CentralProcessor is instancianted using the following code:
_new SystemInfo().getHardware().getProcessor();_
I've attached the core dump below.

The error happens in the _getProcessorCpuLoadTicks_ method of the **SolarisCentralProcessor** class.
One of the three _KstatUtil.kstatDataLookupLong_ call is throwing the error.  I wasn't able to reproduce the error on my Solaris 11.3 x86 VM. 

Do you have any clue on why this is happening ?

[hs_err_pid15717.log](https://github.com/oshi/oshi/files/2012555/hs_err_pid15717.log)

**Comment by dbwiddis** [comment]
Uh oh.  

Glad I've got someone to test on actual hardware and find these.  The log actually appears to show the error in `KstatUtil.kstatDataLookupString` in one of the calls in `initVars()`.  The offending line is the `kstat_data_lookup()` method call from LibKstat.

Can you throw in some more debug statements to see which one of the lookups is failing (or all?) and what your actual kstat value(s) are for the problematic stats?

**Comment by dbwiddis** [comment]
Are you sure you're on [Solaris 11](https://github.com/oshi/oshi/blob/master/FAQ.md#which-operating-systems-are-supported)?  The logfile header indicates version 10:
`OS:                   Oracle Solaris 10 8/11 s10s_u10wos_17 SPARC`
also
`uname:SunOS 5.10 Generic_150400-59 sun4v`

**Comment by Kald0** [comment]
My mistake, I originally attached an old core dump, I've updated the issue with the correct file. 

I've created a custom script that reproduces the SolarisCentralProcessor instantiation with debug logs and I wasn't able to reproduce the issue. I think that it happened in the first place because multiple SolarisCentralProcessors were being instantiated in a very short amount of time (without going into too much details, the program that displays this behaviour creates around 10 threads that will each instantiate the class). 

We'll update our architecture to share a single instance of the SolarisCentralProcessor to the threads and update you with the results.

**Comment by dbwiddis** [comment]
Yeah, it's possible the kstat lookup code doesn't support multiple threads.  I know we've had issues in Windows with WMI for that reason.  I thought kstat did more snapshot type things, though; but it's possible that I've not cleanly separated which snapshot each thread is working on.

**Comment by dbwiddis** [comment]
OK, dug into this and I think thread safety is the issue.  Specifically:

> only one thread may actively use a kstat_ctl_t * value at any time. Synchronization is left to the application.

This is used in `KstatUtil` line 45: 
`private static KstatCtl kc = LibKstat.INSTANCE.kstat_open();`
and then used later in `kstat_read()` and `kstat_chain_update()` calls, the latter of which is probably the issue you're seeing as part of the lookups.

I'm thinking that if `kc` can be synchronized, this can be made thread safe.

**Comment by dbwiddis** [comment]
Sledgehammer method:  Add the `synchronized` keyword to `kstatRead()`, `kstatLookup()`, and `kstatLookupAll()` methods.  

Precise method:   Wrap a `synchronize(kc){ ... }` block around all the sections of the code that access `kc`.  (Possibly including the shutdown hook.)  

The Precise method is only slightly narrower in scope, and locks on the `KstatCtl` instance rather than the class itself... but it probably doesn't matter much.

In either case, the `KstatCtl` class should have a javadoc added to it noting that
> only one thread may actively use a KstatCtl value at any time. Synchronization is left to the application.

**Comment by Kald0** [comment]
I implemented the fix on a local branch that we tested on Solaris SPARC and it didn't fix the issue when using a multi-thread context (i.e. multiple threads instantiating the SolarisCentralProcessor). 

I'll update the issue with the new logs asap.

**Comment by dbwiddis** [comment]
Well, darn.  Interested to see the logs.   Is there any possibility of a processor "shutting down" during operation?

**Comment by YoshiEnVerde** [comment]
I'm gonna throw a guess, and point to the fact that there are a few Kstat methods that are still out of sync blocks:
@**oshi/util/platform/unix/solaris/KstatUtil.java:**
_Ln80:_ `         Pointer p = LibKstat.INSTANCE.kstat_data_lookup(ksp, name);`
_Ln124:_ `        Pointer p = LibKstat.INSTANCE.kstat_data_lookup(ksp, name);`

Both calls to `kstat_data_lookup()` are not being syncronized

**Comment by dbwiddis** [comment]
The [thread-safety concern](https://docs.oracle.com/cd/E86824_01/html/E54769/kstat-data-lookup-3kstat.html) is with the `kstat_ctl_t` type, such as in `kstat_lookup()` and not noted for `kstat_data_lookup()`.  I'd be more concerned about whether we're correctly null-checking `ksp` before those calls.

**Comment by Kald0** [comment]
> Is there any possibility of a processor "shutting down" during operation?
Highly unlikely since we were able to reproduce the issue every single run with multiple threads.

**Comment by dbwiddis** [comment]
I've expanded the synchronization to every method on the object.   Can you see if the latest snapshot works?  If not I'll make it a singleton...

**Comment by Kald0** [comment]
I'll give it a try asap, thanks !

**Comment by Kald0** [comment]
It looks like it's working properly since we haven't heard a complaint from our customer after pushing the new snapshot on their platform. I'll update the issue if anything's not ok.

**Comment by dbwiddis** [comment]
Closing this assuming it's fixed.
