### ISSUE TITLE
Getting CPU load per core

### ISSUE THREAD

**Issue by bitbythecron** [oshi/oshi#496]
Two similarly-related questions:

If there are multiple cores, is it possible to get the CPU load (%) for each core individually? I know that the following code will fetch overall system CPU load:

```
SystemInfo sysInfo = new SystemInfo();
CentralProcessor cpu = sysInfo.getHardware().getProcessor();
Double sysLoad = cpu.getSystemCpuLoad();
```

But I'm wondering if (say, on a quad-core machine) I could get 4 different CPU load values, one per core?

Also, similarly, what is the relationship between `cpu.getPhysicalProcessorCount()` and the number of cores on the CPU? Are they the same thing or will each Physical Processor potentially have multiple cores?

**Comment by dbwiddis** [comment]
Physical Processor Count is intended to be cores.   So my personal machine has one CPU package, 4 physical processors (it's a quad core i7) and 8 logical processors (it has hyperthreading).  My work machine has two CPU packages, 4 physical processors (2 cores per CPU package), and 8 logical processors (hyperthreading).

The per-processor results (`cpu.getProcessorCpuLoadBetweenTicks()` or timing between multiple calls of `getProcessorCpuLoadTicks()`) give results for logical processors.   So for my quad-core machine I typically see loads like [10.3 2.1 10.5 1.9 12.1 2.3 11.2 2.2].   Note each successive pair of logical processors represent a physical processor/core.  So the per-core results would technically be [13.4 12.4 14.4 13.4]  in the above example.  See #62. 

We don't (yet) have a mapping of logical processors to physical processors, but I'm ruminating on how to do that in a future version when I do #418, probably by including a `getBitMask()` method on individual processors to help a user correlate them/roll up information like CPU ticks.  In the meantime, it's probably a safe assumption that if logical = 2x double, you can combine successive pairs in the logical processor results to get what you want.

**Comment by bitbythecron** [comment]
Awesome, everything you say makes sense! Thanks again!
