### ISSUE TITLE
vmstat (swap-ins/swap-outs)

### ISSUE THREAD

**Issue by stefan-reich** [oshi/oshi#504]
Hi, a bit of praise again first - I'm using OSHI to show [how much memory](https://www.youtube.com/watch?v=nMRGcamgc_U) my program actually uses which is really useful. :)

Now the question: Can I get the results of vmstat from within OSHI? For example, the number of swap-ins/swap-outs (to see if the machine is swapping and display a warning signal).

**Comment by dbwiddis** [comment]
Seems like something reasonable to add.  Would you like to submit a PR?

macOS and FreeBSD have `sysctl` calls for this, Solaris has a kstat for it, and it's in `/proc/vmstat` on Linux.  Windows has [Win32_PerfRawData_PerfOS_Memory](https://msdn.microsoft.com/en-us/ie/aa394314(v=vs.94)) WMI or from PDH counters.

**Comment by stefan-reich** [comment]
Oh, you mean me coding it? :) IDK... I'm very busy.

**Comment by dbwiddis** [comment]
Aren't we all. :)

I'll probably get around to it sometime as an implementation/test case for #505.

**Comment by dbwiddis** [comment]
Well, started to toy with this, and I see your request is vague. You gave an "example" but there's a ton more information there.  Do you want swaps or pages or both?  In and out separately or summed together?  Probably back-burnering this as the scope's a lot bigger than I thought.

**Comment by stefan-reich** [comment]
Cool to hear! What I want is a simple indicator that says to the user "your system is swapping" in order to warn him/her. Currently I have no indication for swapping other than the system being slow as I use an SSD.

So I don't even need details - all I want to know is whether there was any swapping (in or out) within the last second.

I know you always have to cover 3 totally different OSes (which is great), so it's probably some work regardless.

I'll be happy to see any progress here, even if it's only on some OSes.

**Comment by dbwiddis** [comment]
It's actually pretty easy on all OS's. The bigger question is how many data points to return.  One, two, or four.   For your use case, is number of swaps (of any size) or number of pages swapped more important?  I'm thinking the latter.

**Comment by stefan-reich** [comment]
Yes, that sounds perfect (number of pages)! Maybe even with the page size, but that would already be luxurious. :)

**Comment by dbwiddis** [comment]
#509 adds the pages swapped in or out.  The page size is also already available if you want it in Bytes.

**Comment by stefan-reich** [comment]
Hey, this works nicely. It's now a standard module in my OS. [Screenshot](https://botcompany.de/1004590/raw/1101317) :)

[Module source code](http://tinybrain.de/1016235)

The weird thing is that it slowly counts both some swap-ins and some swap-outs even though swap is not used at all (see screenshot). Hmm....

**Comment by stefan-reich** [comment]
All in all, swap-in seems a lot more useful thatn swap-out. The latter goes up a lot even without actual swapping.

**Comment by dbwiddis** [comment]
Revisiting this in light of #1202 discussion. I was wondering who put in the "pgpgin" and "pgpgout" counters rather than "pswpin" and "pswpout" and realized it was me, about 2 years ago.   Your comment "it slowly counts both some swap-ins and some swap-outs even though swap is not used at all" indicates that I probably chose poorly, and I should change that to actually count "swap file" pages.
