### ISSUE TITLE
Status of notebook lid (open/closed)

### ISSUE THREAD

**Issue by stefan-reich** [oshi/oshi#506]
Hi, is this something for OSHI maybe? Currently I do something like:

```
boolean lidOpen() {
  File f = oneOfTheFiles("/proc/acpi/button/lid/LID/state", "/proc/acpi/button/lid/LID0/state");
  return containsIgnoringCase(loadTextFile(f), "open");
}

```
...which does work fine on Linux. No solution for Windows yet though.

**Comment by dbwiddis** [comment]
This looks fun.  I wouldn't turn down a PR if someone wants to do it.   But I hope you'll understand this is going to probably be at the very tail end of the feature request list. :)

**Comment by dbwiddis** [comment]
I'm going to go ahead and close this, as I think it's mostly out of scope of OSHI. It only seems to be effective on Linux and you've posted the solution in the initial request!  this may be something to consider in OSHI 5 when there is more of an allowance for code only on a single platform.
