### ISSUE TITLE
Cute little fix for battery level

### ISSUE THREAD

**Issue by stefan-reich** [oshi/oshi#512]
On my Linux, the battery level reporting is weird... with a full battery, it tends to display 0% instead of 100%. This is in the OS itself, not an OSHI bug. It really looks stupid though to see "battery level 0%", so I decided to fix the problem.

This little workaround helps in pretty much all conceivable cases (except in the extremely odd one of the program being _started_ with the battery actually being at 0%).

```
static int last = -1;

// We assume actual 0% never appear longer than this many seconds
static WaitForStableValue<Boolean> zeroSince = new WaitForStableValue(60.0);

static double oshi_batteryLevel_withZeroPercentFix() {
  double dd = oshi_batteryLevel();
  if (isNaN(dd)) return dd;
  int d = iround(dd); // Never seen non-int battery levels
  zeroSince.set(d == 0);
  if (d == 0 && (last < 0 || last >= 99 || isTrue(zeroSince.get())))
    d = 100;
  return last = d;
}
```

The code assumes you call the function reasonably often (often enough so you see every 1% increase or decrease). (Actually, this requirement can be relaxed if the 99 is replaced with, say, 90.)

[Full program](http://tinybrain.de/1016136) with helper functions+classes.

**Comment by dbwiddis** [comment]
Looks like a good use case, perhaps good to add to our currently-blank wiki?

**Comment by stefan-reich** [comment]
Done!
