### ISSUE TITLE
General question: How to track the used RAM

### ISSUE THREAD

**Issue by stefan-reich** [oshi/oshi#519]
This isn't 100% OSHI-related, but I really have a need to find out, and the jdk-discuss list is too slow in reacting.

I am tracking down why my Java 10 process is growing beyond bounds.

Please see the attached screenshot: http://ai1.space/1004590/raw/1101327

The 3 important numbers:

-Java heap: 26 MB (Eden + Survivor + Old Gen)
-Total memory pools committed (as reported by getMemoryPoolMXBeans): 122 MB
-Java process size: 786 MB (reported through OSHI library, confirmed by "top" command)

How is the huge difference explained (122 MB to 786 MB)?

Indeed, the third number (process size) keeps growing and growing while the first two numbers roughly stay the same. The application BTW isn't doing much, just updating some numbers. I think the only native library in use is the OSHI library, but I'd have to check that.

How can I investigate where my memory goes? This is crazy. Any more OSHI functions to try out?

**Comment by dbwiddis** [comment]
I'm not quite sure what the question is.  Is OSHI growing, possibly with a memory leak?  Or is it another process?  Or your java process that includes OSHI?

In the past I've had great success using [IBM's Heap Analyzer](https://www.ibm.com/developerworks/community/alphaworks/tech/heapanalyzer).   You get a heap dump of your process and can drill down into the object(s) taking up memory.

**Comment by dbwiddis** [comment]
I believe you reported this in #521 and it was fixed in #522.
