### ISSUE TITLE
OSHI doesn't build on JDK 10

### ISSUE THREAD

**Issue by stefan-reich** [oshi/oshi#523]
Command: `mvn package`

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running oshi.SystemInfoTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.875 s - in oshi.SystemInfoTest
[INFO] Running oshi.util.EdidUtilTest
[ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.013 s <<< FAILURE! - in oshi.util.EdidUtilTest
[ERROR] testGetEdidAttrs(oshi.util.EdidUtilTest)  Time elapsed: 0.007 s  <<< ERROR!
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at oshi.util.EdidUtilTest.<clinit>(EdidUtilTest.java:57)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at oshi.util.EdidUtilTest.<clinit>(EdidUtilTest.java:57)
```
I think an --add-modules VM parameter is needed. See https://github.com/checkstyle/checkstyle/issues/5027

**Comment by YoshiEnVerde** [comment]
Following the link you provided, I believe myself that we'd be better served by explicitly adding the JEE dependencies that were deprecated in Java 9, to avoid any future issues.

**Comment by dbwiddis** [comment]
Or I can rewrite the EdidUtilTest to remove the `javax.xml.bind.DatatypeConverter` import.  We're only using it for convenience to parse a `String` of hex characters to a `byte[]`.  I'm sure we can find a JDK10-compatible version of that.

**Comment by dbwiddis** [comment]
I think [this answer](https://stackoverflow.com/questions/140131/convert-a-string-representation-of-a-hex-dump-to-a-byte-array-using-java) is one I found when first looking to solve this and went with the "20% faster" choice.  But this is a test so speed isn't important.

**Comment by dbwiddis** [comment]
And I've already implemented the above answer in `ParseUtil.hexStringToByteArray()`.  So this should be a trivial fix.

**Comment by dbwiddis** [comment]
Fun fact, I did the string to byte array but not the byte array to string part in `EdidUtil`.
