### ISSUE TITLE
Windows: OSProcess.getCommandLine() almost always blank

### ISSUE THREAD

**Issue by dustin-johnson** [oshi/oshi#526]
It looks like this is an issue with the caching logic at WindowsOperatingSystem.java:385 and WindowsOperatingSystem.java:486. I'll investigate a bit more.

**Comment by dustin-johnson** [comment]
I've cloned this repro and added the below test to the OperatingSystemTest. It fails every time for me on Windows.

```
    @Test
    public void testGetCommandLine() {
        int processesWithNonEmptyCmdLine = 0;

        for (OSProcess process : new SystemInfo().getOperatingSystem().getProcesses(0, null)) {
            if (!process.getCommandLine().trim().isEmpty()) {
                processesWithNonEmptyCmdLine++;
            }
        }

        assertTrue(processesWithNonEmptyCmdLine >= 1);
    }
```

**Comment by dustin-johnson** [comment]
PR up: #527

**Comment by dbwiddis** [comment]
Thanks for the fix!  I won't even pretend to know what I was thinking when I wrote that... I think I re-used a map that had been populated a different way and neglected to check/change the logic.  Or was sleep deprived.  

Gold star for the added unit test.
