### ISSUE TITLE
FileSystemTest fails if usable > total

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#531]
On my corporate network drives, usable space exceeds the value reported as total space:

`US (Z:) (Network drive) [NTFS] 3.9 TiB of 200 GiB free (2000.9%)`

The unit test should exclude the test on line 58 for network drives.

**Comment by trejkaz** [comment]
What on earth, lol... how can there be 3.9 TiB usable, if there is only 200 GiB free. :)

**Comment by dbwiddis** [comment]
I know, right?   Of course, Windows Explorer tells a different story.
![image](https://user-images.githubusercontent.com/9291703/41753206-c8b3b926-7580-11e8-8286-263d2346302e.png)

So maybe the usable/free is wrong.  Oshi gets that from [GetDiskFreeSpaceEx](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364937(v=vs.85).aspx) where the value is a pointer to an unsigned large integer...

**Comment by dbwiddis** [comment]
Ah, that's for local drives.  OSHI gets network drive free space from WMI (Win32_LogicalDisk) which reports the larger number (4296557993984) in its FreeSpace property.  Not sure what's happening under the hood, but this falls into the "not my circus, not my monkeys" category.
