### ISSUE TITLE
Add child thread cpu usage values to OSProcess

### ISSUE THREAD

**Issue by mar1ged** [oshi/oshi#535]
I copied this from the Sysinfo example:

`100d * (p.getKernelTime() + p.getUserTime()) / p.getUpTime()`

I created a process that keeps several cores busy, htop displays this correctly as `390%` (please see the top of the screenshot).
But it seems like I only get the time values of a single thread (bottom of the screenshot), so the accumulated percentage is only `5.4%`.

![image](https://user-images.githubusercontent.com/16045549/41834287-fd07bc6a-7853-11e8-819f-f4c6a7bc5a21.png)

**Comment by dbwiddis** [comment]
The values returned by OSHI are cumulative for the life of the process.  If I recall correctly, htop gives you a snapshot.   Try calculating the kernel+user time differences over a short time period and divide by the elapsed time.

OSHI gets its values from `/proc/<pid>/stat` so if there's an error in parsing, let me know...

**Comment by dbwiddis** [comment]
Continuing from the above, OSHI's Kernel and user time values come from fields 14 and 15.

>               (14) utime  %lu
>                         Amount of time that this process has been scheduled
>                         in user mode, measured in clock ticks (divide by
>                         sysconf(_SC_CLK_TCK)).  This includes guest time,
>                         guest_time (time spent running a virtual CPU, see
>                         below), so that applications that are not aware of
>                         the guest time field do not lose that time from
>                         their calculations.
> 
>               (15) stime  %lu
>                         Amount of time that this process has been scheduled
>                         in kernel mode, measured in clock ticks (divide by
>                         sysconf(_SC_CLK_TCK)).

It appears you want the rollup for all child processes which would be the next two fields:

>               (16) cutime  %ld
>                         Amount of time that this process's waited-for chil‐
>                         dren have been scheduled in user mode, measured in
>                         clock ticks (divide by sysconf(_SC_CLK_TCK)).  (See
>                         also times(2).)  This includes guest time,
>                         cguest_time (time spent running a virtual CPU, see
>                         below).
> 
>               (17) cstime  %ld
>                         Amount of time that this process's waited-for chil‐
>                         dren have been scheduled in kernel mode, measured in
>                         clock ticks (divide by sysconf(_SC_CLK_TCK)).

OSHI does provide the parent PID, so it would be an easy exercise to just roll up the sum of user/system time for the children.

**Comment by dbwiddis** [comment]
Added this capability via a driver in #1124 that puts all the `/proc/pid/stat` output into an EnumMap.  

```
    public static void main(String... args) {
        LinuxOperatingSystem los = new LinuxOperatingSystem();
        int pid = los.getProcessId();

        // Standard OSHI API
        OSProcess p = los.getProcess(pid);
        System.out.println(p.getName() + " parent is " + p.getParentProcessID() + ", priority is " + p.getPriority());

        // Using the driver
        Triplet<String, Character, Map<PidStat, Long>> t = ProcessStat.getPidStats(pid);
        System.out.println(t.getA() + " parent is " + t.getC().get(PidStat.PPID) + ", priority is "
                + t.getC().get(PidStat.PRIORITY));
    }
```
Output:
```
java parent is 18122, priority is 20
java parent is 18122, priority is 20
```
The child CPU usage can be fetched with `PidStat.CUTIME` and `PidStat.CSTIME` keys.
