### ISSUE TITLE
Include inactive interfaces in hal.getNetworkIFs()

### ISSUE THREAD

**Issue by unanao** [oshi/oshi#540]
My computer have two adapter,  enp2s0 not returned.

enp1s0 is “RUNNING”,  bug enp2s0  is not.

enp1s0    Link encap:Ethernet  HWaddr 00:1F:F2:11:ED:52
          inet addr:192.168.88.45  Bcast:192.168.88.255  Mask:255.255.255.0
          inet6 addr: fe80::b34e:5df4:cc03:f3d7/64 Scope:Link
          UP BROADCAST **RUNNING** MULTICAST  MTU:1500  Metric:1
          RX packets:1437602 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1024632 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:753383011 (718.4 MiB)  TX bytes:409751832 (390.7 MiB)

enp2s0    Link encap:Ethernet  HWaddr 00:1F:F2:11:ED:51
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

**Comment by dbwiddis** [comment]
Which operating system?  If an interface is not running, should it be returned?

**Comment by dbwiddis** [comment]
For all Operating Systems, OSHI currently enumerates interfaces via the JRE's objects:
`Enumeration<NetworkInterface> interfaces = NetworkInterface.getNetworkInterfaces();`

OSHI then adds some additional OS-specific information that the Java objects don't have.

In order to collect non-running interfaces we would have to implement OS-specific enumeration of inactive interfaces.  I'd welcome a PR if you would like to submit one.

**Comment by dbwiddis** [comment]
[This StackOverflow thread](https://stackoverflow.com/questions/17698971/networkinterface-getnetworkinterfaces-not-listing-all-interfaces) is directly relevant.

**Comment by unanao** [comment]
Thank you! No ip interface not display is not a bug for us now, If we add the feature, I will pull a request.

**Comment by dbwiddis** [comment]
Closing this issue as it's been over a year and nobody's indicated this is a priority.  Happy to reopen the issue and discuss how to include inactive interfaces if this becomes a needed feature.
