### ISSUE TITLE
Open JDK 7 unsupported major.minor version

### ISSUE THREAD

**Issue by ashishchauhan99** [oshi/oshi#543]
I compiled my java code just one main class to print cpu id etc.. and packed it as Jar. 
This jar works with oracle jdk7-8 but with open jdk 7 I always get this exception:

Exception in thread "main" java.lang.UnsupportedClassVersionError: oshi/SystemIn                                                                                                      fo : Unsupported major.minor version 52.0

![exception](https://user-images.githubusercontent.com/7995939/42382100-89e5f312-8133-11e8-94d9-757e5dbbe080.PNG)

**Comment by YoshiEnVerde** [comment]
Which exact version of the Oracle JDK did you build this with?
That error is for when the binary is not compatible with your JRE version.
In this case, the 52.0 version number means the code was compiled for JRE8 (meaning you used JDK8), but you're running the code in an older JRE

**Comment by dbwiddis** [comment]
Looks like @YoshiEnVerde has answered most of this.  You've compiled the jars using Java 8 so it's failing at runtime on Java 7.

As an aside, I see you're using OSHI to generate a License Key.  Note some of OSHI's output, particularly "serial number" type information that supports licencing, is a "best effort" method with various backups and can differ, particularly on Linux, based on whether it's running with root/sudo permission.  This is specifically called out in the javadoc.   Not sure how you're using the info but wanted to draw your attention to that issue!
