### ISSUE TITLE
How can I get the adapter's name (nickname) from my network interfaces?

### ISSUE THREAD

**Issue by Davis8988** [oshi/oshi#544]
Hello,
I am trying to retrieve the network interface's nickname which is assigned to it. For example the famous "Local Area Connection" name. 
I want to be able to match the information on the interface to the right adapter via the name, but I couldn't find any way to get this value using OSHI.
 
I am using Windows 10 Home x64. 
Thank you

**Comment by dbwiddis** [comment]
I don't think we grab that information in OSHI.  

It is possible to run the command line `netsh intrface ipv4 show interface` and parse out the Index (Idx) and Name.  The index will correspond to the OSHI object's index.

**Comment by TheSFReader** [comment]
For later searches, (in current version) I think I found it in newer versions in the "ifAlias" field (but only filled if Vista or later)
