### ISSUE TITLE
Selectively updating attributes

### ISSUE THREAD

**Issue by cilki** [oshi/oshi#548]
I'm not sure what's in store for #365, but I think it would be nice to be able to update attributes independently in the new 4.0.0 architecture. This would be helpful for streaming particular properties of a device.

**For example:**
Updating a `NetworkIF` via `updateNetworkStats()` seems to read 14 `/sys/` files on Linux, but I may only care about a few of them. The extra work may add up to become noticeable if there are many virtual interfaces, especially when the polling rate increases, but I have not done any benchmarks to support this.

**Comment by dbwiddis** [comment]
Hey @cilki, thanks for the comment.  I'm not sure what's in store for #365 either... and have been musing about building the new structure myself.    I agree we shouldn't read more than what we need to, and have tried to do that (in general) when I write code.

**Comment by cilki** [comment]
@dbwiddis I'll see if I can come up with any novel ideas. The model proposed by @YoshiEnVerde seems like the right direction and I'll try to extend it.

**Comment by dbwiddis** [comment]
One thing to think about regarding updates:  many of the objects OSHI provides are one-time copies, which are thrown away and new objects created the next polling cycle.  The object creation overhead is probably a bigger concern here than reading `/sys`.  One thing I'd like to consider in the newer design is keeping objects cached internally and returning the actual object to users, allowing them to refresh just that object (or a map or list of them).

**Comment by cilki** [comment]
@dbwiddis Absolutely. Does OSHI provide internal polling? I'm not very familiar with the code yet, but it appears the burden is on the user to do that manually. I'm just contemplating a usage where the user gives OSHI a polling frequency and a callback which is notified when the value changes.

**Comment by dbwiddis** [comment]
No; that burden is on the user. If we did create a UI allowing polling, we would want that in a separate artifact, but allow the base project to still return individual values on-demand.  I would envision something like how the Windows PerfMon program provides the GUI and allows users to add metrics from a drop down menu, which it then polls... but each pull of data goes to the source counters (in our case, OSHI would provide the equivalent.)

I do have a long term vision of building a [Metrics](https://metrics.dropwizard.io/4.0.0/)-based interface with polling, averages, trends, and a GUI.)  #249 is an example of how that could be done on a per-attribute basis (also enabling JMX) and I think the way we currently use `Properties` in the JSON configuration is a good concept for how to think about that (recurisvely parsing each dot-delimited string to get to the value(s) we need).

Also, I'd want to replace our current hamhanded JSON parsing with a much cleaner solution integrating [Jackson](https://github.com/FasterXML/jackson) which would include JSON, XML, or other serialization capability (See #206).

So there ya go.   High level interface should be easy to seamlessly integrate to Jackson and Metrics.  Low level needs to separate the API from the details of the implementation and be smart about when to update and avoid recycling objects so much.  Easy, right?

**Comment by cilki** [comment]
@dbwiddis Is the minimum supported Java version going to increase with OSHI 4?

**Comment by dbwiddis** [comment]
Closing this as it's being actively worked as part of the new API and will be tracked in #771
