### ISSUE TITLE
WindowsDisk().getDisks() not work 

### ISSUE THREAD

**Issue by zolt** [oshi/oshi#550]
Hello. I'm trying to get information about disks on Windows.
WindowsDisk().getDisks() throws 
`Exception in thread "main" java.lang.IllegalArgumentException: Allocation size must be greater than zero
        at com.sun.jna.Memory.<init>(Memory.java:111)
        at oshi.jna.platform.windows.PdhUtilJNA.PdhEnumObjectItemInstances(PdhUtilJNA.java:173)
        at oshi.hardware.platform.windows.WindowsDisks.populateReadWriteMaps(WindowsDisks.java:252)
        at oshi.hardware.platform.windows.WindowsDisks.getDisks(WindowsDisks.java:197)
        at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getDiskStores(WindowsHardwareAbstractionLayer.java:82)`

Target OS: 

- Windows Server 2008 R2 SP1 (Enterprise) build 7601
- Windows 10 build 17134

What am I doing wrong?

**Comment by dbwiddis** [comment]
OSHI assumes it can get read/write information from the Performance Counters.  This is obviously failing in your case.  Possibilities:  (1) Performance Data disabled.  (2) Non-English locale.

Can you run `PerfMon.exe` and see if you have any counter entries for `PhysicalDisk`?

In any case, I need to zero-check the result in the Util method...

**Comment by zolt** [comment]
Right, I have no one counter entries... After adding counters the error has disappeared. I think we need zero-check and do warnings when trying to get read/write information.

**Comment by dbwiddis** [comment]
I already fixed the zero-check in #551, which will ultimately result in zero data in OSHI for reads, writes, and transfer time.  

Had you specifically turned off performance data? I'm not sure what you mean by "adding counters" to turn them back on.  And whether I should investigate a backup source for that data (I would guess if performance counters are off, the WMI data isn't present either.)
