### ISSUE TITLE
Question: Any idea how i could get the Oshi informations from the POM?

### ISSUE THREAD

**Issue by Sami32** [oshi/oshi#570]
Also if the OS total RAM size information is my goal i could always parse all the Oshi informations.

Is there is a way to get these informations from the pom.xml file, perhaps using some Maven plugin like Groovy?

**Comment by cilki** [comment]
pom.xml contains build and distribution information, not system info. You should never parse it yourself because that's what Maven does.

**Comment by dbwiddis** [comment]
The POM is just a text file telling Maven how to build the project.  You need to include oshi into your project, either by adding as a dependency in Maven, Gradle, or whatever your build system is, or by downloading the jar file and putting it on your classpath.  Then see examples in the `SystemInfoTest.java` file on how to get individual fields from java code.

**Comment by Sami32** [comment]
Thank you for having taken the time to answer me +1

It is already done in our Java code.
I was just searching a way to get the RAM size information to use it for compare it and depending on the size set a specific Java heap size value in the JVM configuration for the macOS package build. It that i'll have to find a way to avoid hardcoding it as it is now.

**Comment by dbwiddis** [comment]
If you're just looking for a value to put in your JVM configuration, you can probably script some command line retrievals.  `sysctl hw.memsize` gives total memory on macOS.  The `vm_stat` command gives a lot more detail on available memory, etc.

**Comment by Sami32** [comment]
Thank you very much for sharing your knowledge 👍

**Comment by Sami32** [comment]
My problem is that the macOS installer used doesn't have script ability and that the builds are done on Windows and Linux for now. It is why i searched a way to get that information from an OS independant point of view.

Any other idea?

**Comment by dbwiddis** [comment]
Bootstrap with a version of OSHI (or OSHI-Json) that only gets the memory info or writes it to a file. That will have a predictably small memory footprint.  Then launch the full version.  

Also if you only need total memory, the OperatingSystemMXBean in core java is probably sufficient.

**Comment by Sami32** [comment]
Good idea. I guess that now i have the main card to play with ;)

It is why i try to stay away from Sun OperatingSystemMXBean, because Oracle will soon stop to provide any free JVM AFAIK.
