### ISSUE TITLE
When Paging File is disabled WindowsGlobalMemory shows error message

### ISSUE THREAD

**Issue by gulzarsingh12** [oshi/oshi#572]
![capture](https://user-images.githubusercontent.com/6365923/43387581-64843e50-9419-11e8-8955-dbec6a484790.JPG)
As you can see the above line is used to get the Paging file Usage counter. In my machine, i have disabled paging file due to performance reasons for project i am working on or have enough RAM. So when i do call  below method
![image](https://user-images.githubusercontent.com/6365923/43387722-c63122b2-9419-11e8-9031-438c92c4eb22.png)
It is failing on below line
![image](https://user-images.githubusercontent.com/6365923/43387812-08a3a76e-941a-11e8-8417-4a8c6b488154.png)
In my case, i am monitoring the system performance peridocally after 1 min, so it is always showing the error message 
No data to return. (Performance Counter error **0x800007D5**)
From the log error message , i can find out that paging is disabled and i should not call these methods. Can you please add explicitly some method or api call to know this and dont call this method to get swapUsed and swapTotal and dont fill logs uncessary in that. Also i cant inhrerit this WindowsGlobalMemory class to do it myself and i dont want to maintain a copy of this also in my code due to maintence reasons.

Please let me know if the issue is not clear and you need further information

**Comment by dbwiddis** [comment]
Thanks for the detailed report.

I assume the "swap total" value returns 0, and it makes sense not to ask for a percent usage of 0 with that simple check.  That would avoid the problem for your use case.

Also, note that you can also suppress the log message by setting the log level for the PdhUtil class to FATAL.

**Comment by dbwiddis** [comment]
I was easily able to reproduce this and test some fixes.  Just did two PRs to fix this. #573 is specific to your use case and won't bother to get swap counters if there's no swap file.  #574 will maintain a list of PDH counters that fail and only give a one-time error, suppressing future updates unless the counter is reset (removed and re-added).  So that will eliminate log-spam for any other counters with similar issues.

Merging the PRs now, won't be able to publish to snapshot for a few hours, though.

**Comment by gulzarsingh12** [comment]
Thanks a lot for your consideration and fixing the bug. When will this fix be released?

**Comment by dbwiddis** [comment]
It's up in SNAPSHOT now.  I'll probably cut a patch release in a few days once I finish some housekeeping chores.

**Comment by gulzarsingh12** [comment]
Thanks for information. You guys are doing great job.
