### ISSUE TITLE
Is there a plan to support Raspbian?

### ISSUE THREAD

**Issue by weborld** [oshi/oshi#576]
Is there a plan to support Raspbian?

**Comment by dbwiddis** [comment]
I'd love to support Raspbian.  Also AIX. Also Android.  I do not have a development environment in any of the above. :)

The current Linux support should do most of it for Raspbian, but I'm reliant on users testing and submitting bug reports.

What doesn't work now?  Can you submit a PR to fix it?

**Comment by dbwiddis** [comment]
Hi, @weborld. Can you tell me what doesn't work on Raspbian with the current Linux branch?

**Comment by dbwiddis** [comment]
Checking in again. Is there a specific feature that doesn't work on Raspbian?  OSHI works on most Linux distributions including Debian.  I know some features aren't available on Raspbian but my efforts to set up a test VM have failed, so I'm in need of actual Raspbian users to identify what doesn't work.   If you'd like support I need specific things that I can fix...
