### ISSUE TITLE
"Failed to add PDH counter" on some machines

### ISSUE THREAD

**Issue by SadiinsoSnowfall** [oshi/oshi#578]
A lot of "Failed to add PDH Counter" errors are logged when running the test program on my PC, but the same program run fine without any errors on my AWS VM.

exemple of errors logged (trying to access memory informations) : 
```
[main] ERROR oshi.util.platform.windows.PerfDataUtil - Failed to add PDH Counter: \Mémoire\Pages en entrée/s, Error code: 0xC0000BB8
[main] ERROR oshi.util.platform.windows.PerfDataUtil - Failed to add PDH Counter: \Mémoire\Pages en sortie/s, Error code: 0xC0000BB8
[main] ERROR oshi.util.platform.windows.PerfDataUtil - Failed to add PDH Counter: \Fichier d?échange(_Total)\Pourcentage d?utilisation, Error code: 0xC0000BB8
```
my system details : 
Windows 10 x64 - french
JDK 10.0.2

**Comment by dbwiddis** [comment]
Can you run the Windows Performance Monitor (`perfmon.exe`) on your PC and try to add the counters producing the errors, and identify what the correct string for them is?

**Comment by SadiinsoSnowfall** [comment]
I can only get the french versions of the counter strings : 
"\Mémoire\Écritures de pages/s" and "\Mémoire\Lecture de pages/s".

Also, I can't add any of the counter related to the swap file ("fichier d'échange") in perfmon.

**Comment by dbwiddis** [comment]
It looks like using only PDH counters for your setup isn't going to work.  For the time being, you should be able to use version 3.5.0 on your PC.  I will have to look into adding the older (slower) WMI version as a fallback when counters don't work.

**Comment by SadiinsoSnowfall** [comment]
Thank you for your answer.

I also notice that even if errors are being thrown, all the functions seem to return a correct result. Example : the GlobalMemory#getAvailable() function return the correct amount of free memory on my test setup. Maybe the PDH counters are not needed by this function. In this case, is there a way to disable the error logging ?

**Comment by dbwiddis** [comment]
For memory, the PerfMon counters are only used for swap file reads/writes and percent usage, so you're probably getting zero for those results.   

I believe you should only get those errors one time, but if you still want to suppress the errors, you can set the log level for the class `oshi.util.platform.windows.PerfDataUtil` to FATAL in your logging setup.

**Comment by SadiinsoSnowfall** [comment]
Ok, thanks.

**Comment by thoniTUB** [comment]
Hey, I got a similar Problem regarding the CPU, memory and pagefile

> ERROR [2018-08-09 18:02:30]	o.u.p.w.PerfDataUtil		Failed to add PDH Counter: \Prozessor(_Total)\Interruptzeit (%), Error code: 0xC0000BB8
ERROR [2018-08-09 18:02:30]	o.u.p.w.PerfDataUtil		Failed to add PDH Counter: \Prozessor(_Total)\DPC-Zeit (%), Error code: 0xC0000BB8
ERROR [2018-08-09 18:02:30]	o.u.p.w.PerfDataUtil		Failed to add PDH Counter: \System\Kontextwechsel/s, Error code: 0xC0000BB9
ERROR [2018-08-09 18:02:30]	o.u.p.w.PerfDataUtil		Failed to add PDH Counter: \Prozessor(_Total)\Interrupts/s, Error code: 0xC0000BB8
ERROR [2018-08-09 18:02:30]	o.u.p.w.PerfDataUtil		Failed to update counters. Error code: 0x800007D5
ERROR [2018-08-09 18:02:30]	o.u.p.w.PerfDataUtil		Disabling future updates for \Processor(_Total)\% Interrupt Time. Call removeCounter and addCounter again to reset.
ERROR [2018-08-09 18:02:30]	o.u.p.w.PerfDataUtil		Failed to update counters. Error code: 0x800007D5
ERROR [2018-08-09 18:02:30]	o.u.p.w.PerfDataUtil		Disabling future updates for \Processor(_Total)\% DPC Time. Call removeCounter and addCounter again to reset.
ERROR [2018-08-09 18:02:31]	o.u.p.w.PerfDataUtil		Failed to add PDH Counter: \Arbeitsspeicher\Seiteneingabe/s, Error code: 0xC0000BB8
ERROR [2018-08-09 18:02:31]	o.u.p.w.PerfDataUtil		Failed to add PDH Counter: \Arbeitsspeicher\Geänderte Seiten/s, Error code: 0xC0000BB8
ERROR [2018-08-09 18:02:31]	o.u.p.w.PerfDataUtil		Failed to add PDH Counter: \Auslagerungsdatei(_Total)\Belegung (%), Error code: 0xC0000BB8
<

I coudn't find any counters for those in the perfmon.exe.

**Comment by thoniTUB** [comment]
Thanks for the quick reply!
Unfortunately only the first command works for me. The other two answer, that the alias wasn't found.

[wmic.txt](https://github.com/oshi/oshi/files/2275581/wmic.txt)

**Comment by thoniTUB** [comment]
Oh, seems to make a difference, if you use the wmi cli or just pass the arguments to wmic. Here is the result of the other two commands
[wmic2.txt](https://github.com/oshi/oshi/files/2275609/wmic2.txt)

**Comment by dbwiddis** [comment]
@thoniTUB thank you!    So it looks like WMI has the PerfData even if it's not accessible via performance counters.

I'll do some thinking on how best to handle this. Right now I'm leaning toward a specialized "PerfDataWmi" class that can transparently serve as a backup source for data from the PerfMon counters.  This will try to lean in the direction of having "source data drivers" as envisioned for OSHI 4.0.0.  (@YoshiEnVerde and @cilki I'd appreciate your input on a good design for "try faster option A and use option B if that didn't work").

**Comment by dbwiddis** [comment]
More design thoughts, making notes for myself (or others) here:
- both PDH and WMI are different "syntax" for what's essentially a database query.
  - PDH counter names are `\Object(Instance)\Counter` which correlate directly with WMI Perfadata tables "SELECT Counter FROM Object WHERE Instance=x"
- PDH counter names are localized for non-English Windows versions, and while some work, many do not
- WMI english table names are consistent in non-English versions (they have localized tables referring to/deriving from the English ones) and are a good backup source
- For WMI, because of query overhead it's better to query a table once and get the data (rows=instance, columns=counters) than do a bunch of individual queries.  We haven't optimized PerfData counters to retrieve this way for most counters but they are capable of doing so and we have done so (partially) for CPU ticks.  
  - From a user perspective, we just want the rows and columns and don't care where they came from
  - For performance data they will always be numeric
  - The design should look similar to the existing WMIResult class which can be populated from multiple sources, either the WMIQuery or a new similar interface we'll make for PDH, and generically specify the Object(PDH)/Table(WMI) and Counter(PDH)/Column(WMI) and optionally a filter on the Instance(PDH)/Row(WMI).

**Comment by dbwiddis** [comment]
@thoniTUB and @SadiinsoSnowfall 

I've just merged #588 which should do a good job of testing PDH counters and using WMI as a fallback when the counters aren't available.   I'd appreciate it if you can test the latest SNAPSHOT and see if it resolves your problems.

**Comment by SadiinsoSnowfall** [comment]
I have run the "SystemInfoTest" class on my machine using the latest snapshot (3.8.0, built by using maven on the main branch).

There are still some errors related to PHD counters : 

`[main] WARN oshi.util.platform.windows.WmiUtil - WMI class Win32_Csproduct not found, ignoring further requests.

Checking Processor...
[main] ERROR oshi.util.platform.windows.PerfDataUtil - Failed to add PDH Counter: \Système\Changements de contexte/s, Error code: 0xC0000BB8
[main] WARN oshi.util.platform.windows.PerfDataUtil - Failed to add a counter for PDH: \Système\Changements de contexte/s
[main] ERROR oshi.util.platform.windows.PerfDataUtil - Failed to add PDH Counter: \Processeur(0)\% temps DPC, Error code: 0xC0000BB8
[main] WARN oshi.util.platform.windows.PerfDataUtil - Failed to add a counter for PDH: \Processeur(0)\% temps DPC
[main] WARN oshi.hardware.platform.windows.WindowsCentralProcessor - Unable to enumerate performance counter instances for Processeur.

Checking Memory...
[main] ERROR oshi.util.platform.windows.PerfDataUtil - Failed to add PDH Counter: \Mémoire\Pages en entrée/s, Error code: 0xC0000BB8
[main] WARN oshi.util.platform.windows.PerfDataUtil - Failed to add a counter for PDH: \Mémoire\Pages en entrée/s
[main] ERROR oshi.util.platform.windows.PerfDataUtil - Failed to add PDH Counter: \Fichier d?échange(_Total)\Pourcentage d?utilisation, Error code: 0xC0000BB8
[main] WARN oshi.util.platform.windows.PerfDataUtil - Failed to add a counter for PDH: \Fichier d?échange(_Total)\Pourcentage d?utilisation

Checking Sensors...
[main] ERROR oshi.util.platform.windows.PerfDataUtil - Failed to add PDH Counter: \Informations de zone thermique(\_TZ.THRM)\Temperature, Error code: 0xC0000BB8
[main] WARN oshi.util.platform.windows.PerfDataUtil - Failed to add a counter for PDH: \Informations de zone thermique(\_TZ.THRM)\Temperature

Checking Disks...
[main] ERROR oshi.util.platform.windows.PerfDataUtil - Failed to add PDH Counter: \Disque physique(0 C:)\Lectures disque/s, Error code: 0xC0000BB8
[main] WARN oshi.util.platform.windows.PerfDataUtil - Failed to add a counter for PDH: \Disque physique(0 C:)\Lectures disque/s
[main] WARN oshi.hardware.platform.windows.WindowsDisks - Unable to enumerate performance counter instances for Disque physique

Checking File System...
[main] ERROR oshi.util.platform.windows.PerfDataUtil - Failed to add PDH Counter: \Processus(_Total)\Nombre de handles, Error code: 0xC0000BB8
[main] WARN oshi.util.platform.windows.PerfDataUtil - Failed to add a counter for PDH: \Processus(_Total)\Nombre de handles
`

**Comment by dbwiddis** [comment]
It's a good thing I went to hunt down that log message and realized I'm using [PdhAddEnglishCounter](https://docs.microsoft.com/en-us/windows/desktop/api/pdh/nf-pdh-pdhaddenglishcountera) which handles the localization.  So I shouldn't have even been messing with translations!  Let me get another SNAPSHOT up for you...

**Comment by dbwiddis** [comment]
So the only localization needed is for instance enumeration, which looks like it did work (if I wasn't silly enough to then try to add the translated name).  Can you check the latest SNAPSHOT?

**Comment by thoniTUB** [comment]
I have some dependency problems when the snapshot is added to my local maven repro.
When I add it with:
```
mvn install:install-file -Dfile=C:\...\oshi-core-3.8.0-20180820.014240-18.jar -DgroupId=com.github.oshi -DartifactId=oshi-core -Dversion=3.8.0-SNAPSHOT -Dpackaging=jar
```

And start the program it crashes with:
```
java.lang.NoClassDefFoundError: com/sun/jna/Platform
	at oshi.SystemInfo.<clinit>(SystemInfo.java:59)
        ...
```

When I look into the snapshot's pom, that appears on installation, I can see the jna dependency.
```
		<dependency>
			<groupId>net.java.dev.jna</groupId>
			<artifactId>jna-platform</artifactId>
			<version>4.5.2</version>
		</dependency>
```

This is probably not related to the actual bug, but it stops me from testing the snapshot.

I would appreciate, if you could hint me, where I'm doing the mistake.

**Comment by SadiinsoSnowfall** [comment]
Ok, I have just tried the latest version. There is no PDH errors anymore but there is still a problem with some values such as "CPU load averages", "process list > cpu usage", "fan speed", "cpu voltage". Everything else seems ok.

```
Checking CPU...
Uptime: 2 days, 07:44:42
Context Switches/Interrupts: 113064 / 88569
CPU, IOWait, and IRQ ticks @ 0 sec:[43993875, 0, 15677152, 768251609, 0, 468126, 157503, 0]
CPU, IOWait, and IRQ ticks @ 1 sec:[43993953, 0, 15677183, 768259500, 0, 468126, 157503, 0]
User: 1,0% Nice: 0,0% System: 0,4% Idle: 98,6% IOwait: 0,0% IRQ: 0,0% SoftIRQ: 0,0% Steal: 0,0%
CPU load: 2,8% (counting ticks)
CPU load: 7,2% (OS MXBean)
CPU load averages: N/A N/A N/A
CPU load per processor: 1,4% 7,8% 0,0% 8,0% 6,2% 3,1% 4,6% 6,1%
Checking Processes...
Processes: 166, Threads: 2306
   PID  %CPU %MEM       VSZ       RSS Name
  1016   NaN  0,0  56,8 MiB   0 bytes svchost.exe
  3708   NaN  0,0  70,9 MiB   0 bytes svchost.exe
  6460   NaN  0,0  50,6 MiB   0 bytes dasHost.exe
  6456   NaN  0,0  94,0 MiB   0 bytes svchost.exe
     0 100,0  0,0     4 KiB   0 bytes
Checking Sensors...
Sensors:
 CPU Temperature: 48,0°C
 Fan Speeds: [0]
 CPU Voltage: 0,0V
```

**Comment by SadiinsoSnowfall** [comment]
@thoniTUB Try downloading the main branch, then build it using "mvn clean install -DskipTests".

**Comment by thoniTUB** [comment]
Thanks, it's looking good so far on my machine, though I haven't looked into stats like 'CPU load averages' yet.

**Comment by dbwiddis** [comment]
Glad all the counters are working. Ironically that may mean wasted time coding the WMI backup. Oh, well! It's in now.

Load averages are not relevant on Windows so that's expected,  The voltage and fan sensors, are similarly not usually populated (you could install OpenHardwareMonitor).  The process CPU, however, is definitely odd. I'll have to look into that. I wonder if it's related to #580, because I didn't touch the process CPU code with the latest changes.

**Comment by dbwiddis** [comment]
The process CPU code looks sensible on my machine.  It's possible those four processes had such a short uptime that it calculated as zero.  I've just pushed a commit to enforce a minimum 1ms uptime.  Can you test your processes against SNAPSHOT again?
