### ISSUE TITLE
How I get "system uuid" ?

### ISSUE THREAD

**Issue by Dianlandu** [oshi/oshi#581]
by the method below I can get Linux info system-serial-number and  baseboard-serial-number :
### ### ### ### ### 
    private static void printSystemInfo(ComputerSystem system) {
        System.out.println("system-serial-number: " + system.getSerialNumber());
        System.out.println("baseboard-serial-number: " + system.getBaseboard().getSerialNumber());
    }
### ### ### ### ### 
just like I use "dmidecode -s system-serial-number" and "dmidecode -s baseboard-serial-number". 
But how I can get "system-uuid" like I exec "dmidecode -s system-uuid" in Linux?

I'm eager to find a way to get "system-uuid".
Thank you! Best wishes!

**Comment by dbwiddis** [comment]
OSHI doesn't specifically fetch the system uuid.   We try to stick to cross-platform implementations and Linux has a few more options than other OSes. You're welcome to use the `ExecutingCommand` classes to fetch from the command line and parse it yourself.

**Comment by Dianlandu** [comment]
Thank you for your replying so quickly. I will try making it by some other method.
Good luck!


| |
杜明桥
|
|
dianlandu@163.com
|
签名由网易邮箱大师定制
On 8/8/2018 22:07，dbwiddis<notifications@github.com> wrote：

OSHI doesn't specifically fetch the system uuid. We try to stick to cross-platform implementations and Linux has a few more options than other OSes. You're welcome to use the ExecutingCommand classes to fetch from the command line and parse it yourself.
