### ISSUE TITLE
WindowsOperatingSystem.getProcess or getProcesses freezes indefinitely if run as windows service

### ISSUE THREAD

**Issue by gulzarsingh12** [oshi/oshi#584]
Hi,
I am running my java application as windows service using apache procrun. there is issue in oshi api when we do getProcesses or getProcess then it freezes and never come back. i couldsnt see anything getting print in my log after these calls. Please check this issue.

**Comment by dbwiddis** [comment]
We have earlier had reports of delays/hangs when OSHI starts as a service before WMI has fully started.  See #441.  In that case, changing the service from auto start to delay start fixed the problem.

As a debugging step, can you try manually starting the service after the rest of Windows starts up and see if it works then?   If so, either the delay start, or writing a registry key to have the service depend on the WMI service(s) can make a more permanent solution.

**Comment by dbwiddis** [comment]
It's clear that the issue is with WMI.   It's not clear what is different about your system than most other people.

**Comment by dbwiddis** [comment]
Right now OSHI has an infinite timeout on WMI calls. I could modify the code to put in a timeout but that would just return blanks/empty and while it wouldn't hang your system, you'd still have no more information than if you just didn't make the problematic WMI calls to begin with.

You need to investigate why WMI is not running/returning information on your system.  Try this at a command prompt:
`wmic OS get Caption,BuildNumber`

If you get results, I'll investigate OSHI more.  If you don't, then you might need to troubleshoot your WMI installation.

**Comment by gulzarsingh12** [comment]
Hi i tested on both windows 7, and 10. Its not working. 
find below the output of your command, which is actually working.
![image](https://user-images.githubusercontent.com/6365923/43988638-cfe570e0-9d6c-11e8-913c-391c24579d9e.png)

![image](https://user-images.githubusercontent.com/6365923/43988640-dc1963e4-9d6c-11e8-9b51-2255d770617a.png)



Please have timeout as feature otherwise it is very difficult and application freezes.

**Comment by dbwiddis** [comment]
Are you able to fork the code and make some small edits to test?   You could change [line 409 of the current `WmiUtil.java` class](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/util/platform/windows/WmiUtil.java#L409):

`queryWMI(query, EnumWbemClassObject.WBEM_INFINITE);`

Replace the infinite with some number of milliseconds.  5000 should be sufficient.  

If you're unable to fork it and compile yourself I can put up a snapshot with this change for you to try.

**Comment by dbwiddis** [comment]
Actually I did just make a temporary change in SNAPSHOT to timeout after 10 seconds.  I'm not overly optimistic it'll be the final fix but it should at least give us some progress in diagnosing what's wrong.

**Comment by gulzarsingh12** [comment]
Still not working... i set queryWMI(query, 10000);
10 secs, still not coming back. it is still stuck

**Comment by gulzarsingh12** [comment]
I tried to take thread dump also to find where my code is stuck but no luck couldnt find any trace. Please suggest something

**Comment by gulzarsingh12** [comment]
Hope this helps. This is log when run the code inside threadpool with timeout

Code:
/**
     * To update the metrics of cas processes
     */
    @Override
    public void updateProcessMetrics() {
        Map<Integer, CasProcess> casProcessMap = casAgentDataStore.getCasProcessMapByPid();
        if (isEmpty(casProcessMap)) {
            log.debug("No cas processes running.");
            return;
        }
        log.info("updateProcessMetricsCallable called");
        ListenableFuture<List<OSProcess>> future = taskExecutor.submitListenable(() -> updateProcessMetricsCallable(casProcessMap.keySet()));
        try {
            List<OSProcess> childProcesses = future.get(5, TimeUnit.SECONDS);
            log.info("updateProcessMetricsCallable finsihed");
            if (CollectionUtils.isNotEmpty(childProcesses)) {
                long totalMemory = getOSTotalMemory();
                for (OSProcess osProcess : childProcesses) {
                    updateProcessMetric(casProcessMap.get(osProcess.getProcessID()), osProcess, totalMemory);
                }
            }
            log.info("metrics updated");
        } catch (Exception e) {
            log.error("Failed to update ProcessMetrics.", e);
        }
    }

    private List<OSProcess> updateProcessMetricsCallable(Collection<Integer> pids) {
        return getProcesses(pids);
    }

Log:
===
11 Aug 2018 15:41:25 [pool-1-thread-1     ] ERROR .i.ProcessMonitorOperationImpl - Failed to update ProcessMetrics.
java.util.concurrent.ExecutionException: java.lang.Error: Invalid memory access
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.numerix.cas.agent.startup.monitoring.impl.ProcessMonitorOperationImpl.updateProcessMetrics(ProcessMonitorOperationImpl.java:162)
	at com.numerix.cas.agent.startup.monitoring.impl.CasProcessMonitorImpl$ProcessMonitorRunnable.run(CasProcessMonitorImpl.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Error: Invalid memory access
	at com.sun.jna.Native._getPointer(Native Method)
	at com.sun.jna.Native.getPointer(Native.java:2138)
	at com.sun.jna.Pointer.getPointer(Pointer.java:651)
	at com.sun.jna.platform.win32.COM.COMInvoker._invokeNativeObject(COMInvoker.java:45)
	at oshi.jna.platform.windows.COM.WbemServices.ExecQuery(WbemServices.java:37)
	at oshi.util.platform.windows.WmiUtil.selectProperties(WmiUtil.java:641)
	at oshi.util.platform.windows.WmiUtil.queryWMI(WmiUtil.java:457)
	at oshi.util.platform.windows.WmiUtil.queryWMI(WmiUtil.java:409)
	at oshi.software.os.windows.WindowsOperatingSystem.processMapToList(WindowsOperatingSystem.java:434)
	at oshi.software.os.windows.WindowsOperatingSystem.getProcesses(WindowsOperatingSystem.java:281)
	at com.numerix.cas.agent.sys.SysProcessUtil.getProcesses(SysProcessUtil.java:60)
	at com.numerix.cas.agent.startup.monitoring.impl.ProcessMonitorOperationImpl.updateProcessMetricsCallable(ProcessMonitorOperationImpl.java:177)
	at com.numerix.cas.agent.startup.monitoring.impl.ProcessMonitorOperationImpl.lambda$updateProcessMetrics$0(ProcessMonitorOperationImpl.java:160)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

**Comment by gulzarsingh12** [comment]
Finally, i am able to resolve the issue. To fix my issue with  **java.lang.Error: Invalid memory access**
I have to use new object everytime. like **new SystemInfo().getOperatingSystem().getMemory()**
i have to do this for all my calls, so i suspect, you are reusing some objectsreferences which are pointer and corrupting native memory address. It will be super great if you fix these issue. Also i am waiting for 3.8.0 release for cpu uptime you fixed in another issue.
I have one more request, please expose some method to hook my shutdown method. In windows, there is no graceful shutdown so i call jmx on my api to shutdown my resources. Can you please expose similar method. for example in PerfDataUtil, you can expose that method and call same in your shutdown hook. Otherwise i can manually call to release resources.
I will be grateful to you if you could add this feature

**Comment by dbwiddis** [comment]
Thanks for your patience and detailed information!   

I actually have a PR in to the JNA project submitting much of this WMI code, and code review there has identified an issue in me directly constructing `BSTR` from Java Strings rather than allocating native memory for them.  I don't know if they are the root cause of the issues you're seeing, but based on the stack trace it seems a likely culprit (e.g., I keep the `BSTR` object but if I recycle the underlying Java String I think that could be the problem.)

I'll look into making resource releasing more public. You're also welcome to submit a PR to the project for this, so you're not relying on a single volunteer non-SDE hobbyist coder to have spare time. :)

**Comment by gulzarsingh12** [comment]
Sure Sir, I can contribute. i can submit a PR.

**Comment by gulzarsingh12** [comment]
I have created the patch for my changes which you can review and commit. If you want me to fork the repository and then create pull request please let me know but this was easy for me. you can review this and check-in
[releaseResources.zip](https://github.com/oshi/oshi/files/2280907/releaseResources.zip)

Please let me know if anything required.

**Comment by dbwiddis** [comment]
In general a fork and pull request is preferred so you can get credit as a contributor.

**Comment by dbwiddis** [comment]
Did the PerfData patch (better version) as #586

**Comment by gulzarsingh12** [comment]
@dbwiddis Thanks a lot for considering my idea. I am happy to see that you added/exposed removeAllCounters and unInitCOM. This should help what asked for.
I just pull the code and will test your changes to see if it works.

BTW , do i need to call this along with unInitCOM
**OleAuto.INSTANCE.SysFreeString(WQL);**
I saw this in shutdown hook?

**Comment by dbwiddis** [comment]
Please pull the code again... I realized I made an error in the removeAllCounters iterator and I did a fixup commit and you may not have grabbed it.  If you get a `ConcurrentModificationException` it's already fixed. I hope :)

The static variable WQL allocates native memory for a `BSTR` containing the string "WQL".  It's needed for every single WMI query so it'd be silly to constantly re-allocate it.  If you are absolutely sure you'll never use the util class again, you can free that memory.

**Comment by gulzarsingh12** [comment]
I have not tested removeAllcounters. i will do that later. Once the freeze issue get fixed. 
Unfortuantely it is not working even after your new changes. i am still testing

**Comment by dbwiddis** [comment]
Are you running the service as a [user with permission to query WMI](https://stackoverflow.com/questions/4549445/is-it-possible-to-use-wmi-in-a-windows-service)?

**Comment by gulzarsingh12** [comment]
yeah. i am using"log on" as my user id, which can execute queries

**Comment by gulzarsingh12** [comment]
i have found 2 issues on my side:
1. I cant run oshi api immediately after process is start up.
   Workaround : I have put schedular thread to use oshi api after 1 min of process is started.
2. I cant re-use some of the objects. Given below are the objects i have get always from sysInfo.
   I can resuse  - SysInfo, HardwareAbstractionLayer objects
   static {
        systemInfo = new SystemInfo();
        hardwareAbstractionLayer = systemInfo.getHardware();
    }
   i create the above on initialization
   but i have to always get the below  

   public static OperatingSystem getOperatingSystem() {
        return systemInfo.getOperatingSystem();
    }
    public static GlobalMemory getGlobalMemory() {
        return hardwareAbstractionLayer.getMemory();
    }
    public static CentralProcessor getProcessor() {
        return hardwareAbstractionLayer.getProcessor();
    }

But after the above my code is working now and i am not getting any exception now.

These below changes didn't work:
   WmiUtil.setWmiTimeout();
   WmiUtil.setConnectionCacheTimeout()

I have tested removeAllcounters and unInitCOM and they are working and not throwing any exception.(i did fetch latest code as you said.)

Now i am waiting the 3.8.0-SNAPSHOT to be release soon so that i can integrate release version instead of snapshot with my code. Thanks a lot for your help.

**Comment by dbwiddis** [comment]
Thanks for the update. I'll look into the OS, Memory, and Processor classes to see if I can figure out why you have to create them new.

I'll release the next version as soon as I get more WMI backups to PDH code written.  That'll happen sometime this week.

**Comment by dbwiddis** [comment]
For the timeouts "changes didn't work" I assume means in fixing the hang... vs. the changes actually doing what they were intended to do, change the cacheing and query timeouts...
