### ISSUE TITLE
CPU Usage on Solaris

### ISSUE THREAD

**Issue by Kald0** [oshi/oshi#590]
Hi,

_oshi_ currently retrieves information on OS processes in Solaris by parsing the result of the **ps** command. The colums used to calculate the CPU usage are _etime_ and _time_ (elapsed time and user time respectively). Dividing those two values gives us the CPU usage of this process over its lifespan.

The issue here is that those two values are in seconds and not milliseconds: this makes the retrieval of the "instant" CPU usage almost impossible due to the lack of precision: a 1 second loop will either return 0 or 100%, a 5 second loop will return values in increment of 20%, ....

The solution here is to parse the result of the **prstat** command and its CPU column. The command

> prstat -p <pid> 1 2

will give us a single line of metrics which can then be parsed like the other command. The CPU value here is the "instant" CPU usage of the process and matches the value you can find in the System Monitor for example.

This works for us because we only need a few values from each process (PID, RSS, CPU) but I doubt that this will be easily implementable in _oshi_ since you'd have to run/parse two commands for each process. Feel free to close this if you don't think it's relevant, I wanted to document this in case someone has similar requirements. I can post the complete lists of modifications if you're interested.

**Comment by dbwiddis** [comment]
I like this idea.  I'm wondering if we don't have a better source of info than the `prstat` command, though.  The `proc` filesystem would allow reading `/proc/pid/status` or `/proc/pid/psinfo` which might have the same info available with a more direct "native" call (I consider reads of `/proc` nearly-native, in contrast to parsing command lines).   In either case, I'd welcome a PR if you want to include it.

**Comment by Kald0** [comment]
Thanks for your feedback ! I'll check that and update the issue accordingly.

**Comment by dbwiddis** [comment]
I poked around on my Solaris VM.  Good news: the data is there.  Bad news:  It requires sudo permissions, and it's in binary format so you'd have to read in the data and then figure out which bytes to parse, or build the structure and try to populate it directly with data.  

Or you can parse `prstat`. :)

**Comment by Kald0** [comment]
I came to the same conclusion. I'll work on that in the near future and see if I have enough to submit a PR.

**Comment by dbwiddis** [comment]
After further evaluation, I don't think the `prstat` output is something we should pursue.  The `ps` output does include a `pcpu` field that I think probably provides the same fractional percentage and we could add this to our existing output, but... the definition of "recent" is unspecified.  Based on research it appears to possibly be a 1-minute average.  While your initial issue cites 1-second and 5-second polling, you'd need to maintain a rolling history of the previous minute to "accurately" use that calculation (e.g., ticks 1 minute ago + CPU% * 60seconds.)  Only if OSHI were tracking the ticks from a minute ago could we use this, and I think this is a function better left to clients.  At this polling time frame, OSHI already would report at 1/60th (1.6%) resolution which is probably good enough to detect CPU spikes as quickly as the `%CPU` version of the calculation would be.
