### ISSUE TITLE
OSHI-Metrics

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#598]
This may be a horrible idea and implementation, but I took a crack at building a generic Metrics front-end to OSHI.   [It's on my branch here](https://github.com/dbwiddis/oshi/tree/metrics/oshi-metrics), but since that branch may not persist I'll reproduce some of the key bits here.

I have a properties file `oshi.metrics.properties` containing properties to refresh. So far just playing with a few.  The numbers you see are # of seconds to wait before refresh, or 0 if it's static information (probably will make that -1).
```
#hardware
#  hardware.CentralProcessor
    hardware.CentralProcessor.name                             = 0
    hardware.CentralProcessor.physicalPackageCount             = 0
    hardware.CentralProcessor.physicalProcessorCount           = 0
    hardware.CentralProcessor.logicalProcessorCount            = 0
#  hardware.GlobalMemory
    hardware.GlobalMemory.available                           = 1
    hardware.GlobalMemory.total                               = 0
    hardware.GlobalMemory.swapTotal                           = 20
    hardware.GlobalMemory.swapUsed                            = 5
    hardware.GlobalMemory.swapPagesIn                         = 1
    hardware.GlobalMemory.swapPagesOut                        = 1
    hardware.GlobalMemory.pageSize                            = 0
```
The main method loads these properties into a map along with their desired timeout.  Then I register them in a [Metrics](https://metrics.dropwizard.io/4.0.0/) registry using reflection to execute the getter from the class:
```
    private static void registerMetrics() {
        for (String className : CLASS_MAP.keySet()) {
            try {
                Class<?> clazz = Class.forName(PACKAGE_PREFIX + className);
                final Object o = clazz.newInstance();
                for (Field f : clazz.getFields()) {
                    final String fieldName = f.getName();
                    int timeout = PROPS_MAP.get(className + "." + fieldName);
                    if (timeout < 0) {
                        timeout = Integer.MAX_VALUE;
                    }
                    METRICS.register(MetricRegistry.name(clazz.getClass(), className, fieldName),
                            new CachedGauge<Object>(timeout, TimeUnit.SECONDS) {
                                @Override
                                protected Object loadValue() {
                                    try {
                                        Method m = o.getClass().getMethod(getterName(fieldName), NO_PARAMS);
                                        return (Object) m.invoke(o);
                                    } catch (IllegalAccessException | IllegalArgumentException
                                            | InvocationTargetException | NoSuchMethodException | SecurityException e) {
                                        e.printStackTrace();
                                    }
                                    return null;
                                }
                            });
                }

            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException e) {
                LOG.error("Couldn't find a class at {}{}", PACKAGE_PREFIX, className);
            }
        }
    }
```
The class is essentially a POJO:
```
public class CentralProcessor {
    public int physicalPackageCount;
    public int physicalProcessorCount;
    public int logicalProcessorCount;
    public String name;

    private static final oshi.hardware.CentralProcessor CPU = HardwareAbstractionLayer.HAL.getProcessor();

    /**
     * @return Returns the physicalPackageCount.
     */
    public int getPhysicalPackageCount() {
        physicalPackageCount = CPU.getPhysicalPackageCount();
        return physicalPackageCount;
    }

// <snipped for this issue>
}
```
I can then report using Metrics with a variety of reporters.  The `ConsoleReporter` spits out this every second (updating fields only when their timeout passes):

> 8/28/18 11:04:57 PM ============================================================
> 
> -- Gauges ----------------------------------------------------------------------
> java.lang.Class.hardware.CentralProcessor.logicalProcessorCount
>              value = 8
> java.lang.Class.hardware.CentralProcessor.name
>              value = Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
> java.lang.Class.hardware.CentralProcessor.physicalPackageCount
>              value = 1
> java.lang.Class.hardware.CentralProcessor.physicalProcessorCount
>              value = 4
> java.lang.Class.hardware.GlobalMemory.available
>              value = 5140525056
> java.lang.Class.hardware.GlobalMemory.pageSize
>              value = 4096
> java.lang.Class.hardware.GlobalMemory.swapPagesIn
>              value = 361089858
> java.lang.Class.hardware.GlobalMemory.swapPagesOut
>              value = 3927114
> java.lang.Class.hardware.GlobalMemory.swapTotal
>              value = 2147483648
> java.lang.Class.hardware.GlobalMemory.swapUsed
>              value = 1420034048
> java.lang.Class.hardware.GlobalMemory.total
>              value = 17179869184

Request feedback from @YoshiEnVerde and @cilki ... do you think this type of top level interface could work well with what you envision for OSHI 4?   
* The `CachedGauge` class I'm using automatically handles the "only update it when it's asked for and has timed out" bit, and we can fine tune the getter methods to do the minimal required upating.
* Otherwise the interfaces look similar to what we already have
* The current getters could feed into the "driver-based" values we'd discussed.

Some other notes:
* Using the older 3.x version of Metrics compatible with Java7 but am okay with requiring Java 8 for the next version, and using the latest version of Metrics.
* I don't think I actually need the class instance variables.  I'm iterating over the fields in my code but I could just as easily iterate over the properties and only call the getter methods, much more like the existing OSHI interfaces.   However, I thought including them might allow easier serialization for those who want to do so directly.
* Having the single metrics registry method at the highest level forces some abstractions, "Object" instead of better values (Number or String).  I can probably use some inheritance (and get outputs that don't all start `java.lang.Class`).  I'd like to get more toward generic numeric (integer, real) or String output (like one would see in JSON) rather than worrying overmuch about int vs. long, etc., and allow plenty of NULL that the user has to handle.

* I'll probably play tomorrow trying to get the memory data into a Graphite graph, just for fun.
![image](https://user-images.githubusercontent.com/9291703/44769346-3108ea00-ab19-11e8-8ae4-e34b115ffb90.png)

**Comment by dbwiddis** [comment]
Got rid of the second class map (individual mapping of fields) and instance variables, and did better naming.... just need to figure out the casting for string vs. numeric... and will have to figure out how to handle arrays!

> -- Gauges ----------------------------------------------------------------------
> hardware.CentralProcessor.logicalProcessorCount
>              value = 8
> hardware.CentralProcessor.name
>              value = Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
> hardware.CentralProcessor.physicalPackageCount
>              value = 1
> hardware.CentralProcessor.physicalProcessorCount
>              value = 4
> hardware.GlobalMemory.available
>              value = 4601356288
> hardware.GlobalMemory.pageSize
>              value = 4096
> hardware.GlobalMemory.swapPagesIn
>              value = 363235207
> hardware.GlobalMemory.swapPagesOut
>              value = 4040235
> hardware.GlobalMemory.swapTotal
>              value = 2147483648
> hardware.GlobalMemory.swapUsed
>              value = 988282880
> hardware.GlobalMemory.total
>              value = 17179869184

**Comment by dbwiddis** [comment]
Metrics in JMX for (remote access if desired) is trivial now:
![image](https://user-images.githubusercontent.com/9291703/44773777-41739180-ab26-11e8-88f6-9e3634e39372.png)

**Comment by dbwiddis** [comment]
Latest iteration:  Class variables are back:
* Makes all the lower classes simple POJO which eases serialization
* I can use reflection to determine the class type to pass to the Metrics registry

It's pretty clean and simple and I think it could easily replace oshi-json.  Next challenge is to deal with arrays, both fixed (processor ticks) and variable (process list)...

**Comment by cilki** [comment]
Hey @dbwiddis,
I haven't looked at Metrics or Jackson yet, but I did come up with a radical new design.
Here's a document that I have been updating which will eventually detail everything: [https://github.com/cilki/oshi/blob/4.0.0/oshi-core/DESIGN.md](https://github.com/cilki/oshi/blob/4.0.0/oshi-core/DESIGN.md).

 I've done a small amount of implementation for it on my fork, but ran into some problems with caching so I took a break.

My thoughts on the `CentralProcessor` POJO you posted:
- The container class (`CentralProcessor`) should have no dependency on the driver (the class that retrieves the data, in this case: `CPU.getPhysicalPackageCount()`).
- Multiple physical CPUs are not handled. Since multiplicities are common (maybe not with physical CPUs, but with network interfaces, displays, etc...), I'm trying to deal with this in my design with "Group" objects. So the user would obtain a `CentralProcessorGroup` which yields access to the CPU(s). This idea hasn't fully matured, but I think I can make it work.

**Comment by dbwiddis** [comment]
Thanks for the feedback!  Not sure what you mean by "no dependency".  The CPU just stores an appropriate class-specific class that implements the interface.

Multiple physical packages are counted... I only showed a few of the existing fields.  The problem comes in when I want to get attributes for each CPU.  Currently I have a 5x8 array with the tick values.  It appears I would have no choice but to make a single metrics element for every one of those, e.g., `hardware.CentralProcessor.cpu0.userTime` and so on.  Metrics has a `Meter` class that would be nice for those values to get cpu% for the "last 1min, last 5min, last 15min" and other stats.  But it's not really scalable to do for every single running process (that changes between updates).  

Also the JSON looks like it tracks each element individually, without the nice nested format I've currently got.

Oh, well. I'll keep playing with it for a bit but I'm less excited about using it than I was before.  I do think the POJO format (POJO serialized class implementing interface and calling the core classes) may still be useful for some other application (Jackson?) though.

**Comment by cilki** [comment]
> Not sure what you mean by "no dependency"

I didn't look closely enough to realize that `CPU` was a singleton. Regardless, I think the container class (`CentralProcessor`) should have nothing to do with the logic that actually gets the data.

Did you get a chance to browse my proposal?

**Comment by dbwiddis** [comment]
Closing this issue as I won't be pursuing a Metrics implementation, primarily due to lack of array handling.   I'll focus integration on easy serialization into Jackson.
