### ISSUE TITLE
Javadoc of CentralProcessor.TickType#SYSTEM is confusing

### ISSUE THREAD

**Issue by retomerz** [oshi/oshi#599]
Hello,

First, Thanks for all your work and this good library!

We have found a confusing Javadoc comment [1] in CentralProcessor.TickType#SYSTEM which is as follow:

```
/**
 * CPU utilization that occurred while executing at the system level
 * (kernel). Also includes CPU time which the hypervisor dedicated for
 * other guests in the system (steal).
 */
SYSTEM(2),
```

And the Javadoc of STEAL is:

```
/**
 * Time which the hypervisor dedicated for other guests in the system.
 * Only supported on Linux.
 */
STEAL(7);
```

According to our Linux team the "system" value (readed in /proc/stat) does *not* include "steal".

Can someone please explain the comment in SYSTEM a bit more?
Is this comment related to Linux? Or for another OS (eg Windows)?

Thanks
Reto

[1] https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/hardware/CentralProcessor.java#L49

**Comment by dbwiddis** [comment]
You're asking me what I meant in a comment 2 years ago? LOL....

I think I probably need to add "except for Linux" to the first comment.  I'll look into it.

**Comment by dbwiddis** [comment]
Looks like the original (System) javadoc was written before we had steal put in in #364.  I had originally omitted steal since only one OS had the data.  When steal was added, we neglected to update the javadoc.  It is no longer accurate for Linux, so an "except for Linux" addition would be appropriate.
