### ISSUE TITLE
Process uptime on multicore system

### ISSUE THREAD

**Issue by anitakosman** [oshi/oshi#601]
When trying to calculate cpu usage per process, I want to use OSProcess.upTime as a timestamp for when userTime and kernelTime were measured. What is the reason the sum of userTime and kernelTime is returned when they exceed the actual upTime?

Because on a multicore processor it is valid for the sum of userTime and kernelTime to be bigger than upTime, although total will be returned by getUpTime(). Defeating the purpose of upTime as a Timestamp. 

This approach was suggested by @dbwiddis, see https://github.com/oshi/oshi/issues/372#issuecomment-307573178

**Comment by dbwiddis** [comment]
I just glanced at the code and don't see where this is calculated as you describe.  Which operating system are you using?

**Comment by anitakosman** [comment]
I'm using windows, but that shouldn't matter. Next code is from OSProcess.java:
`/**
     * @return Returns the number of milliseconds since the process started.
     */
    public long getUpTime() {
        if (this.upTime < this.kernelTime + this.userTime) {
            return this.kernelTime + this.userTime;
        }
        return this.upTime;
    }`

**Comment by dbwiddis** [comment]
Ah, I was looking in the OS-specific ones.

Yeah, when I put that in it was intended to be a sanity check and I wasn't thinking about multi-processor systems.  It should probably return the value directly.  Can you submit a PR?

**Comment by dbwiddis** [comment]
Merged.  I'll update snapshot shortly.
