### ISSUE TITLE
Time to take advantage of Jigsaw modules?

### ISSUE THREAD

**Issue by cilki** [oshi/oshi#619]
I imagine that most OSHI users either:
- Use all or most features (CPU, disks, etc) in a monitoring scenario (like my application: [Sandpolis](https://github.com/Subterranean-Security/Sandpolis))
- Use only one or two features and have absolutely no need for anything else

We want to encourage usage in the second category especially, but the size of the artifact may be a non-starter for some people who only need a tiny subset of functionality. Designing the next version of OSHI with Jigsaw modules may be a step in the right direction.

JNA is the heaviest dependency that users need to accept when considering OSHI, and there is nothing we can do about that unless JNA modularizes too. In the very, very distant future, [Project Panama](http://openjdk.java.net/projects/panama/) may be a lighter alternative to JNA and modules would be beneficial in that case too.

To me, the only downside of modularizing is that Java 8 users will be excluded (however, 4.0.0 may be far enough away that this won't be a problem).

Thoughts and suggestions?

**Comment by dbwiddis** [comment]
I'm not comfortable excluding Java 8 users just yet, in particular large organizations who use LTS versions.  I'd want to stick on 8 until the majority of people have switched to Java 11.

Java 11 isn't quite out yet so 8 is the de facto standard for anyone who doesn't update every 6 months.  I do hope we'll get 4.0 out before 2022 or so.  Heck, even I have an idea for what I want to do simply, and leave all you engineers with your grand plans for 5.0 (in which case if you're targeting 2021-2122, Jigsaw away!)

**Comment by dbwiddis** [comment]
Alternately, if you think it's possible to build a parallel artifact using modules, and share bits of code as needed, this could be a good hybrid/bridge.

**Comment by cilki** [comment]
I can setup the packages to look like modules (just minus the `module-info.java`) so that it's compatible with Java 8. Then when it's time to actually modularize, the module descriptors can just be auto-generated.

**Comment by dbwiddis** [comment]
That sounds like a great compromise, and an ideal high-level split between static information that you pull once (like serial#s) and the dynamic info that you update periodically.  I know a common use case is generating a hardware signature for licensing, and that should be made as low-impact as possible.

**Comment by dbwiddis** [comment]
I’m thinking we target a 4.x release with Java8 for early 2019 that moves in the right direction without major refactoring.   And a Java11 5.x release in 2020 while maintaining 4.x patches for a short while.

**Comment by dbwiddis** [comment]
Closing this one as a standalone, but feel free to discuss on #658 which matches my previous comment.
