### ISSUE TITLE
Sound card(s) information

### ISSUE THREAD

**Issue by BilalAM** [oshi/oshi#625]
Information regarding audio card would be a useful addition.
`/proc/asound/cardX` gives information about the sound cards , X is the card number , it depends how many cards do you have . 
`cat /proc/asound/cards` gives me this 
`0 [HDMI           ]: HDA-Intel - HDA Intel HDMI
                      HDA Intel HDMI at 0xd1510000 irq 53`
` 1 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xd1514000 irq 52`

Further information about these can be found in the `codec#0` file.
Interestingly `alsamixer` utility is also using `/proc/asound` to list audio cards and information.

Can this be a useful addition ?

**Comment by cilki** [comment]
Yes, but it will have to wait until we decide on the new design of the next version. There's no sense in adding something new to an old architecture.

**Comment by BilalAM** [comment]
We can still add it though , the new design will take some time .

**Comment by dbwiddis** [comment]
There's no sense waiting until we decide if the decision is going to stretch years. ;)   

This seems a relatively simple implementation (Linux listed above, Windows has Win32_SoundDevice, mac has `system_profiler SPAudioDataType` or possibly registry, and I'm sure we could parse dmidecode for other OS's) and I'd welcome a PR if someone else wants to do it. 

If they want me to do it, then it will probably wait until the new version, and then some. :)

The bigger question is: what (cross-platform) information do we want to expose?  Do we want a specific SoundCard class or perhaps we should roll up miscellaneous hardware like Sound cards, GPUs (another old request hanging out there), etc. in a "Peripherals" or "IO" or similar.  

Again... I'd welcome a PR on this if you'd really like this capability in the current version.

**Comment by BilalAM** [comment]
I can try to make this , the information I managed to discover related to the sound cards were not much in detail, only the number of cards , name , vendor and the type (Like the output shown above) .
GPUs are a bit difficult as it is vendor dependent and non standard , the closest I can get is by running this command I found posted at stackoverflow
`lspci  -v -s  $(lspci | grep ' VGA ' | cut -d" " -f 1)` 
BUT it is also written that it doesn't really show the actual memory of the GPU , for that we need to have vendor dependent libraries installed ...

**Comment by dbwiddis** [comment]
For Mac OS x, parse this output (you can probably load a test file to implement, then replace with command line for final commit):

Command: `system_profiler SPAudioDataType`

Output:
```
Audio:

    Devices:

        Built-in Microphone:

          Default Input Device: Yes
          Input Channels: 2
          Manufacturer: Apple Inc.
          Current SampleRate: 44100
          Transport: Built-in
          Input Source: Internal Microphone

        Built-in Output:

          Default Output Device: Yes
          Default System Output Device: Yes
          Manufacturer: Apple Inc.
          Output Channels: 2
          Current SampleRate: 44100
          Transport: Built-in
          Output Source: Internal Speakers
```

I expect you can use `dmidecode` on Linux to get the format you'll need to parse the same output on Unix.

**Comment by BilalAM** [comment]
It will be a bit tricky for me to implement the mac version (simple because I dont have a macbook :) ) , but i'll try to parse the output you mentioned and maybe see some online articles on how to get the driver version. Also it will take a bit of time for freebsd and solaris as I have never used them before but i will try of course via virtual machines.

**Comment by dbwiddis** [comment]
If you get everything else I can get Mac.

**Comment by dbwiddis** [comment]
While you're reworking this a few issues with `LinuxSoundCard.java` I didn't catch in PR review:
- Null dereference in `getCardCodec()` on the `listFiles()` call.  Needs null check similar to the `getCardFolders()` method.
- The `getStringFromFile()` method in `getSoundCardVersion()` already catches the potential `IOException`.  I assume this catch block is left over from debugging?  It should be removed.

**Comment by dbwiddis** [comment]
Yes, but you can submit those changes with other OS implementation if you're already working on it.

**Comment by BilalAM** [comment]
I have a few questions regarding how to run wmi queries by using the `WmiUtil` and `Wbemcliutil` classes , i read the already implemented code using the methods but one thing I dont understand is that is there a method that returns a key value map from the output of a particular query like the method inside `FileUtil `class (the `getKeyValueFromFile` ) method instead of creating enums for a particular type and calling different methods ?

**Comment by dbwiddis** [comment]
The map is encoded within a `WmiResult` object. It's an `EnumMap` with the property as the key, and a list of results as the value.   using it is straightforward:
1. Determine the WMI class to fetch from.  Let's use [Win32_SoundDevice](https://docs.microsoft.com/en-us/windows/desktop/cimwin32prov/win32-sounddevice).
2. Define an Enum with the properties to fetch, e.g.,
```
    enum SoundDeviceProperty {
        NAME, MANUFACTURER;
    }
```
3. Define a query using the property enum:
```
    WmiQuery<SoundDeviceProperty> soundDeviceQuery = 
        new WmiQuery<>("Win32_SoundDevice", SoundDeviceProperty.class);
```
4. Query the enum and store the results:
```
    WmiResult<SoundDeviceProperty> soundDeviceResult = 
        WmiUtil.queryWMI(soundDeviceQuery);
```
5. Fetch the results by column (Property) and row(index):
```
            for (int sd = 0; sd < soundDeviceResult.getResultCount(); sd++) {
                // use the appropriate type get*() for the WMI type
                String name = WmiUtil.getString(soundDeviceResult, SoundDeviceProperty.NAME, sd);
                // do stuff with name
                }
            }
```

**Comment by BilalAM** [comment]
Ah yes I was actually coding this just now after reading and looking at the classes and understood the overall design , was quite amazed at how simple and straightforward you guys have designed it.

**Comment by dbwiddis** [comment]
"Designed" is a misnomer.  :D   "Weeks of coding can save you hours of planning."   What you see is the result of doing it the hard way and iteratively simplifying over time.

**Comment by BilalAM** [comment]
And the result is a very straightforward and easy to use library ;)

**Comment by BilalAM** [comment]
@dbwiddis for freeBsd I am using GhostBSD (its a version of freeBsd with pre installed gui and other goodies wrapped together) . Now after searching around a bit I found this command `pciconf -v`  that is listing the required information in this way : 

**pcm0@pci0:0:5:0:    class=0x040100 card=0x00008086 chip=0x24158086 rev=0x01 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82801AA AC'97 Audio Controller'
    class      = multimedia
    subclass**

But at the same time the other command that I found was `lshal` that is displaying it in this way : 

**udi = '/org/freedesktop/Hal/devices/pci_8086_2415_oss_pcm_0'
  info.capabilities = {'oss'} (string list)
  info.category = 'oss'  (string)
  info.parent = '/org/freedesktop/Hal/devices/pci_8086_2415'  (string)
  info.product = '82801AA AC'97 Audio Controller (pcm)'  (string)
  info.udi = '/org/freedesktop/Hal/devices/pci_8086_2415_oss_pcm_0'  (string)
  oss.card = 0  (0x0)  (int)
  oss.device = 0  (0x0)  (int)
  oss.device_file = '/dev/dsp0'  (string)
  oss.device_id = '82801AA AC'97 Audio Controller (pcm)'  (string)
  oss.originating_device = '/org/freedesktop/Hal/devices/pci_8086_2415'  (string)
  oss.type = 'pcm'  (stri**

I cannot find this information in the filesystem (i maybe missing something since i am completely new to these operating systems) and the only way I see is to parse these commands . 
Will this be okay i.e parsing commands ?

**Comment by dbwiddis** [comment]
Yes... I was going to suggest `pciconf` was the better parsing for BSD (and possibly Solaris too).  I think you can try `lshal` first (if it's installed, as it's non-sudo) and fall back to `pciconf` otherwise.   (Or do it the other way around.)

**Comment by dbwiddis** [comment]
man pages say yes. I'll test tomorrow. bed now.

**Comment by BilalAM** [comment]
Okay sure , it must be night time at your side since its 12:30 pm at my side !

**Comment by dbwiddis** [comment]
Looks like it works!

**Comment by BilalAM** [comment]
Yes it is working , in fact it is showing more information than it was on FreeBSD (most particularly the `info.solaris.driver` field is showing the driver itself)

**Comment by dbwiddis** [comment]
Looks like we're just waiting on FreeBSD now?

**Comment by dbwiddis** [comment]
Er, nope. #652 was FreeBSD and #655 is Solaris. So this is all done!
