### ISSUE TITLE
Per process CPU usage

### ISSUE THREAD

**Issue by sohailravian** [oshi/oshi#627]
Dear @dbwiddis  I am getting process.getKernelTime() + process.getUserTime() same time no matter how many times i run this code. I am using windows 10 64 bits. Please see below code. Previous time is my static variable.
```
public void cpuUtililizationPerProcess()
{
	int processId = 45884;
	SystemInfo systemInfo = new SystemInfo();
	OSProcess process = systemInfo.getOperatingSystem().getProcess(processId);
	
	CentralProcessor processor = systemInfo.getHardware().getProcessor();
	int cpuNumber = processor.getLogicalProcessorCount();
	
	long currentTime = process.getKernelTime() + process.getUserTime();
	long timeDifference = currentTime - previousTime;
	
	double processCpu =  (100 * ( timeDifference / 5000 ) ) / cpuNumber;
	previousTime = currentTime;
}
```

**Comment by dbwiddis** [comment]
Thanks for the report I just copied your code into a new program, wrapped it in a loop, and put in a 1 second (1000 millisecond) delay using `Util.sleep(1000);`.  I got updated values for my existing process each iteration.  For other processes, some advance and some were "stuck" on the values, but it appeared to be for sleeping/idle processes.
 - Is the process you're measuring actually running?
 - Do you have other process monitoring software that shows this process increasing in kernel/user time (task manager, etc.)
 - can you try it on your existing process (`int processId = systemInfo.getOperatingSystem().getProcessId();`) which we're sure is generating CPU cycles

**Comment by sohailravian** [comment]
@dbwiddis Yes it is running. This is the code which shows process found
System.out.println(systemInfo.getOperatingSystem().getProcess(45884));
-------- Output --------------
OSProcess@7ff88626[processID=45884, name=nginx] 

![image](https://user-images.githubusercontent.com/6654004/45942433-678c3480-bff3-11e8-9ba9-adde24652ea4.png)
![cpu](https://user-images.githubusercontent.com/6654004/45942561-057fff00-bff4-11e8-9576-c6a93fdbee5b.png)

**Comment by sohailravian** [comment]
@dbwiddis I can see in your code these lines as it is always picking from cache.

 // If process exists fetch from cache
                        OSProcess proc = null;
                        if (this.processMap.containsKey(pid)) {
                            proc = this.processMap.get(pid);
                        }
                        // If not in cache or if start time differs too much,
                        // create new process to add/replace cache value

**Comment by dbwiddis** [comment]
The code you posted ([WindowsOperatingSystem.java:504](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java#L504)) only fetches the Process Object itself from the cache, but all attributes (except pid, name, and Start time) should be overwritten by later code.  In particular, the user/kernel time are updated at [line 350](https://github.com/oshi/oshi/blob/482d3061ef54e20b0b84fd492c22e500733ecc96/oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java#L350).

I wrote the following class:
```
package oshi;

import oshi.hardware.CentralProcessor;
import oshi.software.os.OSProcess;
import oshi.util.Util;

public class Test {

    public static long previousTime;

    public static void main(String[] args) {
        for (int i = 0; i < 10; i++) {
            cpuUtilizationPerProcess();
            Util.sleep(5000);
        }
    }

    public static void cpuUtilizationPerProcess() {
        SystemInfo systemInfo = new SystemInfo();
        CentralProcessor processor = systemInfo.getHardware().getProcessor();
        int cpuNumber = processor.getLogicalProcessorCount();

        int processId = systemInfo.getOperatingSystem().getProcessId();
        OSProcess process = systemInfo.getOperatingSystem().getProcess(processId);
        long currentTime = process.getKernelTime() + process.getUserTime();
        long timeDifference = currentTime - previousTime;

        double processCpu = (100 * (timeDifference / 5000d)) / cpuNumber;
        previousTime = currentTime;

        System.out.format("K: %d, U: %d, diff: %d, CPU: %.1f%n", process.getKernelTime(), process.getUserTime(),
                timeDifference, processCpu);
    }
}
```
Output:

> 
> K: 562, U: 1828, diff: 2390, CPU: 12.0
> K: 703, U: 2828, diff: 1141, CPU: 5.7
> K: 828, U: 3656, diff: 953, CPU: 4.8
> K: 984, U: 4609, diff: 1109, CPU: 5.5
> K: 1156, U: 6296, diff: 1859, CPU: 9.3
> K: 1265, U: 6484, diff: 297, CPU: 1.5
> K: 1375, U: 6609, diff: 235, CPU: 1.2
> K: 1515, U: 6656, diff: 187, CPU: 0.9
> K: 1625, U: 6750, diff: 204, CPU: 1.0
> K: 1703, U: 7046, diff: 374, CPU: 1.9

One note, copying from your code, you're doing integer division in the cpu calculation so you truncate decimals. This may result in 0 CPU at that step.

**Comment by sohailravian** [comment]
@dbwiddis You are right if you run this code for operating system process id it gives the required information but when you run this code for any sub process like i want to calculate for Nginx it always returns 0  :(. Process Id is 94880. You can test it for Nginx. Just run Reverse proxy server and hit it with some load and compare it CPU utilization. 

Code Snippet
 public static void cpuUtilizationPerProcess() {
while(true) {
 		SystemInfo systemInfo = new SystemInfo();
		OSProcess process = systemInfo.getOperatingSystem().getProcess(94880);
	        long currentTime = process.getKernelTime() + process.getUserTime();
		long timeDifference = currentTime - previousTime;
		
		double processCpu =  (100 * ( timeDifference / 5000d ) ) ;
		previousTime = currentTime;
		 System.out.format("K: %d, U: %d, diff: %d, CPU: %.1f%n", process.getKernelTime(), process.getUserTime(), timeDifference, processCpu);
		Util.sleep(5000);
	}
}

**Comment by dbwiddis** [comment]
Is it just Nginx that gives 0 results? Is it zero ticks or just non-increasing ticks?   [Reading the Nginx website](http://nginx.org/en/docs/windows.html), it says:

> Known issues
> Although several workers can be started, only one of them actually does any work.

Is this the only program that's giving you the issue, and is it only the multiple workers?   Is there any other process causing this problem?

**Comment by sohailravian** [comment]
i just tried with Nginx so far. In task list it shows correct. About tick i have no idea. I will try with other process as well. Can you give it a try by yourself as well. On more thing if your run the above code with below code it does not output proper data even with windows process as well.
double processCpu =  (100 * ( timeDifference / process.getUpTime()) ) ;
   [
![cpu](https://user-images.githubusercontent.com/6654004/45993902-21da7500-c0a2-11e8-87c2-1203d18d78ac.png)
](url)

**Comment by dbwiddis** [comment]
Please see if you can replicate this error with anything other than Nginx.  Also confirm you only have one Nginx process running.  From the link I quoted above it seems only one of several processes may have usage.   Also can you correlate against the process in the Perfmon.exe Performance monitor (Look under process for the nginx instance, then look at the usage #s) and WMI (`wmic path Win32_Process get ProcessID,KernelModeTime,UserModeTime WHERE ProcessId=12345`)

If OSHI is mismatching these other reporters I will continue to investigate but I still don't think I have enough information to replicate this.  If OSHI is working fine for all the other processes, there's something unusual about this one and I'm not yet sure you've only got a single ProcessID matching that.

In your calculation, `timeDifference / process.getUpTime()` still results in an integer division that will be zero if the left hand side is smaller than the right.  Also you need to get both the time difference (cpu usage) and the up time difference, as the total up time constantly increases but you just want to measure the time between the timestamps that you gathered the data.

**Comment by sohailravian** [comment]
@dbwiddis Yes you are right. I tried with STS.exe process id and it is giving expected result. Nginx has two process running. Parent and worker process. So such processes which uses sub-process by giving parent process id SOCHI can not calculate cpu usage. I really appreciate your help (y) .

**Comment by sohailravian** [comment]
@dbwiddis dear i have a question how to find cores in processors. For example i can see in linux there are 4 processors and each have 2 cores with it. So we have to divide by  processor * core {4*2}.

CentralProcessor processor = systemInfo.getHardware().getProcessor();
int cpuNumber = processor.getLogicalProcessorCount();

This line only provides processor count. how to count core out of it? Below is just one processor

processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 62
model name      : Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz
stepping        : 4
microcode       : 1064
cpu MHz         : 2992.788
cache size      : 25600 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts xtopology tsc_reliable nonstop_tsc aperfmperf unfair_spinlock pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 popcnt aes xsave avx hypervisor lahf_lm ida arat epb xsaveopt pln pts dtherm
bogomips        : 5985.57
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

**Comment by dbwiddis** [comment]
The `CentralProcessor` interface also has `getPhysicalProcessorCount()` and `getPhysicalPackageCount()` methods.  The Physical Processor count is the number of actual CPUs (no hyperthreading) and the Physical Package count is the number of chips/sockets.

When parsing `/proc/cpuinfo` as you've shown, the logical processor count is the number of unique `processor: *` fields, the physical processor count is the number of unique `core id: *` fields (on some systems, `cpu number: *`, and the physical package count is the number of unique `physical id: *` fields.   You could also use the `siblings` and `cpu cores` fields yourself if you chose, (2 physical cores with 2 logical processors each).

**Comment by sohailravian** [comment]
@dbwiddis thankue for your rply. So how should i move on. Should i do getPhysicalProcessorCount() + getPhysicalPackageCount() to get CPU number for calculating average of process or should i do  getPhysicalProcessorCount() * getPhysicalPackageCount??

**Comment by dbwiddis** [comment]
Just the Physical Processor count should represent the total possible usage.  So if you really want to calculate total system utilization you would add up all the ticks from the individual processes and divide by the elapsed milliseconds * # of physical processors.
