### ISSUE TITLE
WindowsOperatingSystem.getProcesses can crash with Win32Exception

### ISSUE THREAD

**Issue by retomerz** [oshi/oshi#637]
Following call
```
os.getProcesses(0, OperatingSystem.ProcessSort.NAME);
```
can crash with
```
com.sun.jna.platform.win32.Win32Exception: The parameter is incorrect.
	at com.sun.jna.platform.win32.Advapi32Util.getAccountBySid(Advapi32Util.java:282)
	at com.sun.jna.platform.win32.Advapi32Util.getAccountBySid(Advapi32Util.java:248)
	at com.sun.jna.platform.win32.Advapi32Util.getTokenAccount(Advapi32Util.java:506)
	at oshi.software.os.windows.WindowsOperatingSystem.processMapToList(WindowsOperatingSystem.java:367)
	at oshi.software.os.windows.WindowsOperatingSystem.getProcesses(WindowsOperatingSystem.java:237)
```
Seen with OSHI 3.8.2 and Microsoft Windows Server 2012 R2 build 9600

**Comment by dbwiddis** [comment]
Is this repeatable (and can you get information about the process causing it) or was this a one-off error?  It looks like there's possibly a race condition if a process ends between opening its handle and getting its token.

**Comment by retomerz** [comment]
I have only seen this error in a log file (in a production environment) so unfortunately I have not much more information.
A race (process just terminated before getTokenAccount is invoked) was also my first idea but I was not able to reproduce it.
My second idea was that, maybe, Advapi32.dll behaves different when the other process runs with a different user (in my case I have used the SYSTEM user with psexec [1], see commented-out code in the testcode below)
but I was still not able to reproduce it.
Or another idea is that a user just started a process and a UAC elevation is in process.

The only warning I get is this:
```
Okt 01, 2018 7:13:47 PM oshi.software.os.windows.WindowsOperatingSystem processMapToList
WARNUNG: Failed to set path on PID 9344. It may have terminated.
```
I think it would make sense to surround the getTokenAccount call with a try/catch and log as much as possible as a warning,
at least the PID and process name (proc.toString). What you think?

[1] https://docs.microsoft.com/en-us/sysinternals/downloads/psexec

Here is my testcode
```
import org.junit.Test;
import oshi.SystemInfo;
import oshi.software.os.OperatingSystem;

import java.io.File;
import java.util.Arrays;

public class ProcessTest {
  @Test
  public void run() throws Exception {
    new Thread(new Runnable() {
      @Override
      public void run() {
        try {
          OperatingSystem os = new SystemInfo().getOperatingSystem();
          while (!Thread.currentThread().isInterrupted()) {
            os.getProcesses(0, OperatingSystem.ProcessSort.NAME);
          }
        } catch (Throwable e) {
          e.printStackTrace();
          System.exit(1);
        }
      }
    }).start();

    while (!Thread.currentThread().isInterrupted()) {
      File stopLatch = File.createTempFile("ProcessTest", ".temp");
      Process p = forkProcess(stopLatch);
      stopLatch.delete();
      p.waitFor();
    }
  }

  private Process forkProcess(File stopLatch) throws Exception {
    File java = new File(System.getProperty("java.home"), "bin/java");
    String cp = System.getProperty("java.class.path");
    return new ProcessBuilder(Arrays.asList(
            /*"C:/tools/sys/PsExec64.exe",
            "-s",*/
            java.getCanonicalPath(),
            "-cp",
            cp,
            ProcessTest.class.getName(),
            stopLatch.getCanonicalPath()

    )).inheritIO().start();
  }

  public static void main(String[] args) throws Exception {
    System.out.println("Begin");
    File f = new File(args[0]);
    while (f.exists()) {
      Thread.sleep(16L);
    }
    System.out.println("End");
  }
}
```

**Comment by dbwiddis** [comment]
Catching Win32Errors in the Advapi calls and sending a warning is probably the way to go.  Care to submit a PR?

**Comment by retomerz** [comment]
@dbwiddis Thank you very much for fixing this!
Do you already know when you will publish a new release?

**Comment by dbwiddis** [comment]
Currently waiting on completing the sound card implementation, so wasn't in a big hurry.  Snapshot should work for you... if you need me to cut a patch release I can do so this weekend.

**Comment by retomerz** [comment]
@dbwiddis  A fresh release would be great!
