### ISSUE TITLE
OSHI 3.x, 4.x, and 5.x Roadmap

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#658]
### OSHI 3.x
- Java 7 compatible branch resides on branch OSHI 3.13.X
- Only bugfixes will be made on this branch
- Will port over Java7 compatible fixes from 4.x

### OSHI 4.x
- Current active development
- Will be released approx. 2019-09-01
- Will be an incremental change from 3.x with the following key changes:
  - Will have minimum Java 8 compatibility
  - Will remove the [oshi-json project/artifact in favor of serializable classes](http://www.mkyong.com/java/jackson-2-convert-java-object-to-from-json/)
  - Will have an oshi-demo project/artifact for common use cases (hardware signature, test if on a VM, and a jackson-based json implementation). We'll continue to add to this collection.
  - ~~Package refactoring to replace "software.os" with just "os"~~ Leaving packages as is.
  - Class name/function refactoring to:
    - ~~Alphabetize similar classes together (e.g., WindowsOperatingSystem will be OperatingSystemWindows)~~ Leaving it as is
    - ~~Make state classes (e.g., cpu ticks on a CentralProcessorState class) serializable using Jackson as a test case~~ Not required for Jackson, just standardize getter behavior.
    - Attempt to enforce the "static data"/"update on request" paradigm simply
    - ~~Use Util classes for derivative calculations (e.g., cpu usage between ticks)~~ For simplicity, just taking arguments.
    - ~~Replace arrays with lists in API~~ Leaving as arrays for serialization
  - Some functionality changes such as ~~counters in original units (jiffies, etc.) with a conversion factor (for ms) available (and in Util class),~~ and per-processor attributes (frequency, physical package/core distinctions, etc.)

### OSHI 5.x
- Will require Java 11 compatibility
- Will be targeted for 2020 or beyond
- Will be a major redesign.  [Current design doc](https://github.com/cilki/oshi/blob/4.0.0/oshi-core/DESIGN.md)  Discussion/development [repository here](https://github.com/oshi/oshi5). 

- Development being led by @cilki

**Comment by cilki** [comment]
I think it's a good idea to do 4.X with some intermediate changes before any major restructuring. I'll have more time to work on this after December and I can help on some 4.X stuff too.

**Comment by lasselindqvist** [comment]
Java 8 as a requirement sounds reasonable as 11 is already out and 8 has been out a long time.

**Comment by stefan-reich** [comment]
Three comments.

1. I love OSHI :smiley: 

2. I have never been sure what the JSON package actually does, always seemed like bloat to me (is someone writing that code manually? :D).

3. Java 8 requirement is absolutely fine.

**Comment by dbwiddis** [comment]
The JSON package produces JSON!  Early on there was a request to output OSHI data in JSON format. After rolling my own and eventually going for the "official" version (which didn't handle nulls well) I eventually got to what we have which is, as you say, mostly bloat.  I want to provide standard POJO/Serializable classes that are easy to get into JSON but don't require OSHI to maintain that.

**Comment by dblock** [comment]
@dbwiddis This is an exciting roadmap! I encourage you to seek additional co-maintainers amongst the active contributors in 2019, too.

**Comment by cilki** [comment]
@dbwiddis Do you think it would be a good idea to make another repository for the OSHI 5 design development and discussion? It would just contain a readme with the master design document and all relevant issues. Then once the design is finalized, the implementation can be done in this repository.

My thought is that this would improve collaboration in the design phase.

**Comment by dbwiddis** [comment]
See https://github.com/oshi/oshi5 and have fun. :)

**Comment by YoshiEnVerde** [comment]
And just when I'm writing down my goals/targets/resolutions for 2019...
I'll read the design doc later today and start a thread/issue or two over OSHI5 to start things ;)

**Comment by dbwiddis** [comment]
Having made some significant improvements without altering the API yet, I think I'm going to release 3.13 before altering the API.  I think I'll still keep it at Java 8 though, rather than backing it out.

**Comment by drdwo** [comment]
Any update for the 4.0 release date? The API changes in 4.0 are necessary for our application, so 3.x is no option for us. Tried 4.0-Snapshot with open jdk 11 and it seems to work. Are there any issues to be expected with jdk 11?

**Comment by dbwiddis** [comment]
We are testing against JDK 11 (and 12 EA and will test 12 and 13 EA when the time comes) so there should be no issues there -- and we'll maintain minimum JDK 8.

As for a timeline, the answer is "when I get some free time".  If others want to help I can point out what needs to be done to accelerate it.  There's actually not much left to do and it falls in the "chore" category but takes time to do it methodically and test on all 5 supported OS's.

**Comment by cilki** [comment]
**Update on 5.X:** I managed to convince one of my professors to sponsor my work on OSHI over the summer for course credit. Effectively this means I'll be putting a lot more effort into the redesign over the next 4 months. My goal is to have a working example implementation by the end of it.

@dbwiddis, here are the specifics if you're interested: [https://github.com/cilki/CS370/blob/master/Proposal/CS370_Proposal.pdf](https://github.com/cilki/CS370/blob/master/Proposal/CS370_Proposal.pdf)

**Comment by dbwiddis** [comment]
This is awesome, @cilki!    Perhaps the motivation I need to finish OSHI 4. :)

**Comment by severn-everett** [comment]
Are we close to a publication date for 4.0? We need to update to JNA 5.4.0 due to a separate dependency.

**Comment by dbwiddis** [comment]
I hate to make promises, but I do hope to get it out this month.  Is there a reason you can't use JNA 5.4 with the earlier version, though?

**Comment by dbwiddis** [comment]
Path to 4.0 release:

1. Conform `updateAttributes()` pattern for:
- [ ] PowerSource
- [ ] HWDiskStore (rename updateDiskStats)
- [ ] OSProcess (call getProcess(pid) and copy)
- [ ] OSFileStore
- [ ] OperatingSystem
- [ ] NetworkParams
- [ ] FileSystem

2. Release 4.0.0-beta1 (Target: by 2019-08-11)

3. Final review of feature requests to consider including. Fix any reported beta bugs.

4. Release 4.0.0-rc1 (Target: by 2019-08-18)

5. Bug fixes as needed.

6. Release 4.0.0 (Target: by 2019-08-25)
