### ISSUE TITLE
Are oshi SystemInfo instances thread safe?

### ISSUE THREAD

**Issue by spyhunter99** [oshi/oshi#660]
I'm running into some strange issue and had a few quick general questions, specifically on Windows where by sometimes WMI queries never return. I see that the newer versions have timeout mechanisms baked in but i wasn't sure if concurrent access to the same objects were ok.

If i'm a user of OSHI, it is better to have a single instance of static SystemInfo that can be used used by multiple concurrent threads or is it better to have single instance per thread or caller?

**Comment by dbwiddis** [comment]
While I've made reasonable efforts to try to avoid issues with thread safety, and many classes will work without a problem, I certainly can't guarantee it.  I do believe WMI should support concurrent queries.  But this is one of those situations where you'd probably want to build a testcase and intentionally hammer the framework with multiple threads to test its robustness.

Happy to try to fix any issues you uncover this way, but searching for them myself hasn't been a priority.

**Comment by spyhunter99** [comment]
Hmm ok thanks for the input
