### ISSUE TITLE
Question: Can OSHI do the difference between genuine OS and VM?

### ISSUE THREAD

**Issue by Sami32** [oshi/oshi#668]
As the macOS VM, for example, would not have the same hardware that a true macOS computer.

Feel free to close this "issue" if that doesn't make any sens to anyone except me.

**Comment by dbwiddis** [comment]
It makes sense, and was suggested in #648. I'll close this issue but welcome you to contribute to the discussion on that other issue.

Bottom line, it's hard to say "for sure" whether you are on a VM or not, particularly if someone intentionally tries to hide the fact.  One "easy" way is by looking at the first half of network MAC cards for VMs; another is to look for the VM's string in Serial #s.   But both MACs and serial #s can be easily changed by users.

There are plenty of other applications that attempt to try to do this but none of them are foolproof.  I'd welcome a "util" class in OSHI that attempts to figure this out with the caveat that it's easily fooled.
