### ISSUE TITLE
Strange mount point for C: drive on Windows

### ISSUE THREAD

**Issue by antonio-rodriges** [oshi/oshi#671]
HWDiskStore[] diskStores = new SystemInfo().getHardware().getDiskStores();
            for (HWDiskStore diskStore : diskStores) {
                System.out.println(diskStore.getName() + " ==> ");
                HWPartition[] partitions = diskStore.getPartitions();
                for (HWPartition partition : partitions) {
                    System.out.print(String.format("%s | %s", partition.getName(), partition.getMountPoint()));
                }
                System.out.println();
            }

yields 

\\.\PHYSICALDRIVE0 ==> 
Installable File System | Installable File System | C:\Unknown | Installable File System | D:\

where `C:\Unknown` seems to be strange

        <oshi.version>3.9.1</oshi.version>

        <dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>
            <version>${oshi.version}</version>
        </dependency>

        
        <dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-json</artifactId>
            <version>${oshi.version}</version>
        </dependency>

        
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>4.5.2</version>
        </dependency>

**Comment by dbwiddis** [comment]
Can you query WMI and post the results: `wmic path Win32_DiskDriveToDiskPartition`

Looking particularly for the "Dependent" field which OSHI parses.

**Comment by dbwiddis** [comment]
Also `wmic path Win32_LogicalDiskToPartition`

I think I see a bug (WindowsDisks.java lines 431-434) where the disk to partition query is executed but the drive to partition property is used to fetch results.

**Comment by antonio-rodriges** [comment]
> wmic path Win32_DiskDriveToDiskPartition
Antecedent                                                             Dependent
\\PELLIGRINI\root\cimv2:Win32_DiskDrive.DeviceID="\\.\PHYSICALDRIVE0"  \\PELLIGRINI\root\cimv2:Win32_DiskPartition.DeviceID="Disk #0, Partition #0"
\\PELLIGRINI\root\cimv2:Win32_DiskDrive.DeviceID="\\.\PHYSICALDRIVE0"  \\PELLIGRINI\root\cimv2:Win32_DiskPartition.DeviceID="Disk #0, Partition #1"
\\PELLIGRINI\root\cimv2:Win32_DiskDrive.DeviceID="\\.\PHYSICALDRIVE0"  \\PELLIGRINI\root\cimv2:Win32_DiskPartition.DeviceID="Disk #0, Partition #2"
\\PELLIGRINI\root\cimv2:Win32_DiskDrive.DeviceID="\\.\PHYSICALDRIVE0"  \\PELLIGRINI\root\cimv2:Win32_DiskPartition.DeviceID="Disk #0, Partition #3"

 wmic path Win32_LogicalDiskToPartition
Antecedent                                                                    Dependent                                                EndingAddress  StartingAddress
\\PELLIGRINI\root\cimv2:Win32_DiskPartition.DeviceID="Disk #0, Partition #1"  \\PELLIGRINI\root\cimv2:Win32_LogicalDisk.DeviceID="C:"  131574352895   105906176
\\PELLIGRINI\root\cimv2:Win32_DiskPartition.DeviceID="Disk #0, Partition #3"  \\PELLIGRINI\root\cimv2:Win32_LogicalDisk.DeviceID="D:"  256059113471   132435230720

**Comment by dbwiddis** [comment]
Thanks!  Now to figure out where that "Unknown" came from!  A mystery!

**Comment by dbwiddis** [comment]
Actually....   are you sure the Unknown is attached to the C:?   Can you throw a newline into your debug format?  I wonder if it's outputting from partition #1 as C:\ and then it's picking up an Unknown as the first part of the next line.

**Comment by dbwiddis** [comment]
I suspect if you do `wmic path Win32_DiskPartition` you'll find an "Unknown" in the name field of partition #2.

**Comment by antonio-rodriges** [comment]
You may be right that Windows reports `unknown` at some places, but `C:\Unknown` is still misleading at runtime

**Comment by antonio-rodriges** [comment]
yes:

\\.\PHYSICALDRIVE0 ==> 
Installable File System | 
Installable File System | C:\
Unknown | 
Installable File System | D:\

**Comment by dbwiddis** [comment]
OK, so it seems like it's working as designed. You have 4 partitions.  Partitions 0, 1 and 3 are formatted as something other than FAT (probably NTFS), while partition 2 is probably not formatted. Partitions 1 and 3 are mounted to the filesystem at C:\ and D:\ respectively.
