### ISSUE TITLE
Network counters don't work on Solaris 10 / SunOS 5.10

### ISSUE THREAD

**Issue by Space2Man** [oshi/oshi#673]
Hi,

I am running OSHI on a system with SunOS 5.10:

SunOS <hostname> 5.10 Generic_150400-07 sun4u sparc SUNW,Sun-Fire-V490

I try to detect the active network interfaces by this (Groovy) code:

```
        networkIFs = OSHI.getNetworkIFs().findAll { ni ->
            log.debug("Checking network interface {}, traffic {}/{}", ni.name, ni.bytesRecv, ni.bytesSent)
            ni.name ==~ networkInterfaceRegEx &&
                    ni.bytesRecv > 0 &&
                    ni.bytesSent > 0
        }
```

But in the logs I see that it detects all interfaces but bytesRecv and bytesSent are 0 for all of them... I also noticed these errors in the logfile:

```
02/Nov/2018 15:45:52,537- ERROR KstatUtil: Failed lo lookup kstat value for key vendor_id
02/Nov/2018 15:45:52,547- ERROR KstatUtil: Failed lo lookup kstat value for key stepping
02/Nov/2018 15:45:52,548- ERROR KstatUtil: Failed lo lookup kstat value for key model
02/Nov/2018 15:45:52,548- ERROR KstatUtil: Failed lo lookup kstat value for key family
```

Maybe there is a generic issue with KstatUtil on this box since you are using KstatUtil.kstatLookup to get the counters for the network interfaces as well ...

Any idea?

Thanks,

    Space

**Comment by Space2Man** [comment]
Thanks as usual for the quick response. I think this is the reason:

> But on Solaris 11, with its completely new network stack, ....

Was not involved that much in Solaris and found out myself that 5.10 is not really supported anymore ... I will check if I still need to get that data or if I just by accident hit the only 5.10 machine still running :)

**Comment by dbwiddis** [comment]
Yep, if you read the whole issue you'll see the main difference is the "link" key vs. no key.

I think it would probably fix it if you replaced

        Kstat ksp = KstatUtil.kstatLookup("link", -1, netIF.getName());
        if (ksp != null && KstatUtil.kstatRead(ksp)) {

with

        Kstat ksp = KstatUtil.kstatLookup("link", -1, netIF.getName());
        if (ksp == null) { // Fails on Solaris 10 so try again
            ksp = KstatUtil.kstatLookup(null, -1, netIF.getName());
        }
        if (ksp != null && KstatUtil.kstatRead(ksp)) {

But I don't have a system to test on.

**Comment by Space2Man** [comment]
I can confirm that it's working on my system as well. Thanks!
