### ISSUE TITLE
Speed of OperatingSystem.getProcesses()

### ISSUE THREAD

**Issue by stefan-reich** [oshi/oshi#677]
It's fast on Windows (<200 ms), but on my Linux system it takes around 1 second (for 230 processes). Any way to speed it up maybe?

**Comment by dbwiddis** [comment]
All the Linux process code reads from various `proc` filesystem pseudo-files.  They are supposed to be virtual files and thus not incur very much filesystem latency.

On my Linux system it takes about 250 ms for 238 processes.  

I expect that caching some info, as mentioned in #676, could speed this up.  Any chance you can profile this and see if there's a particular call that's taking longer than the others?

**Comment by stefan-reich** [comment]
Here you are :) Repeated & sampled over 10 seconds, 10 times a second. Safe point bias applies.

The call actually takes 2 seconds even (quad core ~2 GHz).

55% core activity [95 samples taken]

15/52
java.base@11.0.1/java.lang.ProcessImpl.forkAndExec(Native Method)
java.base@11.0.1/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
java.base@11.0.1/java.lang.ProcessImpl.start(ProcessImpl.java:271)
java.base@11.0.1/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
java.base@11.0.1/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
java.base@11.0.1/java.lang.Runtime.exec(Runtime.java:591)
java.base@11.0.1/java.lang.Runtime.exec(Runtime.java:450)
oshi.util.ExecutingCommand.runNative(ExecutingCommand.java:68)
oshi.util.ExecutingCommand.runNative(ExecutingCommand.java:53)
oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:275)
oshi.software.os.linux.LinuxOperatingSystem.getProcesses(LinuxOperatingSystem.java:204)
main.oshi_listProcesses(main.java:49)


3/52
java.base@11.0.1/java.io.UnixFileSystem.checkAccess(Native Method)
java.base@11.0.1/java.io.File.canRead(File.java:769)
oshi.util.FileUtil.readFile(FileUtil.java:72)
oshi.util.FileUtil.getKeyValueMapFromFile(FileUtil.java:195)
oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:278)
oshi.software.os.linux.LinuxOperatingSystem.getProcesses(LinuxOperatingSystem.java:204)
main.oshi_listProcesses(main.java:49)


2/52
java.base@11.0.1/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
java.base@11.0.1/sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:48)
java.base@11.0.1/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
java.base@11.0.1/sun.nio.ch.IOUtil.read(IOUtil.java:245)
java.base@11.0.1/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:223)
java.base@11.0.1/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
java.base@11.0.1/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
java.base@11.0.1/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
java.base@11.0.1/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
java.base@11.0.1/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
java.base@11.0.1/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
java.base@11.0.1/java.io.InputStreamReader.read(InputStreamReader.java:185)
java.base@11.0.1/java.io.BufferedReader.fill(BufferedReader.java:161)
java.base@11.0.1/java.io.BufferedReader.readLine(BufferedReader.java:326)
java.base@11.0.1/java.io.BufferedReader.readLine(BufferedReader.java:392)
java.base@11.0.1/java.nio.file.Files.readAllLines(Files.java:3330)
oshi.util.FileUtil.readFile(FileUtil.java:75)
oshi.util.FileUtil.getStringFromFile(FileUtil.java:155)
oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:288)
oshi.software.os.linux.LinuxOperatingSystem.getProcesses(LinuxOperatingSystem.java:204)
main.oshi_listProcesses(main.java:49)


2/52
java.base@11.0.1/sun.nio.fs.UnixNativeDispatcher.open0(Native Method)
java.base@11.0.1/sun.nio.fs.UnixNativeDispatcher.open(UnixNativeDispatcher.java:71)
java.base@11.0.1/sun.nio.fs.UnixChannelFactory.open(UnixChannelFactory.java:267)
java.base@11.0.1/sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:143)
java.base@11.0.1/sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:156)
java.base@11.0.1/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:213)
java.base@11.0.1/java.nio.file.Files.newByteChannel(Files.java:370)
java.base@11.0.1/java.nio.file.Files.newByteChannel(Files.java:421)
java.base@11.0.1/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
java.base@11.0.1/java.nio.file.Files.newInputStream(Files.java:155)
java.base@11.0.1/java.nio.file.Files.newBufferedReader(Files.java:2838)
java.base@11.0.1/java.nio.file.Files.readAllLines(Files.java:3327)
oshi.util.FileUtil.readFile(FileUtil.java:75)
oshi.util.FileUtil.getStringFromFile(FileUtil.java:155)
oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:288)
oshi.software.os.linux.LinuxOperatingSystem.getProcesses(LinuxOperatingSystem.java:204)
main.oshi_listProcesses(main.java:49)


2/52
java.base@11.0.1/java.io.UnixFileSystem.canonicalize0(Native Method)
java.base@11.0.1/java.io.UnixFileSystem.canonicalize(UnixFileSystem.java:178)
java.base@11.0.1/java.io.File.getCanonicalPath(File.java:618)
oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:291)
oshi.software.os.linux.LinuxOperatingSystem.getProcesses(LinuxOperatingSystem.java:204)
main.oshi_listProcesses(main.java:49)


2/52
java.base@11.0.1/java.lang.String.split(String.java:2290)
java.base@11.0.1/java.lang.String.split(String.java:2364)
oshi.util.FileUtil.getKeyValueMapFromFile(FileUtil.java:197)
oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:278)
oshi.software.os.linux.LinuxOperatingSystem.getProcesses(LinuxOperatingSystem.java:204)
main.oshi_listProcesses(main.java:49)


1/52
java.base@11.0.1/java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3950)
java.base@11.0.1/java.util.regex.Pattern$Start.match(Pattern.java:3606)
java.base@11.0.1/java.util.regex.Matcher.search(Matcher.java:1729)
java.base@11.0.1/java.util.regex.Matcher.find(Matcher.java:773)
java.base@11.0.1/java.util.Formatter.parse(Formatter.java:2702)
java.base@11.0.1/java.util.Formatter.format(Formatter.java:2655)
java.base@11.0.1/java.util.Formatter.format(Formatter.java:2609)
java.base@11.0.1/java.lang.String.format(String.java:2897)
oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:278)
oshi.software.os.linux.LinuxOperatingSystem.getProcesses(LinuxOperatingSystem.java:204)
main.oshi_listProcesses(main.java:49)


1/52
java.base@11.0.1/java.util.regex.Pattern.split(Pattern.java:1274)
java.base@11.0.1/java.util.regex.Pattern.split(Pattern.java:1334)
oshi.util.FileUtil.getSplitFromFile(FileUtil.java:176)
oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:218)
oshi.software.os.linux.LinuxOperatingSystem.getProcesses(LinuxOperatingSystem.java:204)
main.oshi_listProcesses(main.java:49)


1/52
java.base@11.0.1/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
java.base@11.0.1/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
java.base@11.0.1/java.lang.Runtime.exec(Runtime.java:591)
java.base@11.0.1/java.lang.Runtime.exec(Runtime.java:450)
oshi.util.ExecutingCommand.runNative(ExecutingCommand.java:68)
oshi.util.ExecutingCommand.runNative(ExecutingCommand.java:53)
oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:275)
oshi.software.os.linux.LinuxOperatingSystem.getProcesses(LinuxOperatingSystem.java:204)
main.oshi_listProcesses(main.java:49)


1/52
java.base@11.0.1/java.util.Formatter.parse(Formatter.java:2714)
java.base@11.0.1/java.util.Formatter.format(Formatter.java:2655)
java.base@11.0.1/java.util.Formatter.format(Formatter.java:2609)
java.base@11.0.1/java.lang.String.format(String.java:2897)
oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:278)
oshi.software.os.linux.LinuxOperatingSystem.getProcesses(LinuxOperatingSystem.java:204)
main.oshi_listProcesses(main.java:49)


1/52
java.base@11.0.1/java.lang.reflect.Array.newInstance(Array.java:78)
java.base@11.0.1/java.util.TimSort.<init>(TimSort.java:157)
java.base@11.0.1/java.util.TimSort.sort(TimSort.java:230)
java.base@11.0.1/java.util.Arrays.sort(Arrays.java:1441)
oshi.software.os.linux.LinuxOperatingSystem.init(LinuxOperatingSystem.java:111)
oshi.software.os.linux.LinuxOperatingSystem.<init>(LinuxOperatingSystem.java:90)
oshi.SystemInfo.getOperatingSystem(SystemInfo.java:95)
main.oshi_listProcesses(main.java:49)


1/52
java.base@11.0.1/java.util.Formatter.checkText(Formatter.java:2728)
java.base@11.0.1/java.util.Formatter.parse(Formatter.java:2708)
java.base@11.0.1/java.util.Formatter.format(Formatter.java:2655)
java.base@11.0.1/java.util.Formatter.format(Formatter.java:2609)
java.base@11.0.1/java.lang.String.format(String.java:2897)
oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:288)
oshi.software.os.linux.LinuxOperatingSystem.getProcesses(LinuxOperatingSystem.java:204)
main.oshi_listProcesses(main.java:49)


1/52
java.base@11.0.1/java.lang.ProcessHandleImpl.isAlive0(Native Method)
java.base@11.0.1/java.lang.ProcessHandleImpl.getInternal(ProcessHandleImpl.java:250)
java.base@11.0.1/java.lang.ProcessImpl.<init>(ProcessImpl.java:348)
java.base@11.0.1/java.lang.ProcessImpl.start(ProcessImpl.java:271)
java.base@11.0.1/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
java.base@11.0.1/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
java.base@11.0.1/java.lang.Runtime.exec(Runtime.java:591)
java.base@11.0.1/java.lang.Runtime.exec(Runtime.java:450)
oshi.util.ExecutingCommand.runNative(ExecutingCommand.java:68)
oshi.util.ExecutingCommand.runNative(ExecutingCommand.java:53)
oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:275)
oshi.software.os.linux.LinuxOperatingSystem.getProcesses(LinuxOperatingSystem.java:204)
main.oshi_listProcesses(main.java:49)


1/52
java.base@11.0.1/java.lang.Long.parseLong(Long.java:817)
oshi.util.ParseUtil.parseLongOrDefault(ParseUtil.java:403)
oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:266)
oshi.software.os.linux.LinuxOperatingSystem.getProcesses(LinuxOperatingSystem.java:204)
main.oshi_listProcesses(main.java:49)


1/52
java.base@11.0.1/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
java.base@11.0.1/sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:48)
java.base@11.0.1/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
java.base@11.0.1/sun.nio.ch.IOUtil.read(IOUtil.java:245)
java.base@11.0.1/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:223)
java.base@11.0.1/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
java.base@11.0.1/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
java.base@11.0.1/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
java.base@11.0.1/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
java.base@11.0.1/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
java.base@11.0.1/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
java.base@11.0.1/java.io.InputStreamReader.read(InputStreamReader.java:185)
java.base@11.0.1/java.io.BufferedReader.fill(BufferedReader.java:161)
java.base@11.0.1/java.io.BufferedReader.readLine(BufferedReader.java:326)
java.base@11.0.1/java.io.BufferedReader.readLine(BufferedReader.java:392)
java.base@11.0.1/java.nio.file.Files.readAllLines(Files.java:3330)
oshi.util.FileUtil.readFile(FileUtil.java:75)
oshi.util.FileUtil.getKeyValueMapFromFile(FileUtil.java:195)
oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:278)
oshi.software.os.linux.LinuxOperatingSystem.getProcesses(LinuxOperatingSystem.java:204)
main.oshi_listProcesses(main.java:49)


1/52
java.base@11.0.1/sun.nio.fs.UnixNativeDispatcher.open0(Native Method)
java.base@11.0.1/sun.nio.fs.UnixNativeDispatcher.open(UnixNativeDispatcher.java:71)
java.base@11.0.1/sun.nio.fs.UnixChannelFactory.open(UnixChannelFactory.java:267)
java.base@11.0.1/sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:143)
java.base@11.0.1/sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:156)
java.base@11.0.1/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:213)
java.base@11.0.1/java.nio.file.Files.newByteChannel(Files.java:370)
java.base@11.0.1/java.nio.file.Files.newByteChannel(Files.java:421)
java.base@11.0.1/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
java.base@11.0.1/java.nio.file.Files.newInputStream(Files.java:155)
java.base@11.0.1/java.nio.file.Files.newBufferedReader(Files.java:2838)
java.base@11.0.1/java.nio.file.Files.readAllLines(Files.java:3327)
oshi.util.FileUtil.readFile(FileUtil.java:75)
oshi.util.FileUtil.getSplitFromFile(FileUtil.java:173)
oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:218)
oshi.software.os.linux.LinuxOperatingSystem.getProcesses(LinuxOperatingSystem.java:204)
main.oshi_listProcesses(main.java:49)


1/52
java.base@11.0.1/java.lang.StringBuilder.append(StringBuilder.java:213)
java.base@11.0.1/java.lang.StringBuilder.append(StringBuilder.java:85)
java.base@11.0.1/java.util.Formatter$FixedString.print(Formatter.java:2754)
java.base@11.0.1/java.util.Formatter.format(Formatter.java:2661)
java.base@11.0.1/java.util.Formatter.format(Formatter.java:2609)
java.base@11.0.1/java.lang.String.format(String.java:2897)
oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:288)
oshi.software.os.linux.LinuxOperatingSystem.getProcesses(LinuxOperatingSystem.java:204)
main.oshi_listProcesses(main.java:49)


1/52
java.base@11.0.1/java.util.regex.Matcher.reset(Matcher.java:406)
java.base@11.0.1/java.util.regex.Matcher.<init>(Matcher.java:253)
java.base@11.0.1/java.util.regex.Pattern.matcher(Pattern.java:1133)
java.base@11.0.1/java.util.Formatter.parse(Formatter.java:2700)
java.base@11.0.1/java.util.Formatter.format(Formatter.java:2655)
java.base@11.0.1/java.util.Formatter.format(Formatter.java:2609)
java.base@11.0.1/java.lang.String.format(String.java:2897)
oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:224)
oshi.software.os.linux.LinuxOperatingSystem.getProcesses(LinuxOperatingSystem.java:204)
main.oshi_listProcesses(main.java:49)


1/52
java.base@11.0.1/java.lang.Throwable.fillInStackTrace(Native Method)
java.base@11.0.1/java.lang.Throwable.fillInStackTrace(Throwable.java:787)
java.base@11.0.1/java.lang.Throwable.<init>(Throwable.java:270)
java.base@11.0.1/java.lang.Exception.<init>(Exception.java:66)
java.base@11.0.1/java.lang.RuntimeException.<init>(RuntimeException.java:62)
java.base@11.0.1/java.lang.IllegalArgumentException.<init>(IllegalArgumentException.java:52)
java.base@11.0.1/java.lang.NumberFormatException.<init>(NumberFormatException.java:55)
java.base@11.0.1/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
java.base@11.0.1/java.lang.Long.parseLong(Long.java:702)
java.base@11.0.1/java.lang.Long.parseLong(Long.java:817)
oshi.util.ParseUtil.parseLongOrDefault(ParseUtil.java:403)
oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:271)
oshi.software.os.linux.LinuxOperatingSystem.getProcesses(LinuxOperatingSystem.java:204)
main.oshi_listProcesses(main.java:49)


1/52
java.base@11.0.1/java.lang.ProcessImpl.forkAndExec(Native Method)
java.base@11.0.1/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
java.base@11.0.1/java.lang.ProcessImpl.start(ProcessImpl.java:271)
java.base@11.0.1/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
java.base@11.0.1/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
java.base@11.0.1/java.lang.Runtime.exec(Runtime.java:591)
java.base@11.0.1/java.lang.Runtime.exec(Runtime.java:450)
oshi.util.ExecutingCommand.runNative(ExecutingCommand.java:68)
oshi.util.ExecutingCommand.runNative(ExecutingCommand.java:53)
oshi.util.ExecutingCommand.getAnswerAt(ExecutingCommand.java:114)
oshi.util.ExecutingCommand.getFirstAnswer(ExecutingCommand.java:99)
oshi.software.os.linux.LinuxOperatingSystem.init(LinuxOperatingSystem.java:149)
oshi.software.os.linux.LinuxOperatingSystem.<init>(LinuxOperatingSystem.java:90)
oshi.SystemInfo.getOperatingSystem(SystemInfo.java:95)
main.oshi_listProcesses(main.java:49)


1/52
java.base@11.0.1/java.lang.String.split(String.java:2364)
oshi.util.FileUtil.getKeyValueMapFromFile(FileUtil.java:197)
oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:278)
oshi.software.os.linux.LinuxOperatingSystem.getProcesses(LinuxOperatingSystem.java:204)
main.oshi_listProcesses(main.java:49)


1/52
java.base@11.0.1/java.util.HashMap.putVal(HashMap.java:624)
java.base@11.0.1/java.util.HashMap.put(HashMap.java:607)
oshi.util.FileUtil.getKeyValueMapFromFile(FileUtil.java:199)
oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:278)
oshi.software.os.linux.LinuxOperatingSystem.getProcesses(LinuxOperatingSystem.java:204)
main.oshi_listProcesses(main.java:49)

**Comment by dbwiddis** [comment]
Thanks!  Great info!

Looks like almost 30% of the time is in execution of the `ls -f /proc/%d/fd` calls. Not sure using `lsof` would be any faster but could at least get all the processes in one call and store in a map.

I suspect caching would mitigate many of the other issues, as would possibly running `ps` once and gathering some info, then refining it with `proc` calls.

**Comment by stefan-reich** [comment]
https://github.com/oshi/oshi/pull/680

goes down from 2 seconds to 100-200 ms in my tests
