### ISSUE TITLE
when accessing hardware sensors, cpu temp sometimes throws a class cast exception

### ISSUE THREAD

**Issue by spyhunter99** [oshi/oshi#679]
error message says something like

`CURRENTV is not an unsigned int`

it'll be accessible for a few dozen or so queries then starts throwing that error message and never recovers. This is on a windows server in a vm. Not too sure how that works but it's not reliable and throws unexpectedly. this was with 3.9.1

**Comment by spyhunter99** [comment]
i should know tomorrow. if you need to close, go ahead. we can always
reopen. This issue came up on a particular set of machines with identical
models while running in vm's. i'm actually surprised the value was even
available in a vm.

**Comment by dbwiddis** [comment]
Don't "need" to close, just like to make sure there's nothing else I can do!   There may not be an actual value, but a "zero" value with the wrong type would throw an error while a "null" value wouldn't.  Ironically the type checking I'm flagging isn't even necessary for the way we parse the value, but it doesn't hurt to be more precise... when you don't make mistakes typing it in the first place!

**Comment by spyhunter99** [comment]
it's no longer throwing an exception, which is good. There is one more environmental factor that may have been related. I won't have the test results until monday or tuesday. At least it's not throwing anymore and returning a consistent value for cpu voltage.

**Comment by dbwiddis** [comment]
Cool. I’ll close this issue and if you find something else in your testing it’ll be a new issue.
