### ISSUE TITLE
Spring Boot hanging at start with a javaagent which uses oshi

### ISSUE THREAD

**Issue by uqix** [oshi/oshi#681]
My javaagent uses oshi to print system info, however, when I start a Spring Boot demo app with this agent, the app just hangs after ':: Spring Boot ::        (v2.1.0.RELEASE)' printed without any further logs.

Any tip will be appreciated!

**Comment by dbwiddis** [comment]
One possibility is that SpringBoot may include an older version of OSHI's dependencies, specifically JNA.  Try specifying the latest version in your own POM.

**Comment by uqix** [comment]
@dbwiddis Thanks a lot! 
I just figured out that the problem is logging not hanging - the Spring Boot app keeps running without logs, I think the reason is oshi and Spring Boot both depend on slf4j, my javaagent is packaged with oshi thus slf4j as uber jar, at runtime, slf4j just can not find the binding due to class loading problem.

**Comment by dbwiddis** [comment]
Thanks for letting us know your solution!  Hope it helps someone else!
