### ISSUE TITLE
os version has only major number on CentOs

### ISSUE THREAD

**Issue by Anton-A-Ivanov** [oshi/oshi#682]
seems that /etc/os-release does not contain minor version in CentOs, but /etc/system-release does. detection of os version stops after /etc/os-release version is obtained from first file, this lead to lack of minor release number in OperatingSystemVersion::getVersion()

I've checked also on RHEL, and there is no /etc/os-release, so version is read fully from /etc/system-release

Here is what I get on my CentOS host

> cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

> cat /etc/system-release 
CentOS Linux release 7.4.1708 (Core)

**Comment by dbwiddis** [comment]
Care to take a crack at a PR to fix this?

**Comment by Anton-A-Ivanov** [comment]
Hi, sorry for late answer. There is no lsb-release files in /etc/ on the machine:
> ls -l /etc/*release*
-rw-r--r--. 1 root root  38 Aug 30  2017 /etc/centos-release
-rw-r--r--. 1 root root  51 Aug 30  2017 /etc/centos-release-upstream
-rw-r--r--. 1 root root 393 Aug 30  2017 /etc/os-release
lrwxrwxrwx. 1 root root  14 Jan 25  2018 /etc/redhat-release -> centos-release
lrwxrwxrwx. 1 root root  14 Jan 25  2018 /etc/system-release -> centos-release
-rw-r--r--. 1 root root  23 Aug 30  2017 /etc/system-release-cpe

> cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)
> cat /etc/centos-release-upstream
Derived from Red Hat Enterprise Linux 7.4 (Source)

As for "Care to take a crack at a PR to fix this?" - I was also thinking of rearranging possible sources of OS version, but I doubt I can test my patch enough to make sure it not only fix my problem but also does not break something else on some other linux, and this stops me

Another alternative I see is to get all choises from all possible sources (now it stops after first success ) and then select the best one (say, the longest one, or some by other algorithm of choice). Or at least do not stop trying to get version from the next source if the one you get now is not good enough (e.g. has no minor version)

**Comment by dbwiddis** [comment]
Thanks. Looks like this particular file is only on Fedora-based / CentOS distros, so I jumped it to the head of the line there.  Re-open this issue if this doesn't fix it.
