### ISSUE TITLE
LibC.getpagesize() is not portable and proc/pid/stat parsing is broken

### ISSUE THREAD

**Issue by Space2Man** [oshi/oshi#687]
Hi,

I am trying to watch memory consumption of processes and on some systems it returns 0 for residentSetSize but other values like virtualSize, bytesRead, bytesWritten have correct values.

So far I noticed this on Linux. Starting with debugging now.

**Comment by Space2Man** [comment]
Hm, I have no clue why this happens ... Field 24 has value 116015, but OSProcess.residentSetSize has value 0 ... could it be that Libc.INSTANCE.getpagesize(); returns 0?

According to man page looks like there is a better way to get the pagesize - see [http://man7.org/linux/man-pages/man2/getpagesize.2.html](http://man7.org/linux/man-pages/man2/getpagesize.2.html):

>        Portable applications should employ sysconf(_SC_PAGESIZE) instead of
>        getpagesize():
> 
>            #include <unistd.h>
>            long sz = sysconf(_SC_PAGESIZE);
> 
>        (Most systems allow the synonym _SC_PAGE_SIZE for _SC_PAGESIZE.)

Not sure though if this is possible in JNA ...

**Comment by Space2Man** [comment]
getconf PAGE_SIZE seems to return 4096 on the system ... still trying to debug to see what getpagesize() returns on that system ...

**Comment by dbwiddis** [comment]
Yes, `sysconf()` is possible in JNA.   I tested it for `sysconf(_SC_CLK_TCK)` and it worked fine... but that relies on us knowing that constant (2, in that case, I think).  I did end up just using the `getconf` command line, though, to avoid hardcoding that constant and it's reasonable to do the same for pagesize.

**Comment by Space2Man** [comment]
Yep, saw that commit ... hope to find the time tomorrow to test

**Comment by Space2Man** [comment]
One question: when I try to build my debug version, where do I need to put the license stuff?

[ERROR] Failed to execute goal com.mycila:license-maven-plugin:3.0:format (default) on project oshi-core: Execution default of goal com.mycila:license-maven-plugin:3.0:format failed: Cannot read header document LICENSE_HEADER. Cause: Resource LICENSE_HEADER not found in file system, classpath or URL: no protocol: LICENSE_HEADER -> [Help 1]

**Comment by Space2Man** [comment]
Ah, wait ... I think I found the L8 problem ...

**Comment by dbwiddis** [comment]
Not sure whether if you do command line if you should do PAGE_SIZE or PAGESIZE... I think the latter.

I did look up the page size constant... 28.  So defining `sysconf()` in the shared Unix LibC and the constants _SC_CLK_TCK = 2 and _SC_PAGE_SIZE = 28 in the Linux Libc would probably work as well.

**Comment by Space2Man** [comment]
Hm, just was able to reproduce. But it detects correct page size ... so I will try to debug further.

**Comment by dbwiddis** [comment]
I've found values including 11, 28, and 48 for _SC_PAGE_SIZE in various header files.  I think our only option here is the `getconf` commandline.  I do believe the `PAGESIZE` value is the official version.

**Comment by Space2Man** [comment]
Added some debug:

LinuxOperatingSystem: Found RSS 0, memoryPageSize 4096 for process with pid 21950

**Comment by Space2Man** [comment]
I don't understand why the parseUtil fails to parse field 24:

20/Nov/2018 17:48:07,537- DEBUG LinuxOperatingSystem: FOund stat: 21950 (java) S 21949 21950 21950 0 -1 4202752 579491 0 348 0 677521 347772 0 0 20 0 38 0 3827154149 2602713088 49424 18446744073709551615 4194304 4196468 140721777775920 140721777758464 265512059645 0 0 2 16800973 18446744073709551615 0 0 17 0 0 0 0 0 0
20/Nov/2018 17:48:07,537- DEBUG LinuxOperatingSystem: Found RSS 0, memoryPageSize 4096 for process with pid 21950

**Comment by Space2Man** [comment]
Hm, virtualSize (which should be field 23) gives a hint:

"virtualSize":347772

It detects field 15 as VSS and therefore field 16 as RSS (which is 0)

 21950 (java) S 21949 21950 21950 0 -1 4202752 579491 0 348 0 677521 347772 0 0 20 0 38 0 3827154149 2602713088 49424

**Comment by dbwiddis** [comment]
This is a case where premature optimization is biting me. :)

Different kernels have different total numbers of fields in `/proc/<pid>/stat`. See the static variable `procPidStatLength`.

Until recently, we calculated that value for what we thought was the "youngest" process as part of the HZ calculation.  However, that calculation has been removed, and with it the new length calculation.

The fix is to add a static field below the `procPidStatLength` definition that reads `/proc/self/stat` and counts the fields after the closing process name right-paren.

**Comment by dbwiddis** [comment]
See #626 for the code that was removed that used to calculate this. That `procPidStatLength` calculation in the `init()` method needs to be put back in in some form.

**Comment by Space2Man** [comment]
But you could use it for pid 1 which should always exist on Linux :)

**Comment by dbwiddis** [comment]
Yep, command name can contain spaces. So you need to "split all whitespace except whitespace between the first set of parenthesis".    Or just split on `)` first, and then split the second part by whitespace.  Or slightly more efficient than splitting on `)` is finding its position and using substring, which is what I did before.  You could also, probably most efficiently, character iterate, looking for `)` to start counting and then incrementing every space.

**Comment by dbwiddis** [comment]
Pid 1 may exist but `/proc/self/` also always exists. :)

**Comment by Space2Man** [comment]
ah, sure :)

**Comment by Space2Man** [comment]
I will check tomorrow ...

**Comment by dbwiddis** [comment]
I'll try to tackle both these issues tonight, so perhaps you can just test snapshot in about 12+ hours from now.

**Comment by Space2Man** [comment]
sure :)

**Comment by dbwiddis** [comment]
Did the code in #688 and merged but can't push to snapshot until I get home.  But if you can pull the latest code and test should work for ya... reopen this issue if it doesn't!

**Comment by Space2Man** [comment]
Man, you are fast ... I will do the test when I go to work tomorrow morning!

**Comment by Space2Man** [comment]
Hi,

I have tried to test and packaging fails during the tests:

```
[ERROR] Errors: 
[ERROR]   OperatingSystemTest.testGetChildProcesses:140 » NullPointer
[ERROR]   OperatingSystemTest.testGetCommandLine:258 » NullPointer
[ERROR]   OperatingSystemTest.testOperatingSystem:60 » NullPointer
[ERROR]   OperatingSystemTest.testProcessQueryByList:106 » NullPointer
```

Have you updated the snapshot already?

**Comment by dbwiddis** [comment]
Bummer on the nulls.  However I can't seem to figure out where the test failures are coming from. Is this the `oshi-core` or `oshi-json` artifact?

**Comment by Space2Man** [comment]
It's from oshi-core ... Have you updated the SNAPSHOT? Because I still get the same results ...

**Comment by dbwiddis** [comment]
Yes, SNAPSHOT was updated at 22:23 PST / 01:23 EST / 06:23 UTC.  Could use a more detailed stack trace than a failed test.

**Comment by Space2Man** [comment]
seems to come from latest commit (Optionally check ...)
When testing against 23bea1b6a6e25eb43378f940a1fd7e436dd054fa packaging completes and results are as expected.

**Comment by dbwiddis** [comment]
Well I'm baffled. All the failures have in common the line: `os.getProcesses(0, null)`. It looks like doing a process sort with a null sorting enum is the issue, but that wasn't a recent change.

**Comment by Space2Man** [comment]
FYI: I am packaging on Windows :( ... it seems to be this call which fails:

List<OSProcess> procList = processMapToList(null, slowFields);

**Comment by dbwiddis** [comment]
Try now.   HEAD updated, pushing SNAPSHOT.

**Comment by Space2Man** [comment]
you were a minute faster :) Just wanted to give you the hint regards

List<Integer> pidsToKeep = new ArrayList<>(pids.size());

**Comment by Space2Man** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project oshi-json: Compilation failure
[ERROR] /C:/Users/jheuer2/OneDrive - DXC Production/Daten/Projects/oshi/oshi-json/src/main/java/oshi/json/software/os/impl/OperatingSystemImpl.java:[113,53] no suitable method found for getProcesses(int,oshi.software.os.OperatingSystem.ProcessSort,boolean)
[ERROR] method oshi.software.os.OperatingSystem.getProcesses(int,oshi.software.os.OperatingSystem.ProcessSort) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] method oshi.software.os.OperatingSystem.getProcesses(java.util.Collection<java.lang.Integer>) is not applicable
[ERROR] (actual and formal argument lists differ in length)

**Comment by dbwiddis** [comment]
Try `mvn update`.  Adding the new method in `oshi-core` requires the new compiled version be available to `oshi-json`.

**Comment by Space2Man** [comment]
yep, completes just fine.

**Comment by dbwiddis** [comment]
Woot!  Off to bed before you find other problems. ;)

**Comment by Space2Man** [comment]
Have a good night!
