### ISSUE TITLE
Unique Computer Identifier (HW fingerprint) Util method

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#693]
I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to open source before. This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. :-) Here are the steps to get a PR merged here.

- [ ] Read the [CONTRIBUTING](CONTRIBUTING.md) file for reference.  I'll walk you through anything you don't understand.
- [ ] Find the [Util.java](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/util/Util.java) class.
- [ ] Add a new method to that class matching the code snippet in [this StackOverflow Answer](https://stackoverflow.com/questions/1986732/how-to-get-a-unique-computer-identifier-in-java-like-disk-id-or-motherboard-id/37705082#37705082).
- [ ] Optionally, replace string representation of each output with its `hashcode()`.
- [ ] Fork the project, commit your changes to your fork, create a PR, and get it merged
- [ ] Celebrate

**Comment by Aashishthakur10** [comment]
Hi, I would like to pick this up.

**Comment by dbwiddis** [comment]
Excellent, @aashishthakur!

I’m here for any questions you might have!

**Comment by MartIden** [comment]
If i commited changes, what can i do next?

**Comment by Aashishthakur10** [comment]
Hi @dbwiddis, I have made the changes but since the method I have written is not referenced anywhere how can I test it?

**Comment by dbwiddis** [comment]
You can create a new UtilTest class in the test directory/package structure and test the return value is sensible (find delimiter positions, etc.)

**Comment by dbwiddis** [comment]
@Martiden, where did you commit? Generally you fork this repository on github and set up a local branch to edit and push to your local repo, then make a pull request when it is ready to submit.

**Comment by Aashishthakur10** [comment]
@dbwiddis I called in my method in the already existing UtilTest file. It seems to be working fine. The only question I had is we need the hashcode value of vendor, processorSerialNumber, processorIdentifier right?

**Comment by dbwiddis** [comment]
I listed that above as "optional". The main goal is for you to learn the process of submitting pull requests and making changes.   I would love if the output was of the form `String.format("%08x", vendor.hashcode()) + "-" + ...` but that's just my preference.  This is your submission so you can be as creative (or not) as you want!

**Comment by dbwiddis** [comment]
Closed in #694
