### ISSUE TITLE
Does NetworkIF#getSpeed represent link speed or the max speed of the nic?

### ISSUE THREAD

**Issue by spyhunter99** [oshi/oshi#695]
Does NetworkIF#getSpeed represent link speed or the max speed of the nic?

**Comment by dbwiddis** [comment]
It's whatever the OS provides... I believe max speed (e.g., 100 MBits/sec)... to calculate throughput you have to use the bytes sent/received over time.

**Comment by spyhunter99** [comment]
well link speed can be different than max speed. If i connect a broken or incorrect cat5 cable to a 1Gbps interface, it can connect at 100Mbps. This can also be true for modems, radio/cellular links, etc

**Comment by dbwiddis** [comment]
On [Linux](https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-net), it's:
> the interface latest or current speed value. Value is an integer representing the link speed in Mbits/sec.

On [Windows](https://docs.microsoft.com/en-us/windows/desktop/cimwin32prov/cim-networkadapter), it's:
> Estimate of the current bandwidth in bits per second. For endpoints which vary in bandwidth or for those where no accurate estimation can be made, this property should contain the nominal bandwidth.

(Where nominal is the max)

On [MacOS](https://opensource.apple.com/source/network_cmds/network_cmds-480/ifconfig.tproj/ifconfig.c.auto.html) it's Link Speed (technically "link rate").

Haven't checked Unix but I detect a pattern here. :)

**Comment by spyhunter99** [comment]
cool, thanks
