### ISSUE TITLE
I am not getting how to get all supported display resolutions

### ISSUE THREAD

**Issue by prasanna532** [oshi/oshi#697]

**Comment by dbwiddis** [comment]
OSHI only retrieves the [EDID](https://en.wikipedia.org/wiki/Extended_Display_Identification_Data) for displays.  While there is an `EdidUtil` class to help parse some of this, there are simply too many options to attempt to parse all of them, and there are [numerous](http://www.edidreader.com/)  [utilities](https://metacpan.org/pod/Parse::EDID) [available](http://manpages.ubuntu.com/manpages/bionic/man1/get-edid.1.html) for those who need the more detailed information.
