### ISSUE TITLE
Is there support for detecting earphones/headphones plugged into audio?

### ISSUE THREAD

**Issue by rigorio** [oshi/oshi#698]

**Comment by dbwiddis** [comment]
Short answer: no.

Long answer: there could be if you want to contribute code to add it!

**Comment by BilalAM** [comment]
This sounds interesting , I'll look into this over the weekend

**Comment by dbwiddis** [comment]
[Might not be possible](https://stackoverflow.com/questions/861601/detecting-when-head-phones-are-plugged-in).  

There may be room for a more generic "device tree" generation similar to the USB code but including all devices, allowing text search of results.

**Comment by rigorio** [comment]
> [Might not be possible](https://stackoverflow.com/questions/861601/detecting-when-head-phones-are-plugged-in).
> 
> There may be room for a more generic "device tree" generation similar to the USB code but including all devices, allowing text search of results.

Seems so. Hopefully this becomes possibly in the future. Thanks!

**Comment by shanmukhateja** [comment]
Hi, on the Linux front, the answer to this is not entirely possible.
Since, not all drivers do not have support for this option due to the hardware lacking the said feature on "newer" devices. This is why majority of Linux distributions have chosen to show a pop-up asking user to choose the appropriate device manually.

I couldn't find the exact one I referred to previously but this should suffice for this comment: 
[Open link](https://unix.stackexchange.com/q/25776)

**Comment by dbwiddis** [comment]
Closing this issue since it appears not possible.

**Comment by stefan-reich** [comment]
I have something [for Linux](http://tinybrain.de/1020333):

```
static int linux_rawHeadphonesCount() {
  int n = 0;
  for (File dir : listDirsStartingWith("/proc/asound", "card"))
    n += l(startingWithAfterLtrim(linesFromFile(newFile(dir, "codec#0")), "Pin-ctls: 0x00"));
  ret n;
}
```

Downside is that it returns a value with an offset - like 2 when headphones are not plugged in and 3 when they are. I wasn't sure how to get around that.

**Comment by stefan-reich** [comment]
FWIW, I have this working now. It's really useful to detect the presence of headphones for my voice dialog system. I urge the user to plug the headphones in or out once to know the min and max value, then it works fine. Still Linux only, of course.
