### ISSUE TITLE
Build related, license-maven-plugin fails when running the build from a child module

### ISSUE THREAD

**Issue by spyhunter99** [oshi/oshi#712]
build related issue and relatively minor at that. may not be worth fixing but it is kind of annoying. Good thing oshi is a relatively small project

````
git clone https://github.com/oshi/oshi.git
mvn clean install
cd oshi-core
mvn clean install
````

error message
````
[ERROR] Failed to execute goal com.mycila:license-maven-plugin:3.0:format (default) on project oshi-core: Execution default of goal com.mycila:license-maven-plugin:3.0:format failed: Cannot read header document LICENSE_HEADER. Cause: Resource LICENSE_HEADER not found in file system, classpath or URL: no protocol: LICENSE_HEADER -> [Help 1]
````

**Comment by dbwiddis** [comment]
Can you build it from the parent directory?

```
git clone https://github.com/oshi/oshi.git
mvn clean install -pl oshi-core
```

**Comment by spyhunter99** [comment]
yes that works just fine. just a minor issue

**Comment by dbwiddis** [comment]
You're welcome to fix it if you know maven better than I do!

**Comment by dbwiddis** [comment]
It looks like the solution is to [put the license header on the classpath](https://stackoverflow.com/questions/23274539/maven-license-plugin-use-license-for-parentpom-for-all-children).  This would either mean a new artifact/package that everything depended on, or a new package inside `oshi-core` that all the other packages depend on.  All of this seems like overkill.
