### ISSUE TITLE
NPE on HardwareAbstractionLayer::getComputerSystem for windows 7 and 10 when java as a service (admin account)

### ISSUE THREAD

**Issue by iXo** [oshi/oshi#719]
Hi, I have a problem since some times now :

I am using oshi in a java application that is started as a service on windows 10 LTSB with an admin account.

The problem is for this code : 

`		final SystemInfo si = new SystemInfo();
		final HardwareAbstractionLayer hal = si.getHardware();
		final ComputerSystem computerSystem = hal.getComputerSystem();`

The last line result in a NPE : 

`java.lang.NullPointerException: null
	at oshi.util.platform.windows.WmiUtil.queryWMI(WmiUtil.java:140)
	at oshi.hardware.platform.windows.WindowsComputerSystem.init(WindowsComputerSystem.java:61)
	at oshi.hardware.platform.windows.WindowsComputerSystem.<init>(WindowsComputerSystem.java:55)
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getComputerSystem(WindowsHardwareAbstractionLayer.java:43)
	at infos.SystemInfos.getSystemInfos(SystemInfos.java:53)`

It doesn't seems to be a problem with WMI not ready as if I stop my service, and start it manually (from the service application) I still have this problem.

**Comment by dbwiddis** [comment]
The NPE is on a line processing a COMException from JNA, for which the `HRESULT` is allowed to be `null`.  We need to check for that null.  Can you submit a PR?  If not, i'll toss this one to the first-timers-only list.

**Comment by iXo** [comment]
Thanks for your lightning fast reply ! I don't really know what I could send for the PR, as if we check for the HRESULT is null, this will prevent the exception, but I don't know how to resolve the fact the com is not initialized. 
I would like to help more.
I can try any modification you want me to test.

**Comment by dbwiddis** [comment]
Well, it's catching the exception and generating a log message that's creating the NPE.  At least you'll have a bit more clarity in the log message on what's failing?

**Comment by iXo** [comment]
Hum... I tried to create a test unit just for the NPE, to be able to reproduce it I have to make the initCOM method from WmiUtil to always throw an exception. As the test environment doesn't use any mockup test framework, this will be quite difficult without a quite big modification of the code I want to test. And because the WmiUtil class is well protected I can't extend it.
Maybe I am wrong, sorry I can't really be of any help.

**Comment by iXo** [comment]
(sorry for the right shift of the case entries for the switch)

**Comment by dbwiddis** [comment]
Thanks for the submission... I made one comment.  And no need to build a testcase for what that.  I'm surprised our static analysis programs didn't catch that... maybe because of the exception.

I'm curious if building/testing this on your own project you can get more information with that more verbose log message?

**Comment by dbwiddis** [comment]
A thought for troubleshooting.  Try using JNA's [WbemCliUtil](https://github.com/java-native-access/jna/blob/683fd9b543321716854186f8252ee70cd255af1b/contrib/platform/src/com/sun/jna/platform/win32/COM/WbemcliUtil.java) class (originally part of WMIUtil) and explicitly initializing/uninitializing COM for your queries yourself.  This will help narrow down the initialization issue to whether it's something funky OSHI is doing storing its connection or other OSHI code not related to the underlying COM issues.
