### ISSUE TITLE
Check if monitor is on, also turn it on and off

### ISSUE THREAD

**Issue by stefan-reich** [oshi/oshi#727]
On Linux, it's easy:

[Turn on](http://tinybrain.de/1020237)

```
svoid linux_turnDisplayOn() {
  backtick([[xset dpms force on]]);
}
```

[Turn off](http://tinybrain.de/1020236)

```
svoid linux_turnDisplayOff() {
  backtick([[xset dpms force off]]);
}
```

[Check status](http://tinybrain.de/1020241)

```
sbool linux_isDisplayOn() {
  ret cic(backtick([[xset -q]]), "monitor is on");
}
```

No idea about other OSes.

**Comment by dbwiddis** [comment]
Reconsidering.... looking at the existing code for display detection (returning EDIDs) if it's possible to just add on a "on/off/unknown" status to that result that we're already collecting...

For macOS we find the `IODisplayConnect` information in the registry and read the `IODisplayEDID` value. There's also an `IODisplayPowerManagement` dictionary with a `DevicePowerState` value.

For Linux/Unix we parse `xrandr --verbose` for the EDID (which doesn't always work) and I suppose it wouldn't be such trouble to tack on `xset -q` as a second command.

Still... the fact that this information just isn't available on Windows leaves me less than enthusiastic about it.

**Comment by dbwiddis** [comment]
After considering this and testing a few options, I think this is just not worth doing!  Sorry!

**Comment by stefan-reich** [comment]
Yo, I understand. Thanks
