### ISSUE TITLE
OS Version for Windows Server 2019

### ISSUE THREAD

**Issue by indhupriya** [oshi/oshi#733]
OSHI wrongly displays OS information as **Windows Server 2016** for **Windows Server 2019** since the OS Version is [10.0](https://docs.microsoft.com/en-us/windows/desktop/sysinfo/operating-system-version) for both.
Are there any plans to update the code by taking build numbers ( >17762 for Server 2019) into consideration? (Not sure if this has already been discussed here).

**Comment by dbwiddis** [comment]
There are plans to update the code now!   When will you be submitting the PR? :)

**Comment by dbwiddis** [comment]
Thanks for the fix! Updating snapshot now, will put out 3.12.2 this weekend when I fix some other things.

**Comment by indhupriya** [comment]
Thank you.
