### ISSUE TITLE
Problem opening SWT.NONE styled web browser since 3.7.0

### ISSUE THREAD

**Issue by jimbostimilon** [oshi/oshi#736]
This one might take some explaining...

My 32bit Java app uses a SWT web browser which is configured to use the SWT.NONE style, meaning that on Windows, it uses the default web browser (which is IE, even on Windows 10). This worked fine with OSHI v3.6.2, but using any newer version, my app attempts to open IE, but it doesn't appear to complete. I've tested on WinXP, Win7 and Win10 and they all do the same. My app's code hasn't changed at all other than changing the SWT styles for testing.

It's worth noting that if I change it to use SWT.MOZILLA, the moz based web browser loads without a problem. Likewise, rolling back to v3.6.2 fixes the problem and IE successfully loads.

I don't see any logs or traces to provide any hints as to exactly what's going wrong. If I run my app in debug, to stops at an SWT exception for "Invalid thread access" which is the closest I can get, but again, no stacktrace or logs.

Using git bisect, I was able to identify that the first commit which causes the problem is:
```
commit 206e2df409626321524caced00decc84ac093a1d
Author: dbwiddis Date:   Sun Jul 22 14:18:24 2018 -1000 
Cache WMI connections(#564)
* Handle timeouts with exception
* Cache WMI connections and namespaces
:100644 100644 d86cfe08a6101bd979fa7d25b3635c29383a7586 3fc405f6c2650e3abe801756 b6167b3fc99106dd M CHANGELOG.md
:040000 040000 b5b550341a18a419c37fb1ecc9aaff06ed0975d9 ed3d8c0bd217f0e3f9c456d1 7164cf8b6f8fcb39 M oshi-core
```

I don't really understand how those changes to OSHI could be affecting SWT in this way, but something that was changed in v3.7.0 is definitely the cause.

**Comment by dbwiddis** [comment]
Odd.  I would have suspected some of that WMI Cache stuff, but I've since removed most of it, so there must be something else creating the issue.  The one thing from that commit that's still around in some form is tracking whether COM was initialized... briefly looking at SWT it does use WBEM code (the same underlying interface that WMI uses).  There are some COM settings that OSHI uses when it initializes:
```
    Ole32.INSTANCE.CoInitializeEx(null, Ole32.COINIT_MULTITHREADED);
    Ole32.INSTANCE.CoInitializeSecurity(null, -1, null, null, Ole32.RPC_C_AUTHN_LEVEL_DEFAULT,
                    Ole32.RPC_C_IMP_LEVEL_IMPERSONATE, null, Ole32.EOAC_NONE, null);
```
I'd dig into whether the SWT code is doing something similar.

**Comment by jimbostimilon** [comment]
We are using an older version of SWT (4.7), but we can't move to a newer version at this stage for compatibility reasons but I might be able to test with a newer version on Win10 at least. I'll also see if I can find anything in the SWT code.

**Comment by jimbostimilon** [comment]
> Try editing OSHI's initialization to use Ole32.COINIT_APARTMENTTHREADED.

That solved it immediately. Is it possible to make that change in the OSHI code or do I need to work something else out on my end?

**Comment by dbwiddis** [comment]
Reading the [Remarks here](https://docs.microsoft.com/en-us/windows/desktop/api/combaseapi/nf-combaseapi-coinitializeex), I'm pretty sure that we don't properly handle all the possibilities and return codes in OSHI.

> CoInitializeEx must be called at least once, and is usually called only once, for each thread that uses the COM library. Multiple calls to CoInitializeEx by the same thread are allowed as long as they pass the same concurrency flag, but subsequent valid calls return S_FALSE. To close the COM library gracefully on a thread, each successful call to CoInitialize or CoInitializeEx, including any call that returns S_FALSE, must be balanced by a corresponding call to CoUninitialize.

vs.

```
            // COM was already initialized
            case COMUtils.S_FALSE:
            case WinError.RPC_E_CHANGED_MODE:
                break;
```
This is definitely a bug in OSHI and I'll fix it.

**Comment by dbwiddis** [comment]
OK, I *think* I've fixed the problem just by moving S_FALSE (still "success") up to the branch that sets the COM initialized flag.  My branch / snapshot should work for you, even with the multithreaded initialization -- since I now properly uninitialize it.

**Comment by jimbostimilon** [comment]
That change didn't work for me with multithreaded initialization. No change at all in the behaviour.

Still works fine when changed to apartment.

**Comment by dbwiddis** [comment]
Unfortunately changing to apartment without properly fixing the error handling on changed mode will cause the same issue in reverse.    I need to sort out the correct error handling here... the Microsoft Docs seem to imply `RPC_E_CHANGED_MODE` only occurs when initializing Apartment when it's already multithreaded but aren't clear what happens in the opposite case.  This blog implies the opposite (and is the exact behavior I'm trying to replicate here) but if that's not working, I'm really confused.   I may need to head over to StackOverflow...

**Comment by dbwiddis** [comment]
OK, I think I've got it working. Slightly more optimistic than before.

**Comment by dbwiddis** [comment]
OK, very optimistic now. :)

OSHI was never uninitializing COM, so if it was the first one on the thread, it was forcing the thread to stay in multithreaded mode.  This was preventing the SWT code from properly working in apartment threaded mode. 

If OSHI wasn't the first one, then it was using the other COM initialization without tracking its own, which meant if the external program shut down COM, OSHI would fail.

I've changed it to init/uninit on every query, trying both threading models and using whichever one matches the external (if required).

If this doesn't fix it, I'll officially give up!

**Comment by dbwiddis** [comment]
>  libraries should not be initializing COM because of scenarios like these.

Fair comment and they definitely should not be leaving it initialized (like we did/do until I merge this fix).

However:
- Some data in OSHI is only (reliably) available in WMI
- The alternative to the COM code is to run the `wmic` command line (which probably does the initialization itself under the hood, but does so in its own thread)
- We could also work around this by creating a new Thread to run the WMI queries, but that's probably excessive.
- After finally figuring out what's going on, I'm comfortable that the way we currently handle it is sufficient.  If it hasn't been initialized externally, we initialize it.  If it has been, nothing happens other than incrementing a counter that we now properly decrement.

**Comment by jimbostimilon** [comment]
I've tested your fix on WinXP, Win7 and Win10 and they're all working properly now. Thanks for all your help with this!

**Comment by dbwiddis** [comment]
Thank *you* for your patience in testing and reporting!
