### ISSUE TITLE
Handling custom OSHI driver classes like WMI

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#738]
Part of the solution to #716 (custom log messages) is to allow users to extend/override some/all of OSHI's "driver" classes (for lack of a better word.)  @retomerz submitted a PR which addressed this in #728 but relied on creating an instance of the `WmiQueryHandler` in the `SystemInfo` class and passing it to other classes as an argument in the constructor.

I didn't think the `SystemInfo` class was the right location for this because it was class-independent (while the W in WMI means Windows) and because passing this object as an argument isn't a scalable solution if we expand to similar extensible classes for other Windows code (e.g., PDH) and other OS drivers (mac IOKit, Solaris Kstat).

I merged a portion of the PR with the `WmiQueryHandler` instantiated class, and have temporarily made it a Singleton pending a decision on the best place to put the object instantiation (and more importantly, the ability for a user to write a custom implementation).  I'd like @YoshiEnVerde in particular to comment on this as the "driver" term is from #365, and I think @cilki had some good future design ideas as well.  And anyone with an opinion is welcome to chime in!

Some options I think might work, happy to hear pros/cons:
- Leave it as a Singleton but complement the static `getInstance()` method with a static `setInstance()` method which a user could use to instantiate their own (sub)class and have it returned by later calls to `getInstance()`.
- Put the static methods getting and setting the instance in the `WmiUtil` class, to avoid any confusion with the Singleton pattern.
- Create a new Driver class and "store" the class there.  This would require additional decisions:
  - Do we instantiate the Driver class in `SystemInfo` and pass it to all the other objects as an argument?  If so, what is its interface (recall that Windows code will need a `getWmiDriver()` equivalent while macOS code will need a `getIOKitDriver()` equivalent.  Could the appropriate drivers be stored in platform-specific `EnumMaps` or similar?
  - Do we have static Driver classes for each OS with getters and setters for the appropriate instance?  e.g., the `WindowsDriver` class could have the WMI and PDH drivers; the `MacDriver` class could have the `IOKit` driver, and so on.
- Does someone have an even better idea that I haven't thought of?

**Comment by cilki** [comment]
OK I have some questions before I formalize my plan for the drivers.
- Is `WmiQueryHandler` thread safe? In the current setup it should be because multiple threads may try to query WMI at the same time. I think we should avoid drivers that need to be thread safe in the future (each API object gets its own driver). This would also prevent initializing and uninitializing COM on each query from #736 (more on that later).
- Should the drivers be visible to the user? I'd prefer to keep them private if possible. I didn't look closely at #716, but it seems like there must be a better way than subclassing the driver. I suppose adding a configuration property containing the classname and instantiating with reflection would be a viable way for a user to specify a custom driver, though.

**Comment by dbwiddis** [comment]
> Is WmiQueryHandler thread safe? 

Mostly: yes for practical purposes. We can synchronize one method for certainty.
- It's possible competing threads could set a different default timeout and a race condition could result in one thread overwriting the other's default. This is unlikely to ever happen (the default is intended to be set once early on) and users have the ability to directly specify timeouts regardless of the default.  We could synchronize the setters on this variable to make this safe.
- There are some Sets caching failures and successes.  There are no negative effects for being out of sync here but we could use a Synchronized Set (or just get rid of those variables as they're microoptimizations or convenience to reduce logspam).
- There's a boolean tracking whether security was initialized. It's harmless to initialize it twice.
- There's an int tracking the type of threading for COM initialization. In the rare case where (a) COM is externally initialized, (b) the external initialization threading is different than OSHIs, and (c) both threads simultaneously try the non-working initialization and try to switch it, one or both threads could still fail and/or COM would be uninitialized by one thread while another thread was holding the only initialization. This would cause a one time exception but recover the next time around.  This could be avoided by synchronizing the `queryWmi()` method on the variable enforcing the type of threading, meaning no two threads could simultaneously query WMI.

> Should the drivers be visible to the user?

I don't see why not.  

> I didn't look closely at #716, but it seems like there must be a better way than subclassing the driver.

The stated goal was to override exception handling/logging with custom behavior.  It might be useful to centralize all of OSHI's exception handling and logging to a class/classes that users can more easily override to implement custom behavior.

**Comment by cilki** [comment]
My strategy is closest to your third point. There would be two kinds of drivers:
- Generic Drivers like `FileDriver`, `CmdDriver`, or `WmiDriver`
- Specific Drivers like `CpuDriverWindows` which uses a combination of generic drivers

All of these driver classes would be stateful and non-static. This means that an initialized `FileDriver` knows exactly what file to read and how to parse it. An initialized `CpuDriver` knows which CPU it's responsible for.

If this model doesn't suit WMI, then `WmiQueryHandler` could remain a static util class and each `WmiDriver` would simply delegate queries to it.

There needs to be a mechanism that allows a driver to be "opened" or initialized when needed, stored while in use, and then "closed" when finished. This would be done in what I've always called the "cache layer" which is confusing with value caching, so I'll start calling it the "driver cache". Having stateful drivers means that OSHI needs to know when a user is done querying an API object. I haven't figured this out yet, but one option is offer two versions of each API object:
- One that that implements `AutoClosable` so it can be used in a try-with-resources. The drivers will be left open until the object is closed.
- One that opens and closes a new driver on each query

The benefit of this model is that repeated polling would have almost no initialization cost on each query. Usually I love static util classes, but I think in this case, making the drivers non-static and stateful (and letting the driver cache layer manage their storage) is better design.

**Comment by retomerz** [comment]
Yes the driver classes should be non-static  (also see my comment here about the static trouble: https://github.com/oshi/oshi/issues/716).

I also agree that the "query" logic (which could be in the named "driver" classes)
should be separate from the data beans.

At the moment this things are mixed up. And even worse, the method names do not indicate if the method is a "heavy" or "cheap" call.
A method with "get" prefix does suggest that this method is "cheap".
That is what the most programmers expect when they see a getter.
For methods which makes internally JNI calls, or do other stuff like IO (reading from the disk
is something of the slowest you can do), creating tons of temporary internal objects etc,
such method should have a prefix which also reflects this. Like buildX, makeX, createX, collectX, retrieveX or readX for example.
To reduce the wording in the public API, if think the "query" or "read" prefix is a good choice.
This automatically indicates that such a method should not be used like this:
```
if (driver.readValue() != null) {
    handle(driver.readValue()); // call readValue two times
}
```
(Just as an example, returning an Optional<V> is another topic).
The "get" prefix should be only used if it is really a simple getter, more or less (a lazy getter is okay).

**Comment by dbwiddis** [comment]
> To reduce the wording in the public API, if think the "query" or "read" prefix is a good choice.
> The "get" prefix should be only used if it is really a simple getter, more or less (a lazy getter is okay).

I like how the PDH counter API does it.  After adding a counter, the options are:
- CollectQueryData (does the actual update of the counters)
- GetCounterValue (returns the values and timestamp that were already fetched)

I had already been musing on something like that as a structure:
- Hold onto data in a serializable POJO (I'd say bean but may want to limit the setter permissions) with public getters
- Update the POJO with specific updateFoo() or calculateFoo() methods (internally) selectively called by an `update(Properties p)` API method.

Only reason I haven't gotten started on that is that I'm still trying to figure out the best design:
- Keep existing API and underlying class specific objects (implementing the API interface) but ensure these classes are serializable and only contain the needed fields
  - probably extend a separate Updatable interface with methods associated with the properties
- Create an intermediate data class / bean to hold just the serializable bits, and extend that (cross-platform) data class with platform-specific code to update it.  (What we generally do with the existing abstract classes, but I'd like to revisit that model, and in my example the bean wouldn't implement the interface like the abstract classes do.)
  - So you'd have something like a `GlobalMemoryUpdater` class extends `GlobalMemoryBean` implements `GlobalMemory`, `SelectiveUpdater`.   That updater would have minimal bits in the update methods which would reach out to the appropriate data fetching classes.
  - Only difference between this and the above option is the Bean is separate.  And we'd probably want a "getBean" method that would return it (for parsing into JSON, XML, JMX, whatever).

**Comment by dbwiddis** [comment]
> All of these driver classes would be stateful and non-static. This means that an initialized FileDriver knows exactly what file to read and how to parse it. An initialized CpuDriver knows which CPU it's responsible for.
>
> If this model doesn't suit WMI, then WmiQueryHandler could remain a static util class and each WmiDriver would simply delegate queries to it.

@cilki can you take a peek at the `PerfCounterQuery` (and `PerfCounterWildcardQuery`) classes I just merged in #763 and see if they fit this model?  Basically:
- The Query classes are stateful. They are instantiated in their respective classes and know which PDH counters or WMI tables they are responsible for querying.  But the actual work of the queries is still done by static/singleton objects.

It's not the final solution yet but it's a huge step forward from how it was.

**Comment by dbwiddis** [comment]
Just played around with a quasi-factory-ish-something.  This works... but is it good code?

Interface:
```
public interface Driver {
    Driver generate();

    void setInstanceClass(Class<? extends Driver> instanceClass);

    default void setInstanceClass() {
        setInstanceClass(DefaultDriver.class);
    }
}
```
Default:
```
public class DefaultDriver implements Driver {

    Class<? extends Driver> instanceClass = DefaultDriver.class;

    public DefaultDriver() {
        System.out.println("Instantiated a default driver.");
    }

    @Override
    public Driver generate() {
        try {
            return (Driver) instanceClass.getConstructor(new Class<?>[0]).newInstance(new Object[0]);
        } catch (InstantiationException | IllegalAccessException | IllegalArgumentException | InvocationTargetException
                | NoSuchMethodException | SecurityException e) {
            // That didn't work
            e.printStackTrace();
            return null;
        }
    }

    @Override
    public void setInstanceClass(Class<? extends Driver> instanceClass) {
        this.instanceClass = instanceClass;
    }
}
```
Custom (will be provided by user)
```
public class CustomDriver extends DefaultDriver implements Driver {

    public CustomDriver() {
        System.out.println("Instantiated a custom driver.");
    }

    @Override
    public void setInstanceClass() {
        instanceClass = CustomDriver.class;
    }
}
```
Test (user provides their custom class):
```
public class Test {

    public static void main(String[] args) {
        Driver d = new DefaultDriver();
        d.setInstanceClass(CustomDriver.class);

        Driver custom = d.generate();
        System.out.println("Class type of custom is " + custom.getClass());

    }
}
```
Test output:
```
Instantiated a default driver.
Instantiated a default driver.
Instantiated a custom driver.
Class type of custom is class oshi.CustomDriver
```

**Comment by dbwiddis** [comment]
Implemented the pattern (using reflection for `getConstructor()` and `createInstance()`) for the `WmiQueryHandler` in #767.   The query handler is now completely non-static (except for some constants and the logger etc.) and created in a non-static manner for use when needed (and released when done).

This is appropriate for the WMI queries which no longer need to maintain any state between queries.

The PDH counter handler does need to remain a singleton, however, as we need one central location to track the open queries and handles.  I did make that thread safe in #763 and #766.

**Comment by cilki** [comment]
> @cilki can you take a peek at the PerfCounterQuery (and PerfCounterWildcardQuery) classes I just merged in #763 and see if they fit this model?

One superficial note is that PDH and WMI should probably be separate drivers and then the fallback logic is handled by the _Strategy_ as @YoshiEnVerde invented. That way more complex fallback scenarios can be created cleanly.

`PerfCounterQuery` is definitely a step in the right direction. It knows what properties it needs from the system and gets them with a parameterless query method (`queryValues`). However, I still think there needs to be a concept of open vs closed because of [this shutdown hook](https://github.com/dbwiddis/oshi/blob/45667130283c7eaa053c1a932f398ff39ec99677/oshi-core/src/main/java/oshi/data/windows/PerfCounterQuery.java#L98). It's a temporary solution, and I think it could cause some unsolvable problems in the future. The user will know when they are done polling a group of attributes. Why not let them decide whether to keep the connection open and, if so, when to close it?

Overall, I like the changes, but the shutdown hook gets a -1 from me.

**Comment by dbwiddis** [comment]
> open vs closed because of this shutdown hook. 

The user has the ability to release handles.  There's not so much a connection for PDH as just a handle.  The shutdown hook merely enforces the "release everything when we're done" paradigm -- calling a method available to users as well. 

We could release handles after every query but then we'd just re-open them again, and the API is designed to keep the handles open.

Other than a shutdown hook, how would you ensure we don't leak handles if we run OSHI and let it close, repeatedly?

WMI is different, there's a connection, but we open and close that with each query now.

**Comment by dbwiddis** [comment]
> It should be the user's responsibility. Not directly by accessing the driver of course, but by signaling the API that they are done with the object.

The user does have the ability to release the counters.  And in this case the user is our own code... the hook is just there as a backup if the user doesn't.

But I'm realizing that the shutdown hook waits until the jvm terminates to release, vs. if we put the code in a finalize then they would be released on GC.  (Or we could do both.)

Or we can release immediately after the query since it takes so little time.

**Comment by cilki** [comment]
I think just a finalizer would be the right choice here. I can PR that change if you want.

**Comment by dbwiddis** [comment]
Haha.  I was already getting started on only maintaining handles for the length of the query.

**Comment by dbwiddis** [comment]
But (going in circles) I'm back to where I started.
- The user has the ability to remove handles
- I can alter the code of the PerfCounterQuery and PerfCounterWildcardQuery to release those handles (at a miniscule performance cost) so we never have handles just sitting around
- But that relies on the user to keep track of, and release handles (which is what the query handler is doing!)
- And if the user doesn't do that, the user can create a handle leak
- So keeping track of the handles internally keeps the user from forgetting them (the whole "write code well once and have everyone use it" paradigm)
- I can leave all the `PerfCounterQueryHandler` code just like it is (it's just a bookkeeping service for counter handles), and alter code in the `PerfCounterQuery` and `PerfCounterWildcardQuery` to intentionally release handles as much as possible (empty the shelves).
- But just in case the user messes up, what's so wrong with using the shutdown hook as a last-ditch effort to return handles to Windows on a clean exit?

**Comment by dbwiddis** [comment]
Ah, I see I have 3 different shutdown hooks.  (And they're all doing the same thing!)

I'm going to leave the one in the `PerfCounterQueryHandler` just as a backup to the user, but otherwise plan on the user releasing counters after use.

**Comment by dbwiddis** [comment]
#769 handles all the query closing. As you can see from the removed code, some other benefits to the simpler approach.
