### ISSUE TITLE
Detecting the graphics specs.

### ISSUE THREAD

**Issue by ravimohan1991** [oshi/oshi#753]
I was wondering if the routines generating the information related to Graphic card can be written in these libraries.

**Comment by dbwiddis** [comment]
We could probably do something similar to the Sound Card feature, for the Video Card.  Feel free to contribute a PR.

**Comment by cilki** [comment]
Duplicate of #400.

**Comment by dbwiddis** [comment]
Good point. I'll close this and we can continue any discussion on #400.
