### ISSUE TITLE
Test if running under sudo

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#772]
Some OSHI functionality is different based on elevated permissions.  An `isSudo()` test would be nice to know if OSHI's `ExecutingCommand("sudo *")` code will work.

Windows: [see here](https://www.codeproject.com/Questions/544981/IsplusProcessplusRunningplusasplusAdministrator)

MacOS has $EUID == 0.

Linux and Solaris have an environment variable `SUDO_COMMAND` (among others) set.  I'll have to run some tests on FreeBSD to see if that applies there too.

**Comment by dbwiddis** [comment]
Thanks for the test!  Seems like the SUDO_COMMAND (or SUDO_anything) is still a good flag?

**Comment by henryx** [comment]
I think is needed a double control:
```java
if (System.getenv("USER").equals("root")) {
    if (System.getenv("SUDO_USER") != null) {
        System.out.println("Is launched as root");
    } else {
        System.out.println("Is root!");
    }
} else {
    System.out.println("Is launched as " + System.getenv("USER"));
}
```

**Comment by dbwiddis** [comment]
So for all the *nixes all we have to do is test for nonempty result of `System.getenv("SUDO_USER")`.  This doesn't work on Windows, but we can attempt to access Admin-only files like `%windir%\system32\config\systemprofile` which will give IOException without priviliges.
