### ISSUE TITLE
Replace toArray(new T[size]) with toArray(new T[0])

### ISSUE THREAD

**Issue by hc-codersatlas** [oshi/oshi#780]
Hi, noticed many occurrences of toArray that could be made faster with a find and replace.

Performance: replace toArray(new T[size]) with toArray(new T[0])

https://shipilev.net/blog/2016/arrays-wisdom-ancients/#_conclusion (also contains benchmarks).

Could provide some simple performance improvements thanks!

**Comment by dbwiddis** [comment]
I did a quick search, and only saw the ones in the `SoundCard` classes.

`FreeBsdSoundCard.getSoundCards().toArray(new SoundCard[0]);`

Feel free to submit a PR to fix them, or I can toss this one onto the first-timers-only tag.

**Comment by hc-codersatlas** [comment]
Sure, PR sent.

**Comment by dbwiddis** [comment]
Oh, wait... I was looking at the other direction, from 0 to size.  I'll have to re-read that link and see how I can suppress Codacy's loud complaints about your changes. :)
