### ISSUE TITLE
OSHI does not properly handle Processor Groups

### ISSUE THREAD

**Issue by akaranta** [oshi/oshi#785]
I wrote a simple clojure program, using oshi, to analyze the hardware environment my program was running on. The issue I was investigating was that another clojure program seemed to be utilizing cores only on a single cpu even though there are two physical cpus available on the system.

This is what oshi detected for me

os  #<WindowsOperatingSystem Microsoft Windows Server 2016 build 14393>
processor  #<WindowsCentralProcessor Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz>
physical cpus  1
physical cpu cores  20
logical cpus  40

The code for printing these being
(defn- print-hw-info []
  (let [sys  (SystemInfo.)
        hw   (.getHardware sys)
        proc (.getProcessor hw)
        os   (.getOperatingSystem sys)]
    (println "system info from oshi library")
    (println "os " os)
    (println "processor " proc)
    (println "physical cpus " (.getPhysicalPackageCount proc))
    (println "physical cpu cores " (.getPhysicalProcessorCount proc))
    (println "logical cpus " (.getLogicalProcessorCount proc))))

Runtime.availableProcessors() also returns 40

However, in task manager's Performance tab it says Sockets 2, Cores 40, Logical processors 80. Thus, it appears oshi/the jvm is not seeing them all, only the ones on a single processor.

This is not a virtual machine, so I would assume both the processors being available.

Thus, it appears oshi is able to detect only the other processor.

I am still investigating why the java process only utilizes a singe cpu, but that's a separate matter, albeit the root cause may very well be related.

oshi 3.6.0
clojure version  1.6.0
   java.version : 1.8.0_202
    java.vendor : Oracle Corporation
java.vm.version : 25.202-b08

**Comment by dbwiddis** [comment]
Do you know if the two sockets use NUMA?

**Comment by dbwiddis** [comment]
Another thing to investigate is if the Java processes have any affinity set limiting what they can see.

**Comment by akaranta** [comment]
How can I check if the sockets use NUMA?

I checked the affinity (Task manager -> details) and there's a dropdown menu for selecting a processor group. Only the cores in one processor are selected. If I select the ones in the other and press ok, the ones in the previous group get unselected. 
I don't quite understand why this happens. 
From the documentation I do understand why there's two processor groups (https://docs.microsoft.com/en-us/windows/desktop/procthread/processor-groups) as the total number of logical processors is > 64. However, I don't understand why it appears that a single process can only be running on one or the other, not both.

**Comment by dbwiddis** [comment]
The NUMA question was just to see if I missed something in the package/core counting.  OSHI uses the [GetLogicalProcessorInformation](https://docs.microsoft.com/en-us/windows/desktop/api/sysinfoapi/nf-sysinfoapi-getlogicalprocessorinformation) function to get information about the core (physical processor) and package (socket) counts. There's information about NUMA nodes that we ignore, and if that had been the problem I would have headed down that road.

However, you've pointed out that processor groups are the culprit, and in fact when OSHI calls that function it only gets one group.  From the docs:

> On systems with more than 64 logical processors, the GetLogicalProcessorInformation function retrieves logical processor information about processors in the processor group to which the calling thread is currently assigned. Use the GetLogicalProcessorInformationEx function to retrieve information about processors in all processor groups on the system.

I originally didn't include that capability because it required both Win7 and 64 bit OS (and more importantly I didn't know anyone with system with over 64 processors to test the code).  I'll mark this as a bug and see if I can do some better counting and I hope you'll be able to test the changes.

With regard to why the process can only run on one group, the link you cited has this to say:

> By default, an application is constrained to a single group, which should provide ample processing capability for the typical application. The operating system initially assigns each process to a single group in a round-robin manner across the groups in the system. A process begins its execution assigned to one group. The first thread of a process initially runs in the group to which the process is assigned. Each newly created thread is assigned to the same group as the thread that created it.
> 
> An application that requires the use of multiple groups so that it can run on more than 64 processors must explicitly determine where to run its threads and is responsible for setting the threads' processor affinities to the desired groups.

So the way I read it, all processes by default only run on one processor group and it is the responsibility of the process itself (such as Java) to explicitly assign its threads to processors in another group.

**Comment by dbwiddis** [comment]
Are the logical processor numbers sequential in the groups or 64-based?  In other words are the bit masks bits 0 to 79 or 0 to 39 and 64 to 103?

**Comment by dbwiddis** [comment]
Answering my own question it looks like the bitmasks always go 0 to 63 and there's a separate field for the processor group.  Which creates an interesting challenge trying to map to arrays of processor information (like tick count) that are indexed by processor number.

**Comment by dbwiddis** [comment]
Thanks for your offer to test.  I've got the skeleton of the code written but it's failing on my (32 bit Win7) VM, possibly with the bitness. About to test on 64 bit Win10 and hoping for better results...

BTW, Microsoft has made this a requirement of the software to fix and [points users to Java as the responsible party](https://social.technet.microsoft.com/Forums/windows/en-US/9589087d-9036-4b39-bfce-059aed7b2abf/windows-allow-only-a-maximum-of-36-logical-processors-per-process-out-of-total-of-72-?forum=winserver8gen) but it looks like Java explicitly [decided not to support](https://bugs.openjdk.java.net/browse/JDK-6942632) multiple processor groups.  

So from "within Java" (or Clojure) I think you're stuck.  As a hardware info library, OSHI should at least try to count the real hardware, though...

**Comment by akaranta** [comment]
Thanks a lot for these links! Really useful, it appears that what I was after can't be done, at least not with a reasonable cost/benefit ratio. At least I can stop banging my head against the wall as I know what's going on.

**Comment by dbwiddis** [comment]
Maybe you can help me bang my head against the wall working on the fix. :)

Would you be able to test from [my branch](https://github.com/dbwiddis/oshi/tree/proc-groups) or do I need to push to snapshot for your testing?

**Comment by dbwiddis** [comment]
Code on my branch (linked above) should properly count processors.  Can you test it?   (SystemInfoTest can give totals but it'd be really helpful if you could run the Json.java program in the `oshi-demo` artifact so I can see all the fields.)  I'll get that on the snapshot later tonight.

Still need to figure out how to handle the groups and processor numbers in the per-processor arrays.

**Comment by akaranta** [comment]
AFAIK getting leiningen to use arbitrary jars is somewhat difficult, so what I did I just opened oshi-core\target\oshi-core-4.0.0-SNAPSHOT.jar and my own uberjar and then just copied the newly compiled classes over the old ones. What I got when running my jar was this:

C:\Temp>"C:\Program Files\Java\jdk1.8.0_202\bin\java.exe" -jar loadtest-0.1.0-SNAPSHOT-standalone.jar
System information
available processors (accoring to Runtime)  40
clojure version  1.6.0
Exception in thread "main" java.lang.NoSuchMethodError: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;)Lcom/sun/jna/Library;
        at oshi.jna.platform.windows.Kernel32.<clinit>(Kernel32.java:36)
        at oshi.jna.platform.windows.VersionHelpers.IsWindowsVersionOrGreater(VersionHelpers.java:63)
        at oshi.jna.platform.windows.VersionHelpers.IsWindowsVistaOrGreater(VersionHelpers.java:111)
        at oshi.hardware.platform.windows.WindowsCentralProcessor.<clinit>(WindowsCentralProcessor.java:70)
        at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getProcessor(WindowsHardwareAbstractionLayer.java:70)
        at loadtest.core$print_hw_info.invoke(core.clj:48)
        at loadtest.core$_main.doInvoke(core.clj:22)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at loadtest.core.main(Unknown Source)
		
Not sure if I merged the jars improperly and this is the result? Although it appears to me you are invoking some Java internal classes that are not part of the supported API and maybe they are different in the Java version I am using?

mvn package was not able to finish the build due to

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  26.358 s
[INFO] Finished at: 2019-01-29T21:32:03+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (javadoc-jar) on project oshi-core-shaded: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - D:\work\oshi\oshi-core\src\main\java\oshi\hardware\common\AbstractCentralProcessor.java:101: warning: no @return
[ERROR]     protected abstract LogicalProcessor[] initProcessorCounts();
[ERROR]                                           ^

oshi-demo does not seem to have a jar-file:

$ dir oshi-demo\target
 Volume in drive D is Data
 Volume Serial Number is 526A-A863

 Directory of D:\work\oshi\oshi-demo\target

01/29/2019  09:31 PM    <DIR>          .
01/29/2019  09:31 PM    <DIR>          ..
01/29/2019  09:31 PM    <DIR>          classes
01/29/2019  09:31 PM    <DIR>          generated-sources
               0 File(s)              0 bytes
               4 Dir(s)  810,457,387,008 bytes free
			   
Trying to run Json results in an error:

antti@MSI D:\work\oshi
$ java -cp oshi-demo\target\classes oshi.demo.Json
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonProcessingException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonProcessingException

        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more
		
Am I getting something wrong?

**Comment by akaranta** [comment]
Got your latest changes on your branch. Now mvn package goes fine and there is a jar produced for oshi-demo. It does not run, though:

$ java -cp oshi-demo\target\oshi-demo-4.0.0-SNAPSHOT.jar oshi.demo.Json
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonProcessingException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonProcessingException

        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

Am I missing some dependency?

**Comment by dbwiddis** [comment]
The `oshi-core` artifact depends on JNA, which includes two jars, one for jna and one for jna-platform.

The `oshi-demo` artifact depends on `oshi-core` and also depends on Jackson... see the `pom.xml` file.  Maven may need you to build oshi-core first, and then oshi-demo.   Running `mvn package` at the top level parent project should handle all these dependencies.

I believe either the shaded jar or `oshi-dist` zip files should contain all the files you need.

**Comment by dbwiddis** [comment]
Hmm, the dist file doesn't include the demo... seems I need to fix that.

You should be able to find the demo jar file here:  https://oss.sonatype.org/content/repositories/snapshots/com/github/oshi/

**Comment by dbwiddis** [comment]
As an alternative to the demo, if you can just iterate over the array of LogicalProcessors and output the groups/processor #s/package #s that would work!

**Comment by dbwiddis** [comment]
I think I'll work on a more complete test case tonight that you'll be able to run straight out of oshi-core.

**Comment by dbwiddis** [comment]
The same test code is now on the master branch and the latest 4.0.0-SNAPSHOT.

**Comment by akaranta** [comment]
Please find attached the result of running the ProcInfo class using the latest snapshot. Both packages seem to be detected. 

My own Clojure program also reports the correct information with the latest snapshot.

[procinfo.txt](https://github.com/oshi/oshi/files/2823175/procinfo.txt)

**Comment by dbwiddis** [comment]
Thanks, @akaranta!  Extremely valuable test!   Everything looks as expected except one item: I would have expected group 1 to have 40 of 64 and the same bitmask as group 0.   I'll see if I can figure out why that result is different.

```
Details for 2   group(s):
--
Group 0 had 40 active of 64 max   processors with bitmask 1111111111111111111111111111111111111111.
Group 1 had 0 active of 0 max processors   with bitmask 10100001000000.
```

**Comment by dbwiddis** [comment]
Hey @akaranta I"d appreciate one more test of snapshot or the master branch here.  I only need the top 5 lines... if all goes well Group 1 will match group 0.

**Comment by akaranta** [comment]
Just got the latest snapshot. Here's the first five lines:

Info for 1 group structure (should only be 1):
Relationship should be 4, it is 4
Details for 2 group(s):
Group 0 had 40 active of 64 max processors with bitmask 1111111111111111111111111111111111111111.
Group 1 had 40 active of 64 max processors with bitmask 1111111111111111111111111111111111111111.

I have the whole output if you need anything else from there.

**Comment by dbwiddis** [comment]
Nope! That's perfect and resolves the test! (The rest of the output should be identical to before, I would hope!)

Thanks for your assistance... closing this as fixed.

**Comment by dbwiddis** [comment]
At the risk of you never coming back, @akaranta can I ask you to check out the Current Frequency array for your system?   I'm poring over the docs for the [CallNtPowerInformation function](https://docs.microsoft.com/en-us/windows/desktop/api/powerbase/nf-powerbase-callntpowerinformation) which doesn't seem to indicate whether it fetches from processor groups.  

If what I suspect is true, you'll get the first half of an 80-element array filled with processor frequencies and the other half filled with undefined data.   Not much I can do to fix that with the native but I'd at least like to note that in the Javadocs that the frequencies are for the current Processor Group.  I actually think it's the same value for the whole system, though, and perhaps I should just copy the first half to the second half!

**Comment by akaranta** [comment]
I'll be happy to help if you can elaborate a little on what you want me to check. Where is this information available?

**Comment by dbwiddis** [comment]
Printing this out should do the trick:
`Arrays.toString(new SystemInfo().getHardware().getProcessor().getCurrentFreq());` 

Desired:  80 values approximating 2.00GHz.

Pessimistically expected:  40 values approximating 2.00GHz in the first half of the array and garbage in the second half.

for OSHI: Not sure I can do much to fix that pessimistic expectation, but I'd love to document it.

for JNA: I've submitted code relying on that pessimistic expectation (it will size an array for 40 processors and fill it) and need to know if I need to update my processor counting code to accommodate all 80 received.

**Comment by dbwiddis** [comment]
Hey @akaranta any chance you can provide the output of
`Arrays.toString(new SystemInfo().getHardware().getProcessor().getCurrentFreq());` ?

**Comment by akaranta** [comment]
Hi,

Sorry for the delay. I get to work on this side project when I find the time.
Here's the array you wanted:

current freq  [698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 698000000 -872420912000000 -872427120000000 -872426992000000 854155914000000 852301320000000 854155940000000 852301136000000 0 854155940000000 852301512000000 852301312000000 -872426808000000 0 -1000000 854161910000000 854163008000000 0 852301544000000 22000000 852301752000000 852301560000000 0 452984859000000 0 0 -235998738000000 0 0 0 0 -235998738000000 0 0 0 0 -235998738000000 0 0 0 0]

I see only numbers, hope you see a woman in red dress. :)

**Comment by dbwiddis** [comment]
Perfect! This is exactly what I expected to see -- 40 numbers populated by Windows, 40 numbers full of whatever random bits and bytes happened to be in the memory that was allocated.   I may alter OSHI's code to only return the 40 "sensible" numbers.

That's all I need from you for now!  I really do appreciate you allowing me to use your supercomputer as a testbed.
