### ISSUE TITLE
WmiUtil.getDateString() only returns the date but not the time anymore

### ISSUE THREAD

**Issue by Space2Man** [oshi/oshi#786]
Hi,

since #606 WmiUtil.getDateString() only returns the date but not the time anymore.
Was there a reason why this was done? Is there a way to return the full string again (maybe via different method)?

Thanks,

    Space

**Comment by dbwiddis** [comment]
> since #606 WmiUtil.getDateString() only returns the date but not the time anymore.

Actually the major change in WMI datetime parsing was #569.

> Was there a reason why this was done? 

To remove a dependency on the `threetenbp` project, which implemented Java 8's DateTime functions in Java 7.  Given that the only place we were using that conversion to a `LocalDate` was in fields like "Release Date" that only required the date and not the time, I decided we could just parse MMDDYYYY to YYYY-MM-DD and not have to mess with time zone conversions.

> Is there a way to return the full string again (maybe via different method)?

Now that OSHI 4 is on Java 8, we could bring back the old code without requiring an extra dependency.

**Comment by Space2Man** [comment]
Hm, I thought that CMIDate would return the full and you are just returning the date part ...

Would it be possible to add a WmiUtil.getDateTimeString() which returns the old full value? Or can I use something from JNA directly?

**Comment by dbwiddis** [comment]
You can just fetch the value as a string and parse it.  Use getValue and cast the result to String.

**Comment by dbwiddis** [comment]
The correct long term answer is to have a `WmiUtil.getDateTime()` that returns as a Java 8 `LocalTime` which was the previous behavior, and you can probably dig up that code from an earlier version.   In the meantime to fetch the full string you can use the `WmiResult`'s `getValue()` which returns an `Object`, cast it to `String`, and parse it however you want.

**Comment by Space2Man** [comment]
Thanks, we can live with getValue() ... that's exactly the string we were looking for :)
