### ISSUE TITLE
System.currentTimeMillis is used to measure time intervals, which is incorrect

### ISSUE THREAD

**Issue by stIncMale** [oshi/oshi#796]
`LinuxGlobalMemory.updateMeminfo` (and I would expect the same is true for some other classes) uses `System.currentTimeMillis` to measure time intervals since the `lastUpdate`. But `System.currentTimeMillis` has no monotonicity guarantees, which means it can go backwards essentially disabling the mechanism of updates in `LinuxGlobalMemory.updateMeminfo`.

`System.nanoTime` is created specifically for the purpose of measuring time intervals and should be used for this purpose. It is true that this method also does not guarantee monotonicity because it depends on what is provided by the OS (see [JDK-6458294 : nanoTime affected by system clock change on Linux (RH9) or in general lacks monotonicity](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6458294) for example), but a best effort is done to make it as monotonic as reasonably possible, while no such effort is done (and none is required) for `System.currentTimeMillis`.

**Comment by dbwiddis** [comment]
Thanks for this report.  While you're correct, we're in the process of removing all these as part of an API overhaul in support of #771.  We'll still have an occasional `currentTimeMillis` in the code when it's supposed to actually represent a timestamp, but we will be leaving update intervals to the user.

If you look at the current snapshot version of `LinuxGlobalMemory.updateMemInfo()` you'll see that it's been removed from there already (in #775).

One place we do need to keep the intervals, and change to `nanoTime`, is the `Util.sleep()` method.  Care to do that one?  If not, I'll create a new first-timers-only issue to tackle that.

**Comment by dbwiddis** [comment]
Can you submit a PR to fix the bug?    And we can remove that method since it's no longer used anywhere... whatever code used to use it has obviously been removed.

**Comment by stIncMale** [comment]
Sure, will submit a merge request. Probably tomorrow.

**Comment by dbwiddis** [comment]
Heh. Despite saying "not fully fix #796" in the PR, github's text parser ignored the "not".

As mentioned, I'm getting rid of those as part of the #771 API overhaul. Will keep this open to track.

**Comment by dbwiddis** [comment]
I like it from the standpoint of encapsulating the thread safety for lazy getters.  For the others with "time to live" I think I'm just going to move away from caching the value.  Mostly those attempts have just "protecting users from themselves" e.g., the SMC calls will fail if you don't leave a few (~15-20) milliseconds between them, or microoptimization preventing running code multiple times (trading CPU for the memory to store the cached values).

I'll have to think about this a bit.

**Comment by dbwiddis** [comment]
Finished removing the interval-based caching in #917 and #918.
