### ISSUE TITLE
[version 3.13.0] SystemInfo (and many classes available via it) is not thread-safe

### ISSUE THREAD

**Issue by stIncMale** [oshi/oshi#797]
Instances of `SystemInfo` initialize its fields lazily, but without any synchronization, which leads to executions with data races and the possibilities of having either `NullPointerException` or observing default values for primitive fields.

After taking a first look, I thought "maybe users are not supposed to use `SystemInfo` concurrently", but then I saw the question [Are oshi SystemInfo instances thread safe?](https://github.com/oshi/oshi/issues/660), and an answer 
> I've made reasonable efforts to try to avoid issues with thread safety, and many classes will work without a problem, I certainly can't guarantee it

and realized that `SystemInfo` is actually supposed to be used concurrently... I am going to present a only a few issues, but I would expect that there are more problems.

**Problem 1: lazy initialization without synchronization**
Consider `SystemInfo.getHardware().getMemory().getTotal()`:
* a plain field `SystemInfo.hardware` is initialized lazily to a new instance of let's say `LinuxHardwareAbstractionLayer` when `SystemInfo.getHardware` is called.
* a plain field `LinuxHardwareAbstractionLayer.memory` is initialized lazily to a new instance of let's say `LinuxGlobalMemory` when `LinuxHardwareAbstractionLayer.getMemory` is called.
* a plain field `LinuxGlobalMemory.memTotal` is initialized lazily to a `long` value when `LinuxGlobalMemory.getTotal` is called.

All those fields are initialized without any memory synchronization. As a result writes to `SystemInfo.hardware` field produced by `SystemInfo.getHardware` method and reads from `SystemInfo.hardware` field produced by the same `SystemInfo.getHardware` method are not ordered with happens-before (HB) relation when `SystemInfo.getHardware` is called concurrently (unless a user of `SystemInfo` takes care of that...), and this means that executions contain data races. The mentioned reads of `SystemInfo.hardware` is allowed by the Java memory model to observe both writes to this field produced by `SystemInfo.getHardware` and the implicit write of the default value (this write exists in all executions regardless of whether the original code has it explicitly or not). The same is true for other mentioned fields, and thus there is no guarantee that we will not observe `null` in `SystemInfo.hardware`/`LinuxHardwareAbstractionLayer.memory` and 0 in `LinuxGlobalMemory.memTotal`.

Another slight sub-issue here is that concurrent executions of let's say `SystemInfo.getHardware` may create multiple instances of `LinuxHardwareAbstractionLayer`. But this is because of a race condition that we have in the algorithm "check if hardware is initialized and initialize it if it's not" (and [a race condition is a different thing from a data race](https://sites.google.com/site/aboutmale/techblog/raceconditiondatarace)). But creating a few excessive objects is probably fine for this specific scenario (I don't immediately see problems).

**Problem 2: `LinuxGlobalMemory.updateMeminfo` and `lastUpdate` does not pave proper synchronization**
A plain field `LinuxGlobalMemory.lastUpdate` is being read and written in `LinuxGlobalMemory.updateMeminfo` method without any synchronization. It leads to the things described in **Problem 1**, specifically there is no guarantee that reads from `lastUpdate` in `if (now - this.lastUpdate > 100)` ever see anything other than 0, which would lead each invocation of `LinuxGlobalMemory.lastUpdate` to read from `/proc/meminfo`.

A race condition similar to the one mentioned in **Problem 1** is also applicable here: `LinuxGlobalMemory.lastUpdate` may read from `/proc/meminfo` multiple times when called concurrently because `now - this.lastUpdate > 100` appears to be true for multiple threads. Depending on the cost of reading from `/proc/meminfo`, it may or may not be a problem.

**Comment by dbwiddis** [comment]
You're identifying some good issues but I'd prefer to address fixes in the 4.X branch.

**Comment by stIncMale** [comment]
> [please help!] [PR welcome]

It requires a significant amount of work. I can provide a code expressing an idea of how the aforementioned problems may be solved (will this be helpful?), but I can't afford fixing the whole thing. However, I will ask whether the company would agree to allocate my time for this task since we are using OSHI (though I doubt it).

**Comment by dbwiddis** [comment]
I will update the javadocs on the 3.X branch unless you get to it first.

It is not intended to create multiple _simultaneous_ instances of SystemInfo.  It was intended to allow you to let a `SystemInfo` instance (and its subordinates) be garbage collected and create another one later.    Of course, there are a few `static` objects around that make that not completely perfect either... again, all acknowledged issues we're working hard on eliminating in 4.X.  And when I say "we" I mean "mostly me" and I'd love some help. :)

**Comment by stIncMale** [comment]
> It is not intended to create multiple _simultaneous_ instances of SystemInfo. It was intended to allow you to let a `SystemInfo` instance (and its subordinates) be garbage collected and create another one later.

What if I create only a single instance and will use it during the whole application run time. Will `SystemInfo` re-read all the dynamic information about the system, or something may not be updated and I should create a new instance to be able to see the updated information? (I see that `SystemInfo.getHardware().getMemory().getAvailable()` is updated, but I can't easily tell whether this is true for all dynamic information or not)

**Comment by dbwiddis** [comment]
> What if I create only a single instance and will use it during the whole application run time. Will `SystemInfo` re-read all the dynamic information about the system

**Comment by dbwiddis** [comment]
> What if I create only a single instance and will use it during the whole application run time. Will `SystemInfo` re-read all the dynamic information about the system

It's a mixed bag.  See #310 and #548 and I'm attempting to implement in 4.X consistently in #771.

Currently, for the most part it is updated for non-array method calls, whereas calls that return arrays tend to return static data.

**Comment by dbwiddis** [comment]
With regard to time commitment, understood.  Any help, even documenting a pattern that should be used elsewhere, is useful.   I just want to focus on fixing 4.X as much as possible.  You've already identified many of the issues we're already in the process of fixing... and as you've noted it's a big task and I'm mostly the only one doing it (in my spare time, and I'm not even a software engineer).

The curse of a useful library is more people start using it and then find all the flaws that have been lurking around for years. :)

**Comment by stIncMale** [comment]
> It's a mixed bag. See #310 and #548 and I'm attempting to implement in 4.X consistently in #771.

Thanks!

> I'm mostly the only one doing it (in my spare time, and I'm not even a software engineer)

Excuse my curiosity, do you know the story behind OSHI? Was it started by someone (or a company) and then abandoned, or was it started by you and since then you are still the only one actively contributing, or maybe the story is completely different?

> Any help, even documenting a pattern that should be used elsewhere, is useful.
I will submit the PR with the doc update in the coming days.

**Comment by dbwiddis** [comment]
OSHI was started in 2010 by @dblock and you can read about it in [this blog post](https://code.dblock.org/2010/06/23/introducing-oshi-operating-system-and-hardware-information-java.html).  There was some initial work on basic CPU and Memory stats on Windows, and using command lines in Mac and Linux but it mostly sat undeveloped.  Still, the API skeleton was there and was easy to build on.

In 2015, I was working on a cloud-based distributed computing data mining problem utilizing [JPPF](https://jppf.org/).  As part of optimizing my use of cloud resources (that my company paid for) I wanted to know how much memory my Java code was using. JPPF's library used the [`OperatingSystemMXBean`'s `getFreePhysicalMemory()`](http://cr.openjdk.java.net/~jjg/8008367/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html#getFreePhysicalMemorySize()) method which was useless on Linux, as "free" always decreases to zero even though there's plenty "available".  I searched for a Java alternative and found none other than SIGAR (which had stopped development then) and OSHI (which had the same bug, but was open source and fixable).  I submitted a PR to fix the bug... and since I wanted to learn more about JNA decided to add more.  And more.  And more.  :) 

In the process i learned git, maven, and a bunch of other stuff.  I am not a professional software engineer, just an obsessed enthusiast who loves to learn and solve problems.   Most of OSHI is an exercise in web-searching for the appropriate C code or command lines and porting it to Java via JNA.

I've had a lot of things I've wanted to fix for a while, which is why 4.X is happening, but it will mostly be trying to stabilize the API, getting rid of all the (crappy) static caches, trying to be a little bit smarter (but not perfect) with thread safety.  But I'm hoping to drift back into "maintenance" mode after this overhaul, and letting the 5.x team take over with many more years of experience than I have.

There are some other contributors who have a grand vision for an OSHI 5.X.  I am really looking forward to turning over the project to professionals.

**Comment by stIncMale** [comment]
Thank you for the detailed post! This may be worth mentioning in the [FAQ](https://github.com/oshi/oshi/blob/master/FAQ.md)

> I searched for a Java alternative and found none other than SIGAR (which had stopped development then) and OSHI

So true :)

**Comment by dbwiddis** [comment]
So is fixing this as easy as synchronizing on the object to be returned by the lazy getters?

**Comment by stIncMale** [comment]
> synchronizing on the object to be returned by the lazy getters

Either I misunderstood you, or no, this is not possible :) Could you modify the below sample to show your idea?

```
public class SystemInfo {
  private HardwareAbstractionLayer hardware;

  //may return null
  public HardwareAbstractionLayer getHardware() {
    if (hardware == null) {
        hardware = new LinuxHardwareAbstractionLayer();
    }
    return hardware;
  }
}
```

**If the possibility of the method `getHardware` creating and returning more than one instance of `LinuxHardwareAbstractionLayer` is acceptable** (in practice it would rarely happen and the theoretical maximum of the number of excessive instances of `LinuxHardwareAbstractionLayer` is `number_of_all_threads_calling_getHardware - 1`), then the following can be done:
```
//added the volatile modifier
public class SystemInfo {
  private volatile HardwareAbstractionLayer hardware;

  //may return different instances of LinuxHardwareAbstractionLayer, but never returns null
  //the method is wait-free
  public HardwareAbstractionLayer getHardware() {
    HardwareAbstractionLayer result = hardware;
    if (result == null) {
        result = new LinuxHardwareAbstractionLayer();
        hardware = result;
    }
    return result;//avoid the unnecessary second volatile read
  }
}
```

**If the possibility of the method `getHardware` returning more than one instance of `LinuxHardwareAbstractionLayer` is not acceptable, but the possibility of creating multiple instances is acceptable**, then the following can be done:
```
//use AtomicReference instead of volatile because it provides CAS operation
public class SystemInfo {
  private AtomicReference<HardwareAbstractionLayer> hardware;

  //may create multiple instances of LinuxHardwareAbstractionLayer, but always returns the same instance, never returns null
  //the method is lock-free, but not wait-free
  public HardwareAbstractionLayer getHardware() {
    HardwareAbstractionLayer result = hardware.get();
    if (hardware == null) {
      result = new LinuxHardwareAbstractionLayer();
      if (!hardware.compareAndSet(null, result)) {//we failed, another thread succeeded and set the value
        result = hardware.get();
      }
    }
    return result;//avoid the unnecessary second volatile read
  }
}
```

**If the method `getHardware` must create not more than one instance of `LinuxHardwareAbstractionLayer` and must always return the same instance**, then the method have to be blocking (there is absolutely nothing wrong with it in our situation, just saying) and for example the following can be done (it uses the same idea called double-checked locking that I used in https://gist.github.com/stIncMale/2fce5f39aa37ac4584e0635ca6f67fe5):
```
//use volatile modifier and a lock
public class SystemInfo {
  private final Object monitor = new Object();
  private volatile HardwareAbstractionLayer hardware;

  //always returns the same instance of LinuxHardwareAbstractionLayer, never returns null, never creates more than one instance
  //the method is blocking, but the majority of invocations are wait-free nonetheless
  public HardwareAbstractionLayer getHardware() {
    HardwareAbstractionLayer result = hardware;
    if (result == null) {
      synchronized(monitor) {
        result = hardware;
        if (result == null) {//double-check while holding a lock
          result = new LinuxHardwareAbstractionLayer();
          hardware = result;
        }
      }
    }
    return result;//avoid the unnecessary second volatile read
  }
}
```

**Comment by dbwiddis** [comment]
> Could you modify the below sample to show your idea?

I would except I realized later that I can't synchronize on a null reference.  Thanks for the detailed explanation of how your monitor works in parallel with what appears to be "double checked locking".

For reference, however, I don't care if we have multiple HAL objects floating around.  The only issue is not returning null, so "A" is acceptable.  But if C can be encapsulated in an object that makes it easy to call, then it's probably the best route.

**Comment by dbwiddis** [comment]
I was also about to say "A" won't work because I need serializable objects to enable the JSON implementation, but then remembered that Jackson uses reflection rather than actual serialization... so it might work...

**Comment by stIncMale** [comment]
Oh, I am not proposing to remove `synchronized`, I just gave examples of lazy initialization. So my code is not what I propose to replace `SystemInfo` with. Moreover, this changed need to be done to a ton of classes, not only `SystemInfo` which I picked only as an example.

**Comment by dbwiddis** [comment]
Right, it's a matter of how complex this has to be, how much can be easily abstracted/encapsulated in a helper class, or perhaps just document "Only create one instance of SystemInfo per thread."
