### ISSUE TITLE
Null dereference in PerfCounterQuery

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#803]
I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to open source before. This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. :-) Here are the steps to get a PR merged here.

- [ ] Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  I'll walk you through anything you don't understand.
- [ ] Find the [PerfCounterQuery.java](https://github.com/oshi/oshi/blob/1ea3575239c05ce75a71bbd8739fa691a3b672d2/oshi-core/src/main/java/oshi/data/windows/PerfCounterQuery.java#L107) class.
- [ ] Line 107 attempts to check whether an enum implements an interface using `propertyEnum.getDeclaringClass()`. However, it is possible for `getDeclaringClass()` to return null if the argument is a class which does not extend/implement another class. This will result in an NPE on line 109 when attempting to `getName()` on a null object to create the message for an exception. While we still get an exception, an undocumented NPE is much less useful to the developer than the intended exception message about implementing an interface.
- [ ] Alter the code at line 109 (or earlier) to test whether the declaring class is null prior to calling the `getName()` method on it, putting a more useful string in the exception.  
- [ ] Fork the project, commit your changes to your fork, create a PR, and get it merged
- [ ] Celebrate

**Comment by bewbyte** [comment]
Can I work on this?

**Comment by dbwiddis** [comment]
Go for it! Just assign it to yourself!

**Comment by yehia67** [comment]
Do you want me to add more details in the following string("must implement PdhCounterProperty") Or create a new one and throw an new exception?  (sorry if it's an easy question but I am new in contributing)
```
 throw new IllegalArgumentException(
                    propertyEnum.getDeclaringClass().getName() + " must implement PdhCounterProperty.");

```

**Comment by yehia67** [comment]
I will check '.getName()' functiom if it return Null I will throw error is that alright?

**Comment by dbwiddis** [comment]
Hi @yehia67.  The "... must implement" is fine.  I believe it is sufficient to change `getDeclaringClass()` in the exception message to `getClass()`.

**Comment by yehia67** [comment]
Okay thanks @dbwiddis  I will make pull request.

**Comment by yehia67** [comment]
hello @dbwiddis , Sorry for bothering you but I had made the pull request and I get a reply that I don't Understand could you please explain it  to me.
https://github.com/oshi/oshi/pull/805

**Comment by dbwiddis** [comment]
The reply was just an automated scan by our code coverage bot.   Your PR looks good and I'll merge it!  Thanks for contributing to Open Source!
