### ISSUE TITLE
OSFileStore.getUsableSpace() takes on the same value as Java's getFreeSpace() instead of Java's getUsableSpace().

### ISSUE THREAD

**Issue by ronald-bautista** [oshi/oshi#820]
It looks like OSFileStore.getUsableSpace() has the same value as Java's getFreeSpace() instead of Java's getUsableSpace().

I tried to get the available disk space on my Ubuntu 14.04. Following are the results. I was expecting to get 866.7 MiB for the usableSpace from OSHI but got the value 5.8GiB instead.

java 8:
/: total:97.1 GiB free:5.8 GiB usable:866.7 MiB

oshi:
/: total=97.1 GiB usable=5.8 GiB

df -h:
/dev/mapper/ubuntu--vg-root   98G   92G  861M 100% /

From the source code below, The usableSpace is taken from vfsStat.f_bfree.longValue(). Shouldn't it be taken from vfsStat.f_bavail.longValue() instead?
```       
try {
                LibC.Statvfs vfsStat = new LibC.Statvfs();
                if (0 == LibC.INSTANCE.statvfs(path, vfsStat)) {
                    totalInodes = vfsStat.f_files.longValue();
                    freeInodes = vfsStat.f_ffree.longValue();
                    totalSpace = vfsStat.f_blocks.longValue() * vfsStat.f_bsize.longValue();
                    usableSpace = vfsStat.f_bfree.longValue() * vfsStat.f_bsize.longValue();
                } else {
                    File tmpFile = new File(path);
                    totalSpace = tmpFile.getTotalSpace();
                    usableSpace = tmpFile.getUsableSpace();
                    LOG.error("Failed to get statvfs. Error code: {}", Native.getLastError());
                }
```
OSHI version used: 3.13.0

**Comment by dbwiddis** [comment]
You're correct that it's matching the `getFreeSpace()` value, but the documentation for `getUsableSpace()` seem to imply it's for the JVM rather than for the operating system:

> getUsableSpace() Returns the number of bytes available to this Java virtual machine on the file store.

It's possible we might prefer `getUnallocatedSpace()` instead.  Or does that match OSHI's "free"?

**Comment by dbwiddis** [comment]
Also relevant, the difference between free and available (in the `vfsstat` structure) is for privileged vs. unprivileged users.  It seems that `ext` filesystem types reserve ~5% of disk space for the `root` user.

So the question is, which should OSHI report?  Is there a parallel situation on other file systems?

**Comment by ronald-bautista** [comment]
from the behavior (not document) of java's getTotalSpace(), getFreeSpace() and getUsableSpace(), the values seem to match with the OS's 'df -h' command. Right now, OSHI OSFileStore only exposes 2 of those 3 values: TotalSpace and FreeSpace. I would need the 3rd value which is the available space as described by 'df -h' or UsableSpace as described by java.
From the source code, when LibC.INSTANCE.statvfs fails, it falls back to getting the usableSpace using the java's getUsableSpace(). So it seems the oshi usableSpace is trying to get the same value as java's usablespace.

**Comment by ronald-bautista** [comment]
From java's source code, it seems their usableSpace is taken from fsstat.f_bavail and freeSpace is taken from fsstat.f_bfree:

```
JNIEXPORT jlong JNICALL
Java_java_io_UnixFileSystem_getSpace(JNIEnv *env, jobject this,
                                     jobject file, jint t)
{
    jlong rv = 0L;

    WITH_FIELD_PLATFORM_STRING(env, file, ids.path, path) {
        struct statvfs64 fsstat;
        memset(&fsstat, 0, sizeof(fsstat));
        if (statvfs64(path, &fsstat) == 0) {
            switch(t) {
            case java_io_FileSystem_SPACE_TOTAL:
                rv = jlong_mul(long_to_jlong(fsstat.f_frsize),
                               long_to_jlong(fsstat.f_blocks));
                break;
            case java_io_FileSystem_SPACE_FREE:
                rv = jlong_mul(long_to_jlong(fsstat.f_frsize),
                               long_to_jlong(fsstat.f_bfree));
                break;
            case java_io_FileSystem_SPACE_USABLE:
                rv = jlong_mul(long_to_jlong(fsstat.f_frsize),
                               long_to_jlong(fsstat.f_bavail));
                break;
            default:
                assert(0);
            }
        }
    } END_PLATFORM_STRING(env, path);
    return rv;
}
```

**Comment by dbwiddis** [comment]
Agreed that OSHI fallback is inconsistent.  I was musing “if we only report 2 numbers” what should they be.  Or maybe we should report three numbers. 

Given the name of the method and JVM implementation I’m inclined to match it but also want to look at the other OS implementations.

**Comment by ronald-bautista** [comment]
I think it is better to report 3 numbers as some users might need one of those 3 like myself. If we were constrained to just report 2 numbers, I would rather have the number that matches the Available space as this will usually be useful for my app about how much data I can actually write to the disk. For the method naming, I prefer to match it either with the java's naming or statsv naming. So it's either of these two: 
java:
getUsableSpace(), getFreeSpace()
stasv:
getAvailableSpace(), getFreeSpace()

**Comment by dbwiddis** [comment]
I’m inclined to go with 3 and match JDK FileStore class naming.

**Comment by dbwiddis** [comment]
Ended up going with 3 and matching JDK `File` class naming instead.  Will be fixed in 4.x.  As a workaround for 3.X you can do `File f = new File(fs.getMount());` and use the `File` class methods for free and usable space.

**Comment by ronald-bautista** [comment]
thanks!
