### ISSUE TITLE
SystemInfoTest - reconsider using an arrayList with logger rather than system out

### ISSUE THREAD

**Issue by hazendaz** [oshi/oshi#829]
This is a rehash of an old request.  I rewrote SystemInfoTests to stop using system out long ago. The data is collected in an array list and written to the logger at the end.  In turn I use this as a foundation class in psi probe to output the system information as this class defines on a JSP page.  It would be extremely helpful to raise this again as a pull request so I can avoid unnecessary merge conflicts while keeping up-to-date.

A lot has changed since the early days with this project thus currently a simple change to the simple logging setup to not write out to a log file will still provide the system out usability.  An additional change to send output from tests to redirected log file also solve that issue.  The resulting behaviour as best I can tell is the same.  I can send a PR for review if this sounds acceptable.

**Comment by dbwiddis** [comment]
I'm fine with an overhaul of this class for a few reasons:
- It's not properly a test and doesn't really belong in the "test" structure.
- But the test does allow us to specify a logging provider as a test dependency. 
- Really it should be in the demo artifact but that's a whole separate later and harder to do

As for copying to an array, my concern is that the user won't see any output until the end; also, I occasionally like to look at the timestamp differences for tracking down slow performance issues.  If we retain the log output to the console while the output is being generated and then dump it at the end, that would probably work.

Happy to look at your PR in any case!

**Comment by hazendaz** [comment]
I think I cover overall timing related concerns.  I'd still keep this in the test area.  The small additional changes I think address concerns from way back when.  Since each section otherwise has a log that it started, it probalby has that all nailed down.  I'll try to send this over tomorrow after I look through this a bit more to ensure I've covered all concerns.  Thanks!

**Comment by dbwiddis** [comment]
You still thinking of doing this? :)

**Comment by hazendaz** [comment]
Yes.  Sorry got busy with other stuff and figured this was low priority in big scheme of things.  I have been keeping up to date.  I'll try to look at this over the weekend.  Thanks for checking back on this.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dbwiddis** [comment]
I think I can do this.  This is essentially replacing all existing `System.out.println(foo)` calls with an `output.add(foo)` call, and then dumping the log at the end?  Do you log line by line, or just dump one single line with all the output in one entry?

**Comment by hazendaz** [comment]
Sort of, I have the work done, I just haven't submitted it and wanted to review and make sure I covered all the original performance concerns with it.  Hang on this one, I'll get you a pull request over later this weekend and that can serve as a starting piont.  From what I recall, I think I handled everything as needed.

**Comment by hazendaz** [comment]
PR pushed up.  I agree with your suggestion this class doesn't really belong in tests.  In fact the usage I'm trying to accomplish with it certainly suggests that fact.  Feel free to make any adjustments or changes as needed.  I'm dropping off for the night.  Cheers!
