### ISSUE TITLE
3.13.x on OSX Sierra: ERROR - Failed syctl call: kern.procargs2, Error code: 22

### ISSUE THREAD

**Issue by srosenthal13** [oshi/oshi#831]
ERROR: oshi.software.os.MacOperatingSystem  - Failed syctl call: kern.procargs2, Error code: 22

I see there was a fix for this #395, #396 , but I ran into it today on OSX Sierra, 10.12.4 with OSHI 3.13.x Release. So I must be hitting a condition not covered by that fix.

From what I can see in the 3.13.x sources, the error is being logged in MacOperatingSystem getCommandLine() and should return empty string:

`        if (0 != SystemB.INSTANCE.sysctl(mib, mib.length, procargs, size, null, 0)) {
            LOG.error("Failed syctl call: kern.procargs2, Error code: {}", Native.getLastError());
            return "";
        }`

I'm calling getProcesses() from within another application with the following args:

`OSProcess[] processes = os.getProcesses(0, ProcessSort.NAME, false);`

I get the return values I'm expecting, but then the error occurs. 

I'll investigate further to see I can narrow it down more.

**Comment by dbwiddis** [comment]
The fix in #396 appeared to ignore process 0 which had no command line.  Is it possible that there may be another case where a process has no command line?  Can you add a debug statement to try to identify anything else about that problematic process?

**Comment by srosenthal13** [comment]
Now I'm having a difficult time reproducing it. I've seen it a few times, but it's intermittent. I'll keep chipping away this weekend. I should be able to set up a debug environment on this test system and I'll try to grab more info at the point of failure (assuming I can get it to fail again!).

**Comment by dbwiddis** [comment]
It may just be a race condition where a process ends between grabbing the list and checking the command line.  IN which case, we may just want to change the log message to a warning.

**Comment by srosenthal13** [comment]
That seems sensible, particularly since the if block seems to want to resolve the error by returning an empty string (which probably isn't happening because it's an error?). 

I don't know anything about OSX at this deep a level, but is there anything inherently "dangerous" about this condition? Or is it really just a "sorry, didn't find what you were looking for" type of thing? Seems that way if empty string is a reasonable response.

**Comment by dbwiddis** [comment]
I don't know that deep either, but I can't imagine that `sysctl` isn't safe for a particular command that's been around for a decade, where "invalid pid" is probably the most likely error case.

**Comment by dbwiddis** [comment]
Have you had any more insight into this?  I might just change this to a WARN log message unless you are aware of any other possible issue...
