### ISSUE TITLE
StringIndexOutOfBoundsException——when get processe infomation

### ISSUE THREAD

**Issue by ljtnono** [oshi/oshi#833]
operatingSystem:ubuntu 18.04 
tools: IDEA 2019.1
version:3.13.0
jdk:1.8

code:
```java
try {
            List<OSProcess> procs = Arrays.asList(operatingSystem.getProcesses(5, OperatingSystem.ProcessSort.MEMORY, false));

            System.out.println("   PID  %CPU %MEM       VSZ       RSS Name");
            for (int i = 0; i < procs.size(); i++) {
                OSProcess p = procs.get(i);
                System.out.format(" %5d %5.1f %4.1f %9s %9s %s%n", p.getProcessID(),
                        100d * (p.getKernelTime() + p.getUserTime()) / p.getUpTime(),
                        100d * p.getResidentSetSize() / memory.getTotal(), FormatUtil.formatBytes(p.getVirtualSize()),
                        FormatUtil.formatBytes(p.getResidentSetSize()), p.getName());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
```

output:
```java
java.lang.StringIndexOutOfBoundsException: String index out of range: 63
	at java.lang.String.substring(String.java:1963)
	at oshi.software.os.linux.LinuxOperatingSystem.getProcess(LinuxOperatingSystem.java:218)
	at oshi.software.os.linux.LinuxOperatingSystem.getProcesses(LinuxOperatingSystem.java:188)
	at cn.ljtnono.SystemInfoUtil.getProccessors(SystemInfoUtil.java:129)
	at cn.ljtnono.SystemInfoUtil.main(SystemInfoUtil.java:65)
```

or sometimes maybe all right:
```java
PID  %CPU %MEM       VSZ       RSS Name
 26742  16.0 22.5   5.0 GiB   1.7 GiB java
 27673   2.1 10.7   4.7 GiB 836.9 MiB java
  1796   7.2  6.4   4.1 GiB 506.1 MiB gnome-shell
  2570   2.0  4.2   1.7 GiB 332.5 MiB chrome
  2849   0.2  2.7   1.9 GiB 208.7 MiB chrome

```
as you see, it is unstable..

**Comment by dbwiddis** [comment]
Well, this is an interesting one.  OSHI is parsing the command line from the `/proc/<pid>/exe` pseudofile.  Here's the sequence of code that's throwing the exception:

        Pointer buf = new Memory(1024);
        int size = Libc.INSTANCE.readlink(String.format("/proc/%d/exe", pid), buf, 1023);
        if (size > 0) {
            path = buf.getString(0).substring(0, size); // Exception here!
        }

The error message indicates `size` is 63 here, and is set as the return value from `readlink()`.  So it appears that the call `buf.getString(0)` when applied to a 63-byte buffer is returning a string less than 63 characters long.

This may be an encoding thing... would be interesting to try to figure out which command line is causing the crash.

In any case this is probably a bug and instead of relying on `size` we should check the length of `buf.getString(0)` before calling `substring()`.

**Comment by dbwiddis** [comment]
I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to open source before. This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. :-) Here are the steps to get a PR merged here.

- [ ] Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  I'll walk you through anything you don't understand.
- [ ] Find the [LinuxOperatingSystem.java](https://github.com/oshi/oshi/blob/cf25f117a8fbb75e02aba9bdb194ea023109e6e8/oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java#L217) class.
- [ ] Line 217 converts a JNA `Memory` buffer to a `String` and then creates a `substring()` without doing any length checking.  This fails in some cases (see above).
- [ ] Alter the code to temporarily store the string fetched with `buf.getString(0)` so its `length()` can be calculated.
- [ ] Alter the code getting the substring to take the smaller value of `size` or the temporary string's length.
- [ ] Fork the project, commit your changes to your fork, create a PR, and get it merged
- [ ] Celebrate

**Comment by nsjanani** [comment]
Hello, 
Can I work on this ?
I made a fix on my local feature branch like below:
` if (size > 0) {
            String tmp = buf.getString(0);
            int requiredOffset;
            if(size < tmp.length())
                requiredOffset = size;
            else
                requiredOffset = tmp.length();
            path = tmp.substring(0, requiredOffset);
        }`

But couldn't push my feature branch.
Please let me know.

Cheers,
Janani

**Comment by nsjanani** [comment]
Am getting access denied, while trying to push my feature branch.
`remote: Permission to oshi/oshi.git denied to nsjanani.
fatal: unable to access 'https://github.com/oshi/oshi.git/': The requested URL returned error: 403
`
Any help on the above would be really appreciated.

**Comment by dbwiddis** [comment]
Fix looks good...  I might have inlined the conditional with a ternary operator like `path = tmp.substring(o, tmp.length() < size ? tmp.length() : size);` but yours works as well.  Can you please add curly braces to your if/then code to match our standard formatting? 

You are trying to push directly to the project site -- that only works if you're a maintainer like me.  You need to fork the project to your own github site and push the change there.  Then from the github site you can submit a pull request.

**Comment by nsjanani** [comment]
Sorry for missing the master step.
I did the changes successfully after forking and with using the ternary operation - https://github.com/oshi/oshi/pull/837

Kindly review and merge it.
