### ISSUE TITLE
Start with springBoot error

### ISSUE THREAD

**Issue by frejus123** [oshi/oshi#835]
Trying to gather harware information using the oshi-core dependancy (3.13.0) with SpringBoot (2.0.1RELEASE), and JDK1.8 under Win7 X64 bug get some ERROR .It says 

code:
`java.lang.NoClassDefFoundError:com/sun/jna/platform/win32/COM/WbemcliUtil$WmiQuery
`
How could it be? Thanks.

**Comment by dbwiddis** [comment]
See #669.  This is an issue with Maven transitive dependencies processing for SpringBoot before OSHI.

To resolve, either:
  - Specify `oshi-core` earlier in your POM, or
  - Explicitly state the latest (5.2.0) version in your POM for both `jna` and `jna-platform`.

**Comment by dbwiddis** [comment]
Hi, @frejus123 were you able to resolve this?   Note OSHI 3.13.1 is now out and depends on JNA 5.3.0, so the answer is the same with the newer version(s).

**Comment by dbwiddis** [comment]
Closing as this is a common issue with transitive dependencies, and the solution is posted.
