### ISSUE TITLE
Wrong time unit used in LinuxCentralProcessor

### ISSUE THREAD

**Issue by drdwo** [oshi/oshi#843]
There is a problem with 
https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/hardware/CentralProcessor.java

In the documentation of 
long[][] getProcessorCpuLoadTicks();

we have:

"Note that while tick counters are in units of milliseconds, they may advance ..."

But the actual time unit is different on Linux, implementation in 
https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
is

List<String> procStat = FileUtil.readFile("/proc/stat");
       for (String stat : procStat) {
           if (stat.startsWith("cpu") && !stat.startsWith("cpu ")) {
               // Split the line. Note the first (0) element is "cpu" so
               // remaining
               // elements are offset by 1 from the enum index
               String[] tickArr = ParseUtil.whitespaces.split(stat);

And from 
http://www.linuxhowtos.org/System/procstat.htm we know:
"Time units are in USER_HZ or Jiffies (typically hundredths of a second)."

So either LinuxCentralProcessor should use USER_HZ to convert the data in ms, or
the documentation needs to be adapted. I would prefer an OS-independent fixed time unit.

**Comment by dbwiddis** [comment]
This is a case where I wrote the documentation before I changed the code, and then forget to change the code. :grin:

**Comment by dbwiddis** [comment]
I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to open source before. This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. :-) Here are the steps to get a PR merged here.

Linux tick counters return values in "Jiffies".  In response to #782, we decided to standardize all tick return values in milliseconds.  Your mission, should you choose to accept it, is to convert the Linux Jiffies to Milliseconds.

- [ ] Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  I'll walk you through anything you don't understand.
- [ ] Find the [LinuxCentralProcessor.java](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java#L269) class and locate the [querySystemCpuLoadTicks()](https://github.com/oshi/oshi/blob/bb94806b92f4a10c964b52fe9d351772e4b648e9/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java#L182) and [queryProcessorCpuLoadTicks()](https://github.com/oshi/oshi/blob/bb94806b92f4a10c964b52fe9d351772e4b648e9/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java#L269) methods.
- [ ] These methods currently return arrays of values in units of Jiffies.
- [ ] Alter these methods to return arrays of values in units of milliseconds.  The conversion is `Jiffies * 1000L / hz` where the `hz `value can be obtained from [`LinuxOperatingSystem.getHz()`](http://oshi.github.io/oshi/apidocs/oshi/software/os/linux/LinuxOperatingSystem.html#getHz()).
- [ ] Fork the project, commit your changes to your fork, create a PR, and get it merged
- [ ] Celebrate

**Comment by yudyack** [comment]
Hey i've created a PR to solve this. I don't know if it is the correct way to convert the ticks. 
Could you please review it.

**Comment by dbwiddis** [comment]
Looks great!
