### ISSUE TITLE
Disk statistics difference in linux

### ISSUE THREAD

**Issue by alextinng** [oshi/oshi#853]
Total/Used/Available size got from OSFileStore is always different with which got from "df -Th".
In my server, OSFileStore returned "/ total: 52710469632" but "df -Th" returned 50G, I am really confused, which is right?

**Comment by dbwiddis** [comment]
Doesn't `df` return the available (free) space on the drive, unless you use the `--total` switch?  Try `df --total` rather than the `h` switch which may do some rounding and isn't obviously clear whether it's Gibibytes or Gigabytes.

**Comment by dbwiddis** [comment]
I trust OSHI's number, as the `df` output isn't very clear on units.

Try using `df` without the `h` switch.  It's not clear whether the G means Gibibytes (1024^3) or Gigabytes (1000^3) or is some hybrid like 1024*1024 times a block size of 1000 (if you divide 52710469632 by 1024/1024/1000 you'll get a number that rounds to 50).  Use enough switches on `df` to get a more accurate reading.

**Comment by alextinng** [comment]
Thanks, I tried df --total, it does return different values.

**Comment by dbwiddis** [comment]
Can you post the full `df` output please?

**Comment by spyhunter99** [comment]
I'm seeing a related issue on CentOS 7 whereby all mount points on a specific storage device are not returned by new SystemInfo().getHardware().getDiskStores(). The system has 1 physical drive, which is listed with 2 partitions, "/boot" as one mount point and empty string as the other.

The output of `fidsk -l /dev/sda` lists two partitions, one it boot and the other presumably is everything else

The output of df is significantly different. Ignoring `tmpfs` and `devtmpfs` I have 3 mount points
 - /
 - /home
 - /boot

/ and /home in this case are listed as /dev/mapper/centos-root and /dev/mapper/centos-home in df's output. I think this is an artifact of the newer linux lvm based file format/partitioning scheme, maybe. 

Since they are all different sizes with free spaces, my expectation was that OSHI would return 3 mount points.

In addition, OSHI's field for partition size does not matching df's output. In my case, /boot is 1GB, which matches OSHI. The / parition is 50 GB, and /home is 26G. Oshi reports the empty string partition as 84.8G which is strange. I think the total drive size (it's a VM) is 80 GB.

So I think there's 2 issues here
- not all mount points are being matched with partitions
- secondary issue may be the interpretation of partition sizes vs the device's size

**Comment by dbwiddis** [comment]
Without seeing the actual output of the relevant commands and comparing it to the results via udev, there's not much I can do.  Is the block size different on CentOS?

**Comment by spyhunter99** [comment]
i can get the output, give me a few minutes

**Comment by spyhunter99** [comment]
````

df

Filesystem              1K-blocks     Used Available Use% Mounted on
/dev/mapper/centos-root  52403200 11576992  40826208  23% /
devtmpfs                  3525940        0   3525940   0% /dev
tmpfs                     3543044        0   3543044   0% /dev/shm
tmpfs                     3543044    12880   3530164   1% /run
tmpfs                     3543044        0   3543044   0% /sys/fs/cgroup
/dev/sda1                 1038336   169560    868776  17% /boot
/dev/mapper/centos-home  26324420    33100  26291320   1% /home
tmpfs                      708612        4    708608   1% /run/user/42
tmpfs                      708612       24    708588   1% /run/user/0


df --total

Filesystem              1K-blocks     Used Available Use% Mounted on
/dev/mapper/centos-root  52403200 11578036  40825164  23% /
devtmpfs                  3525940        0   3525940   0% /dev
tmpfs                     3543044        0   3543044   0% /dev/shm
tmpfs                     3543044    12872   3530172   1% /run
tmpfs                     3543044        0   3543044   0% /sys/fs/cgroup
/dev/sda1                 1038336   169560    868776  17% /boot
/dev/mapper/centos-home  26324420    33100  26291320   1% /home
tmpfs                      708612        4    708608   1% /run/user/42
tmpfs                      708612       24    708588   1% /run/user/0
total                    95338252 11793596  83544656  13% -



df -h

Filesystem               Size  Used Avail Use% Mounted on
/dev/mapper/centos-root   50G   12G   39G  23% /
devtmpfs                 3.4G     0  3.4G   0% /dev
tmpfs                    3.4G     0  3.4G   0% /dev/shm
tmpfs                    3.4G   13M  3.4G   1% /run
tmpfs                    3.4G     0  3.4G   0% /sys/fs/cgroup
/dev/sda1               1014M  166M  849M  17% /boot
/dev/mapper/centos-home   26G   33M   26G   1% /home
tmpfs                    693M  4.0K  692M   1% /run/user/42
tmpfs                    693M   24K  692M   1% /run/user/0

````

**Comment by alextinng** [comment]
> Can you post the full `df` output please?

I will but I can't, we are using different machines for accessing internet and developing, so it's hard for me to copy and paste command output.

**Comment by dbwiddis** [comment]
Thanks @spyhunter99 but I also need to see OSHI's #s (derived from `udev`) for comparison.   Also recognize that "G" is kinda vague in units, is it Gigabytes or Gibibytes?  When you say OSHI shows 84.8G vs. 80 G which units are being compared on both ends?  Also the contents of `/proc/self/mounts` would be useful for debugging the mounting mismatch you cite.

**Comment by spyhunter99** [comment]
this is centos7 by the way, recent download

mounts
````
rootfs / rootfs rw 0 0
sysfs /sys sysfs rw,seclabel,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
devtmpfs /dev devtmpfs rw,seclabel,nosuid,size=3525940k,nr_inodes=881485,mode=755 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,seclabel,nosuid,nodev 0 0
devpts /dev/pts devpts rw,seclabel,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,seclabel,nosuid,nodev,mode=755 0 0
tmpfs /sys/fs/cgroup tmpfs ro,seclabel,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,seclabel,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,seclabel,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,seclabel,nosuid,nodev,noexec,relatime,net_prio,net_cls 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,seclabel,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,seclabel,nosuid,nodev,noexec,relatime,cpuacct,cpu 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,seclabel,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,seclabel,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,seclabel,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,seclabel,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,seclabel,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,seclabel,nosuid,nodev,noexec,relatime,freezer 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
/dev/mapper/centos-root / xfs rw,seclabel,relatime,attr2,inode64,noquota 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=35,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=27819 0 0
mqueue /dev/mqueue mqueue rw,seclabel,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,seclabel,relatime 0 0
/dev/sda1 /boot xfs rw,seclabel,relatime,attr2,inode64,noquota 0 0
/dev/mapper/centos-home /home xfs rw,seclabel,relatime,attr2,inode64,noquota 0 0
sunrpc /var/lib/nfs/rpc_pipefs rpc_pipefs rw,relatime 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
tmpfs /run/user/42 tmpfs rw,seclabel,nosuid,nodev,relatime,size=708612k,mode=700,uid=42,gid=42 0 0
tmpfs /run/user/0 tmpfs rw,seclabel,nosuid,nodev,relatime,size=708612k,mode=700 0 0
gvfsd-fuse /run/user/0/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=0,group_id=0 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0

````


sample code and output

````
SystemInfo si = new SystemInfo();
        HardwareAbstractionLayer hw = si.getHardware();

        HWDiskStore[] drives = hw.getDiskStores();

        for (HWDiskStore h : drives) {
            for (HWPartition partition : h.getPartitions()) {
                System.out.println(h.getName() + " " + h.getModel() + " "
                        + partition.getMountPoint() + " "
                        + partition.getIdentification() + " "
                        + partition.getName() + " "
                        + partition.getType() + " "
                        + partition.getSize() + " "
                        + partition.getMajor() + " "
                        + partition.getMinor());
            }
            System.out.println(h.getName() + " " + h.getReadBytes() + " " + h.getWriteBytes() + " " + h.getTransferTime() + " " + h.getTimeStamp());
        }
        
        /*
        output:
/dev/sr0 0 0 0 1557889857624
/dev/sda VMware_Virtual_S /boot /dev/sda1 sda1 xfs 1073741824 8 1
/dev/sda VMware_Virtual_S  /dev/sda2 sda2 LVM2_member 84824555520 8 2
/dev/sda 1137170944 53824512 32114 1557889857625
/dev/dm-0 1123256832 49630208 31743 1557889857628
/dev/dm-1 2519040 0 25 1557889857628
/dev/dm-2 1145344 2097152 67 1557889857629
        */
````

**Comment by spyhunter99** [comment]
i think the default view is based on Gibibytes from df

**Comment by dbwiddis** [comment]
Well, I'm stumped. A few more commands:
```
cat /proc/partitions
blockdev --getsize64 /dev/sda1
cat /sys/class/block/sda1/size
```

**Comment by spyhunter99** [comment]
`blockdev --getsize64 /dev/sda1`
1073741824

`cat /sys/class/block/sda1/size`
2097152

`cat /proc/partitions`
![image](https://user-images.githubusercontent.com/1975321/57772904-b3a3fa80-76e4-11e9-89a5-56dcdc3c97d1.png)

Note, image was from a different vm, so the numbers may be slightly off

**Comment by alextinng** [comment]
I found disk usage contains more mounted directories compared to "df" command. I found 4 mountings using 'df' command(/, /dev/shm, /boot, /u01), but (/, /dev/shm, /boot, /u01, /net, /misc) using oshi, so what is /net and /misc mean? both of their size is empty.

**Comment by dbwiddis** [comment]
Well, I'll have to say I'm stumped.   I don't know if CentOS does something different with udev than the other Linux distributions.  Without having my own VM to test/develop, and nothing obvious in all this output, I'm not sure I can do much. I welcome any fixes from those who can test them.

**Comment by spyhunter99** [comment]
well centos is open source and free, as in free beer. i think it's centos.org. I've used it with virtual box, vmware and xen without much an issue. It's basically the same distro as RHEL. While I have a VM setup and can send it to you, but it may be faster to just build one yourself. I saw this behavior with both centos6.10 and 7.whatever the last download is. Oh and my numbers are with the last 3.x release version.

I can help troubleshoot it i guess. Looking at the source, it looks like it's all jna calls. So either some in jna land isn't right or it's the parsing code in oshi that's wrong

**Comment by dbwiddis** [comment]
I'm sure I can eventually find a CentOS ISO and install it and try to test things, but it's way on the bottom of my to-do list, with the priority being getting version 4 out the door.  Unfortunately my free time has disappeared since my team of 3 at work has now become a team of 1 (me).  Given the many other issues apparently being raised with CentOS it may have enough differences from other Linux distros (or require manual install of a particular package that's default on others) that it just doesn't play nice.

Definitely a problem to solve, but it's looking more and more like a completely different OS that requires testing everything and porting exceptions.

**Comment by spyhunter99** [comment]
understood, i'll see what i can do

**Comment by dbwiddis** [comment]
So, this is a bug.  OSHI uses `statvfs` to get the filesystem size.  The returned structure is:
```
struct statvfs {
    unsigned long  f_bsize;    /* file system block size */
    unsigned long  f_frsize;   /* fragment size */
    fsblkcnt_t     f_blocks;   /* size of fs in f_frsize units */
    fsblkcnt_t     f_bfree;    /* # free blocks */
    fsblkcnt_t     f_bavail;   /* # free blocks for unprivileged users */
    fsfilcnt_t     f_files;    /* # inodes */
    fsfilcnt_t     f_ffree;    /* # free inodes */
    fsfilcnt_t     f_favail;   /* # free inodes for unprivileged users */
    unsigned long  f_fsid;     /* file system ID */
    unsigned long  f_flag;     /* mount flags */
    unsigned long  f_namemax;  /* maximum filename length */
};
```
Note the comment on `f_blocks` which gives the total disk size.  It's in fragments, not blocks.  So OSHI's calculations here are wrong if fragment size <> block size:
```
totalSpace = vfsStat.f_blocks.longValue() * vfsStat.f_bsize.longValue();
usableSpace = vfsStat.f_bavail.longValue() * vfsStat.f_bsize.longValue();
freeSpace = vfsStat.f_bfree.longValue() * vfsStat.f_bsize.longValue();
```
Here's the same calculations in the JDK source code that produce the same statistics in the `File` class:
```
            case java_io_FileSystem_SPACE_TOTAL:
                rv = jlong_mul(long_to_jlong(fsstat.f_frsize),
                               long_to_jlong(fsstat.f_blocks));
                break;
            case java_io_FileSystem_SPACE_FREE:
                rv = jlong_mul(long_to_jlong(fsstat.f_frsize),
                               long_to_jlong(fsstat.f_bfree));
                break;
            case java_io_FileSystem_SPACE_USABLE:
                rv = jlong_mul(long_to_jlong(fsstat.f_frsize),
                               long_to_jlong(fsstat.f_bavail));
                break;
```
So: OSHI needs to change those calculations to be fragments.

**Comment by dbwiddis** [comment]
Sorry for taking a year to investigate what should have been an easy spot when this was first filed!

**Comment by dbwiddis** [comment]
Although [this StackOverflow thread](https://stackoverflow.com/a/54835515/1161484) indicates there shouldn't be a difference.

**Comment by dbwiddis** [comment]
OK, while the above fix is correct, I don't think it actually changes anything in practice.  But I think I know the original cause of the mismatch.  The filesystem type is xfs, which maintains journaling records.

Per [this xfs tech manual](https://techpubs.jurassic.nl/manuals/hdwr/admin/LX_XFS_AG/sgi_html/ch02.html):

> The disk space dedicated to the log does not show up in listings from the df command, nor can you access it with a filename.

**Comment by dbwiddis** [comment]
FYI to lay this issue to rest. @tausiflife did some experiments and confirmed that the total size of a filestore reported by OSHI is correct, and includes both the actual storage space available to users and the XFS log area, which consumes a portion of the "used" space.  Since OSHI's number matches the core Java value, I'm going to consider this issue completely resolved!
