### ISSUE TITLE
getCpuTemperature() at CentOS 7 seems to give always 0.0

### ISSUE THREAD

**Issue by rlouwerens** [oshi/oshi#854]
I'm trying to get the current CPU temperature but always get zero's back from the getCpuTemperature() method.

We use version 3.12.2 but the same occurs with 3.12.0 (no other versions tried).

Files temp1_input until temp6_input exists at /sys/class/hwon/hwon0/ exists and holds values like 43000.

From logging I can see the following from FileUtil:
"Reading file temp3_input" 
"Reading file temp4_input" 
"Reading file temp5_input" 
"Reading file temp1_input" 
"Reading file temp2_input" 
Not sure, but it looks like the FileUtil is not getting the pull path and only the sensor?

Are any issues known with this setup?

Environment:
<artifactId>oshi-core</artifactId>
<groupId>com.github.oshi</groupId>
<version>3.13.2</version>

Centos 7.6.1810

**Comment by dbwiddis** [comment]
OSHI's logic is to use the value in `temp1_input` if it exists; if not, average `temp2_input` thru `temp6_input`.  Can you tell me what the value in `temp1_input` is?

**Comment by dbwiddis** [comment]
> Not sure, but it looks like the FileUtil is not getting the pull path and only the sensor

Yep, `LinuxSensors.java` line 66 does `FileUtil.getIntFromFile(f.getName())` but it needs to be the full path/name of the file on that line.  Can you test this fix and possibly submit a PR?

**Comment by rlouwerens** [comment]
> > Not sure, but it looks like the FileUtil is not getting the pull path and only the sensor
> 
> Yep, `LinuxSensors.java` line 66 does `FileUtil.getIntFromFile(f.getName())` but it needs to be the full path/name of the file on that line. Can you test this fix and possibly submit a PR?

I can verify (with unit tests) that changing the check `&& FileUtil.getIntFromFile(f.getName()) > 0;` at line 66 to `&& FileUtil.getIntFromFile(f.getAbsolutePath()) > 0;`  fixes the issue. 

I changed to unit test SensorsTest to verify the value is greater then 0 in stead of >=:
`assertTrue(s.getCpuTemperature() > 0d && s.getCpuTemperature() <= 100d);`

**Comment by dbwiddis** [comment]
Thanks for the test verification... I see you closed the PR, were you going to rework it?  A few comments:
 - we need to leave the `>=` test in there for other OS's and, I believe, some Linux distributions.  There's probably a way to set a conditional on Linux and the existence of those `sysfs` files, basically forcing the `>` test only if the files exist.
 - I think `getCanonicalPath()` may be preferable to Absolute, but that's just preference.  It's probably the exact same String in this case.

**Comment by rlouwerens** [comment]
I have a limited set of time currently, but when I can I will try to finish it. I closed the PR because of a failing Travis CI build (https://travis-ci.org/oshi/oshi/builds/530663006?utm_source=github_status&utm_medium=notification).

**Comment by dbwiddis** [comment]
Yeah, the >0 probably doesn't work on whatever machines/distro Travis CI runs on, thus my suggestion to make that test conditional on the existence of the sysfs paths.  (And now you know why the test was the way it was, which of course missed this bug.)

**Comment by dbwiddis** [comment]
Fixed in #857
