### ISSUE TITLE
Windows platform  error

### ISSUE THREAD

**Issue by ruanzy** [oshi/oshi#862]
Could not initialize class oshi.hardware.platform.windows.WindowsCentralProcessor

**Comment by dbwiddis** [comment]
This may be related to your versioning, I commented in #863

**Comment by HadesFX** [comment]
using maven ,OSHI version 5.6.0 and JNA version 5.7.0, it can cause this problem,can you help me,thanks

**Comment by dbwiddis** [comment]
Please open a new issue and post the full stack trace and any log errors you have.
