### ISSUE TITLE
java.lang.NoSuchMethodError: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;)Lcom/sun/jna/Library;

### ISSUE THREAD

**Issue by ruanzy** [oshi/oshi#863]

**Comment by dbwiddis** [comment]
You probably have the wrong version of JNA as a dependency. Are you using Maven?  What versions of OSHI and JNA are you using?

**Comment by HadesFX** [comment]
using maven ,OSHI version 5.6.0 and JNA version 5.7.0, it can cause this problem,can you help,thanks

**Comment by dbwiddis** [comment]
Please post a new issue.
