### ISSUE TITLE
Map Intel Processor Identifier to CPU name

### ISSUE THREAD

**Issue by Sami32** [oshi/oshi#865]
https://github.com/hirschmann/nbfc/blob/master/Core/Plugins/OpenHardwareMonitor/Hardware/CPU/IntelCPU.cs

As it is my wondering day ;-)
That could be only me, but having a name like "Haswell" for an Intel CPU, for example, wouldn't be more easily readable?

https://github.com/hirschmann/nbfc/tree/master/Core/Plugins/OpenHardwareMonitor/Hardware/CPU

**Comment by Sami32** [comment]
It came to my mind because of this documentation for hardware acceleration:

https://en.m.wikipedia.org/wiki/Intel_Quick_Sync_Video#Hardware_decoding_and_encoding

**Comment by dbwiddis** [comment]
This looks like a good add-in to toss into the `oshi-demo` project, as it appears the naming can be done by parsing the processor identifier.  It's similar to the "is this a VM" method.

Note you can't just port the code directly over, as it's MPL.  So we'd have to independently write the source code based on [other documentation](https://software.intel.com/en-us/articles/intel-architecture-and-processor-identification-with-cpuid-model-and-family-numbers).

Feel free to contribute!

**Comment by tbradellis** [comment]
I can work this one.  Looking at the links above I'm not seeing where microarchitecture codename is actually stored as part of CPU info. Does this imply that we'd want to maintain a lookup based on  the full model string?  Or, am I overlooking  something.  I think I can run with this if I get pointed in the right direction.

**Comment by dbwiddis** [comment]
The way I thought to do it was to map the appropriate bits of the Processor ID to the processor using the tables at [this link](https://software.intel.com/en-us/articles/intel-architecture-and-processor-identification-with-cpuid-model-and-family-numbers) (you'd need to hard code the lookup).

Actually, we're not guaranteed the endianness of the Processor ID so it'd be better to use the `getFamily()` and `getModel()` fields.

**Comment by dbwiddis** [comment]
Actually the Intel link in the previous comment looks a bit dated.  [Here's another option](https://en.wikichip.org/wiki/intel/cpuid).

**Comment by tbradellis** [comment]
I should have at least a first pass at a PR this week. Had some family in from out of town this weekend so playing tour guide until tomorrow morning.

**Comment by Sami32** [comment]
For olders CPUs that are missing i found some more informations into these links:

http://www.paradicesoftware.com/specs/cpuid/  (7)
https://a4lg.com/tech/x86/database/x86-families-and-models.en.html
http://www.cpu-world.com/cgi-bin/CPUID.pl

https://github.com/pytorch/cpuinfo/blob/master/src/x86/uarch.c

**Comment by dbwiddis** [comment]
Implemented in #894
