### ISSUE TITLE
Win10 Multiple Editions(HomeEdition) not work 

### ISSUE THREAD

**Issue by only3c** [oshi/oshi#871]
I use version 3.9.1 (no other versions tried). it's doesn't work on win10 Multiple Editions(Home Edition) ，but worked on centos7 。So ，what other platform  or version of platform are not available ? Thanks

**Comment by dbwiddis** [comment]
I'd love to try to help, but "doesn't work" gives me nothing to go on. Can you be specific as to what symptoms you are seeing? Is there a stack trace or log message?  Are you seeing results that don't match what you expect?

**Comment by only3c** [comment]
> I'd love to try to help, but "doesn't work" gives me nothing to go on. Can you be specific as to what symptoms you are seeing? Is there a stack trace or log message? Are you seeing results that don't match what you expect?

SystemInfo si = new SystemInfo();  
HardwareAbstractionLayer hal = si.getHardware();

in si hardware and os are  null ,  and i get a exception  ↓

Exception in thread "main" java.lang.NoSuchMethodError: com.sun.jna.platform.win32.OleAuto.VariantClear(Lcom/sun/jna/platform/win32/Variant$VARIANT;)Lcom/sun/jna/platform/win32/WinNT$HRESULT;


Is win10 (Home edition）need  some plug-ins to install ?

**Comment by dbwiddis** [comment]
That looks like you don't have the correct JNA dependency for the OSHI version.  Make sure you include the latest `jna` and `jna-platform` dependencies.

**Comment by only3c** [comment]
No , springboot1.5.9 is already has JNA、jna-platform dependency and those version is 4.2.2，i use oshi version is 3.9.1。It's just has the problem in win10(Home edition), but  it can work normally in centos7 .
So I wonder if it has something to do with the platform.

**Comment by dbwiddis** [comment]
The problem is that the springboot dependency on the older version of JNA is taking priority over the version you are trying to include. (Or perhaps you aren't specifying the newer version and just relying on Springboot's older versions.)

Using Maven to manage your dependencies and including the most recent JNA as the first ones in the list usually solves this problem.  See #835, #681, #669, #351.

**Comment by only3c** [comment]
Thankyou so much dbwiddis ，It's about versions. I change the jna4.2.2 to 4.5.2 and it‘s working now
