### ISSUE TITLE
some classes are not in the latest version

### ISSUE THREAD

**Issue by Abu-Abdullah** [oshi/oshi#873]
hi,

im trying to run the SystemInfoTest but it seems some classes are not available any more e.g.
oshi.hardware.VirtualMemory;

also some functions are not correct e.g.

CentralProcessor.updateAttributes();
processor.getSystemCpuLoadBetweenTicks(prevTicks)
processor.getProcessorCpuLoadBetweenTicks(prevProcTicks);
processor.getMaxFreq();
processor.getCurrentFreq();

**Comment by Abu-Abdullah** [comment]
ok, it seems it is in the snapshot 4.0 version. i would suggest to put it in maven repository if documentation depends on it.

**Comment by dbwiddis** [comment]
The [API documentation](http://oshi.github.io/oshi/apidocs/) linked on the `README` is for the latest stable release, 3.12.2.  The major version number change for 4.0.0 is indicative of this lack of backward compatibility.

4.0.0 is not released, but the draft of the [`UPGRADING`](https://github.com/oshi/oshi/blob/master/UPGRADING.md) document specifies the API changes and is kept updated as new features are added.  This includes movement of the functions you've noted to the new `LogicalProcessor` and `VirtualMemory` classes.
