### ISSUE TITLE
Windows 2008 SP1 - java.lang.UnsatisfiedLinkError: Error looking up function 'WTSEnumerateProcesses

### ISSUE THREAD

**Issue by kthaya** [oshi/oshi#886]
I'm getting following exception in windows 32 2008 SP1 (working fine in 64 version):

Error looking up function 'WTSEnumerateProcessesEx'
: The specified procedure could not be found.

java.lang.UnsatisfiedLinkError: Error looking up function 'WTSEnumerateProcesses
Ex': The specified procedure could not be found.
        at com.sun.jna.Function.<init>(Function.java:252)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:594)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:570)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:556)
        at com.sun.jna.Library$Handler.invoke(Library.java:243)
        at com.sun.proxy.$Proxy7.WTSEnumerateProcessesEx(Unknown Source)
        at oshi.software.os.windows.WindowsOperatingSystem.processMapToList(WindowsOperatingSystem.java:363)
        at oshi.software.os.windows.WindowsOperatingSystem.getProcesses(WindowsOperatingSystem.java:282)
        at oshi.software.common.AbstractOperatingSystem.getProcesses(AbstractOperatingSystem.java:188)

**Comment by dbwiddis** [comment]
[WTSEnumerateProcessesEx](https://docs.microsoft.com/en-us/windows/desktop/api/wtsapi32/nf-wtsapi32-wtsenumerateprocessesexa) Requires minimum Windows 7 or Windows Server 2008 R2.

Unfortunately, the check that OSHI does is for Vista or greater.  

Git blame points the finger squarely at me for goofing this up in #735.  Surprised it wasn't caught before now!  :)

**Comment by dbwiddis** [comment]
I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to open source before. This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. :-) Here are the steps to get a PR merged here.

- [ ] Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  I'll walk you through anything you don't understand.
- [ ] Find the [WindowsOperatingSystem.java](https://github.com/oshi/oshi/blob/b6f44b68cd26a21f16558755e16f6357e63f0852/oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java#L360) class.  On line 360 there is a check for windows version Vista or greater.
- [ ] Alter this conditional to check for Windows 7 or greater.  You may want to define a new constant near [Line 103](https://github.com/oshi/oshi/blob/b6f44b68cd26a21f16558755e16f6357e63f0852/oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java#L103).   Also look over the comments below this conditional, and update where it says "Vista" to say "Windows 7"
- [ ] Fork the project, commit your changes to your fork, create a PR, and get it merged
- [ ] Celebrate

**Comment by kthaya** [comment]
Thank you for informative response. 
I have created a PR https://github.com/oshi/oshi/pull/887.

**Comment by kthaya** [comment]
We have introduced oshi to our project recently, it works nicely in all platforms except windows 2008 SP1. 
Could you please review the PR as soon as practical as we are about to release our product soon? Thank you

**Comment by dbwiddis** [comment]
It's merged and in the snapshot, but we also need to commit to the 3.12.X branch if you're wanting to link a product to it.

**Comment by kthaya** [comment]
Thank you for quick action :)
What is the process to commit in to 3.13.X? Do I need to create new PR?

**Comment by dbwiddis** [comment]
Just released 3.13.3.  Should show up on Maven in a few hours.

**Comment by kthaya** [comment]
Thank you
