### ISSUE TITLE
CentralProcessor.getSystemCpuLoad() returns -1.0 along with many other methods

### ISSUE THREAD

**Issue by ZakharchenkoWork** [oshi/oshi#898]
Environment is Win7 Ultimate SP1 x64.
CODE:
        System.out.println(""+SystemInfo.getCurrentPlatformEnum());
        CentralProcessor cpu = new SystemInfo().getHardware().getProcessor();

        System.out.println(new Gson().toJson( cpu));
        System.out.println(new Gson().toJson( cpu.getSystemCpuLoadTicks()));
        System.out.println(new Gson().toJson( cpu.getProcessorCpuLoadBetweenTicks()));
        System.out.println(new Gson().toJson( cpu.getSystemCpuLoad()));
        System.out.println(new Gson().toJson(  cpu.getSystemLoadAverage()));

OUTPUT
WINDOWS
{"lastCpuLoad":-1.0,"lastCpuLoadTime":1561231971109,"sunMXBean":true,"logicalProcessorCount":8,"physicalProcessorCount":4,"physicalPackageCount":1,"tickTime":0,"prevTicks":[0,0,0,0,0,0,0,0],"curTicks":[0,0,0,0,0,0,0,0],"procTickTime":0,"prevProcTicks":[[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0]],"curProcTicks":[[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0]],"cpuVendor":"GenuineIntel","cpuName":"Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz","processorID":"BFEBFBFF000306A9","cpuIdentifier":"Intel64 Family 6 Model 58 Stepping 9","cpu64":false}
[Thread-0] WARN oshi.util.platform.windows.PerfDataUtil - Failed to add PDH Counter: \Processor(_Total)\% DPC Time, Error code: 0xC0000BB8
[Thread-0] WARN oshi.util.platform.windows.WmiQueryHandler - COM exception: Invalid Query: SELECT PERCENTDPCTIME,PERCENTINTERRUPTTIME FROM Win32_PerfRawData_PerfOS_Processor WHERE Name="_Total"
[14704638,0,7673627,239786391,0,0,0,0]
[Thread-0] WARN oshi.util.platform.windows.WmiQueryHandler - COM exception: Invalid Query: SELECT NAME,PERCENTDPCTIME,PERCENTINTERRUPTTIME,PERCENTPRIVILEGEDTIME,PERCENTPROCESSORTIME,PERCENTUSERTIME FROM Win32_PerfRawData_PerfOS_Processor WHERE NOT Name="_Total"
[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]
-1.0
-1.0

Is it because of Win7 ? Or it is a code? I just  have to be shure it will work on remote production server))))

**Comment by dbwiddis** [comment]
CPU load is expected, as Windows doesn’t have that.  Lack of ticks is a problem though. Can you see that counter in perfmon.exe?

**Comment by ZakharchenkoWork** [comment]
Well on the start of perfmon it gives me errors about missing counters for:
\Memory\Available MBytes
\Memory\% Committed Bytes In Use
\Memory\Cache Faults/sec
\Memory\Cache Faults/sec
\PhysicalDisk(*)\% Idle Time
\PhysicalDisk(*)\Avg. Disk Queue Length
\Network Interface(*)\Bytes Total/sec

But for CPU usage the data is shown, Can you specify how/where/what info i should look for in perfmon?

**Comment by dbwiddis** [comment]
The Processor counter, % time for various inputs matching the error messages

**Comment by dbwiddis** [comment]
Hi, @ZakharchenkoWork. Have you been able to do any more troubleshooting on this?   The lack of so many counters implies some very odd configuration....

**Comment by dbwiddis** [comment]
Hi, @ZakharchenkoWork ... haven't heard from you on this issue.   I will repeat the note that "Load Average" is a *nix term and is not defined on Windows, so the -1 is as expected there; but the remainder of the issues appear to be primarily a configuration issue with your machine, impacting all your performance counters.  Feel free to re-open this issue if you need more help from the project.
