### ISSUE TITLE
Possible memory leak in LinuxDisks?

### ISSUE THREAD

**Issue by cilki** [oshi/oshi#905]
I noticed a few things in `LinuxDisks` as I was doing my design work (hope to have a PR by the end of the month for that). Let me know if the following should be fixed.

- Only one of the calls to `*_unref` in `LinuxDisks` is protected by a try-finally. If something happens in `computeDiskStats`, for example, then this line won't decrement the reference count:
https://github.com/oshi/oshi/blob/c8930dc2c05204e598912c87fcde410d72ae37ed/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxDisks.java#L190
Every call to `udev_unref` and `udev_enumerate_unref` are also outside of try-finally blocks.

- Also, this catch clause seems to be handling control flow :-1:: https://github.com/oshi/oshi/blob/c8930dc2c05204e598912c87fcde410d72ae37ed/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxDisks.java#L163
This is superficial, but it would be nicer to do `if (device == null) break;` in the loop.

**Comment by dbwiddis** [comment]
Regarding line 190, I don't see a leak.  The unref is inside a conditional test on `device != null`.  If `device` is null, then the original reference failed and there's no way to unreference it.  

I do agree the line 163 clause is bad, for reasons outlined in Sonar squid S1166. :D   It should use a null check just like the line 190 one.

**Comment by cilki** [comment]
I guess it's not possible for `computeDiskStats` to throw since `parseStringToLongArray` defaults to zeros if there's an error. I've mostly been deferring the whole "throw vs default" issue until a later time.
