### ISSUE TITLE
OSHI 4.1.0 New Features

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#935]
I've taken a look at a lot of the outstanding issues/feature requests and think there's room to put them into a version 4.1.0.   Opening this issue to track the requests and solicit help from contributors old and new.  I'm adding the `first-timers-only` tag here just in case some new contributors want to wade into a slightly more challenging project -- happy to hand-hold new users through any of these.

- [x] Get Services.  Level of difficulty:  4/10.  This is discussed in #257 and easily implemented on Windows and I think we can do a reasonable implementation on other OS's.  Will be a method on `OperatingSystem` similar to `getProcesses()` but will return a new `OSService` object to be defined later.  Will include a PID, and a status (running/stopped), possibly other fields.
- (Moved to 4.2.0) More battery information.    Level of difficulty: 3/10.   Most of this has been outlined in #306.  Just add more fields to the existing PowerSource class.
- [x] Memory speed.  Level of difficulty 2/10.  Should be an easy addition to the `GlobalMemory` class, hints in #419

**Comment by agithyogendra** [comment]
I would like to work on Get Services

**Comment by dbwiddis** [comment]
Excellent!   This will take a bit of design work up front to identify what attributes you want in the class and how to get them cross-platform.  Please continue discussion on #257.

**Comment by colinbobolin** [comment]
Thanks again @dbwiddis for opening this up to newer contributors. I'll pick up and dig into _More battery information_ since I just finished the PowerSource.toString method.

**Comment by dbwiddis** [comment]
Great, @colinbobolin!  Thanks for stepping up to another challenge!

**Comment by phillips0616** [comment]
If no one has claimed it I would like to work on memory speed and incorporating it into the GlobalMemory class.

**Comment by dbwiddis** [comment]
Sweet, @phillips0616, that would be awesome! It's yours!

**Comment by dbwiddis** [comment]
Hi there, @phillips0616 ... are you working on the Memory Speed issue?  No rush if you're making progress, but if you want to back out, there are others who are looking for something to do!

**Comment by colinbobolin** [comment]
If someone else wants to pick up the battery info feature, I'm getting backed up between work and school and I'm struggling to find time. I'll work on it when I can find time, but if someone wants to take over it might get done sooner.

**Comment by dbwiddis** [comment]
Thanks for trying, @colinbobolin !

**Comment by rohitkukreja1508** [comment]
Are any items here open for contribution?

**Comment by dbwiddis** [comment]
Nobody's working on the Battery info in #306.  I had [just started working](https://github.com/dbwiddis/oshi/tree/physical-memory) on a `PhysicalMemory` class to support #419 as well but haven't done any of the inidivdual class implementations and would be happy to turn that over to someone.

**Comment by rohitkukreja1508** [comment]
I would like to work on #419. By individual class implementations, you meant for this to be implemented on different platforms, right?

**Comment by dbwiddis** [comment]
Yes, the OS implementations.  Updates of the WindowsGlobalMemory, MacGlobalMemory, etc. to return an array of PhysicalMemory objects with the info.

**Comment by minhtran83** [comment]
@dbwiddis Sorry i can't find any release plan page. So i put a comment here. Do you have a clear date for bug fix 4.0.1 cutting from master branch? Thanks, Minh

**Comment by dbwiddis** [comment]
I do not have a specific date planned, as I was hoping for the next JNA release to come out first.  It's been about 3 months since 5.4.0, which was released about 3 months after 5.3.0 so I'm hopeful that's relatively soon.  And I want the submitters of #419 and #257 to be able to finish their PRs without being rushed.

I also have made numerous updates across nearly all classes in support of thread safety and haven't had time to fully test them all on all OS's.  I'm hopeful that I can get to that in the next few weeks.

Is there a specific need for an updated "stable" release of the 4.X branch?

**Comment by minhtran83** [comment]
Thanks for your prompt response @dbwiddis. I much appreciated.
Our product Confluence Server is waiting for the fix of [#974](https://github.com/oshi/oshi/issues/974) and [#1001](https://github.com/oshi/oshi/issues/1001)

We don't have special needs. We found you cut `3.13.4`, so we have thought the same for `4.0.x`

Do you have the testing notes for those changes? I am happy to test that on my Mac OS + Linux VM

**Comment by dbwiddis** [comment]
Gotcha.  I'll try to get 4.1.0 out by the end of the month.

As for testing, no test notes.  Running all the tests in the test suite should suffice, as well as running SystemInfoTest (which running all tests accomplishes, actually) and inspecting the output visually for anything strange, the most likely problem being a copypaste error or unchecked null.

I have and regularly test on Windows 10 and Mac machines, and a Win7 and Ubuntu VM. If you have a non-Debian Linux distribution that would be helpful to test on.   I have FreeBSD and Solaris VMs as well but they don't integrate with my code as seamlessly so I tend to put off thorough testing until before a release.
