### ISSUE TITLE
Move 'oraclejdk8' build to 'openjdk8' due to xenial migration on travis

### ISSUE THREAD

**Issue by hazendaz** [oshi/oshi#940]
The xenial migration on travis is being done in waves.  As a result, 'oraclejdk8' was going to start failing.  This has to due to license issues with older jdk and the underlying script used to retrieve the jdk that cannot get the oracle jdk 8 version.  The only change necessary is to switch to openjdk.

**Comment by hazendaz** [comment]
Note: this hasn't hit 'oshi' directly yet.  I picked this up off a branch of mine on my fork that just started occurring.  I suspect 'oshi' will see this soon enough.

**Comment by hazendaz** [comment]
@dbwiddis 

I'm a bit confused on what I saw here.  I have a branch I called 'wip' for work in progress on my fork.  While the travis file states it should be using mac, it decided to not use mac for some reason with this output.  This is what indicated to me xenial migration which it states on my fork as using xenial.  However, the mac version wouldn't be this anyways.  Under what situation if any do you think this would try to use linux rather than mac?  I still believe moving off Oracle is a good thing in general so I'm raising a PR for that but not so sure how I caused this...


JDK: oraclejdk8 Java
JDK = "Oracle JDK 8 - Linux" MATRIX_ID="first"

**Comment by dbwiddis** [comment]
I’ve already switched all the tests to OpenJDK except the java 8 Mac tests, but they use an Xcode image that does not require any downloading.

**Comment by dbwiddis** [comment]
We used to do Oracle Linux but they started failing a few months ago, likely for the reason you indicated.

**Comment by hazendaz** [comment]
Found my issue...I was on an old commit line. I had rebased locally but not on the remote for my transient branch.  So I was still using the old setup.

I'm closing this for now.  While not using Oracle is still a plus, this was invalid.  Sorry for the noise.

**Comment by dbwiddis** [comment]
No worries.  I can’t even get Java 8 on Linux any more, and I am using the latest Xcode build with Java (which uses HotSpot), 9.3. https://docs.travis-ci.com/user/reference/osx/

**Comment by hazendaz** [comment]
I reworked the travis ci builds.  I'm bringing in a pull request shortly which should help shine light on the issue.  The xcode 9.3 is using the one on the box which is oracle.  I have all the others using standard procedure now.  The install jdk has long since been part of travis directly.  It's also pretty clear what its doing in the output.  The prior set here anyways used the box default for all the Mac versions and was only getting the external for linux.  Now it will get external for all except the jdk 8 need which will remain local.
