### ISSUE TITLE
about cpu info

### ISSUE THREAD

**Issue by tiantangbuyaowo** [oshi/oshi#951]
My machine has eight cpus. I want to get the performance data of each cpu. Does the API support it?

**Comment by dbwiddis** [comment]
Yes, the `CentralProcessor` class returns CPU ticks on a per-logical-processor basis.  You can measure the difference in ticks over time to get usage per processor.

See the [SystemInfoTest](https://github.com/oshi/oshi/blob/a67748eedfbd64af1a75a931d30fb848346da693/oshi-core/src/test/java/oshi/SystemInfoTest.java#L174) class for example calculations.

**Comment by dbwiddis** [comment]
I think I've answered this question, so I'll close this issue.  Feel free to reopen it if you need more help.
