### ISSUE TITLE
Overload methods should not be split

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#954]
[CodeFactor](https://www.codefactor.io/repository/github/oshi/oshi) found an issue: Overload methods should not be split. Previous overloaded method located at line &#39;308&#39;.

It's currently on:
[oshi-core\src\main\java\oshi\software\os\windows\WindowsOperatingSystem.java:350
](https://www.codefactor.io/repository/github/oshi/oshi/source/master/oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java#L350)

**Comment by dbwiddis** [comment]
Several of these issues, actually:  https://www.codefactor.io/repository/github/oshi/oshi/issues/master?category=Style&groupId=787

Simple cut/paste to move the overloaded methods together.

**Comment by rhu2001** [comment]
I'd like a go at this one!

**Comment by dbwiddis** [comment]
Looks like you're on it!
