### ISSUE TITLE
Fix 2 Style issues in multiple files

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#955]
[CodeFactor](https://www.codefactor.io/repository/github/oshi/oshi/overview/master) found multiple issues:

#### Should use uppercase &#39;L&#39;.
[oshi-core\src\main\java\oshi\hardware\platform\linux\LinuxGlobalMemory.java:162
](https://www.codefactor.io/repository/github/oshi/oshi/source/master/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxGlobalMemory.java#L162)[oshi-core\src\main\java\oshi\hardware\platform\linux\LinuxVirtualMemory.java:128
](https://www.codefactor.io/repository/github/oshi/oshi/source/master/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxVirtualMemory.java#L128)

**Comment by dbwiddis** [comment]
I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to open source before. This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. :-) 

There are two instances in the code where a lowercase L is used to denote a `long`.  This produces readability issues because it is easily mistaken as a 1.

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- FInd the two places in the code where the lowercase `l` is used, as linked in the first comment.  Change them to uppercase `L`.
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

**Comment by ektaarora3501** [comment]
Can I work on this issue?

**Comment by dbwiddis** [comment]
It's yours, @ektaarora3501 !

**Comment by ektaarora3501** [comment]
Sir to  correct the return statement from 0l to 0L , is this what is required in the two files?

**Comment by dbwiddis** [comment]
Yes, just change the `return 0l;` to read `return 0L;`
