### ISSUE TITLE
OSProcess constructor with PID

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#957]
Add the capability to construct a new process object given a pid:  `new OSProcess(pid)`.

Steps to implement:
1. Write a new constructor that takes a pid as an argument, sets the `processID` attribute, and calls an `updateAttributes()` method. 
2. Write a new public `updateAttributes()` method which calls the platform-specific `getProcess(this.processId)` and then copies all the values from the return value OSProcess to the class attributes.  You'll have to switch based on `SystemInfo.getCurrentPlatformEnum()`.

**Comment by Potat0x** [comment]
Hello, I will work on it.

**Comment by dbwiddis** [comment]
Thanks @Potat0x !
