### ISSUE TITLE
Move the ProcessorIdentifier inner class to the CentralProcessor class

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#963]
As part of refactoring in #959, I created a new `ProcessorIdentifier` class inside the `AbstractCentralProcessor`.  I think this class should become part of the API.

Steps to implement:
- Move the `ProcessorIdentifier` class to the `CentralProcessor` interface and change its access to `public`.
- Add getters for the fields.  Include javadocs, which you may be able to just copy from where they already exist in `CentralProcessor` (this is their new home)
- Create a new getter `getProcessorIdentifier()` in the `CentralProcessor` interface, implemented in the `AbstractCentralProcessor` class, that returns the instance of this class (`cpuid.get()`).
- Update the existing getters for the fields on this class from direct access of the private fields, to access using the getters.  e.g., change `cpuid.get().cpuName` to `cpuid.get().getName()`.  Better yet, `getProcessorIdentifier().getName()`
- Mark the existing getters on the `CentralProcessor` class (that you just updated) as deprecated, referencing the new class and methods.

**Comment by Praveen101997** [comment]
@dbwiddis  I can't able to find class ProcessorInformation in AbstarctCentralProcessor instead of which I found ProcessorIdentifier Class in it

**Comment by dbwiddis** [comment]
Sorry, was typing from memory. That's the one!

**Comment by Praveen101997** [comment]
@dbwiddis I pull request after changes
But not sure I am doing correctly or not
