### ISSUE TITLE
Apparent Handle leak in WindowsOSSystemInfo#init

### ISSUE THREAD

**Issue by UnAfraid** [oshi/oshi#973]
Hello,

As the title says there is handle leak in class WindowsOSSystemInfo method init()
https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/software/os/windows/WindowsOSSystemInfo.java#L69
```java
...
            IntByReference isWow64 = new IntByReference();
            HANDLE hProcess = Kernel32.INSTANCE.GetCurrentProcess();
            if (Kernel32.INSTANCE.IsWow64Process(hProcess, isWow64) && isWow64.getValue() > 0) {
                Kernel32.INSTANCE.GetNativeSystemInfo(si);
            }
...
```
This handle `hProcess` is allocated and never closed

**Comment by UnAfraid** [comment]
I went on handle leak hunt because i notice my application had open nearly 5000 handles and that is way above what it should be using, fixed everything i found on my code and while i was at it decided to look even at dependencies and thats how i spotted those two, yeah that one may be fake/pseudo handle i'll try to make a PR soon to add comment there.

**Comment by dbwiddis** [comment]
Added the comment in a15ff0a523e8837e65dcc8d93439b17c2f08b0c7 .
