### ISSUE TITLE
default.properties resource file would conflict with other libraries

### ISSUE THREAD

**Issue by nosferaty** [oshi/oshi#974]
In 4.0.0, a new resource file "default.properties" was introduced.
The problem is that the same file would exist in other libs, so we do not know which one will be loaded when we try to get "default.properties" resource.
For example, if an application contains both Felix and Oshi libraries, it crashes on start sometimes (because a random "default.properties" resource file is loaded).
I reckon there could be other libraries with "default.properties" file inside. Renaming this file (for example, with "oshi.properties") will prevent possible conflicts with any other libraries.

**Comment by cilki** [comment]
Yeah I agree with this. We could handle this situation properly, but other libraries may not. `oshi.properties`, `oshi.default.properties`, or `oshi.properties.default` all sound good to me.

In the future it would be nice to have a `module-info.java` that prevents access to our internal resources.

**Comment by dbwiddis** [comment]
I'm not opposed to renaming, but I'm curious why there is a crash on start with some libraries?   If OSHI doesn't find the configurations it wants in a file from another lib it should just ignore it.  What program is crashing?  Is it not possible to have a single default.properties with configuration for multiple applications?

**Comment by cilki** [comment]
There's a chance that another library could receive OSHI's configuration instead of their own if they don't handle multiple files on the classpath with the same name. This could probably lead to a crash.

**Comment by dbwiddis** [comment]
Gotcha.   We should definitely either rename it or move it into a subfolder.  Or delete it from the distribution since it's mostly just an example that people should add to their own configs.

**Comment by cilki** [comment]
Well we still need it in binary, so I think renaming is the right thing to do. If another library includes an  `oshi.properties`, then that's their problem. The only question now is what unique name we should choose.

**Comment by dbwiddis** [comment]
How about `oshi.properties`? :) . Or `oshi.config`.

**Comment by cilki** [comment]
I'll do the rename and maybe emit a warning if multiple `oshi.properties` are found.

**Comment by nosferaty** [comment]
Thanks a lot for resolving it! :+1:
