### ISSUE TITLE
Physical Disk Info to File System Mapping

### ISSUE THREAD

**Issue by aerturk** [oshi/oshi#975]
Currently, physical disk information cannot be mapped to file system information. It will be good if we can get file system information for a physical disk so that we can also find which physical disk contains the OS.

**Comment by dbwiddis** [comment]
This is possible to do via the mount point.  A (physical) `HWDiskStore` has `HWPartition`s, which each have a [`getMountPoint()`](http://oshi.github.io/oshi/apidocs/oshi/hardware/HWPartition.html#getMountPoint--) method.

This mount point corresponds to the `OSFileStore` method [`getMount()`](http://oshi.github.io/oshi/apidocs/oshi/software/os/OSFileStore.html#getMount--)

**Comment by dbwiddis** [comment]
Closing this as I believe I've answered the question.  Feel free to reopen if you think there's something else that should be done.  See also [this relevant StackOverflow answer](url).

**Comment by dbwiddis** [comment]
Since this has been asked a few times, I just wrote a class in `oshi-demo` that does this mapping.
