### ISSUE TITLE
Get Physical Network Interfaces

### ISSUE THREAD

**Issue by aerturk** [oshi/oshi#976]
OS creates many virtual network interfaces if there is virtualization installed and running like Hyper-V or VirtualBox. If we can get which network interface is a real physical device it will be helpful for real device detection. As an example, the following is printed by SystemInfoText.java when run on one of our windows laptop. eth2 and wlan0 are physical network interfaces however there are hyper-v running and virtual interfaces bridged physical interfaces.

> Network Interfaces:
>  Name: eth2 (Realtek PCIe GBE Family Controller)
>   MAC Address: ac:e2:d3:62:82:25
>   MTU: 1500, Speed: 0
>   IPv4: []
>   IPv6: [fe80:0:0:0:adbf:fe75:f996:453c]
>   Traffic: received 0 packets/0 bytes (0 err); transmitted 0 packets/0 bytes (0 err)
>  Name: wlan0 (Microsoft Wi-Fi Direct Virtual Adapter #2)
>   MAC Address: fa:94:c2:5f:53:21
>   MTU: 1500, Speed: 0
>   IPv4: []
>   IPv6: [fe80:0:0:0:994b:5410:41d0:f24d]
>   Traffic: received 0 packets/0 bytes (0 err); transmitted 0 packets/0 bytes (0 err)
>  Name: wlan1 (Microsoft Wi-Fi Direct Virtual Adapter)
>   MAC Address: f8:34:c2:5f:26:45
>   MTU: 1500, Speed: 0
>   IPv4: []
>   IPv6: [fe80:0:0:0:7028:ae50:780f:1c2a]
>   Traffic: received 0 packets/0 bytes (0 err); transmitted 0 packets/0 bytes (0 err)
>  Name: eth6 (Hyper-V Virtual Ethernet Adapter #3)
>   MAC Address: 00:65:5d:58:12:60
>   MTU: 1500, Speed: 10000000000
>   IPv4: [172.16.1.1]
>   IPv6: [fe80:0:0:0:453:21d:d945:ddf3]
>   Traffic: received 0 packets/0 bytes (0 err); transmitted 0 packets/3.1 MiB (0 err)
>  Name: eth11 (Hyper-V Virtual Ethernet Adapter #2)
>   MAC Address: f8:94:c2:af:31:2e
>   MTU: 1500, Speed: 292500000
>   IPv4: [192.168.1.21]
>   IPv6: [fe80:0:0:0:6146:faaf:3f19:d34d]
>   Traffic: received 8418276 packets/9.3 GiB (0 err); transmitted 5595535 packets/673.9 MiB (0 err)
>  Name: eth13 (Hyper-V Virtual Ethernet Adapter)
>   MAC Address: 00:15:5d:23:4c:50
>   MTU: 1500, Speed: 10000000000
>   IPv4: [172.18.70.17]
>   IPv6: [fe80:0:0:0:2d8f:207b:1ea6:ab5]
>   Traffic: received 0 packets/0 bytes (0 err); transmitted 0 packets/2.3 MiB (0 err)

**Comment by dbwiddis** [comment]
This is an interesting request, but I'm not sure there's an easy solution.  Do you know how, programmatically, to detect whether an interface is physical or virtual?  

And if you are inside a virtual machine, your interface is by definition virtual but you would like it to act as a physical one.

**Comment by aerturk** [comment]
There are some useful information for windows on page https://weblogs.sqlteam.com/mladenp/2010/11/04/find-only-physical-network-adapters-with-wmi-win32_networkadapter-class/ 

In short, the following query returns only physical network interfaces on a physical system (I think virtual systems can be omitted because everything is virtual. When the following is run on a virtual windows, it returns nothing).
`Get-WmiObject -Query  "SELECT * FROM Win32_NetworkAdapter WHERE Manufacturer != 'Microsoft' AND NOT PNPDeviceID LIKE 'ROOT\\%'" | Sort index`

**Comment by dbwiddis** [comment]
If we're using `Win32_NetworkAdapter` why not just use the `PhysicalAdapter` boolean?

We also need to find the equivalent cross-platform test.  Linux `sys` filesystem path checking the device tree seems an option.   Not sure about macOS.

One cross-platform test I keep seeing repeatedly has to do with testing DNS on each interface, 

I'm okay with adding some sort of test, e.g., `isPhysicalAdapter()` to enable filtering.  But a significant number of OSHI users are employing it on cloud servers which are nearly always virtual, so a default filtering of the list to physical-only is not an option.

Open to a PR to add an `isPhysicalAdapter` (or other similar name) method, but consider this mostly a user-preference thing and am not likely to code this myself.

**Comment by hrokholskyi** [comment]
Hopefully this might help?

https://unix.stackexchange.com/questions/432245/how-to-get-only-the-name-of-the-physical-ethernet-interface

The feature is really usefull, woulde be great to have!

**Comment by dbwiddis** [comment]
Feel free to write up a PR!

**Comment by dbwiddis** [comment]
OK, I took a look at implementing this tonight, and I don't think the requirement is well specified, nor the solutions presented (for Windows and Mac) very consistent, and I think the code is already there to produce the desired results.

For example, my Parallels VM running Windows would pass the "physical" test given above (Manufacturer is "Intel" and PnPDeviceID starts with "PCI").  It also has the "PhysicalAdapter" boolean set true in that same WMI table, and its type (another test I've seen) is the Ethernet adapter.  Basically, I'm running a Mac, but the virtualization software is doing its best to pretend that its network adapter is a physical one. 

Similarly on my Ubuntu VM, the "physical" interface is in the `/sys/devices/pci0000:00` tree.  There's a hint it's virtual further down the path with a `virtio` subdirectory but it's not in the more obvious `/sys/devices/virtual` area.  Again, the conclusion is that Parallels is presenting the virtual port to the OS as if it were real.

The one test that is a giveaway in both cases: the "physical" networks MAC address begins with 00:1c:42.  This MAC address test is the same test that we use in the `oshi-demo` project's `DetectVM` class already.  Basically something like this should answer the original request:
```
    public static boolean isVirtualInterface(NetworkIF netIF) {
        // Rule out interfaces core Java thinks are virtual
        if (!netIF.queryNetworkInterface().isVirtual()) {
            return false;            
        }
        // Physical if it's not a known VM Mac address
        if (Util.isBlank(DetectVM.findOuiByMacAddressIfPossible(netIF.getMacaddr()))) {
            return true;
        }
        return false;
    }
```
I'm willing to entertain moving this VM detection class from `oshi-demo` into an `oshi-core` Util class to make this check easier, but I'm not sure there's much more I can or should code on this.

**Comment by dbwiddis** [comment]
Hmm. Maybe there is something I can easily do on Windows... a little more research uncovers some information in the [`MIB_IF_ROW2`](https://docs.microsoft.com/en-us/windows/win32/api/netioapi/ns-netioapi-mib_if_row2) structure we use on Windows.  I had already found the `Type` field which when set to `IF_TYPE_ETHERNET_CSMACD` (6) would be one clue.  It looks like combining that with the `ConnectorPresent` bit (in the `InterfaceAndOperStatusFlags`) and a `PhysicalMediumType` of `NdisPhysicalMedium802_3` (14) or the unspecified value (0) is another filter. 

Lots of hoops to jump through, but I think I can make an `isPhysicalAdapter()` method on Windows using these specifications.  It still might not catch VM adapters which are intentionally made to look physical, but hopefully the MAC address check can help there.

**Comment by hmirheydari** [comment]
> 

I have run `Get-WmiObject -Query  "SELECT * FROM Win32_NetworkAdapter WHERE Manufacturer != 'Microsoft' AND NOT PNPDeviceID LIKE 'ROOT\\%'" | Sort index` on an Amazon EC2 instance and the result was as below:
`ServiceName      : xennet
MACAddress       : 06:CF:80:E7:D3:84
AdapterType      : Ethernet 802.3
DeviceID         : 2
Name             : AWS PV Network Device #0
NetworkAddresses :
Speed            : 1000000000`

and you know that all EC2 instances are virtual.

**Comment by dbwiddis** [comment]
The fact that the MAC address isn't associated with a known manufacturer (and is probably random) is definitely a hint at virtual. :)
