### ISSUE TITLE
HWDiskStore contains wrong values if kernel is >= 4.18

### ISSUE THREAD

**Issue by Space2Man** [oshi/oshi#982]
Hi, according to [https://www.kernel.org/doc/Documentation/ABI/testing/procfs-diskstats](https://www.kernel.org/doc/Documentation/ABI/testing/procfs-diskstats) kernel 4.18+ contains 4 additional fields to log trim informations. Is OSHI counting from the end since the value for reads (field 4 in /proc/diskstats) now contains the value for writes (field 8 in /proc/diskstats).

Best regards,

   Space

**Comment by dbwiddis** [comment]
OSHI does not read `/proc/diskstats`, but rather obtains that information from Udev.  Is Udev reporting the wrong info?

**Comment by dbwiddis** [comment]
I believe udev returns the contents of [this stat file](https://www.kernel.org/doc/Documentation/block/stat.txt).   I don't see in the documentation where it has changed to match `/proc/diskstats` but it may have.  OSHI does count "from the end" assuming exactly 11 values.

**Comment by dbwiddis** [comment]
OK, [according to this link](https://www.kernel.org/doc/html/latest/admin-guide/iostats.html), both `/proc/diskstats` and the sysfs (where udev reads) get the data from the same source, so we'll have to count fields...

**Comment by dbwiddis** [comment]
I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to open source before. This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. :-) 

Per the report above, Linux kernels 4.18+ have 15 fields in `/proc/diskstats` and its `sysfs` counterpart, while OSHI assumes a hardcoded value of 11.  We need to update OSHI to perform a one-time read of this file to determine its format.

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- Find the [LinuxDisks](https://github.com/oshi/oshi/blob/05b143dd0dd2485cabc1bebc14d8b710ceef1da2/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxDisks.java#L83) class where the `UDEV_STAT_LENGTH` field is defined on line 83.
- Remove the `= 11;` assignment. Instead, immediately follow that declaration with a `static { }` block. Inside the static block:
  - perform a one-time read of the first line of `/proc/diskstats`.  [Sample output here](https://github.com/prometheus/node_exporter/issues/1049#issuecomment-414081963).  Suggested code:
    `String stat = FileUtil.getStringFromFile(ProcUtil.getProcPath() + "/diskstats");`
  - count the number of whitespace-delimited elements following any non-numeric element.
    - One option is to iterate the string by characters (using `charAt()`), counting spaces.  (Note the first part of the string has multiple consecutive spaces.)  If you start from the end of the string and iterate backwards you can stop when you hit a non-space/non-digit (and decrement that extra space you counted).
    - Another option is to use a regexp.  This is left as an exercise for the reader.
    - If you have a better idea, feel free to use it!
    - Your result should be either 11 or 15.  Assign that value to `UDEV_STAT_LENGTH`.
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

**Comment by dbwiddis** [comment]
I'll just go ahead and fix this since there doesn't seem to be a bevy of first-timers wanting to do it!

**Comment by Space2Man** [comment]
Hi dbwiddis,

thanks for the quick update as usual ... what are the chances to backport this fix into the 3.13.x stream?

Thanks,

    Space

**Comment by dbwiddis** [comment]
Should be an easy fix to backport.  I'll check if any of the other recent changes can also be updated.
