### ISSUE TITLE
Update 3.13.X branch

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#985]
Update the 3.13.X branch with the following commits from master and cut a new release:
- [x] 161a0bfbc68a62f2507fe2380ed5a9e5d1027798
- [x] 453014881f97e9c9b22a7a4b13061d3b091bbe51
- [x] a1fd74e2df7ce143db5c572a3c2beb7940deb28c
- [x] faf0bf757f4a65c2af016e6c3ae7fe1d98a40fce
- [x] bf69c90182cdc8d9b591416c44edba1dad0cbdc5
- [x] ba0148e172abab17063c0072241ea904b5e85297
- [x] 49b3ca3c30adce4828abf2a67d4afbdc52a110a8
- [x] f82cbb0da9cdee23a8212edbdf03a66440399421
- [x] fd2dc9870ea62b62e6d28e39e13818ce952acab7
- [x] 77c5e023a574d6325cea7b4a73f06479c6b8533f

**Comment by Space2Man** [comment]
Thanks man! Highly appreciated ... I will test on Monday! :)

**Comment by dbwiddis** [comment]
Hope it tests fine as I already released 3.13.4. :)

**Comment by Space2Man** [comment]
Looking good so far! Thanks! :)
