### ISSUE TITLE
OSProcess calculateCpuPercent() seems to return problematic values (OSHI 4.1)

### ISSUE THREAD

**Issue by kohnvize** [oshi/oshi#994]
Running a test whereby I have multiple threads running infinite loops in the background in order to max my machine CPU utilization at 100%, I poll the OS processes every five seconds. Using the code from the SystemInfoTest class, I get output which looks like this:
TOP TEN PROCESSES IN ORDER OF UTILIZATION: 
   ```
      PID  %CPU %MEM    VSZ           RSS   Name
       0  7.6     0.0        8 KiB         8 KiB Idle
 14728  7.4     0.0     1.8 GiB 316.6 MiB javaw
  4648  0.2     0.0 335.6 MiB     6.5 MiB SnippingTool
       4  0.1     0.0   10.8 MiB       20 KiB System
  1584  0.1     0.0 771.4 MiB  222.5 MiB dwm
   3616  0.0     0.1 467.1 MiB      1.5 GiB eclipse
   7752  0.0     0.0      2.1 GiB  199.6 MiB OUTLOOK
   3304  0.0     0.0  170.5 MiB     9.3 MiB audiodg
 10472  0.0     0.0       1.1 GiB      55 MiB Teams
 13092  0.0     0.0   379.1 MiB    6.1 MiB ptoneclk
```

Here's what Windows Task Manager looks like at the same time:
![image](https://user-images.githubusercontent.com/42816761/65155336-1e4ea500-d9fb-11e9-81d9-9db058c04f8e.png)

At various times, Task Manager (TM) shows javaw.exe at 94.9 to 98.1%, but javaw.exe from the OSProcess doesn't go above 7.5. Seperately, why is it 7.5? If it is a decimal percentage and I multiple by 100, it would be 750...that certainly isn't correct either. Please help. Thank you.

**Comment by dbwiddis** [comment]
The value you see output from `SystemInfoTest` is intended to show similarly to the `ps` command on *nix machines, which is the average %CPU over the lifetime of the process:
> CPU usage is currently expressed as the percentage of time spent running during the entire lifetime of a process.  This is not ideal, and it does not conform to the standards that ps otherwise conforms to. 

The calculation for the value you see is `100d * (p.getKernelTime() + p.getUserTime()) / p.getUpTime()`.

If you wish to track "real time" utilization over the polling interval (like the Task Manager) you'd need to store the three values above and then calculate the tick difference / time difference.  You should get results closer to 100% (or possibly up to 100% x # of processors).

Note that on Windows, all 3 of these counters increment in 1/64th of a second ticks (16 ms) so you might see unusual results with very short polling intervals.  Your 5-second intervals are probably sufficient to average out the noise.

**Comment by dbwiddis** [comment]
One other note, when comparing OSHI's values to the Windows Task Manager.  Windows scales by # of processors so that it will max out at 100%.  In a 2-core system with only one thread maxed out, it would read 50%, while OSHI's process time (kernel+user) should closely approximate uptime (100%).  With 2 maxed-out threads Task manager should be closer to 100% and OSHI's calculation (using the difference measured from a previous polling interval) should calculate to about 200%.

**Comment by dbwiddis** [comment]
I took a look at this again, after realizing that the "Idle" process should be taking a lot more than it is.  Assuming relatively low utilization (other than when running your test) the idle process should be something closer to 90% x # of processors.  But it's 7.5%, the same order of magnitude as your 90%-usage process.

So either your kernel + user process times are being under-reported, or your up time is being over-reported.  Without knowing more details of these individual components it's hard to troubleshoot further.  

Kernel and User times come from [WTS_PROCESS_INFO_EX](https://docs.microsoft.com/en-us/windows/win32/api/wtsapi32/ns-wtsapi32-wts_process_info_exa) which is interesting because the documentation states the units are "milliseconds" but they appear on my machine to be 100-ns.   I wonder if this changed in a recent version of Windows.

Uptime comes from the registry (HKEY_PERFORMANCE_DATA) and is a bit more complex to figure out what's wrong with it, if anything.  

Can you possibly run your test with that added detail?  Clock time and the values of kernel, user, and up time over several polling intervals would be very useful.

**Comment by kohnvize** [comment]
Thank you so much for looking at this. I'm implementing the means, using OSHI, to monitor users' machines so that if a user reports any kind of issue with our application; usually a perceived lag or an actual freeze of the UI, this behavior will correspond to some metric that OSHI can report on, such as a spike in network activity or some other application on the affected user's machine grabbing the majority of CPU time.
The output to our logs when these incidents occur are first looked at by various levels of support personnel in call centers, and when necessary, are brought to our (the developers) attention. Thus, I need to be able to log numbers that make sens to the support personnel. That said, I will gather the additional metrics and post here.
Thank you again for creating and maintaining OSHI. I had been using SIGAR, but as you know, that is a difficult API to work with, primarily because of the lack of documentation, and the fact that it is a dead project, although it does provide extremely broad and deep API. Unfortunately, it does not work with Java 9+, so it has to go.

**Comment by dbwiddis** [comment]
You might also find the discussion on #627 enlightening.

**Comment by kohnvize** [comment]
![image](https://user-images.githubusercontent.com/42816761/65336927-378b5900-db95-11e9-9674-2ac006df230c.png)

![image](https://user-images.githubusercontent.com/42816761/65337028-65709d80-db95-11e9-9871-419d13d63277.png)

**Comment by kohnvize** [comment]
Is that what you needed?

**Comment by dbwiddis** [comment]
Yes, although text that I could copy/paste rather than an image would have been preferred. I'll see what I can figure out.

**Comment by kohnvize** [comment]
PID  %CPU %MEM    VSZ       RSS                   Name       tKernel         tUser           tUp
     0  7.6  0.0     8 KiB     8 KiB                 Idle    5272257671             0     695792694
 21596  7.3  0.0   1.8 GiB 113.0 MiB                javaw          2546         93234         13154
     4  0.1  0.0   5.7 MiB    20 KiB               System      42666015             0     695792694
 21788  0.1  0.0   1.5 GiB 152.6 MiB                 java         25906        129078       2784507
  1584  0.0  0.0 701.5 MiB  61.0 MiB                  dwm      22584421      10751156     695788387
  7864  0.0  0.1   3.9 GiB   1.4 GiB              eclipse        407421        895562      69354306
  7752  0.0  0.0   2.2 GiB 180.5 MiB              OUTLOOK       2425406       2345109     346561495
 12828  0.0  0.0 778.5 MiB 105.9 MiB              MsMpEng        793843       2441578     292233995
 13092  0.0  0.0 380.3 MiB   5.7 MiB             ptoneclk       5960843       1259718     695441118
  3304  0.0  0.0 170.5 MiB   5.6 MiB              audiodg       1527312       5614218     695782218

2019-09-20 10:54:11,661|ERROR|MachineMonitor                |Machine Timer                 |HIGH CPU UTILIZATION: Load: 100.0%
TOP TEN PROCESSES IN ORDER OF UTILIZATION: 
   PID  %CPU %MEM    VSZ       RSS                   Name       tKernel         tUser           tUp
     0  7.6  0.0     8 KiB     8 KiB                 Idle    5272257671             0     695794665
 21596  7.3  0.0   1.8 GiB 116.4 MiB                javaw          2828        108000         15126
     4  0.1  0.0   5.7 MiB    20 KiB               System      42666078             0     695794665
 21788  0.1  0.0   1.5 GiB 152.6 MiB                 java         25906        129078       2786478
  1584  0.0  0.0 701.5 MiB  61.0 MiB                  dwm      22584453      10751171     695790358
  7864  0.0  0.1   3.9 GiB   1.4 GiB              eclipse        407437        895578      69356278
  7752  0.0  0.0   2.2 GiB 180.5 MiB              OUTLOOK       2425406       2345109     346563466
 12828  0.0  0.0 778.5 MiB 105.9 MiB              MsMpEng        793843       2441578     292235967
 13092  0.0  0.0 380.3 MiB   5.7 MiB             ptoneclk       5960859       1259718     695443089
  3304  0.0  0.0 170.5 MiB   5.6 MiB              audiodg       1527312       5614218     695784190

2019-09-20 10:54:18,948|ERROR|MachineMonitor                |Machine Timer                 |HIGH CPU UTILIZATION: Load: 100.0%
TOP TEN PROCESSES IN ORDER OF UTILIZATION: 
   PID  %CPU %MEM    VSZ       RSS                   Name       tKernel         tUser           tUp
     0  7.6  0.0     8 KiB     8 KiB                 Idle    5272257718             0     695802180
 21596  7.4  0.0   1.8 GiB 175.1 MiB                javaw          3703        164937         22641
     4  0.1  0.0   5.7 MiB    20 KiB               System      42666171             0     695802180
 21788  0.1  0.0   1.5 GiB 152.7 MiB                 java         25906        129078       2793993
  1584  0.0  0.0 701.5 MiB  60.9 MiB                  dwm      22584484      10751171     695797873
  7864  0.0  0.1   3.9 GiB   1.4 GiB              eclipse        407453        895593      69363793
  7752  0.0  0.0   2.2 GiB 180.4 MiB              OUTLOOK       2425406       2345109     346570981
 12828  0.0  0.0 778.5 MiB 105.9 MiB              MsMpEng        793843       2441578     292243481
 13092  0.0  0.0 380.3 MiB   5.7 MiB             ptoneclk       5960953       1259718     695450604
  3304  0.0  0.0 170.5 MiB   5.6 MiB              audiodg       1527312       5614218     695791705

2019-09-20 10:54:21,590|ERROR|MachineMonitor                |Machine Timer                 |HIGH CPU UTILIZATION: Load: 100.0%
TOP TEN PROCESSES IN ORDER OF UTILIZATION: 
   PID  %CPU %MEM    VSZ       RSS                   Name       tKernel         tUser           tUp
     0  7.6  0.0     8 KiB     8 KiB                 Idle    5272257718             0     695804840
 21596  7.5  0.0   1.8 GiB 176.3 MiB                javaw          3937        185156         25301
     4  0.1  0.0   5.7 MiB    20 KiB               System      42666250             0     695804840
 21788  0.1  0.0   1.5 GiB 152.7 MiB                 java         25906        129078       2796653
  1584  0.0  0.0 701.5 MiB  60.9 MiB                  dwm      22584500      10751171     695800533
  7864  0.0  0.1   3.9 GiB   1.4 GiB              eclipse        407453        895593      69366453
  7752  0.0  0.0   2.2 GiB 180.5 MiB              OUTLOOK       2425406       2345109     346573641
 12828  0.0  0.0 778.5 MiB 106.0 MiB              MsMpEng        793843       2441578     292246142
 13092  0.0  0.0 380.3 MiB   5.7 MiB             ptoneclk       5960968       1259718     695453264
  3304  0.0  0.0 170.5 MiB   5.6 MiB              audiodg       1527312       5614218     695794365

2019-09-20 10:54:29,026|ERROR|MachineMonitor                |Machine Timer                 |HIGH CPU UTILIZATION: Load: 100.0%
TOP TEN PROCESSES IN ORDER OF UTILIZATION: 
   PID  %CPU %MEM    VSZ       RSS                   Name       tKernel         tUser           tUp
     0  7.6  0.0     8 KiB     8 KiB                 Idle    5272257734             0     695811937
 21596  7.5  0.0   1.8 GiB 174.1 MiB                javaw          4531        237500         32398
     4  0.1  0.0   5.7 MiB    20 KiB               System      42666390             0     695811937
 21788  0.1  0.0   1.5 GiB 152.8 MiB                 java         25906        129078       2803750
  1584  0.0  0.0 701.5 MiB  60.9 MiB                  dwm      22584671      10751250     695807630
  7864  0.0  0.1   3.9 GiB   1.4 GiB              eclipse        407468        895609      69373550
  7752  0.0  0.0   2.2 GiB 180.5 MiB              OUTLOOK       2425406       2345109     346580738
 12828  0.0  0.0 778.5 MiB 106.0 MiB              MsMpEng        793843       2441578     292253239
 13092  0.0  0.0 380.3 MiB   5.7 MiB             ptoneclk       5961031       1259734     695460361
  3304  0.0  0.0 170.5 MiB   5.6 MiB              audiodg       1527312       5614218     695801462

**Comment by kohnvize** [comment]
Posted the text...it's just that it doesn't line up well

**Comment by dbwiddis** [comment]
Yes but it parses into Excel oh-so-sweetly. :)

The other option is to link a log.

Based on the tick counts, I don't see a problem in OSHI -- at least as far as the ticks.  The timestamps cover 10 seconds (10,000 ms) -- 9.928 seconds by timestamps.  Uptime is correctly reporting 10175 milliseconds.   In the sample, there's not much idle time recorded but your `javaw` process has consumed 78265 ms of processor time (that's almost 100 percent on an 8-virtual-core system).

That doesn't tell me where the 7.5 comes from.  Are you replicating OSHI's calculation or did you do your own?  Based on the Tick count in this sample I see 78625/10175 = which is 769%.  (Again, this is *nix-style usage where you can get > 100% on multithread processes; divide by # of processors to get the windows results.)

**Comment by kohnvize** [comment]
```
for (int i = 0; i < procs.size(); i++) {
			OSProcess p = procs.get(i);
			oshi.add(String.format(" %5d %4.1f %4.1f %9s %9s %s", p.getProcessID(),
					((double) p.getKernelTime() + (double) p.getUserTime()) / (double) p.getUpTime(),
					(double) p.getResidentSetSize() / (double) memory.getTotal(),
					FormatUtil.formatBytes(p.getVirtualSize()), FormatUtil.formatBytes(p.getResidentSetSize()),
					p.getName()));
		}
```

**Comment by dbwiddis** [comment]
OK, so your 7.5 is a simple ratio, which is 750%.   You are seeing correct results, you are running 8 cores at 93.75% each.  See [this link](https://unix.stackexchange.com/questions/145247/understanding-cpu-while-running-top-command) for an explanation.

**Comment by kohnvize** [comment]
So, in summary, to get the per process CPU utilization like Task Manager, what should I be doing?

**Comment by dbwiddis** [comment]
To summarize, there are two output results to understand with respect to task manager.
- the calculation is cumulative, so it won't jump around like task manager, and will stabilize toward one number with relatively constant load.  To get a result per-polling interval you need to store one result, and subtract off the difference in ticks (kernel+user) and difference in uptime over the user.
- the ticks recorded are total cpu ticks consumed across all cores.  Task manager divides by # of cores so it never exceeds 100% -- on an 8-core system a single maxed out thread will never exceed 12.5%.   If you want to match, you need to also do this division by # of logical processors.

So the calculation would be (kernel difference + user difference)/(uptime difference * # of logical processors), which will be a fraction; multiply by 100 to get a percent.

**Comment by kohnvize** [comment]
Thank you, sir! To use OSHI in our application, distributed to tens of thousands of users, is there any licensing text or some such thing I should add to our application or anything you need?

**Comment by dbwiddis** [comment]
I Am Not A Lawyer, so take this advice for what it is.

OSHI is licensed via MIT so the sole requirement to use it is to include the license header: "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."

It's probably sufficient to include the license file in a zip file distribution, or as a comment in source code if that's publicly available, etc.

**Comment by kohnvize** [comment]
Got it. Yes, we have such a folder. The source code is not available.
Thank you again.

**Comment by dbwiddis** [comment]
One more note on matching task manager outputs -- Task Manager updates on 1-second polling interval, but the clock ticks increment in 1/64 of a second ticks (about 16ms).  On an 8-core system, depending on timing, each process's tick total could be off by up to 8*16ms in either direction (1/8 of a second, so displayed results could be up to 1/4 of a second off reality).  So a 1-second polling interval may be too short.  5 or 10 seconds is a better interval to measure.

**Comment by kohnvize** [comment]
Initially I'm using a 5 second interval, and being of a few percent in either direction is not an issue; being off by a fraction of a second as you're pointing out is of no consequence, but we will profile on the 'minimum system requirements' machine we require for our users. If there is a significant performance hit, then the interval will be increased from there. Thank you

**Comment by dbwiddis** [comment]
Feel free to add your application to the README in the list of software that uses OSHI. :)

**Comment by kohnvize** [comment]
At first glance, those are all open source projects, I believe. Do you keep a list of companies that use your project? I'm with Refinitiv ([refinitiv.com](url)). Our 'mommy' and 'daddy' are Thomson Reuters and Blackstone, respectively.

**Comment by dbwiddis** [comment]
I've built the list by figuring out who imports the project using Maven, which is why so many are open source.  I probably don't know much about commercial software, unless they self report.
