### ISSUE TITLE
Difference between Windows Task Manager Memory value and OSHI

### ISSUE THREAD

**Issue by kohnvize** [oshi/oshi#998]
Hi. I'm trying to determine how to get a similar memory value to Windows task manager when dumping processes:

![image](https://user-images.githubusercontent.com/42816761/65451198-ade5c080-de0c-11e9-94dd-58065910a360.png)

TOP TEN PROCESSES IN ORDER OF UTILIZATION: 
  PID    %CPU   %MEM        VSZ         RSS  NAME
 14532   94.5    2.3     1.8 GiB   379.7 MiB javaw     
  3492    0.3    0.2   342.5 MiB    25.6 MiB Taskmgr   
  1552    0.2    0.7   655.0 MiB   118.3 MiB dwm       
     4    0.2    0.0     8.7 MiB      20 KiB System    
 14596    0.2    1.4     3.6 GiB   232.3 MiB firefox   
 12864    0.1    7.1     3.4 GiB     1.1 GiB eclipse   
  8432    0.1    0.0    79.4 MiB     3.7 MiB WmiPrvSE  
  8324    0.0    0.4     2.7 GiB    68.1 MiB firefox   
  5256    0.0    0.7     1.8 GiB   110.9 MiB OUTLOOK   

This is how I'm getting the value for %MEM:
`100 * (double) p.getResidentSetSize() / (double) info.getHardware().getMemory().getTotal()`

Please tell me what I'm doing wrong. Thank you!
David

**Comment by dbwiddis** [comment]
Assuming you have 16GiB of memory, OSHI's output for percent looks reasonable.  I can't tell from the task manager what the actual values are, however.  Please click the "Details" tab, right-click a column header, choose "select columns" and click all the memory related ones.  Then compare:
- OSHI's output for RSS (Private Working Set Size)
- Task manager output for "Memory (private working set)" (these should match OSHI)
- Task manager output for "Memory (active private working set)"
- Task manger output for "Working set (memory)"

**Comment by kohnvize** [comment]
![image](https://user-images.githubusercontent.com/42816761/65458781-58191480-de1c-11e9-98fb-01d648fd40d8.png)

![image](https://user-images.githubusercontent.com/42816761/65458823-7252f280-de1c-11e9-95dd-7b1c105e219c.png)

TOP TEN PROCESSES IN ORDER OF UTILIZATION: 
  PID    %CPU   %MEM        VSZ         RSS  NAME
 14980   91.4    2.4     1.8 GiB   382.2 MiB javaw     
 14068    0.9    0.1   342.1 MiB    23.7 MiB Taskmgr   
  1552    0.8    0.5   725.2 MiB    87.7 MiB dwm       
 12864    0.4    6.8     3.4 GiB     1.1 GiB eclipse   
  5256    0.3    1.2     1.9 GiB   199.4 MiB OUTLOOK   
     4    0.2    0.0     8.9 MiB      20 KiB System    
 12808    0.1    0.0    78.7 MiB     3.5 MiB WmiPrvSE  
 14596    0.1    1.1     3.6 GiB   185.9 MiB firefox   
 13116    0.1    0.0   392.7 MiB     3.8 MiB ptoneclk

**Comment by dbwiddis** [comment]
This looks correct to me. Take the private working set value:  
- `javaw` 391,468 KiB, divide by 1024 is 382.29 MiB
- `eclipse` 1,131,640 KiB, divide by 1024x1024 is 1.08 GiB.
- `OUTLOOK` 204,232 KiB, divide by 1024 is 199.44 MiB

I'm not sure which of these values is displayed in the "Memory" field on the Processes tab, though.

**Comment by dbwiddis** [comment]
Closing this issue as there have been no further comments and it looks like the question has been answered. Feel free to re-open if you need more feedback.
